	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Public Service (AG)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>

			<p><em>Veterinarian</p>
			<p>Urban Planner</p>
			<p>Recreation Administrator</p>
			<p>Preservationist</p>
			<p>Land Developer</p>
			<p>Park Ranger</p>
			<p>Public Utilities Manager</p>
			<p>Police Officer</p>
			<p>Firefighter</p>
			<p>Recyclist</p>
			<p>Security Guard</p>
			<p>Postal Worker</p>
			<p>Public Transportation Operator</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature</h5>

			<p><em>Horticulturist</p>
			<p>Rangeland Specialist</p>
			<p>Toxicologist</p>
			<p>Surveyor</p>
			<p>Tugboat Captain</p>
			<p>Range Inspector</p>
			<p>Park Inspector</p>
			<p>Organic Farmer</p>
			<p>Survival Trainer</p>
			<p>Grounds Maintenance Supervisor</p>
			<p>Nursery Manager</p>
			<p>Animal Caretaker</em></p>
		</div>
		<div class="col">
			<h5>Environment</h5>

			<p><em>Environmental Lawyer</p>
			<p>Geologist</p>
			<p>Civil Engineer</p>
			<p>Pollution Engineer</p>
			<p>Environmentalist</p>
			<p>Waste Management Technician</p>
			<p>Water Treatment Plant Operator</p>
			<p>Power Plant Operator</p>
			<p>Forestry Technician</p>
			<p>Forestry Worker</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>

			<p><em>Veterinarian</p>
			<p>Urban Planner</p>
			<p>Recreation Administrator</p>
			<p>Preservationist</p>
			<p>Land Developer</p>
			<p>Park Ranger</p>
			<p>Public Utilities Manager</p>
			<p>Police Officer</p>
			<p>Firefighter</p>
			<p>Recyclist</p>
			<p>Security Guard</p>
			<p>Postal Worker</p>
			<p>Public Transportation Operator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature</h5>

			<p><em>Horticulturist</p>
			<p>Rangeland Specialist</p>
			<p>Toxicologist</p>
			<p>Surveyor</p>
			<p>Tugboat Captain</p>
			<p>Range Inspector</p>
			<p>Park Inspector</p>
			<p>Organic Farmer</p>
			<p>Survival Trainer</p>
			<p>Grounds Maintenance Supervisor</p>
			<p>Nursery Manager</p>
			<p>Animal Caretaker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Environment</h5>

			<p><em>Environmental Lawyer</p>
			<p>Geologist</p>
			<p>Civil Engineer</p>
			<p>Pollution Engineer</p>
			<p>Environmentalist</p>
			<p>Waste Management Technician</p>
			<p>Water Treatment Plant Operator</p>
			<p>Power Plant Operator</p>
			<p>Forestry Technician</p>
			<p>Forestry Worker</em></p>
		</div>
	</div>
	</div>

