

<div class="row">
	<div class="col-md-12">
		<p class="lead">Outdoor paired with Arts/Communications (AB)</p>
		
		<div class="inter">
		
		<p>An "AB" person loves to work in the open environment in settings
		such as nature (nature photographer), entertainment (marching band),
		recreation (tennis coach), animals (wildlife guide), and land
		improvements (landscaper) and is able to communicate well. The
		word "communicate" means that you can get your ideas, thoughts, or
		feelings understood by others easily and clearly through speaking or
		writing. With this pattern, you will probably want to share your
		interest in nature, the environment, or animals with others through
		your communications skills.</p>
		
		<p>Often, an "AB" person communicates well through "visual media"
		using pictures, charts, graphs, or diagrams to help others
		understand. No matter which method you decide to use to communicate,
		others will probably be able to understand you.</p>
		
		<p>Most occupations in this pairing require a bachelor's degree or
		specialized training. Higher levels of education such as a master's
		degree or a Ph.D. are valuable to certain occupations in this
		pattern.</p>

		<p><strong>Courses you may want to consider taking in high school
		and beyond (in addition to English & Math):</strong><br />
		Any courses that deal with communication, visual media, outdoors,
		and nature will probably interest you and could help prepare you for
		possible career opportunities.</p>

		<table cellpadding="10" cellspacing="10" class="side">
			<tr>
				<td>
					Computer Technology<br />
					Public Relations<br />
					Computer Sciences<br />
					Environmental Science
				</td>
				<td>
					Advertising<br />
					Health/Nutrition<br />
					World Language<br />
					Industrial Technology
				</td>
				<td>
					Agriculture<br />
					Biology<br />
					Psychology<br />
					Sociology
				</td>
				<td>
					Art/Graphic Arts<br />
					Music<br />
					Photography<br />
					Marketing
				</td>
				<td>
					Physical Education<br />
					Economics<br />
					Communications<br />
					Home Economics
				</td>
			</tr>
		</table>

		<p><strong>Extracurricular/volunteer activities or organizations you
		may find interesting:</strong><br />
		If you have time for after-school activities or part-time jobs, make
		them count. You will probably enjoy any club or activity that
		involves communicating with others and/or sharing a love for
		nature.</p>

		<table cellpadding="10" cellspacing="10" class="side">
			<tr valign="top">
				<td>
					Newspaper/Yearbook<br />
					Habitat for Humanity<br />
					Future Farmers of America<br />
					Audio-Visual Services
				</td>
				<td>
					Athletics<br />
					Drama/Theatre<br />
					Photography Club<br />
					Language Club
				</td>
				<td>
					Scouts<br />
					Band/Chorus<br />
					Debate Team<br />
					Adopt-a-Mile
				</td>
				<td>
					Parks/Recreation<br />
					Pen Pals<br />
					Radio/TV activities<br />
					Animal Care
				</td>
			</tr>
		</table>

		<p><strong>Workplaces that you may wish to consider for a part-time
		job:</strong><br />
		These workplaces may offer opportunities to help you decide on a
		career.</p>

		<table cellpadding="10" cellspacing="10" class="side">
			<tr valign="top">
				<td>
					Advertising Agencies<br />
					Printing Companies<br />
					Graphic Design Firms<br />
					Photography Studios
				</td>
				<td>
					Lawn Care Services<br />
					Landscaping Companies<br />
					TV/Radio Studios<br>
					Theaters
				</td>
				<td>
					Libraries<br />
					Farms<br />
					Lumberyards
				</td>
				<td>
					Newspaper Publishing Firms<br />
					Parks/Recreation Depart.<br />
					Photographic Laboratories
				</td>
			</tr>
		</table>
		
	</div>
		
		<p><strong>Here are some career possibilities for you to explore:</strong></p>
		<div style="width: 100%; background-color: #1abd9c; color: white;">
			<p style="text-align: center; padding: 3px 0;"><strong>AB Career Possibilities</strong></p>
		</div>
				<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
					<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
				</div>
			</div>
		</div>
	
		<div class="d-none d-sm-none d-md-block">
		<div class="row">
			<div class="col-auto">
				<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
					<table>
						<tr>
							<td style="text-align: center;">
								<br /><br />
								<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
								<br /><br /><br />
								Education
								<br />
								or
								<br />
								Training
								<br />
								Required
								<br /><br /><br />
								<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
								<br /><br /><br /><br />
							</td>
						</tr>
					</table>
				</div>
			</div>
	<div class="col" style="margin-bottom: 20px;">
		<h5>Arts/Communications</h5>
		<p><em>Environmental Lawyer</p>
		<p>Public Administrator</p>
		<p>Foreign Correspondent</p>
		<p>Parks & Recreation</p>
		<p>Public Relations Specialist</p>
		<p>Recreation\Coach</p>
		<p>Cartoonist</p>
		<p>Nature Writer</p>
		<p>Documentary Writer</p>
		<p>Nature Photographer</p>
		<p>Fund Raiser</em></p>
	</div>
	<div class="col" style="margin-bottom: 20px;">
		<h5>Out of Doors</h5>
		<p><em>Nature Scientist
			<ul>
				<li>Botanist</li>
				<li>Zoologist</li>
			</ul>
			</p>
		<p>Agricultural Scientist</p>
		<p>Geologist</p>
		<p>Petrologist</p>
		<p>Hydrologist</p>
		<p>Athletic Coach</p>
		<p>Professional Athlete</p>
		<p>Soil Technician</p>
		<p>Parks and Recreation Manager</p>
		<p>Dog Trainer</em></p>
	</div>
	<div class="col">
		<h5>Designing/Engineering</h5>

		<p><em>Designing/Engineering</p>
		<p>Architect</p>
		<p>Urban Planner</p>
		<p>Engineer/Designer</p>
		<p>Pilot<br />
		<p>Meteorologist</p>
		<p>Stevedore</p>
		<p>Plumber</p>
		<p>Sculptor (concrete, lawn)</p>
		<p>Pest Control Worker</p>
		<p>Developer
			<ul>
				<li>Residential</li>
				<li>Commercial</li>
				<li>Recreational</li>
			</ul>
		</em></p>
	</div>
</div>
</div>


<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>

	<div class="col" style="margin-bottom: 20px;">
		<h5>Arts/Communications</h5>
		<p><em>Environmental Lawyer</p>
		<p>Public Administrator</p>
		<p>Foreign Correspondent</p>
		<p>Parks & Recreation</p>
		<p>Public Relations Specialist</p>
		<p>Recreation\Coach</p>
		<p>Cartoonist</p>
		<p>Nature Writer</p>
		<p>Documentary Writer</p>
		<p>Nature Photographer</p>
		<p>Fund Raiser</em></p>
	</div>
</div>
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
	<div class="col" style="margin-bottom: 20px;">
		<h5>Out of Doors</h5>
		<p><em>Nature Scientist
			<ul>
				<li>Botanist</li>
				<li>Zoologist</li>
			</ul>
			</p>
		<p>Agricultural Scientist</p>
		<p>Geologist</p>
		<p>Petrologist</p>
		<p>Hydrologist</p>
		<p>Athletic Coach</p>
		<p>Professional Athlete</p>
		<p>Soil Technician</p>
		<p>Parks and Recreation Manager</p>
		<p>Dog Trainer</em></p>
	</div>
</div>
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
	<div class="col">
		<h5>Designing/Engineering</h5>

		<p><em>Designing/Engineering</p>
		<p>Architect</p>
		<p>Urban Planner</p>
		<p>Engineer/Designer</p>
		<p>Pilot<br />
		<p>Meteorologist</p>
		<p>Stevedore</p>
		<p>Plumber</p>
		<p>Sculptor (concrete, lawn)</p>
		<p>Pest Control Worker</p>
		<p>Developer
			<ul>
				<li>Residential</li>
				<li>Commercial</li>
				<li>Recreational</li>
			</ul>
		</em></p>
	</div>
</div>
</div>

