

	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Arts/Communications (AB)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AB Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>

	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Arts/Communications</h5>
			<p><em>Environmental Lawyer</p>
			<p>Public Administrator</p>
			<p>Foreign Correspondent</p>
			<p>Parks & Recreation</p>
			<p>Public Relations Specialist</p>
			<p>Recreation\Coach</p>
			<p>Cartoonist</p>
			<p>Nature Writer</p>
			<p>Documentary Writer</p>
			<p>Nature Photographer</p>
			<p>Fund Raiser</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Out of Doors</h5>
			<p><em>Nature Scientist
				<ul>
					<li>Botanist</li>
					<li>Zoologist</li>
				</ul>
				</p>
			<p>Agricultural Scientist</p>
			<p>Geologist</p>
			<p>Petrologist</p>
			<p>Hydrologist</p>
			<p>Athletic Coach</p>
			<p>Professional Athlete</p>
			<p>Soil Technician</p>
			<p>Parks and Recreation Manager</p>
			<p>Dog Trainer</em></p>
		</div>
		<div class="col">
			<h5>Designing/Engineering</h5>

			<p><em>Designing/Engineering</p>
			<p>Architect</p>
			<p>Urban Planner</p>
			<p>Engineer/Designer</p>
			<p>Pilot<br />
			<p>Meteorologist</p>
			<p>Stevedore</p>
			<p>Plumber</p>
			<p>Sculptor (concrete, lawn)</p>
			<p>Pest Control Worker</p>
			<p>Developer
				<ul>
					<li>Residential</li>
					<li>Commercial</li>
					<li>Recreational</li>
				</ul>
			</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Arts/Communications</h5>
			<p><em>Environmental Lawyer</p>
			<p>Public Administrator</p>
			<p>Foreign Correspondent</p>
			<p>Parks & Recreation</p>
			<p>Public Relations Specialist</p>
			<p>Recreation\Coach</p>
			<p>Cartoonist</p>
			<p>Nature Writer</p>
			<p>Documentary Writer</p>
			<p>Nature Photographer</p>
			<p>Fund Raiser</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Out of Doors</h5>
			<p><em>Nature Scientist
				<ul>
					<li>Botanist</li>
					<li>Zoologist</li>
				</ul>
				</p>
			<p>Agricultural Scientist</p>
			<p>Geologist</p>
			<p>Petrologist</p>
			<p>Hydrologist</p>
			<p>Athletic Coach</p>
			<p>Professional Athlete</p>
			<p>Soil Technician</p>
			<p>Parks and Recreation Manager</p>
			<p>Dog Trainer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Designing/Engineering</h5>

			<p><em>Designing/Engineering</p>
			<p>Architect</p>
			<p>Urban Planner</p>
			<p>Engineer/Designer</p>
			<p>Pilot<br />
			<p>Meteorologist</p>
			<p>Stevedore</p>
			<p>Plumber</p>
			<p>Sculptor (concrete, lawn)</p>
			<p>Pest Control Worker</p>
			<p>Developer
				<ul>
					<li>Residential</li>
					<li>Commercial</li>
					<li>Recreational</li>
				</ul>
			</em></p>
		</div>
	</div>
	</div>
	
