	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Business/Management (AC)</p>
			
			<div class="inter">
				
			<p>Your high score in category "A" shows that you are a person who
			might like an outdoor job that allows you to work with your hands.
			Your high score in "C" shows that you may have an interest in
			working with others.  You probably would like jobs in business,
			sales, and management.  You may like jobs that require that you
			negotiate.  It is likely that you work well with people.  You may be
			happiest in an occupation that includes plenty of interactions with
			different people.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree. It is helpful to have a master's degree or Ph.D. if you hope
			to work in some of these occupations.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			Any courses that deal with the outdoors, nature, and business will
			likely interest you and could help prepare you for possible career
			opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting<br />
						Botany<br />
						Psychology
					</td>
					<td>
						Shop & Industrial Arts<br />
						Computer Sciences<br />
						Marketing & Advertising
					</td>
					<td>
						Agriculture<br />
						Business Law<br />
						Economics
					</td>
					<td>
						Physical Education<br />
						Public Relations<br />
						Speech & Communications
					</td>
					<td>
						Biology<br />
						Business Math<br />
						Sociology
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations you
			may find interesting:</strong><br />
			If you have time for after school activities or part-time jobs, make
			them count. You will probably enjoy any club or activity where you
			can share your love of nature and use your business sense.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Animal Care<br />
						Yearbook Staff<br />
						Adopt-a-Mile
					</td>
					<td>
						Habitat for Humanity<br />
						Community Volunteer<br />
						Computer Activities
					</td>
					<td>
						Future Farmers of America<br />
						Student Exchange Program<br />
						Future Business Leaders
					</td>
					<td>
						Parks & Recreation<br />
						Class/Club Officer<br />
						Junior Achievement
					</td>
					<td>
						Marketing<br />
						Athletics<br />
						Scouts
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you might wish to consider for a part-
			time job:</strong><br />
			These workplaces may offer opportunities to help you decide what you
			want to do as an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising Firms<br />
						Park Services<br />
						Lumberyards<br />
						TV/Radio Studios
					</td>
					<td>
						Landscaping Firms<br />
						Newspaper Publishing Firms<br />
						Graphic Design Firms<br />
					</td>
					<td>
						Printing Companies<br />
						Lawn Care Services<br />
						Delivery Services<br />
					</td>
					<td>
						Theaters<br />
						Farms<br />
						Nurseries<br />
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AC Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business</h5>
			<p><em>Agricultural Economist</p>
			<p>Museum Director</p>
			<p>Agribusiness Consultant</p>
			<p>Range Manager</p>
			<p>Union Leader</p>
			<p>Farm Broker</p>
			<p>Factory Manager</p>
			<p>Warehouse Supervisor</p>
			<p>Auctioneer</p>
			<p>Pet Shop Owner/Worker</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Outdoor Management</h5>
			<p><em>Nature Scientist
				<ul>
					<li>Horticulturist</li>
				</ul>
				</p>
			<p>Wildlife Manager</p>
			<p>Recreation Administrator</p>
			<p>Resort Manager</p>
			<p>Farm Manager</p>
			<p>Rancher</p>
			<p>Orchard Manager</p>
			<p>County Fair Organizer</p>
			<p>Nursery Manager/Worker</em></p>
		</div>
		<div class="col">
			<h5>Environment</h5>
			<p><em>Regional Planner</p>
			<p>Environmentalist</p>
			<p>Environmental Health Inspector</p>
			<p>Environmental Risk Manager</p>
			<p>Wetlands Manager</p>
			<p>Safety/Traffic Engineer</p>
			<p>Logging Supervisor</p>
			<p>Water Quality Technologist</p>
			<p>Agricultural Technician</p>
			<p>Waste Management Technician</p>
			<p>Forestry Technician</em></p>
		</div>
	</div>
	</div>

	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business</h5>
			<p><em>Agricultural Economist<br />
			<p><em>Agricultural Economist</p>
			<p>Museum Director</p>
			<p>Agribusiness Consultant</p>
			<p>Range Manager</p>
			<p>Union Leader</p>
			<p>Farm Broker</p>
			<p>Factory Manager</p>
			<p>Warehouse Supervisor</p>
			<p>Auctioneer</p>
			<p>Pet Shop Owner/Worker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Outdoor Management</h5>
			<p><em>Nature Scientist
				<ul>
					<li>Horticulturist</li>
				</ul>
				</p>
			<p>Wildlife Manager</p>
			<p>Recreation Administrator</p>
			<p>Resort Manager</p>
			<p>Farm Manager</p>
			<p>Rancher</p>
			<p>Orchard Manager</p>
			<p>County Fair Organizer</p>
			<p>Nursery Manager/Worker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Environment</h5>
			<em><p>Regional Planner</p>
			<p>Environmentalist</p>
			<p>Environmental Health Inspector</p>
			<p>Environmental Risk Manager</p>
			<p>Wetlands Manager</p>
			<p>Safety/Traffic Engineer</p>
			<p>Logging Supervisor</p>
			<p>Water Quality Technologist</p>
			<p>Agricultural Technician</p>
			<p>Waste Management Technician</p>
			<p>Forestry Technician</p></em>
		</div></em>
	</div>
	</div>

