	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Clerical/Administrative (AD)</p>
			
			<div class="inter">
			
			<p>If you had a high score in the "A" and "D" categories, you are
			probably a hard worker who likes to do things in a structured way.
			You also prefer to know what is expected of you and have a set
			procedure for tasks.  You do well with order, paperwork, directions
			and time-oriented work details. You learn best by experience and
			like to know the facts. You want to know exactly what will happen.
			You may want to look for careers that will allow you to combine your
			interest in the outdoors with your ability to get things done.</p>
			<p>Most occupations in "AD" combination require at least a
			bachelor's degree. Many require training through a vocational or
			technical program.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			You should consider taking life science courses that will continue
			to develop your interest in and understanding of the outdoors. Some
			business courses are very practical and may help you develop your
			organizational skills.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
							Computer Science<br />
							Agriculture<br />
							Business Technology
						</td>
						<td>
							Economics<br />
							Bookkeeping<br />
							Botany<br />
						</td>
						<td>
							Industrial Technology<br />
							Environmental Science<br />
							Office Administration
						</td>
						<td>
							Physical Education<br />
							Business Education<br />
							Health/Nutrition
						</td>
						<td>
							Biology<br />
							Graphic Arts<br />
							Geography
						</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations you
			may find interesting:</strong><br />
			Experience is an important thing! If you are looking for an
			interesting activity, you should probably think about organizations
			that focus on nature and the environment. Don't forget to find a
			place where you can show how dependable you are.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Adopt-a-Mile<br />
						Habitat for Humanity<br />
						Library Assistant<br />
						Future Farmers of America
					</td>
					<td>
						Athletics<br />
						Office Assistant<br />
						Newspaper/Yearbook<br />
						Future Business Leaders
					</td>
					<td>
						Scouts<br />
						Teaching Assistant<br />
						Class Officer
					</td>
					<td>
						Parks/Recreation<br />
						Audio/Visual Services<br />
						Community Volunteer
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These workplaces may offer opportunities to help you decide and
			prepare you for what you want to do as an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting Firms<br />
						Repair Services
					</td>
					<td>
						Landscaping Firms<br />
						Farms
					</td>
					<td>
						Park Services<br />
						Lumberyards
					</td>
					<td>
						Clerical & Filing Offices<br />
						Lawn Care Services
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AD Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>

	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Outdoor Technical Environments</h5>
			<p><em>Air Traffic Controller</p>
			<p>Army Officer</p>
			<p>Community Relations Manager</p>
			<p>Military Enlisted Personnel</p>
			<p>Aerial Photographer</p>
			<p>Safety Engineer</p>
			<p>Travel Agent</p>
			<p>Air Quality Control Technician</p>
			<p>Telephone Cable Installer</p>
			<p>Highway Maintenance</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature/Office Environments</h5>
			<p><em>Administrative Assistant</p>
			<p>Land & Water Conservationist</p>
			<p>Title Searcher</p>
			<p>Tour Guide</p>
			<p>Receptionist</p>
			<p>Ticket Agent</p>
			<p>Wildlife Tours Agent</em></p>
		</div>
		<div class="col">
			<h5>Nature/Animal Environments</h5>
			<p><em>Livestock Auction Coordinator</p>
			<p>Veterinary Clinic/Hospital
				<ul>
					<li>Technician</li>
					<li>Office Manager</li>
					<li>Administrative Assistant</li>
					<li>Records/Billing Clerk</li>
				</ul></p>
			<p>Secretary- Zoo, Farm, Ranch</p>
			<p>Pet Store Clerk/Caretaker</p>
			<p>Pet Sitter</em></p>
		</div>
		</div>
	</div>


	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Outdoor Technical Environments</h5>
			<p><em>Air Traffic Controller</p>
			<p>Army Officer</p>
			<p>Community Relations Manager</p>
			<p>Military Enlisted Personnel</p>
			<p>Aerial Photographer</p>
			<p>Safety Engineer</p>
			<p>Travel Agent</p>
			<p>Air Quality Control Technician</p>
			<p>Telephone Cable Installer</p>
			<p>Highway Maintenance</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature/Office Environments</h5>
			<p><em>Administrative Assistant</p>
			<p>Land & Water Conservationist</p>
			<p>Title Searcher</p>
			<p>Tour Guide</p>
			<p>Receptionist</p>
			<p>Ticket Agent</p>
			<p>Wildlife Tours Agent</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>>Nature/Animal Environments</h5>
			<p><em>Livestock Auction Coordinator</p>
			<p>Veterinary Clinic/Hospital
				<ul>
					<li>Technician</li>
					<li>Office Manager</li>
					<li>Administrative Assistant</li>
					<li>Records/Billing Clerk</li>
				</ul></p>
			<p>Secretary- Zoo, Farm, Ranch</p>
			<p>Pet Store Clerk/Caretaker</p>
			<p>Pet Sitter</em></p>
		</div>
	</div>
	</div>

