	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Clerical/Administrative (AD)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AD Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>

	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Outdoor Technical Environments</h5>
			<p><em>Air Traffic Controller</p>
			<p>Army Officer</p>
			<p>Community Relations Manager</p>
			<p>Military Enlisted Personnel</p>
			<p>Aerial Photographer</p>
			<p>Safety Engineer</p>
			<p>Travel Agent</p>
			<p>Air Quality Control Technician</p>
			<p>Telephone Cable Installer</p>
			<p>Highway Maintenance</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature/Office Environments</h5>
			<p><em>Administrative Assistant</p>
			<p>Land & Water Conservationist</p>
			<p>Title Searcher</p>
			<p>Tour Guide</p>
			<p>Receptionist</p>
			<p>Ticket Agent</p>
			<p>Wildlife Tours Agent</em></p>
		</div>
		<div class="col">
			<h5>Nature/Animal Environments</h5>
			<p><em>Livestock Auction Coordinator</p>
			<p>Veterinary Clinic/Hospital
				<ul>
					<li>Technician</li>
					<li>Office Manager</li>
					<li>Administrative Assistant</li>
					<li>Records/Billing Clerk</li>
				</ul></p>
			<p>Secretary- Zoo, Farm, Ranch</p>
			<p>Pet Store Clerk/Caretaker</p>
			<p>Pet Sitter</em></p>
		</div>
		</div>
	</div>


	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Outdoor Technical Environments</h5>
			<p><em>Air Traffic Controller</p>
			<p>Army Officer</p>
			<p>Community Relations Manager</p>
			<p>Military Enlisted Personnel</p>
			<p>Aerial Photographer</p>
			<p>Safety Engineer</p>
			<p>Travel Agent</p>
			<p>Air Quality Control Technician</p>
			<p>Telephone Cable Installer</p>
			<p>Highway Maintenance</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature/Office Environments</h5>
			<p><em>Administrative Assistant</p>
			<p>Land & Water Conservationist</p>
			<p>Title Searcher</p>
			<p>Tour Guide</p>
			<p>Receptionist</p>
			<p>Ticket Agent</p>
			<p>Wildlife Tours Agent</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>>Nature/Animal Environments</h5>
			<p><em>Livestock Auction Coordinator</p>
			<p>Veterinary Clinic/Hospital
				<ul>
					<li>Technician</li>
					<li>Office Manager</li>
					<li>Administrative Assistant</li>
					<li>Records/Billing Clerk</li>
				</ul></p>
			<p>Secretary- Zoo, Farm, Ranch</p>
			<p>Pet Store Clerk/Caretaker</p>
			<p>Pet Sitter</em></p>
		</div>
	</div>
	</div>

