	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Protective/Military Service (AE)</span>
				
			<div class="inter">
				
					<p>If you scored high in categories "A" and "E," you have a strong
				interest in nature and you are an adventurous spirit. You like to
				explore new possibilities.  You also know how to  get things done.
				You are willing to be a leader and to get your hands dirty.</p>
				<p>You need specialized training after high school for many of the
				occupations in this pairing.  For some you will need college level
				courses.  For others on-the-job training will be sufficient.</p>
				<p><strong>Courses you may want to consider taking in high school
				and beyond (in addition to English & Math):</strong><br />
				You should take courses that will help you to learn about the
				environment. Life sciences and earth sciences courses will be
				especially valuable.</p>

				<table cellpadding="10" cellspacing="10" class="side">
					<tr valign="top">
						<td>
							Agriculture<br />
							Political Science<br />
							Physical Education<br />
							Telecommunications
						</td>
						<td>
							Business Law<br />
							Biology<br />
							Business Ed.<br />
							Physics
						</td>
						<td>
							Graphic Arts<br />
							Civics/Government<br />
							Economics<br />
							Sociology
						</td>
						<td>
							Criminal Justice<br />
							Geography<br />
							Computer Sciences<br />
							Health/Nutrition
						</td>
						<td>
							Computer Information Systems<br />
							History<br />
							Language (Spanish, etc.)<br />
							Industrial Technology
						</td>
					</tr>
				</table>

				<p><strong>Extracurricular/ volunteer activities or organizations
				that you may find interesting:</strong><br />
				If you have time for after school activities or part-time jobs, make
				them count. You will probably enjoy any club or activity that
				involves working with others and/or sharing a love for nature.</p>

				<table cellpadding="10" cellspacing="10" class="side">
					<tr valign="top">
						<td>
							Adopt-a-Mile<br />
							Habitat for Humanity<br />
							Band
						</td>
						<td>
							Athletics<br />
							ROTC<br />
							Martial Arts
						</td>
						<td>
							Scouts<br />
							Flight Training<br />
							Parks/Recreation
						</td>
						<td>
							Camp Activities<br />
							Future Farmers of America<br />
							Language Club
						</td>
					</tr>
				</table>

				<p><strong>Workplaces that you may wish to consider for a part-time
				job:</strong><br />
				These places may offer valuable opportunities to help you decide
				what you want to do when you are an adult.</p>

				<table cellpadding="10" cellspacing="10" class="side">
					<tr valign="top">
						<td>
							Camp Counseling<br />
							Landscaping/Lawn Care<br />
							Construction Sites
						</td>
						<td>
							Farming<br />
							Lumberyards<br />
							Parks/Recreation
						</td>
						<td>
							Life Guarding<br />
							Veterinary Offices
						</td>
						<td>
							Surveying Companies<br />
							Environmental Agencies
						</td>
					</tr>
				</table>
				
			</div>
				
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AE Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>

	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
				<h5>Military</h5>
				<p><em>Pilot</p>
				<p>Intelligence Specialist</p>
				<p>Graphic Information Specialist</p>
				<p>Aircraft Launch & Recovery Specialist</p>
				<p>Artillery Crew Member</p>
				<p>Military Police</p>
				<p>Platoon/Squad Leader</p>
				<p>Mapping Technician</p>
				<p>Explosive Blasting Specialist</em></p>
			</td>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental</h5>
			<p><em>Nature Scientist
				<ul>
					<li>Geologist</li>
					<li>Marine Biologist</li>
				</ul></p>
			<p>Agricultural Scientist</p>
			<p>Marine Surveyor</p>
			<p>Wildlife Manager</p>
			<p>Park Ranger</p>
			<p>Waste Management Technician</p>
			<p>Cartographer Technician</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Outdoor Service</h5>
			<p><em>Homeland Security Officer</p>
			<p>Immigration Specialist</p>
			<p>Public Safety Officer</p>
			<p>Construction Equipment Operator</p>
			<p>Firefighter</p>
			<p>Heavy Equipment Mechanic</p>
			<p>Security Guard</p>
			<p>Construction Worker</p>
			<p>Groundskeeper</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Military</h5>
			<p><em>Pilot</p>
			<p>Intelligence Specialist</p>
			<p>Graphic Information Specialist</p>
			<p>Aircraft Launch & Recovery Specialist</p>
			<p>Artillery Crew Member</p>
			<p>Military Police</p>
			<p>Platoon/Squad Leader</p>
			<p>Mapping Technician</p>
			<p>Explosive Blasting Specialist</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental</h5>
			<p><em>Nature Scientist
				<ul>
					<li>Geologist</li>
					<li>Marine Biologist</li>
				</ul></p>
			<p>Agricultural Scientist</p>
			<p>Marine Surveyor</p>
			<p>Wildlife Manager</p>
			<p>Park Ranger</p>
			<p>Waste Management Technician</p>
			<p>Cartographer Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Outdoor Service</h5>
			<p><em>Homeland Security Officer</p>
			<p>Immigration Specialist</p>
			<p>Public Safety Officer</p>
			<p>Construction Equipment Operator</p>
			<p>Firefighter</p>
			<p>Heavy Equipment Mechanic</p>
			<p>Security Guard</p>
			<p>Construction Worker</p>
			<p>Groundskeeper</em></p>
		</div>
	</div>
	</div>

