	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Technology (AF)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AF Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Biotechnology<br />Environmental</h5>

			<p><em>Veterinarian</p>
			<p>Aquatic Biologist</p>
			<p>Ecologist</p>
			<p>Geneticist</p>
			<p>Microbiologist</p>
			<p>Physiologist</p>
			<p>Oceanographer</p>
			<p>Seismologist</p>
			<p>Stratigrapher</p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Information</h5>
			<p><em>Urban Planner</p>
			<p>Systems Analyst</p>
			<p>Computer
				<ul>
					<li>Software Engineer</li>
					<li>Programmer</li>
					<li>Technician</li>
					<li>Systems Programmer</li>
				</ul></p>
			<p>Information Systems Mgr.</p>
			<p>Applications Programmer</p>
			<p>User Support Analyst</p>
			<p>Recording Engineer</em></p>
		</div>
		<div class="col">
			<h5>Engineering</h5>

			<p><em>Engineer</p>
			<p>Electrical Engineer</p>
			<p>Mechanical Engineer</p>
			<p>Civil Engineer</p>
			<p>Chemical Engineer</p>
			<p>Industrial Engineer</p>
			<p>Metallurgical Engineer</p>
			<p>Materials Engineer</p>
			<p>Medical Scientist</p>
			<p>Waste Management</p>
			<p>Water Quality Technologist</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Biotechnology<br />Environmental</h5>

			<p><em>Veterinarian</p>
			<p>Aquatic Biologist</p>
			<p>Ecologist</p>
			<p>Geneticist</p>
			<p>Microbiologist</p>
			<p>Physiologist</p>
			<p>Oceanographer</p>
			<p>Seismologist</p>
			<p>Stratigrapher</p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Information</h5>
			<p><em>Urban Planner</p>
			<p>Systems Analyst</p>
			<p>Computer
				<ul>
					<li>Software Engineer</li>
					<li>Programmer</li>
					<li>Technician</li>
					<li>Systems Programmer</li>
				</ul></p>
			<p>Information Systems Mgr.</p>
			<p>Applications Programmer</p>
			<p>User Support Analyst</p>
			<p>Recording Engineer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Engineering</h5>

			<p>Electrical Engineer</p>
			<p>Mechanical Engineer</p>
			<p>Civil Engineer</p>
			<p>Chemical Engineer</p>
			<p>Industrial Engineer</p>
			<p>Metallurgical Engineer</p>
			<p>Materials Engineer</p>
			<p>Medical Scientist</p>
			<p>Waste Management</p>
			<p>Water Quality Technologist</em></p>
		</div>
	</div>
	</div>
