	<div class="row">
		<div class="col-sm-12">
			<p class="lead">Outdoor paired with Technology (AF)</p>
			
			<div class="inter">
			
			<p>With an "AF" interest, you will want to combine your interest in
			open-air occupations with your interest in technologies. You like to
			conduct research, employ change and apply what you know,  to work
			settings of the technologies and outdoors.</p>
			<p>Many of the occupations in this pairing require that you have
			specialized and/or technical training after high school. Many
			require college degrees or college level courses.</p>
			<p><strong>Courses you may want to take in high school and beyond
			(in addition to English & Math):</strong><br />
			In high school you should take courses that allow you to continue
			to learn about the environment. Life science and earth science
			courses will teach you many interesting things about nature.  Look
			for opportunities to use technology to discover new things.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr>
					<td>
						Agriculture<br />
						Environmental Sciences<br />
						Health/Nutrition<br />
						Computer Sciences
					</td>
					<td>
						Computer Programming<br />
						Graphic Art/Drafting<br />
						Industrial Technology<br />
						Health Occupations
					</td>
					<td>
						Physical Education<br />
						Business Education<br />
						Technology Education
					</td>
					<td>
						Biology<br />
						Business Math<br />
						Telecommunications
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			that you may find interesting:</strong><br />
			If you have time for after-school activities or part-time jobs, make
			them count. You will especially enjoy any club or activity that
			involves working with some sort of equipment and/or sharing a love
			for nature.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Adopt-a-Mile<br />
						Habitat for Humanity<br />
						Library Assistant
					</td>
					<td>
						Athletics<br />
						Audio/visual Services<br />
						Newspaper/Yearbook
					</td>
					<td>
						Parks/Recreation<br />
						Chess Club<br />
						Computer Club<br />
					</td>
					<td>
						Future Farmers of America<br />
						Math/Science Clubs<br />
						ROTC<br />
						Scouts
					</td>
				</tr>
			</table>

			<p>	<strong>Workplaces that you may wish to consider for a part-
			time job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Appliance Repair<br />
						Landscaping<br />
						Camp Counseling
					</td>
					<td>
						Farming<br />
						Logging<br />
						Lumberyards
					</td>
					<td>
						Life Guarding<br />
						Delivery Services
					</td>
					<td>
						Park Services<br />
						Lawn Care
					</td>
				</tr>
			</table>
			
			</div>
			
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AF Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Biotechnology<br />Environmental</h5>
			<em><p>Veterinarian</p>
			<p>Aquatic Biologist</p>
			<p>Ecologist</p>
			<p>Geneticist</p>
			<p>Microbiologist</p>
			<p>Physiologist</p>
			<p>Oceanographer</p>
			<p>Seismologist</p>
			<p>Stratigrapher</p></em>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Information</h5>
			<em><p>Urban Planner</p>
			<p>Systems Analyst</p>
			<p>Computer
				<ul>
					<li>Software Engineer</li>
					<li>Programmer</li>
					<li>Technician</li>
					<li>Systems Programmer</li>
				</ul></p>
			<p>Information Systems Mgr.</p>
			<p>Applications Programmer</p>
			<p>User Support Analyst</p>
			<p>Recording Engineer</p></em>
		</div>
		<div class="col">
			<h5>Engineering</h5>
			<em><p>Engineer</p>
			<p>Electrical Engineer</p>
			<p>Mechanical Engineer</p>
			<p>Civil Engineer</p>
			<p>Chemical Engineer</p>
			<p>Industrial Engineer</p>
			<p>Metallurgical Engineer</p>
			<p>Materials Engineer</p>
			<p>Medical Scientist</p>
			<p>Waste Management</p>
			<p>Water Quality Technologist</p></em>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Biotechnology<br />Environmental</h5>

			<p><em>Veterinarian</p>
			<p>Aquatic Biologist</p>
			<p>Ecologist</p>
			<p>Geneticist</p>
			<p>Microbiologist</p>
			<p>Physiologist</p>
			<p>Oceanographer</p>
			<p>Seismologist</p>
			<p>Stratigrapher</p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Information</h5>
			<p><em>Urban Planner</p>
			<p>Systems Analyst</p>
			<p>Computer
				<ul>
					<li>Software Engineer</li>
					<li>Programmer</li>
					<li>Technician</li>
					<li>Systems Programmer</li>
				</ul></p>
			<p>Information Systems Mgr.</p>
			<p>Applications Programmer</p>
			<p>User Support Analyst</p>
			<p>Recording Engineer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Engineering</h5>

			<p>Electrical Engineer</p>
			<p>Mechanical Engineer</p>
			<p>Civil Engineer</p>
			<p>Chemical Engineer</p>
			<p>Industrial Engineer</p>
			<p>Metallurgical Engineer</p>
			<p>Materials Engineer</p>
			<p>Medical Scientist</p>
			<p>Waste Management</p>
			<p>Water Quality Technologist</em></p>
		</div>
	</div>
	</div>
