	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Technology (AF)</p>
			<h5>Here are some career possibilities for you to explore:</h5>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center;"><strong>AF Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;">&nbsp;&nbsp;<img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  More People Oriented</p><p style="float: right;margin-top: -36px;">More Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title="">&nbsp;&nbsp;</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px;">
				<span class="align-middle">
				<br /><br />
				<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
				<br /><br />
				Education
				<br />
				or
				<br />
				Training
				<br />
				Required
				<br /><br />
				<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
				</span>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Biotechnology<br />Environmental</h5>

			<em>Veterinarian<br />
			Aquatic Biologist<br />
			Ecologist<br />
			Geneticist<br />
			Microbiologist<br />
			Physiologist<br />
			Oceanographer<br />
			Seismologist<br />
			Stratigrapher</em>
		</div>
		<div class="col-md" style="margin-bottom: 20px;">
			<h5>Information</h5>
			<em>Urban Planner<br />
			Systems Analyst<br />
			Computer
				<ul>
					<li>Software Engineer</li>
					<li>Programmer</li>
					<li>Technician</li>
					<li>Systems Programmer</li>
				</ul>
			Information Systems Mgr.<br />
			Applications Programmer<br />
			User Support Analyst<br />
			Recording Engineer</em>
		</div>
		<div class="col-md">
			<h5>Engineering</h5>

			<em>Engineer<br />
			Electrical Engineer<br />
			Mechanical Engineer<br />
			Civil Engineer<br />
			Chemical Engineer<br />
			Industrial Engineer<br />
			Metallurgical Engineer<br />
			Materials Engineer<br />
			Medical Scientist<br />
			Waste Management<br />
			Water Quality Technologist</em>
		</div>
	</div>


