	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Public Service (AG)</p>
			
			<div class="inter">
				
			<p>If you scored high in the "A" and "G" categories, you are
			concerned about your planet and the people, animals, and plants that
			live on it.  You have a "no-nonsense" approach that ensures that
			things get done. You enjoy working on a team, but you can work
			alone.  You want to make a difference in the world.</p>
			<p>Most occupations in this pairing require at least a Bachelor's
			Degree. A Master's Degree or Ph.D. is needed for certain
			occupations.</p>
			<p>In high school you should take courses that help you understand
			the environment and people. Science and social studies courses will
			be of particular interest to you.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong></p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Agriculture<br />
						Political Science<br />
						Psychology<br />
						Physical Education
					</td>
					<td>
						Business Law<br />
						Business Ed.<br />
						Sociology<br />
					</td>
					<td>
						Computer Technology<br />
						Biology<br />
						Computer Science<br />
						Environmental Science
					</td>
					<td>
						Government/Civics<br />
						Economics<br />
						Geography<br />
						Industrial Technology
					</td>
					<td>
						World Languages<br />
						Health/Nutrition<br />
						History
					</td>
				</tr>
			</table>

			<p>If you have time for after-school activities or part-time jobs,
			make them count. You will especially enjoy an activity that involves
			working with others and/or sharing a love for nature.</p>
			<p><strong>Extracurricular / volunteer activities or organizations
			that you may find interesting:</strong></p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Adopt-a-Mile<br />
						Habitat for Humanity<br />
						Peer Counselor<br />
						Future Farmers of America
					</td>
					<td>
						Athletics<br />
						Church Activities<br />
						Hospital Volunteer<br />
						Safety Patrol
					</td>
					<td>
						Scouts<br />
						Youth Organizations<br />
						Camp Counselor<br />
						Martial Arts
					</td>
					<td>
						Parks/Recreation<br />
						Chess Club<br />
						ROTC</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Camp Counselor<br />
						Recreation Departments<br />
						Farming
					</td>
					<td>
						Lawn Care/Landscaping<br />
						Park Services<br />
						Life Guarding
					</td>
					<td>
						Lumberyards<br />
						Youth Coaching
					</td>
					<td>
						Hospitals<br />
						Special Olympics
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>

			<p><em>Veterinarian</p>
			<p>Urban Planner</p>
			<p>Recreation Administrator</p>
			<p>Preservationist</p>
			<p>Land Developer</p>
			<p>Park Ranger</p>
			<p>Public Utilities Manager</p>
			<p>Police Officer</p>
			<p>Firefighter</p>
			<p>Recyclist</p>
			<p>Security Guard</p>
			<p>Postal Worker</p>
			<p>Public Transportation Operator</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature</h5>

			<p><em>Horticulturist</p>
			<p>Rangeland Specialist</p>
			<p>Toxicologist</p>
			<p>Surveyor</p>
			<p>Tugboat Captain</p>
			<p>Range Inspector</p>
			<p>Park Inspector</p>
			<p>Organic Farmer</p>
			<p>Survival Trainer</p>
			<p>Grounds Maintenance Supervisor</p>
			<p>Nursery Manager</p>
			<p>Animal Caretaker</em></p>
		</div>
		<div class="col">
			<h5>Environment</h5>

			<p><em>Environmental Lawyer</p>
			<p>Geologist</p>
			<p>Civil Engineer</p>
			<p>Pollution Engineer</p>
			<p>Environmentalist</p>
			<p>Waste Management Technician</p>
			<p>Water Treatment Plant Operator</p>
			<p>Power Plant Operator</p>
			<p>Forestry Technician</p>
			<p>Forestry Worker</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>

			<p><em>Veterinarian</p>
			<p>Urban Planner</p>
			<p>Recreation Administrator</p>
			<p>Preservationist</p>
			<p>Land Developer</p>
			<p>Park Ranger</p>
			<p>Public Utilities Manager</p>
			<p>Police Officer</p>
			<p>Firefighter</p>
			<p>Recyclist</p>
			<p>Security Guard</p>
			<p>Postal Worker</p>
			<p>Public Transportation Operator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature</h5>

			<p><em>Horticulturist</p>
			<p>Rangeland Specialist</p>
			<p>Toxicologist</p>
			<p>Surveyor</p>
			<p>Tugboat Captain</p>
			<p>Range Inspector</p>
			<p>Park Inspector</p>
			<p>Organic Farmer</p>
			<p>Survival Trainer</p>
			<p>Grounds Maintenance Supervisor</p>
			<p>Nursery Manager</p>
			<p>Animal Caretaker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Environment</h5>

			<p><em>Environmental Lawyer</p>
			<p>Geologist</p>
			<p>Civil Engineer</p>
			<p>Pollution Engineer</p>
			<p>Environmentalist</p>
			<p>Waste Management Technician</p>
			<p>Water Treatment Plant Operator</p>
			<p>Power Plant Operator</p>
			<p>Forestry Technician</p>
			<p>Forestry Worker</em></p>
		</div>
	</div>
	</div>

