	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Science/Mathematics (AH)</p>
			
			<div class="inter">
			
			<p>If you scored high in the "A" and "H" categories, you can play an
			important role in understanding, protecting and exploring the laws
			of nature. People with your interests have contributed much to our
			development, discovery and application of knowledge in this
			area. "AH" people are usually excellent thinkers and appliers of
			their knowledge. They are also creative scientists who have a great
			respect for nature. They often find new ways to solve old problems
			in all fields.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree and many will require a master's degree or Ph.D.</p>
			<p><strong>Courses you may want to take in high school and beyond
			(in addition to English & Math):</strong><br />
			In high school you should take courses in math and science. Courses
			about the outdoors and nature will be of great interest to you. They
			will also help prepare you for a possible career in this field.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Agriculture<br />
						Chemistry<br />
						Business Math
					</td>
					<td>
						Calculus<br />
						Health/Nutrition<br />
						Sociology
					</td>
					<td>
						Psychology<br />
						Technology Education<br />
						Environmental Science
					</td>
					<td>
						Trigonometry<br />
						Physics<br />
						Business Education
					</td>
					<td>
						Biology<br />
						Economics<br />
						Telecommunications
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interest:</strong><br />
			If you have time for after-school activities or part-time jobs, make
			them count. You may especially enjoy a club or activity where you can
			share your love for nature and use your thinking skills.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Adopt-a-Mile<br />
						Habitat for Humanity<br />
						Computer Club<br />
						Future Farmers of America
					</td>
					<td>
						Athletics<br />
						Math/Science Club<br />
						Tutoring
					</td>
					<td>
						Scouts<br />
						Hospital Volunteer<br />
						ROTC<br />
						Animal Care
					</td>
					<td>
						Parks/Recreation<br />
						Environmental Activities<br />
						Martial Arts<br />
						Chess Club
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Animal Care<br />
						Landscaping<br />
						Archeological Projects
					</td>
					<td>
						Farming<br />
						Park Services<br />
						Theaters
					</td>
					<td>
						Medical Offices<br />
						Computer Services
					</td>
					<td>
						Veterinary Offices<br />
						Lawn Care
					</td>
				</tr>
			</table>
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">			
			<h5>Medical</h5>
			<p><em>Professor</p>
			<p>Coroner</p>
			<p>Sports Psychologist</p>
			<p>Veterinarian</p>
			<p>Horticultural Therapist</p>
			<p>Scientist
				<ul>
					<li>Animal</li>
					<li>Botanist</li>
					<li>Ecologist</li>
					<li>Food</li>
				</ul></p>
			<p>Recreational Therapist</p>
			<p>Researcher</p>
			<p>Meat Inspector</em>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature Sciences</h5>
			<p><em>Microbiologist</p>
			<p>Archaeologist</p>
			<p>Geoscientist
				<ul>
					<li>Petroleum Geologist</li>
					<li>Mineralogist</li>
					<li>Paleontologist</li>
					<li>Oceanographer</li>
				</ul></p>
			<p>Ecologist</p>
			<p>Conservationist
				<ul>
					<li>Soil</li>
					<li>Wildlife</li>
				</ul></p>
			<p>Political Scientist</p>
			<p>Climatologist</p>
			<p>Firefighter</p>
			<p>TreeFarmer</p>
			<p>PlanetariumTechnician</em>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environment</h5>
			<p><em>Engineer
				<ul>
					<li>Environmental</li>
					<li>Geotechnical</li>
					<li>Mining</li>
					<li>Petroleum</li>
					<li>Waste Management</li>
				</ul></p>
			<p>Hazardous Materials Specialist</p>
			<p>Landscape Architect</p>
			<p>Environmental Health Inspector</p>
			<p>Coast Guard</p>
			<p>Surveyor</p>
			<p>Water Treatment Plant Operator</p>
			<p>Engineering Technician</p>
			<p>Mining</em>
		</div>
		<div class="col">
			<h5>Math</h5>
			<p><em>Astronomer</p>
				<ul>
					<li>Astrophysicist</li>
					<li>Solar</li>
				</ul></p>
			<p>Engineer
				<ul>
					<li>Aeronautical</li>
					<li>Industrial</li>
				</ul></p>
			<p>Financial Officer</p>
			<p>Military Budget Officer</p>
			<p>Bio-statistician</p>
			<p>Statistician</p>
			<p>Surveyor</p>
			<p>Mapping Scientist</p>
			<p>Researcher</p>
			<p>Technician
				<ul>
					<li>Airport Computer</li>
					<li>Mapping</li>
				</ul></em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical</h5>
			<p><em>Professor</p>
			<p>Coroner</p>
			<p>Sports Psychologist</p>
			<p>Veterinarian</p>
			<p>Horticultural Therapist</p>
			<p>Scientist
				<ul>
					<li>Animal</li>
					<li>Botanist</li>
					<li>Ecologist</li>
					<li>Food</li>
				</ul></p>
			<p>Recreational Therapist</p>
			<p>Researcher</p>
			<p>Meat Inspector</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature Sciences</h5>
			<p><em>Microbiologist</p>
			<p>Archaeologist</p>
			<p>Geoscientist
				<ul>
					<li>Petroleum Geologist</li>
					<li>Mineralogist</li>
					<li>Paleontologist</li>
					<li>Oceanographer</li>
				</ul></p>
			<p>Ecologist</p>
			<p>Conservationist
				<ul>
					<li>Soil</li>
					<li>Wildlife</li>
				</ul></p>
			<p>Political Scientist Climatologist</p>
			<p>Firefighter</p>
			<p>TreeFarmer</p>
			<p>PlanetariumTechnician</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Environment</h5>
			<p><em>Engineer
				<ul>
					<li>Environmental</li>
					<li>Geotechnical</li>
					<li>Mining</li>
					<li>Petroleum</li>
					<li>Waste Management</li>
				</ul></p>
			<p>Hazardous Materials Specialist</p>
			<p>Landscape Architect</p>
			<p>Environmental Health Inspector</p>
			<p>Coast Guard</p>
			<p>Surveyor</p>
			<p>Water Treatment Plant Operator</p>
			<p>Engineering Technician</p>
			<p>Mining</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Math</h5>
			<p><em>Astronomer</p>
				<ul>
					<li>Astrophysicist</li>
					<li>Solar</li>
				</ul></p>
			<p>Engineer
				<ul>
					<li>Aeronautical</li>
					<li>Industrial</li>
				</ul></p>
			<p>Financial Officer</p>
			<p>Military Budget Officer</p>
			<p>Bio-statistician</p>
			<p>Statistician</p>
			<p>Surveyor</p>
			<p>Mapping Scientist</p>
			<p>Researcher</p>
			<p>Technician
				<ul>
					<li>Airport Computer</li>
					<li>Mapping</li>
				</ul></em></p>
		</div>
	</div>
	</div>


