	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Science/Mathematics (AH)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">			
			<h5>Medical</h5>
			<p><em>Professor</p>
			<p>Coroner</p>
			<p>Sports Psychologist</p>
			<p>Veterinarian</p>
			<p>Horticultural Therapist</p>
			<p>Scientist
				<ul>
					<li>Animal</li>
					<li>Botanist</li>
					<li>Ecologist</li>
					<li>Food</li>
				</ul></p>
			<p>Recreational Therapist</p>
			<p>Researcher</p>
			<p>Meat Inspector</em>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature Sciences</h5>
			<p><em>Microbiologist</p>
			<p>Archaeologist</p>
			<p>Geoscientist
				<ul>
					<li>Petroleum Geologist</li>
					<li>Mineralogist</li>
					<li>Paleontologist</li>
					<li>Oceanographer</li>
				</ul></p>
			<p>Ecologist</p>
			<p>Conservationist
				<ul>
					<li>Soil</li>
					<li>Wildlife</li>
				</ul></p>
			<p>Political Scientist Climatologist</p>
			<p>Firefighter</p>
			<p>TreeFarmer</p>
			<p>PlanetariumTechnician</em>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environment</h5>
			<p><em>Engineer
				<ul>
					<li>Environmental</li>
					<li>Geotechnical</li>
					<li>Mining</li>
					<li>Petroleum</li>
					<li>Waste Management</li>
				</ul></p>
			<p>Hazardous Materials Specialist</p>
			<p>Landscape Architect</p>
			<p>Environmental Health Inspector</p>
			<p>Coast Guard</p>
			<p>Surveyor</p>
			<p>Water Treatment Plant Operator</p>
			<p>Engineering Technician</p>
			<p>Mining</em>
		</div>
		<div class="col">
			<h5>Math</h5>
			<p><em>Astronomer</p>
				<ul>
					<li>Astrophysicist</li>
					<li>Solar</li>
				</ul></p>
			<p>Engineer
				<ul>
					<li>Aeronautical</li>
					<li>Industrial</li>
				</ul></p>
			<p>Financial Officer</p>
			<p>Military Budget Officer</p>
			<p>Bio-statistician</p>
			<p>Statistician</p>
			<p>Surveyor</p>
			<p>Mapping Scientist</p>
			<p>Researcher</p>
			<p>Technician
				<ul>
					<li>Airport Computer</li>
					<li>Mapping</li>
				</ul></em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical</h5>
			<p><em>Professor</p>
			<p>Coroner</p>
			<p>Sports Psychologist</p>
			<p>Veterinarian</p>
			<p>Horticultural Therapist</p>
			<p>Scientist
				<ul>
					<li>Animal</li>
					<li>Botanist</li>
					<li>Ecologist</li>
					<li>Food</li>
				</ul></p>
			<p>Recreational Therapist</p>
			<p>Researcher</p>
			<p>Meat Inspector</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature Sciences</h5>
			<p><em>Microbiologist</p>
			<p>Archaeologist</p>
			<p>Geoscientist
				<ul>
					<li>Petroleum Geologist</li>
					<li>Mineralogist</li>
					<li>Paleontologist</li>
					<li>Oceanographer</li>
				</ul></p>
			<p>Ecologist</p>
			<p>Conservationist
				<ul>
					<li>Soil</li>
					<li>Wildlife</li>
				</ul></p>
			<p>Political Scientist Climatologist</p>
			<p>Firefighter</p>
			<p>TreeFarmer</p>
			<p>PlanetariumTechnician</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Environment</h5>
			<p><em>Engineer
				<ul>
					<li>Environmental</li>
					<li>Geotechnical</li>
					<li>Mining</li>
					<li>Petroleum</li>
					<li>Waste Management</li>
				</ul></p>
			<p>Hazardous Materials Specialist</p>
			<p>Landscape Architect</p>
			<p>Environmental Health Inspector</p>
			<p>Coast Guard</p>
			<p>Surveyor</p>
			<p>Water Treatment Plant Operator</p>
			<p>Engineering Technician</p>
			<p>Mining</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Math</h5>
			<p><em>Astronomer</p>
				<ul>
					<li>Astrophysicist</li>
					<li>Solar</li>
				</ul></p>
			<p>Engineer
				<ul>
					<li>Aeronautical</li>
					<li>Industrial</li>
				</ul></p>
			<p>Financial Officer</p>
			<p>Military Budget Officer</p>
			<p>Bio-statistician</p>
			<p>Statistician</p>
			<p>Surveyor</p>
			<p>Mapping Scientist</p>
			<p>Researcher</p>
			<p>Technician
				<ul>
					<li>Airport Computer</li>
					<li>Mapping</li>
				</ul></em></p>
		</div>
	</div>
	</div>


