	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Social/Helping (AI)</p>
			
			<div class="inter">
			
			<p>Your high scores in "A" and "I" show that you have several
			characteristics that can help promote the welfare of people. You are
			practical, curious, and people-oriented with a love of the outdoors.
			You like to offer support to people who are having difficulties in
			learning and adjusting to new and different situations. You also
			have an interest in teaching, consulting and counseling for improved
			ways to become healthier physically and mentally. You promote a
			safer and cleaner environment and have respect for those
			environments and individuals.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree.  It is helpful to have a master's degree or a Ph.D. in some
			of the occupations.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that help you understand
			people. Any courses that deal with the outdoors and nature will be
			of great interest to you and will help prepare you for possible
			career opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Agriculture<br />
						Religion<br />
						Psychology<br />
						Sociology
					</td>
					<td>
						Computer Sciences<br />
						Speech & Communications<br />
						Economics<br />
						Environmental Science
					</td>
					<td>
						Health/Nutrition<br />
						Biology<br />
						Home Economics<br />
						Early Childhood
						Education<br />
					</td>
					<td>
						Law<br />
						Education<br />
						Business Ed.<br />
						Logic
					</td>
					<td>
						Physical Education<br />
						History<br />
						Public Relations<br />
						Life Science
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			that you might find interesting:</strong><br />
			If you have time for after-school activities or part-time jobs, make
			them count. You will especially enjoy any club or activity where you
			can share your love for nature and use your people skills.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Adopt-a-Mile<br />
						Habitat for Humanity<br />
						Tutoring<br />
						Animal Care
					</td>
					<td>
						Athletics<br />
						Childcare/Eldercare<br />
						Church Activities<br />
						Future Farmers of America
					</td>
					<td>
						Scouts<br />
						Hospital Volunteer<br />
						Teaching Assistant<br />
						Camp Counselor
					</td>
					<td>
						Parks/Recreation<br />
						Peer Counselor<br />
						ROTC<br />
						Martial Arts
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Day Care Centers<br />
						Recreation Departments<br />
						Life Guard
					</td>
					<td>
						Park Services<br />
						Summer Camps<br />
						Retirement Homes
					</td>
					<td>
						Special Olympic<br />
						Landscaping/Lawn Care
					</td>
					<td>
						Farming<br />
						Lumberyard
					</td>
				</tr>
			</table>
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
	
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>
			<p><em>Teacher
				<ul>
					<li>Agriculture</li>
					<li>Biology</li>
					<li>Industrial Arts</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Horticultural Therapist</p>
			<p>Recreation Therapist</p>
			<p>Peace Corp Worker</p>
			<p>Postal Worker</p>
			<p>Real Estate Appraiser</p>
			<p>Bus Driver</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature</h5>
			<p><em>Veterinarian</p>
			<p>Pet Psychologist</p>
			<p>Ecologist</p>
			<p>Zoo Manager</p>
			<p>Forester</p>
			<p>Wildlife Rehabilitator</p>
			<p>Recreational Therapist</p>
			<p>Park Ranger</p>
			<p>Nature Guide</p>
			<p>Forestry</p>
			<p>Animal Lab Technician</em></p>
		</div>
		<div class="col">
			<h5>Environment</h5>
			<p><em>Civil Engineer</p>
			<p>City Planner</p>
			<p>Surveyor</p>
			<p>Hazardous Waste Management Professional</p>
			<p>Environmental Heath Specialist</p>
			<p>Firefighter</p>
			<p>Emergency Management Specialist</p>
			<p>Recreation Specialist</p>
			<p>Sanitation Engineer</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>
			<p><em>Teacher
				<ul>
					<li>Agriculture</li>
					<li>Biology</li>
					<li>Industrial Arts</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Horticultural Therapist</p>
			<p>Recreation Therapist</p>
			<p>Peace Corp Worker</p>
			<p>Postal Worker</p>
			<p>Real Estate Appraiser</p>
			<p>Bus Driver</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature</h5>
			<p><em>Veterinarian</p>
			<p>Pet Psychologist</p>
			<p>Ecologist</p>
			<p>Zoo Manager</p>
			<p>Forester</p>
			<p>Wildlife Rehabilitator</p>
			<p>Recreational Therapist</p>
			<p>Park Ranger</p>
			<p>Nature Guide</p>
			<p>Forestry</p>
			<p>Animal Lab Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Environment</h5>
			<p><em>Civil Engineer</p>
			<p>City Planner</p>
			<p>Surveyor</p>
			<p>Hazardous Waste Management Professional</p>
			<p>Environmental Heath Specialist</p>
			<p>Firefighter</p>
			<p>Emergency Management Specialist</p>
			<p>Recreation Specialist</p>
			<p>Sanitation Engineer</em></p>
		</div>
	</div>
	</div>

