	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with	Clerical/Administrative (BD)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BD Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Arts/Communication</h5>
			<p><em>Publisher</p>
			<p>Marketing Administrator</p>
			<p>Editor</p>
			<p>Press Secretary</p>
			<p>Media Planner</p>
			<p>Writer
				<ul>
					<li>Newspaper</li>
					<li>Playwright</li>
					<li>Technical</li>
				</ul></p>
			<p>Critic</p>
			<p>Editorial Assistant</p>
			<p>Tour Coordinator</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Clerical/Administrative</h5>
			<p><em>Computer Graphic Designer</p>
			<p>Public Relations Specialist</p>
			<p>Library Assistant</p>
			<p>Paralegal</p>
			<p>Proofreader</p>
			<p>Marketing/Advertising Account Executive</p>
			<p>Real Estate Agent</p>
			<p>Radio/Television
			<p>Traffic Continuity Specialist</p>
			<p>Telemarketer</em></p>
		</div>
		<div class="col">
			<h5>Creative Production</h5>
			<p><em>Book Publishing Professional</p>
			<p>Media Specialist</p>
			<p>Photojournalist</p>
			<p>Television Set Decorator</p>
			<p>Video Production Assistant</p>
			<p>Crossword Puzzle Maker</p>
			<p>Technician
				<ul>
					<li>Media Production</li>
					<li>Design</li>
					<li>Stage</li>
				</ul></p>
			<p>Production Assistant</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Arts/Communication</h5>
			<p><em>Publisher</p>
			<p>Marketing Administrator</p>
			<p>Editor</p>
			<p>Press Secretary</p>
			<p>Media Planner</p>
			<p>Writer
				<ul>
					<li>Newspaper</li>
					<li>Playwright</li>
					<li>Technical</li>
				</ul></p>
			<p>Critic</p>
			<p>Editorial Assistant</p>
			<p>Tour Coordinator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Clerical/Administrative</h5>
			<p><em>Computer Graphic Designer</p>
			<p>Public Relations Specialist</p>
			<p>Library Assistant</p>
			<p>Paralegal</p>
			<p>Proofreader</p>
			<p>Marketing/Advertising Account Executive</p>
			<p>Real Estate Agent</p>
			<p>Radio/Television
			<p>Traffic Continuity Specialist</p>
			<p>Telemarketer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Creative Production</h5>
			<p><em>Book Publishing Professional</p>
			<p>Media Specialist</p>
			<p>Photojournalist</p>
			<p>Television Set Decorator</p>
			<p>Video Production Assistant</p>
			<p>Crossword Puzzle Maker</p>
			<p>Technician
				<ul>
					<li>Media Production</li>
					<li>Design</li>
					<li>Stage</li>
				</ul></p>
			<p>Production Assistant</em></p>
		</div>
	</div>
	</div>

