	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Public Service (BG)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Support Services</h5>
			<p><em>Community College Administrator</p>
			<p>City Zoning Director</p>
			<p>Continuing Education Coordinator</p>
			<p>Teacher
				<ul>
					<li>Adult Education</li>
					<li>Public Speaking</li>
					<li>Broadcasting</li>
				</ul></p>
			<p>Chamber of Commerce Representative</p>
			<p>Visitors Bureau Representative</p>
			<p>TV/Radio Public Affairs Producer</p>
			<p>Lobbyist</p>
			<p>Clergy</p>
			<p>Church Youth Director</p>
			<p>Reservation/Ticket Agent</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Art and Design</h5>
			<p><em>Ballet/Symphony Director</p>
			<p>Ballet/Symphony Manager</p>
			<p>Museum Director</p>
			<p>City Planner</p>
			<p>Orchestra Conductor</p>
			<p>Historic Preservationist</p>
			<p>Performing Arts Personnel Director</p>
			<p>Landscape Designer</p>
			<p>Arts Festival Coordinator</p>
			<p>Exhibit Designer</p>
			<p>Photographer</p>
			<p>Cook</p>
			<p>Floral Designer</em></p>
		</div>
		<div class="col">
			<h5>Communication Services</h5>
			<p><em>Copyright Attorney</p>
			<p>Public Relations Specialist</p>
			<p>Community Affairs Director</p>
			<p>TV/Radio Talk Show Host</p>
			<p>College Marketing Specialist</p>
			<p>Cultural Marketing Specialist</p>
			<p>Broadcaster</p>
			<p>Editorial Writer</p>
			<p>Documentary Film Maker</p>
			<p>Interpreter</p>
			<p>Product Spokesperson</p>
			<p>Theatrical Press Agent</p>
			<p>Market Researcher</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Support Services</h5>
			<p><em>Community College Administrator</p>
			<p>City Zoning Director</p>
			<p>Continuing Education Coordinator</p>
			<p>Teacher
				<ul>
					<li>Adult Education</li>
					<li>Public Speaking</li>
					<li>Broadcasting</li>
				</ul></p>
			<p>Chamber of Commerce Representative</p>
			<p>Visitors Bureau Representative</p>
			<p>TV/Radio Public Affairs Producer</p>
			<p>Lobbyist</p>
			<p>Clergy</p>
			<p>Church Youth Director</p>
			<p>Reservation/Ticket Agent</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Art and Design</h5>
			<p><em>Ballet/Symphony Director</p>
			<p>Ballet/Symphony Manager</p>
			<p>Museum Director</p>
			<p>City Planner</p>
			<p>Orchestra Conductor</p>
			<p>Historic Preservationist</p>
			<p>Performing Arts Personnel Director</p>
			<p>Landscape Designer</p>
			<p>Arts Festival Coordinator</p>
			<p>Exhibit Designer</p>
			<p>Photographer</p>
			<p>Cook</p>
			<p>Floral Designer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Communication Services</h5>
			<p><em>Copyright Attorney</p>
			<p>Public Relations Specialist</p>
			<p>Community Affairs Director</p>
			<p>TV/Radio Talk Show Host</p>
			<p>College Marketing Specialist</p>
			<p>Cultural Marketing Specialist</p>
			<p>Broadcaster</p>
			<p>Editorial Writer</p>
			<p>Documentary Film Maker</p>
			<p>Interpreter</p>
			<p>Product Spokesperson</p>
			<p>Theatrical Press Agent</p>
			<p>Market Researcher</em></p>
		</div>
	</div>
	</div>




