
	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Business/Management (BC)</p>
			
			<div class="inter">
			
			<p>A "BC" pairing indicates that you are a "fun" person. You are
			able to work with many different types of people and, more than
			likely, they enjoy working with you. One of your assets is your
			ability to appreciate others for who they are and what they add to a
			project. You also can work on several tasks at one time. You don't
			need much direction on how to complete a task or assignment because
			you combine creativity with the ability to get things done. You are
			likely to be very dedicated to your work.</p>
			
			<p>Most occupations in this pairing require at least a bachelor's
			degree. Some require post high school courses.</p>
			
			<p><strong>Courses you may want to consider taking in high school and beyond (in addition to Math & English):</strong><br />
			In high school you will want to take classes that will help you
			express yourself better and help you understand others. Writing
			courses will be appropriate. Also, you might consider taking public
			speaking. Some business courses will help you learn how to get
			things done quickly.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting<br />
						Speech & Communication<br />
						Art/Music<br />
						Economics
					</td>
					<td>
						Business Law<br />
						Advertising<br />
						Computer Science<br />
						Government/Civics
					</td>
					<td>
						Computer Technology<br />
						Marketing & Advertising<br />
						Graphic Arts<br />
						Logic
					</td>
					<td>
						Language<br />
						Psychology<br />
						Public Relations<br />
						Political Science
					</td>
					<td>
						Photography<br />
						Sociology<br />
						History<br />
						Business Education
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			Experience is an important thing! If you are looking for a fun
			activity or a part-time job, consider places where communicating
			with others is a focus. Don't forget to find a place where you can
			show how responsible you are.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Drama/Theatre<br />
						Debate Team<br />
						Junior Achievement<br />
						Yearbook
					</td>
					<td>
						Band/Chorus<br />
						Photography Club<br />
						Class Officer<br />
						Radio/TV Activities
					</td>
					<td>
						Newspaper/Yearbook<br />
						Audio/Visual Services<br />
						Computer Activities<br />
						Future Business Leaders
					</td>
					<td>
						Language Club<br />
						Exchange Programs<br />
						Community Volunteer
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job.</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting Firms<br />
						Advertising Agencies<br />
						Office Temporary Services<br />
					</td>
					<td>
						Libraries<br />
						Newspaper Publisher<br />
						Repair Services
					</td>
					<td>
						Radio/TV Studios<br />
						Receptionist<br />
						Graphic Design Firms
					</td>
					<td>
						Restaurant<br />
						Telephone Sales
					</td>
				</tr>
			</table>
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BC Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Business</h5>
			<p><em>Art Director</p>
			<p>Chef</p>
			<p>Illustrator</p>
			<p>Graphic Artist</p>
			<p>Art Dealer</p>
			<p>Interior Designer</p>
			<p>Buyer/Merchandiser</p>
			<p>Restaurateur</p>
			<p>Wedding Consultant</p>
			<p>Fashion Coordinator</p>
			<p>Hair Designer</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications Business</h5>
			<p><em>Public Relations Specialist</p>
			<p>Publicist/Press Agent</p>
			<p>Television Broadcaster</p>
			<p>Advertising Production Manager</p>
			<p>Media Production Specialist</p>
			<p>Advertising Copywriter</p>
			<p>Talk Show Host</p>
			<p>Disc Jockey</p>
			<p>Radio/TV Traffic Manager</p>
			<p>Photographer</em></p>
		</div>
		<div class="col">
			<h5>Entertainment Business</h5>
			<p><em>Book Publishing Professional</p>
			<p>Media Specialist</p>
			<p>Photojournalist</p>
			<p>Television Set Director</p>
			<p>Video Production Assistant</p>
			<p>Crossword Puzzle Maker</p>
			<p>Technician
				<ul>
					<li>Media Production</li>
					<li>Design</li>
					<li>Stage</li>
				</ul></p>
			<p>Production Assistant</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Business</h5>
			<p><em>Art Director</p>
			<p>Chef</p>
			<p>Illustrator</p>
			<p>Graphic Artist</p>
			<p>Art Dealer</p>
			<p>Interior Designer</p>
			<p>Buyer/Merchandiser</p>
			<p>Restaurateur</p>
			<p>Wedding Consultant</p>
			<p>Fashion Coordinator</p>
			<p>Hair Designer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications Business</h5>
			<p><em>Public Relations Specialist</p>
			<p>Publicist/Press Agent</p>
			<p>Television Broadcaster</p>
			<p>Advertising Production Manager</p>
			<p>Media Production Specialist</p>
			<p>Advertising Copywriter</p>
			<p>Talk Show Host</p>
			<p>Disc Jockey</p>
			<p>Radio/TV Traffic Manager</p>
			<p>Photographer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Entertainment Business</h5>
			<p><em>Book Publishing Professional</p>
			<p>Media Specialist</p>
			<p>Photojournalist</p>
			<p>Television Set Director</p>
			<p>Video Production Assistant</p>
			<p>Crossword Puzzle Maker</p>
			<p>Technician
				<ul>
					<li>Media Production</li>
					<li>Design</li>
					<li>Stage</li>
				</ul></p>
			<p>Production Assistant</em></p>
		</div>
	</div>
	</div>

