	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Business/Management (BC)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BC Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Business</h5>
			<p><em>Art Director</p>
			<p>Chef</p>
			<p>Illustrator</p>
			<p>Graphic Artist</p>
			<p>Art Dealer</p>
			<p>Interior Designer</p>
			<p>Buyer/Merchandiser</p>
			<p>Restaurateur</p>
			<p>Wedding Consultant</p>
			<p>Fashion Coordinator</p>
			<p>Hair Designer</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications Business</h5>
			<p><em>Public Relations Specialist</p>
			<p>Publicist/Press Agent</p>
			<p>Television Broadcaster</p>
			<p>Advertising Production Manager</p>
			<p>Media Production Specialist</p>
			<p>Advertising Copywriter</p>
			<p>Talk Show Host</p>
			<p>Disc Jockey</p>
			<p>Radio/TV Traffic Manager</p>
			<p>Photographer</em></p>
		</div>
		<div class="col">
			<h5>Entertainment Business</h5>
			<p><em>Book Publishing Professional</p>
			<p>Media Specialist</p>
			<p>Photojournalist</p>
			<p>Television Set Director</p>
			<p>Video Production Assistant</p>
			<p>Crossword Puzzle Maker</p>
			<p>Technician
				<ul>
					<li>Media Production</li>
					<li>Design</li>
					<li>Stage</li>
				</ul></p>
			<p>Production Assistant</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Business</h5>
			<p><em>Art Director</p>
			<p>Chef</p>
			<p>Illustrator</p>
			<p>Graphic Artist</p>
			<p>Art Dealer</p>
			<p>Interior Designer</p>
			<p>Buyer/Merchandiser</p>
			<p>Restaurateur</p>
			<p>Wedding Consultant</p>
			<p>Fashion Coordinator</p>
			<p>Hair Designer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications Business</h5>
			<p><em>Public Relations Specialist</p>
			<p>Publicist/Press Agent</p>
			<p>Television Broadcaster</p>
			<p>Advertising Production Manager</p>
			<p>Media Production Specialist</p>
			<p>Advertising Copywriter</p>
			<p>Talk Show Host</p>
			<p>Disc Jockey</p>
			<p>Radio/TV Traffic Manager</p>
			<p>Photographer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Entertainment Business</h5>
			<p><em>Book Publishing Professional</p>
			<p>Media Specialist</p>
			<p>Photojournalist</p>
			<p>Television Set Director</p>
			<p>Video Production Assistant</p>
			<p>Crossword Puzzle Maker</p>
			<p>Technician
				<ul>
					<li>Media Production</li>
					<li>Design</li>
					<li>Stage</li>
				</ul></p>
			<p>Production Assistant</em></p>
		</div>
	</div>
	</div>

