	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with	Clerical/Administrative (BD)</p>
			
			<div class="inter">
			
			<p>If you had a high score in categories "B" and "D" you like to
			work on creative projects and you enjoy their completion. You have a
			balance of characteristics that will allow you to be creative and
			efficient. Others know that they can count on you.</p>
			<p>Most occupations in this pairing require at least some post high school courses be taken. Many require a bachelor's degree.</p>
			<p><strong>Courses you might want to take in high
			school.</strong><br />
			In high school you will want to take courses that allow you to
			express your thoughts and ideas through writing, speaking, or visual
			media. You also will want to take courses that appeal to your
			practical side.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising/Marketing<br />
						History<br />
						Computer Technology<br />
						Sociology
					</td>
					<td>
						Computer Programming<br />
						Graphic Arts<br />
						World Languages<br />
						Speech/Communications/
						Music<br />
					</td>
					<td>
						Office Administration<br />
						Photography<br />
						Technology Education
					</td>
					<td>
						Business Education<br />
						Psychology<br />
						Bookkeeping<br />
					</td>
					<td>
						Art<br />
						Business Math<br />
						Geography<br />
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			Experience is an important thing! When you are looking for a fun
			activity or a part-time job, think about working in places where
			communication is the focus. Don't forget to find a place where you
			can show others how dependable you are.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Drama/Theatre<br />
						Debate Team<br />
						Office Assistant<br />
						Music Lessons
					</td>
					<td>
						Band/Chorus<br />
						Photography Club<br />
						Teaching Assistant<br />
						Radio/TV Activities
					</td>
					<td>
						Newspaper/Yearbook<br />
						Audio-Visual Services<br />
						Class Officer<br />
						Community Volunteer
					</td>
					<td>
						Language Club<br />
						Library Assistant<br />
						Future Business Leaders
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting Firms<br />
						Theaters<br />
						Receptionist<br />
						Retail Stores
					</td>
					<td>
						Data Entry/Processing<br />
						Advertising Agencies<br />
						Radio/TV Studios<br />
						Photography Studios
					</td>
					<td>
						Libraries<br />
						Temporary Agencies<br />
						Clerical Offices
					</td>
					<td>
						Printing Companies<br />
						Newspaper Publishers<br />
						Graphic Design Firms
					</td>
				</tr>
			</table>
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BD Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Arts/Communication</h5>
			<p><em>Publisher</p>
			<p>Marketing Administrator</p>
			<p>Editor</p>
			<p>Press Secretary</p>
			<p>Media Planner</p>
			<p>Writer
				<ul>
					<li>Newspaper</li>
					<li>Playwright</li>
					<li>Technical</li>
				</ul></p>
			<p>Critic</p>
			<p>Editorial Assistant</p>
			<p>Tour Coordinator</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Clerical/Administrative</h5>
			<p><em>Computer Graphic Designer</p>
			<p>Public Relations Specialist</p>
			<p>Library Assistant</p>
			<p>Paralegal</p>
			<p>Proofreader</p>
			<p>Marketing/Advertising Account Executive</p>
			<p>Real Estate Agent</p>
			<p>Radio/Television
			<p>Traffic Continuity Specialist</p>
			<p>Telemarketer</em></p>
		</div>
		<div class="col">
			<h5>Creative Production</h5>
			<p><em>Book Publishing Professional</p>
			<p>Media Specialist</p>
			<p>Photojournalist</p>
			<p>Television Set Decorator</p>
			<p>Video Production Assistant</p>
			<p>Crossword Puzzle Maker</p>
			<p>Technician
				<ul>
					<li>Media Production</li>
					<li>Design</li>
					<li>Stage</li>
				</ul></p>
			<p>Production Assistant</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Arts/Communication</h5>
			<p><em>Publisher</p>
			<p>Marketing Administrator</p>
			<p>Editor</p>
			<p>Press Secretary</p>
			<p>Media Planner</p>
			<p>Writer
				<ul>
					<li>Newspaper</li>
					<li>Playwright</li>
					<li>Technical</li>
				</ul></p>
			<p>Critic</p>
			<p>Editorial Assistant</p>
			<p>Tour Coordinator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Clerical/Administrative</h5>
			<p><em>Computer Graphic Designer</p>
			<p>Public Relations Specialist</p>
			<p>Library Assistant</p>
			<p>Paralegal</p>
			<p>Proofreader</p>
			<p>Marketing/Advertising Account Executive</p>
			<p>Real Estate Agent</p>
			<p>Radio/Television
			<p>Traffic Continuity Specialist</p>
			<p>Telemarketer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Creative Production</h5>
			<p><em>Book Publishing Professional</p>
			<p>Media Specialist</p>
			<p>Photojournalist</p>
			<p>Television Set Decorator</p>
			<p>Video Production Assistant</p>
			<p>Crossword Puzzle Maker</p>
			<p>Technician
				<ul>
					<li>Media Production</li>
					<li>Design</li>
					<li>Stage</li>
				</ul></p>
			<p>Production Assistant</em></p>
		</div>
	</div>
	</div>

