	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Protective/Military Service (BE)</p>
			
			<div class="inter">
			
			<p>If you show high scores in categories "B" and "E" you are a
			person who knows how to make things happen. You are very independent
			and have your own way of doing things. You like to use your
			creativity and explore new possibilities.  Teamwork and people are
			important to you. You are especially good at working on teams that
			are solving problems.</p>
			<p>The occupations in this pairing often require some sort of
			specialized training after high school. Some require college level
			courses. Others require training programs provided by the company
			that hires you.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that allow you to continue
			to learn about communication. You will also want to take courses
			that help you understand people.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Business Law<br />
						Psychology<br />
						Computer Sciences<br />
						Music
					</td>
					<td>
						Public Relations<br />
						Graphic Arts<br />
						Geography<br />
						Marketing/Advertising
					</td>
					<td>
						Government/Civics<br />
						Life Sciences<br />
						History<br />
						Criminal Justice
					</td>
					<td>
						World Languages<br />
						Physical Education<br />
						Communications<br />
						Computer Inf. Sys.
					</td>
					<td>
						Political Science<br />
						Sociology<br />
						Photography
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for after school activities or part-time jobs, make
			them count. You will enjoy any club or activity that involves
			working with others and/or communicating your thoughts and
			feelings.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Drama/Theatre<br />
						Debate Team<br />
						ROTC<br />
						Parks & Recreation
					</td>
					<td>
						Band/Chorus<br />
						Photography Club<br />
						Flight Training<br />
						Radio/TV Activities
					</td>
					<td>
						Newspaper/Yearbook<br />
						Audio-Visual Services<br />
						Scouts<br />
						Camp Activities
					</td>
					<td>
						Language Club<br />
						Martial Arts<br />
						Athletics
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising Agencies<br />
						Camp Counselor<br />
						Construction Sites<br />
						TV/Radio Studios
					</td>
					<td>
						Equipment Operation<br />
						Equipment Repair<br />
						Graphic Design Firms<br />
						Recreation/Parks
					</td>
					<td>
						Gyms<br />
						Libraries<br />
						Life Guarding
					</td>
					<td>
						Newspaper publisher<br />
						Photography Studios<br />
						Printing Companies
					</td>
				</tr>
			</table>
		</div>
			
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BE Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Written & Oral Communication</h5>
			<p><em>Attach</p>
			<p>Public Relations Manager</p>
			<p>Foreign Correspondent</p>
			<p>Scientific & Technical Publications Editor</p>
			<p>International News Correspondent</p>
			<p>Historian</p>
			<p>Radio Announcer</p>
			<p>Editorial Assistant</p>
			<p>Reporter</p>
			<p>Interpreter</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communication Technologies</h5>
			<p><em>Communications Manager</p>
			<p>Traffic Engineer</p>
			<p>Film Editor</p>
			<p>Sonar & Radar Technician</p>
			<p>Radio Operator</p>
			<p>Sound & Recording Engineer</p>
			<p>Engineering Technician</p>
			<p>Broadcast Technician</p>
			<p>Instrument Mechanic</p>
			<p>Teletype Operator</em></p>
		</div>
		<div class="col">
			<h5>Visual Product</h5>
			<p><em>Television Program Director</p>
			<p>Broadcast Journalist</p>
			<p>Industrial Designer</p>
			<p>Photojournalist</p>
			<p>Movie Director</p>
			<p>Graphic Designer</p>
			<p>Photographer</p>
			<p>Motion Picture Camera Operator</p>
			<p>Drafting Technician</p>
			<p>Photographic Process Worker</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Written & Oral Communication</h5>
			<p><em>Attach</p>
			<p>Public Relations Manager</p>
			<p>Foreign Correspondent</p>
			<p>Scientific & Technical Publications Editor</p>
			<p>International News Correspondent</p>
			<p>Historian</p>
			<p>Radio Announcer</p>
			<p>Editorial Assistant</p>
			<p>Reporter</p>
			<p>Interpreter</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communication Technologies</h5>
			<p><em>Communications Manager</p>
			<p>Traffic Engineer</p>
			<p>Film Editor</p>
			<p>Sonar & Radar Technician</p>
			<p>Radio Operator</p>
			<p>Sound & Recording Engineer</p>
			<p>Engineering Technician</p>
			<p>Broadcast Technician</p>
			<p>Instrument Mechanic</p>
			<p>Teletype Operator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Visual Product</h5>
			<p><em>Television Program Director</p>
			<p>Broadcast Journalist</p>
			<p>Industrial Designer</p>
			<p>Photojournalist</p>
			<p>Movie Director</p>
			<p>Graphic Designer</p>
			<p>Photographer</p>
			<p>Motion Picture Camera Operator</p>
			<p>Drafting Technician</p>
			<p>Photographic Process Worker</em></p>
		</div>
	</div>
	</div>

