	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Protective/Military Service (BE)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BE Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Written & Oral Communication</h5>
			<p><em>Attach</p>
			<p>Public Relations Manager</p>
			<p>Foreign Correspondent</p>
			<p>Scientific & Technical Publications Editor</p>
			<p>International News Correspondent</p>
			<p>Historian</p>
			<p>Radio Announcer</p>
			<p>Editorial Assistant</p>
			<p>Reporter</p>
			<p>Interpreter</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communication Technologies</h5>
			<p><em>Communications Manager</p>
			<p>Traffic Engineer</p>
			<p>Film Editor</p>
			<p>Sonar & Radar Technician</p>
			<p>Radio Operator</p>
			<p>Sound & Recording Engineer</p>
			<p>Engineering Technician</p>
			<p>Broadcast Technician</p>
			<p>Instrument Mechanic</p>
			<p>Teletype Operator</em></p>
		</div>
		<div class="col">
			<h5>Visual Product</h5>
			<p><em>Television Program Director</p>
			<p>Broadcast Journalist</p>
			<p>Industrial Designer</p>
			<p>Photojournalist</p>
			<p>Movie Director</p>
			<p>Graphic Designer</p>
			<p>Photographer</p>
			<p>Motion Picture Camera Operator</p>
			<p>Drafting Technician</p>
			<p>Photographic Process Worker</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Written & Oral Communication</h5>
			<p><em>Attach</p>
			<p>Public Relations Manager</p>
			<p>Foreign Correspondent</p>
			<p>Scientific & Technical Publications Editor</p>
			<p>International News Correspondent</p>
			<p>Historian</p>
			<p>Radio Announcer</p>
			<p>Editorial Assistant</p>
			<p>Reporter</p>
			<p>Interpreter</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communication Technologies</h5>
			<p><em>Communications Manager</p>
			<p>Traffic Engineer</p>
			<p>Film Editor</p>
			<p>Sonar & Radar Technician</p>
			<p>Radio Operator</p>
			<p>Sound & Recording Engineer</p>
			<p>Engineering Technician</p>
			<p>Broadcast Technician</p>
			<p>Instrument Mechanic</p>
			<p>Teletype Operator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Visual Product</h5>
			<p><em>Television Program Director</p>
			<p>Broadcast Journalist</p>
			<p>Industrial Designer</p>
			<p>Photojournalist</p>
			<p>Movie Director</p>
			<p>Graphic Designer</p>
			<p>Photographer</p>
			<p>Motion Picture Camera Operator</p>
			<p>Drafting Technician</p>
			<p>Photographic Process Worker</em></p>
		</div>
	</div>
	</div>

