	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Technology (BF)</p>
			
			<div class="inter">
			
			<p>With a "BF" interest, you will be a valuable employee in a
			rapidly changing technology field. Almost all technology is in one
			way or another concerned with communication of change. You enjoy the
			mechanics of technology and you can use it to express your thoughts
			and feelings. The technical changes in the technology field offers a
			fast paced, visual interchange of ideas and knowledge.</p>
			<p>Many of the occupations in this pairing require some sort of
			specialized and/or technical training after high school. Many
			require college degrees or college level courses.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that allow you to continue
			to learn about communicating. Technology courses will be important,
			as well.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising/Marketing<br />
						Environmental Science<br />
						Computer Programming
					</td>
					<td>
						Foreign Language<br />
						Drafting<br />
						Psychology
					</td>
					<td>
						Photography<br />
						Technology Ed.<br />
						Public Relations
					</td>
					<td>
						Communications<br />
						History
						Sociology
					</td>
					<td>
						Art/Graphic Art<br />
						Music<br />
						Business Education
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. Any club or activity that involves technology and
			communicating will be valuable.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Drama/Theatre<br />
						Debate Team<br />
						Audiovisual Services
					</td>
					<td>
						Band/Chorus<br />
						Photography Clubs<br />
						Computer Club
					</td>
					<td>
						Newspaper/Yearbook<br />
						Library Assistant<br />
						Music Lesson
					</td>
					<td>
						Radio/TV Activities<br />
						Math/Science Clubs<br />
						Chess Club
					</td>
				<tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Appliance Repair<br />
						Printing Companies<br />
						Lumberyards<br />
						Newspaper Offices
					</td>
					<td>
						Delivery Services<br />
						TV/Radio Studios<br />
						Photographic Labs
					</td>
					<td>
						Graphic Design Firms<br />
						Camp Counseling<br />
						Construction<br />
						Small Engine Repair
					</td>
					<td>
						Forestry<br />
						Equipment Repair Shops<br />
						Farming<br />
						Photography Studios
					</td>
					<td>
						Park Services<br />
						Landscaping<br />
						Lawn Care
					</td>
				</tr>
			</table>
			
		</div>
			
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BF Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications</h5>
			<p><em>Medial Specialist</p>
			<p>Public Relations Specialist</p>
			<p>Editor</p>
			<p>Technical Writer</p>
			<p>Public Relations Assistant</p>
			<p>Sportscaster</p>
			<p>Desktop Publisher</p>
			<p>Tour Publicist</p>
			<p>Interpretive Naturalist</p>
			<p>Musician</p>
			<p>Actor</p>
			<p>Cruise Ship Entertainer</em>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Technology</h5>
			<p><em>Industrial Designer</p>
			<p>Graphic Artist</p>
			<p>Photographer</p>
			<p>Camera Operator</p>
			<p>Lighting Designer</p>
			<p>Video Editor</p>
			<p>Drafting Technician</p>
			<p>Metal Artist/Fabricator</p>
			<p>Model Maker</p>
			<p>Airbrush Artist</p>
			<p>Tattoo Artist</em>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Exhibit Builder</p>
			<p>Theater Lighting Designer</p>
			<p>Sound Mixer</p>
			<p>Radio/TV Service Technician</p>
			<p>Book Binder</p>
			<p>Road Manager</p>
			<p>Roller Coaster Technician</p>
			<p>Tile Setter</p>
			<p>Painter</p>
			<p>Printer Developer</p>
			<p>Carpenter</p>
			<p>Landscape Gardener</p>
			<p>Entertainer Body Guard</em>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications</h5>
			<p><em>Medial Specialist</p>
			<p>Public Relations Specialist</p>
			<p>Editor</p>
			<p>Technical Writer</p>
			<p>Public Relations Assistant</p>
			<p>Sportscaster</p>
			<p>Desktop Publisher</p>
			<p>Tour Publicist</p>
			<p>Interpretive Naturalist</p>
			<p>Musician</p>
			<p>Actor</p>
			<p>Cruise Ship Entertainer</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Technology</h5>
			<p><em>Industrial Designer</p>
			<p>Graphic Artist</p>
			<p>Photographer</p>
			<p>Camera Operator</p>
			<p>Lighting Designer</p>
			<p>Video Editor</p>
			<p>Drafting Technician</p>
			<p>Metal Artist/Fabricator</p>
			<p>Model Maker</p>
			<p>Airbrush Artist</p>
			<p>Tattoo Artist</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Exhibit Builder</p>
			<p>Theater Lighting Designer</p>
			<p>Sound Mixer</p>
			<p>Radio/TV Service Technician</p>
			<p>Book Binder</p>
			<p>Road Manager</p>
			<p>Roller Coaster Technician</p>
			<p>Tile Setter</p>
			<p>Painter</p>
			<p>Printer Developer</p>
			<p>Carpenter</p>
			<p>Landscape Gardener</p>
			<p>Entertainer Body Guard</em>
		</div>
	</div>
	</div>

