	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Public Service (BG)</p>
			
			<div class="inter">
			
			<p>If you scored high in the "B" and "G" categories, you are a very
			independent person. Your "no-nonsense" approach ensures that things
			get done. You are creative, responsible, and outgoing. You enjoy
			working with others, but can work alone. More than likely, you will
			choose an occupation that will help your community.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree. In certain occupations, it is valuable to have a master's
			degree or a Ph.D.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that help you understand
			communication and people. Social studies courses such as political
			science and sociology will be of particular interest to you.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising/Marketing<br />
						Psychology<br />
						Physical Education<br />
						Business Education
					</td>
					<td>
						Government/Civics<br />
						Art<br />
						Public Relations<br />
						Music
					</td>
					<td>
						Graphic Arts<br />
						Communications<br />
						Business Law<br />
						Political Science
					</td>
					<td>
						World Languages<br />
						Geography<br />
						Computer Technology<br />
						Sociology
					</td>
					<td>
						Photography<br />
						Health/Nutrition<br />
						Government<br />
						Economics
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. Any club or activity where communicating with others
			and/or working in a team will be valuable.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Drama/Theatre<br />
						Debate Team<br />
						Church Activities
					</td>
					<td>
						Band/Chorus<br />
						Safety Patrol<br />
						Chess Club
					</td>
					<td>
						Newspaper/Yearbook<br />
						Audio-Visual Services<br />
						Youth Organizations
					</td>
					<td>
						Language Club<br />
						Peer Counselor<br />
						Hospital Volunteer
					</td>
					<td>
						Radio/TV Activities<br />
						Photography Club
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Camp Counseling<br />
						Church Programs<br />
						Courthouse Offices
					</td>
					<td>
						Graphic Design<br />
						Libraries<br />
						Life Guarding
					</td>
					<td>
						Newspaper Offices<br />
						Political Offices<br />
						Printing Companies
					</td>
					<td>
						TV/Radio Studios<br />
						Recreation Departments<br />
						Special Olympics
					</td>
					<td>
						Theater<br />
						Youth Coaching
					</td>
				</tr>
			</table>
					</div>
			
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Support Services</h5>
			<p><em>Community College Administrator</p>
			<p>City Zoning Director</p>
			<p>Continuing Education Coordinator</p>
			<p>Teacher
				<ul>
					<li>Adult Education</li>
					<li>Public Speaking</li>
					<li>Broadcasting</li>
				</ul></p>
			<p>Chamber of Commerce Representative</p>
			<p>Visitors Bureau Representative</p>
			<p>TV/Radio Public Affairs Producer</p>
			<p>Lobbyist</p>
			<p>Clergy</p>
			<p>Church Youth Director</p>
			<p>Reservation/Ticket Agent</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Art and Design</h5>
			<p><em>Ballet/Symphony Director</p>
			<p>Ballet/Symphony Manager</p>
			<p>Museum Director</p>
			<p>City Planner</p>
			<p>Orchestra Conductor</p>
			<p>Historic Preservationist</p>
			<p>Performing Arts Personnel Director</p>
			<p>Landscape Designer</p>
			<p>Arts Festival Coordinator</p>
			<p>Exhibit Designer</p>
			<p>Photographer</p>
			<p>Cook</p>
			<p>Floral Designer</em></p>
		</div>
		<div class="col">
			<h5>Communication Services</h5>
			<p><em>Copyright Attorney</p>
			<p>Public Relations Specialist</p>
			<p>Community Affairs Director</p>
			<p>TV/Radio Talk Show Host</p>
			<p>College Marketing Specialist</p>
			<p>Cultural Marketing Specialist</p>
			<p>Broadcaster</p>
			<p>Editorial Writer</p>
			<p>Documentary Film Maker</p>
			<p>Interpreter</p>
			<p>Product Spokesperson</p>
			<p>Theatrical Press Agent</p>
			<p>Market Researcher</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Support Services</h5>
			<p><em>Community College Administrator</p>
			<p>City Zoning Director</p>
			<p>Continuing Education Coordinator</p>
			<p>Teacher
				<ul>
					<li>Adult Education</li>
					<li>Public Speaking</li>
					<li>Broadcasting</li>
				</ul></p>
			<p>Chamber of Commerce Representative</p>
			<p>Visitors Bureau Representative</p>
			<p>TV/Radio Public Affairs Producer</p>
			<p>Lobbyist</p>
			<p>Clergy</p>
			<p>Church Youth Director</p>
			<p>Reservation/Ticket Agent</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Art and Design</h5>
			<p><em>Ballet/Symphony Director</p>
			<p>Ballet/Symphony Manager</p>
			<p>Museum Director</p>
			<p>City Planner</p>
			<p>Orchestra Conductor</p>
			<p>Historic Preservationist</p>
			<p>Performing Arts Personnel Director</p>
			<p>Landscape Designer</p>
			<p>Arts Festival Coordinator</p>
			<p>Exhibit Designer</p>
			<p>Photographer</p>
			<p>Cook</p>
			<p>Floral Designer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Communication Services</h5>
			<p><em>Copyright Attorney</p>
			<p>Public Relations Specialist</p>
			<p>Community Affairs Director</p>
			<p>TV/Radio Talk Show Host</p>
			<p>College Marketing Specialist</p>
			<p>Cultural Marketing Specialist</p>
			<p>Broadcaster</p>
			<p>Editorial Writer</p>
			<p>Documentary Film Maker</p>
			<p>Interpreter</p>
			<p>Product Spokesperson</p>
			<p>Theatrical Press Agent</p>
			<p>Market Researcher</em></p>
		</div>
	</div>
	</div>




