	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Science/Mathematics (BH)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Design</h5>
			<p><em>Museum Curator</p>
			<p>Architect</p>
			<p>Archeologist</p>
			<p>Gemologist</p>
			<p>Advertising Layout Artist</p>
			<p>Designer
				<ul>
					<li>Industrial</li>
					<li>Graphic</li>
					<li>Product Development</li>
					<li>Interior</li>
					<li>Hair</li>
					<li>Jewelry</li>
					<li>Lighting</li>
				</ul>
			<p>Inventor</em>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications</h5>
			<p><em>Lawyer</p>
			<p>Technical & Scientific Publications Editor</p>
			<p>Teacher
				<ul>
					<li>Drama</li>
					<li>Speech</li>
					<li>Communications</li>
				</ul></p>
			<p>Broadcast News Analyst</p>
			<p>Writer
				<ul>
					<li>Technical</li>
					<li>Journalist</li>
					<li>Biographer</li>
					<li>Nature</li>
					<li>Textbook</li>
				</ul></p>
			<p>Video Producer</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Analysis</h5>
			<p><em>Dentist</p>
			<p>Psychologist</p>
			<p>Speech Pathologist</p>
			<p>Audiologist</p>
			<p>Physical Therapist</p>
			<p>Marketing Director</p>
			<p>Military Officer</p>
			<p>Art Therapist</p>
			<p>Librarian
				<ul>
					<li>Medical</li>
					<li>Research</li>
				</ul></p>
			<p>Statistician
				<ul>
					<li>Marketing</li>
					<li>Research</li>
					<li>Television</li>
				</ul></em></p>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Engineer
				<ul>
					<li>Civil</li>
					<li>Structural</li>
					<li>Industrial</li>
				</ul></p>
			<p>Photographer
				<ul>
					<li>Biological</li>
					<li>Nature</li>
				</ul></p>
			<p>Medical Illustrator</p>
			<p>Landscape Designer</p>
			<p>Computer Artist</p>
			<p>Cartographer</p>
			<p>Dental Technician</p>
			<p>Optician</p>
			<p>Game Inventor</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Design</h5>
			<p><em>Museum Curator</p>
			<p>Architect</p>
			<p>Archeologist</p>
			<p>Gemologist</p>
			<p>Advertising Layout Artist</p>
			<p>Designer
				<ul>
					<li>Industrial</li>
					<li>Graphic</li>
					<li>Product Development</li>
					<li>Interior</li>
					<li>Hair</li>
					<li>Jewelry</li>
					<li>Lighting</li>
				</ul>
			<p>Inventor</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications</h5>
			<p><em>Lawyer</p>
			<p>Technical & Scientific Publications Editor</p>
			<p>Teacher
				<ul>
					<li>Drama</li>
					<li>Speech</li>
					<li>Communications</li>
				</ul></p>
			<p>Broadcast News Analyst</p>
			<p>Writer
				<ul>
					<li>Technical</li>
					<li>Journalist</li>
					<li>Biographer</li>
					<li>Nature</li>
					<li>Textbook</li>
				</ul></p>
			<p>Video Producer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Analysis</h5>
			<p><em>Dentist</p>
			<p>Psychologist</p>
			<p>Speech Pathologist</p>
			<p>Audiologist</p>
			<p>Physical Therapist</p>
			<p>Marketing Director</p>
			<p>Military Officer</p>
			<p>Art Therapist</p>
			<p>Librarian
				<ul>
					<li>Medical</li>
					<li>Research</li>
				</ul></p>
			<p>Statistician
				<ul>
					<li>Marketing</li>
					<li>Research</li>
					<li>Television</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Engineer
				<ul>
					<li>Civil</li>
					<li>Structural</li>
					<li>Industrial</li>
				</ul></p>
			<p>Photographer
				<ul>
					<li>Biological</li>
					<li>Nature</li>
				</ul></p>
			<p>Medical Illustrator</p>
			<p>Landscape Designer</p>
			<p>Computer Artist</p>
			<p>Cartographer</p>
			<p>Dental Technician</p>
			<p>Optician</p>
			<p>Game Inventor</em></p>
		</div>
	</div>
	</div>

