	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Science/Mathematics (BH)</p>
			
			<div class="inter">
			
			<p>If you scored high in the "B" and "H" categories you are
			important to the future. You understand that there are always
			possibilities for improvement in any situation.  People like you
			have discovered many things about the world. You are an excellent
			thinker and are probably a no-nonsense kind of person. You are
			scientifically creative and like to ask the question, "Why?" Because
			of this, you will look for new ways of communicating and new ideas
			to communicate.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree or some post high school courses. It is helpful to have a
			master's degree or Ph.D. if you want to work in many of these
			occupations.</p>
			<p><strong>Courses you may want to take in high school and beyond(in
			addition to English & Math):</strong><br />
			In high school you should take courses that emphasize math and
			science. Any courses dealing with communication will be of great
			interest to you and will help prepare you for possible career
			opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising<br />
						Art<br />
						Trigonometry<br />
						Marketing
					</td>
					<td>
						Calculus<br />
						Chemistry<br />
						Biology<br />
						Photography
					</td>
					<td>
						Computer Sciences<br />
						Computer Technology<br />
						Communications<br />
						Public Relations
					</td>
					<td>
						Health<br />
						World Languages<br />
						Psychology<br />
						Life Science
					</td>
					<td>
						Sociology<br />
						Physics<br />
						Graphic Arts<br />
						Environmental Science
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. Any club or activity where you can communicate with
			others and use your thinking skills is what you will enjoy the
			most.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Drama/Theatre<br />
						Debate Team<br />
						Radio/TV Activities<br />
						Math/Science Club
					</td>
					<td>
						Band/Chorus<br />
						Photography Club<br />
						Hospital Volunteer<br />
						Computer Club
					</td>
					<td>
						Newspaper/Yearbook<br />
						Audio-Visual Services<br />
						Environmental Activities
					</td>
					<td>
						Language Club<br />
						Tutoring<br />
						Chess Club<br />
						Music Lessons
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
							Architect Firms<br />
							Archeological Projects<br />
							Computer Sales Company
						</td>
						<td>
							Computer Services<br />
							Electronic Stores<br />
							Engineering Firms
						</td>
						<td>
							Libraries<br />
							Medical Offices<br />
							Newspaper Offices
						</td>
						<td>
							Photographic Laboratories<br />
							Printing Companies<br />
							TV/Radio Stations
						</td>
						<td>
							Theaters<br />
							Veterinary Offices
						</td>
					</tr>
			</table>
		</div>
			
			
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Design</h5>
			<p><em>Museum Curator</p>
			<p>Architect</p>
			<p>Archeologist</p>
			<p>Gemologist</p>
			<p>Advertising Layout Artist</p>
			<p>Designer
				<ul>
					<li>Industrial</li>
					<li>Graphic</li>
					<li>Product Development</li>
					<li>Interior</li>
					<li>Hair</li>
					<li>Jewelry</li>
					<li>Lighting</li>
				</ul>
			<p>Inventor</em>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications</h5>
			<p><em>Lawyer</p>
			<p>Technical & Scientific Publications Editor</p>
			<p>Teacher
				<ul>
					<li>Drama</li>
					<li>Speech</li>
					<li>Communications</li>
				</ul></p>
			<p>Broadcast News Analyst</p>
			<p>Writer
				<ul>
					<li>Technical</li>
					<li>Journalist</li>
					<li>Biographer</li>
					<li>Nature</li>
					<li>Textbook</li>
				</ul></p>
			<p>Video Producer</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Analysis</h5>
			<p><em>Dentist</p>
			<p>Psychologist</p>
			<p>Speech Pathologist</p>
			<p>Audiologist</p>
			<p>Physical Therapist</p>
			<p>Marketing Director</p>
			<p>Military Officer</p>
			<p>Art Therapist</p>
			<p>Librarian
				<ul>
					<li>Medical</li>
					<li>Research</li>
				</ul></p>
			<p>Statistician
				<ul>
					<li>Marketing</li>
					<li>Research</li>
					<li>Television</li>
				</ul></em></p>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Engineer
				<ul>
					<li>Civil</li>
					<li>Structural</li>
					<li>Industrial</li>
				</ul></p>
			<p>Photographer
				<ul>
					<li>Biological</li>
					<li>Nature</li>
				</ul></p>
			<p>Medical Illustrator</p>
			<p>Landscape Designer</p>
			<p>Computer Artist</p>
			<p>Cartographer</p>
			<p>Dental Technician</p>
			<p>Optician</p>
			<p>Game Inventor</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Design</h5>
			<p><em>Museum Curator</p>
			<p>Architect</p>
			<p>Archeologist</p>
			<p>Gemologist</p>
			<p>Advertising Layout Artist</p>
			<p>Designer
				<ul>
					<li>Industrial</li>
					<li>Graphic</li>
					<li>Product Development</li>
					<li>Interior</li>
					<li>Hair</li>
					<li>Jewelry</li>
					<li>Lighting</li>
				</ul>
			<p>Inventor</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications</h5>
			<p><em>Lawyer</p>
			<p>Technical & Scientific Publications Editor</p>
			<p>Teacher
				<ul>
					<li>Drama</li>
					<li>Speech</li>
					<li>Communications</li>
				</ul></p>
			<p>Broadcast News Analyst</p>
			<p>Writer
				<ul>
					<li>Technical</li>
					<li>Journalist</li>
					<li>Biographer</li>
					<li>Nature</li>
					<li>Textbook</li>
				</ul></p>
			<p>Video Producer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Analysis</h5>
			<p><em>Dentist</p>
			<p>Psychologist</p>
			<p>Speech Pathologist</p>
			<p>Audiologist</p>
			<p>Physical Therapist</p>
			<p>Marketing Director</p>
			<p>Military Officer</p>
			<p>Art Therapist</p>
			<p>Librarian
				<ul>
					<li>Medical</li>
					<li>Research</li>
				</ul></p>
			<p>Statistician
				<ul>
					<li>Marketing</li>
					<li>Research</li>
					<li>Television</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Engineer
				<ul>
					<li>Civil</li>
					<li>Structural</li>
					<li>Industrial</li>
				</ul></p>
			<p>Photographer
				<ul>
					<li>Biological</li>
					<li>Nature</li>
				</ul></p>
			<p>Medical Illustrator</p>
			<p>Landscape Designer</p>
			<p>Computer Artist</p>
			<p>Cartographer</p>
			<p>Dental Technician</p>
			<p>Optician</p>
			<p>Game Inventor</em></p>
		</div>
	</div>
	</div>

