	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Social Helping (BI)</p>
			
			<div class="inter">
			
			<p>Your high scores in "B" and "I" show that you bring together many
			characteristics that can be useful to people. You are a creative and
			outgoing person, and you enjoy helping others with their problems.
			You also have the ability to communicate your ideas and thoughts
			clearly.  You may be a person who likes to teach or to plan fund
			raising programs for charity.  For you, what is important is that
			you are helping others.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree or some post high school courses.  It is helpful to have a
			master's degree or Ph.D. if you want to work in many of these
			occupations.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that help you understand
			people. Any courses in social studies or social sciences will be of
			great interest to you and help prepare you for possible career
			opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising/Marketing<br />
						Psychology<br />
						Computer Sciences<br />
						Communications
					</td>
					<td>
						Computer Technology<br />
						Broadcast/Video<br />
						Public Relations<br />
						Health/Nutrition
					</td>
					<td>
						Graphic Arts<br />
						Home Economics<br />
						Religion<br />
						Photography
					</td>
					<td>
						Law<br />
						History<br />
						Music<br />
						Art
					</td>
					<td>
						World Languages<br />
						Sociology
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. Any club or activity where you can share your ability to
			communicate and use your people skills is what you will enjoy the
			most.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Drama/Theatre<br />
						Debate Team<br />
						Childcare/Eldercare<br />
						Teaching Assistant
					</td>
					<td>
						Band/Chorus<br />
						Photography Club<br />
						Hospital Volunteer<br />
						Church Activities
					</td>
					<td>
						Newspaper/Yearbook<br />
						Audio Visual Services<br />
						Peer Counselor<br />
						Tutoring
					</td>
					<td>
						Language Club<br />
						Radio/TV Activities<br />
						Camp Counselor<br />
						Social Clubs
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising Agencies<br />
						Camp Programs<br />
						Church Programs<br />
						Restaurants
					</td>
					<td>
						Day Care Centers<br />
						Graphic Design Firms<br />
						Libraries<br />
						Special Olympics
					</td>
					<td>
						Life Guarding<br />
						Newspaper Offices<br />
						Photography Studios<br />
						Theaters
					</td>
					<td>
						Preschool Programs<br />
						Printing Companies<br />
						Recreation Department
					</td>
				</tr>
			</table>
		</div>
			
			
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Education</h5>
			<p><em>Clergy
				<ul>
					<li>Brother</li>
					<li>Minister</li>
					<li>Nun</li>
					<li>Priest</li>
					<li>Rabbi</li>
				</ul></p>
			<p>Teacher/Professor
				<ul>
					<li>Art</li>
					<li>Drama</li>
					<li>Dance</li>
					<li>Communications</li>
					<li>Music</li>
					<li>Pre-school</li>
					<li>Religion</li>
					<li>Special Education</li>
					<li>Writing</li>
				</ul></p>
			<p>Teacher's Aide</p>
			<p>Library Assistant</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Helping</h5>
			<p><em>Psychologist</p>
			<p>Public Relations Counselor</p>
			<p>Marriage Counselor</p>
			<p>Art/Music Therapy</p>
			<p>Interior Designer</p>
			<p>Cosmetologist
				<ul>
					<li>Manicurist</li>
					<li>Barber</li>
				</ul></p>
			<p>Massage Therapist</p>
			<p>Audiovisual Librarian</p>
			<p>Advertising Production Specialist</p>
			<p>Adventure Travel Coordinator</p>
			<p>Caterer</p>
			<p>Retail Salesperson</em></p>
		</div>
		<div class="col">
			<h5>Creative Performance</h5>
			<p><em>Writer
				<ul>
					<li>Author</li>
					<li>Playwright</li>
					<li>Poet</li>
					<li>Song</li>
					<li>Screen</li>
					<li>Travel</li>
				</ul></p>
			<p>Chef</p>
			<p>Photographer</p>
			<p>Radio/TV Talk Show Host</p>
			<p>Police Artist</p>
			<p>Actress/Actors</p>
			<p>Musician</p>
			<p>Singer</p>
			<p>Model</p>
			<p>Comedian</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Education</h5>
			<p><em>Clergy
				<ul>
					<li>Brother</li>
					<li>Minister</li>
					<li>Nun</li>
					<li>Priest</li>
					<li>Rabbi</li>
				</ul></p>
			<p>Teacher/Professor
				<ul>
					<li>Art</li>
					<li>Drama</li>
					<li>Dance</li>
					<li>Communications</li>
					<li>Music</li>
					<li>Pre-school</li>
					<li>Religion</li>
					<li>Special Education</li>
					<li>Writing</li>
				</ul></p>
			<p>Teacher's Aide</p>
			<p>Library Assistant</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Helping</h5>
			<p><em>Psychologist</p>
			<p>Public Relations Counselor</p>
			<p>Marriage Counselor</p>
			<p>Art/Music Therapy</p>
			<p>Interior Designer</p>
			<p>Cosmetologist
				<ul>
					<li>Manicurist</li>
					<li>Barber</li>
				</ul></p>
			<p>Massage Therapist</p>
			<p>Audiovisual Librarian</p>
			<p>Advertising Production Specialist</p>
			<p>Adventure Travel Coordinator</p>
			<p>Caterer</p>
			<p>Retail Salesperson</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Creative Performance</h5>
			<p><em>Writer
				<ul>
					<li>Author</li>
					<li>Playwright</li>
					<li>Poet</li>
					<li>Song</li>
					<li>Screen</li>
					<li>Travel</li>
				</ul></p>
			<p>Chef</p>
			<p>Photographer</p>
			<p>Radio/TV Talk Show Host</p>
			<p>Police Artist</p>
			<p>Actress/Actors</p>
			<p>Musician</p>
			<p>Singer</p>
			<p>Model</p>
			<p>Comedian</em></p>
		</div>
	</div>
	</div>



