	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Social Helping (BI)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Education</h5>
			<p><em>Clergy
				<ul>
					<li>Brother</li>
					<li>Minister</li>
					<li>Nun</li>
					<li>Priest</li>
					<li>Rabbi</li>
				</ul></p>
			<p>Teacher/Professor
				<ul>
					<li>Art</li>
					<li>Drama</li>
					<li>Dance</li>
					<li>Communications</li>
					<li>Music</li>
					<li>Pre-school</li>
					<li>Religion</li>
					<li>Special Education</li>
					<li>Writing</li>
				</ul></p>
			<p>Teacher's Aide</p>
			<p>Library Assistant</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Helping</h5>
			<p><em>Psychologist</p>
			<p>Public Relations Counselor</p>
			<p>Marriage Counselor</p>
			<p>Art/Music Therapy</p>
			<p>Interior Designer</p>
			<p>Cosmetologist
				<ul>
					<li>Manicurist</li>
					<li>Barber</li>
				</ul></p>
			<p>Massage Therapist</p>
			<p>Audiovisual Librarian</p>
			<p>Advertising Production Specialist</p>
			<p>Adventure Travel Coordinator</p>
			<p>Caterer</p>
			<p>Retail Salesperson</em></p>
		</div>
		<div class="col">
			<h5>Creative Performance</h5>
			<p><em>Writer
				<ul>
					<li>Author</li>
					<li>Playwright</li>
					<li>Poet</li>
					<li>Song</li>
					<li>Screen</li>
					<li>Travel</li>
				</ul></p>
			<p>Chef</p>
			<p>Photographer</p>
			<p>Radio/TV Talk Show Host</p>
			<p>Police Artist</p>
			<p>Actress/Actors</p>
			<p>Musician</p>
			<p>Singer</p>
			<p>Model</p>
			<p>Comedian</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Education</h5>
			<p><em>Clergy
				<ul>
					<li>Brother</li>
					<li>Minister</li>
					<li>Nun</li>
					<li>Priest</li>
					<li>Rabbi</li>
				</ul></p>
			<p>Teacher/Professor
				<ul>
					<li>Art</li>
					<li>Drama</li>
					<li>Dance</li>
					<li>Communications</li>
					<li>Music</li>
					<li>Pre-school</li>
					<li>Religion</li>
					<li>Special Education</li>
					<li>Writing</li>
				</ul></p>
			<p>Teacher's Aide</p>
			<p>Library Assistant</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Helping</h5>
			<p><em>Psychologist</p>
			<p>Public Relations Counselor</p>
			<p>Marriage Counselor</p>
			<p>Art/Music Therapy</p>
			<p>Interior Designer</p>
			<p>Cosmetologist
				<ul>
					<li>Manicurist</li>
					<li>Barber</li>
				</ul></p>
			<p>Massage Therapist</p>
			<p>Audiovisual Librarian</p>
			<p>Advertising Production Specialist</p>
			<p>Adventure Travel Coordinator</p>
			<p>Caterer</p>
			<p>Retail Salesperson</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Creative Performance</h5>
			<p><em>Writer
				<ul>
					<li>Author</li>
					<li>Playwright</li>
					<li>Poet</li>
					<li>Song</li>
					<li>Screen</li>
					<li>Travel</li>
				</ul></p>
			<p>Chef</p>
			<p>Photographer</p>
			<p>Radio/TV Talk Show Host</p>
			<p>Police Artist</p>
			<p>Actress/Actors</p>
			<p>Musician</p>
			<p>Singer</p>
			<p>Model</p>
			<p>Comedian</em></p>
		</div>
	</div>
	</div>



