	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Business/Management (AC)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AC Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business</h5>
			<p><em>Agricultural Economist</p>
			<p>Museum Director</p>
			<p>Agribusiness Consultant</p>
			<p>Range Manager</p>
			<p>Union Leader</p>
			<p>Farm Broker</p>
			<p>Factory Manager</p>
			<p>Warehouse Supervisor</p>
			<p>Auctioneer</p>
			<p>Pet Shop Owner/Worker</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Outdoor Management</h5>
			<p><em>Nature Scientist
				<ul>
					<li>Horticulturist</li>
				</ul>
				</p>
			<p>Wildlife Manager</p>
			<p>Recreation Administrator</p>
			<p>Resort Manager</p>
			<p>Farm Manager</p>
			<p>Rancher</p>
			<p>Orchard Manager</p>
			<p>County Fair Organizer</p>
			<p>Nursery Manager/Worker</em></p>
		</div>
		<div class="col">
			<h5>Environment</h5>
			<p><em>Regional Planner</p>
			<p>Environmentalist</p>
			<p>Environmental Health Inspector</p>
			<p>Environmental Risk Manager</p>
			<p>Wetlands Manager</p>
			<p>Safety/Traffic Engineer</p>
			<p>Logging Supervisor</p>
			<p>Water Quality Technologist</p>
			<p>Agricultural Technician</p>
			<p>Waste Management Technician</p>
			<p>Forestry Technician</em></p>
		</div>
	</div>
	</div>

	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business</h5>
			<p><em>Agricultural Economist<br />
			<p><em>Agricultural Economist</p>
			<p>Museum Director</p>
			<p>Agribusiness Consultant</p>
			<p>Range Manager</p>
			<p>Union Leader</p>
			<p>Farm Broker</p>
			<p>Factory Manager</p>
			<p>Warehouse Supervisor</p>
			<p>Auctioneer</p>
			<p>Pet Shop Owner/Worker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Outdoor Management</h5>
			<p><em>Nature Scientist
				<ul>
					<li>Horticulturist</li>
				</ul>
				</p>
			<p>Wildlife Manager</p>
			<p>Recreation Administrator</p>
			<p>Resort Manager</p>
			<p>Farm Manager</p>
			<p>Rancher</p>
			<p>Orchard Manager</p>
			<p>County Fair Organizer</p>
			<p>Nursery Manager/Worker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<p><h5>Environment</h5>
			<p><em>Regional Planner</p>
			<p>Environmentalist</p>
			<p>Environmental Health Inspector</p>
			<p>Environmental Risk Manager</p>
			<p>Wetlands Manager</p>
			<p>Safety/Traffic Engineer</p>
			<p>Logging Supervisor</p>
			<p>Water Quality Technologist</p>
			<p>Agricultural Technician</p>
			<p>Waste Management Technician</p>
			<p>Forestry Technician</em></p>
		</div>
	</div>
	</div>
