	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Clerical/Administrative (CD)</p>
			
			<div class="inter">
			
			<p>If you had a high score in categories "C" and "D" you have a head
			for business. You are a good thinker and know how to get what you
			want. You are probably goal-oriented and prefer to know what you are
			working toward.  You may be an outgoing person who likes to lead, or
			you may be a quiet person who likes working with numbers. Either
			way, you know how get the job done. You will benefit from learning
			to understand business.</p>
			<p>Most occupations in this pairing require a bachelor's degree.
			Many others require some post-high school courses.  In most of the
			occupations listed under this pairing, the more education you have
			the better your chances of employment. The competition for these
			jobs is tough. You will need to give yourself every advantage
			possible.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you will want to take courses that allow you to
			express your thoughts and ideas.  You will also want to take courses
			that help you to understand others and the world of business.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Technology Education<br />
						Office Administration<br />
						Computer Sciences<br />
						Advertising/Marketing
					</td>
					<td>
						Business Law<br />
						Public Relations<br />
						Communications<br />
						Computer Technology
					</td>
					<td>
						Computer Programming<br />
						Government/Civics<br />
						Office Technology<br />
						Business Education
					</td>
					<td>
						Economics<br />
						Advertising<br />
						Sociology<br />
						Accounting
					</td>
					<td>
						World Languages<br />
						Business Math<br />
						Bookkeeping
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			Experience is an important thing! When you are looking for ways to
			fill your time with a fun activity or a part-time job, think about
			working in places where you are solving problems and using your
			ability to negotiate. Don't forget to find a place where you can
			show how dependable you are.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Junior Achievement<br />
						Newspaper/Yearbook<br />
						Office Assistant
					</td>
					<td>
						Class Officer<br />
						Exchange Programs<br />
						Teaching Assistant
					</td>
					<td>
						Audio/Visual Services<br />
						Computer Assistant<br />
						Library Assistant
					</td>
					<td>
						Future Business Leaders<br />
						Community Volunteer
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting Firms<br />
						Theaters<br />
						Radio/TV Studios<br />
						Photography Studios
					</td>
					<td>
						Libraries<br />
						Newspapers<br />
						Retail Stores<br />
						Receptionist
					</td>
					<td>
						Data Entry/Processing<br />
						Advertising Agencies<br />
						Temporary Agencies<br />
						Graphic Design Firms
					</td>
					<td>
						Printing Companies<br />
						Telephone Sales<br />
						Clerical Offices<br />
						Restaurants
					</td>
				</tr>
			</table>
		</div>
			
			
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CD Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business Sales</h5>
			<p><em>Computer Sales Representative</p>
			<p>Business Machine Sales Representative</p>
			<p>Insurance Sales Agent</p>
			<p>Real Estate Agent/Broker</p>
			<p>Personnel Consultant</p>
			<p>Analyst
				<ul>
					<li>Marketing</li>
					<li>Stock</li>
				</ul></p>
			<p>Sales Account Supervisor</p>
			<p>Travel Agent</p>
			<p>Sales Support</p>
			<p>Cashier</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business Administrative</h5>
			<p><em>Personnel Director</p>
			<p>Human Resources Manager</p>
			<p>Data Processing Manager</p>
			<p>Facilities Manager</p>
			<p>Office Manager</p>
			<p>Retail Buyer</p>
			<p>Employee Benefits Manager</p>
			<p>Executive Secretary</p>
			<p>Underwriter</p>
			<p>Stock Transfer Clerk</p>
			<p>Personnel Clerk</em></p>
		</div>
		<div class="col">
			<h5>Business Financial</h5>
			<p><em>Chief Financial Officer</p>
			<p>Statistician</p>
			<p>Economic Researcher</p>
			<p>Financial Planner</p>
			<p>Bank Loan Officer</p>
			<p>Auditor</p>
			<p>Bookkeeper</p>
			<p>Tax Preparer</p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Statistical</li>
				</ul></p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business Sales</h5>
			<p><em>Computer Sales Representative</p>
			<p>Business Machine Sales Representative</p>
			<p>Insurance Sales Agent</p>
			<p>Real Estate Agent/Broker</p>
			<p>Personnel Consultant</p>
			<p>Analyst
				<ul>
					<li>Marketing</li>
					<li>Stock</li>
				</ul></p>
			<p>Sales Account Supervisor</p>
			<p>Travel Agent</p>
			<p>Sales Support</p>
			<p>Cashier</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business Administrative</h5>
			<p><em>Personnel Director</p>
			<p>Human Resources Manager</p>
			<p>Data Processing Manager</p>
			<p>Facilities Manager</p>
			<p>Office Manager</p>
			<p>Retail Buyer</p>
			<p>Employee Benefits Manager</p>
			<p>Executive Secretary</p>
			<p>Underwriter</p>
			<p>Stock Transfer Clerk</p>
			<p>Personnel Clerk</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Business Financial</h5>
			<p><em>Chief Financial Officer</p>
			<p>Statistician</p>
			<p>Economic Researcher</p>
			<p>Financial Planner</p>
			<p>Bank Loan Officer</p>
			<p>Auditor</p>
			<p>Bookkeeper</p>
			<p>Tax Preparer</p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Statistical</li>
				</ul></p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>

	