	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Protective/Military Service (CE)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CE Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Management</h5>
			<em>Education Director</p>
			Operations Manager</p>
			Urban Planner</p>
			Food Service Manager</p>
			Air Traffic Controller</p>
			Funeral Director</p>
			Officer's Club Manager</p>
			Construction Manager</p>
			Store Manager</p>
			Aircraft Sales Representative</p>
			Theater Director</p>
			Auto Detailer</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Finance & Business DevelopmentM</h5>
			<em>Auditor</p>
			Management Consultant</p>
			Benefits Administrator</p>
			Financial Aid Officer</p>
			Financial Planner</p>
			Organizational Developer</p>
			Contract Administrator</p>
			Revenue Officer</p>
			Bank Examiner</p>
			Job Development Specialist</p>
			Stock Broker</p>
			Payroll Specialist</em></p>
		</div>
		<div class="col">
			<h5>Law & Civil Service</h5>
			<em>Attach&eacute;</p>
			Foreign Service Officer</p>
			Environmental Project Manager</p>
			Communications Manager</p>
			Environmental Protection Specialist</p>
			Secret Service Agent</p>
			FBI Agent</p>
			Police Agent</p>
			Fire Chief</p>
			Intelligence Officer</p>
			Recruiter</p>
			Safety Engineer</p>
			Firefighter</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Management</h5>
			<em>Education Director</p>
			Operations Manager</p>
			Urban Planner</p>
			Food Service Manager</p>
			Air Traffic Controller</p>
			Funeral Director</p>
			Officer's Club Manager</p>
			Construction Manager</p>
			Store Manager</p>
			Aircraft Sales Representative</p>
			Theater Director</p>
			Auto Detailer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Finance & Business DevelopmentM</h5>
			<em>Auditor</p>
			Management Consultant</p>
			Benefits Administrator</p>
			Financial Aid Officer</p>
			Financial Planner</p>
			Organizational Developer</p>
			Contract Administrator</p>
			Revenue Officer</p>
			Bank Examiner</p>
			Job Development Specialist</p>
			Stock Broker</p>
			Payroll Specialist</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Law & Civil Service</h5>
			<em>Attach&eacute;</p>
			Foreign Service Officer</p>
			Environmental Project Manager</p>
			Communications Manager</p>
			Environmental Protection Specialist</p>
			Secret Service Agent</p>
			FBI Agent</p>
			Police Agent</p>
			Fire Chief</p>
			Intelligence Officer</p>
			Recruiter</p>
			Safety Engineer</p>
			Firefighter</em></p>
		</div>
	</div>
	</div>

