	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Protective/Military Service (CE)</p>
			
			<div class="inter">
			
			<p>If you show high scores in categories "C" and "E", you are a
			person who knows how to make things happen. You are adventurous and
			like exploring new possibilities.  You especially like to take risks
			and try new things.  You make a good leader. You will want to
			combine your strong interest in business with your adventurous
			spirit.</p>
			<p>Many of the occupations in this pairing require some sort of
			specialized training after high school. Some require college level
			courses.  Others require training programs provided by the company
			or firm that hires you.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that allow you to continue
			to learn about business. You will want to take courses that help you
			to understand people as well.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising<br />
						Sociology<br />
						Life Sciences<br />
						Economics
					</td>
					<td>
						Business Math<br />
						Political Science<br />
						Physical Education<br />
						Communications
					</td>
					<td>
						Physics<br />
						Geography<br />
						Psychology<br />
						Marketing
					</td>
					<td>
						Government/Civics<br />
						Environmental Science<br />
						Technology Education
					</td>
					<td>
						Business Law<br />
						Public Relations<br />
						Business Education
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations you
			may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. You will enjoy any club or activity that involves
			working with others as a part of a team.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Jr. Achievement<br />
						Exchange Programs<br />
						Computer Activities<br />
						Future Business Leaders
					</td>
					<td>
						Yearbook<br />
						ROTC<br />
						Scouts<br />
						Band
					</td>
					<td>
						Class Officer<br />
						Flight Training<br />
						Parks/Recreation<br />
						Camp Activities
					</td>
					<td>
						Community Volunteer<br />
						Martial Arts<br />
						Athletics
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time job:</strong><br />
			These places may offer valuable opportunities to help you decide what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising Agencies<br />
						Data Processing<br />
						Graphic Design<br />
						Life Guarding<br />
						Photography Studios<br />
					</td>
					<td>
						Temporary Agencies<br />
						Camp Counseling<br />
						Equipment Operation<br />
						Radio Stations
					</td>
					<td>
						Construction Sites<br />
						Equipment Repair<br />
						Libraries<br />
						Printing Companies
					</td>
					<td>
						Recreation/Parks<br />
						Gyms<br />
						Newspapers<br />
						TV Studios
					</td>
				</tr>
			</table>
		</div>
			
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CE Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Management</h5>
			<em>Education Director</p>
			Operations Manager</p>
			Urban Planner</p>
			Food Service Manager</p>
			Air Traffic Controller</p>
			Funeral Director</p>
			Officer's Club Manager</p>
			Construction Manager</p>
			Store Manager</p>
			Aircraft Sales Representative</p>
			Theater Director</p>
			Auto Detailer</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Finance & Business DevelopmentM</h5>
			<em>Auditor</p>
			Management Consultant</p>
			Benefits Administrator</p>
			Financial Aid Officer</p>
			Financial Planner</p>
			Organizational Developer</p>
			Contract Administrator</p>
			Revenue Officer</p>
			Bank Examiner</p>
			Job Development Specialist</p>
			Stock Broker</p>
			Payroll Specialist</em></p>
		</div>
		<div class="col">
			<h5>Law & Civil Service</h5>
			<em>Attach&eacute;</p>
			Foreign Service Officer</p>
			Environmental Project Manager</p>
			Communications Manager</p>
			Environmental Protection Specialist</p>
			Secret Service Agent</p>
			FBI Agent</p>
			Police Agent</p>
			Fire Chief</p>
			Intelligence Officer</p>
			Recruiter</p>
			Safety Engineer</p>
			Firefighter</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Management</h5>
			<em>Education Director</p>
			Operations Manager</p>
			Urban Planner</p>
			Food Service Manager</p>
			Air Traffic Controller</p>
			Funeral Director</p>
			Officer's Club Manager</p>
			Construction Manager</p>
			Store Manager</p>
			Aircraft Sales Representative</p>
			Theater Director</p>
			Auto Detailer</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Finance & Business DevelopmentM</h5>
			<em>Auditor</p>
			Management Consultant</p>
			Benefits Administrator</p>
			Financial Aid Officer</p>
			Financial Planner</p>
			Organizational Developer</p>
			Contract Administrator</p>
			Revenue Officer</p>
			Bank Examiner</p>
			Job Development Specialist</p>
			Stock Broker</p>
			Payroll Specialist</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Law & Civil Service</h5>
			<em>Attach&eacute;</p>
			Foreign Service Officer</p>
			Environmental Project Manager</p>
			Communications Manager</p>
			Environmental Protection Specialist</p>
			Secret Service Agent</p>
			FBI Agent</p>
			Police Agent</p>
			Fire Chief</p>
			Intelligence Officer</p>
			Recruiter</p>
			Safety Engineer</p>
			Firefighter</em></p>
		</div>
	</div>
	</div>

