	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Technology (CF)</p>
			
			<div class="inter">
			
			<p>With a "CF" interest, you will be a valuable employee. You like
			working with people on projects or assignments that have to do with
			biotechnology, information systems, engineering and environmental in
			the technology industries. The field of business is becoming more
			technical and fast-paced. This means that you will have many
			opportunities to find the occupation that suits you. You will be
			happiest in an occupation that allows you to use your ability to
			understand how things work and solve problems.</p>
			<p>Many of the occupations in this pairing require some sort of
			specialized and/or technical training after high school. Some
			require college degrees or college level courses.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that allow you to continue to
			learn about business. Technology courses will be important too.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising/Marketing<br />
						Computer Programming<br />
						Technology Education
					</td>
					<td>
						Trade & Industry<br />
						Business Education<br />
						Political Science
					</td>
					<td>
						Psychology<br />
						Sociology<br />
						Economics
					</td>
					<td>
						Business Law<br />
						Computer Sciences<br />
						Government/Civics
					</td>
					<td>
						Public Relations<br />
						History<br />
						Accounting
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations you
			may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. Any club or activity that involves working with
			technology and communicating will be valuable.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Junior Achievement<br />
						Newspaper/Yearbook<br />
						Library Assistant<br />
						Chess Club

					</td>
					<td>
						Audio/Visual Services<br />
						Class Officer<br />
						Radio/TV Club<br />
						Community Volunteer
					</td>
					<td>
						Math/Science Club<br />
						Destination Imagination<br />
						Future Business Leaders
					</td>
					<td>
						Odyssey of The Mind<br />
						Computer Activities<br />
						Future Problem Solvers
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Appliance Repair<br />
						Newspapers<br />
						Photography Studios<br />
						Small Engine Repair
					</td>
					<td>
						Equipment Operations<br />
						Graphic Design Firms<br />
						Printing Companies
					</td>
					<td>
						Delivery Service<br />
						Equipment Repair Shops<br />
						Photographic Laboratories
					</td>
					<td>
						TV/Radio Stations<br />
						Telephone Sales<br />
						Data Processing
					</td>
				</tr>
			</table>
		</div>
			
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CF Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business & Community Service</h5>
			<em>Athletic Director</p>
			Safety Engineer</p>
			Police Chief</p>
			Sheriff</p>
			Deputy Sheriff</p>
			Youth Services Director</p>
			Fitness Club Manager</p>
			Aircraft Sales Representative</p>
			Professional Athlete</p>
			Real Estate Agent</p>
			Machinist</p>
			Corrections Officer</p>
			Cleaning Service Owner</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business & Environment</h5>
			<em>Environmental Risk Manager</p>
			Land Acquisition Professional</p>
			Solid Waste Management</p>
			Environmental Protection Specialist</p>
			Environmental Project Manager</p>
			Fire Chief</p>
			Park Ranger</p>
			Park & Recreation Manager</p>
			Forestry Technician</p>
			Firefighter</p>
			Rancher</p>
			Logging Supervisor</em></p>
		</div>
		<div class="col">
			<h5>Business & Technology</h5>
			<em>Information Manager</p>
			Computer Specialist</p>
			Database Manager</p>
			Air Traffic Controller</p>
			Construction Manager</p>
			Building Contractor</p>
			Computer Sales Representative</p>
			Software Sales Representative</p>
			Computer Engineer</p>
			Industrial Production Manager</p>
			Computer Store Manager</p>
			Public Service Technician</p>
			Truck Driver</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business & Community Service</h5>
			<em>Athletic Director</p>
			Safety Engineer</p>
			Police Chief</p>
			Sheriff</p>
			Deputy Sheriff</p>
			Youth Services Director</p>
			Fitness Club Manager</p>
			Aircraft Sales Representative</p>
			Professional Athlete</p>
			Real Estate Agent</p>
			Machinist</p>
			Corrections Officer</p>
			Cleaning Service Owner</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business & Environment</h5>
			<em>Environmental Risk Manager</p>
			Land Acquisition Professional</p>
			Solid Waste Management</p>
			Environmental Protection Specialist</p>
			Environmental Project Manager</p>
			Fire Chief</p>
			Park Ranger</p>
			Park & Recreation Manager</p>
			Forestry Technician</p>
			Firefighter</p>
			Rancher</p>
			Logging Supervisor</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Business & Technology</h5>
			<em>Information Manager</p>
			Computer Specialist</p>
			Database Manager</p>
			Air Traffic Controller</p>
			Construction Manager</p>
			Building Contractor</p>
			Computer Sales Representative</p>
			Software Sales Representative</p>
			Computer Engineer</p>
			Industrial Production Manager</p>
			Computer Store Manager</p>
			Public Service Technician</p>
			Truck Driver</em></p>
		</div>
	</div>
	</div>

