	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Technology (CF)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CF Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business & Community Service</h5>
			<em>Athletic Director</p>
			Safety Engineer</p>
			Police Chief</p>
			Sheriff</p>
			Deputy Sheriff</p>
			Youth Services Director</p>
			Fitness Club Manager</p>
			Aircraft Sales Representative</p>
			Professional Athlete</p>
			Real Estate Agent</p>
			Machinist</p>
			Corrections Officer</p>
			Cleaning Service Owner</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business & Environment</h5>
			<em>Environmental Risk Manager</p>
			Land Acquisition Professional</p>
			Solid Waste Management</p>
			Environmental Protection Specialist</p>
			Environmental Project Manager</p>
			Fire Chief</p>
			Park Ranger</p>
			Park & Recreation Manager</p>
			Forestry Technician</p>
			Firefighter</p>
			Rancher</p>
			Logging Supervisor</em></p>
		</div>
		<div class="col">
			<h5>Business & Technology</h5>
			<em>Information Manager</p>
			Computer Specialist</p>
			Database Manager</p>
			Air Traffic Controller</p>
			Construction Manager</p>
			Building Contractor</p>
			Computer Sales Representative</p>
			Software Sales Representative</p>
			Computer Engineer</p>
			Industrial Production Manager</p>
			Computer Store Manager</p>
			Public Service Technician</p>
			Truck Driver</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business & Community Service</h5>
			<em>Athletic Director</p>
			Safety Engineer</p>
			Police Chief</p>
			Sheriff</p>
			Deputy Sheriff</p>
			Youth Services Director</p>
			Fitness Club Manager</p>
			Aircraft Sales Representative</p>
			Professional Athlete</p>
			Real Estate Agent</p>
			Machinist</p>
			Corrections Officer</p>
			Cleaning Service Owner</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business & Environment</h5>
			<em>Environmental Risk Manager</p>
			Land Acquisition Professional</p>
			Solid Waste Management</p>
			Environmental Protection Specialist</p>
			Environmental Project Manager</p>
			Fire Chief</p>
			Park Ranger</p>
			Park & Recreation Manager</p>
			Forestry Technician</p>
			Firefighter</p>
			Rancher</p>
			Logging Supervisor</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Business & Technology</h5>
			<em>Information Manager</p>
			Computer Specialist</p>
			Database Manager</p>
			Air Traffic Controller</p>
			Construction Manager</p>
			Building Contractor</p>
			Computer Sales Representative</p>
			Software Sales Representative</p>
			Computer Engineer</p>
			Industrial Production Manager</p>
			Computer Store Manager</p>
			Public Service Technician</p>
			Truck Driver</em></p>
		</div>
	</div>
	</div>

