	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Public Service (CG)</p>
			
			<div class="inter">
			
			<p>If you scored high in the "C" and "G" categories, you are people-
			oriented. You have leadership ability and can persuade others. You
			feel a responsibility to others. You probably want to work in ways
			that can help your friends, your family, and your community.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree. In some of these jobs, it helps to have a master's degree or
			a Ph.D.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that help you to understand
			business practices and people. Social studies courses such as
			political science and sociology may be of interest to you.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising/Marketing<br />
						Computer Technology<br />
						Computer Sciences<br />
						Health/Nutrition
					</td>
					<td>
						Government/Civics<br />
						Business Math<br />
						History<br />
						Political Science
					</td>
					<td>
						Sociology<br />
						Business Law<br />
						Communications<br />
						Graphic Arts
					</td>
					<td>
						World Languages<br />
						Psychology<br />
						Criminal Justice<br />
						Accounting
					</td>
					<td>
						Business Education<br />
						Public Relations<br />
						Physical Education
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations you
			may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. Any club or activity where communicating with others
			and/or working for good causes would be helpful.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Class Officer<br />
						Exchange Programs<br />
						Youth Organizations
					</td>
					<td>
						Future Business Leaders<br />
						Junior Achievement<br />
						Hospital Volunteer
					</td>
					<td>
						Safety Patrol<br />
						Peer Counselor<br />
						Yearbook
					</td>
					<td>
						Church Activities<br />
						Computer Activities<br />
						Community Volunteer
					</td>
					<td>
						Chess Club<br />
						Camp Counselor<br />
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting Firms<br />
						Company Offices<br />
						Legal Offices<br />
						Newspaper Offices<br />
						Telephone Sales
					</td>
					<td>
						Courthouse Offices<br />
						Recreation Departments<br />
						Office Temp. Agencies<br />
						Graphic Design Firms<br />
						TV/Radio Studios
					</td>
					<td>
						Retail Stores<br />
						Church Programs<br />
						Libraries<br />
						Restaurants<br />
						Life Guarding
					</td>
					<td>
						Political Offices<br />
						Camp Counseling<br />
						Special Olympics<br />
						Youth Coaching
					</td>
				</tr>
			</table>
		</div>
			
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Public Service</h5>
			<p><em>College President/Administrator</p>
			<p>Publisher</p>
			<p>City Manager</p>
			<p>Social Work Agency Director</p>
			<p>Hospital Marketing Director</p>
			<p>Police Chief</p>
			<p>Elected Public Official</p>
			<p>Director of Security</p>
			<p>Continuing Education Coordinator</p>
			<p>Detective</p>
			<p>Bank Teller</p>
			<p>Security Guard</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Management</h5>
			<p><em>Airport Manager</p>
			<p>Hospital Administrator</p>
			<p>Public School Administrator</p>
			<p>Hotel Manager</p>
			<p>Shopping Mall Manager</p>
			<p>Trade Show Coordinator</p>
			<p>Military Officer</p>
			<p>Press Secretary</p>
			<p>Plant (Manufacturing) Manager</p>
			<p>Postal Supervisor</p>
			<p>Retail Sales Manager</p>
			<p>Assistant Restaurant Manager</em></p>
		</div>
		<div class="col">
			<h5>Business & Industry</h5>
			<p><em>Corporate Lawyer</p>
			<p>Patent Lawyer</p>
			<p>Industrial Psychologist</p>
			<p>City Housing Director</p>
			<p>Personnel Director</p>
			<p>Marketing Director</p>
			<p>Mortgage Loan Officer</p>
			<p>Financial Manager</p>
			<p>Corporate Trainer</p>
			<p>Land Developer</p>
			<p>Personnel Consultant</p>
			<p>Auctioneer</p>
			<p>Retail Salesperson</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Public Service</h5>
			<p><em>College President/Administrator</p>
			<p>Publisher</p>
			<p>City Manager</p>
			<p>Social Work Agency Director</p>
			<p>Hospital Marketing Director</p>
			<p>Police Chief</p>
			<p>Elected Public Official</p>
			<p>Director of Security</p>
			<p>Continuing Education Coordinator</p>
			<p>Detective</p>
			<p>Bank Teller</p>
			<p>Security Guard</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Management</h5>
			<p><em>Airport Manager</p>
			<p>Hospital Administrator</p>
			<p>Public School Administrator</p>
			<p>Hotel Manager</p>
			<p>Shopping Mall Manager</p>
			<p>Trade Show Coordinator</p>
			<p>Military Officer</p>
			<p>Press Secretary</p>
			<p>Plant (Manufacturing) Manager</p>
			<p>Postal Supervisor</p>
			<p>Retail Sales Manager</p>
			<p>Assistant Restaurant Manager</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Business & Industry</h5>
			<p><em>Corporate Lawyer</p>
			<p>Patent Lawyer</p>
			<p>Industrial Psychologist</p>
			<p>City Housing Director</p>
			<p>Personnel Director</p>
			<p>Marketing Director</p>
			<p>Mortgage Loan Officer</p>
			<p>Financial Manager</p>
			<p>Corporate Trainer</p>
			<p>Land Developer</p>
			<p>Personnel Consultant</p>
			<p>Auctioneer</p>
			<p>Retail Salesperson</em></p>
		</div>
	</div>
	</div>


