<span class="header1">Business/Management paired with Public Service
(CG)</span>

<p>If you scored high in the "C" and "G" categories, you are people-
oriented. You have leadership ability and can persuade others. You
feel a responsibility to others. You probably want to work in ways
that can help your friends, your family, and your community.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree. In some of these jobs, it helps to have a master's degree or
a Ph.D.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that help you to understand
business practices and people. Social studies courses such as
political science and sociology will be of interest to you.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising/Marketing<br />
			Computer Technology<br />
			Computer Sciences<br />
			Health/Nutrition
		</td>
		<td>
			Government/Civics<br />
			Business Math<br />
			History<br />
			Political Science
		</td>
		<td>
			Sociology<br />
			Business Law<br />
			Communications<br />
			Graphic Arts
		</td>
		<td>
			Foreign Languages<br />
			Psychology<br />
			Criminal Justice<br />
			Accounting
		</td>
		<td>
			Business Education<br />
			Public Relations<br />
			Physical Education
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations you
may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. Any club or activity where communicating with others
and/or working for good causes would be helpful.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Class Officer<br />
			Exchange Programs<br />
			Youth Organizations
		</td>
		<td>
			Future Business Leaders<br />
			Junior Achievement<br />
			Hospital Volunteer
		</td>
		<td>
			Safety Patrol<br />
			Peer Counselor<br />
			Yearbook
		</td>
		<td>
			Church Activities<br />
			Computer Activities<br />
			Community Volunteer
		</td>
		<td>
			Chess Club<br />
			Camp Counselor<br />
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting Firms<br />
			Company Offices<br />
			Legal Offices<br />
			Newspaper Offices<br />
			Telephone Sales
		</td>
		<td>
			Courthouse Offices<br />
			Recreation Departments<br />
			Office Temp. Agencies<br />
			Graphic Design Firms<br />
			TV/Radio Studios
		</td>
		<td>
			Retail Stores<br />
			Church Programs<br />
			Libraries<br />
			Restaurants<br />
			Life Guarding
		</td>
		<td>
			Political Offices<br />
			Camp Counseling<br />
			Special Olympics<br />
			Youth Coaching
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">CG Career
Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%"
align="left"><strong>More People Oriented</strong></td>
					<td width="33%"
align="center"><strong><----------></strong></td>
					<td width="33%"
align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0"
cellspacing="0" height="400">
				<tr align="center"
height="33%"><td><strong>More<br /></strong></td></tr>
				<tr align="center"
height="33%"><td><strong>Education<br />or<br />Training<br />Require
d</strong></td></tr>
				<tr align="center"
height="33%"><td><strong><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span
class="header2">Public Service</span><br /><br />
						<em>College
President/Administrator<br /><br />
						Publisher<br /><br />
						City
Manager<br /><br />
						Social Work Agency
Director<br /><br />
						Hospital Marketing
Director<br /><br />
						Police
Chief<br /><br />
						Elected Public
Official<br /><br />
						Director of
Security<br /><br />
						Continuing Education
Coordinator<br /><br />
						Detective<br /><br />
						Bank
Teller<br /><br />
						Security Guard</em>
					</td>
					<td width="33%">
						<span
class="header2">Management</span><br /><br />
						<em>Airport
Manager<br /><br />
						Hospital
Administrator<br /><br />
						Public School
Administrator<br /><br />
						Hotel
Manager<br /><br />
						Shopping Mall
Manager<br /><br />
						Trade Show
Coordinator<br /><br />
						Military
Officer<br /><br />
						Press
Secretary<br /><br />
						Plant
(Manufacturing) Manager<br /><br />
						Postal
Supervisor<br /><br />
						Retail Sales
Manager<br /><br />
						Assistant Restaurant
Manager</em>
					</td>
					<td width="33%">
						<span
class="header2">Business & Industry</span><br /><br />
						<em>Corporate
Lawyer<br /><br />
						Patent
Lawyer<br /><br />
						Industrial
Psychologist<br /><br />
						City Housing
Director<br /><br />
						Personnel
Director<br /><br />
						Marketing
Director<br /><br />
						Mortgage Loan
Officer<br /><br />
						Financial
Manager<br /><br />
						Corporate
Trainer<br /><br />
						Land
Developer<br /><br />
						Personnel
Consultant<br /><br />

	Auctioneer<br /><br />
						Retail
Salesperson</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">PUBLIC SERVICE</span>
<p>People who do well in this field are good leaders. They also want
to provide some sort of service to the community.</p>

<hr size="1" />

	<span class="header2">School Principal</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/1387.jpg"
width="100" height="100" border="0" alt="School Principal" />
	<span class="header3">Job Description</span>
	<blockquote>A school principal is responsible for the day-to-
day management of the school. As a principal, you would work very
closely with teachers to make sure that students were being taught
well. You would also work to keep students' parents and the members
of the community satisfied.  The school board would hire the
teachers and other employees, but you would interview them and make
an assessment of them before they were hired.</blockquote>
	<span class="header3">Education</span>
	<blockquote>In most public schools, principals, assistant
principals, and school district administrators need a master's
degree in education administration or educational leadership. Some
principals and central office administrators have a doctorate or
specialized degree in education administration.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of school principals was $92,510 in
May 2016.</blockquote>

<hr size="1" />

	<span class="header2">Government
Legislator - Elected Official</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/1403.jpg"
width="100" height="100" border="0" alt="Government Legislator" />
	<span class="header3">Job Description</span>
	<blockquote>A government legislator works with other elected
officials to pass laws. The purpose of these laws is to make
improvements or solve problems. It is possible to serve as a state
or federal legislator.  In either case, those who lived in your
community would vote you into office.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Legislators do not have to have a degree, but
most people who are elected do have a degree. The most common
degrees are law, public administration, and political science. In
addition, people vote for candidates who have experience in
planning. They also prefer legislators who can negotiate and
motivate other people.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of Government
legislators/elected officials was $23,470 in May 2016.
</blockquote>

<hr size="1" />

	<span class="header2">Police Detective</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a police detective, you would investigate
crimes. You would try to find out what happened and who was
involved. This is an exciting occupation. But it can be a dangerous
job too.  To do this job well you must be able to look at a crime
scene and take in as much information as possible. You also must be
a good listener so that you can take in information while a witness
or suspect is talking.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Applicants usually must have at least a high
school education and some departments require one or two years of
college coursework or, in some cases, a college degree. Most police
and detectives learn much of what they need to know on the job,
often in their agency's police academy.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of police detectives was
$61,600 in May 2016. </blockquote>

<hr size="1" />

<span class="header1">MANAGEMENT</span>
<p>The occupations in this field are for people who like to oversee
the work of others.</p>

<hr size="1" />

	<span class="header2">Medical and Health Services
Manager</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a medical and health services manager, you
would be responsible for the day-to-day running of a health care
facility such as a hospital, clinic or hospice. You would be in
charge of hiring employees and budgeting money. You might also help
to raise money to keep the facility going. To do well in this job
you need business skills.  You also need leadership and people
skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a master's degree for this job. This
degree might be in hospital or health administration. It might also
be in public health.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of medical and health
services managers was $96,540 in May 2016.
</blockquote>

<hr size="1" />

	<span class="header2">Hotel Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/43096.jpg"
width="100" height="100" border="0" alt="Hotel Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Hotels are an important part of the community.
The person who runs a hotel is called a hotel manager. As a hotel
manager, you would be responsible for making sure the guests are
comfortable during their stay. One of the most important duties you
would have is to make sure that the employees are doing their jobs
properly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most large, full-service hotel chains usually
hire people who have a bachelor's degree in business, hotel, or
hospitality management for management trainee positions; however, a
liberal arts degree coupled with experience in the hospitality field
may be sufficient. At other hotels, especially those with fewer
services, employers look for applicants with an associate degree or
certificate in hotel, restaurant, or hospitality management along
with experience. Formal internships or part-time or summer work in a
hotel are an asset. Most degree programs include work-study
opportunities. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of lodging managers was
$51,840 in May 2016.</blockquote>

<hr size="1" />

	<span class="header2">Food Service Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/43129.jpg"
width="100" height="100" border="0" alt="Assistant Restaurant
Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Food service managers are responsible for the
daily operations of restaurants to prepare and serve meals and
beverages and ensure that customers are satisfied with their dining
experience. In addition, they oversee the inventory and ordering of
food, equipment, and supplies and arrange for the routine
maintenance and upkeep of the restaurant's equipment and facilities.
Managers generally are responsible for all of the administrative and
human-resource functions of running the business, including
recruiting new employees and monitoring employee performance and
training. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Both 2- and 4-year degree programs provide
instruction in nutrition, sanitation, and food planning and
preparation, as well as accounting, business law and management, and
computer science. Some programs combine classroom and on-the-job
experience. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of food service managers
was $50,820 in May 2016. </blockquote>

<hr size="1" />

<span class="header1">BUSINESS & INDUSTRY</span>
<p>If you like to be challenged mentally, you may want to consider
this occupational field. The occupations in this field need people
who are good at solving problems.</p>

<hr size="1" />

	<span class="header2">Corporate Lawyer</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/1366.jpg"
width="100" height="100" border="0" alt="Corporate Lawyer" />
	<span class="header3">Job Description</span>
	<blockquote>As a corporate lawyer, you would work for a
large company.  You would use your knowledge of the law to advise
executives.  You would tell them how to best protect the company and
stay within the laws that govern business.  You would also gather
and communicate information to other legal professionals or
clients.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To become a lawyer, you need a bachelor's degree
plus three years of law school.  Lawyers must pass a written test
known as the "bar exam" also.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of corporate lawyers was
$118,160 in May 2016. </blockquote>

<hr size="1" />

	<span class="header2">Management
Consultant</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/1370.jpg"
width="100" height="100" border="0" alt="Placement Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy helping people in practical ways,
you might become a placement specialist (employment recruiter). You
would find job opportunities in the community.  You would then
find people within the community to fill these jobs. You would
interview the person to be hired.  You might also test the person
using an instrument like the Interest Inventory that you
took.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree for this
job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of management consultants
was $81,330 in May 2016.
</blockquote>

<hr size="1" />

	<span class="header2">Retail Salesperson</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/1302.jpg"
width="100" height="100" border="0" alt="Retail Salesperson" />
	<span class="header3">Job Description</span>
	<blockquote>When you go into a department store, you may
have someone who comes to you and asks, "May I help you?"  This
person is a retail salesperson. A retail salesperson answers
questions that customers ask and helps the customer decide on what
to buy. He/she also "rings up" the sale on a cash register or
computer. Sometimes he/she is asked to restock shelves or
racks.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Companies provide on-the-job training for this
job. They may require special knowledge for people who want to work
in technical sales positions.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of retail salespersons
was $22,900 in May 2016. </blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit
the <em>Occupational Outlook Handbook</em>:</strong> <a
href="http://www.bls.gov/ooh">www.bls.gov/ooh</a></p>

<p><strong>You may also want to try the <em>Occupational Information
Network</em> Web site:</strong> <a
href="http://online.onetcenter.org/gen_search_page">online.onetcenter
.org/gen_search_page</a></p>



<blockquote>Salary data from Bureau of Labor Statistics, U.S.
Department of Labor, <i>Occupational Outlook Handbook, 2016-17
Edition, </i> visited 2/08/2018. </blockquote>
