	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Science/Mathematics (CH)</p>
			
			<div class="inter">
			
			<p>If your scores on this pairing were high, you naturally
			understand that there are always ways to improve a situation. You
			can probably handle several tasks at one time. People like you have
			made important contributions in business. You are an excellent
			thinker.  You are also likely to be a no-nonsense kind of person.
			You are creative and like to ask the question, "Why?"
			Because of this, you will look for new business ventures.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree or some post high school courses. For some jobs, it may be
			valuable to have a master's degree or a Ph.D.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that emphasize math and
			science. Any courses dealing with business will be of great interest
			to you. They will also help to prepare you for possible careers in
			this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Biology<br />
						Calculus<br />
						Physics<br />
						Sociology
					</td>
					<td>
						Computer Sciences<br />
						Advertising/Marketing<br />
						Accounting<br />
						Business Education
					</td>
					<td>
						Business Law<br />
						Chemistry<br />
						Psychology<br />
						Trigonometry
					</td>
					<td>
						Business Math<br />
						Communications<br />
						Economics<br />
						Political Science
					</td>
					<td>
						World Languages<br />
						Technology Education<br />
						Government/Civics<br />
						Environmental Sciences
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for after-school activities or part-time jobs, make
			them count. Any club or activity that involves using your people and
			thinking skills is what you will enjoy the most.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Future Business Leaders<br />
						Hospital Volunteer<br />
						Yearbook<br />
						Computer Club
					</td>
					<td>
						Computer Activities<br />
						Environmental Activities<br />
						Junior Achievement<br />
						Class Officer
					</td>
					<td>
						Chess Clubs<br />
						Math/Science Club<br />
						Tutoring
					</td>
					<td>
						Exchange Programs<br />
						Marketing<br />
						Community Volunteer
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting Firms<br />
						Electronics Stores<br />
						Photographic Laboratories<br />
						Restaurants
					</td>
					<td>
						Computer Services<br />
						Engineering Firms<br />
						Medical Offices<br />
						Printing Companies
					</td>
					<td>
						Data Entry<br />
						Landscaping Companies<br />
						Newspaper Offices<br />
					</td>
					<td>
						Architect Firms<br />
						Theaters<br />
						TV/Radio Stations
					</td>
				</tr>
			</table>
		</div>
			
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Finance</h5>
			<em>Chief Financial Officer</p>
			Financial Advisor</p>
			Accountant</p>
			Auditor
				<ul>
					<li>Bank</li>
					<li>Federal Reserve</li>
				</ul></p>
			Stockbroker</p>
			Statistician</p>
			Loan Officer</p>
			Accounting Clerk</p>
			Cashier</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical</h5>
			<em>Public Health Administrator</p>
			Physician</p>
			Hospital Administrator</p>
			Epidemiologist</p>
			Medical Officer</p>
			Nursing Home Director</p>
			Pharmacist</p>
			Optician</p>
			Patient Representative</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Analysis/Research</h5>
			<em>Economist</p>
			Marketing Director</p>
			Entrepreneur</p>
			Financial Analyst</p>
			Market Researcher</p>
			Insurance Planner & Analyst</p>
			Medical Economist</p>
			Computer Systems Analyst</em></p>
		</div>
		<div class="col">
			<h5>Nature</h5>
			<em>Zoo Administrator</p>
			Science Museum Director</p>
			Historic Preservationist</p>
			Fishery Manager/Technician</p>
			Wildlife Manager/Technician</p>
			Refuge Manager</p>
			Lobbyist</p>
			Grass Roots Coordinator</p>
			Fund Raiser</p>
			Real Estate Developer</p>
			Nursery Manager</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Finance</h5>
			<em>Chief Financial Officer</p>
			Financial Advisor</p>
			Accountant</p>
			Auditor
				<ul>
					<li>Bank</li>
					<li>Federal Reserve</li>
				</ul></p>
			Stockbroker</p>
			Statistician</p>
			Loan Officer</p>
			Accounting Clerk</p>
			Cashier</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical</h5>
			<em>Public Health Administrator</p>
			Physician</p>
			Hospital Administrator</p>
			Epidemiologist</p>
			Medical Officer</p>
			Nursing Home Director</p>
			Pharmacist</p>
			Optician</p>
			Patient Representative</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Analysis/Research</h5>
			<em>Economist</p>
			Marketing Director</p>
			Entrepreneur</p>
			Financial Analyst</p>
			Market Researcher</p>
			Insurance Planner & Analyst</p>
			Medical Economist</p>
			Computer Systems Analyst</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Nature</h5>
			<em>Zoo Administrator</p>
			Science Museum Director</p>
			Historic Preservationist</p>
			Fishery Manager/Technician</p>
			Wildlife Manager/Technician</p>
			Refuge Manager</p>
			Lobbyist</p>
			Grass Roots Coordinator</p>
			Fund Raiser</p>
			Real Estate Developer</p>
			Nursery Manager</em></p>
		</div>
	</div>
	</div>

