	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Science/Mathematics (CH)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Finance</h5>
			<em>Chief Financial Officer</p>
			Financial Advisor</p>
			Accountant</p>
			Auditor
				<ul>
					<li>Bank</li>
					<li>Federal Reserve</li>
				</ul></p>
			Stockbroker</p>
			Statistician</p>
			Loan Officer</p>
			Accounting Clerk</p>
			Cashier</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical</h5>
			<em>Public Health Administrator</p>
			Physician</p>
			Hospital Administrator</p>
			Epidemiologist</p>
			Medical Officer</p>
			Nursing Home Director</p>
			Pharmacist</p>
			Optician</p>
			Patient Representative</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Analysis/Research</h5>
			<em>Economist</p>
			Marketing Director</p>
			Entrepreneur</p>
			Financial Analyst</p>
			Market Researcher</p>
			Insurance Planner & Analyst</p>
			Medical Economist</p>
			Computer Systems Analyst</em></p>
		</div>
		<div class="col">
			<h5>Nature</h5>
			<em>Zoo Administrator</p>
			Science Museum Director</p>
			Historic Preservationist</p>
			Fishery Manager/Technician</p>
			Wildlife Manager/Technician</p>
			Refuge Manager</p>
			Lobbyist</p>
			Grass Roots Coordinator</p>
			Fund Raiser</p>
			Real Estate Developer</p>
			Nursery Manager</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Finance</h5>
			<em>Chief Financial Officer</p>
			Financial Advisor</p>
			Accountant</p>
			Auditor
				<ul>
					<li>Bank</li>
					<li>Federal Reserve</li>
				</ul></p>
			Stockbroker</p>
			Statistician</p>
			Loan Officer</p>
			Accounting Clerk</p>
			Cashier</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical</h5>
			<em>Public Health Administrator</p>
			Physician</p>
			Hospital Administrator</p>
			Epidemiologist</p>
			Medical Officer</p>
			Nursing Home Director</p>
			Pharmacist</p>
			Optician</p>
			Patient Representative</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Analysis/Research</h5>
			<em>Economist</p>
			Marketing Director</p>
			Entrepreneur</p>
			Financial Analyst</p>
			Market Researcher</p>
			Insurance Planner & Analyst</p>
			Medical Economist</p>
			Computer Systems Analyst</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Nature</h5>
			<em>Zoo Administrator</p>
			Science Museum Director</p>
			Historic Preservationist</p>
			Fishery Manager/Technician</p>
			Wildlife Manager/Technician</p>
			Refuge Manager</p>
			Lobbyist</p>
			Grass Roots Coordinator</p>
			Fund Raiser</p>
			Real Estate Developer</p>
			Nursery Manager</em></p>
		</div>
	</div>
	</div>

