	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Social Helping (CI)</p>
			
			<div class="inter">
			
			<p>Your high scores in "C" and "I" show that you have several
			characteristics that can help you to be useful to people. You are a
			creative, outgoing, and talented person. You like to offer support
			to people who are having difficulties. You also know that working
			hard is important. No matter what you choose to do, you will want to
			know you are helping people.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree.  It is helpful to have a master's degree or a Ph.D. in some
			of the occupations.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to Math & English):</strong><br />
			In high school you should take courses that help you understand
			people. Any courses in social studies or social sciences will be of
			great interest to you and will also help prepare you for possible
			career opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting<br />
						Business Law<br />
						Religion
					</td>
					<td>
						History<br />
						Psychology<br />
						Sociology
					</td>
					<td>
						Business Math<br />
						Computer Technology<br />
						Life Sciences
					</td>
					<td>
						Business Education<br />
						Government/Civics<br />
						Public Relations
					</td>
					<td>
						Health/Nutrition<br />
						Home Economics<br />
						Communications
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for after school activities or part-time jobs, make
			them count. You will enjoy any club or activity where you can use
			your people skills and help others.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Community Volunteer<br />
						Exchange Programs<br />
						Teaching Assistant<br />
						Tutoring
					</td>
					<td>
						Childcare/Eldercare<br />
						Peer Counselor<br />
						Future Business Leaders<br />
						Newspaper/Yearbook
					</td>
					<td>
						Church Activities<br />
						Hospital Volunteer<br />
						Computer Activities
				<span class="header2">Mental Health and
					</td>
					<td>
						Junior Achievement<br />
						Class Officer<br />
						Camp Counselor
					</td>
				</tr>
			</table>

			<p>	<strong>Workplaces that you may wish to consider for a part-
			time job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising Agencies<br />
						Company Offices<br />
						Graphic Design Firms<br />
						Recreation Departments
					</td>
					<td>
						Camp Programs<br />
						Day Care Centers<br />
						Life Guarding<br />
						Restaurants
					</td>
					<td>
						Church Programs<br />
						Libraries<br />
						Newspaper Offices<br />
						Special Olympics
					</td>
					<td>
						Printing Companies<br />
						Preschool Programs<br />
						Photographic Studios
					</td>
				</tr>
			</table>
		</div>
			
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Religious Activities Director</p>
			<p>Health Services Administrator</p>
			<p>Clergy</p>
			<p>Occupational Social Worker</p>
			<p>Public Health Social Worker</p>
			<p>Adult Education Teacher (Business Courses)</p>
			<p>Human Services Worker</p>
			<p>Homeless Shelter Director</p>
			<p>Parole Officer</p>
			<p>Home Health Aide</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<p><h5>Business Helping</h5>
			<p><em>Personnel Consultant</p>
			<p>Corporate Trainer</p>
			<p>Employment Interviewer</p>
			<p>Property Manager</p>
			<p>Real Estate Agent</p>
			<p>Insurance Agent</p>
			<p>Sales Occupation</p>
			<p>Service Occupation</p>
			<p>Bank Teller</p>
			<p>Receptionist</p>
			<p>Computer Salesperson</p>
			<p>Retail Salesperson</em></p>
		</div>
		<div class="col">
			<p><h5>Business Management</h5>
			<p><em>Hospital Administrator</p>
			<p>Financial Planner</p>
			<p>Geriatric Care Manager</p>
			<p>Human Resources Manager</p>
			<p>Funeral Director</p>
			<p>Hotel Manager</p>
			<p>Benefits Administrator</p>
			<p>Retirement Manager</p>
			<p>Restaurant Manager</p>
			<p>Travel Agency Manager</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Religious Activities Director</p>
			<p>Health Services Administrator</p>
			<p>Clergy</p>
			<p>Occupational Social Worker</p>
			<p>Public Health Social Worker</p>
			<p>Adult Education Teacher (Business Courses)</p>
			<p>Human Services Worker</p>
			<p>Homeless Shelter Director</p>
			<p>Parole Officer</p>
			<p>Home Health Aide</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<p><h5>Business Helping</h5>
			<p><em>Personnel Consultant</p>
			<p>Corporate Trainer</p>
			<p>Employment Interviewer</p>
			<p>Property Manager</p>
			<p>Real Estate Agent</p>
			<p>Insurance Agent</p>
			<p>Sales Occupation</p>
			<p>Service Occupation</p>
			<p>Bank Teller</p>
			<p>Receptionist</p>
			<p>Computer Salesperson</p>
			<p>Retail Salesperson</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<p><h5>Business Management</h5>
			<p><em>Hospital Administrator</p>
			<p>Financial Planner</p>
			<p>Geriatric Care Manager</p>
			<p>Human Resources Manager</p>
			<p>Funeral Director</p>
			<p>Hotel Manager</p>
			<p>Benefits Administrator</p>
			<p>Retirement Manager</p>
			<p>Restaurant Manager</p>
			<p>Travel Agency Manager</em></p>
		</div>
	</div>
	</div>

