<span class="header1">Business/Management paired with Social Helping 
(CI)</span>

<p>Your high scores in "C" and "I" show that you have several 
characteristics that can help you to be useful to people. You are a 
creative, outgoing, and talented person. You like to offer support 
to people who are having difficulties. You also know that working 
hard is important. No matter what you choose to do, you will want to 
know you are helping people.</p>
<p>Most occupations in this pairing require at least a bachelor's 
degree.  It is helpful to have a master's degree or a Ph.D. in some 
of the occupations.</p>
<p><strong>Courses you may want to consider taking in high school 
and beyond (in addition to Math & English):</strong><br />
In high school you should take courses that help you understand 
people. Any courses in social studies or social sciences will be of 
great interest to you and will also help prepare you for possible 
career opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting<br />
			Business Law<br />
			Religion
		</td>
		<td>
			History<br />
			Psychology<br />
			Sociology
		</td>
		<td>
			Business Math<br />
			Computer Technology<br />
			Life Sciences
		</td>
		<td>
			Business Education<br />
			Government/Civics<br />
			Public Relations
		</td>
		<td>
			Health/Nutrition<br />
			Home Economics<br />
			Communications
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations 
you may find interesting:</strong><br /> 
If you have time for after school activities or part-time jobs, make 
them count. You will enjoy any club or activity where you can use 
your people skills and help others.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Community Volunteer<br />
			Exchange Programs<br />
			Teaching Assistant<br />
			Tutoring
		</td>
		<td>
			Childcare/Eldercare<br />
			Peer Counselor<br />
			Future Business Leaders<br />
			Newspaper/Yearbook
		</td>
		<td>
			Church Activities<br />
			Hospital Volunteer<br />
			Computer Activities
		</td>
		<td>
			Junior Achievement<br />
			Class Officer<br />
			Camp Counselor
		</td>
	</tr>
</table>

<p>	<strong>Workplaces that you may wish to consider for a part-
time job:</strong><br />
These places may offer valuable opportunities to help you decide 
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising Agencies<br />
			Company Offices<br />
			Graphic Design Firms<br /> 
			Recreation Departments
		</td>
		<td>
			Camp Programs<br />
			Day Care Centers<br />
			Life Guarding<br />
			Restaurants
		</td>
		<td>
			Church Programs<br />
			Libraries<br />
			Newspaper Offices<br />
			Special Olympics
		</td>
		<td>
			Printing Companies<br />
			Preschool Programs<br />
			Photographic Studios
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to 
explore.</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">CI Career 
Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" 
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" 
align="left"><strong>More People Oriented</strong></td>
					<td width="33%" 
align="center"><strong><----------></strong></td>
					<td width="33%" 
align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" 
cellspacing="0" height="400">
				<tr align="center" 
height="33%"><td><strong>More<br /></strong></td></tr>
				<tr align="center" 
height="33%"><td><strong>Education<br />or<br />Training<br />Require
d</strong></td></tr>
				<tr align="center" 
height="33%"><td><strong><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" 
cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span 
class="header2">Social Helping</span><br /><br />
						<em>Religious 
Activities Director<br /><br />
						Health Services 
Administrator<br /><br />
						Clergy<br /><br />
						Occupational Social 
Worker<br /><br />
						Public Health Social 
Worker<br /><br />
						Adult Education 
Teacher (Business Courses)<br /><br />
						Human Services 
Worker<br /><br />
						Homeless Shelter 
Director<br /><br />
						Parole 
Officer<br /><br />
						Home Health Aide</em>
					</td>
					<td width="33%">
						<span 
class="header2">Business Helping</span><br /><br />
						<em>Personnel 
Consultant<br /><br />
						Corporate 
Trainer<br /><br />
						Employment 
Interviewer<br /><br />
						Property 
Manager<br /><br />
						Real Estate 
Agent<br /><br />
						Insurance 
Agent<br /><br />
						Sales 
Occupation<br /><br />
						Service 
Occupation<br /><br />
						Bank 
Teller<br /><br />
					
	Receptionist<br /><br />
						Computer 
Salesperson<br /><br />
						Retail 
Salesperson</em>
					</td>
					<td width="33%">
						<span 
class="header2">Business Management</span><br /><br />
						<em>Hospital 
Administrator<br /><br />
						Financial 
Planner<br /><br />
						Geriatric Care 
Manager<br /><br />
						Human Resources 
Manager<br /><br />
						Funeral 
Director<br /><br />
						Hotel 
Manager<br /><br />
						Benefits 
Administrator<br /><br />
						Retirement 
Manager<br /><br />
						Restaurant 
Manager<br /><br />
						Travel Agency 
Manager</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">SOCIAL HELPING</span>
<p>Occupations in this field allow you to help others. They also 
allow you to use your business and management skills.  Most of the 
occupations are associated with social work.</p>

<hr size="1" />

	<span class="header2">Social Worker</span><br /><br />
	<img class="job_pic" src="/images/icons/CI/1212.jpg" 
width="100" height="100" border="0" alt="Public Health Social 
Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Social work is a profession for those with a 
strong desire to help improve people's lives. Social workers assist 
people by helping them cope with issues in their everyday lives, 
deal with their relationships, and solve personal and family 
problems. </blockquote>
	<span class="header3">Education</span>
	<blockquote>While a bachelor's degree is the minimum 
requirement, a master's degree in social work or a related field has 
become the standard for many positions.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of social workers was 
$42,480 in May 2010. </blockquote>

<hr size="1" />

	<span class="header2">Mental Health and 
Substance Abuse Social Worker </span><br /><br />
	<img class="job_pic" src="/images/icons/CI/7240.jpg" 
width="100" height="100" border="0" alt="Occupational Social 
Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Mental health and substance abuse social workers 
assess and treat individuals with mental illness or substance abuse 
problems, including abuse of alcohol, tobacco, or other drugs. Such 
services include individual and group therapy, outreach, crisis 
intervention, social rehabilitation, and teaching skills needed for 
everyday living. </blockquote>
	<span class="header3">Education</span>
	<blockquote>A master's degree in social work (MSW) is 
typically required for positions in health settings and is required 
for clinical work as well.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of mental health and 
substance abuse social workers was $42,480 in May 2010. </blockquote>

<hr size="1" />

	<span class="header2">Social and Human Service 
Assistants</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Social and human service assistants provide 
services to clients to help them improve their quality of life. They 
assess clients' needs, investigate their eligibility for benefits 
and services such as food stamps, Medicaid, or welfare, and help to 
obtain them. They also arrange for transportation and escorts, if 
necessary, and provide emotional support. Social and human service 
assistants monitor and keep case records on clients and report 
progress to supervisors and case managers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is not required for most 
jobs in this occupation, but employers increasingly seek individuals 
with relevant work experience or education beyond high 
school.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of social and human 
service assistants was $28,200 in May 2010. </blockquote>

<hr size="1" />

<span class="header1">BUSINESS HELPING</span>
<p>In this field you would need to have an outgoing personality.  
You would also need to enjoy meeting new people. The occupations in 
this field allow you to provide a service to customers.</p>

<hr size="1" />

	<span class="header2">Property, Real Estate, or Community 
Association Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CI/1319.jpg" 
width="100" height="100" border="0" alt="Property Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Property is land that has value. The property 
may have a building or buildings on it. If you were a property 
manager, you would be responsible for the day-to-day running of a 
property. You might run an office, an apartment complex, or a retail 
building. Your duties might include making rental agreements, 
collecting rent, and hiring employees to maintain the 
grounds.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers increasingly are hiring college 
graduates with a bachelor's or master's degree in business 
administration, accounting, finance, or real estate, even if they 
don't have much practical experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of property real estate 
or community association managers was $51,480 in May 2010. 
</blockquote>

<hr size="1" />


	<span class="header2">Real Estate Agent</span><br /><br />
	<img class="job_pic" src="/images/icons/CI/C526017.jpg" 
width="100" height="100" border="0" alt="Real Estate Agent" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy working with people and want to 
help them buy a house or land, you might become a real estate agent. 
As a real estate agent, you would work with people who want to sell 
their homes, and you would show these homes to others. You would 
help people who want to buy a home to get a loan. You would need to 
be independent and a good problem solver.  You also need to be able 
to communicate well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma to be a 
real estate agent. More and more employers want you to have a 
bachelor's degree.  Real estate agents must be licensed in the state 
in which they work.  To get this license, you must take courses in 
real estate law and pass an exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of real estate agents was 
$42,680 in May 2010. </blockquote>

<hr size="1" />

	<span class="header2">Bank Teller</span><br /><br />
	<img class="job_pic" src="/images/icons/CI/1371.jpg" 
width="100" height="100" border="0" alt="Bank Teller" />
	<span class="header3">Job Description</span>
	<blockquote>A bank teller handles large sums of money. As a 
bank teller, you would help customers with their deposits and 
withdrawals. Banks look for people who work well with customers, 
have good math skills, and know the importance of keeping detailed 
records.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A high school diploma is needed to be a bank 
teller. A teller is given on-the-job training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of bank tellers was 
$24,100 in May 2010. </blockquote>

<hr size="1" />

<span class="header1">BUSINESS MANAGEMENT</span>
<p>The occupations in this field require you to oversee others as 
they are doing their jobs. You need to be good with people and know 
how to handle business.</p>

<hr size="1" />

	<span class="header2">Funeral Director</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A funeral director helps a family make funeral 
plans when a family member has died. If you were a funeral 
director, you would handle the details of the funeral service and 
burial. You would put a notice in the newspaper. You would also 
order flowers and contact people to speak at the 
funeral.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Funeral directors are licensed in all states. 
State licensing laws vary, but most require applicants to be 21 
years old, have two years of formal education, serve a one-year 
apprenticeship, and pass an examination. College programs in 
mortuary science usually last from two to four years. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of funeral directors was 
$54,330 in May 2010. </blockquote>

<hr size="1" />

	<span class="header2">Hotel or 
Lodging Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/43096.jpg" 
width="100" height="100" border="0" alt="Hotel Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Hotels are an important part of the community. 
The person who runs a hotel is called a hotel manager. As a hotel 
manager, you would be responsible for making sure the guests are 
comfortable during their stay. One of the most important duties you 
would have is to make sure that the employees are doing their jobs 
properly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most large, full-service hotel chains usually 
hire people who have a bachelor's degree in business, hotel, or 
hospitality management for management trainee positions; however, a 
liberal arts degree coupled with experience in the hospitality field 
may be sufficient. At other hotels, especially those with fewer 
services, employers look for applicants with an associate degree or 
certificate in hotel, restaurant, or hospitality management along 
with experience. Formal internships or part-time or summer work in a 
hotel are an asset. Most degree programs include work-study 
opportunities. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of lodging managers was 
$46,880 in May 2010.</blockquote>

<hr size="1" />

	<span class="header2">Food Service Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/43129.jpg" 
width="100" height="100" border="0" alt="Assistant Restaurant 
Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Food service managers are responsible for the 
daily operations of restaurants to prepare and serve meals and 
beverages and ensure that customers are satisfied with their dining 
experience. In addition, they oversee the inventory and ordering of 
food, equipment, and supplies and arrange for the routine 
maintenance and upkeep of the restaurant's equipment and facilities. 
Managers generally are responsible for all of the administrative and 
human-resource functions of running the business, including 
recruiting new employees and monitoring employee performance and 
training. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Both 2- and 4-year degree programs provide 
instruction in nutrition, sanitation, and food planning and 
preparation, as well as accounting, business law and management, and 
computer science. Some programs combine classroom on-the-job 
experience. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of food service managers 
was $48,130 in May 2010. </blockquote>
<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit 
the <em>Occupational Outlook Handbook</em>:</strong> <a 
href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information 
Network</em> Web site:</strong> <a 
href="http://online.onetcenter.org/gen_search_page">online.onetcenter
.org/gen_search_page</a></p>




<blockquote>Salary data from Bureau of Labor Statistics, U.S. 
Department of Labor, <i>Occupational Outlook Handbook, 2012-13 
Edition, </i> visited 8/27/2012. </blockquote>


