	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Clerical/Administrative (CD)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CD Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business Sales</h5>
			<p><em>Computer Sales Representative</p>
			<p>Business Machine Sales Representative</p>
			<p>Insurance Sales Agent</p>
			<p>Real Estate Agent/Broker</p>
			<p>Personnel Consultant</p>
			<p>Analyst
				<ul>
					<li>Marketing</li>
					<li>Stock</li>
				</ul></p>
			<p>Sales Account Supervisor</p>
			<p>Travel Agent</p>
			<p>Sales Support</p>
			<p>Cashier</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business Administrative</h5>
			<p><em>Personnel Director</p>
			<p>Human Resources Manager</p>
			<p>Data Processing Manager</p>
			<p>Facilities Manager</p>
			<p>Office Manager</p>
			<p>Retail Buyer</p>
			<p>Employee Benefits Manager</p>
			<p>Executive Secretary</p>
			<p>Underwriter</p>
			<p>Stock Transfer Clerk</p>
			<p>Personnel Clerk</em></p>
		</div>
		<div class="col">
			<h5>Business Financial</h5>
			<p><em>Chief Financial Officer</p>
			<p>Statistician</p>
			<p>Economic Researcher</p>
			<p>Financial Planner</p>
			<p>Bank Loan Officer</p>
			<p>Auditor</p>
			<p>Bookkeeper</p>
			<p>Tax Preparer</p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Statistical</li>
				</ul></p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business Sales</h5>
			<p><em>Computer Sales Representative</p>
			<p>Business Machine Sales Representative</p>
			<p>Insurance Sales Agent</p>
			<p>Real Estate Agent/Broker</p>
			<p>Personnel Consultant</p>
			<p>Analyst
				<ul>
					<li>Marketing</li>
					<li>Stock</li>
				</ul></p>
			<p>Sales Account Supervisor</p>
			<p>Travel Agent</p>
			<p>Sales Support</p>
			<p>Cashier</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Business Administrative</h5>
			<p><em>Personnel Director</p>
			<p>Human Resources Manager</p>
			<p>Data Processing Manager</p>
			<p>Facilities Manager</p>
			<p>Office Manager</p>
			<p>Retail Buyer</p>
			<p>Employee Benefits Manager</p>
			<p>Executive Secretary</p>
			<p>Underwriter</p>
			<p>Stock Transfer Clerk</p>
			<p>Personnel Clerk</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Business Financial</h5>
			<p><em>Chief Financial Officer</p>
			<p>Statistician</p>
			<p>Economic Researcher</p>
			<p>Financial Planner</p>
			<p>Bank Loan Officer</p>
			<p>Auditor</p>
			<p>Bookkeeper</p>
			<p>Tax Preparer</p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Statistical</li>
				</ul></p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>

	