	<div class="row">
		<div class="col-md-12">
			<p class="lead">Clerical/Administrative paired with Protective/Military Service (DE)</p>
			
			<div class="inter">
			
			<p>If you show high scores in categories "D" and "E," you are a
			person who knows how to make things happen. You are respectful to
			others. You also probably enjoy working on a team. You are able to
			complete tasks quickly. An exciting environment is important to you.
			You especially like to try new things.</p>
			<p>Some of the occupations in this pairing require a bachelor's
			degree and many others require specialized training.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to Math & English):</strong><br />
			In high school you should take courses that allow you to continue
			to learn about business. You will want to take courses that help you
			understand people as well.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting<br />
						Business Law<br />
						Computer Sciences<br />
						Public Relations
					</td>
					<td>
						History<br />
						Physics<br />
						Geography<br />
						Economics
					</td>
					<td>
						Business Math<br />
						Sociology<br />
						Government/Civics<br />
						Life Sciences
					</td>
					<td>
						Political Science<br />
						Business Education<br />
						Technology Education<br />
						Environmental Sciences
					</td>
					<td>
						Bookkeeping<br />
						World Languages<br />
						Physical Education<br />
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations you
			may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. You will enjoy any club or activity that involves taking
			on challenges.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Athletics<br />
						Camp Activities<br />
						Martial Arts
					</td>
					<td>
						Audio/Visual Services<br />
						Newspaper/Yearbook<br />
						Future Business Leaders<br />
					</td>
					<td>
						Band<br />
						Scouts<br />
						ROTC
					</td>
					<td>
						Teaching Assistant<br />
						Community Volunteer<br />
						Flight Training
					</td>
					<td>
						Library Assistant<br />
						Class Officer
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Construction Sites<br />
						Radio/TV Stations<br />
						Printing Companies
					</td>
					<td>
						Temporary Agencies<br />
						Equipment Operation<br />
						Equipment Repair Shops
					</td>
					<td>
						Libraries<br />
						Gyms<br />
						Life Guarding
					</td>
					<td>
						Camp Counseling<br />
						Photography Studios<br />
						Parks/Recreation
					</td>
					<td>
						Newspapers<br />
						Data Processing
					</td>
				</tr>
			</table>
		</div>
			
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>DE Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Staff Support Services</h5>
			<p><em>Assistant Sports Coach</p>
			<p>Paralegal</p>
			<p>Airline Ticket Agent</p>
			<p>Executive Assistant</p>
			<p>Drafting Technician</p>
			<p>Court Reporter</p>
			<p>Data Reporter</p>
			<p>Receptionist</p>
			<p>City Maintenance Worker</p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Mail</li>
					<li>Shipping & Receiving</li>
				</ul></em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
		  	<h5>Office Administration</h5>
			<p><em>Operations Manager</p>
			<p>Computer Systems Analyst</p>
			<p>Human Resources Representative</p>
			<p>Office Manager</p>
			<p>Purchasing Agent</p>
			<p>Clerical Supervisor</p>
			<p>Software Technician</p>
			<p>Office Machine
			<p>Repair Technician</p>
			<p>Accountant
				<ul>
					<li>Payroll</li>
					<li>Accounts Payable</li>
					<li>Accounts Receivable</li>
				</ul></em></p>
		</div>
		<div class="col">
			<h5>Military</h5>
			<p><em>Religious Program Specialist</p>
			<p>Recruiting Specialist</p>
			<p>Administrative Support Services</p>
			<p>Lodging Specialist</p>
			<p>Legal Technician</p>
			<p>Transportation Specialist</p>
			<p>Computer Operator</p>
			<p>Optometric Technician</p>
			<p>Stenographer</p>
			<p>Stock & Inventory Specialist</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Staff Support Services</h5>
			<p><em>Assistant Sports Coach</p>
			<p>Paralegal</p>
			<p>Airline Ticket Agent</p>
			<p>Executive Assistant</p>
			<p>Drafting Technician</p>
			<p>Court Reporter</p>
			<p>Data Reporter</p>
			<p>Receptionist</p>
			<p>City Maintenance Worker</p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Mail</li>
					<li>Shipping & Receiving</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
		  	<h5>Office Administration</h5>
			<p><em>Operations Manager</p>
			<p>Computer Systems Analyst</p>
			<p>Human Resources Representative</p>
			<p>Office Manager</p>
			<p>Purchasing Agent</p>
			<p>Clerical Supervisor</p>
			<p>Software Technician</p>
			<p>Office Machine
			<p>Repair Technician</p>
			<p>Accountant
				<ul>
					<li>Payroll</li>
					<li>Accounts Payable</li>
					<li>Accounts Receivable</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Military</h5>
			<p><em>Religious Program Specialist</p>
			<p>Recruiting Specialist</p>
			<p>Administrative Support Services</p>
			<p>Lodging Specialist</p>
			<p>Legal Technician</p>
			<p>Transportation Specialist</p>
			<p>Computer Operator</p>
			<p>Optometric Technician</p>
			<p>Stenographer</p>
			<p>Stock & Inventory Specialist</em></p>
		</div>
	</div>
	</div>

