	<div class="row">
		<div class="col-md-12">
			<p class="lead">Clerical/Administrative paired with Protective/Military Service (DE)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>DE Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Staff Support Services</h5>
			<p><em>Assistant Sports Coach</p>
			<p>Paralegal</p>
			<p>Airline Ticket Agent</p>
			<p>Executive Assistant</p>
			<p>Drafting Technician</p>
			<p>Court Reporter</p>
			<p>Data Reporter</p>
			<p>Receptionist</p>
			<p>City Maintenance Worker</p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Mail</li>
					<li>Shipping & Receiving</li>
				</ul></em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
		  	<h5>Office Administration</h5>
			<p><em>Operations Manager</p>
			<p>Computer Systems Analyst</p>
			<p>Human Resources Representative</p>
			<p>Office Manager</p>
			<p>Purchasing Agent</p>
			<p>Clerical Supervisor</p>
			<p>Software Technician</p>
			<p>Office Machine
			<p>Repair Technician</p>
			<p>Accountant
				<ul>
					<li>Payroll</li>
					<li>Accounts Payable</li>
					<li>Accounts Receivable</li>
				</ul></em></p>
		</div>
		<div class="col">
			<h5>Military</h5>
			<p><em>Religious Program Specialist</p>
			<p>Recruiting Specialist</p>
			<p>Administrative Support Services</p>
			<p>Lodging Specialist</p>
			<p>Legal Technician</p>
			<p>Transportation Specialist</p>
			<p>Computer Operator</p>
			<p>Optometric Technician</p>
			<p>Stenographer</p>
			<p>Stock & Inventory Specialist</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Staff Support Services</h5>
			<p><em>Assistant Sports Coach</p>
			<p>Paralegal</p>
			<p>Airline Ticket Agent</p>
			<p>Executive Assistant</p>
			<p>Drafting Technician</p>
			<p>Court Reporter</p>
			<p>Data Reporter</p>
			<p>Receptionist</p>
			<p>City Maintenance Worker</p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Mail</li>
					<li>Shipping & Receiving</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
		  	<h5>Office Administration</h5>
			<p><em>Operations Manager</p>
			<p>Computer Systems Analyst</p>
			<p>Human Resources Representative</p>
			<p>Office Manager</p>
			<p>Purchasing Agent</p>
			<p>Clerical Supervisor</p>
			<p>Software Technician</p>
			<p>Office Machine
			<p>Repair Technician</p>
			<p>Accountant
				<ul>
					<li>Payroll</li>
					<li>Accounts Payable</li>
					<li>Accounts Receivable</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Military</h5>
			<p><em>Religious Program Specialist</p>
			<p>Recruiting Specialist</p>
			<p>Administrative Support Services</p>
			<p>Lodging Specialist</p>
			<p>Legal Technician</p>
			<p>Transportation Specialist</p>
			<p>Computer Operator</p>
			<p>Optometric Technician</p>
			<p>Stenographer</p>
			<p>Stock & Inventory Specialist</em></p>
		</div>
	</div>
	</div>

