	<div class="row">
		<div class="col-md-12">
			<p class="lead">Clerical/Administrative paired with Technology (DF)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>DF Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technical Administration</h5>
			<em>Publisher</p>
			Graphic Artist</p>
			Technical Proofreader</p>
			Graphics Specialist</p>
			Medical Record Administrator</p>
			Computer Programmer</p>
			Airline Ticket Agent</p>
			Dispensing Optician</p>
			Stenographer</p>
			Work Processor</p>
			Switchboard Operator</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Clerical Services</h5>
			<em>Court Reporter</p>
			Recreation Administrator</p>
			Library Technical Assistant</p>
			Insurance Claims Examiner</p>
			Directory Assistance Operator</p>
			Mail Carrier</p>
			Construction Secretary</p>
			Clerk
				<ul>
					<li>General Office</li>
					<li>Personnel</li>
					<li>Mail</li>
					<li>Shipping</li>
				</ul></em></p>
		</div>
		<div class="col">
			<h5>Technical Operation</h5>
			<em>Surveyor</p>
			Parks & Recreation</p>
			Public Relations Assistant</p>
			Database Administrator</p>
			Computer Programmer</p>
			Flight Operations Specialist</p>
			Computer Service Technician</p>
			Shoe Repairer</p>
			Corrections Officer</p>
			Security Guard</p>
			Parts Clerk
				<ul>
					<li>Auto
					<li>Hardware</li>
				</ul></em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technical Administration</h5>
			<em>Publisher</p>
			Graphic Artist</p>
			Technical Proofreader</p>
			Graphics Specialist</p>
			Medical Record Administrator</p>
			Computer Programmer</p>
			Airline Ticket Agent</p>
			Dispensing Optician</p>
			Stenographer</p>
			Work Processor</p>
			Switchboard Operator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Clerical Services</h5>
			<em>Court Reporter</p>
			Recreation Administrator</p>
			Library Technical Assistant</p>
			Insurance Claims Examiner</p>
			Directory Assistance Operator</p>
			Mail Carrier</p>
			Construction Secretary</p>
			Clerk
				<ul>
					<li>General Office</li>
					<li>Personnel</li>
					<li>Mail</li>
					<li>Shipping</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Technical Operation</h5>
			<em>Surveyor</p>
			Parks & Recreation</p>
			Public Relations Assistant</p>
			Database Administrator</p>
			Computer Programmer</p>
			Flight Operations Specialist</p>
			Computer Service Technician</p>
			Shoe Repairer</p>
			Corrections Officer</p>
			Security Guard</p>
			Parts Clerk
				<ul>
					<li>Auto
					<li>Hardware</li>
				</ul></em></p>
		</div>
	</div>
	</div>

