	<div class="row">
		<div class="col-md-12">
			<p class="lead">Clerical/Administrative paired with Technology (DF)</p>
			
			<div class="inter">
			
			<p>With a "DF" interest, you will be a valuable employee. Those who
			have strong scores in "D" and "F" have very high goals and want
			things to be done right. You like to use tools and information to
			reach your goals. You are an active person and will want a job that
			keeps you on the go.</p>
			<p>Many of the occupations in this pairing require some specialized
			or technical training after high school. Some require college level
			courses and others require college degrees.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school, you should take courses that allow you to continue
			to learn how to be efficient. Technology courses will be important,
			too.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting<br />
						Business Law<br />
						Graphic Art<br />
					</td>
					<td>
						Office Administration<br />
						Computer Programming<br />
						Environmental Science<br />
					</td>
					<td>
						Bookkeeping<br />
						Business Math<br />
						Psychology<br />
					</td>
					<td>
						Physical Education<br />
						Government/Civics<br />
						Business Education<br />
					</td>
					<td>
						Technology Education<br />
						Geography<br />
						Communications
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / Volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. Any club or activity that involves technology and
			procedures will be valuable.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Math/Science Clubs<br />
						Chess Club<br />
						Office Assistant
					</td>
					<td>
						Park & Recreation Activities<br />
						Audio/Visual Services<br />
						Future Business Leaders
					</td>
					<td>
						Library Assistant<br />
						Photography Clubs<br />
						Community Volunteer
					</td>
					<td>
						Computer Club<br />
						Newspaper/Yearbook<br />
						Teaching Assistant
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Farming<br />
						Delivery Services<br />
						Lumberyard<br />
						Construction
					</td>
					<td>
						Environmental Services<br />
						Landscaping/Lawn Care<br />
						Photography Studios<br />
						Park Services
					</td>
					<td>
						Newspaper Offices<br />
						Camp Counseling<br />
						Data Processing
					</td>
					<td>
						Equipment Operations<br />
						Graphic Design Firms<br />
						Equipment Repair Shops
					</td>
				</tr>
			</table>
		</div>
			
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>DF Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technical Administration</h5>
			<em>Publisher</p>
			Graphic Artist</p>
			Technical Proofreader</p>
			Graphics Specialist</p>
			Medical Record Administrator</p>
			Computer Programmer</p>
			Airline Ticket Agent</p>
			Dispensing Optician</p>
			Stenographer</p>
			Work Processor</p>
			Switchboard Operator</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Clerical Services</h5>
			<em>Court Reporter</p>
			Recreation Administrator</p>
			Library Technical Assistant</p>
			Insurance Claims Examiner</p>
			Directory Assistance Operator</p>
			Mail Carrier</p>
			Construction Secretary</p>
			Clerk
				<ul>
					<li>General Office</li>
					<li>Personnel</li>
					<li>Mail</li>
					<li>Shipping</li>
				</ul></em></p>
		</div>
		<div class="col">
			<h5>Technical Operation</h5>
			<em>Surveyor</p>
			Parks & Recreation</p>
			Public Relations Assistant</p>
			Database Administrator</p>
			Computer Programmer</p>
			Flight Operations Specialist</p>
			Computer Service Technician</p>
			Shoe Repairer</p>
			Corrections Officer</p>
			Security Guard</p>
			Parts Clerk
				<ul>
					<li>Auto
					<li>Hardware</li>
				</ul></em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technical Administration</h5>
			<em>Publisher</p>
			Graphic Artist</p>
			Technical Proofreader</p>
			Graphics Specialist</p>
			Medical Record Administrator</p>
			Computer Programmer</p>
			Airline Ticket Agent</p>
			Dispensing Optician</p>
			Stenographer</p>
			Work Processor</p>
			Switchboard Operator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Clerical Services</h5>
			<em>Court Reporter</p>
			Recreation Administrator</p>
			Library Technical Assistant</p>
			Insurance Claims Examiner</p>
			Directory Assistance Operator</p>
			Mail Carrier</p>
			Construction Secretary</p>
			Clerk
				<ul>
					<li>General Office</li>
					<li>Personnel</li>
					<li>Mail</li>
					<li>Shipping</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Technical Operation</h5>
			<em>Surveyor</p>
			Parks & Recreation</p>
			Public Relations Assistant</p>
			Database Administrator</p>
			Computer Programmer</p>
			Flight Operations Specialist</p>
			Computer Service Technician</p>
			Shoe Repairer</p>
			Corrections Officer</p>
			Security Guard</p>
			Parts Clerk
				<ul>
					<li>Auto
					<li>Hardware</li>
				</ul></em></p>
		</div>
	</div>
	</div>

