	<div class="row">
		<div class="col-md-12">
			<p class="lead">Clerical/Administrative paired with Public Service (DG)</p>
			
			<div class="inter">
			
			<p>If you scored high in the "D" and "G" categories, you are
			reliable and honest.  You are also supportive and resourceful. You
			are the kind of person that employers prefer.  If you want to, you
			can use your organizational skills and interest in helping others to
			make a difference in the world.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree. For some jobs, it may be valuable to have a master's degree
			or a Ph.D.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that help you to understand
			business practices.  You should also take courses that help you to
			understand people. Social studies courses such as political science
			and sociology may interest you.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Business Math<br />
						Health/Nutrition<br />
						Physical Education<br />
						Political Science
					</td>
					<td>
						Computer Technology<br />
						Public Relations<br />
						Advertising/Marketing<br />
						Business Education
					</td>
					<td>
						Computer Sciences<br />
						Government/Civics<br />
						Bookkeeping<br />
						World Languages
					</td>
					<td>
						History<br />
						Sociology<br />
						Accounting<br />
						Economics
					</td>
					<td>
						Business Law<br />
						Photography<br />
						Psychology
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. Any club or activity that involves helping others or
			working for a cause can provide valuable experience.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Community Volunteer<br />
						Audio/Visual Services<br />
						Library Assistant<br />
						Class Officer
					</td>
					<td>
						Teaching Assistant<br />
						Exchange Programs<br />
						Junior Achievement<br />
						Newspaper/Yearbook
					</td>
					<td>
						Future Business Leaders<br />
						Safety Patrol<br />
						Youth Organizations<br />
						Office Assistant
					</td>
					<td>
						Church Activities<br />
						Hospital Volunteer<br />
						Peer Counselor<br />
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Recreation Departments<br />
						Special Olympics<br />
						Accounting Firms<br />
						Temporary Agencies
					</td>
					<td>
						Business Offices<br />
						Legal Offices<br />
						Restaurants<br />
						Television Sales
					</td>
					<td>
						Accounting Firms<br />
						Libraries<br />
						Business Offices<br />
						Legal Offices
					</td>
					<td>
						Camp Counseling<br />
						Courthouses<br />
						Newspaper Offices<br />
						Radio/TV Studios
					</td>
					<td>
						Church Activities<br />
						Life Guarding<br />
						Political Offices<br />
						Youth Coaching
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>DG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Services</h5>
			<p><em>Social Worker
				<ul>
					<li>Occupational</li>
					<li>School</li>
					<li>Human Services</li>
				</ul></p>
			<p>Vocational Rehabilitation Counselor</p>
			<p>Postal Inspector</p>
			<p>Teacher Aide</p>
			<p>Real Estate Broker</p>
			<p>Flight Attendant</p>
			<p>Church Attendant</p>
			<p>Postal Worker</p>
			<p>Hospital Outpatient
			<p>Coordinator</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Administrative Services</h5>
			<p><em>Government Office Administrator</p>
			<p>LiteraryAgent</p>
			<p>Human Resources Job Analyst</p>
			<p>Insurance Claims Examiner</p>
			<p>Medical Record Administrator</p>
			<p>Executive Assistant</p>
			<p>Transportation Ticket Agent</p>
			<p>Fire Department Secretary</p>
			<p>Receptionist</p>
			<p>Clerk
				<ul>
					<li>File</li>
					<li>Mail</li>
					<li>Insurance Processing</li>
				</ul></em></p>
		</div>
		<div class="col">
			<h5>Legal/Military Services</h5>
			<p><em>Law Librarian</p>
			<p>Paralegal</p>
			<p>Court Reporter</p>
			<p>Legal Secretary</p>
			<p>Flight Operations Specialist</p>
			<p>Legal Technician</p>
			<p>Personnel Specialist</p>
			<p>Deputy Sheriff</p>
			<p>Real Estate Closing Secretary</p>
			<p>Law Enforcement Dispatcher</p>
			<p>911 Operator</p>
			<p>Administrative Support Specialist</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Services</h5>
			<p><em>Social Worker
				<ul>
					<li>Occupational</li>
					<li>School</li>
					<li>Human Services</li>
				</ul></p>
			<p>Vocational Rehabilitation Counselor</p>
			<p>Postal Inspector</p>
			<p>Teacher Aide</p>
			<p>Real Estate Broker</p>
			<p>Flight Attendant</p>
			<p>Church Attendant</p>
			<p>Postal Worker</p>
			<p>Hospital Outpatient
			<p>Coordinator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Administrative Services</h5>
			<p><em>Government Office Administrator</p>
			<p>LiteraryAgent</p>
			<p>Human Resources Job Analyst</p>
			<p>Insurance Claims Examiner</p>
			<p>Medical Record Administrator</p>
			<p>Executive Assistant</p>
			<p>Transportation Ticket Agent</p>
			<p>Fire Department Secretary</p>
			<p>Receptionist</p>
			<p>Clerk
				<ul>
					<li>File</li>
					<li>Mail</li>
					<li>Insurance Processing</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Legal/Military Services</h5>
			<p><em>Law Librarian</p>
			<p>Paralegal</p>
			<p>Court Reporter</p>
			<p>Legal Secretary</p>
			<p>Flight Operations Specialist</p>
			<p>Legal Technician</p>
			<p>Personnel Specialist</p>
			<p>Deputy Sheriff</p>
			<p>Real Estate Closing Secretary</p>
			<p>Law Enforcement Dispatcher</p>
			<p>911 Operator</p>
			<p>Administrative Support Specialist</em></p>
		</div>
	</div>
	</div>

