	<div class="row">
		<div class="col-md-12">
			<p class="lead">Clerical/Administrative paired with Science/Mathematics (DH)</span></p>
			
			<div class="inter">
			
			<p>If you scored high in categories "D" and "H," you naturally
			understand that there are always ways to improve a situation.  You
			can probably handle several tasks at one time. People like you have
			made important contributions in business. You are an excellent
			thinker.  You are also likely to be a no-nonsense kind of person.
			You are creative and like to ask the question, "Why?" Because of
			this, you will look for new ways to do tasks.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree. In some of these jobs, it helps to have a master's degree or
			a Ph.D.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that emphasize math and
			science. Any courses that help you develop efficiency will be of
			great interest to you.  They will also help prepare you for possible
			career opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Business Education<br />
						Computer Information Systems<br />
						Computer Programming<br />
						Environmental Science
					</td>
					<td>
						Biology<br />
						Calculus<br />
						Accounting<br />
						Physics
					</td>
					<td>
						Sociology<br />
						Economics<br />
						Psychology<br />
						Trigonometry
					</td>
					<td>
						Business Math<br />
						Communications<br />
						World Languages<br />
						Public Relations
					</td>
					<td>
						Geography<br />
						Life Science<br />
						Computer Sciences
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations you
			may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. You will most enjoy any club or activity where you can
			use your thinking skills.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Environmental Activities<br />
						Future Business Leaders<br />
						Math/Science Club<br />
						Audio/Visual Services
					</td>
					<td>
						Computer Club<br />
						Library Assistant<br />
						Chess Club<br />
						Tutoring
					</td>
					<td>
						Hospital Volunteer<br />
						Office Assistant<br />
						Newspaper/Yearbook
					</td>
					<td>
						Teaching Assistant<br />
						Community Volunteer<br />
						Class Officer<br />
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Printing Companies<br />
						Computer Sales Companies<br />
						Archeological Projects<br />
						Engineering Firms<br />
						TV/Radio Stations<br />
						Photographic Laboratories
					</td>
					<td>
						Veterinary Offices<br />
						Accounting Firms<br />
						Landscaping Firms<br />
						Printing Companies<br />
						Architect Firms<br />
						Newspaper Offices
					</td>
					<td>
						Theaters<br />
						Computer Services<br />
						Libraries<br />
						Medical Offices<br />
						Electronic Stores<br />
						Libraries<br />
					</td>
					<td>
						Restaurants<br />
						Data Entry<br />
						Landscaping Firms<br />
						Restaurants<br />
						Newspaper Offices
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>DH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Administrative Services</h5>
			<p><em>Medical Record Administrator</p>
			<p>Medical
				<ul>
					<li>Transcriptionist</li>
					<li>Assistant</li>
					<li>Secretary</li>
					<li>Receptionist</li>
				</ul></p>
			<p>Pharmacist's Assistant</p>
			<p>Research Assistant</p>
			<p>Laboratory/Clinic Manager</p>
			<p>Medical Office Manager</p>
			<p>Human Service Worker</p>
			<p>Medical Coding Specialist</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Services</h5>
			<p><em>Geriatric Assessment Coordinator</p>
			<p>Physician's Assistant</p>
			<p>Nurse Supervisor</p>
			<p>Research Analyst</p>
			<p>Medical Librarian</p>
			<p>Dental Hygienist</p>
			<p>Science Technician</p>
			<p>Laboratory Technologist</p>
			<p>Licensed Practical Nurse</p>
			<p>Outpatient Coordinator</p>
			<p>Home Health Aide</em></p>
		</div>
		<div class="col">
			<h5>Math Services</h5>
			<p><em>Accountant</p>
			<p>Bio-statistician</p>
			<p>Public Health Program Specialist</p>
			<p>Researcher</p>
			<p>Bookkeeper</p>
			<p>Purchasing Agent</p>
			<p>Computer
				<ul>
					<li>Systems Analyst</li>
					<li>Programmer</li>
			 </ul></p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Statement</li>
					<li>Brokerage</li>
				</ul></p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Administrative Services</h5>
			<p><em>Medical Record Administrator</p>
			<p>Medical
				<ul>
					<li>Transcriptionist</li>
					<li>Assistant</li>
					<li>Secretary</li>
					<li>Receptionist</li>
				</ul></p>
			<p>Pharmacist's Assistant</p>
			<p>Research Assistant</p>
			<p>Laboratory/Clinic Manager</p>
			<p>Medical Office Manager</p>
			<p>Human Service Worker</p>
			<p>Medical Coding Specialist</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Services</h5>
			<p><em>Geriatric Assessment Coordinator</p>
			<p>Physician's Assistant</p>
			<p>Nurse Supervisor</p>
			<p>Research Analyst</p>
			<p>Medical Librarian</p>
			<p>Dental Hygienist</p>
			<p>Science Technician</p>
			<p>Laboratory Technologist</p>
			<p>Licensed Practical Nurse</p>
			<p>Outpatient Coordinator</p>
			<p>Home Health Aide</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Math Services</h5>
			<p><em>Accountant</p>
			<p>Bio-statistician</p>
			<p>Public Health Program Specialist</p>
			<p>Researcher</p>
			<p>Bookkeeper</p>
			<p>Purchasing Agent</p>
			<p>Computer
				<ul>
					<li>Systems Analyst</li>
					<li>Programmer</li>
			 </ul></p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Statement</li>
					<li>Brokerage</li>
				</ul></p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>

