	<div class="row">
		<div class="col-md-12">
			<p class="lead">Clerical/Administrative paired with Social/Helping (DI)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>DI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>Education Administrator</p>
			<p>Teacher
				<ul>
					<li>Business</li>
					<li>Continuing Education</li>
					<li>Computer</li>
					<li>Math</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Nursing Instructor</p>
			<p>Career Counselor</p>
			<p>Library Technician</p>
			<p>Pre-school Coordinator</p>
			<p>Computer Trainer</p>
			<p>Camp Counselor</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Assistant Hospital Administrator</p>
			<p>Clergy</p>
			<p>Social Care Worker</p>
			<p>Marriage & Family Therapist</p>
			<p>Retirement Facility Administrator</p>
			<p>Traffic Safety Administrator</p>
			<p>Flight Attendant</p>
			<p>Cruise Ship Activities Director</p>
			<p>Convention Coordinator</p>
			<p>Meeting & Events Planner</p>
			<p>Nursery School Child-Care Provider</em></p>
		</div>
		<div class="col">
			<h5>Administrative Helping</h5>
			<p><em>Bank Branch Manager</p>
			<p>Contract Administrator</p>
			<p>Loan Officer</p>
			<p>Office Manager</p>
			<p>Insurance Sales Agent</p>
			<p>Hotel Desk Clerk</p>
			<p>Customer Service Representative</p>
			<p>Claims Adjuster</p>
			<p>Personnel Clerk</p>
			<p>Hospital Receptionist</p>
			<p>Secretary</p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>Education Administrator</p>
			<p>Teacher
				<ul>
					<li>Business</li>
					<li>Continuing Education</li>
					<li>Computer</li>
					<li>Math</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Nursing Instructor</p>
			<p>Career Counselor</p>
			<p>Library Technician</p>
			<p>Pre-school Coordinator</p>
			<p>Computer Trainer</p>
			<p>Camp Counselor</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Assistant Hospital Administrator</p>
			<p>Clergy</p>
			<p>Social Care Worker</p>
			<p>Marriage & Family Therapist</p>
			<p>Retirement Facility Administrator</p>
			<p>Traffic Safety Administrator</p>
			<p>Flight Attendant</p>
			<p>Cruise Ship Activities Director</p>
			<p>Convention Coordinator</p>
			<p>Meeting & Events Planner</p>
			<p>Nursery School Child-Care Provider</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Administrative Helping</h5>
			<p><em>Bank Branch Manager</p>
			<p>Contract Administrator</p>
			<p>Loan Officer</p>
			<p>Office Manager</p>
			<p>Insurance Sales Agent</p>
			<p>Hotel Desk Clerk</p>
			<p>Customer Service Representative</p>
			<p>Claims Adjuster</p>
			<p>Personnel Clerk</p>
			<p>Hospital Receptionist</p>
			<p>Secretary</p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>

