	<div class="row">
		<div class="col-md-12">
			<p class="lead">Clerical/Administrative paired with Social/Helping (DI)</p>
			
			<div class="inter">
			
			<p>Your high scores in "D" and "I" show that you have
			characteristics that are useful to people. You are seen as
			dependable, friendly, and helpful. Others know that they can count
			on you. No matter what you choose to do, you will want to know you
			are helping people.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree.  In some of these jobs, it helps to have a master's degree
			or a Ph.D.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that help you to understand
			people. Any courses in social studies or social sciences will be of
			interest to you.  They will also help prepare you for possible
			career opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Logic<br />
						Education<br />
						Religion
					</td>
					<td>
						Computer Sciences<br />
						Health/Nutrition<br />
						Physical Education<br />
					</td>
					<td>
						Business Law<br />
						Life Sciences<br />
						Communications
					</td>
					<td>
						Psychology<br />
						Business Math<br />
						Sociology
					</td>
					<td>
						Bookkeeping<br />
						Home Economics<br />
						Business Education
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. You will most enjoy any club or activity where you can
			use your people skills.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Church Activities<br />
						Childcare / Eldercare<br />
						Hospital Volunteer<br />
						Newspaper / Yearbook
					</td>
					<td>
						Library Assistant<br />
						Class Officer<br />
						Tutoring<br />
						Peer Counselor
					</td>
					<td>
						Community Volunteer<br />
						Audio / Visual Services<br />
						Future Business Leaders
					</td>
					<td>
						Office Assistant<br />
						Teaching Assistant<br />
						Camp Counselor
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising Agencies<br />
						Company Offices<br />
						Printing Companies<br />
						Life Guarding<br />
					</td>
					<td>
						Day Care Centers<br />
						Photography Studios<br />
						Preschool Programs<br />
						Special Olympics
					</td>
					<td>
						Church Programs<br />
						Newspaper Offices<br />
						Libraries<br />
					</td>
					<td>
						Restaurants<br />
						Camp Programs<br />
						Recreational programs
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>DI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>Education Administrator</p>
			<p>Teacher
				<ul>
					<li>Business</li>
					<li>Continuing Education</li>
					<li>Computer</li>
					<li>Math</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Nursing Instructor</p>
			<p>Career Counselor</p>
			<p>Library Technician</p>
			<p>Pre-school Coordinator</p>
			<p>Computer Trainer</p>
			<p>Camp Counselor</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Assistant Hospital Administrator</p>
			<p>Clergy</p>
			<p>Social Care Worker</p>
			<p>Marriage & Family Therapist</p>
			<p>Retirement Facility Administrator</p>
			<p>Traffic Safety Administrator</p>
			<p>Flight Attendant</p>
			<p>Cruise Ship Activities Director</p>
			<p>Convention Coordinator</p>
			<p>Meeting & Events Planner</p>
			<p>Nursery School Child-Care Provider</em></p>
		</div>
		<div class="col">
			<h5>Administrative Helping</h5>
			<p><em>Bank Branch Manager</p>
			<p>Contract Administrator</p>
			<p>Loan Officer</p>
			<p>Office Manager</p>
			<p>Insurance Sales Agent</p>
			<p>Hotel Desk Clerk</p>
			<p>Customer Service Representative</p>
			<p>Claims Adjuster</p>
			<p>Personnel Clerk</p>
			<p>Hospital Receptionist</p>
			<p>Secretary</p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>Education Administrator</p>
			<p>Teacher
				<ul>
					<li>Business</li>
					<li>Continuing Education</li>
					<li>Computer</li>
					<li>Math</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Nursing Instructor</p>
			<p>Career Counselor</p>
			<p>Library Technician</p>
			<p>Pre-school Coordinator</p>
			<p>Computer Trainer</p>
			<p>Camp Counselor</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Assistant Hospital Administrator</p>
			<p>Clergy</p>
			<p>Social Care Worker</p>
			<p>Marriage & Family Therapist</p>
			<p>Retirement Facility Administrator</p>
			<p>Traffic Safety Administrator</p>
			<p>Flight Attendant</p>
			<p>Cruise Ship Activities Director</p>
			<p>Convention Coordinator</p>
			<p>Meeting & Events Planner</p>
			<p>Nursery School Child-Care Provider</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Administrative Helping</h5>
			<p><em>Bank Branch Manager</p>
			<p>Contract Administrator</p>
			<p>Loan Officer</p>
			<p>Office Manager</p>
			<p>Insurance Sales Agent</p>
			<p>Hotel Desk Clerk</p>
			<p>Customer Service Representative</p>
			<p>Claims Adjuster</p>
			<p>Personnel Clerk</p>
			<p>Hospital Receptionist</p>
			<p>Secretary</p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>

