	<div class="row">
		<div class="col-md-12">
			<p class="lead">Protective/Military Service paired with Technology (EF)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>EF Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Military</h5>
			<p><em>Transportation Director</p>
			<p>Military Strategist</p>
			<p>Air Traffic Controller</p>
			<p>Communications Manager</p>
			<p>Ship Captain</p>
			<p>Space Systems Specialist</p>
			<p>Recruiter</p>
			<p>Flight Crew Member</p>
			<p>Recreation Scout</p>
			<p>Flight Operations Specialist</p>
			<p>Radar Operator</p>
			<p>Aircraft Technician</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technology Operations</h5>
			<p><em>Archeologist</p>
			<p>Geologist</p>
			<p>Cartographer</p>
			<p>Physical Education Teacher</p>
			<p>Alcohol, Tobacco, and Firearms Agent</p>
			<p>Sports Coordinator</p>
			<p>Professional Athlete</p>
			<p>State Trooper</p>
			<p>Truck Driver</p>
			<p>Plumber</p>
			<p>Heavy Equipment Operator</em></p>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Engineer
				<ul>
					<li>Structural</li>
					<li>Electronics</li>
					<li>Mechanical</li>
					<li>Robotics</li>
					<li>Waste Management</li>
				</ul></p>
			<p>Aircraft Pilot</p>
			<p>Millwright</p>
			<p>Electrician</p>
			<p>Computer Service Technician</p>
			<p>Mechanical Engineering Technician</p>
			<p>Aircraft Technician</p>
			<p>Computer Operator</p>
			<p>Machinist</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Military</h5>
			<p><em>Transportation Director</p>
			<p>Military Strategist</p>
			<p>Air Traffic Controller</p>
			<p>Communications Manager</p>
			<p>Ship Captain</p>
			<p>Space Systems Specialist</p>
			<p>Recruiter</p>
			<p>Flight Crew Member</p>
			<p>Recreation Scout</p>
			<p>Flight Operations Specialist</p>
			<p>Radar Operator</p>
			<p>Aircraft Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technology Operations</h5>
			<p><em>Archeologist</p>
			<p>Geologist</p>
			<p>Cartographer</p>
			<p>Physical Education Teacher</p>
			<p>Alcohol, Tobacco, and Firearms Agent</p>
			<p>Sports Coordinator</p>
			<p>Professional Athlete</p>
			<p>State Trooper</p>
			<p>Truck Driver</p>
			<p>Plumber</p>
			<p>Heavy Equipment Operator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Engineer
				<ul>
					<li>Structural</li>
					<li>Electronics</li>
					<li>Mechanical</li>
					<li>Robotics</li>
					<li>Waste Management</li>
				</ul></p>
			<p>Aircraft Pilot</p>
			<p>Millwright</p>
			<p>Electrician</p>
			<p>Computer Service Technician</p>
			<p>Mechanical Engineering Technician</p>
			<p>Aircraft Technician</p>
			<p>Computer Operator</p>
			<p>Machinist</em></p>
		</div>
	</div>
	</div>

