	<div class="row">
		<div class="col-md-12">
			<p class="lead">Protective/Military Service paired with Social/Helping (EI)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>EI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Teaching/Guidance</h5>
			<p><em>Chaplain</p>
			<p>College Professor</p>
			<p>Librarian</p>
			<p>Industrial Arts Teacher</p>
			<p>Nurse</p>
			<p>Recruiting Specialist</p>
			<p>Religious Program Specialist</p>
			<p>Nursing Technician</p>
			<p>Trainer</p>
			<p>Instructor
				<ul>
					<li>Karate</li>
					<li>Sky Diving</li>
					<li>Skiing</li>
					<li>Scuba Diving</li>
				</ul></em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Helping/Supportive</h5>
			<p><em>Therapist</p>
			<p>Social Worker</p>
			<p>Chiropractor</p>
			<p>Food Service Director</p>
			<p>Housing Relocation Administration</p>
			<p>Physical Therapist Assistant</p>
			<p>Special Service Coordinator</p>
			<p>Interpreter/Translator</p>
			<p>Occupation Therapy Specialist</p>
			<p>Recreation Specialist</p>
			<p>Medical Service Technician</p>
			<p>Cleaning Service Owner</em></p>
		</div>
		<div class="col">
			<h5>Supportive Operations</h5>
			<p><em>U.S. Marshal</p>
			<p>Customs Inspector</p>
			<p>Private Investigator</p>
			<p>Police Officer/Military Police</p>
			<p>City/State Employee</p>
			<p>Correctional Officer</p>
			<p>Compliance Officer</p>
			<p>Volunteer Coordinator</p>
			<p>City Transportation Operator</p>
			<p>Security Guard</p>
			<p>Life Guard</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Teaching/Guidance</h5>
			<p><em>Chaplain</p>
			<p>College Professor</p>
			<p>Librarian</p>
			<p>Industrial Arts Teacher</p>
			<p>Nurse</p>
			<p>Recruiting Specialist</p>
			<p>Religious Program Specialist</p>
			<p>Nursing Technician</p>
			<p>Trainer</p>
			<p>Instructor
				<ul>
					<li>Karate</li>
					<li>Sky Diving</li>
					<li>Skiing</li>
					<li>Scuba Diving</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Helping/Supportive</h5>
			<p><em>Therapist</p>
			<p>Social Worker</p>
			<p>Chiropractor</p>
			<p>Food Service Director</p>
			<p>Housing Relocation Administration</p>
			<p>Physical Therapist Assistant</p>
			<p>Special Service Coordinator</p>
			<p>Interpreter/Translator</p>
			<p>Occupation Therapy Specialist</p>
			<p>Recreation Specialist</p>
			<p>Medical Service Technician</p>
			<p>Cleaning Service Owner</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Supportive Operations</h5>
			<p><em>U.S. Marshal</p>
			<p>Customs Inspector</p>
			<p>Private Investigator</p>
			<p>Police Officer/Military Police</p>
			<p>City/State Employee</p>
			<p>Correctional Officer</p>
			<p>Compliance Officer</p>
			<p>Volunteer Coordinator</p>
			<p>City Transportation Operator</p>
			<p>Security Guard</p>
			<p>Life Guard</em></p>
		</div>
	</div>
	</div>

