	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Protective/Military Service (AE)</span>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AE Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>

	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
				<h5>Military</h5>
				<p><em>Pilot</p>
				<p>Intelligence Specialist</p>
				<p>Graphic Information Specialist</p>
				<p>Aircraft Launch & Recovery Specialist</p>
				<p>Artillery Crew Member</p>
				<p>Military Police</p>
				<p>Platoon/Squad Leader</p>
				<p>Mapping Technician</p>
				<p>Explosive Blasting Specialist</em></p>
			</td>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental</h5>
			<p><em>Nature Scientist
				<ul>
					<li>Geologist</li>
					<li>Marine Biologist</li>
				</ul></p>
			<p>Agricultural Scientist</p>
			<p>Marine Surveyor</p>
			<p>Wildlife Manager</p>
			<p>Park Ranger</p>
			<p>Waste Management Technician</p>
			<p>Cartographer Technician</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Outdoor Service</h5>
			<p><em>Homeland Security Officer</p>
			<p>Immigration Specialist</p>
			<p>Public Safety Officer</p>
			<p>Construction Equipment Operator</p>
			<p>Firefighter</p>
			<p>Heavy Equipment Mechanic</p>
			<p>Security Guard</p>
			<p>Construction Worker</p>
			<p>Groundskeeper</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Military</h5>
			<p><em>Pilot</p>
			<p>Intelligence Specialist</p>
			<p>Graphic Information Specialist</p>
			<p>Aircraft Launch & Recovery Specialist</p>
			<p>Artillery Crew Member</p>
			<p>Military Police</p>
			<p>Platoon/Squad Leader</p>
			<p>Mapping Technician</p>
			<p>Explosive Blasting Specialist</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental</h5>
			<p><em>Nature Scientist
				<ul>
					<li>Geologist</li>
					<li>Marine Biologist</li>
				</ul></p>
			<p>Agricultural Scientist</p>
			<p>Marine Surveyor</p>
			<p>Wildlife Manager</p>
			<p>Park Ranger</p>
			<p>Waste Management Technician</p>
			<p>Cartographer Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Outdoor Service</h5>
			<p><em>Homeland Security Officer</p>
			<p>Immigration Specialist</p>
			<p>Public Safety Officer</p>
			<p>Construction Equipment Operator</p>
			<p>Firefighter</p>
			<p>Heavy Equipment Mechanic</p>
			<p>Security Guard</p>
			<p>Construction Worker</p>
			<p>Groundskeeper</em></p>
		</div>
	</div>
	</div>

