	<div class="row">
		<div class="col-md-12">
			<p class="lead">Protective/Military Service paired with Technology (EF)</p>
			
			<div class="inter">
			
			<p>With an "EF" interest, you will want to push your physical and
			mental strengths to their limits. You will want to be challenged and
			have adventures along the way.</p>
			<p>Many of the occupations in this pairing require some sort of
			specialized training after high school. Some require college degrees
			or college level courses.  For others, you will need technical
			training.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that allow you to challenge
			your mind. You will want to take technical courses too.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Business Law<br />
						Computer Sciences<br />
						Economics<br />
						Graphic Art<br />
					</td>
					<td>
						Computer Technology<br />
						Public Relations<br />
						Business Education<br />
						Computer Technology<br />
						Government/Civics
					</td>
					<td>
						Computer Programming<br />
						Environmental Sciences<br />
						Physical Education<br />
						Industrial Technology
					</td>
					<td>
						Logic<br />
						Sociology<br />
						History<br />
						Physics
					</td>
					<td>
						Drafting<br />
						Business Math<br />
						World Languages<br />
						Political Science
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular / volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for after-school activities or part-time jobs, make
			them count. Any club or activity where you are mentally and
			physically challenged will be valuable. You will also want
			technology to be a part of the activities.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Audiovisual Services<br />
						Newspaper/Yearbook<br />
						Math/Science Clubs
					</td>
					<td>
						Flight Training<br />
						Camp Activities<br />
						Library Assistant
					</td>
					<td>
						ROTC<br />
						Athletics<br />
						Scouts
					</td>
					<td>
						Band<br />
						Computer Club<br />
						Martial Arts
					</td>
					<td>
						Language Club<br />
						Parks/Recreation
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Appliance Repair<br />
						Environmental Services<br />
						Newspaper Offices<br />
						Photography Studios<br />
						Small Engine Repair
					</td>
					<td>
						Camp Counseling<br />
						Equipment Operations<br />
						Data Processing<br />
						Graphic Design Firms<br />
						Park Services<br />
					</td>
					<td>
						Lumberyards<br />
						Printing Companies<br />
						Construction<br />
						Equipment Repair<br />
						Landscaping Firms
					</td>
					<td>
						Company Offices<br />
						Delivery Services<br />
						Photographic Labs<br />
						Radio/TV Stations
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>EF Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Military</h5>
			<p><em>Transportation Director</p>
			<p>Military Strategist</p>
			<p>Air Traffic Controller</p>
			<p>Communications Manager</p>
			<p>Ship Captain</p>
			<p>Space Systems Specialist</p>
			<p>Recruiter</p>
			<p>Flight Crew Member</p>
			<p>Recreation Scout</p>
			<p>Flight Operations Specialist</p>
			<p>Radar Operator</p>
			<p>Aircraft Technician</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technology Operations</h5>
			<p><em>Archeologist</p>
			<p>Geologist</p>
			<p>Cartographer</p>
			<p>Physical Education Teacher</p>
			<p>Alcohol, Tobacco, and Firearms Agent</p>
			<p>Sports Coordinator</p>
			<p>Professional Athlete</p>
			<p>State Trooper</p>
			<p>Truck Driver</p>
			<p>Plumber</p>
			<p>Heavy Equipment Operator</em></p>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Engineer
				<ul>
					<li>Structural</li>
					<li>Electronics</li>
					<li>Mechanical</li>
					<li>Robotics</li>
					<li>Waste Management</li>
				</ul></p>
			<p>Aircraft Pilot</p>
			<p>Millwright</p>
			<p>Electrician</p>
			<p>Computer Service Technician</p>
			<p>Mechanical Engineering Technician</p>
			<p>Aircraft Technician</p>
			<p>Computer Operator</p>
			<p>Machinist</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Military</h5>
			<p><em>Transportation Director</p>
			<p>Military Strategist</p>
			<p>Air Traffic Controller</p>
			<p>Communications Manager</p>
			<p>Ship Captain</p>
			<p>Space Systems Specialist</p>
			<p>Recruiter</p>
			<p>Flight Crew Member</p>
			<p>Recreation Scout</p>
			<p>Flight Operations Specialist</p>
			<p>Radar Operator</p>
			<p>Aircraft Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technology Operations</h5>
			<p><em>Archeologist</p>
			<p>Geologist</p>
			<p>Cartographer</p>
			<p>Physical Education Teacher</p>
			<p>Alcohol, Tobacco, and Firearms Agent</p>
			<p>Sports Coordinator</p>
			<p>Professional Athlete</p>
			<p>State Trooper</p>
			<p>Truck Driver</p>
			<p>Plumber</p>
			<p>Heavy Equipment Operator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Engineer
				<ul>
					<li>Structural</li>
					<li>Electronics</li>
					<li>Mechanical</li>
					<li>Robotics</li>
					<li>Waste Management</li>
				</ul></p>
			<p>Aircraft Pilot</p>
			<p>Millwright</p>
			<p>Electrician</p>
			<p>Computer Service Technician</p>
			<p>Mechanical Engineering Technician</p>
			<p>Aircraft Technician</p>
			<p>Computer Operator</p>
			<p>Machinist</em></p>
		</div>
	</div>
	</div>

