	<div class="row">
		<div class="col-md-12">
			<p class="lead">Protective/Military Service paired with Public Service (EG)</p>
			
			<div class="inter">
			
			<p>Your high scores in this pairing show that you can be put into
			positions of leadership and responsibility. You are reliable and
			honest. You are also supportive and resourceful. You are the kind of
			person that employers prefer. You can plan and coordinate events as
			well as guide and influence people.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree. It is helpful to have a master's degree or Ph.D. if you hope
			to work in some of these occupations.</p>
			<p><strong>Courses you may want to consider taking in high school
			and beyond (in addition to English & Math):</strong><br />
			In high school you should take courses that will help you to
			understand people and train you for leadership roles. Social studies
			courses such as political science and sociology may interest you.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Drafting<br />
						Civics<br />
						Psychology<br />
						Geography
					</td>
					<td>
						Health/Nutrition<br />
						Physical Education<br />
						Computer Technology<br />
						Political Science
					</td>
					<td>
						Business Law<br />
						Communications<br />
						Business Math<br />
						Public Speaking
					</td>
					<td>
						Government<br />
						History<br />
						Music<br />
						Sociology<br />
					</td>
					<td>
						World Languages<br />
						Industrial Technology<br />
						Advertising/Marketing<br />
						Criminal Justice
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for after-school activities or part-time jobs, make
			them count. You will most enjoy any club or activity where you can
			use your mental and physical strength.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Band<br />
						Chess Club<br />
						ROTC
					</td>
					<td>
						Flight Training<br />
						Camp Activities<br />
						Hospital Volunteer
					</td>
					<td>
						Language Club<br />
						Martial Arts<br />
						Athletics
					</td>
					<td>
						Church Activities<br />
						Parks & Recreation<br />
						Youth Organizations
					</td>
					<td>
						Peer Counselor<br />
						Safety Patrol<br />
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Business Offices<br />
						Legal Offices<br />
						Newspaper Offices
					</td>
					<td>
						Camp Counseling<br />
						Courthouse Offices<br />
						Libraries
					</td>
					<td>
						Church Programs<br />
						Radio/TV Studios<br />
						Retail Stores
					</td>
					<td>
						Graphic Design Firms<br />
						Recreation Departments<br />
						Political Offices
					</td>
					<td>
						Special Olympics<br />
						Youth Coaching<br />
						Life Guarding
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>EG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community</h5>
			<p><em>Social Worker
				<ul>
					<li>Drug & Alcohol</li>
					<li>Family</li>
					<li>Public Health</li>
				</ul></p>
			<p>Public Health Consultant</p>
			<p>Public Affairs Officer</p>
			<p>Postal Service Administrator</p>
			<p>Firefighter</p>
			<p>Postal Service Personnel</p>
			<p>Religious Program Specialist</p>
			<p>Public Health Field Worker</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Legal</h5>
			<p><em>Lawyer</p>
			<p>Labor Relations Specialist</p>
			<p>Police Chief</p>
			<p>County Sheriff</p>
			<p>FBI Agent</p>
			<p>Investigator Detective</p>
			<p>Police Officer</p>
			<p>Legal Technician</p>
			<p>Customs Agent</p>
			<p>Security Guard</em></p>
		</div>
		<div class="col">
			<h5>Military</h5>
			<p><em>Chaplain</p>
			<p>Engineer</p>
			<p>Military Officer</p>
			<p>Transportation Manager</p>
			<p>Military Police</p>
			<p>Recruiting Specialist</p>
			<p>Interpreter & Translator</p>
			<p>Military Trainer</p>
			<p>Emergency Management Specialist</p>
			<p>Medic</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community</h5>
			<p><em>Social Worker
				<ul>
					<li>Drug & Alcohol</li>
					<li>Family</li>
					<li>Public Health</li>
				</ul></p>
			<p>Public Health Consultant</p>
			<p>Public Affairs Officer</p>
			<p>Postal Service Administrator</p>
			<p>Firefighter</p>
			<p>Postal Service Personnel</p>
			<p>Religious Program Specialist</p>
			<p>Public Health Field Worker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Legal</h5>
			<p><em>Lawyer</p>
			<p>Labor Relations Specialist</p>
			<p>Police Chief</p>
			<p>County Sheriff</p>
			<p>FBI Agent</p>
			<p>Investigator Detective</p>
			<p>Police Officer</p>
			<p>Legal Technician</p>
			<p>Customs Agent</p>
			<p>Security Guard</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Military</h5>
			<p><em>Chaplain</p>
			<p>Engineer</p>
			<p>Military Officer</p>
			<p>Transportation Manager</p>
			<p>Military Police</p>
			<p>Recruiting Specialist</p>
			<p>Interpreter & Translator</p>
			<p>Military Trainer</p>
			<p>Emergency Management Specialist</p>
			<p>Medic</em></p>
		</div>
	</div>
	</div>

