	<div class="row">
		<div class="col-md-12">
			<p class="lead">Protective/Military Service paired with Science/Mathematics (EH)</p>
			
			<div class="inter">
			
			<p>If you scored high in the "E" and "H" categories, you naturally
			understand that there are always ways to improve a situation.
			People like you have helped to discover much information about the
			world. You are an excellent thinker and are probably a hands-on kind
			of person. You are creative and like physical challenges.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree. It is helpful to have a master's degree or Ph.D. if you hope
			to work in some of these occupations.</p>
			<p><strong>Courses you may want to take in high school and beyond
			(In addition to English & Math):</strong><br />
			In high school you should take courses that emphasize math and
			science. You will also enjoy courses that allow you to use your
			physical strength.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting<br />
						Biology<br />
						Calculus
					</td>
					<td>
						Economics<br />
						Business Law<br />
						Chemistry
					</td>
					<td>
						Physics<br />
						Sociology<br />
						History
					</td>
					<td>
						Graphic Art<br />
						Political Science<br />
						Telecommunications
					</td>
					<td>
						Environmental Science<br />
						Technology Education<br />
						Computer Information Systems
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count.  You will enjoy any club or activity where you can use
			your thinking skills to face mental and physical challenges.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Athletics<br />
						ROTC<br />
						Martial Arts
					</td>
					<td>
						Flight Training<br />
						Parks/Recreation<br />
						Camp Activities
					</td>
					<td>
						Scouts<br />
						Tutoring<br />
						Band
					</td>
					<td>
						Computer Club<br />
						Chess Club<br />
						Language Club
					</td>
					<td>
						Hospital Volunteer<br />
						Environmental Activities<br />
						Math/Science Club
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting Firms<br />
						Athletic Programs<br />
						Data Entry
					</td>
					<td>
						Landscaping Firms<br />
						Newspaper Offices<br />
						Radio/TV Stations
					</td>
					<td>
						Electronic Stores<br />
						Photographic Labs<br />
						Medical Offices
					</td>
					<td>
						Architect Firm<br />
						Computer Services<br />
						Engineering Firms
					</td>
					<td>
						Printing Companies<br />
						Sports Companies<br />
						Veterinary Offices
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>EH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Sciences</h5>
			<p><em>Physician</p>
			<p>Military Medical Officer</p>
			<p>Sports Psychologist</p>
			<p>Exercise Physiologist</p>
			<p>Hospital Administrators</p>
			<p>Health Sciences Librarian</p>
			<p>Dietitian/Nutritionist</p>
			<p>Recreation Therapist</p>
			<p>Nurse</p>
			<p>Paramedic</p>
			<p>Technician
				<ul>
					<li>Medical
					<li>Operation Room
					<li>Military Cardiopulmonary</li>
				</ul></em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental</h5>
			<p><em>Archeologist</p>
			<p>Urban/Regional Planner</p>
			<p>Marine Biologist</p>
			<p>Engineer
				<ul>
					<li>Aerospace</li>
					<li>Environmental</li>
					<li>Nuclear</li>
				</ul></p>
			<p>Environmental Risk Manager</p>
			<p>Meteorologist</p>
			<p>Military
				<ul>
					<li>Land Surveyor</li>
					<li>Weather Observer</li>
					<li>Environmental Health Specialist</li>
				</ul></p>
			<p>Land Surveyor</p>
			<p>Waste Management Technician</em></p>
		</div>
		<div class="col">
			<h5>Math/Analyst</h5>
			<p><em>Economist</p>
			<p>Mathematician</p>
			<p>Actuary</p>
			<p>Statistician</p>
			<p>Military
				<ul>
					<li>Strategist</li>
					<li>Financial Manager</li>
					<li>Intelligence Officer</li>
				</ul></p>
			<p>Analyst
				<ul>
					<li>Budget</li>
					<li>Research</li>
					<li>Computer Systems</li>
				</ul></p>
			<p>Computer Security Specialist</p>
			<p>Mapping Technician</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Sciences</h5>
			<p><em>Physician</p>
			<p>Military Medical Officer</p>
			<p>Sports Psychologist</p>
			<p>Exercise Physiologist</p>
			<p>Hospital Administrators</p>
			<p>Health Sciences Librarian</p>
			<p>Dietitian/Nutritionist</p>
			<p>Recreation Therapist</p>
			<p>Nurse</p>
			<p>Paramedic</p>
			<p>Technician
				<ul>
					<li>Medical
					<li>Operation Room
					<li>Military Cardiopulmonary</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental</h5>
			<p><em>Archeologist</p>
			<p>Urban/Regional Planner</p>
			<p>Marine Biologist</p>
			<p>Engineer
				<ul>
					<li>Aerospace</li>
					<li>Environmental</li>
					<li>Nuclear</li>
				</ul></p>
			<p>Environmental Risk Manager</p>
			<p>Meteorologist</p>
			<p>Military
				<ul>
					<li>Land Surveyor</li>
					<li>Weather Observer</li>
					<li>Environmental Health Specialist</li>
				</ul></p>
			<p>Land Surveyor</p>
			<p>Waste Management Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Math/Analyst</h5>
			<p><em>Economist</p>
			<p>Mathematician</p>
			<p>Actuary</p>
			<p>Statistician</p>
			<p>Military
				<ul>
					<li>Strategist</li>
					<li>Financial Manager</li>
					<li>Intelligence Officer</li>
				</ul></p>
			<p>Analyst
				<ul>
					<li>Budget</li>
					<li>Research</li>
					<li>Computer Systems</li>
				</ul></p>
			<p>Computer Security Specialist</p>
			<p>Mapping Technician</em></p>
		</div>
	</div>
	</div>


