	<div class="row">
		<div class="col-md-12">
			<p class="lead">Protective/Military Service paired with Science/Mathematics (EH)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>EH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Sciences</h5>
			<p><em>Physician</p>
			<p>Military Medical Officer</p>
			<p>Sports Psychologist</p>
			<p>Exercise Physiologist</p>
			<p>Hospital Administrators</p>
			<p>Health Sciences Librarian</p>
			<p>Dietitian/Nutritionist</p>
			<p>Recreation Therapist</p>
			<p>Nurse</p>
			<p>Paramedic</p>
			<p>Technician
				<ul>
					<li>Medical
					<li>Operation Room
					<li>Military Cardiopulmonary</li>
				</ul></em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental</h5>
			<p><em>Archeologist</p>
			<p>Urban/Regional Planner</p>
			<p>Marine Biologist</p>
			<p>Engineer
				<ul>
					<li>Aerospace</li>
					<li>Environmental</li>
					<li>Nuclear</li>
				</ul></p>
			<p>Environmental Risk Manager</p>
			<p>Meteorologist</p>
			<p>Military
				<ul>
					<li>Land Surveyor</li>
					<li>Weather Observer</li>
					<li>Environmental Health Specialist</li>
				</ul></p>
			<p>Land Surveyor</p>
			<p>Waste Management Technician</em></p>
		</div>
		<div class="col">
			<h5>Math/Analyst</h5>
			<p><em>Economist</p>
			<p>Mathematician</p>
			<p>Actuary</p>
			<p>Statistician</p>
			<p>Military
				<ul>
					<li>Strategist</li>
					<li>Financial Manager</li>
					<li>Intelligence Officer</li>
				</ul></p>
			<p>Analyst
				<ul>
					<li>Budget</li>
					<li>Research</li>
					<li>Computer Systems</li>
				</ul></p>
			<p>Computer Security Specialist</p>
			<p>Mapping Technician</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Sciences</h5>
			<p><em>Physician</p>
			<p>Military Medical Officer</p>
			<p>Sports Psychologist</p>
			<p>Exercise Physiologist</p>
			<p>Hospital Administrators</p>
			<p>Health Sciences Librarian</p>
			<p>Dietitian/Nutritionist</p>
			<p>Recreation Therapist</p>
			<p>Nurse</p>
			<p>Paramedic</p>
			<p>Technician
				<ul>
					<li>Medical
					<li>Operation Room
					<li>Military Cardiopulmonary</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental</h5>
			<p><em>Archeologist</p>
			<p>Urban/Regional Planner</p>
			<p>Marine Biologist</p>
			<p>Engineer
				<ul>
					<li>Aerospace</li>
					<li>Environmental</li>
					<li>Nuclear</li>
				</ul></p>
			<p>Environmental Risk Manager</p>
			<p>Meteorologist</p>
			<p>Military
				<ul>
					<li>Land Surveyor</li>
					<li>Weather Observer</li>
					<li>Environmental Health Specialist</li>
				</ul></p>
			<p>Land Surveyor</p>
			<p>Waste Management Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Math/Analyst</h5>
			<p><em>Economist</p>
			<p>Mathematician</p>
			<p>Actuary</p>
			<p>Statistician</p>
			<p>Military
				<ul>
					<li>Strategist</li>
					<li>Financial Manager</li>
					<li>Intelligence Officer</li>
				</ul></p>
			<p>Analyst
				<ul>
					<li>Budget</li>
					<li>Research</li>
					<li>Computer Systems</li>
				</ul></p>
			<p>Computer Security Specialist</p>
			<p>Mapping Technician</em></p>
		</div>
	</div>
	</div>


