<span class="header1">Protective/Military Service paired with 
Social/Helping (EI)</span>

<p>Your high scores in "E" and "I" show that you have 
characteristics that are useful to people. You will be highly valued 
in the work force. Your strengths will be useful in many different 
occupations. You have a desire to share information with others and 
will be able to do this in a systematic way. You can be a leader if 
necessary.</p>
<p>Most occupations in this pairing require at least a bachelor's 
degree. In some of these jobs, it helps to have a master's degree or 
a Ph.D.</p>
<p><strong>Courses you might want to take in high school and beyond 
(in addition to English & Math):</strong><br />
In high school you should take courses that help you to understand 
people. Any courses in social studies or social sciences will be of 
interest.  They will also help prepare you for possible career 
opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Education<br />
			Religion<br />
			Graphic Arts<br />
			Psychology
		</td>
		<td>
			Government/Civics<br />
			Computer Technology<br />
			Home Economics<br />
			Communications
		</td>
		<td>
			Health/Nutrition<br />
			Physical Education<br />
			Foreign Language<br />
		</td>
		<td>
			Sociology<br />
			Life Science<br />
			Physics
		</td>
		<td>
			Political Science<br />
			Public Relations<br />
			Industrial Technology
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations 
you may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make 
them count. You will enjoy any club or activity where you can use 
your people skills and participate in mental or physical 
challenges.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			ROTC<br />
			Athletics<br />
			Band<br />
			Martial Arts
		</td>
		<td>
			Church Activities<br />
			Childcare/Eldercare<br />
			Hospital Volunteer<br />
			Flight Training
		</td>
		<td>
			Community Volunteer<br />
			Language Clubs<br />
			Parks/Recreation
		</td>
		<td>
			Scouts<br />
			Peer Counselor<br />
			Tutoring
		</td>
		<td>
			Teaching Assistant<br />
			Community Volunteer<br />
			Camp Counselor
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time 
job:</strong><br />
These places may offer valuable opportunities to help you decide 
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising Agencies<br />
			Graphic Design Firm<br />
			Photographic Studios
		</td>
		<td>
			Company Offices<br />
			Newspaper Offices<br />
			Recreation Departments
		</td>
		<td>
			Preschool Programs<br />
			Camp Programs<br />
			Day Care Centers<br />
		</td>
		<td>
			Life Guarding<br />
			Libraries<br />
			Restaurants
		</td>
		<td>
			Church Programs<br />
			Printing Companies<br />
			Special Olympics
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to 
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">EI Career 
Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" 
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" 
align="left"><strong>More People Oriented</strong></td>
					<td width="33%" 
align="center"><strong><----------></strong></td>
					<td width="33%" 
align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" 
cellspacing="0" height="400">
				<tr align="center" 
height="33%"><td><strong>More<br /></strong></td></tr>
				<tr align="center" 
height="33%"><td><strong>Education<br />or<br />Training<br />Require
d</strong></td></tr>
				<tr align="center" 
height="33%"><td><strong><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" 
cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span 
class="header2">Teaching/Guidance</span><br /><br />
					
	<em>Chaplain<br /><br />
						College 
Professor<br /><br />
						Librarian<br /><br />
						Industrial Arts 
Teacher<br /><br />
						Nurse<br /><br />
						Recruiting 
Specialist<br /><br />
						Religious Program 
Specialist<br /><br />
						Nursing 
Technician<br /><br />
						Trainer<br /><br />
						Instructor
							<ul>
							
	<li>Karate</li>
							
	<li>Sky Diving</li>
							
	<li>Skiing</li>
							
	<li>Scuba Diving</li>
							</ul></em>
					</td>
					<td width="33%">
						<span 
class="header2">Helping/Supportive</span><br /><br />
					
	<em>Therapist<br /><br />
						Social 
Worker<br /><br />
					
	Chiropractor<br /><br />
						Food Service 
Director<br /><br />
						Housing Relocation 
Administration<br /><br />
						Physical Therapist 
Assistant<br /><br />
						Special Service 
Coordinator<br /><br />
					
	Interpreter/Translator<br /><br />
						Occupation Therapy 
Specialist<br /><br />
						Recreation 
Specialist<br /><br />
						Medical Service 
Technician<br /><br />
						Cleaning Service 
Owner</em>
					</td>
					<td width="33%">
						<span 
class="header2">Supportive Operations</span><br /><br />
						<em>U.S. 
Marshal<br /><br />
						Customs 
Inspector<br /><br />
						Private 
Investigator<br /><br />
						Police 
Officer/Military Police<br /><br />
						City/State 
Employee<br /><br />
						Correctional 
Officer<br /><br />
						Compliance 
Officer<br /><br />
						Volunteer 
Coordinator<br /><br />
						City Transportation 
Operator<br /><br />
						Security 
Guard<br /><br />
						Life Guard</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">TEACHING/GUIDANCE</span>
<p>The occupations in this field allow you to help others while 
working in a place that has set procedures and guidelines. If you 
like to know what is expected of you, these are good job 
possibilities.</p>

<hr size="1" />

	<span class="header2">Clergy (Pastor, Priest, Rabbi) 
</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/43007.jpg" 
width="100" height="100" border="0" alt="Chaplain" />
	<span class="header3">Job Description</span>
	<blockquote>Conduct religious worship and perform other 
spiritual functions associated with beliefs and practices of 
religious faith or denomination. Provide spiritual and moral 
guidance and assistance to members.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a master's degree in theology to become 
a clergy. In addition, you would be "ordained" by a religious 
denomination.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>According to the job-search website indeed.com, 
the median annual wage of clergy was $44,000 in September 
2012.<blockquote>

<hr size="1" />

	<span class="header2">Military Trainer</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/M99.jpg" 
width="100" height="100" border="0" alt="Military Trainer" />
	<span class="header3">Job Description</span>
	<blockquote>A military trainer is a teacher. As a military 
trainer, you would teach, lecture, and test military personnel. You 
might train new recruits on how to drive a tank. Or, you might teach 
officers to use a new computer program. You would actually do many 
of the same things your classroom teacher does to prepare for 
his/her students.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree for this job.  Some 
training would be provided by the military.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>According to the job-search website indeed.com, 
the median annual wage of military trainers was $122,000 in 
September 2012.</blockquote>

<hr size="1" />

	<span class="header2">Recruiting 
Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/M37.jpg" 
width="100" height="100" border="0" alt="Recruiting Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>A recruiting specialist helps those who are 
interested in joining the military to sign up. In this job, you 
would interview people who wanted to join the military.  You would 
also speak to high school and community groups.</blockquote>
	<span class="header3">Educations</span>
	<blockquote>You would need a high school diploma to become a 
recruiting specialist. Courses in English, social studies, and 
public speaking are valuable.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of recruiting specialists 
was $52,690 in May 2010. </blockquote>

<hr size="1" />

<span class="header1">HELPING/SUPPORTIVE</span>
<p>The occupations in this field provide services to others that 
help them to improve their well-being. If you want to help people 
stay healthy, these occupations might be for you.</p>

<hr size="1" />

	<span class="header2">Chiropractor</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/43039.jpg" 
width="100" height="100" border="0" alt="Chiropractor" />
	<span class="header3">Job Description</span>
	<blockquote>A chiropractor believes that disease, pain, and 
poor health are caused by problems with the spinal column, muscles, 
and nerves.  As a chiropractor, you would help your patients feel 
better by "adjusting" their spinal column.  Most chiropractors work 
for themselves so knowledge of a small business would be 
helpful.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Chiropractors must be licensed, which requires 
two to four years of undergraduate education, the completion of a 
four-year chiropractic college course, and passing scores on 
national and state examinations.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of chiropractors was 
$67,200 in May 2010. </blockquote>

<hr size="1" />

	<span class="header2">Physical Therapy 
Assistant</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Under the direction and supervision of physical 
therapists, they provide part of a patient's treatment. This might 
involve exercises, massages, electrical stimulation, paraffin baths, 
hot and cold packs, traction, and ultrasound. Physical therapist 
assistants record the patient's responses to treatment and report 
the outcome of each treatment to the physical therapist.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most physical therapist assistants earn an 
associate degree from an accredited physical therapist assistant 
program. Some states require licensing for physical therapist 
assistants.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of physical therapy 
assistants was $37,710 in May 2010. </blockquote>

<hr size="1" />

	<span class="header2">School Counselor</span><br /><br />
		<span class="header3">Job Descriptions</span>
	<blockquote>School counselors assist students of all levels, 
from elementary school to postsecondary education. They advocate for 
students and work with other individuals and organizations to 
promote the academic, career, personal, and social development of 
children and youth. School counselors help students evaluate their 
abilities, interests, talents, and personalities to develop 
realistic academic and career goals.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Many states require school counselors to hold a 
state school counseling certification and to have completed at least 
some graduate course work; most require the completion of a master's 
degree. Some states require school counselors to be licensed, which 
generally requires continuing education credits.  </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of school counselors was 
$53,380 in May 2010. </blockquote>

<hr size="1" />

<span class="header1">SUPPORTIVE OPERATIONS</span>
<p>The occupations in this field mainly deal with law enforcement. 
If you want to make sure others are safe, consider these jobs.</p>

<hr size="1" />

	<span class="header2">U.S. Marshal</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>The main job of a U.S. marshal is to protect 
federal employees in the court system. As a marshal, you might be 
responsible for making sure that a federal courtroom is safe. You 
would protect the judge, clerk, and jurors. You could be assigned to 
protect a prisoner.  You could also be expected to track down an 
escaped prisoner. Being a U.S. marshal is a demanding 
job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To be appointed as a U.S. Marshal (USM), the 
candidate should have college training, significant experience in 
the administration of justice, including four years of command-level 
law enforcement management duties, experience in coordinating with 
law enforcement agencies, and experience with local, state or 
federal court systems to include the protection of court personnel,
jurors and witnesses.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of U.S marshalls was 
$19,260 in May 2010. </blockquote>

<hr size="1" />

	<span class="header2">U.S. Customs and Border Patrol
Agent</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/25032.jpg" 
width="100" height="100" border="0" alt="Customs Agent" />
	<span class="header3">Job Description</span>
	<blockquote>Many people come into the United States from 
other countries to visit or live. Goods or products also arrive 
every day. To enter the country, people and goods must go through 
customs. As a customs agent, you would work at an airport, 
seaport, or border.  Your job would be to enforce our country's 
laws. You might be assigned to inspect goods coming into the 
country. You would make sure taxes were paid and that nothing 
illegal was being brought in.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree or three years of 
work experience for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>According to the job-search website indeed.com, 
tghe median annual wage of U.S Customs was $27,000 in September 
2012. </blockquote>

<hr size="1" />

	<span class="header2">Military Police</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/M26.jpg" 
width="100" height="100" border="0" alt="Military Police" />
	<span class="header3">Job Description</span>
	<blockquote>Each branch of the military has its own police 
department. As a  member of the military police, you would make sure 
that people and properties were safe. You might patrol the base or 
facility. You would provide traffic control when needed. You might 
also make arrests.</blockquote>
	<span class="header3">Education</span>
	<blockquote>On-the-job training is provided for 
M.P.'s.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>According to the job-search website indeed.com, 
the median annual wage of military police was $72,000 in September 
2012.<blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit 
the <em>Occupational Outlook Handbook</em>:</strong> <a 
href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information 
Network</em> Web site:</strong> <a 
href="http://online.onetcenter.org/gen_search_page">online.onetcenter
.org/gen_search_page</a></p>



<blockquote>Salary data from Bureau of Labor Statistics, U.S. 
Department of Labor, <i>Occupational Outlook Handbook, 2012-13 
Edition, </i> visited 8/27/2012. </blockquote>



Additional average salary information acquired from job search 
website indeed.com in September 2012. The Indeed Salary Search data 
is based on an index of salary information extracted from over 50 
million job postings from thousands of unique sources over the 
previous year.



