	<div class="row">
		<div class="col-md-12">
			<p class="lead">Protective/Military Service paired with Social/Helping (EI)</p>
			
			<div class="inter">
			
			<p>Your high scores in "E" and "I" show that you have
			characteristics that are useful to people. You will be highly valued
			in the work force. Your strengths will be useful in many different
			occupations. You have a desire to share information with others and
			will be able to do this in a systematic way. You can be a leader if
			necessary.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree. In some of these jobs, it helps to have a master's degree or
			a Ph.D.</p>
			<p><strong>Courses you might want to take in high school and beyond
			(in addition to English & Math):</strong><br />
			In high school you should take courses that help you to understand
			people. Any courses in social studies or social sciences will be of
			interest.  They will also help prepare you for possible career
			opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Education<br />
						Religion<br />
						Graphic Arts<br />
						Psychology
					</td>
					<td>
						Government/Civics<br />
						Computer Technology<br />
						Home Economics<br />
						Communications
					</td>
					<td>
						Health/Nutrition<br />
						Physical Education<br />
						World Languages<br />
					</td>
					<td>
						Sociology<br />
						Life Science<br />
						Physics
					</td>
					<td>
						Political Science<br />
						Public Relations<br />
						Industrial Technology
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. You will enjoy any club or activity where you can use
			your people skills and participate in mental or physical
			challenges.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						ROTC<br />
						Athletics<br />
						Band<br />
						Martial Arts
					</td>
					<td>
						Church Activities<br />
						Childcare/Eldercare<br />
						Hospital Volunteer<br />
						Flight Training
					</td>
					<td>
						Community Volunteer<br />
						Language Clubs<br />
						Parks/Recreation
					</td>
					<td>
						Scouts<br />
						Peer Counselor<br />
						Tutoring
					</td>
					<td>
						Teaching Assistant<br />
						Community Volunteer<br />
						Camp Counselor
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising Agencies<br />
						Graphic Design Firm<br />
						Photography Studios
					</td>
					<td>
						Company Offices<br />
						Newspaper Offices<br />
						Recreation Departments
					</td>
					<td>
						Preschool Programs<br />
						Camp Programs<br />
						Day Care Centers<br />
					</td>
					<td>
						Life Guarding<br />
						Libraries<br />
						Restaurants
					</td>
					<td>
						Church Programs<br />
						Printing Companies<br />
						Special Olympics
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>EI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Teaching/Guidance</h5>
			<p><em>Chaplain</p>
			<p>College Professor</p>
			<p>Librarian</p>
			<p>Industrial Arts Teacher</p>
			<p>Nurse</p>
			<p>Recruiting Specialist</p>
			<p>Religious Program Specialist</p>
			<p>Nursing Technician</p>
			<p>Trainer</p>
			<p>Instructor
				<ul>
					<li>Karate</li>
					<li>Sky Diving</li>
					<li>Skiing</li>
					<li>Scuba Diving</li>
				</ul></em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Helping/Supportive</h5>
			<p><em>Therapist</p>
			<p>Social Worker</p>
			<p>Chiropractor</p>
			<p>Food Service Director</p>
			<p>Housing Relocation Administration</p>
			<p>Physical Therapist Assistant</p>
			<p>Special Service Coordinator</p>
			<p>Interpreter/Translator</p>
			<p>Occupation Therapy Specialist</p>
			<p>Recreation Specialist</p>
			<p>Medical Service Technician</p>
			<p>Cleaning Service Owner</em></p>
		</div>
		<div class="col">
			<h5>Supportive Operations</h5>
			<p><em>U.S. Marshal</p>
			<p>Customs Inspector</p>
			<p>Private Investigator</p>
			<p>Police Officer/Military Police</p>
			<p>City/State Employee</p>
			<p>Correctional Officer</p>
			<p>Compliance Officer</p>
			<p>Volunteer Coordinator</p>
			<p>City Transportation Operator</p>
			<p>Security Guard</p>
			<p>Life Guard</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Teaching/Guidance</h5>
			<p><em>Chaplain</p>
			<p>College Professor</p>
			<p>Librarian</p>
			<p>Industrial Arts Teacher</p>
			<p>Nurse</p>
			<p>Recruiting Specialist</p>
			<p>Religious Program Specialist</p>
			<p>Nursing Technician</p>
			<p>Trainer</p>
			<p>Instructor
				<ul>
					<li>Karate</li>
					<li>Sky Diving</li>
					<li>Skiing</li>
					<li>Scuba Diving</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Helping/Supportive</h5>
			<p><em>Therapist</p>
			<p>Social Worker</p>
			<p>Chiropractor</p>
			<p>Food Service Director</p>
			<p>Housing Relocation Administration</p>
			<p>Physical Therapist Assistant</p>
			<p>Special Service Coordinator</p>
			<p>Interpreter/Translator</p>
			<p>Occupation Therapy Specialist</p>
			<p>Recreation Specialist</p>
			<p>Medical Service Technician</p>
			<p>Cleaning Service Owner</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Supportive Operations</h5>
			<p><em>U.S. Marshal</p>
			<p>Customs Inspector</p>
			<p>Private Investigator</p>
			<p>Police Officer/Military Police</p>
			<p>City/State Employee</p>
			<p>Correctional Officer</p>
			<p>Compliance Officer</p>
			<p>Volunteer Coordinator</p>
			<p>City Transportation Operator</p>
			<p>Security Guard</p>
			<p>Life Guard</em></p>
		</div>
	</div>
	</div>

