	<div class="row">
		<div class="col-md-12">
			<p class="lead">Technology paired with Public Service (FG)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>FG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>
			<p><em>Inspector
				<ul>
					<li>Building</li>
					<li>Public Works</li>
				</ul></p>
			<p>Land Surveyor</p>
			<p>Environmental Grass Roots Coordinator</p>
			<p>Police Officer</p>
			<p>Immigration Inspector</p>
			<p>Firefighter</p>
			<p>Recreation Worker</p>
			<p>Bus Driver</p>
			<p>Subway Operator</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technical Service</h5>
			<p><em>Industrial Labor Relations Specialist</p>
			<p>Engineer
				<ul>
					<li>Civil</li>
					<li>Aircraft</li>
					<li>Structural</li>
				</ul></p>
			<p>Hazardous Waste Management</p>
			<p>Plant Safety Specialist</p>
			<p>Equipment Specialist</p>
			<p>Tour Boat Captain</p>
			<p>Broadcast Technician</p>
			<p>Waste Management Technician</em></p>
		</div>
		<div class="col">
			<h5>Nature/Wildlife Service</h5>
			<p><em>Environmentalist</p>
			<p>Environmental Protection Specialist</p>
			<p>Historic Preservationist</p>
			<p>Park Ranger</p>
			<p>Recreation Administrator</p>
			<p>Nature Interpreter</p>
			<p>Zoo Keeper</p>
			<p>Recreations Site Developer</p>
			<p>Ranger Aide</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>
			<p><em>Inspector
				<ul>
					<li>Building</li>
					<li>Public Works</li>
				</ul></p>
			<p>Land Surveyor</p>
			<p>Environmental Grass Roots Coordinator</p>
			<p>Police Officer</p>
			<p>Immigration Inspector</p>
			<p>Firefighter</p>
			<p>Recreation Worker</p>
			<p>Bus Driver</p>
			<p>Subway Operator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technical Service</h5>
			<p><em>Industrial Labor Relations Specialist</p>
			<p>Engineer
				<ul>
					<li>Civil</li>
					<li>Aircraft</li>
					<li>Structural</li>
				</ul></p>
			<p>Hazardous Waste Management</p>
			<p>Plant Safety Specialist</p>
			<p>Equipment Specialist</p>
			<p>Tour Boat Captain</p>
			<p>Broadcast Technician</p>
			<p>Waste Management Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Nature/Wildlife Service</h5>
			<p><em>Environmentalist</p>
			<p>Environmental Protection Specialist</p>
			<p>Historic Preservationist</p>
			<p>Park Ranger</p>
			<p>Recreation Administrator</p>
			<p>Nature Interpreter</p>
			<p>Zoo Keeper</p>
			<p>Recreations Site Developer</p>
			<p>Ranger Aide</em></p>
		</div>
	</div>
	</div>

