	<div class="row">
		<div class="col-md-12">
			<p class="lead">Arts/Communications paired with Technology (BF)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>BF Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications</h5>
			<p><em>Medial Specialist</p>
			<p>Public Relations Specialist</p>
			<p>Editor</p>
			<p>Technical Writer</p>
			<p>Public Relations Assistant</p>
			<p>Sportscaster</p>
			<p>Desktop Publisher</p>
			<p>Tour Publicist</p>
			<p>Interpretive Naturalist</p>
			<p>Musician</p>
			<p>Actor</p>
			<p>Cruise Ship Entertainer</em>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Technology</h5>
			<p><em>Industrial Designer</p>
			<p>Graphic Artist</p>
			<p>Photographer</p>
			<p>Camera Operator</p>
			<p>Lighting Designer</p>
			<p>Video Editor</p>
			<p>Drafting Technician</p>
			<p>Metal Artist/Fabricator</p>
			<p>Model Maker</p>
			<p>Airbrush Artist</p>
			<p>Tattoo Artist</em>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Exhibit Builder</p>
			<p>Theater Lighting Designer</p>
			<p>Sound Mixer</p>
			<p>Radio/TV Service Technician</p>
			<p>Book Binder</p>
			<p>Road Manager</p>
			<p>Roller Coaster Technician</p>
			<p>Tile Setter</p>
			<p>Painter</p>
			<p>Printer Developer</p>
			<p>Carpenter</p>
			<p>Landscape Gardener</p>
			<p>Entertainer Body Guard</em>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Communications</h5>
			<p><em>Medial Specialist</p>
			<p>Public Relations Specialist</p>
			<p>Editor</p>
			<p>Technical Writer</p>
			<p>Public Relations Assistant</p>
			<p>Sportscaster</p>
			<p>Desktop Publisher</p>
			<p>Tour Publicist</p>
			<p>Interpretive Naturalist</p>
			<p>Musician</p>
			<p>Actor</p>
			<p>Cruise Ship Entertainer</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Creative Technology</h5>
			<p><em>Industrial Designer</p>
			<p>Graphic Artist</p>
			<p>Photographer</p>
			<p>Camera Operator</p>
			<p>Lighting Designer</p>
			<p>Video Editor</p>
			<p>Drafting Technician</p>
			<p>Metal Artist/Fabricator</p>
			<p>Model Maker</p>
			<p>Airbrush Artist</p>
			<p>Tattoo Artist</em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Technology</h5>
			<p><em>Exhibit Builder</p>
			<p>Theater Lighting Designer</p>
			<p>Sound Mixer</p>
			<p>Radio/TV Service Technician</p>
			<p>Book Binder</p>
			<p>Road Manager</p>
			<p>Roller Coaster Technician</p>
			<p>Tile Setter</p>
			<p>Painter</p>
			<p>Printer Developer</p>
			<p>Carpenter</p>
			<p>Landscape Gardener</p>
			<p>Entertainer Body Guard</em>
		</div>
	</div>
	</div>

