	<div class="row">
		<div class="col-md-12">
			<p class="lead">Technology paired with Public Service (FG)</p>
			
			<div class="inter">
			
			<p>You will be a valued member of the work force. You are very
			community minded and prefer a "hands-on" approach. You want to make
			the world a better place through technology.  There are many
			occupations that require being able to work with people, machines,
			and tools.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree. It is helpful to have a master's degree or Ph.D. if you hope
			to work in some of these occupations.</p>
			<p><strong>Courses you may want to take in high school and beyond
			(in addition to English & Math):</strong><br />
			In high school you should take courses that will help you
			understand people, machines, and tools. Technology courses such as
			computer science and programming will be of interest to you.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Government/Civics<br />
						Public Speaking<br />
						Computer Sciences<br />
						Business Law<br />
						Physical Education
					</td>
					<td>
						Computer Programming<br />
						Marketing/Advertising<br />
						Technology Education<br />
						Environmental Science
					</td>
					<td>
						Geography<br />
						Psychology<br />
						Sociology<br />
						Economics
					</td>
					<td>
						Business Math<br />
						World Languages<br />
						Public Speaking<br />
						Political Science
					</td>
					<td>
						Telecommunications<br />
						Health/Nutrition<br />
						Business Education
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for after-school activities or part-time jobs, make
			them count. You will enjoy any club or activity where you can use
			technology.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Church Activities<br />
						Hospital Volunteer<br />
						Computer Club<br />
						Library Assistant
					</td>
					<td>
						Audio/Visual Services<br />
						Environmental Activities<br />
						Youth Organizations
					</td>
					<td>
						Chess Club<br />
						Safety Patrol<br />
						Tutoring
					</td>
					<td>
						Camp Counselor<br />
						Newspaper/Yearbook<br />
						Math/Science Clubs
					</td>
					<td>
						Peer Counselor<br />
						Martial Arts
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Graphic Design Firms<br />
						Printing Companies<br />
						Road Construction
					</td>
					<td>
						Camp Counseling<br />
						Life Guarding<br />
						Youth Coaching
					</td>
					<td>
						Church Programs<br />
						Newspaper Offices<br />
						Legal Activities
					</td>
					<td>
						Special Olympics<br />
						Libraries<br />
						Recreation Depts.
					</td>
					<td>
						Courthouse Offices<br />
						Radio/TV Stations<br />
						Political Offices
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>FG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>
			<p><em>Inspector
				<ul>
					<li>Building</li>
					<li>Public Works</li>
				</ul></p>
			<p>Land Surveyor</p>
			<p>Environmental Grass Roots Coordinator</p>
			<p>Police Officer</p>
			<p>Immigration Inspector</p>
			<p>Firefighter</p>
			<p>Recreation Worker</p>
			<p>Bus Driver</p>
			<p>Subway Operator</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technical Service</h5>
			<p><em>Industrial Labor Relations Specialist</p>
			<p>Engineer
				<ul>
					<li>Civil</li>
					<li>Aircraft</li>
					<li>Structural</li>
				</ul></p>
			<p>Hazardous Waste Management</p>
			<p>Plant Safety Specialist</p>
			<p>Equipment Specialist</p>
			<p>Tour Boat Captain</p>
			<p>Broadcast Technician</p>
			<p>Waste Management Technician</em></p>
		</div>
		<div class="col">
			<h5>Nature/Wildlife Service</h5>
			<p><em>Environmentalist</p>
			<p>Environmental Protection Specialist</p>
			<p>Historic Preservationist</p>
			<p>Park Ranger</p>
			<p>Recreation Administrator</p>
			<p>Nature Interpreter</p>
			<p>Zoo Keeper</p>
			<p>Recreations Site Developer</p>
			<p>Ranger Aide</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>
			<p><em>Inspector
				<ul>
					<li>Building</li>
					<li>Public Works</li>
				</ul></p>
			<p>Land Surveyor</p>
			<p>Environmental Grass Roots Coordinator</p>
			<p>Police Officer</p>
			<p>Immigration Inspector</p>
			<p>Firefighter</p>
			<p>Recreation Worker</p>
			<p>Bus Driver</p>
			<p>Subway Operator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Technical Service</h5>
			<p><em>Industrial Labor Relations Specialist</p>
			<p>Engineer
				<ul>
					<li>Civil</li>
					<li>Aircraft</li>
					<li>Structural</li>
				</ul></p>
			<p>Hazardous Waste Management</p>
			<p>Plant Safety Specialist</p>
			<p>Equipment Specialist</p>
			<p>Tour Boat Captain</p>
			<p>Broadcast Technician</p>
			<p>Waste Management Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Nature/Wildlife Service</h5>
			<p><em>Environmentalist</p>
			<p>Environmental Protection Specialist</p>
			<p>Historic Preservationist</p>
			<p>Park Ranger</p>
			<p>Recreation Administrator</p>
			<p>Nature Interpreter</p>
			<p>Zoo Keeper</p>
			<p>Recreations Site Developer</p>
			<p>Ranger Aide</em></p>
		</div>
	</div>
	</div>

