	<div class="row">
		<div class="col-md-12">
			<p class="lead">Technology paired with Science/Mathematics (FH)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>FH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Sciences</h5>
			<p><em>Physicist
				<ul>
					<li>Biophysicist</li>
					<li>Health</li>
					<li>Medical</li>
					<li>Solid-state</li>
					<li>Nuclear</li>
				</ul></p>
			<p>Physical Therapist</p>
			<p>Prosthetic Engineer</p>
			<p>Prosthetic Designer</p>
			<p>Physical Therapist Assistant</p>
			<p>Technician
				<ul>
					<li>Nuclear Medicine</li>
					<li>Surgical</li>
					<li>Radiological</li>
					<li>Clinical Laboratory</li>
					<li>Cardiovascular</li>
				</ul></em>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental Sciences</h5>
			<p><em>City Planner</p>
			<p>Marine Biologist</p>
			<p>Geographer</p>
			<p>Industrial Hygienist</p>
			<p>Engineer
				<ul>
					<li>Electrical</li>
					<li>Industrial</li>
					<li>Mechanical</li>
				</ul></p>
			<p>Environmentalist</p>
			<p>Meteorologist</p>
			<p>Climatologist</p>
			<p>Air Pollution Control Technician</p>
			<p>Land Surveyor</p>
			<p>Energy Management Technician</em></p>
		</div>
		<div class="col">
			<h5>Engineering Sciences</h5>
			<p><em>Engineer
				<ul>
					<li>Aeronautical</li>
					<li>Electrical</li>
					<li>Mechanical</li>
				</ul></p>
			<p>Cartographer</p>
			<p>Aircraft Pilot</p>
			<p>Aviation Safety Inspector</p>
			<p>Inventor</p>
			<p>Researcher</p>
			<p>Boat Captain</p>
			<p>Technician
				<ul>
					<li>Mechanical Engineering</li>
					<li>Electrical Repair</li>
					<li>Cable Equipment</li>
				</ul></p>
			<p>Craftsman
				<ul>
					<li>Stone Cutter</li>
					<li>Brick Mason</li>
				</ul></em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Sciences</h5>
			<p><em>Physicist
				<ul>
					<li>Biophysicist</li>
					<li>Health</li>
					<li>Medical</li>
					<li>Solid-state</li>
					<li>Nuclear</li>
				</ul></p>
			<p>Physical Therapist</p>
			<p>Prosthetic Engineer</p>
			<p>Prosthetic Designer</p>
			<p>Physical Therapist Assistant</p>
			<p>Technician
				<ul>
					<li>Nuclear Medicine</li>
					<li>Surgical</li>
					<li>Radiological</li>
					<li>Clinical Laboratory</li>
					<li>Cardiovascular</li>
				</ul></em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental Sciences</h5>
			<p><em>City Planner</p>
			<p>Marine Biologist</p>
			<p>Geographer</p>
			<p>Industrial Hygienist</p>
			<p>Engineer
				<ul>
					<li>Electrical</li>
					<li>Industrial</li>
					<li>Mechanical</li>
				</ul></p>
			<p>Environmentalist</p>
			<p>Meteorologist</p>
			<p>Climatologist</p>
			<p>Air Pollution Control Technician</p>
			<p>Land Surveyor</p>
			<p>Energy Management Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Engineering Sciences</h5>
			<p><em>Engineer
				<ul>
					<li>Aeronautical</li>
					<li>Electrical</li>
					<li>Mechanical</li>
				</ul></p>
			<p>Cartographer</p>
			<p>Aircraft Pilot</p>
			<p>Aviation Safety Inspector</p>
			<p>Inventor</p>
			<p>Researcher</p>
			<p>Boat Captain</p>
			<p>Technician
				<ul>
					<li>Mechanical Engineering</li>
					<li>Electrical Repair</li>
					<li>Cable Equipment</li>
				</ul></p>
			<p>Craftsman
				<ul>
					<li>Stone Cutter</li>
					<li>Brick Mason</li>
				</ul></em></p>
		</div>
	</div>
	</div>

