	<div class="row">
		<div class="col-md-12">
			<p class="lead">Technology paired with Science/Mathematics (FH)</p>
			
			<div class="inter">
			
			<p>If your scored high in the "F" and "H" categories, you are
			important to the future. People like you have discovered many things
			about the world. Your curiosity about how machines and tools work
			will be important to the work force. You are an excellent thinker.
			You are also probably a hands-on kind of person. You are creative
			and have technical skills as well. There will be many opportunities
			for you.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree.  It is helpful to have a master's degree or Ph.D. to work in
			some of these occupations.</p>
			<p><strong>Courses you might want to take in high school and beyond
			(in addition to English & Math):</strong><br />
			In high school you should take courses that emphasize math and
			science. Any courses that provide opportunities to use your mental
			strength will be of great interest to you.  They will also help
			prepare you for career opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting<br />
						Biology<br />
						Calculus
					</td>
					<td>
						Economics<br />
						Marketing<br />
						Public Relations
					</td>
					<td>
						Physics<br />
						Computer Sciences<br />
						Chemistry
					</td>
					<td>
						Advertising<br />
						Computer Programming<br />
						Sociology
					</td>
					<td>
						Business Math<br />
						Communications<br />
						Psychology
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations
			you may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. You will enjoy any club or activity where you can use
			your thinking skills and technology.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Chess Club<br />
						Tutoring
					</td>
					<td>
						Newspaper/Yearbook<br />
						Computer Club<br />
					</td>
					<td>
						Environmental Activities<br />
						Audio/Visual Services
					</td>
					<td>
						Math/Science Clubs<br />
						Library Assistant
					</td>
					<td>
						Hospital Volunteer<br />
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting Firms<br />
						Architect Firms<br />
						Computer Services<br />
					</td>
					<td>
						Electronic Stores<br />
						Medical Offices<br />
						Printing Companies<br />
					</td>
					<td>
						Appliance Repair<br />
						Engineering Firms<br />
						Newspaper Offices<br />
					</td>
					<td>
						Computer Services<br />
						Data Entry<br />
						Libraries<br />
					</td>
					<td>
						Photographic Labs<br />
						Radio/TV Stations<br />
						Veterinary Offices
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>FH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Sciences</h5>
			<p><em>Physicist
				<ul>
					<li>Biophysicist</li>
					<li>Health</li>
					<li>Medical</li>
					<li>Solid-state</li>
					<li>Nuclear</li>
				</ul></p>
			<p>Physical Therapist</p>
			<p>Prosthetic Engineer</p>
			<p>Prosthetic Designer</p>
			<p>Physical Therapist Assistant</p>
			<p>Technician
				<ul>
					<li>Nuclear Medicine</li>
					<li>Surgical</li>
					<li>Radiological</li>
					<li>Clinical Laboratory</li>
					<li>Cardiovascular</li>
				</ul></em>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental Sciences</h5>
			<p><em>City Planner</p>
			<p>Marine Biologist</p>
			<p>Geographer</p>
			<p>Industrial Hygienist</p>
			<p>Engineer
				<ul>
					<li>Electrical</li>
					<li>Industrial</li>
					<li>Mechanical</li>
				</ul></p>
			<p>Environmentalist</p>
			<p>Meteorologist</p>
			<p>Climatologist</p>
			<p>Air Pollution Control Technician</p>
			<p>Land Surveyor</p>
			<p>Energy Management Technician</em></p>
		</div>
		<div class="col">
			<h5>Engineering Sciences</h5>
			<p><em>Engineer
				<ul>
					<li>Aeronautical</li>
					<li>Electrical</li>
					<li>Mechanical</li>
				</ul></p>
			<p>Cartographer</p>
			<p>Aircraft Pilot</p>
			<p>Aviation Safety Inspector</p>
			<p>Inventor</p>
			<p>Researcher</p>
			<p>Boat Captain</p>
			<p>Technician
				<ul>
					<li>Mechanical Engineering</li>
					<li>Electrical Repair</li>
					<li>Cable Equipment</li>
				</ul></p>
			<p>Craftsman
				<ul>
					<li>Stone Cutter</li>
					<li>Brick Mason</li>
				</ul></em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Sciences</h5>
			<p><em>Physicist
				<ul>
					<li>Biophysicist</li>
					<li>Health</li>
					<li>Medical</li>
					<li>Solid-state</li>
					<li>Nuclear</li>
				</ul></p>
			<p>Physical Therapist</p>
			<p>Prosthetic Engineer</p>
			<p>Prosthetic Designer</p>
			<p>Physical Therapist Assistant</p>
			<p>Technician
				<ul>
					<li>Nuclear Medicine</li>
					<li>Surgical</li>
					<li>Radiological</li>
					<li>Clinical Laboratory</li>
					<li>Cardiovascular</li>
				</ul></em>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental Sciences</h5>
			<p><em>City Planner</p>
			<p>Marine Biologist</p>
			<p>Geographer</p>
			<p>Industrial Hygienist</p>
			<p>Engineer
				<ul>
					<li>Electrical</li>
					<li>Industrial</li>
					<li>Mechanical</li>
				</ul></p>
			<p>Environmentalist</p>
			<p>Meteorologist</p>
			<p>Climatologist</p>
			<p>Air Pollution Control Technician</p>
			<p>Land Surveyor</p>
			<p>Energy Management Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Engineering Sciences</h5>
			<p><em>Engineer
				<ul>
					<li>Aeronautical</li>
					<li>Electrical</li>
					<li>Mechanical</li>
				</ul></p>
			<p>Cartographer</p>
			<p>Aircraft Pilot</p>
			<p>Aviation Safety Inspector</p>
			<p>Inventor</p>
			<p>Researcher</p>
			<p>Boat Captain</p>
			<p>Technician
				<ul>
					<li>Mechanical Engineering</li>
					<li>Electrical Repair</li>
					<li>Cable Equipment</li>
				</ul></p>
			<p>Craftsman
				<ul>
					<li>Stone Cutter</li>
					<li>Brick Mason</li>
				</ul></em></p>
		</div>
	</div>
	</div>

