	<div class="row">
		<div class="col-md-12">
			<p class="lead">Technology paired with Social/Helping (FI)</p>
			
			<div class="inter">
			
			<p>Your high scores in "F" and "I" show that you have
			characteristics that are useful to people.  You will be highly
			valued in the work force.  In addition, you  have the potential to
			make a real difference in the world.  You have an interest in
			technology and in other people.  Your strengths will be
			useful in many different occupations.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree.  It is helpful to have a master's degree or Ph.D. if you
			hope to work in some of these occupations.</p>
			<p><strong>Courses you might want to take in high school and beyond
			(in addition to English & Math):</strong><br />
			In high school you should take courses that will help you
			understand people. Any courses in social studies and technology will
			be of interest to you.  They will also help prepare you for possible
			career opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Health/Nutrition<br />
						Psychology<br />
						Sociology
					</td>
					<td>
						Home Economics<br />
						Public Relations<br />
						Communications
					</td>
					<td>
						Graphic Arts<br />
						Business Education<br />
						Religion
					</td>
					<td>
						Business Law<br />
						Education Technology<br />
						Environmental Science
					</td>
					<td>
						History<br />
						Life Science<br />
						Education
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations you
			may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. You will enjoy any club or activity where you can share
			your love for nature and use your people skills.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Church Activities<br />
						Camp Counselor<br />
						Hospital Volunteer
					</td>
					<td>
						Peer Counselor<br />
						Tutoring<br />
						Chess Club<br />
					</td>
					<td>
						Childcare/Eldercare<br />
						Yearbook/Newspaper<br />
						Audio/Visual Services
					</td>
					<td>
						Computer Club<br />
						Music Lessons<br />
						Martial Arts
					</td>
					<td>
						Teaching Assistant<br />
						Library Assistant<br />
						Math/Science Clubs
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Company Offices<br />
						Equipment Repair<br />
						Road Building
					</td>
					<td>
						Life Guarding<br />
						Restaurant<br />
						Repair Services
					</td>
					<td>
						Construction Companies<br />
						Graphic Design Firms<br />
						Recreation Department<br />
					</td>
					<td>
						Church Programs<br />
						Day Care Centers<br />
						Libraries
					</td>
					<td>
						Photography Studios<br />
						Printing Companies<br />
						Newspaper Offices
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>FI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education & Instruction</h5>
			<p><em>College Professor</p>
			<p>Teacher
				<ul>
					<li>Continuing Education</li>
					<li>Environmental Science</li>
					<li>Computer Science</li>
					<li>Shop</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Sports & Fitness Trainer</p>
			<p>Coach</p>
			<p>Instructor
				<ul>
					<li>Aerobics Exercise</li>
					<li>Martial Arts</li>
					<li>Police Academy</li>
					<li>Survival Training</li>
					<li>Trade School</li>
				</ul></em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Public Health Administrator</p>
			<p>Environmental Lawyer</p>
			<p>Social Worker</p>
			<p>Nurse</p>
			<p>Recreational Therapist</p>
			<p>Dental Hygienist</p>
			<p>Paramedic</p>
			<p>Police Officer</p>
			<p>Military Police</p>
			<p>Flight Attendant</p>
			<p>Barber</em></p>
		</div>
		<div class="col">
			<h5>Technology Helping</h5>
			<p><em>Veterinarian</p>
			<p>Medical Equipment Designer</p>
			<p>Park Ranger</p>
			<p>Firefighter</p>
			<p>Military Teletype Operator</p>
			<p>Computer Trainer</p>
			<p>Craftsperson
				<ul>
					<li>Plumber</li>
					<li>Carpenter</li>
					<li>Heating</li>
					<li>Air Conditioning</li>
				</ul></p>
			<p>Appliance Repair Technician</p>
			<p>Electronics Technician</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education & Instruction</h5>
			<p><em>College Professor</p>
			<p>Teacher
				<ul>
					<li>Continuing Education</li>
					<li>Environmental Science</li>
					<li>Computer Science</li>
					<li>Shop</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Sports & Fitness Trainer</p>
			<p>Coach</p>
			<p>Instructor
				<ul>
					<li>Aerobics Exercise</li>
					<li>Martial Arts</li>
					<li>Police Academy</li>
					<li>Survival Training</li>
					<li>Trade School</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Public Health Administrator</p>
			<p>Environmental Lawyer</p>
			<p>Social Worker</p>
			<p>Nurse</p>
			<p>Recreational Therapist</p>
			<p>Dental Hygienist</p>
			<p>Paramedic</p>
			<p>Police Officer</p>
			<p>Military Police</p>
			<p>Flight Attendant</p>
			<p>Barber</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Technology Helping</h5>
			<p><em>Veterinarian</p>
			<p>Medical Equipment Designer</p>
			<p>Park Ranger</p>
			<p>Firefighter</p>
			<p>Military Teletype Operator</p>
			<p>Computer Trainer</p>
			<p>Craftsperson
				<ul>
					<li>Plumber</li>
					<li>Carpenter</li>
					<li>Heating</li>
					<li>Air Conditioning</li>
				</ul></p>
			<p>Appliance Repair Technician</p>
			<p>Electronics Technician</em></p>
		</div>
	</div>
	</div>

