	<div class="row">
		<div class="col-md-12">
			<p class="lead">Public Service paired with Social/Helping (GI)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>GI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>Teacher</p>
			<p>Public Health Education</p>
			<p>Police Academy</p>
			<p>Instructor</p>
			<p>Guidance Counselor</p>
			<p>Training Specialist</p>
			<p>Library Technician</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Service</h5>
			<p><em>Social Worker
				<ul>
					<li>Child Welfare</li>
					<li>Family Services</li>
					<li>Drug & Alcohol</li>
					<li>Mental Health</li>
					<li>Occupational</li>
				</ul></p>
			<p>Human Services Worker
				<ul>
					<li>Social Service Assistant</li>
					<li>Case Management</li>
					<li>Community Outreach Worker</li>
					<li>Child Care Worker</li>
				</ul></p>
			<p>Health Care Worker</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Public Service</h5>
			<em>Lawyer
				<ul>
					<li>Public Defender</li>
					<li>Judge</li>
				</ul></p>
			<p>Paralegal</p>
			<p>Police Officer</p>
			<p>Firefighter</p>
			<p>Political Campaign Worker</p>
			<p>Flight Attendant</em></p>
		</div>
		<div class="col">
			<h5>Health Care</h5>
			<p><em>Public Health Investigator</p>
			<p>Rehabilitation Counselor</p>
			<p>Paramedic</p>
			<p>Community Health Nurse</p>
			<p>Medical Assistant</p>
			<p>Patient Representative</p>
			<p>Nursing Aide</p>
			<p>Home Health Aide</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>Teacher</p>
			<p>Public Health Education</p>
			<p>Police Academy</p>
			<p>Instructor</p>
			<p>Guidance Counselor</p>
			<p>Training Specialist</p>
			<p>Library Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Service</h5>
			<p><em>Social Worker
				<ul>
					<li>Child Welfare</li>
					<li>Family Services</li>
					<li>Drug & Alcohol</li>
					<li>Mental Health</li>
					<li>Occupational</li>
				</ul></p>
			<p>Human Services Worker
				<ul>
					<li>Social Service Assistant</li>
					<li>Case Management</li>
					<li>Community Outreach Worker</li>
					<li>Child Care Worker</li>
				</ul></p>
			<p>Health Care Worker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Public Service</h5>
			<em>Lawyer
				<ul>
					<li>Public Defender</li>
					<li>Judge</li>
				</ul></p>
			<p>Paralegal</p>
			<p>Police Officer</p>
			<p>Firefighter</p>
			<p>Political Campaign Worker</p>
			<p>Flight Attendant</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Health Care</h5>
			<p><em>Public Health Investigator</p>
			<p>Rehabilitation Counselor</p>
			<p>Paramedic</p>
			<p>Community Health Nurse</p>
			<p>Medical Assistant</p>
			<p>Patient Representative</p>
			<p>Nursing Aide</p>
			<p>Home Health Aide</em></p>
		</div>
	</div>
	</div>

