	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Public Service (CG)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Public Service</h5>
			<p><em>College President/Administrator</p>
			<p>Publisher</p>
			<p>City Manager</p>
			<p>Social Work Agency Director</p>
			<p>Hospital Marketing Director</p>
			<p>Police Chief</p>
			<p>Elected Public Official</p>
			<p>Director of Security</p>
			<p>Continuing Education Coordinator</p>
			<p>Detective</p>
			<p>Bank Teller</p>
			<p>Security Guard</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Management</h5>
			<p><em>Airport Manager</p>
			<p>Hospital Administrator</p>
			<p>Public School Administrator</p>
			<p>Hotel Manager</p>
			<p>Shopping Mall Manager</p>
			<p>Trade Show Coordinator</p>
			<p>Military Officer</p>
			<p>Press Secretary</p>
			<p>Plant (Manufacturing) Manager</p>
			<p>Postal Supervisor</p>
			<p>Retail Sales Manager</p>
			<p>Assistant Restaurant Manager</em></p>
		</div>
		<div class="col">
			<h5>Business & Industry</h5>
			<p><em>Corporate Lawyer</p>
			<p>Patent Lawyer</p>
			<p>Industrial Psychologist</p>
			<p>City Housing Director</p>
			<p>Personnel Director</p>
			<p>Marketing Director</p>
			<p>Mortgage Loan Officer</p>
			<p>Financial Manager</p>
			<p>Corporate Trainer</p>
			<p>Land Developer</p>
			<p>Personnel Consultant</p>
			<p>Auctioneer</p>
			<p>Retail Salesperson</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Public Service</h5>
			<p><em>College President/Administrator</p>
			<p>Publisher</p>
			<p>City Manager</p>
			<p>Social Work Agency Director</p>
			<p>Hospital Marketing Director</p>
			<p>Police Chief</p>
			<p>Elected Public Official</p>
			<p>Director of Security</p>
			<p>Continuing Education Coordinator</p>
			<p>Detective</p>
			<p>Bank Teller</p>
			<p>Security Guard</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Management</h5>
			<p><em>Airport Manager</p>
			<p>Hospital Administrator</p>
			<p>Public School Administrator</p>
			<p>Hotel Manager</p>
			<p>Shopping Mall Manager</p>
			<p>Trade Show Coordinator</p>
			<p>Military Officer</p>
			<p>Press Secretary</p>
			<p>Plant (Manufacturing) Manager</p>
			<p>Postal Supervisor</p>
			<p>Retail Sales Manager</p>
			<p>Assistant Restaurant Manager</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Business & Industry</h5>
			<p><em>Corporate Lawyer</p>
			<p>Patent Lawyer</p>
			<p>Industrial Psychologist</p>
			<p>City Housing Director</p>
			<p>Personnel Director</p>
			<p>Marketing Director</p>
			<p>Mortgage Loan Officer</p>
			<p>Financial Manager</p>
			<p>Corporate Trainer</p>
			<p>Land Developer</p>
			<p>Personnel Consultant</p>
			<p>Auctioneer</p>
			<p>Retail Salesperson</em></p>
		</div>
	</div>
	</div>


