	<div class="row">
		<div class="col-md-12">
			<p class="lead">Clerical/Administrative paired with Public Service (DG)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>DG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Services</h5>
			<p><em>Social Worker
				<ul>
					<li>Occupational</li>
					<li>School</li>
					<li>Human Services</li>
				</ul></p>
			<p>Vocational Rehabilitation Counselor</p>
			<p>Postal Inspector</p>
			<p>Teacher Aide</p>
			<p>Real Estate Broker</p>
			<p>Flight Attendant</p>
			<p>Church Attendant</p>
			<p>Postal Worker</p>
			<p>Hospital Outpatient
			<p>Coordinator</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Administrative Services</h5>
			<p><em>Government Office Administrator</p>
			<p>LiteraryAgent</p>
			<p>Human Resources Job Analyst</p>
			<p>Insurance Claims Examiner</p>
			<p>Medical Record Administrator</p>
			<p>Executive Assistant</p>
			<p>Transportation Ticket Agent</p>
			<p>Fire Department Secretary</p>
			<p>Receptionist</p>
			<p>Clerk
				<ul>
					<li>File</li>
					<li>Mail</li>
					<li>Insurance Processing</li>
				</ul></em></p>
		</div>
		<div class="col">
			<h5>Legal/Military Services</h5>
			<p><em>Law Librarian</p>
			<p>Paralegal</p>
			<p>Court Reporter</p>
			<p>Legal Secretary</p>
			<p>Flight Operations Specialist</p>
			<p>Legal Technician</p>
			<p>Personnel Specialist</p>
			<p>Deputy Sheriff</p>
			<p>Real Estate Closing Secretary</p>
			<p>Law Enforcement Dispatcher</p>
			<p>911 Operator</p>
			<p>Administrative Support Specialist</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Services</h5>
			<p><em>Social Worker
				<ul>
					<li>Occupational</li>
					<li>School</li>
					<li>Human Services</li>
				</ul></p>
			<p>Vocational Rehabilitation Counselor</p>
			<p>Postal Inspector</p>
			<p>Teacher Aide</p>
			<p>Real Estate Broker</p>
			<p>Flight Attendant</p>
			<p>Church Attendant</p>
			<p>Postal Worker</p>
			<p>Hospital Outpatient
			<p>Coordinator</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Administrative Services</h5>
			<p><em>Government Office Administrator</p>
			<p>LiteraryAgent</p>
			<p>Human Resources Job Analyst</p>
			<p>Insurance Claims Examiner</p>
			<p>Medical Record Administrator</p>
			<p>Executive Assistant</p>
			<p>Transportation Ticket Agent</p>
			<p>Fire Department Secretary</p>
			<p>Receptionist</p>
			<p>Clerk
				<ul>
					<li>File</li>
					<li>Mail</li>
					<li>Insurance Processing</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Legal/Military Services</h5>
			<p><em>Law Librarian</p>
			<p>Paralegal</p>
			<p>Court Reporter</p>
			<p>Legal Secretary</p>
			<p>Flight Operations Specialist</p>
			<p>Legal Technician</p>
			<p>Personnel Specialist</p>
			<p>Deputy Sheriff</p>
			<p>Real Estate Closing Secretary</p>
			<p>Law Enforcement Dispatcher</p>
			<p>911 Operator</p>
			<p>Administrative Support Specialist</em></p>
		</div>
	</div>
	</div>

