	<div class="row">
		<div class="col-md-12">
			<p class="lead">Protective/Military Service paired with Public Service (EG)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>EG Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community</h5>
			<p><em>Social Worker
				<ul>
					<li>Drug & Alcohol</li>
					<li>Family</li>
					<li>Public Health</li>
				</ul></p>
			<p>Public Health Consultant</p>
			<p>Public Affairs Officer</p>
			<p>Postal Service Administrator</p>
			<p>Firefighter</p>
			<p>Postal Service Personnel</p>
			<p>Religious Program Specialist</p>
			<p>Public Health Field Worker</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Legal</h5>
			<p><em>Lawyer</p>
			<p>Labor Relations Specialist</p>
			<p>Police Chief</p>
			<p>County Sheriff</p>
			<p>FBI Agent</p>
			<p>Investigator Detective</p>
			<p>Police Officer</p>
			<p>Legal Technician</p>
			<p>Customs Agent</p>
			<p>Security Guard</em></p>
		</div>
		<div class="col">
			<h5>Military</h5>
			<p><em>Chaplain</p>
			<p>Engineer</p>
			<p>Military Officer</p>
			<p>Transportation Manager</p>
			<p>Military Police</p>
			<p>Recruiting Specialist</p>
			<p>Interpreter & Translator</p>
			<p>Military Trainer</p>
			<p>Emergency Management Specialist</p>
			<p>Medic</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community</h5>
			<p><em>Social Worker
				<ul>
					<li>Drug & Alcohol</li>
					<li>Family</li>
					<li>Public Health</li>
				</ul></p>
			<p>Public Health Consultant</p>
			<p>Public Affairs Officer</p>
			<p>Postal Service Administrator</p>
			<p>Firefighter</p>
			<p>Postal Service Personnel</p>
			<p>Religious Program Specialist</p>
			<p>Public Health Field Worker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Legal</h5>
			<p><em>Lawyer</p>
			<p>Labor Relations Specialist</p>
			<p>Police Chief</p>
			<p>County Sheriff</p>
			<p>FBI Agent</p>
			<p>Investigator Detective</p>
			<p>Police Officer</p>
			<p>Legal Technician</p>
			<p>Customs Agent</p>
			<p>Security Guard</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Military</h5>
			<p><em>Chaplain</p>
			<p>Engineer</p>
			<p>Military Officer</p>
			<p>Transportation Manager</p>
			<p>Military Police</p>
			<p>Recruiting Specialist</p>
			<p>Interpreter & Translator</p>
			<p>Military Trainer</p>
			<p>Emergency Management Specialist</p>
			<p>Medic</em></p>
		</div>
	</div>
	</div>

