	<div class="row">
		<div class="col-md-12">
			<p class="lead">Public Service paired with Science/Mathematics (GH)</p>
			
			<div class="inter">
			
			<p>If your scored high in the "G" and "H" categories, you understand
			that there are always ways to improve a situation. You have the
			ability to investigate, explore, and apply information. This will
			make you a valuable employee.  People like you have discovered
			important information that has made the world a better place.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree.  It is helpful to have a master's degree or Ph.D. if you
			hope to work in some of these occupations.</p>
			<p><strong>Courses you may want to take in high school and beyond
			(in addition to English & Math):</strong><br />
			In high school you should take courses that emphasize math and
			science. Any courses that will help you understand people and
			society will be of interest to you.  They will also prepare you for
			possible career opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Communications<br />
						Government/Civics<br />
						Physical Education<br />
						Public Relations
					</td>
					<td>
						Sociology<br />
						Psychology<br />
						Trigonometry<br />
						Accounting
					</td>
					<td>
						Health/Nutrition<br />
						Physics/Chemistry<br />
						Computer Info. Systems<br />
						Technology Education
					</td>
					<td>
						Calculus<br />
						Biology<br />
						Geometry<br />
						Economics
					</td>
					<td>
						Business Education<br />
						World Languages<br />
						Criminal Justice<br />
						Political Science
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations you
			may find interesting:</strong><br />
			If you have time for afterschool activities or part-time jobs, make
			them count. You will enjoy any club or activity where you can share
			your love for helping your community and use your thinking skills.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Math/Science Clubs<br />
						Computer Club
					</td>
					<td>
						Chess Club<br />
						Tutoring
					</td>
					<td>
						Environmental Activities<br />
						Hospital Volunteer
					</td>
					<td>
						Peer Counselor<br />
						Church Activities
					</td>
					<td>
						Safety Patrol
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Accounting Firms<br />
						Appliance Repair<br />
						Medical Offices<br />
						Political Offices
					</td>
					<td>
						Data Entry<br />
						Construction<br />
						News Media<br />
						Legal Offices
					</td>
					<td>
						Athletic Programs<br />
						Sports Companies<br />
						Electronic Stores<br />
						Veterinary Offices
					</td>
					<td>
						Printing Companies<br />
						Computer Services<br />
						Libraries<br />
						Computer Sales
					</td>
					<td>
						Archeological Projects<br />
						Courthouse Activities<br />
						Landscaping Services
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>GH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
	
		<div class="col" style="margin-bottom: 20px;">
			<h5>Public Service</h5>
			<p><em>Military Medical Officer</p>
			<p>Political Scientist</p>
			<p>Fire Chief</p>
			<p>Health Inspector</p>
			<p>Lobbyist</p>
			<p>Peace Corp Worker</p>
			<p>Foreign Service Officer</p>
			<p>Police Officer</p>
			<p>Investigator</p>
			<p>Security Guard</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social/Mental</h5>
			<p><em>Public Health
				<ul>
					<li>Physician</li>
					<li>Dental</li>
				</ul></p>
			<p>Epidemiologist</p>
			<p>Psychologist</p>
			<p>Health Services Administrator</p>
			<p>Social Worker</p>
			<p>Public Health Field Worker</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental</h5>
			<p><em>Environmental Lawyer</p>
			<p>Chemical Engineer</p>
			<p>Ecologist</p>
			<p>Environmental Health Inspector</p>
			<p>Meteorologist</p>
			<p>Meteorologist Technician</p>
			<p>Energy Management Technician</p>
			<p>Waste Management Technician</em></p>
		</div>
		<div class="col">
			<h5>Science/Medical</h5>
			<p><em>Biological Scientist</p>
			<p>Optometrist</p>
			<p>Public Health Nurse</p>
			<p>Chiropractor</p>
			<p>Dietitian</p>
			<p>Dental Hygienist</p>
			<p>Paramedic</p>
			<p>Nurse's Aide</p>
			<p>Ophthalmic Lab Technician</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Public Service</h5>
			<p><em>Military Medical Officer</p>
			<p>Political Scientist</p>
			<p>Fire Chief</p>
			<p>Health Inspector</p>
			<p>Lobbyist</p>
			<p>Peace Corp Worker</p>
			<p>Foreign Service Officer</p>
			<p>Police Officer</p>
			<p>Investigator</p>
			<p>Security Guard</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social/Mental</h5>
			<p><em>Public Health
				<ul>
					<li>Physician</li>
					<li>Dental</li>
				</ul></p>
			<p>Epidemiologist</p>
			<p>Psychologist</p>
			<p>Health Services Administrator</p>
			<p>Social Worker</p>
			<p>Public Health Field Worker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Environmental</h5>
			<p><em>Environmental Lawyer</p>
			<p>Chemical Engineer</p>
			<p>Ecologist</p>
			<p>Environmental Health Inspector</p>
			<p>Meteorologist</p>
			<p>Meteorologist Technician</p>
			<p>Energy Management Technician</p>
			<p>Waste Management Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Science/Medical</h5>
			<p><em>Biological Scientist</p>
			<p>Optometrist</p>
			<p>Public Health Nurse</p>
			<p>Chiropractor</p>
			<p>Dietitian</p>
			<p>Dental Hygienist</p>
			<p>Paramedic</p>
			<p>Nurse's Aide</p>
			<p>Ophthalmic Lab Technician</em></p>
		</div>
	</div>
	</div>

