	<div class="row">
		<div class="col-md-12">
			<p class="lead">Public Service paired with Social/Helping (GI)</p>
			
			<div class="inter">
			
			<p>Your high scores in "G" and "I" show that you are headed for a
			rewarding career.  You will be highly valued in the work force.  You
			also have the potential to make a real difference in the world.  You
			are a responsible, independent worker and you know how to make
			things happen.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree.  It is helpful to have a master's degree or Ph.D. if you
			hope to work in some of these occupations.</p>
			<p><strong>Courses you might want to take in high
			school.</strong><br />
			In high school you should take courses that will help you
			understand people. Any courses in social studies and political
			science will be of interest to you.  They will also help prepare you
			for possible career opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Government/Civics<br />
						World Languages<br />
						Home Economics<br />
						Nutrition/Health
					</td>
					<td>
						Religion<br />
						Psychology<br />
						Sociology<br />
						Education
					</td>
					<td>
						Computer Technology<br />
						Physical Education<br />
						Public Relations<br />
						Marketing/Advertising
					</td>
					<td>
						Communications<br />
						Business Education<br />
						Political Science<br />
						Criminal Justice
					</td>
					<td>
						Graphic Arts<br />
						Law<br />
						Life Science
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations you
			may find interesting:</strong><br />
			If you have time for after-school activities or part-time jobs, make
			them count.  You will enjoy any club or activity where you can share
			your love for helping others and use your people skills.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Youth Organizations<br />
						Peer Counselor
					</td>
					<td>
						Safety Patrol<br />
						Tutoring
					</td>
					<td>
						Chess Club<br />
						Camp Counselor
					</td>
					<td>
						Childcare/Eldercare<br />
						Church Activities
					</td>
					<td>
						Hospital Volunteer<br />
						Teaching Assistant
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may wish to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Company Offices<br />
						Church Programs<br />
						Libraries
					</td>
					<td>
						Hospice Activities<br />
						Day Care Centers<br />
						Photographic Studios
					</td>
					<td>
						Life Guarding<br />
						Printing Companies<br />
						Special Olympics
					</td>
					<td>
						Construction Companies<br />
						Hospital Volunteer<br />
						Recreation Departments
					</td>
					<td>
						Camp Programs<br />
						Preschool Programs
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>GI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>Teacher</p>
			<p>Public Health Education</p>
			<p>Police Academy</p>
			<p>Instructor</p>
			<p>school Counselor</p>
			<p>Training Specialist</p>
			<p>Library Technician</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Service</h5>
			<p><em>Social Worker
				<ul>
					<li>Child Welfare</li>
					<li>Family Services</li>
					<li>Drug & Alcohol</li>
					<li>Mental Health</li>
					<li>Occupational</li>
				</ul></p>
			<p>Human Services Worker
				<ul>
					<li>Social Service Assistant</li>
					<li>Case Management</li>
					<li>Community Outreach Worker</li>
					<li>Child Care Worker</li>
				</ul></p>
			<p>Health Care Worker</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Public Service</h5>
			<em>Lawyer
				<ul>
					<li>Public Defender</li>
					<li>Judge</li>
				</ul></p>
			<p>Paralegal</p>
			<p>Police Officer</p>
			<p>Firefighter</p>
			<p>Political Campaign Worker</p>
			<p>Flight Attendant</em></p>
		</div>
		<div class="col">
			<h5>Health Care</h5>
			<p><em>Public Health Investigator</p>
			<p>Rehabilitation Counselor</p>
			<p>Paramedic</p>
			<p>Community Health Nurse</p>
			<p>Medical Assistant</p>
			<p>Patient Representative</p>
			<p>Nursing Aide</p>
			<p>Home Health Aide</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>Teacher</p>
			<p>Public Health Education</p>
			<p>Police Academy</p>
			<p>Instructor</p>
			<p>school Counselor</p>
			<p>Training Specialist</p>
			<p>Library Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Service</h5>
			<p><em>Social Worker
				<ul>
					<li>Child Welfare</li>
					<li>Family Services</li>
					<li>Drug & Alcohol</li>
					<li>Mental Health</li>
					<li>Occupational</li>
				</ul></p>
			<p>Human Services Worker
				<ul>
					<li>Social Service Assistant</li>
					<li>Case Management</li>
					<li>Community Outreach Worker</li>
					<li>Child Care Worker</li>
				</ul></p>
			<p>Health Care Worker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Public Service</h5>
			<em>Lawyer
				<ul>
					<li>Public Defender</li>
					<li>Judge</li>
				</ul></p>
			<p>Paralegal</p>
			<p>Police Officer</p>
			<p>Firefighter</p>
			<p>Political Campaign Worker</p>
			<p>Flight Attendant</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Health Care</h5>
			<p><em>Public Health Investigator</p>
			<p>Rehabilitation Counselor</p>
			<p>Paramedic</p>
			<p>Community Health Nurse</p>
			<p>Medical Assistant</p>
			<p>Patient Representative</p>
			<p>Nursing Aide</p>
			<p>Home Health Aide</em></p>
		</div>
	</div>
	</div>

