	<div class="row">
		<div class="col-md-12">
			<p class="lead">Clerical/Administrative paired with Science/Mathematics (DH)</span></p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>DH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Administrative Services</h5>
			<p><em>Medical Record Administrator</p>
			<p>Medical
				<ul>
					<li>Transcriptionist</li>
					<li>Assistant</li>
					<li>Secretary</li>
					<li>Receptionist</li>
				</ul></p>
			<p>Pharmacist's Assistant</p>
			<p>Research Assistant</p>
			<p>Laboratory/Clinic Manager</p>
			<p>Medical Office Manager</p>
			<p>Human Service Worker</p>
			<p>Medical Coding Specialist</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Services</h5>
			<p><em>Geriatric Assessment Coordinator</p>
			<p>Physician's Assistant</p>
			<p>Nurse Supervisor</p>
			<p>Research Analyst</p>
			<p>Medical Librarian</p>
			<p>Dental Hygienist</p>
			<p>Science Technician</p>
			<p>Laboratory Technologist</p>
			<p>Licensed Practical Nurse</p>
			<p>Outpatient Coordinator</p>
			<p>Home Health Aide</em></p>
		</div>
		<div class="col">
			<h5>Math Services</h5>
			<p><em>Accountant</p>
			<p>Bio-statistician</p>
			<p>Public Health Program Specialist</p>
			<p>Researcher</p>
			<p>Bookkeeper</p>
			<p>Purchasing Agent</p>
			<p>Computer
				<ul>
					<li>Systems Analyst</li>
					<li>Programmer</li>
			 </ul></p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Statement</li>
					<li>Brokerage</li>
				</ul></p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>



	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Administrative Services</h5>
			<p><em>Medical Record Administrator</p>
			<p>Medical
				<ul>
					<li>Transcriptionist</li>
					<li>Assistant</li>
					<li>Secretary</li>
					<li>Receptionist</li>
				</ul></p>
			<p>Pharmacist's Assistant</p>
			<p>Research Assistant</p>
			<p>Laboratory/Clinic Manager</p>
			<p>Medical Office Manager</p>
			<p>Human Service Worker</p>
			<p>Medical Coding Specialist</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medical Services</h5>
			<p><em>Geriatric Assessment Coordinator</p>
			<p>Physician's Assistant</p>
			<p>Nurse Supervisor</p>
			<p>Research Analyst</p>
			<p>Medical Librarian</p>
			<p>Dental Hygienist</p>
			<p>Science Technician</p>
			<p>Laboratory Technologist</p>
			<p>Licensed Practical Nurse</p>
			<p>Outpatient Coordinator</p>
			<p>Home Health Aide</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Math Services</h5>
			<p><em>Accountant</p>
			<p>Bio-statistician</p>
			<p>Public Health Program Specialist</p>
			<p>Researcher</p>
			<p>Bookkeeper</p>
			<p>Purchasing Agent</p>
			<p>Computer
				<ul>
					<li>Systems Analyst</li>
					<li>Programmer</li>
			 </ul></p>
			<p>Clerk
				<ul>
					<li>Accounting</li>
					<li>Statement</li>
					<li>Brokerage</li>
				</ul></p>
			<p>Bank Teller</em></p>
		</div>
	</div>
	</div>

