	<div class="row">
		<div class="col-md-12">
			<p class="lead">Public Service paired with Science/Mathematics (GH)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>GH Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Public Service</h5>
			<p><em>Military Medical Officer</p>
			<p>Political Scientist</p>
			<p>Fire Chief</p>
			<p>Health Inspector</p>
			<p>Lobbyist</p>
			<p>Peace Corp Worker</p>
			<p>Foreign Service Officer</p>
			<p>Police Officer</p>
			<p>Investigator</p>
			<p>Security Guard</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social/Mental</h5>
			<p><em>Public Health
				<ul>
					<li>Physician</li>
					<li>Dental</li>
				</ul></p>
			<p>Epidemiologist</p>
			<p>Psychologist</p>
			<p>Health Services Administrator</p>
			<p>Social Worker</p>
			<p>Public Health Field Worker</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environmental</h5>
			<p><em>Environmental Lawyer</p>
			<p>Chemical Engineer</p>
			<p>Ecologist</p>
			<p>Environmental Health Inspector</p>
			<p>Meteorologist</p>
			<p>Meteorologist Technician</p>
			<p>Energy Management Technician</p>
			<p>Waste Management Technician</em></p>
		</div>
		<div class="col">
			<h5>Science/Medical</h5>
			<p><em>Biological Scientist</p>
			<p>Optometrist</p>
			<p>Public Health Nurse</p>
			<p>Chiropractor</p>
			<p>Dietitian</p>
			<p>Dental Hygienist</p>
			<p>Paramedic</p>
			<p>Nurse's Aide</p>
			<p>Ophthalmic Lab Technician</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Public Service</h5>
			<p><em>Military Medical Officer</p>
			<p>Political Scientist</p>
			<p>Fire Chief</p>
			<p>Health Inspector</p>
			<p>Lobbyist</p>
			<p>Peace Corp Worker</p>
			<p>Foreign Service Officer</p>
			<p>Police Officer</p>
			<p>Investigator</p>
			<p>Security Guard</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social/Mental</h5>
			<p><em>Public Health
				<ul>
					<li>Physician</li>
					<li>Dental</li>
				</ul></p>
			<p>Epidemiologist</p>
			<p>Psychologist</p>
			<p>Health Services Administrator</p>
			<p>Social Worker</p>
			<p>Public Health Field Worker</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Environmental</h5>
			<p><em>Environmental Lawyer</p>
			<p>Chemical Engineer</p>
			<p>Ecologist</p>
			<p>Environmental Health Inspector</p>
			<p>Meteorologist</p>
			<p>Meteorologist Technician</p>
			<p>Energy Management Technician</p>
			<p>Waste Management Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Science/Medical</h5>
			<p><em>Biological Scientist</p>
			<p>Optometrist</p>
			<p>Public Health Nurse</p>
			<p>Chiropractor</p>
			<p>Dietitian</p>
			<p>Dental Hygienist</p>
			<p>Paramedic</p>
			<p>Nurse's Aide</p>
			<p>Ophthalmic Lab Technician</em></p>
		</div>
	</div>
	</div>

