	<div class="row">
		<div class="col-md-12">
			<p class="lead">Science/Mathematics paired with Social/Helping (HI)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>HI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-none d-lg-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>College Professor</p>
			<p>Education Administrator</p>
			<p>Teacher
				<ul>
					<li>Adult Education</li>
					<li>Science</li>
					<li>Math</li>
					<li>Biology</li>
					<li>Computer</li>
					<li>Physics</li>
					<li>English</li>
				</ul></p>
			<p>Clergy
				<ul>
					<li>Priest</li>
					<li>Rabbi</li>
					<li>Minister</li>
				</ul></p>
			<p>Librarian</p>
			<p>Teacher's Aide</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Service</h5>
			<p><em>Psychologist</p>
			<p>Health Services Administrator</p>
			<p>Economist</p>
			<p>Social Worker
				<ul>
					<li>Mental Health</li>
					<li>School</li>
					<li>Geriatric</li>
				</ul></p>
			<p>Psychotherapist</p>
			<p>Counselor
				<ul>
					<li>School</li>
					<li>Career</li>
					<li>Drugs & Alcohol</li>
				</ul></p>
			<p>Researcher</p>
			<p>Psychiatric Technician</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medicine</h5>
			<p><em>Physician</p>
			<p>Dentist</p>
			<p>Veterinarian</p>
			<p>Pharmacist</p>
			<p>Physical Therapist</p>
			<p>Nurse</p>
			<p>Dietitian</p>
			<p>Dental Hygienist</p>
			<p>Lab/Medical Technologist</p>
			<p>Dental/Veterinary Assistant</p>
			<p>Dental/Veterinary Technician</p>
			<p>Home Health Aide</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environment</h5>
			<p><em>Earth Scientist
				<ul>
					<li>Geologist</li>
					<li>Oceanographer</li>
					<li>Ecologist</li>
					<li>Meteorologist</li>
				</ul></p>
			<p>Zoologist</p>
			<p>Engineer
				<ul>
					<li>Environmental</li>
					<li>Chemical</li>
				</ul></p>
			<p>Astronomer</p>
			<p>Forester</p>
			<p>Parks & Recreation Manager</p>
			<p>Zoo Keeper</p>
			<p>Meteorological Technician</p>
			<p>Research Assistant</em></p>
		</div>
		<div class="col">
			<h5>Mathematics</h5>
			<p><em>Social Scientist
				<ul>
					<li>Anthropologist</li>
					<li>Sociologist</li>
				</ul></p>
			<p>Accountant</p>
			<p>Statistician</p>
			<p>Computer Systems Analyst</p>
			<p>Computer Trainer</p>
			<p>Puzzle Inventor</p>
			<p>Research Assistant</p>
			<p>Clerk
				<ul>
					<li>Statistics</li>
					<li>Accounting</li>
				</ul></em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-block d-lg-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>College Professor</p>
			<p>Education Administrator</p>
			<p>Teacher
				<ul>
					<li>Adult Education</li>
					<li>Science</li>
					<li>Math</li>
					<li>Biology</li>
					<li>Computer</li>
					<li>Physics</li>
					<li>English</li>
				</ul></p>
			<p>Clergy
				<ul>
					<li>Priest</li>
					<li>Rabbi</li>
					<li>Minister</li>
				</ul></p>
			<p>Librarian</p>
			<p>Teacher's Aide</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Service</h5>
			<p><em>Psychologist</p>
			<p>Health Services Administrator</p>
			<p>Economist</p>
			<p>Social Worker
				<ul>
					<li>Mental Health</li>
					<li>School</li>
					<li>Geriatric</li>
				</ul></p>
			<p>Psychotherapist</p>
			<p>Counselor
				<ul>
					<li>School</li>
					<li>Career</li>
					<li>Drugs & Alcohol</li>
				</ul></p>
			<p>Researcher</p>
			<p>Psychiatric Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Medicine</h5>
			<p><em>Physician</p>
			<p>Dentist</p>
			<p>Veterinarian</p>
			<p>Pharmacist</p>
			<p>Physical Therapist</p>
			<p>Nurse</p>
			<p>Dietitian</p>
			<p>Dental Hygienist</p>
			<p>Lab/Medical Technologist</p>
			<p>Dental/Veterinary Assistant</p>
			<p>Dental/Veterinary Technician</p>
			<p>Home Health Aide</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Environment</h5>
			<p><em>Earth Scientist
				<ul>
					<li>Geologist</li>
					<li>Oceanographer</li>
					<li>Ecologist</li>
					<li>Meteorologist</li>
				</ul></p>
			<p>Zoologist</p>
			<p>Engineer
				<ul>
					<li>Environmental</li>
					<li>Chemical</li>
				</ul></p>
			<p>Astronomer</p>
			<p>Forester</p>
			<p>Parks & Recreation Manager</p>
			<p>Zoo Keeper</p>
			<p>Meteorological Technician</p>
			<p>Research Assistant</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Mathematics</h5>
			<p><em>Social Scientist
				<ul>
					<li>Anthropologist</li>
					<li>Sociologist</li>
				</ul></p>
			<p>Accountant</p>
			<p>Statistician</p>
			<p>Computer Systems Analyst</p>
			<p>Computer Trainer</p>
			<p>Puzzle Inventor</p>
			<p>Research Assistant</p>
			<p>Clerk
				<ul>
					<li>Statistics</li>
					<li>Accounting</li>
				</ul></em></p>
		</div>
	</div>
	</div>

