	<div class="row">
		<div class="col-md-12">
			<p class="lead">Science/Mathematics paired with Social/Helping (HI)</p>
			
			<div class="inter">
			
			<p>Your high scores in "H" and "I" show that you are headed for a
			rewarding career. You will be highly valued in the work force. You
			have the potential to make a real difference in the world. You will
			help others by gathering information and doing research. You are a
			naturally caring person and you have a scientific mind which will
			serve you well.</p>
			<p>Most occupations in this pairing require at least a bachelor's
			degree. It is helpful to have a master's degree or Ph.D. if you hope
			to work in some of these occupations.</p>
			<p><strong>Courses you may want to take in high school and beyond
			(in addition to English & Math):</strong><br />
			In high school you should take courses that help you to understand
			people. Any courses in math and science will be of great interest to
			you. They will also help prepare you for possible career
			opportunities in this area.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Business Law<br />
						Drafting<br />
						Environmental Sciences<br />
						Health<br />
						Math
					</td>

					<td>
						Political Science<br />
						Religion<br />
						Computer Sciences<br />
						Education
					</td>

					<td>
						Government<br />
						Home Economics<br />
						Nutrition<br />
						Psychology
					</td>

					<td>
						Sociology<br />
						Computer Technology<br />
						English<br />
						Graphic Arts
					</td>

					<td>
						Law<br />
						Physical Education<br />
						Public Relations<br />
						Speech & Communications
					</td>
				</tr>
			</table>

			<p><strong>Extracurricular/volunteer activities or organizations
			that you may find interesting:</strong><br />
			If you have time for after-school activities or part-time jobs, make
			them count. You will enjoy any club or activity where you can share
			your love for math and science and use your people skills.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Band<br />
						Church Activities<br />
						Debate Teams<br />
						Hospice Volunteer<br />
						Junior Achievement<br />
						Pen Pals
					</td>

					<td>
						School Newspaper<br />
						School TV<br />
						Tutoring<br />
						Cheerleading<br />
						Class Officer
					</td>

					<td>
						Eldercare<br />
						Hospital Volunteer<br />
						Parks & Recreation<br />
						Photography Clubs<br />
						School Radio
					</td>

					<td>
						Scouts<br />
						Youth Groups<br />
						Childcare<br />
						Community Volunteer<br />
						Exchange Programs
					</td>

					<td>
						Language Clubs<br />
						Peer Counselor<br />
						School Monitor<br />
						School Sales<br />
						Social Clubs
					</td>
				</tr>
			</table>

			<p><strong>Workplaces that you may want to consider for a part-time
			job:</strong><br />
			These places may offer valuable opportunities to help you decide
			what you want to do when you are an adult.</p>

			<table cellpadding="10" cellspacing="10" class="side">
				<tr valign="top">
					<td>
						Advertising Agencies<br />
						Construction Companies<br />
						Graphic Design Firms<br />
						Libraries
					</td>

					<td>
						Photography Studios<br />
						Recreation Departments<br />
						Camp Programs<br />
						Church Programs
					</td>

					<td>
						Hospice Activities<br />
						Life Guarding<br />
						Preschool Programs<br />
						Restaurants
					</td>

					<td>
						Company Offices<br />
						Day Care Centers<br />
						Hospital Volunteer
					</td>

					<td>
						Newspaper Offices<br />
						Printing Companies<br />
						Special Olympics
					</td>
				</tr>
			</table>
			
		</div>
			
			<p><strong>Here are some career possibilities for you to explore:</strong></p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>HI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td style="text-align: center;">
							<br /><br />
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br /><br />
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>College Professor</p>
			<p>Education Administrator</p>
			<p>Teacher
				<ul>
					<li>Adult Education</li>
					<li>Science</li>
					<li>Math</li>
					<li>Biology</li>
					<li>Computer</li>
					<li>Physics</li>
					<li>English</li>
				</ul></p>
			<p>Clergy
				<ul>
					<li>Priest</li>
					<li>Rabbi</li>
					<li>Minister</li>
				</ul></p>
			<p>Librarian</p>
			<p>Teacher's Aide</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Service</h5>
			<p><em>Psychologist</p>
			<p>Health Services Administrator</p>
			<p>Economist</p>
			<p>Social Worker
				<ul>
					<li>Mental Health</li>
					<li>School</li>
					<li>Geriatric</li>
				</ul></p>
			<p>Psychotherapist</p>
			<p>Counselor
				<ul>
					<li>School</li>
					<li>Career</li>
					<li>Drugs & Alcohol</li>
				</ul></p>
			<p>Researcher</p>
			<p>Psychiatric Technician</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Medicine</h5>
			<p><em>Physician</p>
			<p>Dentist</p>
			<p>Veterinarian</p>
			<p>Pharmacist</p>
			<p>Physical Therapist</p>
			<p>Nurse</p>
			<p>Dietitian</p>
			<p>Dental Hygienist</p>
			<p>Lab/Medical Technologist</p>
			<p>Dental/Veterinary Assistant</p>
			<p>Dental/Veterinary Technician</p>
			<p>Home Health Aide</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Environment</h5>
			<p><em>Earth Scientist
				<ul>
					<li>Geologist</li>
					<li>Oceanographer</li>
					<li>Ecologist</li>
					<li>Meteorologist</li>
				</ul></p>
			<p>Zoologist</p>
			<p>Engineer
				<ul>
					<li>Environmental</li>
					<li>Chemical</li>
				</ul></p>
			<p>Astronomer</p>
			<p>Forester</p>
			<p>Parks & Recreation Manager</p>
			<p>Zoo Keeper</p>
			<p>Meteorological Technician</p>
			<p>Research Assistant</em></p>
		</div>
		<div class="col">
			<h5>Mathematics</h5>
			<p><em>Social Scientist
				<ul>
					<li>Anthropologist</li>
					<li>Sociologist</li>
				</ul></p>
			<p>Accountant</p>
			<p>Statistician</p>
			<p>Computer Systems Analyst</p>
			<p>Computer Trainer</p>
			<p>Puzzle Inventor</p>
			<p>Research Assistant</p>
			<p>Clerk
				<ul>
					<li>Statistics</li>
					<li>Accounting</li>
				</ul></em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-block d-lg-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education</h5>
			<p><em>College Professor</p>
			<p>Education Administrator</p>
			<p>Teacher
				<ul>
					<li>Adult Education</li>
					<li>Science</li>
					<li>Math</li>
					<li>Biology</li>
					<li>Computer</li>
					<li>Physics</li>
					<li>English</li>
				</ul></p>
			<p>Clergy
				<ul>
					<li>Priest</li>
					<li>Rabbi</li>
					<li>Minister</li>
				</ul></p>
			<p>Librarian</p>
			<p>Teacher's Aide</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Service</h5>
			<p><em>Psychologist</p>
			<p>Health Services Administrator</p>
			<p>Economist</p>
			<p>Social Worker
				<ul>
					<li>Mental Health</li>
					<li>School</li>
					<li>Geriatric</li>
				</ul></p>
			<p>Psychotherapist</p>
			<p>Counselor
				<ul>
					<li>School</li>
					<li>Career</li>
					<li>Drugs & Alcohol</li>
				</ul></p>
			<p>Researcher</p>
			<p>Psychiatric Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Medicine</h5>
			<p><em>Physician</p>
			<p>Dentist</p>
			<p>Veterinarian</p>
			<p>Pharmacist</p>
			<p>Physical Therapist</p>
			<p>Nurse</p>
			<p>Dietitian</p>
			<p>Dental Hygienist</p>
			<p>Lab/Medical Technologist</p>
			<p>Dental/Veterinary Assistant</p>
			<p>Dental/Veterinary Technician</p>
			<p>Home Health Aide</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Environment</h5>
			<p><em>Earth Scientist
				<ul>
					<li>Geologist</li>
					<li>Oceanographer</li>
					<li>Ecologist</li>
					<li>Meteorologist</li>
				</ul></p>
			<p>Zoologist</p>
			<p>Engineer
				<ul>
					<li>Environmental</li>
					<li>Chemical</li>
				</ul></p>
			<p>Astronomer</p>
			<p>Forester</p>
			<p>Parks & Recreation Manager</p>
			<p>Zoo Keeper</p>
			<p>Meteorological Technician</p>
			<p>Research Assistant</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Mathematics</h5>
			<p><em>Social Scientist
				<ul>
					<li>Anthropologist</li>
					<li>Sociologist</li>
				</ul></p>
			<p>Accountant</p>
			<p>Statistician</p>
			<p>Computer Systems Analyst</p>
			<p>Computer Trainer</p>
			<p>Puzzle Inventor</p>
			<p>Research Assistant</p>
			<p>Clerk
				<ul>
					<li>Statistics</li>
					<li>Accounting</li>
				</ul></em></p>
		</div>
	</div>
	</div>

