	<div class="row">
		<div class="col-md-12">
			<p class="lead">Outdoor paired with Social/Helping (AI)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>AI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>
			<p><em>Teacher
				<ul>
					<li>Agriculture</li>
					<li>Biology</li>
					<li>Industrial Arts</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Horticultural Therapist</p>
			<p>Recreation Therapist</p>
			<p>Peace Corp Worker</p>
			<p>Postal Worker</p>
			<p>Real Estate Appraiser</p>
			<p>Bus Driver</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature</h5>
			<p><em>Veterinarian</p>
			<p>Pet Psychologist</p>
			<p>Ecologist</p>
			<p>Zoo Manager</p>
			<p>Forester</p>
			<p>Wildlife Rehabilitator</p>
			<p>Recreational Therapist</p>
			<p>Park Ranger</p>
			<p>Nature Guide</p>
			<p>Forestry</p>
			<p>Animal Lab Technician</em></p>
		</div>
		<div class="col">
			<h5>Environment</h5>
			<p><em>Civil Engineer</p>
			<p>City Planner</p>
			<p>Surveyor</p>
			<p>Hazardous Waste Management Professional</p>
			<p>Environmental Heath Specialist</p>
			<p>Firefighter</p>
			<p>Emergency Management Specialist</p>
			<p>Recreation Specialist</p>
			<p>Sanitation Engineer</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Community Service</h5>
			<p><em>Teacher
				<ul>
					<li>Agriculture</li>
					<li>Biology</li>
					<li>Industrial Arts</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Horticultural Therapist</p>
			<p>Recreation Therapist</p>
			<p>Peace Corp Worker</p>
			<p>Postal Worker</p>
			<p>Real Estate Appraiser</p>
			<p>Bus Driver</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Nature</h5>
			<p><em>Veterinarian</p>
			<p>Pet Psychologist</p>
			<p>Ecologist</p>
			<p>Zoo Manager</p>
			<p>Forester</p>
			<p>Wildlife Rehabilitator</p>
			<p>Recreational Therapist</p>
			<p>Park Ranger</p>
			<p>Nature Guide</p>
			<p>Forestry</p>
			<p>Animal Lab Technician</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Environment</h5>
			<p><em>Civil Engineer</p>
			<p>City Planner</p>
			<p>Surveyor</p>
			<p>Hazardous Waste Management Professional</p>
			<p>Environmental Heath Specialist</p>
			<p>Firefighter</p>
			<p>Emergency Management Specialist</p>
			<p>Recreation Specialist</p>
			<p>Sanitation Engineer</em></p>
		</div>
	</div>
	</div>

