	<div class="row">
		<div class="col-md-12">
			<p class="lead">Business/Management paired with Social Helping (CI)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>CI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Religious Activities Director</p>
			<p>Health Services Administrator</p>
			<p>Clergy</p>
			<p>Occupational Social Worker</p>
			<p>Public Health Social Worker</p>
			<p>Adult Education Teacher (Business Courses)</p>
			<p>Human Services Worker</p>
			<p>Homeless Shelter Director</p>
			<p>Parole Officer</p>
			<p>Home Health Aide</em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<p><h5>Business Helping</h5>
			<p><em>Personnel Consultant</p>
			<p>Corporate Trainer</p>
			<p>Employment Interviewer</p>
			<p>Property Manager</p>
			<p>Real Estate Agent</p>
			<p>Insurance Agent</p>
			<p>Sales Occupation</p>
			<p>Service Occupation</p>
			<p>Bank Teller</p>
			<p>Receptionist</p>
			<p>Computer Salesperson</p>
			<p>Retail Salesperson</em></p>
		</div>
		<div class="col">
			<p><h5>Business Management</h5>
			<p><em>Hospital Administrator</p>
			<p>Financial Planner</p>
			<p>Geriatric Care Manager</p>
			<p>Human Resources Manager</p>
			<p>Funeral Director</p>
			<p>Hotel Manager</p>
			<p>Benefits Administrator</p>
			<p>Retirement Manager</p>
			<p>Restaurant Manager</p>
			<p>Travel Agency Manager</em></p>
		</div>
	</div>
	</div>


	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Religious Activities Director</p>
			<p>Health Services Administrator</p>
			<p>Clergy</p>
			<p>Occupational Social Worker</p>
			<p>Public Health Social Worker</p>
			<p>Adult Education Teacher (Business Courses)</p>
			<p>Human Services Worker</p>
			<p>Homeless Shelter Director</p>
			<p>Parole Officer</p>
			<p>Home Health Aide</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<p><h5>Business Helping</h5>
			<p><em>Personnel Consultant</p>
			<p>Corporate Trainer</p>
			<p>Employment Interviewer</p>
			<p>Property Manager</p>
			<p>Real Estate Agent</p>
			<p>Insurance Agent</p>
			<p>Sales Occupation</p>
			<p>Service Occupation</p>
			<p>Bank Teller</p>
			<p>Receptionist</p>
			<p>Computer Salesperson</p>
			<p>Retail Salesperson</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<p><h5>Business Management</h5>
			<p><em>Hospital Administrator</p>
			<p>Financial Planner</p>
			<p>Geriatric Care Manager</p>
			<p>Human Resources Manager</p>
			<p>Funeral Director</p>
			<p>Hotel Manager</p>
			<p>Benefits Administrator</p>
			<p>Retirement Manager</p>
			<p>Restaurant Manager</p>
			<p>Travel Agency Manager</em></p>
		</div>
	</div>
	</div>

