	<div class="row">
		<div class="col-md-12">
			<p class="lead">Technology paired with Social/Helping (FI)</p>
			<p>Here are some career possibilities for you to explore:</p>
			<div style="width: 100%; background-color: #1abd9c; color: white;">
				<p style="text-align: center; padding: 3px 0;"><strong>FI Career Possibilities</strong></p>
			</div>
			<div style="width: 100%; background-color: #defff5; color: black; margin-top: -11px;">
				<p style="text-align: left;"><img src="/img/icons/caret-left-fill.svg" alt="" width="22" height="22" title="">  People Oriented</p><p style="float: right;margin-top: -35px;">Technical Oriented  <img src="/img/icons/caret-right-fill.svg" alt="" width="22" height="22" title=""></p>
			</div>
		</div>
	</div>
	
	<div class="d-none d-sm-none d-md-block">
	<div class="row">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							</p><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							</p><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education & Instruction</h5>
			<p><em>College Professor</p>
			<p>Teacher
				<ul>
					<li>Continuing Education</li>
					<li>Environmental Science</li>
					<li>Computer Science</li>
					<li>Shop</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Sports & Fitness Trainer</p>
			<p>Coach</p>
			<p>Instructor
				<ul>
					<li>Aerobics Exercise</li>
					<li>Martial Arts</li>
					<li>Police Academy</li>
					<li>Survival Training</li>
					<li>Trade School</li>
				</ul></em></p>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Public Health Administrator</p>
			<p>Environmental Lawyer</p>
			<p>Social Worker</p>
			<p>Nurse</p>
			<p>Recreational Therapist</p>
			<p>Dental Hygienist</p>
			<p>Paramedic</p>
			<p>Police Officer</p>
			<p>Military Police</p>
			<p>Flight Attendant</p>
			<p>Barber</em></p>
		</div>
		<div class="col">
			<h5>Technology Helping</h5>
			<p><em>Veterinarian</p>
			<p>Medical Equipment Designer</p>
			<p>Park Ranger</p>
			<p>Firefighter</p>
			<p>Military Teletype Operator</p>
			<p>Computer Trainer</p>
			<p>Craftsperson
				<ul>
					<li>Plumber</li>
					<li>Carpenter</li>
					<li>Heating</li>
					<li>Air Conditioning</li>
				</ul></p>
			<p>Appliance Repair Technician</p>
			<p>Electronics Technician</em></p>
		</div>
	</div>
	</div>
	
	
	<div class="d-block d-md-none">
	<div class="row" style="margin-bottom: 24px;">
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Education & Instruction</h5>
			<p><em>College Professor</p>
			<p>Teacher
				<ul>
					<li>Continuing Education</li>
					<li>Environmental Science</li>
					<li>Computer Science</li>
					<li>Shop</li>
					<li>Physical Education</li>
				</ul></p>
			<p>Sports & Fitness Trainer</p>
			<p>Coach</p>
			<p>Instructor
				<ul>
					<li>Aerobics Exercise</li>
					<li>Martial Arts</li>
					<li>Police Academy</li>
					<li>Survival Training</li>
					<li>Trade School</li>
				</ul></em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;">
			<h5>Social Helping</h5>
			<p><em>Public Health Administrator</p>
			<p>Environmental Lawyer</p>
			<p>Social Worker</p>
			<p>Nurse</p>
			<p>Recreational Therapist</p>
			<p>Dental Hygienist</p>
			<p>Paramedic</p>
			<p>Police Officer</p>
			<p>Military Police</p>
			<p>Flight Attendant</p>
			<p>Barber</em></p>
		</div>
	</div>
	<div class="row" style="margin-bottom: 24px;">	
		<div class="col-auto">
			<div style="background-color: #defff5; text-align: center; height: 100%; padding: 3px 3px 3px 6px;">
				<table>
					<tr>
						<td>
							<img src="/img/icons/caret-up-fill.svg" alt="" width="22" height="22" title="">
							<br /><br /><br />
							Education
							<br />
							or
							<br />
							Training
							<br />
							Required
							<br /><br /><br />
							<img src="/img/icons/caret-down-fill.svg" alt="" width="22" height="22" title="">
						</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="col">
			<h5>Technology Helping</h5>
			<p><em>Veterinarian</p>
			<p>Medical Equipment Designer</p>
			<p>Park Ranger</p>
			<p>Firefighter</p>
			<p>Military Teletype Operator</p>
			<p>Computer Trainer</p>
			<p>Craftsperson
				<ul>
					<li>Plumber</li>
					<li>Carpenter</li>
					<li>Heating</li>
					<li>Air Conditioning</li>
				</ul></p>
			<p>Appliance Repair Technician</p>
			<p>Electronics Technician</em></p>
		</div>
	</div>
	</div>

