<span class="header1">Outdoor paired with Clerical/Administrative 
(AD)</span>

<p>If you had a high score in the "A" and "D" categories, you are 
probably a hard worker who likes to do things in a structured way. 
You also prefer to know what is expected of you and have a set 
procedure for tasks.  You do well with order, paperwork, directions 
and time-oriented work details. You learn best by experience and 
like to know the facts. You want to know exactly what will happen. 
You may want to look for careers that will allow you to combine your 
interest in the outdoors with your ability to get things done.</p>
<p>Most occupations in "AD" combination require at least a 
bachelor's degree. Many require training through a vocational or 
technical program.</p>
<p><strong>Courses you may want to consider taking in high school 
and beyond (in addition to English & Math):</strong><br />
You should consider taking life science courses that will continue 
to develop your interest in and understanding of the outdoors. Some 
business courses are very practical and may help you develop your 
organizational skills.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
				Computer Science<br />
				Agriculture<br />
				Business Technology
			</td>
			<td>
				Economics<br />
				Bookkeeping<br />
				Botany<br />
			</td>
			<td>
				Industrial Technology<br />
				Environmental Science<br />
				Office Administration
			</td>
			<td>
				Physical Education<br />
				Business Education<br />
				Health/Nutrition
			</td>
			<td>
				Biology<br />
				Graphic Arts<br />
				Geography
			</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations you 
may find interesting:</strong><br />
Experience is an important thing! If you are looking for an 
interesting activity, you should probably think about organizations 
that focus on nature and the environment. Don't forget to find a 
place where you can show how dependable you are.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Adopt-a-Mile<br />
			Habitat for Humanity<br />
			Library Assistant<br />
			Future Farmers of America
		</td>
		<td>
			Athletics<br />
			Office Assistant<br />
			Newspaper/Yearbook<br />
			Future Business Leaders 
		</td>
		<td>
			Scouts<br />
			Teaching Assistant<br />
			Class Officer
		</td>
		<td>
			Parks/Recreation<br />
			Audio/Visual Services<br />
			Community Volunteer
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time 
job:</strong><br />
These workplaces may offer opportunities to help you decide and 
prepare you for what you want to do as an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting Firms<br />
			Repair Services
		</td>
		<td>
			Landscaping Firms<br />
			Farms
		</td>
		<td>
			Park Services<br />
			Lumberyards
		</td>
		<td>
			Clerical & Filing Offices<br />
			Lawn Care Services
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to 
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">AD Career 
Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" 
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" 
align="left"><strong>More People Oriented</strong></td>
					<td width="33%" 
align="center"><strong><----------></strong></td>
					<td width="33%" 
align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" 
cellspacing="0" height="400">
				<tr align="center" 
height="33%"><td><strong>More<br /></strong></td></tr>
				<tr align="center" 
height="33%"><td><strong>Education<br/>or<br />Training<br />Required
</strong></td></tr>
				<tr align="center" 
height="33%"><td><strong><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" 
cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span 
class="header2">Outdoor Technical Environments</span><br /><br />
						<em>Air Traffic 
Controller<br /><br />
						Army 
Officer<br /><br />
						Community 
Relations 
Manager<br /><br />
						Military 
Enlisted 
Personnel<br /><br />
						Aerial 
Photographer<br /><br />
						Safety 
Engineer<br /><br />
						Travel 
Agent<br /><br />
						Air Quality 
Control 
Technician<br /><br />
						Telephone Cable 
Installer<br /><br />
						Highway 
Maintenance</em>
					</td>
					<td width="33%">
						<span 
class="header2">Nature/Office Environments</span><br /><br />
					
	<em>Administrative 
Assistant<br /><br />
						Land & Water 
Conservationist<br /><br />
						Title 
Searcher<br /><br />
						Tour 
Guide<br /><br />
					
	Receptionist<br /><br />
						Ticket Agent-
Wildlife Tours Agent</em>
					</td>
					<td width="33%">
						<span 
class="header2">Nature/Animal Environments</span><br /><br />
						<em>Livestock 
Auction Coordinator<br /><br />
						Veterinary 
Clinic/Hospital
							<ul>
							
	<li>Technician</li>
							
	<li>Office Manager</li>
							
	<li>Administrative Assistant</li>
							
	<li>Records/Billing Clerk</li>
							</ul>
						Secretary- Zoo, 
Farm, Ranch<br /><br />
						Pet Store 
Clerk/Caretaker<br /><br />
						Pet Sitter</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">OUTDOOR TECHNICAL FIELD</span>
<p>Environmental pollution makes us more likely to get sick.  We 
need more facts and new technologies to prevent damage to the 
environment and our health.  Each occupation in this field helps 
preserve our future.</p>

<hr size="1" />

	<span class="header2">Community Relations 
Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/AD/1369.jpg" 
width="100" height="100" border="0" alt="Community Relations 
Manager" />
	<span class="header3">Job Description</span>
	<blockquote>If you understand technical information, and you 
communicate well, you might become a community relations manager.  
In this job you would work for a manufacturer.  You would tell 
people who live near the factory about any risks the factory might 
pose to them.  You would also report any emergencies in the plant 
that could cause harm to its neighbors.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree in communications, 
public relations, or journalism to become a community relations 
manager.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of community relations 
managers was 
$57,950 in May 2010.
</blockquote>

<hr  size="1" />

	<span class="header2">Safety Engineer</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A safety engineer works to make products safer 
and easier to use.  If you become a safety engineer, you would work 
for manufacturers, government agencies, or consulting firms. You 
might set safety standards for products. You might also inspect 
products to see that they meet these standards.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree to become 
a safety engineer. Many employers prefer a master's 
degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of safety engineers was 
$75,430 in May 
2010.</blockquote>

<hr size="1" />

	<span class="header2">Air Quality Control 
Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/AD/C1259_02.jpg" 
width="100" height="100" border="0" alt="Air Quality Control 
Technician" />
	<span class="header3">Job Description</span>
	<blockquote>If you are concerned about the air we breathe, 
you might become an air quality control technician.  In this job 
you would use special equipment to be sure that factories do not 
emit too much pollution into the air. You would also conduct 
laboratory experiments and pollution inspections.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need an associate degree or completion of a 
1-year certification program to be trained as a technician. Some 
companies will want you to have some college education.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of air quality control 
technicians was 
$42,530 in May 2010.
</blockquote>

<hr size="1" />

<span class="header1">NATURE/OFFICE FIELD</span>
<p>If you're interested in nature and the environment, and are good 
at problem solving, then you may want to consider the following 
occupations.</p>

<hr size="1" />

	<span class="header2">Land and Water 
Conservationist</span><br /><br />
	<img class="job_pic" src="/images/icons/AD/1231.jpg" 
width="100" height="100" border="0" alt="Land and Water 
Conservationist" />
	<span class="header3">Job Description</span>
	<blockquote>As a land and water conservationist, you would 
protect the natural habitats of wildlife. You would likely work for 
a federal or state government agency. The purpose of your office 
would be to make the rules and regulations that keep land and water 
from being polluted or contaminated.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Conservation scientists generally have at least 
a bachelor's degree in fields such as ecology, natural resource 
management, agriculture, biology, or environmental science. 
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of land and water 
conservationists was $57,420 in May 2010.
</blockquote>

<hr size="1" />

	<span class="header2">Conservation 
Technician</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a conservation technician, you 
would work with conservationists.  You will help them to protect 
natural wildlife habitats.  You might perform chemical tests on 
water and soil samples to check for pollutants.</blockquote>
        <span class="header3">Education</span>
        <blockquote>Most science technicians 
need an associate degree or a certificate in applied science or 
science-related technology.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of conservation 
technicians was $33,930 in May 2010. </blockquote>

<hr size="1" />

	<span class="header2">Tour Guide</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>If you like to teach others about our 
environment, you might become a wildlife guide. People often tour 
parks, wildlife refuges, and other natural areas.  As a wildlife 
guide, you would point out the interesting features of such areas to 
these people.  You would need excellent public speaking skills to do 
this.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The education you need varies with the employer 
and job. For some positions, you need a college education.  For 
other positions, you need only a high school diploma.  You must be 
interested in the park or museum where you want to work and have a 
pleasant disposition.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>According to the job-search websit indeed.com, 
the median annual wage of tour guides was $32,000 in May 2010. 
</blockquote>

<hr size="1" />

<span class="header1">NATURE/ANIMAL FIELD</span>
<p>If you enjoy working with or around animals, consider the 
following occupations.</p>

<hr size="1" />

	<span class="header2">Veterinary 
Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/AD/Ph43131.jpg" 
width="100" height="100" border="0" alt="Veterinary Technician" />
	<span class="header3">Job Description</span>
	<blockquote>A veterinary technician works with animals in 
animal hospitals and clinics.  In this job you would work closely 
with veterinarians.  You would help conduct laboratory tests.  You 
would also help dress wounds and prepare animals for 
surgery.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are primarily two levels of education and 
training for entry to this occupation: a 2-year program for 
veterinary technicians and a 4-year program for veterinary 
technologists. To become licensed or certified, you must pass a 
state test.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of veterinary technicians 
was $29,710 in May 2010.</blockquote>

<hr size="1" />

	<span class="header2">Animal Caretaker</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>An animal caretaker does for animals many of the 
things that a practical nurse does for people.  As an animal 
caretaker, you would work in an animal hospital or clinic.  You 
would look after sick animals and report any changes to the 
veterinarian. You would also feed, walk, and care for the animals. 
You might even bathe them.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most employers have on-the-job training programs 
for employees.  No college degree is required.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of animal caretakers was 
$19,780 in May 2010.</blockquote>

<hr size="1" />

	<span class="header2">Pet Sitter</span><br /><br />
	<img class="job_pic" src="/images/icons/AD/43130.jpg" 
width="100" height="100" border="0" alt="Pet Sitter" />
	<span class="header3">Job Description</span>
	<blockquote>A pet sitter cares for pets while their owners 
are away.  If you become a pet sitter, you will visit the animal's 
home or stay there until its owners return.  You will feed, walk, 
groom, and play with the pet(s).</blockquote>
	<span class="header3">Education</span>
	<blockquote>No college degree or high school diploma is 
required for this position.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A pet sitter may charge by the visit, half-hour, 
hour, day, or week. The hourly pay rate may be $10-20+. In 2012, Pet 
Sitters of America estimated a national pay amount of $15 per visit. 
</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit 
the <em>Occupational Outlook Handbook</em>:</strong> <a 
href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information 
Network</em> Web site:</strong> <a 
href="http://online.onetcenter.org/gen_search_page">online.onetcenter
.org/gen_search_page</a></p>


<blockquote>Salary data from Bureau of Labor Statistics, U.S. 
Department of Labor, <i>Occupational Outlook Handbook, 2012-13 
Edition, </i> visited 8/27/2012. </blockquote>





Additional average salary information acquired from job search 
website indeed.com in September 2012. The Indeed Salary Search data 
is based on an index of salary information extracted from over 50 
million job postings from thousands of unique sources over the 
previous year.











