<span class="header1">Arts/Communications paired with Technology (BF)</span>

<p>With a "BF" interest, you will be a valuable employee in a rapidly changing technology field. Almost all technology is in one way or another concerned with communication of change. You enjoy the mechanics of technology and you can use it to express your thoughts and feelings. The technical changes in the technology field offers a fast paced, visual, interchange of ideas and knowledge.</p>
<p>Many of the occupations in this pairing require some sort of specialized and/or technical training after high school. Many require college degrees or college level courses.</p>

<p><strong>Here are some career possibilities for you to explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">BF Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Communications</span><br /><br />
						<em>Medial Specialist<br /><br />
						Public Relations Specialist<br /><br />
						Editor<br /><br />
						Technical Writer<br /><br />
						Public Relations Assistant<br /><br />
						Sportscaster<br /><br />
						Desktop Publisher<br /><br />
						Tour Publicist<br /><br />
						Interpretive Naturalist<br /><br />
						Musician<br /><br />
						Actor<br /><br />
						Cruise Ship Entertainer</em>
					</td>
					<td width="33%">
						<span class="header2">Creative Technology</span><br /><br />
						<em>Industrial Designer<br /><br />
						Graphic Artist<br /><br />
						Photographer<br /><br />
						Camera Operator<br /><br />
						Lighting Designer<br /><br />
						Video Editor<br /><br />
						Drafting Technician<br /><br />
						Metal Artist/Fabricator<br /><br />
						Model Maker<br /><br />
						Airbrush Artist<br /><br />
						Tattoo Artist</em>
					</td>
					<td width="33%">
						<span class="header2">Technology</span><br /><br />
						<em>Exhibit Builder<br /><br />
						Theater Lighting Designer<br /><br />
						Sound Mixer<br /><br />
						Radio/TV Service Technician<br /><br />
						Book Binder<br /><br />
						Road Manager<br /><br />
						Roller Coaster Technician<br /><br />
						Tile Setter<br /><br />
						Painter<br /><br />
						Printer Developer<br /><br />
						Carpenter<br /><br />
						Landscape Gardener<br /><br />
						Entertainer Body Guard</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">COMMUNICATIONS</span>
<p>Your ability to communicate may be your ticket into the occupations in this field. Those who work in this field are excellent communicators. They can speak in front of a large group of people.</p>

<hr size="1" />

	<span class="header2">Public Relations Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/BF/1369.jpg" width="100" height="100" border="0" alt="Public Relations Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>Companies want customers and others to see them in a positive way.  So they hire people to see that this happens.  As a public relations specialist, you would let people know about the good things your company has done.  To do this, you would write press releases, brochures, and television and radio announcements.  It would be important that you were enthusiastic about the company. You would also need to be able to write and speak clearly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in communications, journalism, or public relations for this job.  Work experience is important too.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary ranges from $18,000 to $100,000.</blockquote>

<hr size="1" />

	<span class="header2">Technical Writer</span><br /><br />
	<img class="job_pic" src="/images/icons/BF/43289.jpg" width="100" height="100" border="0" alt="Technical Writer" />
	<span class="header3">Job Description</span>
	<blockquote>Have you ever read the owner's manual for your computer, sound system, or video game? The person who wrote the manuals was a technical writer. In this job, you would write manuals, catalogs, and instruction books.  You would make science or technical information and directions easy for others to understand.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A college degree is needed for this job.  Usually the technical writer relies on a degree in a specialized field.  For example, writers who work on computer manuals usually have a degree in computer science.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary of a writer varies.  The amount would depend on what area of technology you were writing about.  It would also depend on whom you were working for.</blockquote>

<hr size="1" />

	<span class="header2">Actor/Actress</span><br /><br />
	<img class="job_pic" src="/images/icons/BF/C575061.jpg" width="100" height="100" border="0" alt="Actor/Actress" />
	<span class="header3">Job Description</span>
	<blockquote>If you have a burning desire to be in the movies or in a play on Broadway, you might become a professional actor or actress.  In this job, you would play the role of a character in a play, television program, or movie.  To be successful, you must have a talent for acting.  You must also be able to perform in front of a large group of people. You would have to be able to remember your lines.  You would also have to get along with other actors, the directors, and others who make the production possible.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You can take college courses or get a degree in drama.  But the best teacher is experience. The courses give you a chance to learn new acting skills and improve your acting technique. But performing in front of an audience helps you to understand how to act.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>It is very difficult to say what an actor/actress makes.  Most actors do not have a steady job. In fact, they often take other jobs to make a living. It takes determination and hard work to be financially successful.  It can also take a long time.</blockquote>

<hr size="1" />

<span class="header1">CREATIVE TECHNOLOGY</span>
<p>The occupations in this field need people who can use their technical skills to create something new. Your creativity and interest in technology will help you to succeed in this field.</p>

<hr size="1" />

	<span class="header2">Photographer</span><br /><br />
	<img class="job_pic" src="/images/icons/BF/43060.jpg" width="100" height="100" border="0" alt="Photographer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like taking pictures and have a good "eye," you might become a professional photographer. A photographer combines communications skills and technology.  In this job, you would take pictures of people, things, or events. You must be creative.  Your goal is to show people something they might otherwise not have seen.  You must understand the technical aspects of the camera.  You must know how to process film too. Many photographers work for themselves.  So, it is helpful to understand how a small business works.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A Bachelor's Degree in photography or the visual arts can develop your basic skills.  But, you also need to be creative to succeed in this field.  Spend as much time as possible looking at great pictures and taking your own. Getting involved in photography clubs and working in photo shops and labs will help you learn more about using your camera to capture successful photographs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A photographer's salary can be anywhere from $15,000 to  $48,000 + per year.</blockquote>

<hr size="1" />

	<span class="header2">Video Editor</span><br /><br />
	<img class="job_pic" src="/images/icons/BF/C506027.jpg" width="100" height="100" border="0" alt="Video Editor" />
	<span class="header3">Job Description</span>
	<blockquote>When you watch a movie or television program, you are watching more than the work of actors.  You are watching the work of a video editor too.  As a video editor, you would use your creativity to piece together the footage of a film or program. You would have two goals.  You would want to be sure the audience could understand the story.  You also want to edit the film so that the audience could "feel" the movie.  You would use video equipment to make the movie seem exciting, dramatic, funny, or scary.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are colleges that offer programs in video editing. You don't need a college degree to become a video editor, however, it will make a job easier to find.  Experience is very important.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A video editor's salary starts at around $28,000 and can go to over $100,000 in highly specialized areas.</blockquote>

<hr size="1" />

	<span class="header2">Airbrush Artist</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As an airbrush artist, you would work in a photographic processing lab.  You would use your skills to restore damaged or faded photographs. To do this job well, you must understand the photo developing process. You must also like work that requires attention to detail.</blockquote>
	<span class="header3">Education</span>
	<blockquote>On-the-job training is provided for employees. Employers look for people who have a steady hand and an eye for detail.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary is about $20,000.</blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY</span>
<p>If you prefer a hands-on approach in your work, you might be interested in occupations in this field.  You need to have skill in using technology.</p>

<hr size="1" />

	<span class="header2">Lighting Designer</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A lighting designer is a part of the stage crew that helps the actors look better on stage.  If you would like to be a part of a drama production, but not want to be an actor or director, this may be a job for you.  As a lighting designer, you would use your technical know-how to make the lighting on stage reflect the "feeling" of the play. For example, if the scene were set in the middle of an electrical storm you would make sure there were flashes of light on stage.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A Bachelor's Degree may help you to get a job, but it is not required.  It is important to have experience. Sometimes, lighting designers serve as an apprentice before becoming a designer. An apprentice is someone who is learning a trade by working on the job with an experienced person.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A yearly income of $15,000 to $150,000 may be earned.</blockquote>

<hr size="1" />

	<span class="header2">Sound Mixer</span><br /><br />
	<img class="job_pic" src="/images/icons/BF/43158.jpg" width="100" height="100" border="0" alt="Sound Mixer" />
	<span class="header3">Job Description</span>
	<blockquote>A sound mixer makes the sound tracks for movies or television programs. If you would like to work in the movies or television without being in front of the camera, this job may be for you.  As a sound mixer, you would watch the movie or program and add music or sound effects. These sounds are important to the "feel" of the movie. You would make sure that the music and sound effects fit the scene. For example, the director may want a particular scene to be scary. You would add music and sound effects that would give the audience added reason to be scared.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There is no educational requirement to be a sound mixer. Many sound mixers start their career by serving as an apprentice.  An apprentice is someone who is learning a trade by working on the job with an experienced person. Part-time jobs will be important in gaining needed experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary is based on skill and experience. A sound mixer may earn $20,000 to $100,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Road Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/BF/43239.jpg" width="100" height="100" border="0" alt="Road Manager" />
	<span class="header3">Job Description</span>
	<blockquote>When rock bands or stage productions take their shows on the road, they hire a road manager. If you became a road manager, you would make the arrangements for equipment and performers to arrive at the concerts or performances on time. Road managers have a tough job.  They are expected to deal with any problems during a tour and to handle a thousand details.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There is no college degree needed to be a road manager. You must have experience working with people and solving problems.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $100,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
