<span class="header1">Arts/Communications paired with Public Service (BG)</span>

<p>If you scored high in the "B" and "G" categories, you are a very independent person. Your "no-nonsense" approach ensures that things get done. You are creative, responsible, and outgoing. You enjoy working with others, but can work alone. More than likely, you will choose an occupation that will help your community.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree. In certain occupations, it is valuable to have a Master's Degree or a Ph.D.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">BG Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Community Support Services</span><br /><br />
						<em>Community College Administrator<br /><br />
						City Zoning Director<br /><br />
						Continuing Education Coordinator<br /><br />
						Teacher
							<ul>
								<li>Adult Education</li>
								<li>Public Speaking</li>
								<li>Broadcasting</li>
							</ul>
						Chamber of Commerce Representative<br /><br />
						Visitors Bureau Representative<br /><br />
						TV/Radio Public Affairs Producer<br /><br />
						Lobbyist<br /><br />
						Clergy<br /><br />
						Church Youth Director<br /><br />
						Reservation/Ticket Agent</em>
					</td>
					<td width="33%">
						<span class="header2">Art and Design</span><br /><br />
						<em>Ballet/Symphony Director<br /><br />
						Ballet/Symphony Manager<br /><br />
						Museum Director<br /><br />
						City Planner<br /><br />
						Orchestra Conductor<br /><br />
						Historic Preservationist<br /><br />
						Performing Arts Personnel Director<br /><br />
						Landscape Designer<br /><br />
						Arts Festival Coordinator<br /><br />
						Exhibit Designer<br /><br />
						Photographer<br /><br />
						Cook<br /><br />
						Floral Designer</em>
					</td>
					<td width="33%">
						<span class="header2">Communication Services</span><br /><br />
						<em>Copyright Attorney<br /><br />
						Public Relations Specialist<br /><br />
						Community Affairs Director<br /><br />
						TV/Radio Talk Show Host<br /><br />
						College Marketing Specialist<br /><br />
						Cultural Marketing Specialist<br /><br />
						Broadcaster<br /><br />
						Editorial Writer<br /><br />
						Documentary Film Maker<br /><br />
						Interpreter<br /><br />
						Product Spokesperson<br /><br />
						Theatrical Press Agent<br /><br />
						Market Researcher</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">COMMUNITY SUPPORT SERVICES</span>
<p>Leadership ability plays an important role in achieving success in this field.  Creativity and independence are valuable for those in this field as well.  If you have leadership skills and are creative, here are three occupations to consider.</p>

<hr size="1" />

	<span class="header2">Community College Administrator</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>If you like the idea of helping others to improve their education, you may choose to become a community college administrator. In this job, you would plan educational programs for those in your community. You would also hire qualified instructors to teach them. You would need good problem solving skills.  You would also have to know how to work with large numbers of people.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Master's Degree for this job.  You also need to have a teaching certificate and experience in teaching at a community college.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A yearly salary runs from $27,000 to $90,000.</blockquote>

<hr size="1" />

	<span class="header2">Reservation Agent</span><br /><br />
	<img class="job_pic" src="/images/icons/BG/1216.jpg" width="100" height="100" border="0" alt="Reservation Agent" />
	<span class="header3">Job Description</span>
	<blockquote>As a reservation agent, you would work for an airline or hotel.  You would help people reserve plane tickets and hotel rooms as they plan a vacation or business trip.  A good agent must be able to work well with people and understand the needs of travelers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.  You also need to be able to use a computer.  Geography and history will help you.  Many of the places that people visit are studied in these courses.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly average income of a reservation agent is $26,000.</blockquote>

<hr size="1" />

	<span class="header2">Ticket Agent</span><br /><br />
	<img class="job_pic" src="/images/icons/BG/43274.jpg" width="100" height="100" border="0" alt="Ticket Agent" />
	<span class="header3">Job Description</span>
	<blockquote>If the idea of helping people get to where they want to go appeals to you, you might become a ticket agent. As a ticket agent, you would sell tickets at bus stations, train stations, and airports. You would assign seats to passengers and check-in their luggage. You must like working with the public to be good at this job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.  You also need to know how to use a computer.  Taking Geography in high school may be a good idea. Many of the places visited by your customers are studied in this course.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly income is $26,000.</blockquote>

<hr size="1" />

<span class="header1">ART AND DESIGN</span>
<p>To do well in the occupations in this field, you need to be able to lead.  You also need to have good organization skills.  Creativity is important as well.</p>

<hr size="1" />

	<span class="header2">Museum Director</span><br /><br />
	<img class="job_pic" src="/images/icons/BG/43054.jpg" width="100" height="100" border="0" alt="Museum Director" />
	<span class="header3">Job Description</span>
	<blockquote>A museum is a building where important relics and artifacts are kept and displayed for the public to view. The person who acquires artifacts for a museum to display and makes sure these artifacts are cared for is the museum director.  As a museum director, you would manage the staff, plan the budget, raise funds, and set museum policies. This is a very difficult job.  To succeed in it, you need plenty of energy.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A museum director usually has a Master's Degree or a Ph.D.  Work experience is also important. A director must know every part of the museum business.  Part-time jobs and entry-level positions are first steps in moving into a director's position.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $100,000.</blockquote>

<hr size="1" />

	<span class="header2">Orchestra Conductor</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>An orchestra conductor leads a group of musicians who play different instruments.  As a conductor, you would choose the music, set up tours, and direct rehearsals and concerts. This job requires a person who has musical talent and plays an instrument well.  It also requires a person who enjoys classical music.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree for this job.  You also need to have had a successful career as a musician.  Most conductors have played in several orchestras before they gain this position.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary depends on the reputation of the orchestra the conductor directs. The salary can reach over $100,000 per year.</blockquote>

<hr size="1" />

	<span class="header2">Floral Designer</span><br /><br />
	<img class="job_pic" src="/images/icons/BG/43094.jpg" width="100" height="100" border="0" alt="Floral Designer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like flowers and plants and know how to arrange them, you might become a floral designer. As a designer, you would use different kinds of plants to make bouquets and other flower arrangements.  You would work directly with the customers, so good people skills are necessary.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some training beyond high school may be needed.  Extracurricular activities and part-time jobs may be a way for you to get training in floral design.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary differs greatly. Some designers work for an hourly wage while others make a guaranteed salary each year. A salary of $20,000+ could be expected.</blockquote>

<hr size="1" />

<span class="header1">COMMUNICATION SERVICE</span>
<p>The processes of creating and sharing are important to each of the occupations in this field. Your creativity and communication skills are valuable assets to these occupations.</p>

<hr size="1" />

	<span class="header2">Radio Community Affairs Director</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A radio community affairs director works with a team to create public service programs to put on the radio.  These programs address a need in the community. In this job, you would learn what the community needed and plan programs that meet those needs.  To be effective in this job, you need to be a good leader and a good writer.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree to become a radio community affairs director. It will be important to have experience too.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $12,000 to $40,000.  The amount depends on how much experience the director has.  It also depends on how much money the community is able to pay.</blockquote>

<hr size="1" />

	<span class="header2">Editorial Writer</span><br /><br />
	<img class="job_pic" src="/images/icons/BG/43276.jpg" width="100" height="100" border="0" alt="Editorial Writer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like for others to know your opinions on events in your community or nation, you might become an editorial writer.  In this job, you would write an opinion about current news issues or stories.  Your goal would be to get others to agree with your point of view.  To be good at this job, you must write well.  You must also be willing to work hard to understand the issues.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a degree in journalism to work for a newspaper.  Most editorial writers work as reporters for several years.  Only then are they given the chance to write their opinions.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>An editorial writer can earn between $17,000 to $55,000.</blockquote>

<hr size="1" />

	<span class="header2">Theatrical Press Agent</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A theatrical press agent handles the publicity for plays.  It is this person who lets people know when a new play opens in your city or town.  As a theatrical press agent, you would supervise the creation of posters, newspaper advertisements, and radio and television commercials.  You would also contact the newspapers, the television station, and radio stations to have the advertisements run.  This is an influential job.  Without a theatrical press agent, people would not know about the play.  No money would be made.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To be a theatrical press agent, a college degree is needed.  An apprenticeship of three years is usually required.  You will find college courses in writing, advertising, and business to be valuable.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary for an agent is $20,000 to $75,000+.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
