<span class="header1">Business/Management paired with Protective/Military Service (CE)</span>

<p>If you show high scores in categories "C" and "E", you are a person who knows how to make things happen. You are adventurous and like exploring new possibilities.  You especially like to take risks and try new things.  You make a good leader. You will want to combine your strong interest in business with your adventurous spirit.</p>
<p>Many of the occupations in this pairing require some sort of specialized training after high school. Some require college level courses.  Others require training programs provided by the company or firm that hires you.</p>

<p><strong>Here are some career possibilities for you to explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">CE Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Management</span><br /><br />
						<em>Education Director<br /><br />
						Operations Manager<br /><br />
						Urban Planner<br /><br />
						Food Service Manager<br /><br />
						Air Traffic Controller<br /><br />
						Funeral Director<br /><br />
						Officer's Club Manager<br /><br />
						Construction Manager<br /><br />
						Store Manager<br /><br />
						Aircraft Sales Representative<br /><br />
						Theater Director<br /><br />
						Auto Detailer</em>
					</td>
					<td width="33%">
						<span class="header2">Finance & Business Development</span><br /><br />
						Auditor<br /><br />
						<em>Management Consultant<br /><br />
						Benefits Administrator<br /><br />
						Financial Aid Officer<br /><br />
						Financial Planner<br /><br />
						Organizational Developer<br /><br />
						Contract Administrator<br /><br />
						Revenue Officer<br /><br />
						Bank Examiner<br /><br />
						Job Development Specialist<br /><br />
						Stock Broker<br /><br />
						Payroll Specialis</em>
					</td>
					<td width="33%">
						<span class="header2">Law & Civil Service</span><br /><br />
						<em>Attaché<br /><br />
						Foreign Service Officer<br /><br />
						Environmental Project Manager<br /><br />
						Communications Manager<br /><br />
						Environmental Protection Specialist<br /><br />
						Secret Service Agent<br /><br />
						FBI Agent<br /><br />
						Police Agent<br /><br />
						Fire Chief<br /><br />
						Intelligence Officer<br /><br />
						Recruiter<br /><br />
						Safety Engineer<br /><br />
						Firefighter</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">MANAGEMENT</span>
<p>These occupations need people who are good leaders and understand the importance of detail. If you fit this description, then you might want to consider the occupations in this field. Here are three examples.</p>

<hr size="1" />

	<span class="header2">Food Service Manager</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A food service manager oversees the operation of a kitchen or dining hall.  As a food service manager, you would plan menus, create a budget, and schedule the staff.  If military life interests you, you could work in the kitchen on a military base.  Otherwise, you might work at any location that has a kitchen and serves food to large numbers of people. This includes schools, hospitals, and nursing homes.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree for this job.  This degree might be in food service management or nutrition.  It might also be in business administration.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $21,000 to $67,000+. Often managers receive bonuses based on profits.</blockquote>

<hr size="1" />

	<span class="header2">Construction Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CE/1140.jpg" width="100" height="100" border="0" alt="Construction Manager" />
	<span class="header3">Job Description</span>
	<blockquote>A construction manager works at a building site to see that construction is done correctly and remains on schedule. As a construction manager, you would schedule the work day for the other construction workers. You would also schedule specialized workers such as plumbers or electricians. You would be responsible for the workers' safety. You would also be responsible for the equipment and budgets. It would be your job to see that the building was completed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need to work as a construction worker before you could get this job. Most construction managers have worked in various jobs on a building site.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The amount of money earned depends on the size and type of project. The yearly salary ranges from $38,000 to $112,000.</blockquote>

<hr size="1" />

	<span class="header2">Auto Detailer</span><br /><br />
	<img class="job_pic" src="/images/icons/CE/C29095.jpg" width="100" height="100" border="0" alt="Auto Detailer" />
	<span class="header3">Job Description</span>
	<blockquote>Many people take great pains to make sure that their cars are kept in good condition. An auto detailer helps in the care of cars. In this job, you would clean cars, trucks, or vans from bumper to bumper, inside and outside. You might even paint stripes or add personalized touches to the vehicle for the owner. You would be doing very strenuous work, so you would need to be in good physical condition.  You would also need to be detail oriented.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need experience in car upkeep for this job.  There are no educational requirements.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary varies. Some detailers are paid by the hour. Others receive a salary.</blockquote>

<hr size="1" />

<span class="header1">FINANCE & BUSINESS DEVELOPMENT</span>
<p>Peple in the occupations in this field help others to make money. Here are three examples of the types of occupations in this field.</p>

<hr size="1" />

	<span class="header2">Management Consultant</span><br /><br />
	<img class="job_pic" src="/images/icons/CE/1126.jpg" width="100" height="100" border="0" alt="Management Consultant" />
	<span class="header3">Job Description</span>
	<blockquote>Many companies need advice on how to invest and use their money. A financial management consultant looks for new ways for a company to make and use money wisely.  If you were a diversity management consultant, you would help companies to manage different people.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A college degree is needed to become a management consultant.  Most companies look for those with degrees in business, math, or a computer-related area.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary runs from $25,000 to $80,000.</blockquote>

<hr size="1" />

	<span class="header2">Organizational Developer</span><br /><br />
	<img class="job_pic" src="/images/icons/CE/1249.jpg" width="100" height="100" border="0" alt="Organizational Developer" />
	<span class="header3">Job Description</span>
	<blockquote>Companies often look for ways to improve their day-to-day operations. As an organizational developer, you would look at the organizational plan of a company to see what changes were needed. For example, you might find the company should provide better employee benefits. Or, you might find it should hire new people or reduce the number of people employed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A college degree is required for this job.  Good communication skills are needed too.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary range is about $23,000 to $80,000 per year.</blockquote>

<hr size="1" />

	<span class="header2">Financial Aid Officer</span><br /><br />
	<img class="job_pic" src="/images/icons/CE/1202.jpg" width="100" height="100" border="0" alt="Financial Aid Officer" />
	<span class="header3">Job Description</span>
	<blockquote>A financial aid officer works with students who need help in paying their college tuition. In this job, you would let students know what kinds of loans or grants they might qualify for. You would help them to complete the necessary application forms. You would also see that those students who met the requirements for receiving money got this money.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma to become a financial aid officer. Courses in math, statistics, and English are valuable, so consider taking these in high school.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $21,000 to $35,000.</blockquote>

<hr size="1" />

<span class="header1">LAW & CIVIL SERVICE</span>
<p>The occupations in this field deal with the laws of the nation or state. Civil servants are people who provide services to the general public. If you want to help those living in your community, consider the occupations in this field.</p>

<hr size="1" />

	<span class="header2">Military Attaché</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A military attaché works for the military. In this job, you would collect information about the military forces of other countries. To be able to do this, you would meet with government officials and other people who have information.  You would then decide what the other country's government might be planning to do.  You would report what you had found out to the people who needed to know. Commanders might use this information as they plan possible military movements.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree for this position.  You also need to understand one or more foreign languages.  Knowledge of other countries is a must. To be chosen as an attaché, you would need to have many years' experience in the military. The person who fills this position has to be very educated.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

	<span class="header2">Foreign Service Officer</span><br /><br />
	<img class="job_pic" src="/images/icons/CE/1113.jpg" width="100" height="100" border="0" alt="Foreign Service Officer" />
	<span class="header3">Job Description</span>
	<blockquote>A foreign officer works for the government.  In this job, you would work at an embassy or consulate. You would live in the country where you were providing service.  Your job would be to help American citizens who traveled to that country.  You would also help American companies work with that country's government.  Your goal would be to help Americans and American businesses enjoy or work in the country.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to be a Foreign Service officer.  You also need to have studied at least one foreign language.  Also courses in English, history, economics, and public speaking are important. The person who fills this position must be very educated. Knowledge of other countries is a must.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>You would be employed by the U.S. Government in this job, so the yearly salary you receive is based on your government pay grade.</blockquote>

<hr size="1" />

	<span class="header2">Environmental Protection Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/CE/1285.jpg" width="100" height="100" border="0" alt="Environmental Protection Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>An environmental protection specialist works for the government.  In this job, you would monitor companies and manufacturers.  Your job would be to see that they obeyed the regulations that keep the air and water clean.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in a technical field for this job. You also need to have skills in accounting and statistics.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The starting salary of an environmental protection specialist is between $25,000 to $30,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
