<span class="header1">Clerical/Administrative paired with Public Service (DG)</span>

<p>If you scored high in the "D" and "G" categories, you are reliable and honest.  You are also supportive, and resourceful. You are the kind of person that employers prefer.  If you want to, you can use your organizational skills and interest in helping others to make a difference in the world.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree. For some jobs, it may be valuable to have a Master's Degree or a Ph.D.</p>

<p><strong>Here are some career possibilities for you to explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">DG Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Community Services</span><br /><br />
						<em>Social Worker
							<ul>
								<li>Occupational</li>
								<li>School</li>
								<li>Human Services</li>
							</ul>
						Vocational Rehabilitation Counselor<br /><br />
						Postal Inspector<br /><br />
						Teacher Aide<br /><br />
						Real Estate Broker<br /><br />
						Flight Attendant<br /><br />
						Church Attendant<br /><br />
						Postal Worker<br /><br />
						Hospital Outpatient Coordinator</em>
					</td>
					<td width="33%">
						<span class="header2">Administrative Services</span><br /><br />
						<em>Government Office Administrator<br /><br />
						Literary Agent<br /><br />
						Human Resources Job Analyst<br /><br />
						Insurance Claims Examiner<br /><br />
						Medical Record Administrator<br /><br />
						Executive Assistant<br /><br />
						Transportation Ticket Agent<br /><br />
						Fire Department Secretary<br /><br />
						Receptionist<br /><br />
						Clerk
							<ul>
								<li>File</li>
								<li>Mail</li>
								<li>Insurance Processing</li>
							</ul></em>
					</td>
					<td width="33%">
						<span class="header2">Legal/Military Services</span><br /><br />
						<em>Law Librarian<br /><br />
						Paralegal<br /><br />
						Court Reporter<br /><br />
						Legal Secretary<br /><br />
						Flight Operations Specialist<br /><br />
						Legal Technician<br /><br />
						Personnel Specialist<br /><br />
						Deputy Sheriff<br /><br />
						Real Estate Closing Secretary<br /><br />
						Law Enforcement Dispatcher<br /><br />
						911 Operator<br /><br />
						Administrative Support Specialist</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">COMMUNITY SERVICES</span>
<p>The occupations in this field provide help for members in the community. If you want to help make your community a better place to live, think about the occupations in this field.</p>

<hr size="1" />

	<span class="header2">Computer Service Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/DG/1212.jpg" width="100" height="100" border="0" alt="Social Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Social work is all about helping. If you were to become a social worker, you would help people find solutions to problems. You might help them deal with being unemployed, being physically or mentally disabled, or being addicted to drugs. There is a lot of paperwork involved in being a social worker. There are many different types of social workers as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is needed for an entry level job.  Those with more responsible positions must have a Master's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $23,000 to $56,000.</blockquote>

<hr size="1" />

	<span class="header2">Teacher's Aide or Paraprofessional</span><br /><br />
	<img class="job_pic" src="/images/icons/DG/43319.jpg" width="100" height="100" border="0" alt="Teacher's Aide or Paraprofessional" />
	<span class="header3">Job Description</span>
	<blockquote>Not everyone who works at a school is a teacher.  The job of a teacher's aide is similar to that of a teacher.  As a teacher's aide, you would help a teacher care for his/her students, grade papers, perform clerical duties, and prepare instructional materials.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree or at least some higher-level education courses for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average wage is about $8.29 to $8.77 an hour.</blockquote>

<hr size="1" />

	<span class="header2">Mail Carrier</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>There are many different jobs in the Postal Service. A mail carrier is just one. As a mail carrier, you would start your day by sorting the mail.  Then you would deliver it to those on your route.  Mail carriers must be able to work on their own as well as on a team.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.  You must also be at least 18 years old.  In addition, you must pass a written and physical exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A beginning base range is about $32,000 to $54,000 a year.</blockquote>

<hr size="1" />

<span class="header1">ADMINISTRATIVE SERVICES</span>
<p>The occupations in this field allow you to help employees or customers of a company.  You must be able to work well with others to do these jobs.</p>

<hr size="1" />

	<span class="header2">Job Analyst</span><br /><br />
	<img class="job_pic" src="/images/icons/DG/1364.jpg" width="100" height="100" border="0" alt="Job Analyst" />
	<span class="header3">Job Description</span>
	<blockquote>If you were a job analyst, you would work with the human resources department of a company.  You would write job descriptions so those employees would know exactly what their duties are.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to work in the human resources department of any company. It is even better to have a master's degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $18,000 to $100,000.</blockquote>

<hr size="1" />

	<span class="header2">Executive Assistant</span><br /><br />
	<img class="job_pic" src="/images/icons/DG/1206.jpg" width="100" height="100" border="0" alt="Executive Secretary" />
	<span class="header3">Job Description</span>
	<blockquote>An executive is a person who makes important decisions for an organization or business.  As an executive assistant, you would help the executive set up meetings and conferences. You would also answer letters, prepare reports, and do any other task that needed attention.  You would need to have good people skills to do this job well.  You would also need to be able to use a computer.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $22,000 to $50,000+.</blockquote>

<hr size="1" />

	<span class="header2">Insurance Processing Clerk</span><br /><br />
	<img class="job_pic" src="/images/icons/DG/C506006.jpg" width="100" height="100" border="0" alt="Insurance Processing Clerk" />
	<span class="header3">Job Description</span>
	<blockquote>People who do the clerical work to help the customers of an insurance company are insurance processing clerks. In this job, you would process insurance policy applications. You would also check the terms of the policy when a customer makes a claim against the policy.  You would need to make sure that you prepared the papers correctly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary range is $20,000 to $42,000.</blockquote>

<hr size="1" />

<span class="header1">LEGAL/MILITARY SERVICES</span>
<p>The occupations found in this field require people who are efficient and productive.  They also need people who are dependable.  If you understand the importance of "doing your duty", you may want to look at occupations in this field.</p>

<hr size="1" />

	<span class="header2">Court Reporter</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Courts are required to have somebody "record" what is said in the courtroom during a trial or hearing. The person who does this is a court reporter. As a court reporter, you would use a stenotype machine which is a type of computer that allows you to key in every word that the lawyers, judge, and witnesses say. Some reporters work within the courtroom. Other reporters are self-employed and they work in different locations.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are special schools where you can earn a degree in court reporting. These schools offer two or four year programs. You might also have to pass a written test to become certified by the state in which you work.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges between $23,000 to $73,000.</blockquote>

<hr size="1" />

	<span class="header2">Military Legal Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/DG/43286.jpg" width="100" height="100" border="0" alt="Military Legal Technician" />
	<span class="header3">Job Description</span>
	<blockquote>To become a military legal technician, you would have to join the military. In this job, you would conduct research and prepare for a trial in a military court. You would interview witnesses. You would also keep the law books and trial information needed for the case, and you would make sure that legal paperwork was done correctly. The duties of this job are much like those of a paralegal in the civilian courts.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma to join the military.  On-the-job training is provided.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

	<span class="header2">Administrative Support Specialist</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>An administrative support specialist helps an administrator do his/her job. In this job, you would help with the clerical duties of a military office.  You would type and proofread.  You would also order supplies, and organize and maintain files.  You would use a computer to do your job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma to join the military.  On-the-job training is provided.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
