<span class="header1">Clerical/Administrative paired with Social/Helping (DI)</span>

<p>Your high scores in "D" and "I" show that you have characteristics that are useful to people. You are seen as dependable, friendly, and helpful. Others know that they can count on you. No matter what you choose to do, you will want to know you are helping people.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree.  In some of these jobs, it helps to have a Master's Degree or a Ph.D.</p>

<p><strong>Here are some career possibilities for you to explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">DI Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Education</span><br /><br />
						<em>Education Administrator<br /><br />
						Teacher
							<ul>
								<li>Business</li>
								<li>Continuing Education</li>
								<li>Computer</li>
								<li>Math</li>
								<li>Physical Education</li>
							</ul>
						Nursing Instructor<br /><br />
						Career Counselor<br /><br />
						Library Technician<br /><br />
						Pre-school Coordinator<br /><br />
						Computer Trainer<br /><br />
						Camp Counselor</em>
					</td>
					<td width="33%">
						<span class="header2">Social Helping</span><br /><br />
						<em>Assistant Hospital Administrator<br /><br />
						Clergy<br /><br />
						Social Care Worker<br /><br />
						Marriage & Family Therapist<br /><br />
						Retirement Facility Administrator<br /><br />
						Traffic Safety Administrator<br /><br />
						Flight Attendant<br /><br />
						Cruise Ship Activities Director<br /><br />
						Convention Coordinator<br /><br />
						Meeting & Events Planner<br /><br />
						Nursery School Child-Care Provider</em>
					</td>
					<td width="33%">
						<span class="header2">Administrative Helping</span><br /><br />
						<em>Bank Branch Manager<br /><br />
						Contract Administrator<br /><br />
						Loan Officer<br /><br />
						Office Manager<br /><br />
						Insurance Sales Agent<br /><br />
						Hotel Desk Clerk<br /><br />
						Customer Service Representative<br /><br />
						Claims Adjuster<br /><br />
						Personnel Clerk<br /><br />
						Hospital Receptionist<br /><br />
						Secretary<br /><br />
						Bank Teller</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">EDUCATION</span>
<p>The occupations in this field deal with helping others learn more.</p>

<hr size="1" />

	<span class="header2">Education Administrator</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Even in a school or college, somebody must be in charge. An education administrator oversees the activities that go on in a school, college, or school system. In this job, you might be a school principal. You might also be a county superintendent, or a dean at a college. You would make sure that the teachers, professors, and other school personnel were doing their jobs. You would set goals and plan educational or school programs as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Master's Degree or Ph.D. to advance in the field of education. Teaching experience is required as well.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $31,000 to $200,000+.</blockquote>

<hr size="1" />

	<span class="header2">Computer Trainer</span><br /><br />
	<img class="job_pic" src="/images/icons/DI/1378.jpg" width="100" height="100" border="0" alt="Computer Trainer" />
	<span class="header3">Job Description</span>
	<blockquote>A computer trainer teaches others to use a computer and computer programs. As a computer trainer, you would need technical knowledge of the computer and know how to teach.  Some computer trainers work for one company.  Others have their own computer training business.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need to have some college courses for this job.  Also, you need to know about many different kinds of computers and software packages.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $25,000 to $75,000.</blockquote>

<hr size="1" />

	<span class="header2">Camp Counselor</span><br /><br />
	<img class="job_pic" src="/images/icons/DI/C557003.jpg" width="100" height="100" border="0" alt="Camp Counselor" />
	<span class="header3">Job Description</span>
	<blockquote>If you are an active person and enjoy nature, you might become a camp counselor.  In this job, you would help young people learn about nature and enjoy outdoor activities. You might oversee them while they swam or rode horses. You might also teach archery or craft classes.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma for this job.  Some employers want you to have a Bachelor's Degree in parks and recreation management.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $11,000 to $30,000.</blockquote>

<hr size="1" />

<span class="header1">SOCIAL HELPING</span>
<p>These occupations are for people who want to give support and encouragement to those in need.</p>

<hr size="1" />

	<span class="header2">Clergy</span><br /><br />
	<img class="job_pic" src="/images/icons/DI/43007.jpg" width="100" height="100" border="0" alt="Clergy" />
	<span class="header3">Job Description</span>
	<blockquote>The word "clergy" refers to someone who works as a minister, rabbi, or priest. If you were a member of the clergy, you would run religious activities. You would perform weddings, preside at funerals, and help those who needed it.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to enter this occupation.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary varies.  It depends on the religious affiliation.  It also depends on what the religious community can afford to pay.</blockquote>

<hr size="1" />

	<span class="header2">Medical Assistant</span><br /><br />
	<img class="job_pic" src="/images/icons/DI/43148.jpg" width="100" height="100" border="0" alt="Medical Assistant" />
	<span class="header3">Job Description</span>
	<blockquote>As a medical assistant, you would help a nurse or doctor collect medical information from patients.  You would also help store these records and make sure they were accurate and easy to find.  If you worked in a doctor's office, you would greet the patient.  You would also take his/her temperature and blood pressure, and listen to the patient's heart before the doctor or nurse sees him/her.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need to take special courses at a vocation school to become a medical assistant.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $17,500 to $34,000.</blockquote>

<hr size="1" />

	<span class="header2">Child Care Worker</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A childcare worker has to enjoy being around small children because they take care of children ages 5 and under. You would help keep them occupied and happy with activities. You would see that they got enough rest.  You would also help them to enjoy snacks and meal times. You would probably work with groups of children in a nursery, preschool, or daycare center.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma for this job.  Many employers want to hire people who have experience working with children.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Most childcare workers earn an hourly wage. Some may earn $20,000 a year.</blockquote>

<hr size="1" />

<span class="header1">ADMINISTRATIVE HELPING</span>
<p>If you chose an occupation in this field, you would provide support and help in a company.</p>

<hr size="1" />

	<span class="header2">Administrative Service Manager</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As an administrative service manager, you would have many responsibilities. You would oversee employees and make sure they are doing their jobs. You would also look for ways to make their jobs easier and less time consuming. The purchase and sell of products for your company would also be your responsibility.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree for this job.  It would be helpful to have a degree in business administration or finance.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $30,000 to $60,000.</blockquote>

<hr size="1" />

	<span class="header2">Office Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/DI/43302.jpg" width="100" height="100" border="0" alt="Office Manager" />
	<span class="header3">Job Description</span>
	<blockquote>If you were an office manager, it would be your responsibility to see that the office ran smoothly.  You would look for better ways to do daily tasks. You would be expected to do many different kinds of tasks yourself and you would have to handle many things at once.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You may need a Bachelor's Degree for this job. You will need experience in an office. You will also need experience in managing people.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $22,000 to $50,000+.</blockquote>

<hr size="1" />

	<span class="header2">Personnel Clerk</span><br /><br />
	<img class="job_pic" src="/images/icons/DI/43328.jpg" width="100" height="100" border="0" alt="Personnel Clerk" />
	<span class="header3">Job Description</span>
	<blockquote>Companies keep information about each of their employees on file.  This information includes each employee's job application. It includes information about any job evaluations as well. As a personnel clerk, you would keep employee files up to date and secure. You would use a computer to do this.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.  You need a Bachelor's Degree if you plan to stay with the company and be promoted.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average salary is $29,000 a year.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
