<span class="header1">Protective/Military Service paired with Technology (EF)</span>

<p>With an "EF" interest, you will want to push your physical and mental strength to their limits. You will want to be challenged and have adventures along the way.</p>
<p>Many of the occupations in this pairing require some sort of specialized training after high school. Some require college degrees or college level courses.  For others, you will need technical training.</p>

<p><strong>Here are some career possibilities for you to explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">EF Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Military</span><br /><br />
						<em>Transportation Director<br /><br />
						Military Strategist<br /><br />
						Air Traffic Controller<br /><br />
						Communications Manager<br /><br />
						Ship Captain<br /><br />
						Space Systems Specialist<br /><br />
						Recruiter<br /><br />
						Flight Crew Member<br /><br />
						Recreation Scout<br /><br />
						Flight Operations Specialist<br /><br />
						Radar Operator<br /><br />
						Aircraft Technician</em>
					</td>
					<td width="33%">
						<span class="header2">Technology Operations</span><br /><br />
						<em>Archeologist<br /><br />
						Geologist<br /><br />
						Cartographer<br /><br />
						Physical Education Teacher<br /><br />
						Alcohol, Tobacco, and Firearms Agent<br /><br />
						Sports Coordinator<br /><br />
						Professional Athlete<br /><br />
						State Trooper<br /><br />
						Truck Driver<br /><br />
						Plumber<br /><br />
						Heavy Equipment Operator</em>
					</td>
					<td width="33%">
						<span class="header2">Technology</span><br /><br />
						<em>Engineer
							<ul>
								<li>Structural</li>
								<li>Electronics</li>
								<li>Mechanical</li>
								<li>Robotics</li>
								<li>Waste Management</li>
							</ul>
						Aircraft Pilot<br /><br />
						Millwright<br /><br />
						Electrician<br /><br />
						Computer Service Technician<br /><br />
						Mechanical Engineering Technician<br /><br />
						Aircraft Technician<br /><br />
						Computer Operator<br /><br />
						Machinist</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">MILITARY</span>
<p>There are many technical jobs in the military that offer excitement and challenge. You may find one of these to be to your liking.</p>

<hr size="1" />

	<span class="header2">Air Traffic Controller</span><br /><br />
	<img class="job_pic" src="/images/icons/EF/43161.jpg" width="100" height="100" border="0" alt="Air Traffic Controller" />
	<span class="header3">Job Description</span>
	<blockquote>An air traffic controller uses radar and computer equipment to track aircraft while they are in the air. As an air traffic controller, you would talk to the aircraft pilots at take-off and landing. You would make sure that only one aircraft was on the runway at a time. You would also make sure that they stayed a certain distance from each other while they were in the air.  This is an important job.  Many people's safety depends on the controller.  You can also do this job as a civilian.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To be an air traffic controller, you must receive special training.  An air traffic controller for the military receives training on a military base. The Federal Aviation Agency trains civilian controllers.  A civil service exam must be passed.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.  The yearly salary for a civilian controller ranges from $55,000 to $136,000.</blockquote>

<hr size="1" />

	<span class="header2">Air Crew Member</span><br /><br />
	<img class="job_pic" src="/images/icons/EF/M041.jpg" width="100" height="100" border="0" alt="Air Crew Member" />
	<span class="header3">Job Description</span>
	<blockquote>As a member of an aircrew, you would do one of several different jobs on a military aircraft. You might run the communication and radar equipment, the gunnery systems or other machinery aboard. You might also operate and maintain the in-flight refueling system. This can be a very stressful job.  It puts your physical stamina to the test.</blockquote>
	<span class="header3">Education</span>
	<blockquote>All of the jobs on an aircraft require specialized training. The majority of training is done by the military. A high school diploma is acceptable, but a college degree is preferred.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

<span class="header1">OUTDOOR OPERATIONS</span>
<p>The occupations found in this category are for people who like working with equipment, tools, and technology. If this sounds like you, you might want to work in this field.</p>

<hr size="1" />

	<span class="header2">Cartographer</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A cartographer creates maps.  As a cartographer, you would use information from land surveyors, photographs, and satellites. You would spend much of your time on a computer creating maps from this information.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most cartographers have at least a degree in engineering or science.  Some employees become cartographers by working as a cartographic technician first. This job does not require a degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary is $46,000.</blockquote>

<hr size="1" />

	<span class="header2">Truck Driver</span><br /><br />
	<img class="job_pic" src="/images/icons/EF/1168.jpg" width="100" height="100" border="0" alt="Truck Driver" />
	<span class="header3">Job Description</span>
	<blockquote>As a truck driver, you would take loads of goods and produce across the country to be sold. You would be responsible for whatever you were hauling in your truck until you delivered it to its drop-off.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most companies prefer their truck drivers to have high school diplomas. There are schools that provide training for truck drivers. Each state has strict regulations on the trucking industry.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Most of the time, a truck driver is paid by the hour or by the mile. The yearly salary ranges from $20,000 to $49,000.</blockquote>

<hr size="1" />

	<span class="header2">Heavy Equipment Operator</span><br /><br />
	<img class="job_pic" src="/images/icons/EF/1396.jpg" width="100" height="100" border="0" alt="Heavy Equipment Operator" />
	<span class="header3">Job Description</span>
	<blockquote>Equipment operators use heavy machinery such as cranes and bulldozers to move dirt, wood, or other materials used in construction.  If you were an equipment operator, you might work at road paving sites.  You might also work at industrial and construction sites.  This equipment can be dangerous.  Safety practices are a big concern.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.  You are more likely to get a job operating expensive equipment if you have taken courses at a vocational school.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A general salary range for this job is $19,000 to $53,000 per year.</blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY</span>
<p>If you like a hands-on approach to technology, you might like the occupations in this field.</p>

<hr size="1" />

	<span class="header2">Electronic Engineer</span><br /><br />
	<img class="job_pic" src="/images/icons/EF/C0936_02.jpg" width="100" height="100" border="0" alt="Electronic Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>An electronic engineer helps to create things you use everyday such as radios, computers, and televsions.  In this job, you would design and test electronic equipment.  You might also oversee the making of this equipment.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree for this job.  Most employers are looking for people who have their Master's Degree or Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $48,000 to $108,000 and would depend on the engineer's education and experience.</blockquote>

<hr size="1" />

	<span class="header2">Millwright</span><br /><br />
	<img class="job_pic" src="/images/icons/EF/C1610_07.jpg" width="100" height="100" border="0" alt="Millwright" />
	<span class="header3">Job Description</span>
	<blockquote>As a millwright, you would install, dismantle, and repair heavy machinery for any kind of industry. You would need to be able to read a blueprint.  This is a diagram that explains how the machine is constructed, and how it should be installed.  Millwrights use special tools, so you would also need to understand how tools work and use them correctly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You could become a millwright in two ways.  You might work as an apprentice to another millwright. An apprentice is someone who learns a trade by working on the job with an experienced person.  You might also attend a vocational tech program.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $26,000 to $65,000.</blockquote>

<hr size="1" />

	<span class="header2">Mechanical Engineering Technician</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A mechanical engineering technician helps an engineer to design equipment.  This might be industrial machinery and other equipment.  In this job, you would make sketches of machinery.  You would plan schedules.  You would also prepare layouts and estimate labor costs.  You would write reports too.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Sometimes on-the-job training is available.  But most of the time, you need to have had previous training to get a job.  Vocational schools, community colleges, and the military offer this training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $16,000 to $50,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
