<p class="lead">CHARACTERISTICS OF THE <strong>"A"</strong> CATEGORY</p>
<p class="header2">OUTDOOR</p>
<p>If you have a high score in category "A," you will probably 
prefer outdoor-related jobs. "Outdoor" has to do with work that 
involves tending and managing the environment. You are likely to be 
an active person who enjoys physical activities. You would enjoy a 
job where you can work with your hands building and repairing 
things. You are a practical person who appreciates nature. People 
with outdoor-related jobs are very important to society because they 
help preserve our environment. </p>

