<span class="header1">Outdoor paired with Arts/Communications (AB)
</span>

<p>An "AB" person loves to work in the open environment in settings
such as nature (nature photographer), entertainment (marching band),
recreation (tennis coach), animals (wildlife guide), and land
improvements (landscaper) and is able to communicate well. The
word "communicate" means that you can get your ideas, thoughts, or
feelings understood by others easily and clearly through speaking or
writing. With this pattern, you will probably want to share your
interest in nature, the environment, or animals with others through
your communications skills.</p>
<p>Often, an "AB" person communicates well through "visual media"
using pictures, charts, graphs, or diagrams to help others
understand. No matter which method you decide to use to communicate,
others will probably be able to understand you.</p>
<p>Most occupations in this pairing require a bachelor's degree or
specialized training. Higher levels of education such as a master's
degree or a Ph.D. are valuable to certain occupations in this
pattern.</p>

<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
Any courses that deal with communication, visual media, outdoors,
and nature will probably interest you and could help prepare you for
possible career opportunities.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Computer Technology<br />
			Public Relations<br />
			Computer Sciences<br />
			Environmental Science
		</td>
		<td>
			Advertising<br />
			Health/Nutrition<br />
			World Language<br />
			Industrial Technology
		</td>
		<td>
			Agriculture<br />
			Biology<br />
			Psychology<br />
			Sociology
		</td>
		<td>
			Art/Graphic Arts<br />
			Music<br />
			Photography<br />
			Marketing
		</td>
		<td>
			Physical Education<br />
			Economics<br />
			Communications<br />
			Home Economics
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations you
may find interesting:</strong><br />
If you have time for after-school activities or part-time jobs, make
them count. You will probably enjoy any club or activity that
involves communicating with others and/or sharing a love for
nature.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Newspaper/Yearbook<br />
			Habitat for Humanity<br />
			Future Farmers of America<br />
			Audio-Visual Services
		</td>
		<td>
			Athletics<br />
			Drama/Theatre<br />
			Photography Club<br />
			Language Club
		</td>
		<td>
			Scouts<br />
			Band/Chorus<br />
			Debate Team<br />
			Adopt-a-Mile
		</td>
		<td>
			Parks/Recreation<br />
			Pen Pals<br />
			Radio/TV activities<br />
			Animal Care
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These workplaces may offer opportunities to help you decide on a
career.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising Agencies<br />
			Printing Companies<br />
			Graphic Design Firms<br />
			Photography Studios
		</td>
		<td>
			Lawn Care Services<br />
			Landscaping Companies<br />
			TV/Radio Studios<br>
			Theaters
		</td>
		<td>
			Libraries<br />
			Farms<br />
			Lumberyards
		</td>
		<td>
			Newspaper Publishing Firms<br />
			Parks/Recreation Depart.<br />
			Photographic Laboratories
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">AB Career Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8" border="none">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Arts/Communications</span><br />
						<em>Environmental
Lawyer<br />
						Public
Administrator<br />
						Foreign
Correspondent<br />
						Parks &
Recreation Administrator<br />
						Public Relations
Specialist<br />

	Recreation\Coach<br />

	Cartoonist<br />
						Nature
Writer<br />
						Documentary
Writer<br />
						Nature
Photographer<br />
						Fund
Raiser<br /></em>
					</td>
					<td width="33%">
						<span
class="header2">Out of Doors</span><br />
						<em>Nature Scientist
							<ul>

	<li>Botanist</li>

	<li>Zoologist</li>
							</ul>
						Agricultural
Scientist<br />
						Geologist<br />

	Petrologist<br />

	Hydrologist<br />
						Athletic
Coach<br />
						Professional
Athlete<br />
						Soil
Technician<br />
						Parks and Recreation
Manager<br />
						Dog
Trainer<br /></em>
					</td>
					<td width="33%">
						<span
class="header2">Designing/Engineering</span><br />

	<em>Designing/Engineering<br />
						Architect<br />
						Urban
Planner<br />

	Engineer/Designer<br />
						Pilot<br />

	Meteorologist<br />
						Stevedore<br />
						Plumber<br />
						Sculptor (concrete,
lawn)<br />
						Pest Control
Worker<br />
						Developer
							<ul>

	<li>Residential</li>

	<li>Commercial</li>

	<li>Recreational</li>
							</ul></em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">ARTS AND COMMUNICATIONS</span>
<p>Do you want to share your interest in nature and the environment
with others?  Do you have strong communication skills?  If so, a
career as an environmental lawyer, writer, or photographer may be of
interest to you.</p>

<hr size="1" />

	<span class="header2">Environmental Lawyer</span><br />
	<img class="job_pic" src="/images/icons/AB/1360.jpg"
width="100" height="100" border="0" alt="Environmental Lawyer" />
	<span class="header3">Job Description</span>
	<blockquote>If you want to influence how people and
organizations use the earth's environment, this occupation may be
for you. To practice environmental law, you must understand the law
and communicate well. You must also be organized and able to
negotiate with others. If you become an environmental lawyer, you
might develop a legal case or appear in court to prevent the
building of a road through a wilderness area.  You might also defend
a logging company's right to build that road.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You will need a bachelor's degree and three
years of law school to be an environmental lawyer. You must also
pass the state "bar exam."  To learn about nature sciences and city
and rural development, volunteer with political action groups
concerned about the environment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of lawyers was $122,960
in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Writer</span><br />
	<img class="job_pic" src="/images/icons/AB/1040.jpg"
width="100" height="100" border="0" alt="Writer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like to write and are good at it, you may
want to become a professional writer. Writers express their thoughts
and ideas through words written on a page or computer screen. As a
writer, you could help inform others about issues that affect the
environment. You may work on nature documentaries, or on articles
for newspapers, nature magazines, or scientific
journals.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers look for writers with at least a
bachelor's degree. Education is very valuable, but you must have
talent and skill too. You will want to write as much as possible.
Getting involved in writing groups, school newspapers, and yearbooks
can give you valuable experience and improve your skills. Practice
is important, so take every opportunity to write.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of writers and authors
was $63,200 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Nature Photographer</span><br />
	<img class="job_pic" src="/images/icons/AB/43060.jpg"
width="100" height="100" border="0" ALT="Nature Photographer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like taking pictures of natural settings
and have a good "eye,"  you may become a nature photographer. To do
so, you must be creative and understand how cameras work. Your work
might appear in magazines, books and journals, or in travel and
advertising displays. Many photographers work for themselves. So, it
is helpful to understand how a small business works.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree in photography or the visual
arts can develop your basic skills. But, you also need to be
creative to succeed in this	field. Spend as much time as
possible looking at great pictures and taking your own. Getting
involved in photography clubs and working in photo shops and labs
will help you learn more about using your camera to capture
nature.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of photographers was
$36,280 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">ANIMAL AND NATURE SCIENCES</span>
<p>Occupations in this field are concerned with studying and working
with plants and animals. They are more "hands on" than occupations
in the arts and communication field. People in this field work to
benefit the plants and animals in our environment. They should be
active and enjoy being in nature and working outdoors.</p>

<hr size="1" />

	<span class="header2">Botanist</span><br />
	<img class="job_pic" src="/images/icons/AB/1020.jpg"
width="100" height="100" border="0" alt="Botanist" />
	<span class="header3">Job Description</span>
	<blockquote>Botanists (wildlife biologists) study plants and their environments.
Some study all aspects of plant life, including algae, fungi,
lichens, mosses, ferns, conifers, and flowering plants; others
specialize in areas such as identification and classification of
plants, the structure and function of plant parts, the biochemistry
of plant processes, the causes and cures of plant diseases, the
interaction of plants with other organisms and the environment, and
the geological record of plants.</blockquote>
	<span class="header3">Education</span>
		<blockquote>Most biological scientists need a Ph.D.
degree
in biology or one of its subfields to work in research or
development positions. A period of postdoctoral work in the
laboratory of a senior researcher has become common for biological
scientists who intend to conduct research or teach at the university
level.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of botanists was $63,270
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Zoologist</span><br />
	<img class="job_pic" src="/images/icons/AB/1079.jpg"
width="100" height="100" border="0" alt="Zoologist" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy learning about and working with
animals, you may become a zoologist.  Zoologists work in zoos and
wildlife parks.  They also work in research centers and agricultural
settings.  If you become a zoologist, you could help save animals or
protect endangered species. You might also help develop better ways
to raise animals for food, or work to produce better breeds of
animals.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A zoologist must have at least a bachelor's
degree for an entry-level job.  Employers prefer a master's degree
or Ph.D.  To find out if you enjoy close contact with animals, you
might work on a farm, or in a zoo or pet store.  You might also
volunteer as a veterinarian's assistant.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of zoologists was $63,270
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Logging Worker</span>
	<br />
	<span class="header3">Job Description</span>
	<blockquote>Logging workers harvest timber from forests to
provide the raw material for consumer and industrial products.
Logging jobs are physically demanding and can be dangerous.  Workers
spend the majority of their time outdoors, sometimes in bad weather
and often in remote areas.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most logging workers need a high school
diploma.  You will recieve on-the-job training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage for logging workers was
$41,230 in May 2019.</blockquote>

<hr size="1" />

<span class="header1">DESIGNING AND ENGINEERING</span>
<p>Another good way to combine your interests in nature, the arts,
and communications is to put your skills to use in design and
engineering. These occupations are very technical. To do them, you
must be good at logical thinking and planning. You must also
be able to demonstrate your plan or create a sample of the new
product you have developed. Those who enjoy careers in these fields
are very precise people. They like detailed work and are willing to
spend time ensuring that things are done right.</p>
<p>Let's look at three occupations that may interest you.</p>

<hr size="1" />

	<span class="header2">Urban Planner</span><br />
	<img class="job_pic" src="/images/icons/AB/43137.jpg"
width="100" height="100" border="0" alt="Urban Planner" />
	<span class="header3">Job Description</span>
	<blockquote>The word "urban" means "city." An urban planner
works with agencies that are concerned with the growth of cities. As
an urban planner, you would help to see that cities grew in ways
that were good for the environment and for people.  You might decide
that a new street is needed or that old buildings should be
repaired. You might work to ensure that water and sewage are
available when new communities are developed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers require at least a bachelor's degree.
You will need a master's degree to advance in this field.  You also
need to be creative and able to see the "big picture" when faced
with a complex problem.  To see if urban issues interest you,
volunteer with groups that work to make their city a better place to
live.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage for urban
planners was $74,350 in May 2019.</blockquote>

<hr size="1">

	<span class="header2">Industrial Designer</span><br />
	<img class="job_pic" src="/images/icons/AB/C0777_50.jpg"
width="100" height="100" border="0" alt="Industrial Designer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like to create things that others want,
you may become an industrial designer.  An industrial designer plans
and makes manufactured products such as toys, cars, or exercise
equipment for others to buy. To succeed at this occupation, you need
to be artistic. You also need to understand what consumers want to
buy.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers require at least a bachelor's degree.
They look for experience as well. You will also need a flair for
seeing where a product can be improved or a new product is needed.
Spend time with people who "tinker," - play with products to see if
they can be improved.  Obtain part-time work in a manufacturing
setting, if possible.  Find a way to be around people who can teach
you informally how to think about products.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage for industrial designers
was $68,890 in May 2019. </blockquote>

<hr  size="1" />

	<span class="header2">Land Surveyor</span><br />
	<img class="job_pic" src="/images/icons/AB/43169.jpg"
width="100" height="100" border="0" alt="Land Surveyor" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy working outdoors with others, you
may become a land surveyor.  A land surveyor works with a team of
two to four people to measure land and map out property boundaries.
Construction crews cannot start building until the land has been
surveyed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most surveyors have a bachelor's degree. Licensure is required to offer surveying services to the public.  A part-time job with a surveying company could help
you determine if you would like to become a land surveyor.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage for land surveyors was
$63,420 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p>
 
<blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 9, 2020). </blockquote>
 
<blockquote>National Center for O*NET Development, <i> O*NET Online</i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 9, 2020). </blockquote>

</div>
 