<span class="header1">Outdoor paired with Business / Management (AC)
</span>

<p>Your high score in category "A" shows that you are a person who
might like an outdoor job that allows you to work with your hands.
Your high score in "C" shows that you may have an interest in
working with others.  You probably would like jobs in business,
sales, and management.  You may like jobs that require that you
negotiate.  It is likely that you work well with people.  You may be
happiest in an occupation that includes plenty of interactions with
different people.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree. It is helpful to have a master's degree or Ph.D. if you hope
to work in some of these occupations.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
Any courses that deal with the outdoors, nature, and business will
likely interest you and could help prepare you for possible career
opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting<br />
			Botany<br />
			Psychology
		</td>
		<td>
			Shop & Industrial Arts<br />
			Computer Sciences<br />
			Marketing & Advertising
		</td>
		<td>
			Agriculture<br />
			Business Law<br />
			Economics
		</td>
		<td>
			Physical Education<br />
			Public Relations<br />
			Speech & Communications
		</td>
		<td>
			Biology<br />
			Business Math<br />
			Sociology
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations you
may find interesting:</strong><br />
If you have time for after school activities or part-time jobs, make
them count. You will probably enjoy any club or activity where you
can share your love of nature and use your business sense.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Animal Care<br />
			Yearbook Staff<br />
			Adopt-a-Mile
		</td>
		<td>
			Habitat for Humanity<br />
			Community Volunteer<br />
			Computer Activities
		</td>
		<td>
			Future Farmers of America<br />
			Student Exchange Program<br />
			Future Business Leaders
		</td>
		<td>
			Parks & Recreation<br />
			Class/Club Officer<br />
			Junior Achievement
		</td>
		<td>
			Marketing<br />
			Athletics<br />
			Scouts
		</td>
	</tr>
</table>

<p><strong>Workplaces that you might wish to consider for a part-
time job:</strong><br />
These workplaces may offer opportunities to help you decide what you
want to do as an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising Firms<br />
			Park Services<br />
			Lumberyards<br />
			TV/Radio Studios
		</td>
		<td>
			Landscaping Firms<br />
			Newspaper Publishing Firms<br />
			Graphic Design Firms<br />
		</td>
		<td>
			Printing Companies<br />
			Lawn Care Services<br />
			Delivery Services<br />
		</td>
		<td>
			Theaters<br />
			Farms<br />
			Nurseries<br />
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">AC Career Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%"
align="left"><strong>More People Oriented</strong></td>
					<td width="33%"
align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Business</span><br />
						<em>Agricultural
Economist<br />
						Museum
Director<br />
						Agribusiness
Consultant<br />
						Range
Manager<br />
						Union
Leader<br />
						Farm
Broker<br />
						Factory
Manager<br />
						Warehouse
Supervisor<br />

	Auctioneer<br />
						Pet Shop
Owner/Worker</em>
					</td>
					<td width="33%">
						<span
class="header2">Outdoor Management</span><br />
						<em>Nature Scientist
							<ul>

	<li>Horticulturist</li>
							</ul>
						Wildlife
Manager<br />
						Recreation
Administrator<br />
						Resort
Manager<br />
						Farm
Manager<br />
						Rancher<br />
						Orchard
Manager<br />
						County Fair
Organizer<br />
						Nursery
Manager/Worker</em>
					</td>
					<td width="33%">
						<span
class="header2">Environment</span><br />
						<em>Regional
Planner<br />

	Environmentalist<br />
						Environmental Health
Inspector<br />
						Environmental Risk
Manager<br />
						Wetlands
Manager<br />
						Safety/Traffic
Engineer<br />
						Logging
Supervisor<br />
						Water Quality
Technologist<br />
						Agricultural
Technician<br />
						Waste Management
Technician<br />
						Forestry
Technician</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<p>Keep reading to learn more about some of the occupations shown
above.</p>

<hr size="1" />

<span class="header1">BUSINESS</span>
<p>The occupations in this field help others use our earth's natural
resources in a productive and efficient way. Without those in this
field, the earth's resources would not last long against the demands
of our growing population.</p>

<hr size="1" />

	<span class="header2">Agricultural
Economist</span><br />
	<img class="job_pic" src="/images/icons/AC/1142.jpg"
width="100" height="100" border="0" alt="Agricultural Economist" />
	<span class="header3">Job Description</span>
	<blockquote>If you become an agricultural economist (also known as environmental economist), you
would help in growing, pricing, and selling farm products. You
would find out what customers want, and tell farmers what to plant,
and how much they should charge for it.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To work as an assistant to an agricultural
economist, you need a bachelor's degree in agriculture.  You need at
least a master's degree to become an agricultural economist.  Many
in this field have a Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of agricultural
economists was $105,020 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Range Manager</span><br />
	<img class="job_pic" src="/images/icons/AC/1023.jpg"
width="100" height="100" border="0" alt="Range Manager" />
	<span class="header3">Job Description</span>
	<blockquote>A range manager works to protect the plant and
animal life of rangelands that are used for business or recreation.
For example, a business may be drilling for oil on the rangeland.
As a range manager, you would monitor the drilling activities to
make sure no oil was spilled. This is a difficult occupation.  To do
it well, you would need knowledge of both nature and business
management.  You must also be able to balance the business's needs
with those of the environment.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A range manager must have at least a bachelor's
degree in range management or range science.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of range managers was
$62,660 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Agricultural Manager</span><br />
	<img class="job_pic" src="/images/icons/AC/43204.jpg"
width="100" height="100" border="0" alt="Agricultural Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Agricultural Managers take care of the day-to-
day operation of one or more farms, ranches, nurseries, or other
agricultural establishments for corporations or owners. Agricultural
managers usually do not do production activities themselves.
Instead, they hire and supervise farm and livestock workers to do
most daily production tasks.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You may learn a lot about farming through
experience. You may, however, also want to get a bachelor's degree
in agriculture or farm science. A bachelor's degree offers the
advantage of knowing about the technology used in farming today and
in the future.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of agricultural managers
was $71,160 in May 2019. </blockquote>

<hr size="1">

<span class="header1">OUTDOOR MANAGEMENT</span>
<p>In this field, you would work more with people than with nature
and the environment. To succeed as a manager, you must be a good
team leader, be able to plan ahead, and want to work outdoors. Here
are three occupations which may interest you.</p>

<hr size="1" />

	<span class="header2">Zoologist</span><br />
	<img class="job_pic" src="/images/icons/AC/1270.jpg"
width="100" height="100" border="0" alt="Wildlife Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Zoologists study the characteristics of animals,
such as their interactions with other species, reproduction,
diseases, and movement patterns.  For example, they might take blood
samples from animals to assess their levels of nutrition.  Most
zoologists work on research teams with other scientists and
technicians.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Zoologists need a bachelor's degree for entry-
level jobs, but a master's degree is often needed for advancement. A
Ph.D is necessary for most independant research jobs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of zoologists was $63,270
 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Recreational
Therapist</span><br />
	<img class="job_pic" src="/images/icons/AC/C553057.jpg"
width="100" height="100" border="0" alt="Recreational Therapy" />
	<span class="header3">Job Description</span>
	<blockquote>Recreational therapists plan recreational
activities.  They also see that these activities go smoothly and
that people who participate have a good time.  As a recreational
therapist, you might plan a craft class for a group of eight-
year-olds. You may also plan physical exercise programs or travel
groups for people of all ages.  You may even work at a beach resort
or on a cruise ship.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree to become
a recreational therapist.  You also need to be creative and
enthusiastic.  To get experience and see if you would like this job,
get a part-time job as a camp counselor or a youth
organizer.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of recreational
therapists was $48,220 in May 2019. </blockquote>

<hr  size="1" />

	<span class="header2">Farm Manager</span><br />
	<img class="job_pic" src="/images/icons/AC/1028.jpg"
width="100" height="100" border="0" alt="Farm Manager" />
	<span class="header3">Job Description</span>
	<blockquote>If you like both farming and business, you may
become a farm manager.  As a farm manager, you would run another
person's farm. You would plan the planting and harvesting of crops,
and get the crop to market for selling.  You would also decide how
many farm workers were needed and what chores they needed to
do.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Farm managers need at least a high school diploma and practical experience.  Consider summer work on a farm to get
that experience.  Many people want to become farm managers, so you
must be well prepared. A bachelor's degree with courses in agriculture and business will set you apart when applying for a position as a farm manager. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of farm managers was $71,160
in May 2019.  </blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>The occupations in this field call for strong, free thinking
people who do not mind getting their hands dirty or being on their
own. All the occupations in this field have one thing in common.
They require that you work directly with our environment.  If you
want to do this and have the qualities that were listed, there are
three occupations that you might find interesting.</p>

<hr size="1" />

	<span class="header2">Environmental Engineer
</span><br />
	<img class="job_pic" src="/images/icons/AC/1285.jpg"
width="100" height="100" border="0" alt="Environmental Engineers " />
	<span class="header3">Job Description</span>
	<blockquote>Environmental engineers use the principles of
engineering, soil science, biology, and chemistry to develop
solutions to environmental problems. They are involved in efforts to
improve recycling, waste disposal, public health, and control of
water and air pollution.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Environmental engineers must have a bachelor's
degree in environmental engineering or a related field, such as
civil, chemical, or mechanical engineering.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of environmental
engineers was $88,860 in May 2019.</blockquote>

<hr  size="1" />

	<span class="header2">Waste Management
Technician</span><br />
	<img class="job_pic" src="/images/icons/AC/43020.jpg"
width="100" height="100" border="0" alt="Waste Management
Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Manufacturing processes can create dangerous
waste materials.  If you become a waste management technician (or waste handling technician), you
might help to remove chemical or nuclear wastes created by these
processes.  You would wear protective clothing. You would work with
equipment designed to remove toxic waste from the water and
soil.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma to become a waste
management technician. You would also participate in a training
program offered by your company or receive training through a technical school.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of a waste management technician was
$43,900 in May 2019.</blockquote>

<hr size="1" />

<span class="header2">Forester</span><br />
<img class="job_pic" src="/images/icons/AC/1042.jpg" width="100"
height="100" border="0" alt="Forester" />
<span class="header3">Job Description</span>
<blockquote>A forester works to allow people to visit and
use our forests, and to protect the environment.  If you become a
forester, you might plan and oversee forest operations.
These include logging, tree planting, water regulation, and wildlife
management.  You might also collect information for research and
oversee work crews. This is not an easy job.  You must be willing to
work hard and be outside in all kinds of weather.</blockquote>
<span class="header3">Education</span>
<blockquote>To become a forester, you need a bachelor's
degree in forestry or a related field.</blockquote>
<span class="header3">Salary</span>
<blockquote>The median annual wage of foresters was
$61,790 in May 2019.</blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 9, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 9, 2020). </blockquote>


</div>


