<span class="header1">Outdoor paired with Protective/Military
Service (AE)</span>

<p>If you scored high in categories "A" and "E," you have a strong
interest in nature and you are an adventurous spirit. You like to
explore new possibilities.  You also know how to  get things done.
You are willing to be a leader and to get your hands dirty.</p>
<p>You need specialized training after high school for many of the
occupations in this pairing.  For some you will need college level
courses.  For others on-the-job training will be sufficient.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
You should take courses that will help you to learn about the
environment. Life sciences and earth sciences courses will be
especially valuable.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Agriculture<br />
			Political Science<br />
			Physical Education<br />
			Telecommunications
		</td>
		<td>
			Business Law<br />
			Biology<br />
			Business Ed.<br />
			Physics
		</td>
		<td>
			Graphic Arts<br />
			Civics/Government<br />
			Economics<br />
			Sociology
		</td>
		<td>
			Criminal Justice<br />
			Geography<br />
			Computer Sciences<br />
			Health/Nutrition
		</td>
		<td>
			Computer Information Systems<br />
			History<br />
			Language (Spanish, etc.)<br />
			Industrial Technology
		</td>
	</tr>
</table>

<p><strong>Extracurricular/ volunteer activities or organizations
that you may find interesting:</strong><br />
If you have time for after school activities or part-time jobs, make
them count. You will probably enjoy any club or activity that
involves working with others and/or sharing a love for nature.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Adopt-a-Mile<br />
			Habitat for Humanity<br />
			Band
		</td>
		<td>
			Athletics<br />
			ROTC<br />
			Martial Arts
		</td>
		<td>
			Scouts<br />
			Flight Training<br />
			Parks/Recreation
		</td>
		<td>
			Camp Activities<br />
			Future Farmers of America<br />
			Language Club
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Camp Counseling<br />
			Landscaping/Lawn Care<br />
			Construction Sites
		</td>
		<td>
			Farming<br />
			Lumberyards<br />
			Parks/Recreation
		</td>
		<td>
			Life Guarding<br />
			Veterinary Offices
		</td>
		<td>
			Surveying Companies<br />
			Environmental Agencies
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">AE Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Military</span><br />

	<em>Pilot<br />
						Intelligence
Specialist<br />
						Graphic
Information
Specialist<br />
						Aircraft Launch
&
Recovery Specialist<br />
						Artillery Crew
Member<br />
						Military
Police<br />
						Platoon/Squad
Leader<br />
						Mapping
Technician<br />
						Explosive
Blasting
Specialist</em>
					</td>
					<td width="33%">
						<span
class="header2">Environmental</span><br />
						<em>Nature
Scientist
							<ul>

	<li>Geologist</li>

	<li>Marine Biologist</li>
							</ul>
						Agricultural
Scientist<br />
						Marine
Surveyor<br />
						Wildlife
Manager<br />
						Park
Ranger<br />
						Waste Management
Technician<br />
						Cartographer
Technician</em>
					</td>
					<td width="33%">
						<span
class="header2">Outdoor Service</span><br />
						<em>Homeland
Security Officer<br />
						Immigration
Specialist<br />
						Public Safety
Officer<br />
						Construction
Equipment Operator<br />

	Firefighter<br />
						Heavy Equipment
Mechanic<br />
						Security
Guard<br />
						Construction
Worker<br />

	Groundskeeper</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">MILITARY</span>
<p>If you are looking for a challenge that will test your brain and
body, consider the occupations in this field.</p>

<hr size="1" />

	<span class="header2">Military Pilot</span><br />
	<img class="job_pic" src="/images/icons/AE/43025.jpg"
width="100" height="100" border="0" alt="Military Pilot" />
	<span class="header3">Job Description</span>
	<blockquote>Military pilots fly many kinds of aircraft in
all branches of the Armed Forces.  As a military pilot, you might
fly a reconnaissance plane or supersonic jet fighter.  You might
also fly a helicopter or cargo transport.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree from a military
college to become a military pilot.  Both the college and follow up
training programs are very difficult.  Many people want to be a
military pilot.  Only a few can meet the requirements.  To get this
job you must work very hard and have great mental and
physical health.  You should expect to attend graduate school and
other military education programs as you advance in your career.  It
takes about 16 years to become a high-ranking command
pilot.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the Military is
based on your rank, years of service and occupational
specialty.</blockquote>

<hr size="1" />

	<span class="header2">Intelligence
Specialist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>You have probably seen movies about government
spies who provide information on an opposing government. These are
intelligence specialists. These individuals gather and study
information that is needed to protect our national safety.  In this
job you would use tools such as computers and satellites.  You
would also take and study photographs and create and study maps.
For example, they might find out about another nation's troop
movements.  They might discover their military codes or find their
missile sites.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree and special training
from the military for this job. Courses in algebra, geometry, and
geography will be helpful to you.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of intelligence specialists was $83,170 in
May 2019.</blockquote>

	<span class="header2">Blasting Specialist</span><br />
	<img class="job_pic" src="/images/icons/AE/M15-0974.jpg"
width="100" height="100" border="0" alt="Blasting Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>A blasting specialist works with explosives used
by the military. If you become a blasting specialist, you would move
explosives from one location to another.  You would also blow up
buildings or other sites.  You would keep detailed records of what
you had done. To work as a blasting specialist you must be able to
stay calm under pressure.  You must also be able to follow
procedures carefully and exactly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>It's best to have a college degree.  You will
also need to attend a special training program.  It is important to
understand chemistry so that you can handle explosives
safely.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of of blasting specialists was $46,250 in May 2019.</blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENTAL</span>
<p>You may have a strong interest in working outdoors or in saving
our environment. The occupations in this field deal with the "Great
Outdoors."</p>

<hr size="1" />

	<span class="header2">Marine Surveyor</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Marine surveyors (or marine engineers) explore the land under the
world's oceans and seas.  As a marine surveyor, you would use
different equipment to find out how deep the water is and what kind
of land lies under it.  You would not work alone.  Instead, you
would be part of a team. You must be very precise and detail
oriented when working as a marine surveyor.  You must also work well
with other people.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most surveyors, cartographers, and
photogrammetrists have a bachelor's degree in surveying or a related
field. Every state requires that surveyors be licensed.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of marine surveyors was $92,400
in May 2019.</blockquote>
<hr size="1" />

	<span class="header2">Park Ranger</span><br />
	<img class="job_pic" src="/images/icons/AE/C585042.jpg"
width="100" height="100" border="0" alt="Park Ranger" />
	<span class="header3">Job Description</span>
	<blockquote>A park ranger (or park naturalists) makes sure that visitors and
wildlife are safe in state and national parks. As a park ranger you
would patrol the park.  You would also collect fees, provide
information about the park, and enforce park rules and
regulations.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Workers in this occupation need, at a minimum, a
bachelor's degree in forestry, environmental science, range
management, or a related discipline.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of park rangers was
$62,660 in May 2019.
</blockquote>
<hr size="1" />

	<span class="header2">Zoologist</span><br />
	<img class="job_pic" src="/images/icons/AE/1270.jpg"
width="100" height="100" border="0" alt="Wildlife Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Zoologists study the characteristics of animals,
such as their interactions with other species, reproduction,
diseases, and movement patterns.  For example, they might take blood
samples from animals to assess their levels of nutrition.  Most
zoologists work on research teams with other scientists and
technicians.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Zoologists need a bachelor's degree for entry-
level jobs, but a master's degree is often needed for advancement.
A Ph.D is necessary for most independant research jobs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of zoologists was
$63,270 in May 2019.</blockquote>

<hr size="1" />

<span class="header1">OUTDOOR ACTIVE</span>
<p>Many people with your interests like to work in occupations that
allow them to stay "on the go."  These next occupations do this.</p>

<hr size="1" />

	<span class="header2">Building Inspector</span><br />
	<img class="job_pic" src="/images/icons/AE/43241.jpg"
width="100" height="100" border="0" alt="Building Inspector" />
	<span class="header3">Job Description</span>
	<blockquote>Building inspectors make sure that buildings are
safe.  They work on-site, looking to see that builders follow the
safety codes and other rules set by the government. As a building
inspector you would check to see that the building is built to stay
strong.  You would make sure, for example, that the roof would not
collapse under snow.  You would make sure that there is an easy way
to leave the building in case of a fire.  You would check the
building for flaws and insist that all flaws be fixed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Although requirements vary considerably,
construction and building inspectors should have a thorough
knowledge of construction materials and practices. In some states
construction and building inspectors are required to obtain a
special license or certification, so it is important to check with
the appropriate state agency. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of building inspectors
was $60,710 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Meter Reader</span><br />
	<span class="header3">Job Description</span>
	<blockquote>As a meter reader you would drive through
neighborhoods, stopping at utility meters.  You would check these
meters to see how much water, electricity or natural gas each
household has used.  You would record these figures and report them
to the utility company.  The company would send a bill to each
customer based on these figures.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma and good writing
and math skills for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of meter reader was $42,280
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Construction Worker</span><br />
	<img class="job_pic" src="/images/icons/AE/43191.jpg"
width="100" height="100" border="0" alt="Construction Worker" />
	<span class="header3">Job Description</span>
	<blockquote>A construction worker builds things like houses,
office buildings, and skyscrapers.  If you were a construction
worker, you could be a roofer.  You could frame buildings or you
might dig foundations.  Construction is hard work and a
construction site can be dangerous.  To do construction work you
must be in top physical condition. You must also follow safety
procedures and regulations carefully.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You do not need college courses for this work.
But you must understand basic math and be able to read mechanical
drawings.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of construction workers
was $36,000 in May 2019.</blockquote>

<hr size="1" />


<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 9, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 9, 2020). </blockquote>

</div>
