<span class="header1">Outdoor paired with Technology (AF)</span>

<p>With an "AF" interest, you will want to combine your interest in
open-air occupations with your interest in technologies. You like to
conduct research, employ change and apply what you know to work
settings of the technologies and outdoors.</p>
<p>Many of the occupations in this pairing require that you have
specialized and/or technical training after high school. Many
require college degrees or college level courses.</p>
<p><strong>Courses you may want to take in high school and beyond
(in addition to English & Math):</strong><br />
In high school you should take courses that allow you to continue
to learn about the environment. Life science and earth science
courses will teach you many interesting things about nature.  Look
for opportunities to use technology to discover new things.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Agriculture<br />
			Environmental Sciences<br />
			Health/Nutrition<br />
			Computer Sciences
		</td>
		<td>
			Computer Programming<br />
			Graphic Art/Drafting<br />
			Industrial Technology<br />
			Health Occupations
		</td>
		<td>
			Physical Education<br />
			Business Education<br />
			Technology Education
		</td>
		<td>
			Biology<br />
			Business Math<br />
			Telecommunications
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
that you may find interesting:</strong><br />
If you have time for after-school activities or part-time jobs, make
them count. You will especially enjoy any club or activity that
involves working with some sort of equipment and/or sharing a love
for nature.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Adopt-a-Mile<br />
			Habitat for Humanity<br />
			Library Assistant
		</td>
		<td>
			Athletics<br />
			Audio/visual Services<br />
			Newspaper/Yearbook
		</td>
		<td>
			Parks/Recreation<br />
			Chess Club<br />
			Computer Club<br />
		</td>
		<td>
			Future Farmers of America<br />
			Math/Science Clubs<br />
			ROTC<br />
			Scouts
		</td>
	</tr>
</table>

<p>	<strong>Workplaces that you may wish to consider for a part-
time job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Appliance Repair<br />
			Landscaping<br />
			Camp Counseling
		</td>
		<td>
			Farming<br />
			Logging<br />
			Lumberyards
		</td>
		<td>
			Life Guarding<br />
			Delivery Services
		</td>
		<td>
			Park Services<br />
			Lawn Care
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">AF Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Biotechnology Environmental</span><br />

	<em>Veterinarian<br />
						Aquatic
Biologist<br />
						Ecologist<br />

	Geneticist<br />

	Microbiologist<br />

	Physiologist<br />
						Geological
Oceanographer<br />

	Seismologist<br />
						Stratigrapher</em>
					</td>
					<td width="33%">
						<span
class="header2">Information</span><br />
						<em>Urban
Planner<br />
						Systems
Analyst<br />
						Computer
							<ul>

	<li>Software Engineer</li>

	<li>Programmer</li>

	<li>Technician</li>

	<li>Systems Programmer</li>
							</ul>
						Information Systems
Mgr.<br />
						Applications
Programmer<br />
						User Support
Analyst<br />
						Recording
Engineer</em>
					</td>
					<td width="33%">
						<span
class="header2">Engineering</span><br />

	<em>Engineer<br />
						Electrical
Engineer<br />
						Mechanical
Engineer<br />
						Civil
Engineer<br />
						Chemical
Engineer<br />
						Industrial
Engineer<br />
						Metallurgical
Engineer<br />
						Materials
Engineer<br />
						Medical
Scientist<br />
						Waste
Management<br />
						Water Quality
Technologist</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">NATURE/ANIMALS</span>
<p>If you choose an occupation in this field, you will work
directly with nature and animals. People in these occupations often
work as practical scientists. They discover new information about
nature because they work closely in it.</p>

<hr size="1" />

	<span class="header2">Agricultural
Scientist</span><br />
	<img class="job_pic" src="/images/icons/AF/43207.jpg"
width="100" height="100" border="0" alt="Agricultural Scientist" />
	<span class="header3">Job Description</span>
	<blockquote>An agricultural scientist finds ways to make
farming easier and more productive.  As an agricultural scientist,
you could work to increase plant production and keep farm animals
healthier. You could also work to develop safer pesticides and find
better ways to protect water and soil.  For this work, you need a
strong background in biology and other sciences.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree to be an agricultural scientist. Many earn advanced degrees.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of agriculture scientists
was $65,160 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Zoologist</span><br />
	<img class="job_pic" src="/images/icons/AF/1270.jpg"
width="100" height="100" border="0" alt="Zoologist" />
	<span class="header3">Job Description</span>
	<blockquote>Zoologists study the characteristics of animals,
such as their interactions with other species, reproduction,
diseases, and movement patterns.  For example, they might take blood
samples from animals to assess their levels of nutrition.  Most
zoologists work on research teams with other scientists and
technicians.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Zoologists need a bachelor's degree for entry-
level jobs, but a master's degree is often needed for advancement.
A Ph.D is necessary for most independant research jobs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of zoologists was
$63,270 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Animal Caretaker</span><br />
	<span class="header3">Job Description</span>
	<blockquote>An animal caretaker works with non-farm
animals.  If you were an animal caretaker, you would work in a zoo,
veterinary hospital, pet store or animal shelter.  You would feed
and water the animals.  You would bathe, groom and exercise the
animals too.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most employers have on-the-job training programs
for employees. No college degree is required. There is a need for
more animal caretakers.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of animal caretakers was
$28,590 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>There are occupations that mix a love for the outdoors and an
interest in technology.  Here are three examples.</p>

<hr size="1" />

	<span class="header2">Meteorologist</span><br />
	<img class="job_pic" src="/images/icons/AF/1265.jpg"
width="100" height="100" border="0" alt="Meteorologist" />
	<span class="header3">Job Description</span>
	<blockquote>Meteorologists use computers, radar and
satellites to study the atmosphere.  As a meteorologist, you would
use the data you collect to create weather reports.  These reports
tell people about current conditions.  They also forecast future
weather conditions.  This is an important job.  Weather forecasts
are used to warn  people of severe or dangerous weather.  This
information is important to everybody.  It can help to save lives.
It can also help to save property.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree in meteorology, or in a
related field such as physics or earth science.  If you want to
teach meteorology or conduct research, you would need a Master's
Degree or Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of meteorologists was
$95,380 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Agricultural
Technician</span><br />
	<img class="job_pic" src="/images/icons/AF/1194.jpg"
width="100" height="100" border="0" alt="Agricultural Technician" />
	<span class="header3">Job Description</span>
	<blockquote>An agricultural technician works closely with
agricultural scientists.  If you were an agricultural technician,
you would help these scientists to increase plant production.  You
would also help to see that farm animals were well fed.  You would
spend time in the laboratory and at local farms.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most science technicians need an
associate degree or a certificate in applied science or science-
related technology.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of agriculture
technicians was $41,230 in May 2019.</blockquote>


<hr size="1" />

	<span class="header2">Landscaper</span><br />
	<img class="job_pic" src="/images/icons/AF/43190.jpg"
width="100" height="100" border="0" alt="Landscaper" />
	<span class="header3">Job Description</span>
	<blockquote>Landscapers spend nearly all of their time
outdoors.  If you were a landscaper, you might work as a gardener or
groundskeeper.  You would seed, weed, mow, fertilize grass, and
fertilize and prune shrubs using the many tools of the landscaping
trade. This is a good occupation if you want a business of your
own.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most grounds maintenance workers learn on-the-
job. However, some occupations may require formal training in areas
such as landscape design, horticulture, or business management.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of landscapers was
$30,440 in May 2019.</blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY</span>
<p>Your active, hands-on way of working and interest in how things
work will make you valuable to employers in this occupational
field.</p>

<hr size="1" />

	<span class="header2">Petroleum Engineer</span><br />
	<img class="job_pic" src="/images/icons/AF/1323.jpg"
width="100" height="100" border="0" alt="Petroleum Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>Petroleum and natural gas are found under the
ground.  If you were a petroleum engineer, you would find and
retrieve this petroleum and natural gas. You would need to know
about rocks and minerals and retrieval methods.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree to become
a petroleum engineer. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of petroleum engineers
was $137,720 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Construction Equipment
Operator</span><br />
	<img class="job_pic" src="/images/icons/AF/1396.jpg"
width="100" height="100" border="0" alt="Equipment Operator" />
	<span class="header3">Job Description</span>
	<blockquote>Equipment operators use heavy machinery such as
cranes, bulldozers, and winches to move dirt, wood, or other
materials used in construction.  If you were an equipment operator,
you might work at road paving sites.  You might also work at
industrial and construction sites.  This equipment can be
dangerous.  Safety practices are a big concern.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.
You are more likely to get a job running expensive equipment if you
have taken courses at a vocational school.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of construction equipment
operators was $48,160 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Survival Equipment Specialist of the
Armed Forces (Military)</span><br />
	<span class="header3">Job Description</span>
	<blockquote>A survival equipment specialist makes sure that
equipment such as parachutes, rafts, fire extinguishers, and oxygen
tanks are working well.  In this job, you would inspect safety
equipment before training sessions or military missions. Others'
lives would depend on your work.  You would need to be very thorough
and detailed in performing your duties.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You do not need college courses to be a survival
equipment specialist.  Shop mechanics and the sciences are high
school courses that will help you to get this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the Military isbased on your rank, years of service and occupationalspecialty.</blockquote>
<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 9, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 9, 2020). </blockquote>

</div>
