<span class="header1">Outdoor paired with Public Service (AG)</span>

<p>If you scored high in the "A" and "G" categories, you are
concerned about your planet and the people, animals, and plants that
live on it.  You have a "no-nonsense" approach that ensures that
things get done. You enjoy working on a team, but you can work
alone.  You want to make a difference in the world.</p>
<p>Most occupations in this pairing require at least a Bachelor's
Degree. A Master's Degree or Ph.D. is needed for certain
occupations.</p>
<p>In high school you should take courses that help you understand
the environment and people. Science and social studies courses will
be of particular interest to you.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong></p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Agriculture<br />
			Political Science<br />
			Psychology<br />
			Physical Education
		</td>
		<td>
			Business Law<br />
			Business Ed.<br />
			Sociology<br />
		</td>
		<td>
			Computer Technology<br />
			Biology<br />
			Computer Science<br />
			Environmental Science
		</td>
		<td>
			Government/Civics<br />
			Economics<br />
			Geography<br />
			Industrial Technology
		</td>
		<td>
			World Languages<br />
			Health/Nutrition<br />
			History
		</td>
	</tr>
</table>

<p>If you have time for after-school activities or part-time jobs,
make them count. You will especially enjoy an activity that involves
working with others and/or sharing a love for nature.</p>
<p><strong>Extracurricular / volunteer activities or organizations
that you may find interesting:</strong></p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Adopt-a-Mile<br />
			Habitat for Humanity<br />
			Peer Counselor<br />
			Future Farmers of America
		</td>
		<td>
			Athletics<br />
			Church Activities<br />
			Hospital Volunteer<br />
			Safety Patrol
		</td>
		<td>
			Scouts<br />
			Youth Organizations<br />
			Camp Counselor<br />
			Martial Arts
		</td>
		<td>
			Parks/Recreation<br />
			Chess Club<br />
			ROTC</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Camp Counselor<br />
			Recreation Departments<br />
			Farming
		</td>
		<td>
			Lawn Care/Landscaping<br />
			Park Services<br />
			Life Guarding
		</td>
		<td>
			Lumberyards<br />
			Youth Coaching
		</td>
		<td>
			Hospitals<br />
			Special Olympics
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">AG Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Community Service</span><br />

	<em>Veterinarian<br />
						Urban
Planner<br />
						Recreation
Administrator<br />

	Preservationist<br />
						Land
Developer<br />
						Park
Ranger<br />
						Public Utilities
Manager<br />
						Police
Officer<br />

	Firefighter<br />

	Recyclist<br />
						Security
Guard<br />
						Postal
Worker<br />
						Public
Transportation Operator</em>
					</td>
					<td width="33%">
						<span
class="header2">Nature</span><br />

	<em>Horticulturist<br />
						Rangeland
Specialist<br />

	Toxicologist<br />

	Surveyor<br />
						Tugboat
Captain<br />
						Range
Inspector<br />
						Park
Inspector<br />
						Organic
Farmer<br />
						Survival
Trainer<br />
						Grounds
Maintenance
Supervisor<br />
						Nursery
Manager<br />
						Animal
Caretaker</em>
					</td>
					<td width="33%">
						<span
class="header2">Environment</span><br />

	<em>Environmental
Lawyer<br />

	Geologist<br />
						Civil
Engineer<br />
						Pollution
Engineer<br />

	Environmentalist<br />
						Waste Management
Technician<br />
						Water Treatment
Plant Operator<br />
						Power Plant
Operator<br />
						Forestry
Technician<br />
						Forestry
Worker</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr  size="1" />

<span class="header1">COMMUNITY SERVICE</span>
<p>Your caring nature can lead you to many exciting occupations that
will allow you to serve your community.  Here are some examples.</p>

<hr  size="1" />

	<span class="header2">Recreation
Administrator</span><br />
	<img class="job_pic" src="/images/icons/AG/C553057.jpg"
width="100" height="100" border="0" alt="Recreation Administrator" />
	<span class="header3">Job Description</span>
	<blockquote>Recreation administrators (also called recreation coordinators or activity directors) plan recreational
activities.  They also see that these activities go smoothly and
that people who participate have a good time.  As a recreation
administrator, you might plan a craft class for a group of eight-
year-olds. You might also plan physical exercise programs or travel
groups for people of all ages.  You might even work at a beach
resort or on a cruise ship.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to become
a recreation administrator.  You also need to be creative and
enthusiastic.  To get experience and see if you would like this job,
get a part-time job as a camp counselor or a youth
organizer.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of recreation
administrators was $26,350 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Park Ranger</span><br />
	<img class="job_pic" src="/images/icons/AG/C585042.jpg"
width="100" height="100" border="0" alt="Park Ranger" />
	<span class="header3">Job Description</span>
	<blockquote>A park ranger (or park naturalist) makes sure that visitors and
wildlife are safe in state and national parks. As a park ranger, you
would patrol the park to make sure that all is well. You would also
do other things such as collect fees, give park information, and
enforce park rules and regulations.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Workers in this occupation need, at a minimum, a
bachelor's degree in forestry, environmental science, range
management, or a related discipline.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of park rangers was
$62,660 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Firefighter</span><br />
	<img class="job_pic" src="/images/icons/AG/1392.jpg"
width="100" height="100" border="0" alt="Firefighter" />
	<span class="header3">Job Description</span>
	<blockquote>Firefighters control and put out fires that
threaten lives or property.  As a firefighter, you would have to act
quickly and responsibly in the middle of a fire or other emergency.
Since most firefighters must now have EMT (Emergency Medical
Technician) credentials, in addition to learning CPR and first aid,
you would have to take classes necessary for the EMT
designation.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You usually do not need a college degree to
become a firefighter.  But you must pass a written test and a test
of physical strength.  Firefighters need to understand chemistry, as
certain chemical mixtures can cause a fire or explosion.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of firefighters was
$50,850 in May 2019.
</blockquote>

<hr size="1" />

<span class="header1">NATURE</span>
<p>The occupations in this field are like those found under the
Community Service field. They help nature and people.</p>

<hr size="1" />

	<span class="header2">Rangeland Specialist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Rangelands are special types of environments
found in the United States. A rangeland specialist (also known as a conservationist or range manager) works to keep the
delicate rangeland ecosystem safe. As a rangeland specialist, you
would have two tasks.  You would plan programs that allowed visitors
to understand and enjoy the rangeland.  You would see that these
programs did not disturb the wildlife.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to become
a rangeland specialist.  Having a Master's Degree will help you to
get a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of rangeland specialists was $62,660
in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Organic Farmer</span><br />
	<img class="job_pic" src="/images/icons/AG/1336.jpg"
width="100" height="100" border="0" alt="Organic Farmer" />
	<span class="header3">Job Description</span>
	<blockquote>An organic farmer grows fruits and vegetables
without the use of pesticides or other chemicals.  If you are
concerned about the chemicals used to grow our food and want to
become a farmer, you might become an organic farmer.  As an organic
farmer, you would work outdoors, plowing, sowing, and harvesting
your crop.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some farmers take college level courses and even
get degrees in agricultural science.  But you can farm without a
degree.  Experience is often the best way to learn about crops and
farming.  Participate in agricultural clubs or work in plant
nurseries or on a farm to gain this experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of organic farmers was
$71,160 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Forestry Worker</span><br />
	<img class="job_pic" src="/images/icons/AG/1345.jpg"
width="100" height="100" border="0" alt="Logger" />
	<span class="header3">Job Description</span>
	<blockquote>A forestry worker works as part of a team to cut
down trees for lumber. A forestry team is made up of a faller, who
cuts down the trees; a bucker, who trims off the branches; and a
grader, who inspects and measures the logs.  As a forestry worker,
you may do any of these jobs.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You do not need a college degree to become a
logger. You do need to be strong and a hard worker.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of forestry workers was
$31,770 in May 2019.</blockquote>
<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>If you are interested in the scientific and technical parts of
nature, you will want to consider the occupations in this field.</p>

<hr size="1" />

	<span class="header2">Toxicologist</span><br />
	<img class="job_pic" src="/images/icons/AG/43142.jpg"
width="100" height="100" border="0" alt="Toxicologist" />
	<span class="header3">Job Description</span>
	<blockquote>A toxicologist studies the effects of chemicals
on people and other living things.  As a toxicologist, you might
study the effects of household bleach on the water supply. You might
be concerned with pollutants and pesticides.  You might focus on
toxic dumpsites.  You would report your findings to the proper
authorities and help to eliminate any problems.  You must have a
broad understanding of chemistry and biology to do this job
well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most medical scientists, such as toxicologists, need a Ph.D. in a
biological science; some hold a medical degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of toxicologists was
$88,790 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Water Treatment Plant
Operator</span><br />
	<span class="header3">Job Description</span>
	<blockquote>As a water treatment plant operator, you would
use equipment to remove pollutants from water.  Then you would see
that the water was returned to the environment. Since computers are
essential to doing this job, you would need good computer
skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma to become a water
treatment plant operator.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of water treatment plant
operators was $47,760 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Power Plant Operator</span><br />
	<!-- <img class="job_pic" src="/images/icons/AG/1345.jpg"
width="100" height="100" border="0" alt="Power Plant Operator" /> -->
	<span class="header3">Job Description</span>
	<blockquote>If you were a power plant operator, you would
control the machines that make the electricity we need. The most
important part of your job would be making sure the correct voltage
is flowing through the machines. When incorrect voltage flows
through the machines, it causes a blackout.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma and extensive on-the-job training to become a power
plant operator.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of power plant operators
was $85,950 in May 2019.</blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 9, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 9, 2020). </blockquote>

</div>
