<span class="header1">Outdoor paired with Science/Mathematics (AH)
</span>

<p>If you scored high in the "A" and "H" categories, you can play an
important role in understanding, protecting and exploring the laws
of nature. People with your interests have contributed much to our
development, discovery and application of knowledge in this
area. "AH" people are usually excellent thinkers and appliers of
their knowledge. They are also creative scientists who have a great
respect for nature. They often find new ways to solve old problems
in all fields.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree and many will require a master's degree or Ph.D.</p>
<p><strong>Courses you may want to take in high school and beyond
(in addition to English & Math):</strong><br />
In high school you should take courses in math and science. Courses
about the outdoors and nature will be of great interest to you. They
will also help prepare you for a possible career in this field.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Agriculture<br />
			Chemistry<br />
			Business Math
		</td>
		<td>
			Calculus<br />
			Health/Nutrition<br />
			Sociology
		</td>
		<td>
			Psychology<br />
			Technology Education<br />
			Environmental Science
		</td>
		<td>
			Trigonometry<br />
			Physics<br />
			Business Education
		</td>
		<td>
			Biology<br />
			Economics<br />
			Telecommunications
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interest:</strong><br />
If you have time for after-school activities or part-time jobs, make
them count. You may especially enjoy a club or activity where you can
share your love for nature and use your thinking skills.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Adopt-a-Mile<br />
			Habitat for Humanity<br />
			Computer Club<br />
			Future Farmers of America
		</td>
		<td>
			Athletics<br />
			Math/Science Club<br />
			Tutoring
		</td>
		<td>
			Scouts<br />
			Hospital Volunteer<br />
			ROTC<br />
			Animal Care
		</td>
		<td>
			Parks/Recreation<br />
			Environmental Activities<br />
			Martial Arts<br />
			Chess Club
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Animal Care<br />
			Landscaping<br />
			Archeological Projects
		</td>
		<td>
			Farming<br />
			Park Services<br />
			Theaters
		</td>
		<td>
			Medical Offices<br />
			Computer Services
		</td>
		<td>
			Veterinary Offices<br />
			Lawn Care
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">AH Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="25%">
						<span
class="header2">Medical</span><br />

	<em>Professor<br />
						Coroner<br />
						Sports
Psychologist<br />

	Veterinarian<br />
						Horticultural
Therapist<br />
						Scientist
							<ul>

	<li>Animal</li>

	<li>Botanist</li>

	<li>Ecologist</li>

	<li>Food</li>
							</ul>
						Recreational
Therapist<br />

	Researcher<br />
						Meat Inspector</em>
					</td>
					<td width="25%">
						<span
class="header2">Nature Sciences</span><br />

	<em>Microbiologist<br />

	Archaeologist<br />
						Geoscientist
							<ul>

	<li>Petroleum Geologist</li>

	<li>Mineralogist</li>

	<li>Paleontologist</li>

	<li>Oceanographer</li>
							</ul>
						Ecologist<br />
						Conservationist
							<ul>

	<li>Soil</li>

	<li>Wildlife</li>
							</ul>
						Political Scientist<br />
Climatologist<br />

	Firefighter<br />
						Tree
Farmer<br />
						Planetarium
Technician</em>
					</td>
					<td width="25%">
						<span
class="header2">Environment</span><br />
						<em>Engineer
							<ul>

	<li>Environmental</li>

	<li>Geotechnical</li>

	<li>Mining</li>

	<li>Petroleum</li>

	<li>Waste Management</li>
							</ul>
						Hazardous Materials
Specialist<br />
						Landscape
Architect<br />
						Environmental Health
Inspector<br />
						Coast
Guard<br />
						Surveyor<br />
						Water Treatment
Plant Operator<br />
						Engineering
Technician<br />
						Mining</em>
					</td>
					<td width="25%">
						<span
class="header2">Math</span><br />

	<em>Astronomer<br />
							<ul>

	<li>Astrophysicist</li>

	<li>Solar</li>
							</ul>
						Engineer
							<ul>

	<li>Aeronautical</li>

	<li>Industrial</li>
							</ul>
						Financial
Officer<br />
						Military Budget
Officer<br />
						Bio-
statistician<br />

	Statistician<br />
						Surveyor<br />
						Mapping
Scientist<br />

	Researcher<br />
						Technician
							<ul>

	<li>Airport Computer

	<li>Mapping</li>
							</ul></em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">MEDICAL</span>
<p>Your ability to reason and your no-nonsense approach to science
can help you to become an expert in this field.  Observation and problem solving are very important. Here are
three occupations found in this field.</p>

<hr size="1" />

	<span class="header2">Recreational
Therapist</span><br />
	<img class="job_pic" src="/images/icons/AH/43033.jpg"
width="100" height="100" border="0" alt="Recreational Therapist" />
	<span class="header3">Job Description</span>
	<blockquote>Recreational therapists plan, direct, and
coordinate recreation programs for people with disabilities or
illnesses. They use a variety of techniques, including arts and
crafts, drama, music, dance, sports, games, and field trips. These
programs help maintain or improve a client's physical and emotional
well-being.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most recreational therapists need a bachelor's
degree in therapeutic recreation or a related field. Though less
common, associate's, master's, or doctoral degrees are also
available.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of recreational
therapists was $48,220 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Animal Scientist</span><br />
	<img class="job_pic" src="/images/icons/AH/1009.jpg"
width="100" height="100" border="0" alt="Animal Scientist" />
	<span class="header3">Job Description</span>
	<blockquote>Animal scientists conduct research to improve
the breeding and health of livestock and other farm animals.  As an
animal scientist, you would look for ways farmers and cattle
ranchers could keep their animals healthy through better nutrition
and disease control. For example, you might find a vaccine that
helps prevent a disease found in cattle. You might work to solve
problems in breeding.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most biological scientists need a Ph.D. degree
in biology or one of its subfields to work in research or
development positions.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of animal scientists was
$60,300 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Veterinary
Technician</span><br />
	<img class="job_pic" src="/images/icons/AH/43131.jpg"
width="100" height="100" border="0" alt="Veterinary Technician" />
	<span class="header3">Job Description</span>
	<blockquote>A veterinary technician works in animal
hospitals and clinics.  In this job, you would work closely with
veterinarians.  You would help conduct laboratory tests.  You would
also help dress wounds and prepare animals for surgery.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To be a veterinary technician, you will need an associate degree, vocational training or on-the-job training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of veterinary technicians
was $35,320 in May 2019.</blockquote>

<hr size="1" />

<span class="header1">NATURE</span>
<p>Science thrives on curiosity. We know about the world and its
history because there were people who were curious. The following
occupations need people who aren't afraid to ask questions and who
like finding answers.</p>

<hr size="1" />

	<span class="header2">Oceanographer</span><br />
	<img class="job_pic" src="/images/icons/AH/C511037.jpg"
width="100" height="100" border="0" alt="Oceanographer" />
	<span class="header3">Job Description</span>
	<blockquote>Oceanographers (geoscientists) are scientists
who study the ocean. As an oceanographer, you might study the
ocean's movements.  You might study the plants and animals that live
under the ocean's surface.  You might focus on what lies on the
ocean floor.  The oceans still hold many mysteries.  As an
oceanographer, you would search for what is unknown.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A master's degree is the primary educational
requirement for most entry-level positions.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of oceanographers was
$92,040 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Soil Conservationist</span><br />
	<img class="job_pic" src="/images/icons/AH/43173.jpg"
width="100" height="100" border="0" alt="Soil Conservationist" />
	<span class="header3">Job Description</span>
	<blockquote>A soil conservationist protects the soil needed
for plant and crop growth. As a soil conservationist, you would work
with other scientists.  Your goal would be to find ways to get the
most crops from the land without hurting the environment. You would
find solutions to problems such as erosion and share your solutions
with farmers, ranchers, and government agencies.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You will need at least a bachelor's degree to
get a job. In this area, the more you know and the more experience
you have, the better your chances for employment. Your part-time
jobs and extracurricular activities may play an important role in
your job prospects.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of soil conservationists
was $62,660 in May 2019.</blockquote>
<hr size="1" />

	<span class="header2">Climatologist</span><br />
	<img class="job_pic" src="/images/icons/AH/1053.jpg"
width="100" height="100" border="0" alt="Climatologist" />
	<span class="header3">Job Description</span>
	<blockquote>Climatologists (atmospheric scientists) study
the earth's climates.  As a climatologist, you would look at past
weather records and research weather pattern changes to determine
and predict area climates. You might study the effect of people's
activities on the atmosphere and the effect of pollution on our
air.  Your work could contribute to maps that show the world's
climates.  It could contribute to other reports as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree to work as
a climatologist.  In this occupation, the more education you have,
the better off you will be.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of climatologists was
$95,380 in May 2019.</blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>A desire to help improve our environment plays an important role
in these occupations.</p>

<hr size="1" />

	<span class="header2">Landscape Architect</span><br />
	<img class="job_pic" src="/images/icons/AH/43236.jpg"
width="100" height="100" border="0" alt="Landscape Architect" />
	<span class="header3">Job Description</span>
	<blockquote>Around office buildings and malls are beautiful
areas of flowers and trees. During construction, these areas are
nothing more than mud or dirt. The person who plans the landscaping
around a new building is a landscape architect. As a landscape
architect, you would look over the area surrounding a project or
building site.  You would think of a way to create a beautiful natural looking environment. To succeed in this job, you
must appreciate nature and have an "eye" for beauty.  You must also
have the technical skills to draw up plans that can be followed
easily.  Finally, you must be able to "see" how the area will look
after your plans are followed before the project begins.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree in landscape
architecture. You must also pass an exam to earn licensure.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of landscape architects
was $69,360 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Environmental Health
Inspector</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Environmental health inspectors (sometimes called occupational health and safety specialists) usually work for
a state government.  In this job, you would work to keep our food,
water and air clean and safe.  You would monitor factories,
businesses, and hospitals to be sure that they obeyed government
safety regulations that help to keep our environment
safe.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most states agencies prefer hiring people who
have bachelor's degrees, and many encourage employees to pass a certification exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of environmental health
inspectors was $74,100 in May 2019.</blockquote>

<hr size="1" />

<span class="header1">MATH</span>
<p>It takes a person who is good at reasoning and is very curious to
fill positions in this field.  Here are three occupations that you
might find interesting.</p>

<hr size="1" />

	<span class="header2">Astrophysicist/Solar
Astronomer</span><br />
	<img class="job_pic" src="/images/icons/AH/1277.jpg"
width="100" height="100" border="0" alt="Astrophysicist/Solar
Astronomer" />
	<span class="header3">Job Description</span>
	<blockquote>If you are fascinated by the stars in the sky
and the solar system, you might become an astrophysicist or a solar
astronomer.  People in these professions track, study and review
data related to the stars and planets.  You need an imagination to
work in this area.  You need good math skills too.</blockquote>
	<span class="header3">Education</span>
	<blockquote>For most occupations in the field of astronomy,
a Ph.D. is required.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of astrophysicists was
$122,220 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Surveyor</span><br />
	<img class="job_pic" src="/images/icons/AH/43169.jpg"
width="100" height="100" border="0" alt="Surveyor" />
	<span class="header3">Job Description</span>
	<blockquote>If you are a down to earth person and enjoy
working outdoors, you might become a surveyor.  As a surveyor, you
would chart, study, measure, and map the earth's surface. This
occupation requires someone who is detailed and precise.</blockquote>
	<span class="header3">Education</span>
	<blockquote>In most states, a surveyor needs a four-year
degree in surveying or civil engineering. To provide services to the public, a license is required.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of surveyors was $63,420
in May 2019.</blockquote>
<hr size="1" />

	<span class="header2">Mapping Technician</span><br />
	<span class="header3">Job Description</span>
	<blockquote>A mapping technician helps a surveyor. As a
mapping technician, you would work with a team headed by a
surveyor.  You would handle and use the surveying instruments used
to measure distance and altitude.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You can get on-the-job training; however, it is
easier to get a job if you complete a vocational tech program.
There are one-year, two-year, and three-year programs for those who
want to study mapping technology.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of mapping technicians
was $45,010 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 9, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online</i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 9, 2020). </blockquote>

</div>

