<span class="header1">Outdoor paired with Social/Helping (AI)</span>

<p>Your high scores in "A" and "I" show that you have several
characteristics that can help promote the welfare of people. You are
practical, curious, and people-oriented with a love of the outdoors.
You like to offer support to people who are having difficulties in
learning and adjusting to new and different situations. You also
have an interest in teaching, consulting and counseling for improved
ways to become healthier physically and mentally. You promote a
safer and cleaner environment and have respect for those
environments and individuals.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree.  It is helpful to have a master's degree or a Ph.D. in some
of the occupations.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that help you understand
people. Any courses that deal with the outdoors and nature will be
of great interest to you and will help prepare you for possible
career opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Agriculture<br />
			Religion<br />
			Psychology<br />
			Sociology
		</td>
		<td>
			Computer Sciences<br />
			Speech & Communications<br />
			Economics<br />
			Environmental Science
		</td>
		<td>
			Health/Nutrition<br />
			Biology<br />
			Home Economics<br />
			Early Childhood
			Education<br />
		</td>
		<td>
			Law<br />
			Education<br />
			Business Ed.<br />
			Logic
		</td>
		<td>
			Physical Education<br />
			History<br />
			Public Relations<br />
			Life Science
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
that you might find interesting:</strong><br />
If you have time for after-school activities or part-time jobs, make
them count. You will especially enjoy any club or activity where you
can share your love for nature and use your people skills.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Adopt-a-Mile<br />
			Habitat for Humanity<br />
			Tutoring<br />
			Animal Care
		</td>
		<td>
			Athletics<br />
			Childcare/Eldercare<br />
			Church Activities<br />
			Future Farmers of America
		</td>
		<td>
			Scouts<br />
			Hospital Volunteer<br />
			Teaching Assistant<br />
			Camp Counselor
		</td>
		<td>
			Parks/Recreation<br />
			Peer Counselor<br />
			ROTC<br />
			Martial Arts
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Day Care Centers<br />
			Recreation Departments<br />
			Life Guard
		</td>
		<td>
			Park Services<br />
			Summer Camps<br />
			Retirement Homes
		</td>
		<td>
			Special Olympic<br />
			Landscaping/Lawn Care
		</td>
		<td>
			Farming<br />
			Lumberyard
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">AI Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Community Service</span><br />
						<em>Teacher
							<ul>

	<li>Agriculture</li>

	<li>Biology</li>

	<li>Industrial Arts</li>

	<li>Physical Education</li>
							</ul>
						Horticultural
Therapist<br />
						Recreation
Therapist<br />
						Peace Corp
Worker<br />
						Postal
Worker<br />
						Real Estate
Appraiser<br />
						Bus Driver</em>
					</td>
					<td width="33%">
						<span
class="header2">Nature</span><br />

	<em>Veterinarian<br />
						Pet
Psychologist<br />

	Ecologist<br />
						Zoo
Manager<br />

	Forester<br />
						Wildlife
Rehabilitator<br />
						Recreational
Therapist<br />
						Park
Ranger<br />
						Nature
Guide<br />

	Forestry<br />
						Animal Lab
Technician</em>
					</td>
					<td width="33%">
						<span
class="header2">Environment</span><br />
						<em>Civil
Engineer<br />
						City
Planner<br />

	Surveyor<br />
						Hazardous Waste
Management Professional<br />
						Environmental
Heath
Specialist<br />

	Firefighter<br />
						Emergency
Management
Specialist<br />
						Recreation
Specialist<br />
						Sanitation
Engineer</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">COMMUNITY SERVICE</span>
<p>There are many occupations that combine an interest in nature and
the environment with helping others.</p>

<hr size="1" />

	<span class="header2">Recreational Therapist</span><br />
	<img class="job_pic" src="/images/icons/AI/18272.jpg"
width="100" height="100" border="0" alt="Recreation Therapist" />
	<span class="header3">Job Description</span>
	<blockquote>If you want to make a difference in people's
lives, you might become a recreational therapist.  Recreational
therapists work as members of a medical team. They use nature,
dance, art, games, and music to help patients keep their spirits up
as they go through a serious illness or trauma.  They help them to
regain self-confidence as they recover.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree to work as a recreational therapist. Some employers want certified therapists only. To
be certified you need to pass the required state or board
exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of recreational therapists
was $48,220 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Postal Worker</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Anyone who works at the post office is a postal
worker. As a postal worker, there would be many jobs that you can
do.  For example, you could be a mail carrier, delivering mail to
homes and businesses.  You could also become a mail sorter and
bagger.  There are many other jobs as well.  They require different
levels of education and skill.  All postal workers must be able to
get along with people.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A postal worker does not necessarily need a
college degree, but a high school diploma is required. Also a
written exam must be passed.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of postal workers was
$52,060 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Bus Driver</span><br />
	<!-- <img class="job_pic" src="/images/icons/AI/C512076.jpg"
width="100" height="100" border="0" alt="Bus Driver" /> -->
	<span class="header3">Job Description</span>
	<blockquote>If you live in a city that has public
transportation, you are probably familiar with riding a bus to
places in the city. A bus driver makes sure that others arrive at
their jobs or other destinations safely. To be a bus driver, you
must be a responsible person and enjoy being with people. You must
also be an excellent driver.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Each state has specific guidelines that a person
must follow to become a bus driver. Most states require drivers to
pass several written exams and to have a high school
diploma.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of city bus drivers was
$43,030 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">NATURE</span>
<p>Because people with an "AI" interest pairing are practical,
curious, and helpful, many go into occupations in nature and
science. Here are three occupations for you to consider.</p>

<hr size="1" />

	<span class="header2">Veterinarian</span><br />
	<img class="job_pic" src="/images/icons/AI/43132.jpg"
width="100" height="100" border="0" alt="Veterinarian" />
	<span class="header3">Job Description</span>
	<blockquote>Veterinarians care for sick and injured
animals.  If you love animals and are good at science, you might
become a veterinarian. In this job, you would diagnose what was
wrong with animals.  You would vaccinate them against disease.  You
would tell people how to look after their animals and keep them free
from injury or disease.  If you like looking for new ways to treat
animals and control diseases, you could do research in this
area.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A veterinarian must have a license and must have
a Doctor of Veterinary Medicine degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of veterinarians was
$95,460 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Ecologist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>An ecologist is a scientist who studies the
effect that people and animals have on the earth's environment.  If
you are concerned about harm to the environment and have good
computer skills, this may be a good job for you.  As an
environmentalist, you would conduct field studies.  You would also
work in laboratories.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree to become an
ecologist.  Most employers look for a master's degree and
experience.  To get experience, volunteer with groups who work to
protect the environment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of ecologists was $71,360
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Zoologist</span><br />
	<img class="job_pic" src="/images/icons/AI/1270.jpg"
width="100" height="100" border="0" alt="Wildlife Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Zoologists study the characteristics of animals,
such as their interactions with other species, reproduction,
diseases, and movement patterns. For example, they might take blood
samples from animals to assess their levels of nutrition. Most
zoologists work on research teams with other scientists and
technicians. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Zoologists need a bachelor's degree for entry-
level jobs, but a master's degree is often needed for advancement. A
Ph.D. is necessary for most independent research jobs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of zoologists was $63,270
in May 2019. </blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>Protecting our planet is very important to our future. The
occupations in this field focus on keeping the environment clean and
safe.</p>

<hr size="1" />

	<span class="header2">Civil Engineer</span><br />
	<img class="job_pic" src="/images/icons/AI/43243.jpg"
width="100" height="100" border="0" alt="Civil Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>The word "civil" describes anything that has to
do with a city or with civilization. A civil engineer plans and
builds structures that make our lives easier. As a civil engineer,
you would plan and oversee the building of roads, bridges, and
airports. You would also make sure that the structures that were
built were safe for people to use.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree to become a civil
engineer. Many people enter into this field with a master's degree.
Civil engineers can work in several specialty fields.  Each has its
own education requirements.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of civil engineers was
$87,060 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Hazardous Substance Engineer</span><br />
	<img class="job_pic" src="/images/icons/AI/43020.jpg"
width="100" height="100" border="0" alt="Hazardous Waste Management
Professional" />
	<span class="header3">Job Description</span>
	<blockquote>Hazardous waste has become a problem. Factories
and manufacturing plants discard harmful waste materials.  These
materials get into the environment.  They  poison plants and
animals.  Hazardous Substance Engineers (also called environmental engineers) use their
knowledge of the physical makeup and history of the Earth to protect
the environment, study the properties of underground and surface
waters, locate water and energy resources, predict water-related
geologic hazards, and provide environmental site assessments and
advice on hazardous-waste-site remediation.

</blockquote>
	<span class="header3">Education</span>
	<blockquote>You can enter this field with a bachelor's
degree.  Many people have their master's degree. Education is
important in this line of work. The more you have, the better your
chances for getting a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of hazardous waste
management professionals was $88,860 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Emergency Management
Specialist</span><br />
	<img class="job_pic" src="/images/icons/AI/M34.jpg"
width="100" height="100" border="0" alt="Emergency Management
Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>Emergency management specialists work for the 
military, other government organizations, hospitals and private companies.  If you were a specialist, you would develop and oversee
plans for disaster relief if there should be a national, regional or
state emergency. You would train others to provide this relief.  You
would also tell people what to do if there was an
emergency.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The military provides training to people who
want to work in this occupation. On the other hand, if you are a civilian, you typically need a bachelor's degree to work as an emergency management specialist. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of emergency management
	specialists was $74,590 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 9, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 9, 2020). </blockquote>

</div>
