<span class="header1">Arts/Communications paired with
Business/Management (BC)</span>

<p>A "BC" pairing indicates that you are a "fun" person. You are
able to work with many different types of people and, more than
likely, they enjoy working with you. One of your assets is your
ability to appreciate others for who they are and what they add to a
project. You also can work on several tasks at one time. You don't
need much direction on how to complete a task or assignment because
you combine creativity with the ability to get things done. You are
likely to be very dedicated to your work.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree. Some require post high school courses.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to Math & English):</strong><br />
In high school you will want to take classes that will help you
express yourself better and help you understand others. Writing
courses will be appropriate. Also, you might consider taking public
speaking. Some business courses will help you learn how to get
things done quickly.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting<br />
			Speech & Communication<br />
			Art/Music<br />
			Economics
		</td>
		<td>
			Business Law<br />
			Advertising<br />
			Computer Science<br />
			Government/Civics
		</td>
		<td>
			Computer Technology<br />
			Marketing & Advertising<br />
			Graphic Arts<br />
			Logic
		</td>
		<td>
			Language<br />
			Psychology<br />
			Public Relations<br />
			Political Science
		</td>
		<td>
			Photography<br />
			Sociology<br />
			History<br />
			Business Education
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
Experience is an important thing! If you are looking for a fun
activity or a part-time job, consider places where communicating
with others is a focus. Don't forget to find a place where you can
show how responsible you are.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Drama/Theatre<br />
			Debate Team<br />
			Junior Achievement<br />
			Yearbook
		</td>
		<td>
			Band/Chorus<br />
			Photography Club<br />
			Class Officer<br />
			Radio/TV Activities
		</td>
		<td>
			Newspaper/Yearbook<br />
			Audio/Visual Services<br />
			Computer Activities<br />
			Future Business Leaders
		</td>
		<td>
			Language Club<br />
			Exchange Programs<br />
			Community Volunteer
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job.</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting Firms<br />
			Advertising Agencies<br />
			Office Temporary Services<br />
		</td>
		<td>
			Libraries<br />
			Newspaper Publisher<br />
			Repair Services
		</td>
		<td>
			Radio/TV Studios<br />
			Receptionist<br />
			Graphic Design Firms
		</td>
		<td>
			Restaurant<br />
			Telephone Sales
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">BC Career
Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%"
align="left"><strong>More People Oriented</strong></td>
					<td width="33%"
align="center"><strong><----------></strong></td>
					<td width="33%"
align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0"
cellspacing="0" height="400">
				<tr align="center"
height="33%"><td><strong>More<br /></strong></td></tr>
				<tr align="center"
height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center"
height="33%"><td><strong><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span
class="header2">Creative Business</span><br /><br />
						<em>Art
Director<br /><br />
						Chef<br /><br />

	Illustrator<br /><br />
						Graphic
Artist<br /><br />
						Art
Dealer<br /><br />
						Interior
Designer<br /><br />

	Buyer/Merchandiser<br /><br />

	Restaurateur<br /><br />
						Wedding
Consultant<br /><br />
						Fashion
Coordinator<br /><br />
						Hair Designer</em>
					</td>
					<td width="33%">
						<span
class="header2">Communications Business</span><br /><br />
						<em>Public Relations
Specialist<br /><br />
						Publicist/Press
Agent<br /><br />
						Television
Broadcaster<br /><br />
						Advertising
Production Manager<br /><br />
						Media Production
Specialist<br /><br />
						Advertising
Copywriter<br /><br />
						Talk Show
Host<br /><br />
						Disc
Jockey<br /><br />
						Radio/TV Traffic
Manager<br /><br />
						Photographer</em>
					</td>
					<td width="33%">
						<span
class="header2">Entertainment Business</span><br /><br />
						<em>Book Publishing
Professional<br /><br />
						Media
Specialist<br /><br />

	Photojournalist<br /><br />
						Television Set
Director<br /><br />
						Video Production
Assistant<br /><br />
						Crossword Puzzle
Maker<br /><br />
						Technician
							<ul>

	<li>Media Production</li>

	<li>Design</li>

	<li>Stage</li>
							</ul>
						Production
Assistant</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">CREATIVE BUSINESS</span>
<p>You can be successful in this field if you have a talent and can
manage business matters yourself. This field combines artistic
talent with practical business sense.</p>

<hr size="1" />

	<span class="header2">Chef</span><br /><br />
	<img class="job_pic" src="/images/icons/BC/43009.jpg"
width="100" height="100" border="0" alt="Chef" />
	<span class="header3">Job Description</span>
	<blockquote>If you became a chef, you would use your
creativity to prepare new kinds of dishes or meals for others to
eat. You would work in a kitchen creating new recipes, preparing the
meals, and overseeing the staff.  Creativity is important to a
chef.</blockquote>
	<span class="header3">Education</span>
	<blockquote>No college degree is needed.  Most chefs learn
their craft at schools called "culinary institutes."  Chefs who do
not train at a culinary institute are put through a tough on-the-job
training program while working in a kitchen at another
job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of chefs was $43,180 in
May 2016. </blockquote>

<hr size="1" />

	<span class="header2">Illustrator</span><br /><br />
	<img class="job_pic" src="/images/icons/BC/43312.jpg"
width="100" height="100" border="0" alt="Illustrator" />
	<span class="header3">Job Description</span>
	<blockquote>Illustrators draw or paint pictures that go with
somebody else's words.  Their goal is to "add to" the appeal or
impact of the words.  Their work can be found in newspapers,
magazines, books, and greeting cards.  It can be found in TV
commercials as well.  As an illustrator, you would be most likely to
find work with an advertising agency or a publishing company.  But
other organizations hire illustrators too.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most illustrators have had some post high school
courses. A bachelor's degree from a college, university, or an art
school is a definite advantage.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>According to the job search website, indeed.com, the
	median annual wage of illustrators was $46,844 in February 2018. </blockquote>

<hr size="1" />

	<span class="header2">Interior Designer</span><br /><br />
	<img class="job_pic" src="/images/icons/BC/43032.jpg"
width="100" height="100" border="0" alt="Interior Designer" />
	<span class="header3">Job Description</span>
	<blockquote>If you have a "knack" for making a room look its
best, you might become an interior designer. Interior designers help
their clients decorate the inside of homes, offices, and
businesses.  In this job, you would decorate rooms working within a
budget. To do this, you would have to know the best prices on
furniture, drapes, and room accessories.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need to complete a three to four-year
program in interior designing.  You may want to join a
professional association to find a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of interior designers was
$49,810 in May 2016. </blockquote>

<hr size="1" />

<span class="header1">COMMUNICATIONS BUSINESS</span>
<p>The communication business needs people who can perform on and
off the air. In this occupational field, you must have specialized
knowledge in an area such as politics, art, sports, or business.
Here are three examples.</p>

<hr size="1" />

	<span class="header2">News Reporter</span><br /><br />
	<img class="job_pic" src="/images/icons/BC/C506027.jpg"
width="100" height="100" border="0" alt="News Reporter" />
	<span class="header3">Job Description</span>
	<blockquote>A news reporter is responsible for putting the
news or other programming on the air. As a news reporter, you would
probably begin your career by working behind the scenes.  It is very
tough to become an "on air" reporter.  People are usually
promoted into these positions after they have proven they can
do "off air" work.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a degree in journalism or
communications to work as a copywriter, the first job of a
news reporter. The more experience you have around a studio, the
better your chances to do "on air" work.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of news reporters was
$38,870 in May 2016. </blockquote>

<hr size="1" />

	<span class="header2">Public Relations
Manager/Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/BC/C1737_31.jpg"
width="100" height="100" border="0" alt="Advertising Copywriter" />
	<span class="header3">Job Description</span>
	<blockquote>If you like the idea of writing TV commercials
or creating ads for magazines, you might become a Public Relations
Manager or Specialist.  You need to love to write and be good at
it.  You also need to work well under pressure.  Studios are fast
paced.  You must be able to work in a hectic atmosphere.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree in public
relations, journalism, communications, English, or business to
become a Public Relations Manager/Specialist.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of Public Relations
Manager/Specialist was $58,020 in May 2016.</blockquote>

<hr size="1" />

<span class="header1">ENTERTAINMENT BUSINESS</span>
<p>The occupations in this field allow people to work "behind the
scenes" in show business. To be successful in this field you must
understand business and have good people skills.</p>

<hr size="1" />

	<span class="header2">Talent Agent</span><br /><br />
	<img class="job_pic" src="/images/icons/BC/43321.jpg"
width="100" height="100" border="0" alt="Talent Agent" />
	<span class="header3">Job Description</span>
	<blockquote>A talent agent negotiates contracts, invests
money, and makes deals for an entertainer.  In this job, you would
make sure that the entertainer's money was handled well.  You would
also help the entertainer find new places to perform.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree in business
administration or accounting for this job.  Some entertainers prefer
a master's degree. You also need to know what the public wants to
see and be able to search out opportunities.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>According to the online O*Net Resource Center, onetonline.org, the
	median annual wage of talent agents was $62,080 in February 2018. </blockquote>

<hr size="1" />

	<span class="header2">Performing Arts
Administrator</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>When you go to a theater to see a play, you see
the actors working. You do not see others working behind the stage
to make sure that things go smoothly.  A performing arts
administrator is responsible for the entire production.  As a
performing arts administrator, you would oversee the staff and make
sure they performed their duties.  You would handle the production's
money.  You would also oversee the day-to-day running of an acting
company or theater.  It takes a long time to become a performing
arts administrator.  Most performing arts administrator begin their
career in the theater as actors, directors, or
producers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most performing arts administrators have a
master's degree or a Ph.D.  Experience in the theater will be very
important to getting a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of performing arts
administrators was $70,950 in May 2016. </blockquote>

<hr size="1" />

	<span class="header2">Assistant Director</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>It takes many people to put a television program
on the air. An assistant director is one of these people.  Assistant
directors (or first and second assistants) help directors with such
details as handling the transportation of equipment, arranging for
food and accommodations, and hiring performers who appear a the
film, but have no lines. This is where many people begin their
careers behind the
camera.</blockquote>
	<span class="header3">Education</span>
	<blockquote>In addition to colleges and technical schools,
many independent centers offer training programs on various aspects
of filmmaking, such as screenwriting, film editing, directing, and
acting. For example, the American Film Institute offers training in
directing, production, cinematography, screenwriting, editing, and
production design.

</blockquote>
	<span class="header3">Salary</span>
	<blockquote>According to the job search website, indeed.com, the median
	annual wage of assistant directors was $55,792 in February 2018. </blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit
the <em>Occupational Outlook Handbook</em>:</strong> <a
href="http://www.bls.gov/ooh">www.bls.gov/ooh</a></p>

<p><strong>You may also want to try the <em>Occupational Information
Network</em> Web site:</strong> <a
href="http://online.onetcenter.org/gen_search_page">online.onetcenter
.org/gen_search_page</a></p>


<blockquote>Salary data from Bureau of Labor Statistics, U.S.
Department of Labor, <i>Occupational Outlook Handbook, 2016-17
Edition, </i> visited 2/07/2018. </blockquote>


Additional average salary information acquired from job search
website indeed.com in February 2018. The Indeed Salary Search data
is based on an index of salary information extracted from over 50
million job postings from thousands of unique sources over the
previous year.
