<p class="header1">Arts/Communications paired with
Business/Management (BC)</p>

<p>A "BC" pairing indicates that you are a "fun" person. You are
able to work with many different types of people and, more than
likely, they enjoy working with you. One of your assets is your
ability to appreciate others for who they are and what they add to a
project. You also can work on several tasks at one time. You don't
need much direction on how to complete a task or assignment because
you combine creativity with the ability to get things done. You are
likely to be very dedicated to your work.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree. Some require post high school courses.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to Math & English):</strong><br />
In high school you will want to take classes that will help you
express yourself better and help you understand others. Writing
courses will be appropriate. Also, you might consider taking public
speaking. Some business courses will help you learn how to get
things done quickly.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting<br />
			Speech&nbsp;&&nbsp;Communication<br />
			Art/Music<br />
			Economics
		</td>
		<td>
			Business Law<br />
			Advertising<br />
			Computer Science<br />
			Government/Civics
		</td>
		<td>
			Computer Technology<br />
			Marketing&nbsp;&&nbsp;Advertising<br />
			Graphic Arts<br />
			Logic
		</td>
		<td>
			Language<br />
			Psychology<br />
			Public Relations<br />
			Political Science
		</td>
		<td>
			Photography<br />
			Sociology<br />
			History<br />
			Business Education
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
Experience is an important thing! If you are looking for a fun
activity or a part-time job, consider places where communicating
with others is a focus. Don't forget to find a place where you can
show how responsible you are.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Drama/Theatre<br />
			Debate Team<br />
			Junior Achievement<br />
			Yearbook
		</td>
		<td>
			Band/Chorus<br />
			Photography Club<br />
			Class Officer<br />
			Radio/TV Activities
		</td>
		<td>
			Newspaper/Yearbook<br />
			Audio/Visual Services<br />
			Computer Activities<br />
			Future Business Leaders
		</td>
		<td>
			Language Club<br />
			Exchange Programs<br />
			Community Volunteer
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job.</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting Firms<br />
			Advertising Agencies<br />
			Office Temporary Services<br />
		</td>
		<td>
			Libraries<br />
			Newspaper&nbsp;Publisher<br />
			Repair Services
		</td>
		<td>
			Radio/TV Studios<br />
			Receptionist<br />
			Graphic&nbsp;Design&nbsp;Firms
		</td>
		<td>
			Restaurant<br />
			Telephone Sales
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="10" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">BC Career Possibilities</span><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8" border="none">
					<td width="33%" border="0" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" border="0" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" border="none" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Creative Business</span><br />
						<em>Art Director<br />
						Chef<br />
						Illustrator<br />
						Graphic Artist<br />
						Art Dealer<br />
						Interior Designer<br />
						Buyer/Merchandiser<br />
						Hair Stylist<br />
						Wedding Consultant<br />
						Fashion Coordinator<br />
						Restaurateur</em>
					</td>
					<td width="33%">
						<span
class="header2">Communications Business</span><br />
						<em>Public Relations
Specialist<br />
						Publicist/Press
Agent<br />
						Television
Broadcaster<br />
						Advertising
Production Manager<br />
						Media Production
Specialist<br />
						Advertising
Copywriter<br />
						Talk Show
Host<br />
						Disc
Jockey<br />
						Radio/TV Traffic
Manager<br />
						Photographer</em>
					</td>
					<td width="33%">
						<span
class="header2">Entertainment Business</span><br />
						<em>Book Publishing
Professional<br />
						Media
Specialist<br />

	Photojournalist<br />
						Television Set	Director<br />
						Video Production Assistant<br />
						Crossword Puzzle	Maker<br />
						Technician
							<ul>

	<li>Media Production</li>

	<li>Design</li>

	<li>Stage</li>
							</ul>
						Production Assistant</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>


<div class="inner">
	
<hr size="1" />

<span class="header1">CREATIVE BUSINESS</span>
<p>You can be successful in this field if you have a talent and can
manage business matters yourself. This field combines artistic
talent with practical business sense.</p>

<hr size="1" />

	<span class="header2">Chef</span><br />
	<img class="job_pic" src="/images/icons/BC/43009.jpg"
width="100" height="100" border="0" alt="Chef" />
	<span class="header3">Job Description</span>
	<blockquote>If you became a chef, you would use your
creativity to prepare new kinds of dishes or meals for others to
eat. You would work in a kitchen creating new recipes, preparing the
meals, and overseeing the staff.  Creativity is important to a
chef.</blockquote>
	<span class="header3">Education</span>
	<blockquote>No college degree is needed.  Most chefs learn
their craft at schools called "culinary institutes."  Chefs who do
not train at a culinary institute are put through a tough on-the-job
training program while working in a kitchen at another
job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of chefs was $51,530 in
May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Illustrator</span><br />
	<img class="job_pic" src="/images/icons/BC/43312.jpg"
width="100" height="100" border="0" alt="Illustrator" />
	<span class="header3">Job Description</span>
	<blockquote>Illustrators draw or paint pictures that go with
somebody else's words.  Their goal is to "add to" the appeal or
impact of the words.  Their work can be found in newspapers,
magazines, books, and greeting cards.  It can be found in TV
commercials as well.  As an illustrator, you would be most likely to
find work with an advertising agency or a publishing company.  But
other organizations hire illustrators too.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most illustrators have had some post high school
courses. A bachelor's degree from a college, university, or an art
school is a definite advantage.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of illustrators was $50,550 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Interior Designer</span><br />
	<img class="job_pic" src="/images/icons/BC/43032.jpg"
width="100" height="100" border="0" alt="Interior Designer" />
	<span class="header3">Job Description</span>
	<blockquote>If you have a "knack" for making a room look its
best, you might become an interior designer. Interior designers help
their clients decorate the inside of homes, offices, and
businesses.  In this job, you would decorate rooms working within a
budget. To do this, you would have to know the best prices on
furniture, drapes, and room accessories.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You typically need a bachelor's degree, with a focus on interior design for this occupation. You may want to join a
professional association to find a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of interior designers was
$56,040 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">COMMUNICATIONS BUSINESS</span>
<p>The communication business needs people who can perform on and
off the air. In this occupational field, you must have specialized
knowledge in an area such as politics, art, sports, or business.
Here are three examples.</p>

<hr size="1" />

	<span class="header2">News Reporter</span><br />
	<img class="job_pic" src="/images/icons/BC/C506027.jpg"
width="100" height="100" border="0" alt="News Reporter" />
	<span class="header3">Job Description</span>
	<blockquote>A news reporter is responsible for putting the
news or other programming on the air. As a news reporter, you would
probably begin your career by working behind the scenes.  It is very
tough to become an "on air" reporter.  People are usually
promoted into these positions after they have proven they can
do "off air" work.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a degree in journalism or
communications to work as a copywriter, the first job of a
news reporter. The more experience you have around a studio, the
better your chances to do "on air" work.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of news reporters was
$46,270 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Public Relations
Manager/Specialist</span><br />
	<img class="job_pic" src="/images/icons/BC/C1737_31.jpg"
width="100" height="100" border="0" alt="Advertising Copywriter" />
	<span class="header3">Job Description</span>
	<blockquote>Companies want customers and others to see them in a positive way. As a public relations specialist, you would let people know about the good things your company has done. To do this, you would create press releases, social media campaigns and TV and radio announcements. It would be important that you were enthusiastic about the company. You would also need to be able to write and speak clearly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree in public
relations, journalism, communications, English, or business to
become a Public Relations Manager/Specialist.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of public relations
manager/specialist was $61,150 in May 2019.</blockquote>

<hr size="1" />

<span class="header1">ENTERTAINMENT BUSINESS</span>
<p>The occupations in this field allow people to work "behind the
scenes" in show business. To be successful in this field you must
understand business and have good people skills.</p>

<hr size="1" />

	<span class="header2">Talent Agent</span><br />
	<img class="job_pic" src="/images/icons/BC/43321.jpg"
width="100" height="100" border="0" alt="Talent Agent" />
	<span class="header3">Job Description</span>
	<blockquote>A talent agent negotiates contracts, invests
money, and makes deals for an entertainer.  In this job, you would
make sure that the entertainer's money was handled well.  You would
also help the entertainer find new places to perform.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree in business
administration or accounting for this job.  Some entertainers prefer
a master's degree. You also need to know what the public wants to
see and be able to search out opportunities.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of talent agents was $73,740 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Theater Director</span><br />
	<span class="header3">Job Description</span>
	<blockquote>When you go to a theater to see a play, you see
the actors working. You do not see others working behind the stage
to make sure that things go smoothly. A theater director is responsible for the entire production. As a theater director, you would be involved with scripts, rehearsals, and overseeing the cast and crew. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Most theater directors have a
bachelor's degree and several years of theater-related experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of theater directors was $74,420 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Set and Exhibit Designer</span><br />
	<span class="header3">Job Description</span>
	<blockquote>It takes many people to create movies, TV programs, plays and exhibits. A set and exhibit designer is one of these people. They work behind the scenes. They study scripts and do research in order to create a design that will be used to construct an appropriate exhibit or set.</blockquote>
	<span class="header3">Education</span>
	<blockquote>In addition to colleges and technical schools,
many independent centers, such as the American Film Institute, offer training programs on screenwriting, film editing, directing, acting, and production design. Many set and exhibit designers have 4-year degrees and job-related experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of set and exhibit designers was $54,600 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 10, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 10, 2020). </blockquote>

</div>