<span class="header1">Arts/Communications paired with
Clerical/Administrative (BD)</span>

<p>If you had a high score in categories "B" and "D" you like to
work on creative projects and you enjoy their completion. You have a
balance of characteristics that will allow you to be creative and
efficient. Others know that they can count on you.</p>
<p>Most occupations in this pairing require at least some post high school courses be taken. Many require a bachelor's degree.</p>
<p><strong>Courses you might want to take in high
school.</strong><br />
In high school you will want to take courses that allow you to
express your thoughts and ideas through writing, speaking, or visual
media. You also will want to take courses that appeal to your
practical side.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising/Marketing<br />
			History<br />
			Computer Technology<br />
			Sociology
		</td>
		<td>
			Computer Programming<br />
			Graphic Arts<br />
			World Languages<br />
			Speech/Communications/
			Music<br />
		</td>
		<td>
			Office Administration<br />
			Photography<br />
			Technology Education
		</td>
		<td>
			Business Education<br />
			Psychology<br />
			Bookkeeping<br />
		</td>
		<td>
			Art<br />
			Business Math<br />
			Geography<br />
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
Experience is an important thing! When you are looking for a fun
activity or a part-time job, think about working in places where
communication is the focus. Don't forget to find a place where you
can show others how dependable you are.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Drama/Theatre<br />
			Debate Team<br />
			Office Assistant<br />
			Music Lessons
		</td>
		<td>
			Band/Chorus<br />
			Photography Club<br />
			Teaching Assistant<br />
			Radio/TV Activities
		</td>
		<td>
			Newspaper/Yearbook<br />
			Audio-Visual Services<br />
			Class Officer<br />
			Community Volunteer
		</td>
		<td>
			Language Club<br />
			Library Assistant<br />
			Future Business Leaders
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting Firms<br />
			Theaters<br />
			Receptionist<br />
			Retail Stores
		</td>
		<td>
			Data Entry/Processing<br />
			Advertising Agencies<br />
			Radio/TV Studios<br />
			Photography Studios
		</td>
		<td>
			Libraries<br />
			Temporary Agencies<br />
			Clerical Offices
		</td>
		<td>
			Printing Companies<br />
			Newspaper Publishers<br />
			Graphic Design Firms
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">BD Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Creative Arts/Communication</span><br />

	<em>Publisher<br />
						Marketing
Administrator<br />
						Editor<br />
						Press
Secretary<br />
						Media
Planner<br />
						Writer
							<ul>

	<li>Newspaper</li>

	<li>Playwright</li>

	<li>Technical</li>
							</ul>
						Critic<br />
						Editorial
Assistant<br />
						Tour Coordinator</em>
					</td>
					<td width="33%">
						<span
class="header2">Creative Clerical/Administrative</span><br />
						<em>Computer Graphic
Designer<br />
						Public Relations
Specialist<br />
						Library
Assistant<br />
						Paralegal<br />

	Proofreader<br />

	Marketing/Advertising Account Executive<br />
						Real Estate
Agent<br />
						Radio/Television
Traffic Continuity Specialist<br />
						Telemarketer</em>
					</td>
					<td width="33%">
						<span
class="header2">Creative Production</span><br />
						<em>Book Publishing
Professional<br />
						Media
Specialist<br />

	Photojournalist<br />
						Television Set
Decorator<br />
						Video Production
Assistant<br />
						Crossword Puzzle
Maker<br />
						Technician
							<ul>

	<li>Media Production</li>

	<li>Design</li>

	<li>Stage</li>
							</ul>
						Production
Assistant</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">CREATIVE ARTS/COMMUNICATION</span>
<p>Writing is the main occupation in this field.  There are many
different types of writers. Here are three examples you might want
to consider.</p>

<hr size="1" />

	<span class="header2">Newswriter</span><br />
	<img class="job_pic" src="/images/icons/BD/43336.jpg"
width="100" height="100" border="0" alt="Newswriter" />
	<span class="header3">Job Description</span>
	<blockquote>A newswriter gathers information and writes
articles for the newspaper or items for a newscast.  To be a
newswriter, you must be able to write well.  You must also be able
to get yourself started and to finish writing your news articles on
time.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a degree in communications, journalism,
or English for this job.  Any experience you have had at a newspaper
or broadcast studio will also help.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of newswriters was
$46,270 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Editor</span><br />
	<img class="job_pic" src="/images/icons/BD/C506006.jpg"
width="100" height="100" border="0" alt="Editor" />
	<span class="header3">Job Description</span>
	<blockquote>There are many kinds of editors.  Some editors
know what readers like.  These editors read manuscripts and decide
which should become a book.  Other editors do "pencil point"
editing.  They read a manuscript.  Then they make changes in the way
it is organized or in the words or grammar.  These editors make the
writing easier to read or more interesting.  To be an editor, you
must know how to write. You must also know how to evaluate other
people's writing and help make it better.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree in
communications, journalism, or English for this job.  Often, editors
are people who were writers first.  Your work experience will be
very important to finding a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of editors was $61,370 in
May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Editorial Assistant</span><br />
	<span class="header3">Job Description</span>
	<blockquote>As an editorial assistant you would work closely
with an editor.  You would check to be sure that writers' grammar,
spelling, and sentence structure were correct.   You would also be
sure that any facts, dates and other information were
correct.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree in
communications, journalism, or English for this job.  You can gain
writing and editing experience by working on yearbooks, school
newspapers, etc.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of editorial assistants was $41,951 in
May 2019.</blockquote>

<hr size="1" />

<span class="header1">CREATIVE CLERICAL/ADMINISTRATION</span>
<p>To succeed in this field, you need to have good organizing
skills.  You also need to be a good writer, and to show
originality.  Here are three occupations for you to consider.</p>

<hr size="1" />

	<span class="header2">Public Relations
Specialist</span><br />
	<img class="job_pic" src="/images/icons/BD/1369.jpg"
width="100" height="100" border="0" alt="Public Relations
Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>Companies want customers and others to see them
in a positive way.  So they hire people to achieve this. As a public
relations specialist, you would let people know about the good
things your company has done.  To do this, you would write press
releases, brochures, and television and radio announcements.  It
would be important that you were enthusiastic about the company. You
would also need to be able to write and speak clearly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree in communications,
journalism, or public relations for this job.  Work experience will
be important, too.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of public relations
specialists was $61,150 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Paralegal</span><br />
	<img class="job_pic" src="/images/icons/BD/43286.jpg"
width="100" height="100" border="0" alt="Paralegal" />
	<span class="header3">Job Description</span>
	<blockquote>You may be interested in law or the court
system, but not want to be a lawyer. If so, you might become a
paralegal.  A paralegal works closely with a lawyer.  As a
paralegal, you would do a lot of research to find background
information for the lawyer. You would also help the lawyer prepare
for court.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Paralegals often receive 
training in a paralegal certification program, and many have an associate's degree. More and more, lawyers want to
hire paralegals who have a bachelor's degree in humanities or the
social sciences.  You will find a job more easily if you learn as
much about the law as you can. It is also helpful to work in a law
office, if possible.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of paralegals was $51,740
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Real Estate Agent</span><br />
	<img class="job_pic" src="/images/icons/BD/C526017.jpg"
width="100" height="100" border="0" alt="Real Estate Agent" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy working with people and want to
help them buy housing or land, you might become a real estate agent.
As a real estate agent, you would work with people who want to sell
their home.  You would show this home to people who want to buy
it.  You would help these would-be buyers get a loan.  You would
need to be independent and a good problem solver.  You must also communicate well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma to be a
real estate agent. More and more employers want you to have a
bachelor's degree.  Real estate agents must be licensed in the state
in which they work.  To get this license, you must take courses in
real estate law and practices and pass an exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of real estate agents was
$48,930 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">CREATIVE PRODUCTION</span>
<p>The occupations in this field need people who are outgoing and
creative.  Here are two examples.</p>

<hr size="1" />

	<span class="header2">Managing Editor</span><br />
	<img class="job_pic" src="/images/icons/BD/43333.jpg"
width="100" height="100" border="0" alt="Managing Editor" />
	<span class="header3">Job Description</span>
	<blockquote>A managing editor works in the publishing
industry.  As a managing editor, you would oversee the hiring of
writers and reporters.  You would also plan what is published.  You
would know every aspect of putting together a newspaper or
magazine.  Your job would be important.  But it would be stressful
too.  Managing editors usually have other jobs in publishing before
they are promoted to this job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree in English,
literature, or journalism for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of managing editors was $61,370
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Media Specialist</span><br />
	<img class="job_pic" src="/images/icons/BD/43278.jpg"
width="100" height="100" border="0" alt="Media Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>To see what a media specialist does, go to your
school media center or library. A media specialist helps others get
ready to give presentations or to chair meetings.  As a media
specialist, you would suggest easy and effective ways to get a
message across.  You would show people how to use the equipment.
You would also see that the equipment was in good repair.  You must
be creative and be comfortable with technology to be good at this
job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A master's degree in library science (MLS) is
necessary for librarian positions in most public, academic, and
special libraries. School librarians do not typically need an MLS
but must meet State licensing requirements. A part-time job at your
local library would give you experience.  You might also volunteer
in your school media center.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of media specialists was
$59,500 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 11, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 11, 2020). </blockquote>

</div>
