<span class="header1">Arts/Communications paired with
Protective/Military Service (BE)</span>

<p>If you show high scores in categories "B" and "E" you are a
person who knows how to make things happen. You are very independent
and have your own way of doing things. You like to use your
creativity and explore new possibilities.  Teamwork and people are
important to you. You are especially good at working on teams that
are solving problems.</p>
<p>The occupations in this pairing often require some sort of
specialized training after high school. Some require college level
courses. Others require training programs provided by the company
that hires you.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that allow you to continue
to learn about communication. You will also want to take courses
that help you understand people.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Business Law<br />
			Psychology<br />
			Computer Sciences<br />
			Music
		</td>
		<td>
			Public Relations<br />
			Graphic Arts<br />
			Geography<br />
			Marketing/Advertising
		</td>
		<td>
			Government/Civics<br />
			Life Sciences<br />
			History<br />
			Criminal Justice
		</td>
		<td>
			World Languages<br />
			Physical Education<br />
			Communications<br />
			Computer Inf. Sys.
		</td>
		<td>
			Political Science<br />
			Sociology<br />
			Photography
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for after school activities or part-time jobs, make
them count. You will enjoy any club or activity that involves
working with others and/or communicating your thoughts and
feelings.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Drama/Theatre<br />
			Debate Team<br />
			ROTC<br />
			Parks & Recreation
		</td>
		<td>
			Band/Chorus<br />
			Photography Club<br />
			Flight Training<br />
			Radio/TV Activities
		</td>
		<td>
			Newspaper/Yearbook<br />
			Audio-Visual Services<br />
			Scouts<br />
			Camp Activities
		</td>
		<td>
			Language Club<br />
			Martial Arts<br />
			Athletics
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising Agencies<br />
			Camp Counselor<br />
			Construction Sites<br />
			TV/Radio Studios
		</td>
		<td>
			Equipment Operation<br />
			Equipment Repair<br />
			Graphic Design Firms<br />
			Recreation/Parks
		</td>
		<td>
			Gyms<br />
			Libraries<br />
			Life Guarding
		</td>
		<td>
			Newspaper publisher<br />
			Photography Studios<br />
			Printing Companies
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">BE Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Written & Oral Communication</span><br />

	<em>Lawyer<br />
						Public Relations
Manager<br />
						Foreign
Correspondent<br />
						Scientific &
Technical Publications Editor<br />
						International News
Correspondent<br />
						Historian<br />
						Radio
Announcer<br />
						Editorial
Assistant<br />
						Reporter<br />
						Interpreter</em>
					</td>
					<td width="33%">
						<span
class="header2">Communication Technologies</span><br />
						<em>Communications
Manager<br />
						Traffic
Engineer<br />
						Film
Editor<br />
						Sonar & Radar
Technician<br />
						Radio
Operator<br />
						Sound & Recording
Engineer<br />
						Engineering
Technician<br />
						Broadcast
Technician<br />
						Instrument
Mechanic<br />
						Teletype
Operator</em>
					</td>
					<td width="33%">
						<span
class="header2">Visual Product</span><br />
						<em>Television
Program Director<br />
						Broadcast
Journalist<br />
						Industrial
Designer<br />

	Photojournalist<br />
						Movie
Director<br />
						Graphic
Designer<br />

	Photographer<br />
						Motion Picture
Camera Operator<br />
						Drafting
Technician<br />
						Photographic Process
Worker</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">WRITTEN & ORAL COMMUNICATIONS</span>
<p>These occupations need people who can write well and enjoy public
speaking. If speaking in front of large groups does not bother you,
the occupations in this field may be appropriate.</p>

<hr size="1" />

	<span class="header2">Scientific or Technical Publications
Writer</span><br />
	<img class="job_pic" src="/images/icons/BE/43289.jpg"
width="100" height="100" border="0" alt="Scientific or Technical
Publications Writer" />
	<span class="header3">Job Description</span>
	<blockquote>Technical writers put technical information into
easily understandable language. They prepare product documentation,
such as operating and maintenance manuals, catalogs, assembly
instructions, and project proposals. Technical writers primarily are
found in the information technology industry, writing operating
instructions for online.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree in
communications, journalism, or English for this job. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of scientific or
technical publications writers was $72,850 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Editorial Assistant</span><br />
	<span class="header3">Job Description</span>
	<blockquote>As an editorial assistant you would work closely
with an editor.  You would check to be sure that writers' grammar,
spelling, sentence structure, facts, dates and other information were
correct.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree in
communications, journalism, or English for this job.  Volunteer work
on yearbooks and school newspapers can give you
experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of editorial assistants was $41,951 in
May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Reporter</span><br />
	<img class="job_pic" src="/images/icons/BE/43293.jpg"
width="100" height="100" border="0" alt="Reporter" />
	<span class="header3">Job Description</span>
	<blockquote>If you like to look for clues and piece stories
together, you might become a reporter. As a reporter, you would
research "a lead" or information about a possible newsworthy story.
You would then write the story using the facts you found through
your research.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree in
communications, journalism, or English for this job.  Experience at
a newspaper or broadcast studio is helpful too.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of reporters was $46,270
in May 2019. </blockquote>

<hr size="1" />

<span class="header1">COMMUNICATIONS TECHNOLOGIES</span>
<p>The occupations in this field are very important to our everyday
routines. They allow you to come in contact with large numbers of
people.</p>

<hr size="1" />

	<span class="header2">Traffic Engineer</span><br />
	<img class="job_pic" src="/images/icons/BE/1099.jpg"
width="100" height="100" border="0" alt="Traffic Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>A traffic engineer studies traffic volume,
speed, effectiveness of signals, adequacy of lighting, and other
factors influencing traffic conditions to decide where traffic
lights, signs and road markings should be placed. Your designs would
help traffic to flow smoothly. </blockquote>
	<span class="header3">Education</span>
	<blockquote>A traffic engineer typically has at least a
bachelor's degree and is registered in the state where he/she
works.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of traffic engineers was $87,060 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Radio Operator</span><br />
	<img class="job_pic" src="/images/icons/BE/M100.jpg"
width="100" height="100" border="0" alt="Radio Operator" />
	<span class="header3">Job Description</span>
	<blockquote>A radio operator often works for the military.
In this job, you would send, receive, and log radio messages.
Sometimes you would figure out secret codes.  This is an important
job. Without radio operators, it would be hard to communicate within
the military.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You do not need a college degree for this job.
But courses in typing, speech, and English will be valuable. The
military will train you in radio operation.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of radio operators was $42,790 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Broadcast Technician</span><br />
	<img class="job_pic" src="/images/icons/BE/1102.jpg"
width="100" height="100" border="0" alt="Broadcast Technician" />
	<span class="header3">Job Description</span>
	<blockquote>A broadcast technician helps set up, repair, and
operate the equipment used to send radio and television signals.
Technicians operate the cameras.  They also create lighting effects
and develop sound tracks. You might enjoy this job if you like
working with equipment and do not mind getting your hands
dirty.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Technical school, community college, or college
training in broadcast technology, electronics, or computer
networking provides the best preparation for work as a broadcast
technician.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of broadcast technicians
was $40,570 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">VISUAL PRODUCTION</span>
<p>Jobs in this field are concerned with producing visual
materials.  These materials can play an important role in helping
people to understand information. They make written materials more
interesting as well.  Here are three examples.</p>

<hr size="1" />

	<span class="header2">Broadcast Journalist</span><br />
	<img class="job_pic" src="/images/icons/BE/43067.jpg"
width="100" height="100" border="0" alt="Audiovisual Production
Director" />
	<span class="header3">Job Description</span>
	<blockquote>News analysts, reporters, and correspondents
gather information, prepare stories, and make broadcasts that inform
us about local, state, national, and international events; present
points of view on current issues; and report on the actions of
public officials, corporate executives, interest groups, and others
who exercise power.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most employers prefer individuals with a
bachelor's degree in journalism or mass communications, but some
hire graduates with other majors. They look for experience at school
newspapers or broadcasting stations, and internships with news
organizations.  </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of broadcast journalists
was $46,270 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Graphic Designer</span><br />
	<img class="job_pic" src="/images/icons/BE/43312.jpg"
width="100" height="100" border="0" alt="Graphic Designer" />
	<span class="header3">Job Description</span>
	<blockquote>A graphic designer helps to create visual
displays that appear in many kinds of publications.  As a graphic
designer, you would make signs, charts, tables, and other visual
displays.  Your work could appear in magazines, training manuals,
newspapers, and other publications.  You need to be creative to do
well in this job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's or an associate degree in graphic
design is usually required for a job as a graphic designer.
Creativity, communication, and problem solving skills and
familiarity with computer graphics and design software also are
important.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of graphic designers was
$52,110 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Photojournalist</span><br />
	<img class="job_pic" src="/images/icons/BE/43060.jpg"
width="100" height="100" border="0" alt="Photojournalist" />
	<span class="header3">Job Description</span>
	<blockquote>If you like to take photographs, you might
become a photojournalist. In this job, you would photograph
important events for newspapers, magazines, and television. A
photojournalist's job is much like that of a reporter. The
difference is that you would use photos to tell the story. To be
successful, you need to be brave enough to follow a hunch. You also
have to be able to make quick decisions.</blockquote>
	<span class="header3">Education</span>
	<block-quote>Positions in photojournalism or in
industrial or scientific photography generally require a college
degree in photography or in a field related to the industry in which
the photographer seeks employment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of photojournalists was
$36,280 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 10, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 10, 2020). </blockquote>

</div>
