<span class="header1">Arts/Communications paired with Technology (BF)
</span>

<p>With a "BF" interest, you will be a valuable employee in a
rapidly changing technology field. Almost all technology is in one
way or another concerned with communication of change. You enjoy the
mechanics of technology and you can use it to express your thoughts
and feelings. The technical changes in the technology field offers a
fast paced, visual interchange of ideas and knowledge.</p>
<p>Many of the occupations in this pairing require some sort of
specialized and/or technical training after high school. Many
require college degrees or college level courses.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that allow you to continue
to learn about communicating. Technology courses will be important,
as well.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising/Marketing<br />
			Environmental Science<br />
			Computer Programming
		</td>
		<td>
			World Languages<br />
			Drafting<br />
			Psychology			Appliance Repair<br />
			Printing Companies<br />
			Lumberyards<br />
			Newspaper Offic
		</td>
		<td>
			Photography<br />
			Technology Ed.<br />
			Public Relations
		</td>
		<td>
			Communications<br />
			History
			Sociology
		</td>
		<td>
			Art/Graphic Art<br />
			Music<br />
			Business Education
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. Any club or activity that involves technology and
communicating will be valuable.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Drama/Theatre<br />
			Debate Team<br />
			Audiovisual Services
		</td>
		<td>
			Band/Chorus<br />
			Photography Clubs<br />
			Computer Club
		</td>
		<td>
			Newspaper/Yearbook<br />
			Library Assistant<br />
			Music Lesson
		</td>
		<td>
			Radio/TV Activities<br />
			Math/Science Clubs<br />
			Chess Club
		</td>
	<tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Appliance Repair<br />
			Printing Companies<br />
			Lumberyards<br />
			Newspaper Offices
		</td>
		<td>
			Delivery Services<br />
			TV/Radio Studios<br />
			Photographic Labs
		</td>
		<td>
			Graphic Design Firms<br />
			Camp Counseling<br />
			Construction<br />
			Small Engine Repair
		</td>
		<td>
			Forestry<br />
			Equipment Repair Shops<br />
			Farming<br />
			Photography Studios
		</td>
		<td>
			Park Services<br />
			Landscaping<br />
			Lawn Care
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">BF Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Communications</span><br />
						<em>Medial
Specialist<br />
						Public Relations
Specialist<br />
						Editor<br />
						Technical
Writer<br />
						Public Relations
Assistant<br />

	Sportscaster<br />
						Desktop
Publisher<br />
						Tour
Publicist<br />
						Interpretive
Naturalist<br />
						Musician<br />
						Actor<br />
						Cruise Ship
Entertainer</em>
					</td>
					<td width="33%">
						<span
class="header2">Creative Technology</span><br />
						<em>Industrial
Designer<br />
						Graphic
Artist<br />

	Photographer<br />
						Camera
Operator<br />
						Lighting
Designer<br />
						Video
Editor<br />
						Drafting
Technician<br />
						Metal
Artist/Fabricator<br />
						Model
Maker<br />
						Airbrush
Artist<br />
						Tattoo Artist</em>
					</td>
					<td width="33%">
						<span
class="header2">Technology</span><br />
						<em>Exhibit
Builder<br />
						Theater Lighting
Designer<br />
						Sound
Mixer<br />
						Radio/TV Service
Technician<br />
						Book
Binder<br />
						Road
Manager<br />
						Roller Coaster
Technician<br />
						Tile
Setter<br />
						Painter<br />
						Printer
Developer<br />
						Carpenter<br />
						Landscape
Gardener<br />
						Entertainer Body
Guard</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">COMMUNICATIONS</span>
<p>Your ability to communicate may be your ticket into the
occupations in this field. Those who work in this field are
excellent communicators. They can speak in front of a large group of
people.</p>

<hr size="1" />

	<span class="header2">Public Relations
Specialist</span><br />
	<img class="job_pic" src="/images/icons/BF/1369.jpg"
width="100" height="100" border="0" alt="Public Relations
Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>Companies want customers and others to see them
in a positive way.  So they hire people to see that this happens.
As a public relations specialist, you would let people know about
the good things your company has done.  To do this, you would write
press releases, brochures, and television and radio announcements.
It would be important that you were enthusiastic about the company.
You would also need to be able to write and speak
clearly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Opportunities should be best for college
graduates who combine a degree in public relations, journalism, or
another communications-related field with a public relations
internship or other related work experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of public relations
specialists was $61,150 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Technical Writer</span><br />
	<img class="job_pic" src="/images/icons/BF/43289.jpg"
width="100" height="100" border="0" alt="Technical Writer" />
	<span class="header3">Job Description</span>
	<blockquote>Have you ever read the owner's manual for your
computer, sound system, or video game? The person who wrote the
manuals was a technical writer. In this job, you would write
manuals, catalogs, and instruction books.  You would make science or
technical information and directions easy for others to
understand.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most jobs in this occupation require a college
degree preferably in communications, journalism, or English, but a
degree in a technical subject may also be useful for technical writing
positions. For example, writers who work on computer manuals usually
have a degree in computer science.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of technical writers was
$72,850 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Actor/Actress</span><br />
	<img class="job_pic" src="/images/icons/BF/C575061.jpg"
width="100" height="100" border="0" alt="Actor/Actress" />
	<span class="header3">Job Description</span>
	<blockquote>If you have a burning desire to be in the movies
or in a play on Broadway, you might become a professional actor or
actress.  In this job, you would play the role of a character in a
play, television program, or movie.  To be successful, you must have
a talent for acting.  You must also be able to perform in front of a
large group of people. You would have to be able to remember your
lines.  You would also have to get along with other actors, the
directors, and others who make the production possible.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Formal dramatic training, either through an
acting conservatory or a university program, generally is necessary
for these jobs, but some people successfully enter the field without
it. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median wage of actors/actresses was $20.43 per hour in May 2019. </blockquote>

<hr size="1" />

<span class="header1">CREATIVE TECHNOLOGY</span>
<p>The occupations in this field need people who can use their
technical skills to create something new. Your creativity and
interest in technology will help you to succeed in this field.</p>

<hr size="1" />

	<span class="header2">Photographer</span><br />
	<img class="job_pic" src="/images/icons/BF/43060.jpg"
width="100" height="100" border="0" alt="Photographer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like taking pictures and have a
good "eye," you might become a professional photographer. A
photographer combines communications skills and technology.  In this
job, you would take pictures of people, things, or events. You must
be creative.  Your goal is to show people something they might
otherwise not have seen.  You must understand the technical aspects
of the camera.  You must also know how to produce finished images and prints using computer software. Many photographers work for themselves. So, it is helpful to understand
how a small business works.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree in photography or the visual
arts can develop your basic skills.  But, you also need to be
creative to succeed in this field.  Spend as much time as possible
looking at great pictures and taking your own. Getting involved in
photography clubs and working in photo shops and labs will help you
learn more about using your camera to capture successful
photographs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of photographers was
$36,280 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Video Editor</span><br />
	<img class="job_pic" src="/images/icons/BF/C506027.jpg"
width="100" height="100" border="0" alt="Video Editor" />
	<span class="header3">Job Description</span>
	<blockquote>When you watch a movie or television program,
you are watching more than the work of actors.  You are watching the
work of a video editor, too.  As a video editor, you would use your
creativity to piece together the footage of a film or program. You
would have two goals.  You would want to be sure the audience could
understand the story.  You also want to edit the film so that the
audience could "feel" the movie.  You would use video equipment to
make the movie seems exciting, dramatic, funny, or scary.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Television, video, and motion picture camera
operators and editors usually acquire their skills through formal
postsecondary training at vocational schools, colleges,
universities, or photographic institutes. A bachelor's degree may be
required for some positions, particularly those for film and video
editors. Employers usually seek applicants with a good eye,
imagination, and creativity, as well as a good technical
understanding of how the camera operates. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of video editors was
$63,780 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Desktop Publisher</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Desktop publishers use computer software to
design page layouts for newspapers, books, brochures, and other
items that will be printed or put online. They collect the text,
graphics, and other materials they will need and then format them
into a finished product.</blockquote>
	<span class="header3">Education</span>
	<blockquote>On-the-job training is provided for employees. Many desktop 
publishers need an associate's degree.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of desktop publishers was
$45,390 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY</span>
<p>If you prefer a hands-on approach in your work, you might be
interested in occupations in this field.  You need to have skill in
using technology.</p>

<hr size="1" />

	<span class="header2">Lighting Designer</span><br />
	<span class="header3">Job Description</span>
	<blockquote>A lighting designer is a part of the set design stage crew
that helps the actors look better on stage.  If you would like to be
a part of a drama production, but not want to be an actor or
director, this may be a job for you.  As a lighting designer, you
would use your technical know-how to make the lighting on stage
reflect the "feeling" of the play. For example, if the scene were
set in the middle of an electrical storm you would make sure there
were flashes of light on stage.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree may help you to get a job,
but it is not required.  It is important to have experience.
Sometimes, lighting designers serve as an apprentice before becoming
a designer. An apprentice is someone who is learning a trade by
working on the job with an experienced person.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of lighting designers was $54,600
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Sound Engineering
Technician</span><br />
	<img class="job_pic" src="/images/icons/BF/43158.jpg"
width="100" height="100" border="0" alt="Sound Mixer" />
	<span class="header3">Job Description</span>
	<blockquote>Sound engineering technicians operate machines
and equipment to record, synchronize, mix, or reproduce music,
voices, or sound effects in recording studios, sporting arenas,
theater productions, or movie and video productions.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The best way to prepare for a broadcast and
sound engineering technician job is to obtain technical school,
community college, or college training in broadcast technology,
electronics, or computer networking.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of  sound engineering
technicians was $45,510 in May 2019. </blockquote>

<hr size="1" />


	<span class="header2">Road Manager</span><br />
	<img class="job_pic" src="/images/icons/BF/43239.jpg"
width="100" height="100" border="0" alt="Road Manager" />
	<span class="header3">Job Description</span>
	<blockquote>When rock bands or stage productions take their
shows on the road, they hire a road manager. If you became a road
manager, you would make the arrangements for equipment and
performers to arrive at the concerts or performances on time. Road
managers have a tough job.  They are expected to deal with any
problems during a tour and to handle a thousand details.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There is no college degree needed to be a road
manager. You must have experience working with people and solving
problems.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>According to the job search website, indeed.com, the median annual wage of road managers was $40,952 in September 2020. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 10, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 10, 2020). </blockquote>

<blockquote>Indeed.com. On the Internet at <a href="http://www/indeed.com">http://www/indeed.com</a> (visited September 10, 2020). </blockquote>

</div>