<span class="header1">Arts/Communications paired with Public Service
(BG)</span>

<p>If you scored high in the "B" and "G" categories, you are a very
independent person. Your "no-nonsense" approach ensures that things
get done. You are creative, responsible, and outgoing. You enjoy
working with others, but can work alone. More than likely, you will
choose an occupation that will help your community.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree. In certain occupations, it is valuable to have a master's
degree or a Ph.D.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that help you understand
communication and people. Social studies courses such as political
science and sociology will be of particular interest to you.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising/Marketing<br />
			Psychology<br />
			Physical Education<br />
			Business Education
		</td>
		<td>
			Government/Civics<br />
			Art<br />
			Public Relations<br />
			Music
		</td>
		<td>
			Graphic Arts<br />
			Communications<br />
			Business Law<br />
			Political Science
		</td>
		<td>
			World Languages<br />
			Geography<br />
			Computer Technology<br />
			Sociology
		</td>
		<td>
			Photography<br />
			Health/Nutrition<br />
			Government<br />
			Economics
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. Any club or activity where communicating with others
and/or working in a team will be valuable.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Drama/Theatre<br />
			Debate Team<br />
			Church Activities
		</td>
		<td>
			Band/Chorus<br />
			Safety Patrol<br />
			Chess Club
		</td>
		<td>
			Newspaper/Yearbook<br />
			Audio-Visual Services<br />
			Youth Organizations
		</td>
		<td>
			Language Club<br />
			Peer Counselor<br />
			Hospital Volunteer
		</td>
		<td>
			Radio/TV Activities<br />
			Photography Club
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Camp Counseling<br />
			Church Programs<br />
			Courthouse Offices
		</td>
		<td>
			Graphic Design<br />
			Libraries<br />
			Life Guarding
		</td>
		<td>
			Newspaper Offices<br />
			Political Offices<br />
			Printing Companies
		</td>
		<td>
			TV/Radio Studios<br />
			Recreation Departments<br />
			Special Olympics
		</td>
		<td>
			Theater<br />
			Youth Coaching
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">BG Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Community Support Services</span><br />
						<em>Community
College Administrator<br />
						City Zoning
Director<br />
						Continuing Education
Coordinator<br />
						Teacher
							<ul>

	<li>Adult Education</li>

	<li>Public Speaking</li>

	<li>Broadcasting</li>
							</ul>
						Chamber of Commerce
Representative<br />
						Visitors Bureau
Representative<br />
						TV/Radio Public
Affairs Producer<br />
						Lobbyist<br />
						Clergy<br />
						Church Youth
Director<br />
						Reservation/Ticket
Agent</em>
					</td>
					<td width="33%">
						<span
class="header2">Art and Design</span><br />
						<em>Ballet/Symphony
Director<br />
						Ballet/Symphony
Manager<br />
						Museum
Director<br />
						City
Planner<br />
						Orchestra
Conductor<br />
						Historic
Preservationist<br />
						Performing Arts
Personnel Director<br />
						Landscape
Designer<br />
						Arts Festival
Coordinator<br />
						Exhibit
Designer<br />

	Photographer<br />
						Cook<br />
						Floral Designer</em>
					</td>
					<td width="33%">
						<span
class="header2">Communication Services</span><br />
						<em>Copyright
Attorney<br />
						Public Relations
Specialist<br />
						Community Affairs
Director<br />
						TV/Radio Talk Show
Host<br />
						College Marketing
Specialist<br />
						Cultural Marketing
Specialist<br />

	Broadcaster<br />
						Editorial
Writer<br />
						Documentary Film
Maker<br />

	Interpreter<br />
						Product
Spokesperson<br />
						Theatrical Press
Agent<br />
						Market
Researcher</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">COMMUNITY SUPPORT SERVICES</span>
<p>Leadership ability plays an important role in achieving success
in this field.  Creativity and independence are valuable for those
in this field as well.  If you have leadership skills and are
creative, here are three occupations to consider.</p>

<hr size="1" />

	<span class="header2">Education
Administrator</span><br />
	<span class="header3">Job Description</span>
	<blockquote>If you like the idea of helping others to
improve their education, you may choose to become an education
administrator. In this job, you would plan educational programs for
those in your community. You would also hire qualified instructors
to teach them. You would need good problem solving skills.  You
would also have to know how to work with large numbers of
people.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Many jobs require a master's or doctoral degree
and experience in a related occupation, such as teaching or
admissions counseling.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of education
administrators was $95,410 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Flight Attendant</span><br />
	<img class="job_pic" src="/images/icons/BG/1216.jpg"
width="100" height="100" border="0" alt="Flight Attendant" />
	<span class="header3">Job Description</span>
	<blockquote>Major airlines are required by law to provide
flight attendants for the safety and security of the traveling
public. Although the primary job of the flight attendants is to
ensure that security and safety regulations are followed, attendants
also try to make flights comfortable and enjoyable for
passengers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Flight attendants must be certified by the
Federal Aviation Administration (FAA). A high school diploma is the
minimum educational requirement, but airlines increasingly prefer
applicants who have a college degree. Experience in dealing with the
public is important because flight attendants must be able to
interact comfortably with strangers and remain calm under
duress.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of flight attendants was
$56,640 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Ticket Agent</span><br />
	<img class="job_pic" src="/images/icons/BG/43274.jpg"
width="100" height="100" border="0" alt="Ticket Agent" />
	<span class="header3">Job Description</span>
	<blockquote>If the idea of helping people get to where they
want to go appeals to you, you might become a ticket agent. As a
ticket agent, you would sell tickets at bus stations, train
stations, and airports. You would assign seats to passengers and
check-in their luggage. You must like working with the public to be
good at this job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most reservation and transportation ticket
agents spend several weeks in company-sponsored training programs
learning the reservation system and other travel-related
information. Good customer service skills and the ability to work
quickly are important. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of ticket agents was
$23,500 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">ART AND DESIGN</span>
<p>To do well in the occupations in this field, you need to be able
to lead.  You also need to have good organization skills.
Creativity is important as well.</p>

<hr size="1" />

	<span class="header2">Museum Director</span><br />
	<img class="job_pic" src="/images/icons/BG/43054.jpg"
width="100" height="100" border="0" alt="Museum Director" />
	<span class="header3">Job Description</span>
	<blockquote>A museum is a building where important relics
and artifacts are kept and displayed for the public to view. The
person who acquires artifacts for a museum to display and makes sure
these artifacts are cared for is the museum director or curator.  As
a museum director, you would manage the staff, plan the budget,
raise funds, and set museum policies. This is a very difficult job.
To succeed in it, you need plenty of energy.</blockquote>
	<span class="header3">Education</span>
	<blockquote>For employment as a curator, most museums
require a master's degree in an appropriate discipline of the
museum's specialty: art, history, or archaeology, or in museum
studies. Many employers prefer a doctoral degree, particularly for
curators in natural history or science museums. Earning two graduate
degrees: one in museum studies (museology) and the other in a
specialized subject, gives a candidate a distinct advantage in this
competitive job market. In small museums, curatorial positions may
be available to individuals with a bachelor's degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of museum directors was
$54,570 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Orchestra Conductor</span><br />
	<span class="header3">Job Description</span>
	<blockquote>An orchestra conductor leads a group of
musicians who play different instruments.  As a conductor, you would
choose the music, set up tours, and direct rehearsals and concerts.
This job requires a person who has musical talent and plays an
instrument well.  It also requires a person who enjoys classical
music.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Formal training may be obtained through private
study with an accomplished musician, in a college or university
music program, or in a music conservatory. You also need to have had
a successful career as a musician.  Most conductors have played in
several orchestras before they gain this position.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of orchestra conductors
was $51,670 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Floral Designer</span><br />
	<img class="job_pic" src="/images/icons/BG/43094.jpg"
width="100" height="100" border="0" alt="Floral Designer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like flowers and plants and know how to
arrange them, you might become a floral designer. As a designer, you
would use different kinds of plants to make bouquets and other
flower arrangements.  You would work directly with the customers, so
good people skills are necessary.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Floral design is the only design occupation that
does not require formal postsecondary training; most floral
designers learn their skills on the job. Employers generally look
for high school graduates who have creativity, a flair for arranging
flowers, and a desire to learn.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of floral designers was
$28,040 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">COMMUNICATION SERVICE</span>
<p>The processes of creating and sharing are important to each of
the occupations in this field. Your creativity and communication
skills are valuable assets to these occupations.</p>

<hr size="1" />

	<span class="header2">Radio Program
Director</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Program directors are in charge of on-air
programming in radio stations. Program directors decide what type of
music will be played, supervise on-air personnel, and often select
the specific songs and the order in which they will be played.
Considerable experience, usually as a disc jockey, is required, as
well as a thorough knowledge of music.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree to become a radio
program director. It will be important to have experience
too.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of radio program
directors was $74,420 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Editorial Writer</span><br />
	<img class="job_pic" src="/images/icons/BG/43276.jpg"
width="100" height="100" border="0" alt="Editorial Writer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like for others to know your opinions on
events in your community or nation, you might become an editorial
writer.  In this job, you would write an opinion about current news
issues or stories.  Your goal would be to get others to agree with
your point of view.  To be good at this job, you must write well.
You must also be willing to work hard to understand the
issues.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a degree in journalism to work for a
newspaper.  Most editorial writers work as reporters for several
years.  Only then are they given the chance to write their
opinions.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of editorial writers was
$46,270 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Theatrical Press
Agent</span><br />
	<span class="header3">Job Description</span>
	<blockquote>A theatrical press agent or public relations
specialist, handles the publicity
for plays.  It is this person who lets people know when a new play
opens in your city or town.  As a theatrical press agent, you would
supervise the creation of posters, social media and newspaper advertisements, and
radio and television commercials.  You would also contact the
newspapers, the television station, and radio stations to have the
advertisements run.  This is an influential job.  Without a
theatrical press agent, people would not know about the play.  No
money would be made.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Opportunities should be best for college
graduates who combine a degree in public relations, journalism, or
another communications-related field with a studies in theatre.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of theatrical press
agents was $61,150 in May 2019.
</blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 11, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 11, 2020). </blockquote>

</div>