<span class="header1">Arts/Communications paired with
Science/Mathematics (BH)</span>

<p>If you scored high in the "B" and "H" categories you are
important to the future. You understand that there are always
possibilities for improvement in any situation.  People like you
have discovered many things about the world. You are an excellent
thinker and are probably a no-nonsense kind of person. You are
scientifically creative and like to ask the question, "Why?" Because
of this, you will look for new ways of communicating and new ideas
to communicate.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree or some post high school courses. It is helpful to have a
master's degree or Ph.D. if you want to work in many of these
occupations.</p>
<p><strong>Courses you may want to take in high school and beyond(in
addition to English & Math):</strong><br />
In high school you should take courses that emphasize math and
science. Any courses dealing with communication will be of great
interest to you and will help prepare you for possible career
opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising<br />
			Art<br />
			Trigonometry<br />
			Marketing
		</td>
		<td>
			Calculus<br />
			Chemistry<br />
			Biology<br />
			Photography
		</td>
		<td>
			Computer Sciences<br />
			Computer Technology<br />
			Communications<br />
			Public Relations
		</td>
		<td>
			Health<br />
			World Languages<br />
			Psychology<br />
			Life Science
		</td>
		<td>
			Sociology<br />
			Physics<br />
			Graphic Arts<br />
			Environmental Science
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. Any club or activity where you can communicate with
others and use your thinking skills is what you will enjoy the
most.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Drama/Theatre<br />
			Debate Team<br />
			Radio/TV Activities<br />
			Math/Science Club
		</td>
		<td>
			Band/Chorus<br />
			Photography Club<br />
			Hospital Volunteer<br />
			Computer Club
		</td>
		<td>
			Newspaper/Yearbook<br />
			Audio-Visual Services<br />
			Environmental Activities
		</td>
		<td>
			Language Club<br />
			Tutoring<br />
			Chess Club<br />
			Music Lessons
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
				Architect Firms<br />
				Archeological Projects<br />
				Computer Sales Company
			</td>
			<td>
				Computer Services<br />
				Electronic Stores<br />
				Engineering Firms
			</td>
			<td>
				Libraries<br />
				Medical Offices<br />
				Newspaper Offices
			</td>
			<td>
				Photographic Laboratories<br />
				Printing Companies<br />
				TV/Radio Stations
			</td>
			<td>
				Theaters<br />
				Veterinary Offices
			</td>
		</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">BH Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="25%">
						<span
class="header2">Design</span><br />
						<em>Museum
Curator<br />
						Architect<br />

	Archeologist<br />

	Gemologist<br />
						Advertising Layout
Artist<br />
						Designer
							<ul>

	<li>Industrial</li>

	<li>Graphic</li>

	<li>Product Development</li>

	<li>Interior</li>

	<li>Hair</li>

	<li>Jewelry</li>

	<li>Lighting</li>
							</ul>
						Watch
Maker<br />
						Inventor</em>
					</td>
					<td width="25%">
						<span
class="header2">Communications</span><br />

	<em>Lawyer<br />
						Technical &
Scientific Publications Editor<br />
						Teacher
							<ul>

	<li>Drama</li>

	<li>Speech</li>

	<li>Communications</li>
							</ul>
						Broadcast News
Analyst<br />
						Writer
							<ul>

	<li>Technical</li>

	<li>Journalist</li>

	<li>Biographer</li>

	<li>Nature</li>

	<li>Textbook</li>
							</ul>
						Video Producer</em>
					</td>
					<td width="25%">
						<span
class="header2">Analysis</span><br />

	<em>Dentist<br />

	Psychologist<br />
						Speech
Pathologist<br />

	Audiologist<br />
						Physical
Therapist<br />
						Marketing
Director<br />
						Military
Officer<br />
						Art
Therapist<br />
						Librarian
							<ul>

	<li>Medical</li>

	<li>Research</li>
							</ul>
						Statistician
							<ul>

	<li>Marketing</li>

	<li>Research</li>

	<li>Television</li>
							</ul></em>
					</td>
					<td width="25%">
						<span
class="header2">Technology</span><br />
						<em>Engineer
							<ul>

	<li>Civil</li>

	<li>Structural</li>

	<li>Industrial</li>
							</ul>
						Photographer
							<ul>

	<li>Biological</li>

	<li>Nature</li>
							</ul>
						Medical
Illustrator<br />
						Landscape
Designer<br />
						Computer
Artist<br />

	Cartographer<br />
						Dental
Technician<br />
						Optician<br />
						Game Inventor</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">DESIGN</span>
<p>In this field, employees must be creative, like to study, and be
good communicators. If this describes you, then you might want to
consider the following occupations.</p>

<hr size="1" />

	<span class="header2">Museum Director</span><br />
	<img class="job_pic" src="/images/icons/BG/43054.jpg"
width="100" height="100" border="0" alt="Museum Director" />
	<span class="header3">Job Description</span>
	<blockquote>A museum is a building where important relics
and artifacts are kept and displayed for the public to view. The
person who acquires artifacts for a museum to display and makes sure
these artifacts are cared for is the museum director or curator.  As
a museum director, you would manage the staff, plan the budget,
raise funds, and set museum policies. This is a very difficult job.
To succeed in it, you need plenty of energy.</blockquote>
	<span class="header3">Education</span>
	<blockquote>For employment as a curator, most museums
require a master's degree in an appropriate discipline of the
museum's specialty: art, history, or archaeology, or in museum
studies. Many employers prefer a doctoral degree, particularly for
curators in natural history or science museums. Earning two graduate
degrees: one in museum studies (museology) and the other in a
specialized subject, gives a candidate a distinct advantage in this
competitive job market. In small museums, curatorial positions may
be available to individuals with a bachelor's degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of museum directors was
$49,850 in May 2019. </blockquote>

		<hr size="1" />

	<span class="header2">Archeologist</span><br />
	<img class="job_pic" src="/images/icons/BH/1325.jpg"
width="100" height="100" border="0" alt="Archeologist" />
	<span class="header3">Job Description</span>
	<blockquote>Archeologists often participate in archeological
digs, looking for clues of past communities. As an archeologist, you
would work with others to find artifacts from people who lived in
the past. This is a difficult job.  You would not only look for
clues that lead to artifacts, you would also oversee assistants at
the dig as well. This can be a very exciting occupation.  The digs
often occur in distant and unusual places. Sometimes the artifacts
found are very valuable.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a master's degree for this
job.  Most archeologists have a Ph.D.  This is an occupation that
needs very educated people.  Those who have a bachelor's degree work
as assistants to archeologists.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of archeologists was
$63,670 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Industrial Designer</span><br />
	<img class="job_pic" src="/images/icons/BH/C0777_50.jpg"
width="100" height="100" border="0" alt="Industrial Designer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like to create things that others want,
you might become an industrial designer.  An industrial designer
plans and makes manufactured products such as toys, cars, or
exercise equipment for others to buy. To succeed at this occupation,
you need to be artistic. You also need to understand what consumers
want to buy.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is required for most entry-
level commercial and industrial design positions. Many designers
also pursue a master's degree to increase their employment
opportunities.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of industrial designers
was $68,890 in May 2019.
</blockquote>

<hr size="1" />

<span class="header1">COMMUNICATION</span>
<p>Occupations in this field are for people who enjoy investigating
clues and are able to speak and write well.  People who do well in
these occupations like to tell others what they have discovered.</p>

<hr size="1" />

	<span class="header2">Lawyer</span><br />
	<img class="job_pic" src="/images/icons/BH/43286.jpg"
width="100" height="100" border="0" alt="Lawyer" />
	<span class="header3">Job Description</span>
	<blockquote>Lawyers give legal advice and assistance to
people.  They represent their clients in court and in other legal
matters.  There are many kinds of lawyers.  Some work with people
who have been arrested and represent them in court.  There are also
corporate lawyers who take care of any legal issues that are related
to running a business.  There are real estate lawyers, family
lawyers, and environmental lawyers as well.  What these jobs have in
common is that the lawyer is responsible for helping his/her clients
in matters that relate to the law.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree plus three years of
law school to become a lawyer. Also a lawyer must pass an exam known
as the bar. A lawyer must be very sharp and continue to learn about
the law, because laws often change.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of lawyers was $122,960
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Broadcast News
Analyst</span><br />
	<span class="header3">Job Description</span>
	<blockquote>If you like to share your opinions and want to
persuade others to think as you do, you might become a broadcast
news analyst.  As a news analyst, you would present the news story
on the television or radio. You would then explain how you think
this will affect your viewers or listeners.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most employers prefer individuals with a
bachelor's degree in journalism or mass communications, but some
hire graduates with other majors. They look for experience at school
newspapers or broadcasting stations, and internships with news
organizations.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of broadcast news
analysts was $46,270 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Biographer</span><br />
	<img class="job_pic" src="/images/icons/BH/43219.jpg"
width="100" height="100" border="0" alt="Biographer" />
	<span class="header3">Job Description</span>
	<blockquote>If you have ever read a book about the life of
someone important, you have read a biography. The person who wrote
the biography is a biographer. As a biographer, you would research a
person's life and then write a book about him or her. To get your
information, you would interview people who know or knew the
person.  You would also use documents from a library or family album
to learn about the person's life.  It would be important to know
where to look for information. Good writing skills are essential as
well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A biographer usually has a degree in journalism
or English.  You need to combine writing courses and as much
experience as possible to prepare for this work.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of biographers was
$63,200 in May 2019.</blockquote>

<hr size="1" />

<span class="header1">ANALYSIS</span>
<p>The occupations in this field need someone who is naturally
curious and can use the scientific method to solve problems.</p>

<hr size="1" />

	<span class="header2">Speech Pathologist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>A speech pathologist helps people who have
trouble speaking.  As a speech pathologist, you would teach your
clients to shape their mouth and use their tongue correctly when
speaking. You would also help them to make distinctions between
words so that others can understand them.  Some speech pathologists
work with children who are having trouble learning to speak
clearly.  Others work with adults who have had a stroke or other
medical problem.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A master's degree is the most common level of
education among speech-language pathologists. Licensure or
certification requirements also exist, but vary by
State.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of speech pathologists
was $79,120 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Health Science
Librarian</span><br />
	<img class="job_pic" src="/images/icons/BH/43282.jpg"
width="100" height="100" border="0" alt="Health Science Librarian" />
	<span class="header3">Job Description</span>
	<blockquote>You probably know that a librarian works in a
library and keeps books and other library materials in order. What
you may not know is that there are specific types of librarians. One
type is a health science librarian.  As a health science librarian,
you would keep the large amount of information found in the medical
field available and organized.  You would also help doctors, nurses,
and other health care workers find information about health issues
or diseases. This is an important job.  To do it well, you must be
able to handle and organize large amounts of
information.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a master's degree in library
science to apply for this job.  Volunteer or work in a library to
get experience with the way information is organized.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of librarians was $59,500
in May 2019. </blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY</span>
<p>Occupations in this field require good communication skills.
They also require an interest in technology.  People who work in
this field must have an eye for beauty and must also be able to work
with
details.</p>

<hr size="1" />

	<span class="header2">Civil Engineer</span><br />
	<img class="job_pic" src="/images/icons/BH/43243.jpg"
width="100" height="100" border="0" alt="Civil Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>The word "civil" describes anything that has to
do with a city or with civilization. A civil engineer plans and
builds structures that make our lives easier. As a civil engineer,
you would plan and oversee the building of roads, bridges, and
airports. You would also make sure that the structures were safe for
people to use.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree to become a civil
engineer. Many people enter into this field with a master's degree.
Civil engineers can work in several specialty fields.  Each has its
own education requirements.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of civil engineers was
$87,060 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Photographer</span><br />
	<img class="job_pic" src="/images/icons/BH/43060.jpg"
width="100" height="100" border="0" alt="Photographer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like taking pictures and have a
good "eye", you might become a professional photographer. A
photographer combines communication skills and technology.  In this
job, you would take pictures of people, things, or events. You must
be creative.  Your goal is to show people something they might not
have seen otherwise.  You must understand the technical aspects of
the camera. You must also know how to use computer software to edit, 
organize and publish pictures. Many photographers work for themselves, 
so it is helpful to understand how a small business works.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree in photography or the visual
arts can develop your basic skills.  But, you also need to be
creative to succeed in this field.  Spend as much time as possible
looking at pictures and taking your own. Getting involved in
photography clubs and working in photo shops and labs will help you
learn more about using your camera to capture successful
photographs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of photographers was
$36,280 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Dental Technician</span><br />
	<span class="header3">Job Description</span>
	<blockquote>A dental technician makes appliances and devices used by the
dentist in treating patients. As a dental technician you would make
crowns, bridges, and dentures for people's mouths.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Dental laboratory technicians typically need a high 
school diploma and on-the-job training. They begin by learning
simple tasks, such as pouring plaster into an impression, and
progress to more complex procedures, such as making porcelain crowns
and bridges. Becoming a fully trained technician requires an average
of three to four years, depending upon the individual's aptitude and
ambition, but it may take a few years more to become an accomplished
technician. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of dental technicians was
$37,370 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 11, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 11, 2020). </blockquote>

</div>
