<span class="header1">Arts/Communications paired with Social Helping
(BI)</span>

<p>Your high scores in "B" and "I" show that you bring together many
characteristics that can be useful to people. You are a creative and
outgoing person, and you enjoy helping others with their problems.
You also have the ability to communicate your ideas and thoughts
clearly.  You may be a person who likes to teach or to plan fund
raising programs for charity.  For you, what is important is that
you are helping others.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree or some post high school courses.  It is helpful to have a
master's degree or Ph.D. if you want to work in many of these
occupations.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that help you understand
people. Any courses in social studies or social sciences will be of
great interest to you and help prepare you for possible career
opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising/Marketing<br />
			Psychology<br />
			Computer Sciences<br />
			Communications
		</td>
		<td>
			Computer Technology<br />
			Broadcast/Video<br />
			Public Relations<br />
			Health/Nutrition
		</td>
		<td>
			Graphic Arts<br />
			Home Economics<br />
			Religion<br />
			Photography
		</td>
		<td>
			Law<br />
			History<br />
			Music<br />
			Art
		</td>
		<td>
			World Languages<br />
			Sociology
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. Any club or activity where you can share your ability to
communicate and use your people skills is what you will enjoy the
most.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Drama/Theatre<br />
			Debate Team<br />
			Childcare/Eldercare<br />
			Teaching Assistant
		</td>
		<td>
			Band/Chorus<br />
			Photography Club<br />
			Hospital Volunteer<br />
			Church Activities
		</td>
		<td>
			Newspaper/Yearbook<br />
			Audio Visual Services<br />
			Peer Counselor<br />
			Tutoring
		</td>
		<td>
			Language Club<br />
			Radio/TV Activities<br />
			Camp Counselor<br />
			Social Clubs
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising Agencies<br />
			Camp Programs<br />
			Church Programs<br />
			Restaurants
		</td>
		<td>
			Day Care Centers<br />
			Graphic Design Firms<br />
			Libraries<br />
			Special Olympics
		</td>
		<td>
			Life Guarding<br />
			Newspaper Offices<br />
			Photography Studios<br />
			Theaters
		</td>
		<td>
			Preschool Programs<br />
			Printing Companies<br />
			Recreation Department
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">BI Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Creative Education</span><br />
						<em>Clergy
							<ul>

	<li>Brother</li>

	<li>Minister</li>

	<li>Nun</li>

	<li>Priest</li>

	<li>Rabbi</li>
							</ul>
						Teacher/Professor
							<ul>

	<li>Art</li>

	<li>Drama</li>

	<li>Dance</li>

	<li>Communications</li>

	<li>Music</li>

	<li>Pre-school</li>

	<li>Religion</li>

	<li>Special Education</li>

	<li>Writing</li>
							</ul>
						Teacher's
Aide<br />
						Library
Assistant</em>
					</td>
					<td width="33%">
						<span
class="header2">Creative Helping</span><br />

	<em>Psychologist<br />
						Public Relations
Counselor<br />
						Marriage
Counselor<br />
						Art/Music
Therapy<br />
						Interior
Designer<br />
						Cosmetologist
							<ul>

	<li>Manicurist</li>

	<li>Barber</li>
							</ul>
						Massage
Therapist<br />
						Audiovisual
Librarian<br />
						Advertising
Production Specialist<br />
						Adventure Travel
Coordinator<br />
						Caterer<br />
						Retail
Salesperson</em>
					</td>
					<td width="33%">
						<span
class="header2">Creative Performance</span><br />
						<em>Writer
							<ul>

	<li>Author</li>

	<li>Playwright</li>

	<li>Poet</li>

	<li>Song</li>

	<li>Screen</li>

	<li>Travel</li>
							</ul>
						Chef<br />

	Photographer<br />
						Radio/TV Talk Show
Host<br />
						Police
Artist<br />

	Actress/Actors<br />
						Musician<br />
						Singer<br />
						Model<br />
						Comedian</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">CREATIVE EDUCATION</span>
<p>The occupations in this field need people who communicate well
and want to help people solve problems. Let's look at three
occupations that may interest you.</p>

<hr size="1" />

	<span class="header2">Art Teacher</span><br />
	<img class="job_pic" src="/images/icons/BI/C2126_01.jpg"
width="100" height="100" border="0" alt="Art Teacher" />
	<span class="header3">Job Description</span>
	<blockquote>An art teacher helps students in his/her class
to enjoy the beauty in art and to develop any new artistic skills.  As an art teacher, you would write lesson plans,
teach classes, and possibly sponsor the school's art club. You would
need to have skill in at least one area of art. But what is most
important is that you are able to help students get in touch with
their own interests and skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To teach in the public schools you need at
least a bachelor's degree. You also need a teaching license or
certificate.  Most public school teachers earn a master's degree as
they continue to teach.  Teachers love to learn and spend a great
deal of time as students themselves.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage in May 2019 of art teachers
in elementary and middle schools was $59,420. High school teachers' salary was $61,660, and $83,220 was the median annual salary in post-secondary settings. </blockquote>

<hr size="1" />

	<span class="header2">Special Education
Teacher</span><br />
	<span class="header3">Job Description</span>
	<blockquote>A special education teacher works with students
who have learning, physical, mental, or emotional disabilities.  As a special
education teacher, you would write individual lesson plans and teach
your students.  You would need to be able to encourage students to
work hard even when they found the work difficult. You must also be
able to help them get in touch with their interests and
skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To teach in public schools you need at least a
bachelor's degree. You also need a teaching license or certificate.
Most public school teachers earn a master's degree as they continue
to teach. Teachers love to learn and spend a great deal of time as
students themselves.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of special education
teachers was $61,030 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Teacher
Assistant/Paraprofessional</span><br />
	<img class="job_pic" src="/images/icons/BI/Ph43319.jpg"
width="100" height="100" border="0" alt="Teacher's
Aide/Paraprofessional" />
	<span class="header3">Job Description</span>
	<blockquote>The job of a teacher's assistant is similar to that of a teacher. As a
teacher's assistant, you would help a licensed teacher care for his/her students,
grade papers, perform clerical duties, and prepare instructional
materials.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Many teacher assistants need only a high school
diploma and on-the-job training. A college degree or related
coursework in child development improves job opportunities, however.
In fact, teacher assistants who work in Title 1 schools, those with
a large proportion of students from low-income households, must have
college training or proven academic skills. They face new Federal
requirements as of 2006: assistants must hold a 2-year or higher
degree, have a minimum of 2 years of college, or pass a rigorous
State or local assessment. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of teacher assistants was
$27,920 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">CREATIVE HELPING</span>
<p>If you want to help others and are creative, the occupations in
this field may be appropriate for you. The goal of these occupations
is to help others reach a goal. Let's look at three occupations that
may interest you.</p>

<hr size="1" />

	<span class="header2">Psychologist</span><br />
	<img class="job_pic" src="/images/icons/BI/43119.jpg"
width="100" height="100" border="0" alt="Psychologist" />
	<span class="header3">Job Description</span>
	<blockquote>There are different kinds of psychologists.
Some focus on testing students. These are educational psychologists
who might test a student's IQ, or to see if a student has a learning
disability. Some psychologists focus on helping people who are
having psychological problems. These are clinical psychologists who
help their clients to talk about and work through any problems they
may be having. Then they work with the person to develop a plan that
will help solve the problems. If you were either kind of
psychologist, you could work in private practice, either on your own
or in a small group. You could also work in a school, hospital, or
treatment center.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A doctoral degree usually is required for
independent practice as a psychologist. A specialist degree or its
equivalent is required in most states for an individual to work as a
school psychologist, although a few states still credential school
psychologists with master's degrees. People with a master's degree
in psychology may work as industrial-organizational psychologists.
A bachelor's degree in psychology qualifies a person to assist
psychologists and other professionals in community mental health
centers, vocational rehabilitation offices, and correctional
programs. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of psychologists was
$80,370 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Interior Designer</span><br />
	<img class="job_pic" src="/images/icons/BI/43032.jpg"
width="100" height="100" border="0" alt="Interior Designer" />
	<span class="header3">Job Description</span>
	<blockquote>If you have a skill for making a room look its
best, you might become an interior designer. Interior designers help
their clients decorate the inside of homes, offices, and
businesses.  In this job you would decorate rooms working within a
budget. To do this, you would have to know the best prices on
furniture, drapes, and other room accessories.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Postsecondary education, especially a bachelor's
degree, is recommended for entry-level positions in interior design.
Training programs are available from professional design schools or
from colleges and universities and usually take 2 to 4 years to
complete.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of interior designers was
$56,040 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Retail Salesperson</span><br />
	<img class="job_pic" src="/images/icons/BI/1302.jpg"
width="100" height="100" border="0" alt="Retail Salesperson" />
	<span class="header3">Job Description</span>
	<blockquote>A retail salesperson answers customers' questions and helps them decide what to buy.  As a retail
salesperson, you would "ring up" the sale on a cash register or
computer.  You would search for items that customers asked for.  You
would also restock the shelves as needed. Other duties might include
closing the cash register at the end of a shift and keeping the
store neat.  Sometimes you will need to be pleasant with people even
when they seem to be demanding.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Retail salespeople typically learn their skills
through on-the-job training. Although advancement opportunities are
limited, having a college degree or a great deal of experience may
help retail salespersons move into management positions.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of retail salespersons
was $25,440 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">CREATIVE PERFORMANCE</span>
<p>To enter  occupations in this field, you need talent and the
courage to perform. It takes hard work and determination to succeed
in the field of creative performance. Here are three occupations
that might interest you.</p>

<hr size="1" />

	<span class="header2">Screenwriter</span><br />
	<img class="job_pic" src="/images/icons/BI/43336.jpg"
width="100" height="100" border="0" alt="Screenwriter">
	<span class="header3">Job Description</span>
	<blockquote>A screenwriter does not perform on stage, but
his/her work is still important. As a screenwriter, you would write
scripts for movies and television programs. You would
search for interesting topics and create stories
based on these. You would work closely with producers and
directors.  You might even work with other writers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Although many screenwriters have college
degrees, talent and creativity are even more important determinants
of success in the industry. Screenwriters need to develop creative
writing skills, a mastery of film language, and a basic
understanding of filmmaking. In addition to colleges and technical
schools, many independent centers offer training programs on various
aspects of filmmaking, such as screenwriting, film editing,
directing, and acting. For example, the American Film Institute
offers training in directing, production, cinematography,
screenwriting, editing, and production design.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of screenwriters was $63,200
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Chef</span><br />
	<img class="job_pic" src="/images/icons/BI/43009.jpg"
width="100" height="100" border="0" alt="Chef" />
	<span class="header3">Job Description</span>
	<blockquote>If you became a chef, you would use your
creativity to prepare new kinds of dishes or meals for others to
eat. You would work in a kitchen creating new recipes, preparing the
meals, and overseeing the staff. Creativity is important to a
chef.</blockquote>
	<span class="header3">Education</span>
	<blockquote>No college degree is needed. Most chefs learn
their craft at schools called "culinary institutes." Chefs who do
not train at a culinary institute are put through a tough on-the-job
training program while working in a kitchen at another
job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of chefs was $51,530 in
May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Musician</span><br />
	<img class="job_pic" src="/images/icons/BI/C1926_03.jpg"
width="100" height="100" border="0" alt="Musician" />
	<span class="header3">Job Description</span>
	<blockquote>A musician is someone who plays an instrument or
sings. As a musician, you would perform in front of other people.
Most musicians practice and work with other musicians.  To succeed
as a musician you must be creative and have musical talent. You
must also be able to work with others as few musicians play music
alone.  In addition, you will want to understand business.  Many
musicians are expected to manage their own careers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Musicians need extensive and prolonged training
and practice to acquire the necessary skills and knowledge to
interpret music at a professional level. Like other artists,
musicians and singers continually strive to improve their abilities.
Formal training may be obtained through private study with an
accomplished musician, in a college or university music program, or
in a music conservatory. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median wage of musicians was $30.39 per hour in May 2019.
</blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 10, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 10, 2020). </blockquote>

</div>
