<span class="header1">Business/Management paired with
Clerical/Administrative (CD)</span>

<p>If you had a high score in categories "C" and "D" you have a head
for business. You are a good thinker and know how to get what you
want. You are probably goal-oriented and prefer to know what you are
working toward.  You may be an outgoing person who likes to lead, or
you may be a quiet person who likes working with numbers. Either
way, you know how get the job done. You will benefit from learning
to understand business.</p>
<p>Most occupations in this pairing require a bachelor's degree.
Many others require some post-high school courses.  In most of the
occupations listed under this pairing, the more education you have
the better your chances of employment. The competition for these
jobs is tough. You will need to give yourself every advantage
possible.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you will want to take courses that allow you to
express your thoughts and ideas.  You will also want to take courses
that help you to understand others and the world of business.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Technology Education<br />
			Office Administration<br />
			Computer Sciences<br />
			Advertising/Marketing
		</td>
		<td>
			Business Law<br />
			Public Relations<br />
			Communications<br />
			Computer Technology
		</td>
		<td>
			Computer Programming<br />
			Government/Civics<br />
			Office Technology<br />
			Business Education
		</td>
		<td>
			Economics<br />
			Advertising<br />
			Sociology<br />
			Accounting
		</td>
		<td>
			World Languages<br />
			Business Math<br />
			Bookkeeping
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
Experience is an important thing! When you are looking for ways to
fill your time with a fun activity or a part-time job, think about
working in places where you are solving problems and using your
ability to negotiate. Don't forget to find a place where you can
show how dependable you are.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Junior Achievement<br />
			Newspaper/Yearbook<br />
			Office Assistant
		</td>
		<td>
			Class Officer<br />
			Exchange Programs<br />
			Teaching Assistant
		</td>
		<td>
			Audio/Visual Services<br />
			Computer Assistant<br />
			Library Assistant
		</td>
		<td>
			Future Business Leaders<br />
			Community Volunteer
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting Firms<br />
			Theaters<br />
			Radio/TV Studios<br />
			Photography Studios
		</td>
		<td>
			Libraries<br />
			Newspapers<br />
			Retail Stores<br />
			Receptionist
		</td>
		<td>
			Data Entry/Processing<br />
			Advertising Agencies<br />
			Temporary Agencies<br />
			Graphic Design Firms
		</td>
		<td>
			Printing Companies<br />
			Telephone Sales<br />
			Clerical Offices<br />
			Restaurants
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">CD Career Possibilities</span><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Business Sales</span><br />
						<em>Computer Sales
Representative<br />
						Business Machine
Sales Representative<br />
						Insurance Sales
Agent<br />
						Real Estate
Agent/Broker<br />
						Personnel
Consultant<br />
						Analyst
							<ul>

	<li>Marketing</li>

	<li>Stock</li>
							</ul>
						Sales Account
Supervisor<br />
						Travel
Agent<br />
						Sales
Support<br />
						Cashier</em>
					</td>
					<td width="33%">
						<span
class="header2">Business Administrative</span><br />
						<em>Personnel
Director<br />
						Human Resources
Manager<br />
						Data Processing
Manager<br />
						Facilities
Manager<br />
						Office
Manager<br />
						Retail
Buyer<br />
						Employee Benefits
Manager<br />
						Executive
Secretary<br />

	Underwriter<br />
						Stock Transfer
Clerk<br />
						Personnel Clerk</em>
					</td>
					<td width="33%">
						<span
class="header2">Business Financial</span><br />
						<em>Chief Financial
Officer<br />

	Statistician<br />
						Economic
Researcher<br />
						Financial
Planner<br />
						Bank Loan
Officer<br />
						Auditor<br />

	Bookkeeper<br />
						Tax
Preparer<br />
						Clerk
							<ul>

	<li>Accounting</li>

	<li>Statistical</li>
							</ul>
						Bank Teller</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">BUSINESS SALES</span>
<p>People who do well in this occupation are self-starters and can
be responsible for their own schedule.  In addition, they like
meeting new people.  If this describes you, consider the occupations
in this field.</p>

<hr size="1" />

	<span class="header2">Insurance Agent</span><br />
	<img class="job_pic" src="/images/icons/CD/C506005.jpg"
width="100" height="100" border="0" alt="Insurance Agent" />
	<span class="header3">Job Description</span>
	<blockquote>An insurance agent sells and services insurance
policies.  People buy insurance for their homes, cars, and even
health.  It protects them from losing a lot of money if something
happens to their possessions or themselves.  But choosing the right
insurance can be difficult.  As an insurance agent, you would help
people decide what type of insurance policy they need. You would
also help them to file a claim to collect money on their policy when
necessary.</blockquote>
	<span class="header3">Education</span>
	<blockquote>For insurance sales agent jobs, many companies
and independent agencies prefer to hire college graduates -
especially those who have majored in business or economics. High
school graduates may be hired if they have proven sales ability or
have been successful in other types of work.  A state license is
required.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of insurance agents was
$50,940 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Travel Agent</span><br />
	<img class="job_pic" src="/images/icons/CD/1216.jpg"
width="100" height="100" border="0" alt="Travel Agent">
	<span class="header3">Job Description</span>
	<blockquote>When people go on trips, they often make
transportation and hotel reservations. A travel agent is important
to a traveler. If you were a travel agent, you would work very
closely with the public making arrangements for vacations or
business trips. You might work for a hotel or an airline. A good
agent must be able to work well with people and understand the needs
of a traveler.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The minimum requirement for those interested in
becoming a travel agent is a high school diploma or equivalent. Much
of the training is provided on the job, a significant part of which
consists of instruction on how to use reservation systems. Training
specific to becoming a travel agent is available at many
vocational schools, online, and in community colleges. A few
colleges offer bachelor's or master's degrees in travel and tourism.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of travel agents was
$40,660 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Cashier</span><br />
	<img class="job_pic" src="/images/icons/CD/1142.jpg"
width="100" height="100" border="0" alt="Cashier">
	<span class="header3">Job Description</span>
	<blockquote>A cashier takes the money of customers who want
to buy something from a store.  As a cashier, you would ring up the
items the customer wanted to buy. You would handle cash, checks, and
credit and debit card purchases. It would be important that the
amount of money in the cash drawer matched the amount on the
receipts in the machine.</blockquote>
	<span class="header3">Education</span>
	<blockquote>If you were a cashier you would be given on-the-
job training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of cashiers was $23,650
in May 2019. </blockquote>

<hr size="1" />

<span class="header1">BUSINESS ADMINISTRATION</span>
<p>In the occupations in this field, you would make sure that others
did their jobs correctly, and that the business actions ran
smoothly. If you enjoy overseeing the work of others, consider the
occupations in this field.  Here are three examples.</p>

<hr size="1" />

	<span class="header2">Human Resources
Manager</span><br />
	<img class="job_pic" src="/images/icons/CD/1372.jpg"
width="100" height="100" border="0" alt="Human Resource Manager">
	<span class="header3">Job Description</span>
	<blockquote>A human resources manager helps to develop and
carry out a company's "people" policies.  He/she serves as a link
between employees and upper management. As a human resources
manager, you might hire or fire employees.  You might also write job
descriptions and train new employees.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The educational backgrounds of human resources,
training, and labor relations managers and specialists vary
considerably, reflecting the diversity of duties and levels of
responsibility. In filling entry-level jobs, many employers seek
college graduates who have majored in human resources, human
resources administration, or industrial and labor relations. Other
employers look for college graduates with a technical or business
background or a well-rounded liberal arts education.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of human resources
managers was $116,720 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Employee Benefits
Manager</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Companies often provide their employees with
benefits such as paid vacation time and health insurance. These are
called employee benefits.  Employee benefits managers and
specialists manage the company's employee benefits program, notably
its health insurance and pension plans. An employee benefits manager
helps employees to understand their benefits. She/he also helps them
to use these benefits to their advantage. As an employee benefits
manager, you would need to be well organized. You would also need to
enjoy working with people.</blockquote>
	<span class="header3">Education</span>
	<blockquote> College graduates who have earned certification from professional organizations such as the International Foundation of Employee Benefit Plans
should have the best job opportunities. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of employee benefits
managers was $122,270 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Brokerage Clerk</span><br />
	<img class="job_pic" src="/images/icons/CD/43328.jpg"
width="100" height="100" border="0" alt="Brokerage Clerk">
	<span class="header3">Job Description</span>
	<blockquote>For a typical investor, buying and selling stock
is as easy as calling a broker on the phone or entering the trade
into a computer. Behind the scenes, however, buying and selling
stock is more complicated, involving trade execution and a fair
amount of paperwork. While brokers do some of this work themselves,
much of it is delegated to brokerage clerks whose tasks include
computing and recording data pertaining to securities transactions,
contacting customers, taking orders, and informing clients of
changes to their accounts.

</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some brokerage clerk positions require only a
high school diploma, but graduates from 2- and 4-year college degree
programs are increasingly preferred. Positions dealing with the
public, such as broker's or sales assistant, and those dealing with
more complicated financial records are especially likely to require
a college degree. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of brokerage clerks was
$40,540 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">BUSINESS FINANCIAL</span>
<p>People who do well in the occupations in this field enjoy working
with money. They also are good organizers and can keep track of
details.</p>

<hr size="1" />

	<span class="header2">Loan Officer</span><br />
	<img class="job_pic" src="/images/icons/CD/C506008.jpg"
width="100" height="100" border="0" alt="Loan Officer">
	<span class="header3">Job Description</span>
	<blockquote>A loan officer works for a bank or lending
company. As a loan officer, you help customers fill out loan
applications and make sure that the information on the application
is correct. You would then see if the people wanting the loan met
your company's guidelines for a loan. If so, you would help to
process the loan.  If not, you would help them to understand why
they did not get the loan.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Loan officers usually need a bachelor's degree
in finance, economics, or a related field. Those who work with home loans must be licensed. Previous banking,
lending, or sales experience is also highly valued by
employers.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of loan officers was
$63,270 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Bookkeeper</span><br />
	<img class="job_pic" src="/images/icons/CD/1287.jpg"
width="100" height="100" border="0" alt="Bookkeeper">
	<span class="header3">Job Description</span>
	<blockquote>All companies must keep detailed records of
their cash flow and how much money they earn. As a bookkeeper, you
would be responsible for keeping this information. You would have to
enjoy working with numbers and be good at keeping track of details
to do this job well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.
Most companies offer on-the-job training. Courses in business math
and computer science from a vocational school can help you to get a
job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of bookkeepers was
$41,230 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Bank Teller</span><br />
	<img class="job_pic" src="/images/icons/CD/1371.jpg"
width="100" height="100" border="0" alt="Bank Teller">
	<span class="header3">Job Description</span>
	<blockquote>A bank teller handles large sums of money. As a
bank teller, you would help customers with their deposits and
withdrawals. Banks look for people who work well with customers,
have good math skills, and know the importance of keeping detailed
records.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A high school diploma is needed to be a bank
teller. A teller is given on-the-job training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of bank tellers was
$31,230 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 10, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 10, 2020). </blockquote>

</div>
