<span class="header1">Business/Management paired with
Protective/Military Service (CE)</span>

<p>If you show high scores in categories "C" and "E", you are a
person who knows how to make things happen. You are adventurous and
like exploring new possibilities.  You especially like to take risks
and try new things.  You make a good leader. You will want to
combine your strong interest in business with your adventurous
spirit.</p>
<p>Many of the occupations in this pairing require some sort of
specialized training after high school. Some require college level
courses.  Others require training programs provided by the company
or firm that hires you.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that allow you to continue
to learn about business. You will want to take courses that help you
to understand people as well.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising<br />
			Sociology<br />
			Life Sciences<br />
			Economics
		</td>
		<td>
			Business Math<br />
			Political Science<br />
			Physical Education<br />
			Communications
		</td>
		<td>
			Physics<br />
			Geography<br />
			Psychology<br />
			Marketing
		</td>
		<td>
			Government/Civics<br />
			Environmental Science<br />
			Technology Education
		</td>
		<td>
			Business Law<br />
			Public Relations<br />
			Business Education
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations you
may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. You will enjoy any club or activity that involves
working with others as a part of a team.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Jr. Achievement<br />
			Exchange Programs<br />
			Computer Activities<br />
			Future Business Leaders
		</td>
		<td>
			Yearbook<br />
			ROTC<br />
			Scouts<br />
			Band
		</td>
		<td>
			Class Officer<br />
			Flight Training<br />
			Parks/Recreation<br />
			Camp Activities
		</td>
		<td>
			Community Volunteer<br />
			Martial Arts<br />
			Athletics
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time job:</strong><br />
These places may offer valuable opportunities to help you decide what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising Agencies<br />
			Data Processing<br />
			Graphic Design<br />
			Life Guarding<br />
			Photography Studios<br />
		</td>
		<td>
			Temporary Agencies<br />
			Camp Counseling<br />
			Equipment Operation<br />
			Radio Stations
		</td>
		<td>
			Construction Sites<br />
			Equipment Repair<br />
			Libraries<br />
			Printing Companies
		</td>
		<td>
			Recreation/Parks<br />
			Gyms<br />
			Newspapers<br />
			TV Studios
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">CE Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Management</span><br />
						<em>Education
Director<br />
						Operations
Manager<br />
						Urban
Planner<br />
						Food Service
Manager<br />
						Air Traffic
Controller<br />
						Funeral
Director<br />
						Officer's Club
Manager<br />
						Construction
Manager<br />
						Store
Manager<br />
						Aircraft Sales
Representative<br />
						Theater
Director<br />
						Auto Detailer</em>
					</td>
					<td width="33%">
						<span
class="header2">Finance & Business Development</span><br />

	<em>Auditor<br />
						Management
Consultant<br />
						Benefits
Administrator<br />
						Financial Aid
Officer<br />
						Financial
Planner<br />
						Organizational
Developer<br />
						Contract
Administrator<br />
						Revenue
Officer<br />
						Bank
Examiner<br />
						Job Development
Specialist<br />
						Stock
Broker<br />
						Payroll
Specialist</em>
					</td>
					<td width="33%">
						<span
class="header2">Law & Civil Service</span><br />

	<em>Attach&eacute;<br />
						Foreign Service
Officer<br />
						Environmental
Project Manager<br />
						Communications
Manager<br />
						Environmental
Protection Specialist<br />
						Secret Service
Agent<br />
						FBI Agent<br />
						Police
Agent<br />
						Fire
Chief<br />
						Intelligence
Officer<br />
						Recruiter<br />
						Safety
Engineer<br />
						Firefighter</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">MANAGEMENT</span>
<p>These occupations need people who are good leaders and understand
the importance of detail. If you fit this description, then you
might want to consider the occupations in this field. Here are three
examples.</p>

<hr size="1" />

	<span class="header2">Food Service Manager</span><br />
	<span class="header3">Job Description</span>
	<blockquote>A food service manager oversees the operation of
a kitchen or dining hall.  As a food service manager, you would plan
menus, create a budget, and schedule the staff.  If military life
interests you, you could work in the kitchen on a military base.
Otherwise, you might work at any location that has a kitchen and
serves food to large numbers of people. This includes schools,
hospitals, and nursing homes.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Many food service management companies and
restaurant chains recruit management trainees from 2- and 4-year
college hospitality management programs, which require internships
and real-life experience to graduate. Some restaurant chains prefer
to hire people with degrees in restaurant and institutional food
service management, but they often hire graduates with degrees in
other fields who have demonstrated experience, interest, and
aptitude. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of food service managers
was $55,320 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Construction Manager</span><br /> 
	<img class="job_pic" src="/images/icons/CE/1140.jpg"
width="100" height="100" border="0" alt="Construction Manager" />
	<span class="header3">Job Description</span>
	<blockquote>A construction manager works at a building site
to see that construction is done correctly and remains on schedule.
As a construction manager, you would schedule the work day for the
other construction workers. You would also schedule specialized
workers such as plumbers or electricians. You would be responsible
for the workers' safety. You would also be responsible for the
equipment and budgets. It would be your job to see that the building
was completed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers increasingly prefer to hire
construction managers with a bachelor's degree in construction
science, construction management, building science, or civil
engineering, although it is also possible for experienced
construction workers to move up to become construction
managers.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of construction managers
was $95,260 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Collision Repair Technician</span><br />
	<img class="job_pic" src="/images/icons/CE/C29095.jpg"
width="100" height="100" border="0" alt="Collision Repair
Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Most of the damage resulting from everyday
vehicle collisions can be repaired, and vehicles can be refinished
to look and drive like new. Automotive body repairers, often called
collision repair technicians, straighten bent bodies, remove dents,
and replace crumpled parts that cannot be fixed. It is very
strenuous work so you would need to be in good physical condition.
You would also need to be detail oriented.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Collision repair programs may be offered in high
school or in postsecondary vocational schools and community
colleges. Trade and technical school programs typically award
certificates to graduates after six months to a year of collision
repair study. Some community colleges offer 2-year programs in
collision repair. On-the-job training is also offered in some
automotive repair shops.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of collision repair
technicians was $42,350 in May 2019.
</blockquote>

<hr size="1" />

<span class="header1">FINANCE & BUSINESS DEVELOPMENT</span>
<p>People in the occupations in this field help others to make
money. Here are three examples of the types of occupations in this
field.</p>

<hr size="1" />

	<span class="header2">Management
Consultant</span><br />
	<img class="job_pic" src="/images/icons/CE/1126.jpg"
width="100" height="100" border="0" alt="Management Consultant" />
	<span class="header3">Job Description</span>
	<blockquote>Many companies need advice on how to invest and
use their money. A financial management consultant looks for new
ways for a company to make and use money wisely.  If you were a
diversity management consultant, you would help companies to manage
different people.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A college degree is needed to become a
management consultant.  Most companies look for those with degrees
in business, math, or a computer-related area and several years of related experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of management consultants
was $85,260 in May 2019. </blockquote>

<hr size="1" />


	<span class="header2">Management Analyst
</span><br />
	<img class="job_pic" src="/images/icons/CE/1249.jpg"
width="100" height="100" border="0" alt="Management Analyst" />
	<span class="header3">Job Description</span>
	<blockquote>Companies often look for ways to improve their
day-to-day operations. As a management analyst, you would
look at the organizational plan of a company to see what changes
were needed. For example, you might find the company should provide
better employee benefits. Or, you might find it should hire new
people or reduce the number of people employed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Entry requirements for management analysts vary.
For some entry-level positions, a bachelor's degree is sufficient.
For others, a master's degree, specialized expertise, or both is
required.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of management analysts was $85,260 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Financial Aid
Officer</span><br />
	<img class="job_pic" src="/images/icons/CE/1202.jpg"
width="100" height="100" border="0" alt="Financial Aid Officer" />
	<span class="header3">Job Description</span>
	<blockquote>A financial aid officer (or advisor) works with students who
need help in paying their college tuition. In this job, you would
let students know what kinds of loans or grants might be available to them. You would help them to complete the necessary application
forms. You would also see that those students who met the
requirements for receiving money got this money.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Admissions, student affairs, and financial aid
directors and registrars sometimes start in related staff jobs with
bachelor's degrees and obtain advanced degrees in college student
affairs, counseling, or higher education administration.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>According to the job search website, indeed.com, the
median annual wage of financial aid officers was $45,950 in September 2020.
</blockquote>

<hr size="1" />

<span class="header1">LAW & CIVIL SERVICE</span>
<p>The occupations in this field deal with the laws of the nation or
state. Civil servants are people who provide services to the general
public. If you want to help those living in your community, consider
the occupations in this field.</p>

<hr size="1" />

	<span class="header2">Military Attach&eacute;</span><br />
	<span class="header3">Job Description</span>
	<blockquote>A military attach&eacute; works for the military. In
this job, you would collect information about the military forces of
other countries. To be able to do this, you would meet with
government officials and other people who have information.  You
would then decide what the other country's government might be
planning to do.  You would report what you had found out to the
people who needed to know. Commanders might use this information as
they plan possible military movements.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree for this
position.  You also need to understand one or more world languages.  Knowledge of other countries is a must. To be chosen as
an attach&eacute;, you would need to have many years' experience in the
military. The person who fills this position has to be very
educated.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the Military is
based on your rank, years of service, and occupational
specialty.</blockquote>

<hr size="1" />

	<span class="header2">Foreign Service
Officer</span><br />
	<img class="job_pic" src="/images/icons/CE/1113.jpg"
width="100" height="100" border="0" alt="Foreign Service Officer" />
	<span class="header3">Job Description</span>
	<blockquote>A foreign officer works for the government.  In
this job, you would work at an embassy or consulate. You would live
in the country where you were providing service.  Your job would be
to help American citizens who traveled to that country.  You would
also help American companies work with that country's government.
Your goal would be to help Americans and American businesses enjoy
or work in the country.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree to be a Foreign
Service officer.  You also need to have studied at least one world
language.  Also courses in English, history, economics, and public
speaking are important. The person who fills this position must be
very educated. Knowledge of other countries is a must.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median average wage of foreign service officers was $123,092 in September 2020, according to state.gov. </blockquote>

<hr size="1" />

	<span class="header2">Environmental Protection
Specialist</span><br />
	<img class="job_pic" src="/images/icons/CE/1285.jpg"
width="100" height="100" border="0" alt="Environmental Protection
Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>An environmental protection specialist works for
the government.  In this job, you would monitor companies and
manufacturers.  Your job would be to see that they obeyed the
regulations that keep the air and water clean.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree in a technical
field for this job. You also need to have skills in accounting and
statistics.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of environmental
protection specialists was $71,360 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 14, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 14, 2020). </blockquote>

</div>
