<span class="header1">Business/Management paired with Technology (CF)
</span>

<p>With a "CF" interest, you will be a valuable employee. You like
working with people on projects or assignments that have to do with
biotechnology, information systems, engineering and environmental in
the technology industries. The field of business is becoming more
technical and fast-paced. This means that you will have many
opportunities to find the occupation that suits you. You will be
happiest in an occupation that allows you to use your ability to
understand how things work and solve problems.</p>
<p>Many of the occupations in this pairing require some sort of
specialized and/or technical training after high school. Some
require college degrees or college level courses.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that allow you to continue to
learn about business. Technology courses will be important too.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising/Marketing<br />
			Computer Programming<br />
			Technology Education
		</td>
		<td>
			Trade & Industry<br />
			Business Education<br />
			Political Science
		</td>
		<td>
			Psychology<br />
			Sociology<br />
			Economics
		</td>
		<td>
			Business Law<br />
			Computer Sciences<br />
			Government/Civics
		</td>
		<td>
			Public Relations<br />
			History<br />
			Accounting
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations you
may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. Any club or activity that involves working with
technology and communicating will be valuable.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Junior Achievement<br />
			Newspaper/Yearbook<br />
			Library Assistant<br />
			Chess Club

		</td>
		<td>
			Audio/Visual Services<br />
			Class Officer<br />
			Radio/TV Club<br />
			Community Volunteer
		</td>
		<td>
			Math/Science Club<br />
			Destination Imagination<br />
			Future Business Leaders
		</td>
		<td>
			Odyssey of The Mind<br />
			Computer Activities<br />
			Future Problem Solvers
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Appliance Repair<br />
			Newspapers<br />
			Photography Studios<br />
			Small Engine Repair
		</td>
		<td>
			Equipment Operations<br />
			Graphic Design Firms<br />
			Printing Companies
		</td>
		<td>
			Delivery Service<br />
			Equipment Repair Shops<br />
			Photographic Laboratories
		</td>
		<td>
			TV/Radio Stations<br />
			Telephone Sales<br />
			Data Processing
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">CF Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Business & Community Service</span><br />
						<em>Athletic
Director<br />
						Safety
Engineer<br />
						Police
Chief<br />
						Sheriff<br />
						Deputy
Sheriff<br />
						Youth Services
Director<br />
						Fitness Club
Manager<br />
						Aircraft Sales
Representative<br />
						Professional
Athlete<br />
						Real Estate
Agent<br />
						Machinist<br />
						Corrections
Officer<br />
						Cleaning Service
Owner</em>
					</td>
					<td width="33%">
						<span
class="header2">Business & Environment</span><br />
						<em>Environmental
Risk Manager<br />
						Land Acquisition
Professional<br />
						Solid Waste
Management<br />
						Environmental
Protection Specialist<br />
						Environmental
Project Manager<br />
						Fire
Chief<br />
						Park
Ranger<br />
						Park & Recreation
Manager<br />
						Forestry
Technician<br />

	Firefighter<br />
						Rancher<br />
						Logging
Supervisor</em>
					</td>
					<td width="33%">
						<span
class="header2">Business & Technology</span><br />
						<em>Information
Manager<br />
						Computer
Specialist<br />
						Database
Manager<br />
						Air Traffic
Controller<br />
						Construction
Manager<br />
						Building
Contractor<br />
						Computer Sales
Representative<br />
						Software Sales
Representative<br />
						Computer
Engineer<br />
						Industrial
Production Manager<br />
						Computer Store
Manager<br />
						Public Service
Technician<br />
						Truck Driver</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">BUSINESS & COMMUNITY SERVICE</span>
<p>If you worked within this occupational field, a community or
business would hire you. These occupations are physically demanding.
To enjoy them you must like adventure.</p>

<hr size="1" />

	<span class="header2">Police Officer</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Uniformed police officers have general law
enforcement duties, including maintaining regular patrols and
responding to calls for service. They may direct traffic at the
scene of an accident, investigate a burglary, or give first aid to
an accident victim.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Law enforcement agencies encourage applicants to
take courses or training related to law enforcement subjects after
high school. Many entry-level applicants for police jobs have
completed some formal postsecondary education, and a significant
number are college graduates. Many junior colleges, colleges, and
universities offer programs in law enforcement or administration of
justice. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of police officers was
$65,170 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Detective</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Detectives are plain-clothes investigators who
gather facts and collect evidence for criminal cases. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Law enforcement agencies encourage applicants to
take courses or training related to law enforcement subjects after
high school. Many agencies pay all or part of the tuition for
officers to work toward degrees in criminal justice, police science,
administration of justice, or public administration and pay higher
salaries to those who earn such a degree. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of detectives was $65,170
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Corrections Officer</span><br />
	<img class="job_pic" src="/images/icons/CF/so000174.jpg"
width="100" height="100" border="0" alt="Corrections Officer" />
	<span class="header3">Job Description</span>
	<blockquote>A corrections officer works in a jail or prison.
As a corrections officer, you would make sure that prisoners were
safe. You would also see that they followed the rules of the prison
and did not escape. You would search cells for items that the
prisoners should not have and report any arguments or
fights.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The Federal Bureau of Prisons requires entry-
level correctional officers to have at least a bachelor's degree;
three years of full-time experience in a field providing counseling,
assistance, or supervision to individuals; or a combination of the
two. Some state and local corrections agencies require some college
credits, but law enforcement or military experience may be
substituted to fulfill this requirement.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of corrections officers
was $45,180 in May 2019.
</blockquote>

<hr size="1" />

<span class="header1">BUSINESS & ENVIRONMENT</span>
<p>The occupations in this field protect, manage, or research the
environment. If the environment is one of your interests, you might
want to consider the occupations in this field. Here are three
examples.</p>

<hr size="1" />

	<span class="header2">Waste Management
Technician</span><br />
	<img class="job_pic" src="/images/icons/AC/43020.jpg"
width="100" height="100" border="0" alt="Waste Management
Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Manufacturing processes can create dangerous
waste materials.  If you become a waste management technician, you
might help to remove chemical or nuclear wastes created by these
processes.  You would wear protective clothing. You would work with
equipment designed to remove toxic waste from the water and
soil.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma to become a waste
management technician. You would also participate in a training
program offered by your company.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of waste management
technicians was $43,900 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Park Ranger</span><br />
	<img class="job_pic" src="/images/icons/CF/C585042.jpg"
width="100" height="100" border="0" alt="Park Ranger" />
	<span class="header3">Job Description</span>
	<blockquote>A park ranger makes sure that visitors and
wildlife are safe in state and national parks. As a park ranger, you
would patrol the park.  You would also collect fees, provide
information about the park, and enforce park rules and
regulations.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Workers in this occupation need, at a minimum, a
bachelor's degree in forestry, environmntal science, range
management, or a related discipline.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of park rangers was
$62,660 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Forestry Technician</span><br />
	<img class="job_pic" src="/images/icons/CF/43168.jpg"
width="100" height="100" border="0" alt="Forestry Technician" />
	<span class="header3">Job Description</span>
	<blockquote>A forestry technician works to allow people to
visit and use our forests, and to protect the environment. If you
become a forestry technician, you might plan and oversee forest
operations. These include logging, tree planting, water regulation,
and wildlife management. You might also collect information for
research and oversee work crews. This is not an easy job. You must
be willing to work hard and be outside in all kinds of weather.
</blockquote>
	<span class="header3">Education</span>
	<blockquote>To become a forestry technician, you typically need some training in a vocational school or an associate's degree.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of forestry technicians
was $45,500 in May 2019.
</blockquote>

<hr size="1" />

<span class="header1">BUSINESS & TECHNOLOGY</span>
<p>Technology is becoming more and more important in running an
office.  The occupations in this field need people who know how
business machines and equipment work. If you enjoy working with
equipment or machines, this field may be for you.</p>

<hr size="1" />

	<span class="header2">Computer and Information Systems
Manager</span><br />
	<img class="job_pic" src="/images/icons/CF/43334.jpg"
width="100" height="100" border="0" alt="Computer and Information
Systems " />
	<span class="header3">Job Description</span>
	<blockquote>Computer and information systems managers plan,
coordinate, and direct research and facilitate the computer-related
activities of firms. They help determine both technical and business
goals in consultation with top management and make detailed plans
for the accomplishment of these goals. This requires a strong
understanding of both technology and business practices.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree usually is required for
management positions, although employers often prefer a graduate
degree, especially an MBA with technology as a core component.  Some
universities offer degrees in management information systems. These
degrees blend technical subjects with business, accounting, and
communications courses.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of computer and
information system managers was $146,360 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Computer Software 
Engineer</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Computer software (or hardware) engineers apply the principles
of computer science and mathematical analysis to the design,
development, testing, and evaluation of the software and systems
that make computers work.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most employers prefer applicants who have at
least a bachelor's degree and experience with a variety of computer
systems and technologies. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of computer software
engineers was $117,220 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Computer Service
Technician</span><br />
	<!-- <img class="job_pic" src="/images/icons/CF/1234.jpg"
width="100" height="100" border="0" alt="Computer Service
Technician" /> -->
	<span class="header3">Job Description</span>
	<blockquote>Computers are very important to our society and
will continue to be in the future. If you like knowing what makes
computers work and want to keep them running, you might become a
computer service technician. In this job, you figure out why a
computer isn't working and fix it.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers prefer workers who are certified or
who have training in electronics from an associate degree program,
the military, a vocational school, or an equipment manufacturer.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of computer service
technicians was $54,760 in May 2019.
</blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 14, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 14, 2020). </blockquote>

</div>
