<span class="header1">Business/Management paired with
Science/Mathematics (CH)</span>

<p>If your scores on this pairing were high, you naturally
understand that there are always ways to improve a situation. You
can probably handle several tasks at one time. People like you have
made important contributions in business. You are an excellent
thinker.  You are also likely to be a no-nonsense kind of person.
You are creative and like to ask the question, "Why?"
Because of this, you will look for new business ventures.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree or some post high school courses. For some jobs, it may be
valuable to have a master's degree or a Ph.D.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that emphasize math and
science. Any courses dealing with business will be of great interest
to you. They will also help to prepare you for possible careers in
this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Biology<br />
			Calculus<br />
			Physics<br />
			Sociology
		</td>
		<td>
			Computer Sciences<br />
			Advertising/Marketing<br />
			Accounting<br />
			Business Education
		</td>
		<td>
			Business Law<br />
			Chemistry<br />
			Psychology<br />
			Trigonometry
		</td>
		<td>
			Business Math<br />
			Communications<br />
			Economics<br />
			Political Science
		</td>
		<td>
			World Languages<br />
			Technology Education<br />
			Government/Civics<br />
			Environmental Sciences
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for after-school activities or part-time jobs, make
them count. Any club or activity that involves using your people and
thinking skills is what you will enjoy the most.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Future Business Leaders<br />
			Hospital Volunteer<br />
			Yearbook<br />
			Computer Club
		</td>
		<td>
			Computer Activities<br />
			Environmental Activities<br />
			Junior Achievement<br />
			Class Officer
		</td>
		<td>
			Chess Clubs<br />
			Math/Science Club<br />
			Tutoring
		</td>
		<td>
			Exchange Programs<br />
			Marketing<br />
			Community Volunteer
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting Firms<br />
			Electronics Stores<br />
			Photographic Laboratories<br />
			Restaurants
		</td>
		<td>
			Computer Services<br />
			Engineering Firms<br />
			Medical Offices<br />
			Printing Companies
		</td>
		<td>
			Data Entry<br />
			Landscaping Companies<br />
			Newspaper Offices<br />
		</td>
		<td>
			Architect Firms<br />
			Theaters<br />
			TV/Radio Stations
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">CH Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="25%">
						<span
class="header2">Finance</span><br />
						<em>Chief Financial
Officer<br />
						Financial
Advisor<br />

	Accountant<br />
						Auditor
							<ul>

	<li>Bank</li>

	<li>Federal Reserve</li>
							</ul>

	Stockbroker<br />

	Statistician<br />
						Loan
Officer<br />
						Accounting
Clerk<br />
						Cashier</em>
					</td>
					<td width="25%">
						<span
class="header2">Medical</span><br />
						<em>Public Health
Administrator<br />
						Physician<br />
						Hospital
Administrator<br />

	Epidemiologist<br />
						Medical
Officer<br />
						Nursing Home
Director<br />

	Pharmacist<br />
						Optician<br />
						Patient
Representative</em>
					</td>
					<td width="25%">
						<span
class="header2">Analysis/Research</span><br />

	<em>Economist<br />
						Marketing
Director<br />

	Entrepreneur<br />
						Financial
Analyst<br />
						Market
Researcher<br />
						Insurance Planner &
Analyst<br />
						Medical
Economist<br />
						Computer Systems
Analyst</em>
					</td>
					<td width="25%">
						<span
class="header2">Nature</span><br />
						<em>Zoo
Administrator<br />
						Science Museum
Director<br />
						Historic
Preservationist<br />
						Fishery
Manager/Technician<br />
						Wildlife
Manager/Technician<br />
						Refuge
Manager<br />
						Lobbyist<br />
						Grass Roots
Coordinator<br />
						Fund
Raiser<br />
						Real Estate
Developer<br />
						Nursery Manager</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">FINANCE</span>
<p>The occupations in this field are for people who are able to
investigate and are good with numbers. If you would like to work with
finances, these occupations might be for you.</p>

<hr size="1" />

	<span class="header2">Accountant</span><br />
	<img class="job_pic" src="/images/icons/CH/1287.jpg"
width="100" height="100" border="0" alt="Accountant" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy working with numbers, you might
become an accountant. An accountant is responsible for helping a
company make money. You might advise the company to buy or sell
stock, or you might prepare its taxes.  You would also keep careful
records so that it was possible to tell how much money the company
made and where this money was spent.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree for an entry level
job. Most accountants are CPA's (Certified Public Accountants). To
become a CPA you must have a bachelor's degree. You must also pass
a written exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of accountants was
$71,550 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Statistician</span><br />
	<img class="job_pic" src="/images/icons/CH/C1618_03.jpg"
width="100" height="100" border="0" alt="Statistician" />
	<span class="header3">Job Description</span>
	<blockquote>As a statistician, you would gather and analyze information
in numbers. For example, Major League Baseball players have their
batting averages determined by statisticians. If you worked in a
business, you would look at certain numbers to see how well the
company was doing.  Is it in good shape? Numbers give the
statistician the answer.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree in
statistics or mathematics for this job.  To get a promotion, you
must have a master's degree or a Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of statisticians was
$91,160 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Loan Officer</span><br />
	<img class="job_pic" src="/images/icons/CH/C506008.jpg"
width="100" height="100" border="0" alt="Loan Officer" />
	<span class="header3">Job Description</span>
	<blockquote>A loan officer works for a bank or lending
company. As a loan officer, you would help customers fill out loan
applications and make sure that the information on the application
is correct. You would then see if the people wanting the loan met
your company's guidelines for a loan. If so, you would help to
process the loan.  If not, you would help them to understand why
they did not get the loan.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Loan officers usually need a bachelor's degree
in finance, economics, or a related field. Previous banking,
lending, or sales experience is also highly valued by employers.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of loan officers was
$63,270 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">MEDICAL</span>
<p>Health care is one area where business and science blend well.
The occupations in this field need people who are interested in the
physical well-being of others.</p>

<hr size="1" />

<span class="header2">Medical and Health Services
Manager</span><br />
	<span class="header3">Job Description</span>
	<blockquote>As a medical and health services manager, you
would be
responsible for the day-to-day running of a health care facility
such as a hospital, clinic or nursing home. You would be in charge of
hiring employees and budgeting money. You might also help to raise
money to keep the facility going. To do well in this job, you need
business skills.  You also need leadership and people
skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree for this job. This
degree might be in hospital or health administration or in public health. Many people in this field also have master's degrees. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of medical and health
service managers was $100,980 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Nursing Home
Director</span><br />
	<span class="header3">Job Description</span>
	<blockquote>As a nursing home director, you would make sure
that the building and equipment are kept in good condition.  You
would also make sure that the elderly people who live in the home
are well cared for. An important part of your duties would be to
oversee the employees who care for the elderly. Another important
duty is to run the home so that it earns a profit.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Many people who work as health care
administrators, such as nursing home directors, must have a master's degree. Some health care
administrators have degrees in public health.  Others have a degree
in public administration.  Still others have a degree in business
administration.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of nursing home directors
was $100,980 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Polysomnographic
Technologist or Medical Technologist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Polysomnographic technologists monitor
the activity of adults and children in sleep laboratories.
They observe patients, collect data, and take notes during
a sleep study. Then, they summarize the information for
a sleep physician, who makes a diagnosis and recommends
treatment. Technologists often assist patients in understanding and
adjusting to the recommended treatment.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To be a certified polysomnographic technologist
you will need to complete an associate degree program with an
emphasis in polysomnography. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of polysomnographic
technologists or medical technologists was $53,120 in May 2019.
</blockquote>

<hr size="1" />


<span class="header1">ANALYSIS/RESEARCH</span>
<p>In this field, employees need to understand how to make money and
how to do business. If you chose to work in this field, you would
study how business is practiced and what companies must do to make
money.</p>

<hr size="1" />

	<span class="header2">Economist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy finding clues and drawing
conclusions, you might become an economist. An economist looks at
trends in business and predicts what will happen. For example, you
might study the oil business and decide whether the price of
gasoline will be going up or down. You would probably like this job
if you are naturally curious and enjoy a challenge.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a master's degree for this
job. Many employers will want you to have a Ph.D. Education is very
important.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of economists was $105,020
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Market Researcher</span><br />
	<img class="job_pic" src="/images/icons/CH/43326.jpg"
width="100" height="100" border="0" alt="Market Researcher" />
	<span class="header3">Job Description</span>
	<blockquote>A market researcher (or market research analyst) works for a company that makes a product sold to the public. As a researcher, you might work
for a toy manufacturer or a retail store. You would collect
information about what customers want to buy and give your results
to the company.  If you are curious and understand business, this
might be a good job for you.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree for this job.
Market researchers start out in entry-level jobs, then they are
promoted to this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of market researchers was
$63,790 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Computer Systems
Analyst</span><br />
	<img class="job_pic" src="/images/icons/CH/43166.jpg"
width="100" height="100" border="0" alt="Computer Systems Analyst" />
	<span class="header3">Job Description</span>
	<blockquote>Computer systems analysts solve computer
problems and use computer technology to meet the needs of an
organization. They may design and develop new computer systems by
choosing and configuring hardware and software. They may also devise
ways to apply existing systems' resources to additional
tasks.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers generally prefer applicants who have
at least a bachelor's degree in computer science, information
science, or management information systems. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of computer systems
analyists was $90,920 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">NATURE</span>
<p>If you enjoy nature or are concerned about the environment, this
occupational field may be for you.  People who work in this field
enjoy life sciences and understand business.</p>

<hr size="1" />

	<span class="header2">Life Science Museum
Director</span><br />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy helping others know about the
environment and nature, you might become a life science museum
director.  In this job, you would plan and oversee the daily routine
of a museum. You would manage employees and keep the building in
good repair. Most directors start out as a museum curator.  Later,
they are promoted the director's job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employment as an archivist, conservator, or
museum director usually requires graduate education and related work
experience. Museum technicians often start work with a bachelor's
degree. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of life science museum
directors was $49,850 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Zoologist</span><br />
	<img class="job_pic" src="/images/icons/CH/1270.jpg"
width="100" height="100" border="0" alt="Zoologist" />
	<span class="header3">Job Description</span>
	<blockquote>Zoologists study the characteristics of animals,
such as their interactions with other species, reproduction,
diseases, and movement patterns.  For example, they might take blood
samples from animals to assess their levels of nutrition.  Most
zoologists work on research teams with other scientists and
technicians.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Zoologists need a bachelor's degree for entry-
level jobs, but a master's degree is often needed for advancement.
A Ph.D is necessary for independant research jobs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of zoologists was
$63,270 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Farmer, Rancher, Agricultural
Manager</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Crop farmers and managers determine the best
time to plant seed, apply fertilizer and chemicals, and harvest and
market the crops. Many carefully plan the combination of crops they
grow so that if the price of one crop drops, they will have
sufficient income from another crop to make up the loss. Livestock,
dairy, and poultry farmers and ranchers feed and care for animals
and keep barns, pens, coops, and other farm buildings clean and in
good condition. Although employment on most farms is limited to the
farmer and one or two family workers or hired employees, some large
farms have 100 or more full-time and seasonal workers. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Most farmers receive their training on the job,
often by being raised on a farm. However, the completion of a 2-year
associate degree or a 4-year bachelor's degree at a college of
agriculture is becoming increasingly important for farm managers and
for farmers and ranchers who expect to make a living at farming.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of farmers/ranchers was
$71,160 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 15, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 15, 2020). </blockquote>

</div>
