<span class="header1">Clerical/Administrative paired with
Protective/Military Service (DE)</span>

<p>If you show high scores in categories "D" and "E," you are a
person who knows how to make things happen. You are respectful to
others. You also probably enjoy working on a team. You are able to
complete tasks quickly. An exciting environment is important to you.
You especially like to try new things.</p>
<p>Some of the occupations in this pairing require a bachelor's
degree and many others require specialized training.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to Math & English):</strong><br />
In high school you should take courses that allow you to continue
to learn about business. You will want to take courses that help you
understand people as well.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting<br />
			Business Law<br />
			Computer Sciences<br />
			Public Relations
		</td>
		<td>
			History<br />
			Physics<br />
			Geography<br />
			Economics
		</td>
		<td>
			Business Math<br />
			Sociology<br />
			Government/Civics<br />
			Life Sciences
		</td>
		<td>
			Political Science<br />
			Business Education<br />
			Technology Education<br />
			Environmental Sciences
		</td>
		<td>
			Bookkeeping<br />
			World Languages<br />
			Physical Education<br />
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations you
may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. You will enjoy any club or activity that involves taking
on challenges.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Athletics<br />
			Camp Activities<br />
			Martial Arts
		</td>
		<td>
			Audio/Visual Services<br />
			Newspaper/Yearbook<br />
			Future Business Leaders<br />
		</td>
		<td>
			Band<br />
			Scouts<br />
			ROTC
		</td>
		<td>
			Teaching Assistant<br />
			Community Volunteer<br />
			Flight Training
		</td>
		<td>
			Library Assistant<br />
			Class Officer
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Construction Sites<br />
			Radio/TV Stations<br />
			Printing Companies
		</td>
		<td>
			Temporary Agencies<br />
			Equipment Operation<br />
			Equipment Repair Shops
		</td>
		<td>
			Libraries<br />
			Gyms<br />
			Life Guarding
		</td>
		<td>
			Camp Counseling<br />
			Photography Studios<br />
			Parks/Recreation
		</td>
		<td>
			Newspapers<br />
			Data Processing
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">DE Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main"v>
					<td width="33%">
						<span
class="header2">Staff Support Services</span><br />
						<em>Assistant Sports
Coach<br />
						Paralegal<br />
						Airline Ticket
Agent<br />
						Executive
Assistant<br />
						Drafting
Technician<br />
						Court
Reporter<br />
						Data
Reporter<br />

	Receptionist<br />
						City Maintenance
Worker<br />
						Clerk
							<ul>

	<li>Accounting</li>

	<li>Mail</li>

	<li>Shipping & Receiving</li>
							</ul></em>
					</td>
					<td width="33%">
						<span
class="header2">Office Administration</span><br />
						<em>Operations
Manager<br />
						Computer Systems
Analyst<br />
						Human Resources
Representative<br />
						Office
Manager<br />
						Purchasing
Agent<br />
						Clerical
Supervisor<br />
						Software
Technician<br />
						Office Machine
Repair Technician<br />
						Accounting Clerk
							<ul>

	<li>Payroll</li>

	<li>Accounts Payable</li>

	<li>Accounts Receivable</li>
							</ul></em>
					</td>
					<td width="33%">
						<span
class="header2">Military</span><br />
						<em>Religious
Program Specialist<br />
						Recruiting
Specialist<br />
						Administrative
Support Services<br />
						Lodging
Specialist<br />
						Legal
Technician<br />
						Transportation
Specialist<br />
						Computer
Operator<br />
						Optometric
Technician<br />

	Stenographer<br />
						Stock & Inventory
Specialist</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">STAFF SUPPORT SERVICES</span>
<p>The occupations in this field give support to other staff members
and provide services to the public. If you chose an occupation in
this field, you would play an important role in an organization or
business because you would make sure that things were done
correctly.</p>

<hr size="1" />

	<span class="header2">Executive Assistant</span><br />
	<img class="job_pic" src="/images/icons/DE/1206.jpg"
width="100" height="100" border="0" alt="Executive Secretary" />
	<span class="header3">Job Description</span>
	<blockquote>Executive assistants perform a variety of
administrative and clerical duties necessary to run an organization
efficiently. They serve as information and communication managers
for an office; plan and schedule meetings and appointments; organize
and maintain paper and electronic files; manage projects; conduct
research; and disseminate information by using the telephone, mail
services, websites, and e-mail. They also may handle travel and
guest arrangements.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers of executive assistants increasingly
are seeking candidates with a college degree, as these assistants
work closely with top executives. A degree related to the business
or industry in which a person is seeking employment may provide the
job seeker with an advantage in the application process.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of executive assistants 
was $39,850 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Drafter</span><br />
	<img class="job_pic" src="/images/icons/DE/43138.jpg"
width="100" height="100" border="0" alt="Drafting Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Drafters prepare technical drawings and plans
which are used to build everything from manufactured products such
as toys, toasters, industrial machinery, and spacecraft to
structures such as houses, office buildings, and oil and gas
pipelines. Drafters use Computer Aided Design to prepare drawings.
</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers prefer applicants who have completed
postsecondary school training in drafting, which is offered by
technical institutes, community colleges, and some 4-year colleges
and universities. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of drafters was $56,830 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Accounting Clerk</span><br />
	<img class="job_pic" src="/images/icons/DE/1203.jpg"
width="100" height="100" border="0" alt="Accounting Clerk" />
	<span class="header3">Job Description</span>
	<blockquote>As an accounting clerk, you would help a company
keep track of its money. You would use the computer to develop
spreadsheets that track how and where company money was being
spent.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers usually prefer bookkeeping,
accounting, and auditing clerks to have at least a high school
diploma and some accounting coursework or relevant work experience.
Clerks should also have good communication skills, be 
detail-oriented, and trustworthy.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of accounting clerks was
$41,230 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">OFFICE ADMINISTRATION</span>
<p>All of the occupations in this field need people who will follow
very strict rules. If you chose an occupation in this field, you
would make sure that procedures were followed and that all tasks
were completed.</p>

<hr size="1" />

	<span class="header2">Cardiovascular
Technician</span><br />
	<img class="job_pic" src="/images/icons/DE/1387.jpg"
width="100" height="100" border="0" alt="Purchasing Agent" />
	<span class="header3">Job Description</span>
	<blockquote>Cardiovascular technologists and technicians
assist physicians in diagnosing and treating cardiac (heart) and
peripheral vascular (blood vessel) ailments. They schedule
appointments, perform ultrasound or cardiovascular procedures,
review doctors' interpretations and patient files, and monitor
patients' heart rates. They also operate and care for testing
equipment and explain test procedures. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Although a few cardiovascular technologists,
vascular technologists, and cardiac sonographers are currently
trained on the job, most receive training in 2- to 4-year programs.
The majority of technologists complete a 2-year junior or community
college program, but 4-year programs are increasingly available.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of cardiovascular
technicians was $59,600 in May 2019.
</blockquote>

<hr size="1" />

	<span class="header2">Supervisor of Office Support Workers</span><br />
	<img class="job_pic" src="/images/icons/DE/43302.jpg"
width="100" height="100" border="0" alt="Clerical Supervisor" />
	<span class="header3">Job Description</span>
	<blockquote>A office supervisor plans and schedules what
those in an office do. You would assign work, maintain personnel
files, and train new staff members. If the office equipment were to
break down, it would be your responsibility to make sure it was
repaired. You must be able to communicate well and handle many
things going on at the same time.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most firms fill office and administrative
support supervisory and managerial positions by promoting office or
administrative support workers from within their organizations. To
become eligible for promotion to a supervisory position,
administrative support workers must prove they are capable of
handling additional responsibilities. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of supervisors of office support workers 
was $56,620 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Office Machine Repair
Technician</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Office machines must be kept in good running
order.  As an office machine repair technician, you would be
responsible for installing office equipment. You would also repair
and maintain this equipment.  You would work on copiers, computers,
and other machines.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need some training in electronics for this
job. It is helpful to attend a one-to-two year program in this
field.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of office machine repair
technicians was $42,070 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">MILITARY</span>
<p>The military has many jobs for people who are good at handling
details and who are efficient.</p>

<hr size="1" />

	<span class="header2">Optometric
Technician</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Optometry is the science of vision and eye care.
Service members must have good vision. As an optometric technician (or optician)
in the military, you would help an optometrist with
his/her patients. You would perform vision screening tests and order
glasses and contact lenses. You would have to be very precise in
giving prescriptions for glasses and contacts.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You do not need any special education to become
an optometric technician. Training usually occurs on-the-job. It would be helpful 
to take courses such as geometry and algebra in high school.  Biology courses will also
be helpful.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of civilian optometric technicians
was $37,840 in May 2019. Military pay depends on rank and years of service. </blockquote>

<hr size="1" />

	<span class="header2">Transportation
Specialist</span><br />
	<img class="job_pic" src="/images/icons/DE/400067.jpg"
width="100" height="100" border="0" alt="Transportation
Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>A transportation specialist in the military has
many duties.  As a transportation specialist, you might make travel
reservations.  You might also check cargo or check in passengers.
You might also act as a flight attendant. Most of your passengers
would be military personnel and their families.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are no formal requirements for this
position.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of civilian transportation
specialists was $56,640 in May 2019. Military pay depends on rank and 
years of service. </blockquote>

<hr size="1" />

	<span class="header2">Lodging Specialist</span><br />
	<img class="job_pic" src="/images/icons/DE/43099.jpg"
width="100" height="100" border="0" alt="Lodging Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>A lodging specialist is much like a hotel
manager and clerk.  In this job, you would check in military
personnel and their families at a hotel-like facility. You would
answer telephone calls. You would keep records of expenses as
well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are no formal requirements for this
position.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of civilian lodging specialists
was $54,430 in May 2019. Military pay depends on rank and years of service. </blockquote>

<hr size="1" />


<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 15, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 15, 2020). </blockquote>

</div>
