<span class="header1">Clerical/Administrative paired with Technology
(DF)</span>

<p>With a "DF" interest, you will be a valuable employee. Those who
have strong scores in "D" and "F" have very high goals and want
things to be done right. You like to use tools and information to
reach your goals. You are an active person and will want a job that
keeps you on the go.</p>
<p>Many of the occupations in this pairing require some specialized
or technical training after high school. Some require college level
courses and others require college degrees.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school, you should take courses that allow you to continue
to learn how to be efficient. Technology courses will be important,
too.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting<br />
			Business Law<br />
			Graphic Art<br />
		</td>
		<td>
			Office Administration<br />
			Computer Programming<br />
			Environmental Science<br />
		</td>
		<td>
			Bookkeeping<br />
			Business Math<br />
			Psychology<br />
		</td>
		<td>
			Physical Education<br />
			Government/Civics<br />
			Business Education<br />
		</td>
		<td>
			Technology Education<br />
			Geography<br />
			Communications
		</td>
	</tr>
</table>

<p><strong>Extracurricular / Volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. Any club or activity that involves technology and
procedures will be valuable.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Math/Science Clubs<br />
			Chess Club<br />
			Office Assistant
		</td>
		<td>
			Park & Recreation Activities<br />
			Audio/Visual Services<br />
			Future Business Leaders
		</td>
		<td>
			Library Assistant<br />
			Photography Clubs<br />
			Community Volunteer
		</td>
		<td>
			Computer Club<br />
			Newspaper/Yearbook<br />
			Teaching Assistant
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Farming<br />
			Delivery Services<br />
			Lumberyard<br />
			Construction
		</td>
		<td>
			Environmental Services<br />
			Landscaping/Lawn Care<br />
			Photography Studios<br />
			Park Services
		</td>
		<td>
			Newspaper Offices<br />
			Camp Counseling<br />
			Data Processing
		</td>
		<td>
			Equipment Operations<br />
			Graphic Design Firms<br />
			Equipment Repair Shops
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">DF Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Technical Administration</span><br />

	<em>Publisher<br />
						Graphic
Artist<br />
						Technical
Proofreader<br />
						Graphics
Specialist<br />
						Medical Record
Administrator<br />
						Computer
Programmer<br />
						Airline Ticket
Agent<br />
						Dispensing
Optician<br />

	Stenographer<br />
						Work
Processor<br />
						Switchboard
Operator</em>
					</td>
					<td width="33%">
						<span
class="header2">Clerical Services</span><br />
						<em>Court
Reporter<br />
						Recreation
Administrator<br />
						Library Technical
Assistant<br />
						Insurance Claims
Examiner<br />
						Directory Assistance
Operator<br />
						Mail
Carrier<br />
						Construction
Secretary<br />
						Clerk
							<ul>

	<li>General Office</li>

	<li>Personnel</li>

	<li>Mail</li>

	<li>Shipping</li>
							</ul></em>
					</td>
					<td width="33%">
						<span
class="header2">Technical Operation</span><br />

	<em>Surveyor<br />
						Parks &
Recreation<br />
						Public Relations
Assistant<br />
						Database
Administrator<br />
						Computer
Programmer<br />
						Flight Operations
Specialist<br />
						Computer Service
Technician<br />
						Shoe
Repairer<br />
						Corrections
Officer<br />
						Security
Guard<br />
						Parts Clerk
							<ul>

	<li>Auto

	<li>Hardware</li>
							</ul></em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header2">TECHNICAL ADMINISTRATION</span>
<p>If you have the ability to keep details straight and like to work
with technology, this field may be for you. The occupations in this
field must have detail oriented people who have technical skills.</p>

<hr size="1" />

	<span class="header2">Graphic Designer</span><br />
	<img class="job_pic" src="/images/icons/DF/43285.jpg"
width="100" height="100" border="0" alt="Graphic Artist" />
	<span class="header3">Job Description</span>
	<blockquote>Graphic designers (or graphic artists) plan,
analyze, and create visual solutions to communication problems.
They find the most effective way to get messages across in print,
electronic, and film media using a variety of methods such as color,
type, illustration, photography, animation, and various print and
layout techniques. An increasing number of graphic designers also
develop material for Internet Web pages, interactive media, and
multimedia projects. </blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's or an associate degree in graphic
design is usually required for a job as a graphic designer.  Graphic
designers must keep up with new and updated software on their own
or through software training programs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of graphic designers was
$52,110 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Optician</span><br />
	<span class="header3">Job Description</span>
	<blockquote>In this job you would work with the two types
of eye doctors, ophthalmologists and optometrists. Your duties would
be to fill the prescriptions for eyeglasses and contact lenses. You
would help patients pick out frames as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A high school diploma is all that is required to
get into this occupation, but most workers have completed at least
some college courses or a degree. About half the states require
individuals to pass one or more of the following for licensure: a
state practical examination, a state written examination, and
certification examinations offered by the American Board of
Opticianry (ABO) and the National Contact Lens Examiners (NCLE).
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of opticians
was $37,840 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Computer Scientist</span><br />
	<img class="job_pic" src="/images/icons/DF/43219.jpg"
width="100" height="100" border="0" alt="Computer Scientist" />
	<span class="header3">Job Description</span>
	<blockquote>Computer scientists work as theorists,
researchers, or inventors. The areas of computer science research
range from complex theory to hardware design to programming-language
design. Some researchers work on multidisciplinary projects, such as
developing and advancing uses of virtual reality, extending human-
computer interaction, or designing robots. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Most computer scientist positions require a
master's degree or Ph.D. Computer scientists having only a bachelor's 
degree are generally limited in their ability to advance. Technological 
advances come so rapidly in the computer field that continuous  
study is necessary to keep one's skills up to date.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of computer scientists
was $122,840 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">CLERICAL SERVICES</span>
<p>The occupations in this field need people who can recall and
record details. If you have a mind that easily remembers details,
they may interest you.</p>

<hr size="1" />

	<span class="header2">Court Reporter</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Courts are required to have somebody "record"
what is said in the courtroom during a trial or hearing. The person
who does this is a court reporter. As a court reporter, you would
use a special type of machine called a stenotype, which is a type of
computer that allows you to key in every word that the judge,
lawyers, and witnesses say. Some reporters work within the
courtroom. Other reporters are self-employed and they work in
different locations.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The amount of training required to become a
court reporter varies with the type of reporting chosen. Typically, 
you need an associate's degree to be a court reporter. Many states 
require licensure or certification. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of court reporters was
$60,130 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Insurance Claims
Adjuster</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Sometimes accidents occur and property is
damaged or destroyed. If the property has been insured, it is
replaced, repaired, or reimbursed by an insurance company. The
person who decides whether a "claim" is covered under an insurance
policy is an insurance claims adjuster. In this job, you would do a
lot of paperwork.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Training and entry requirements vary widely for
claims adjusters, appraisers, examiners, and investigators. Although
many in these occupations do not have a college degree, most
companies prefer to hire college graduates. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of insurance claims
adjusters was $66,540 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">TECHNICAL OPERATIONS</span>
<p>Many of the occupations in this field require computer skills. If
you enjoy working with computers, these occupations may be for
you.</p>

<hr size="1" />


	<span class="header2">Automotive Service
Technician</span><br />
	<img class="job_pic" src="/images/icons/DF/C1737_20.jpg"
width="100" height="100" border="0" alt="Shipping Clerk" />
	<span class="header3">Job Description</span>
	<blockquote>Automotive service technicians inspect,
maintain, and repair automobiles and light trucks that run on
gasoline, electricity, or alternative fuels such as ethanol.
Automotive service technicians' and mechanics' responsibilities have
evolved from simple mechanical repairs to high-level technology-
related work. They use computerized shop equipment and work with
electronic components while maintaining their skills with
traditional hand tools too. </blockquote>
	<span class="header3">Education</span>
	<blockquote>People seeking work in automotive service should
complete a formal training program in high school or in a
postsecondary vocational school or community college. However, some
service technicians still learn the trade solely by assisting and
learning from experienced workers. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of automotive service
technicians was $42,090 in May 2019. </blockquote>

<hr size="1" />


	<span class="header2">Computer Programmer</span><br />
	<img class="job_pic" src="/images/icons/DF/43290.jpg"
width="100" height="100" border="0" alt="Computer Programme" />
	<span class="header3">Job Description</span>
	<blockquote>Computer programmers write, test, and maintain
the detailed instructions, called programs, that computers follow to
perform their functions. Programmers also conceive, design, and test
logical structures for solving problems by computer.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is commonly required for
computer programming jobs, although a two-year degree or certificate
may be adequate for some positions. Employers favor applicants who
already have relevant programming skills and experience. Skilled
workers who keep up to date with the latest technology usually have
good opportunities for advancement. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of computer programmers
was $86,550 in May 2019. </blockquote>

<hr size="1" />


	<span class="header2">Telecommunications Engineering 
Specialist </span><br />
	<span class="header3">Job Description</span>
	<blockquote>Telecommunications engineering specialists focus on the
interaction between computer and communications equipment. These
workers design voice and data communication systems, supervise the
installation of the systems, and provide maintenance and other
services to clients after the systems are installed. </blockquote>
	<span class="header3">Education</span>
	<blockquote>While there is no universally accepted way to
prepare for a job as a telecommunications engineering specialist, most employers 
place a premium on some formal college education. A bachelor's degree 
is a prerequisite for some jobs; however, some may require only 
a two-year degree. Relevant work experience also is very important.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of telecommunications
engineering specialists was $112,690 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Precision Equipment
Repairer</span><br />
	<img class="job_pic" src="/images/icons/DF/1234.jpg"
width="100" height="100" border="0" alt="Computer Service
Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Repairing and maintaining watches, cameras,
musical instruments, medical equipment, and other precision
instruments require a high level of skill and attention to
detail.</blockquote>
	<span class="header3">Education</span>
	<blockquote>For most precision equipment repairers, the most
significant source of postsecondary education is on-the-job
training. Even in positions where an associate or bachelor's degree
is required, an internship or apprenticeship is generally required
before a technician is fully qualified.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of precision equipment
repairers was $58,060 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 18, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 18, 2020). </blockquote>

</div>
