<span class="header1">Clerical/Administrative paired with Public
Service (DG)</span>

<p>If you scored high in the "D" and "G" categories, you are
reliable and honest.  You are also supportive and resourceful. You
are the kind of person that employers prefer.  If you want to, you
can use your organizational skills and interest in helping others to
make a difference in the world.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree. For some jobs, it may be valuable to have a master's degree
or a Ph.D.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that help you to understand
business practices.  You should also take courses that help you to
understand people. Social studies courses such as political science
and sociology may interest you.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Business Math<br />
			Health/Nutrition<br />
			Physical Education<br />
			Political Science
		</td>
		<td>
			Computer Technology<br />
			Public Relations<br />
			Advertising/Marketing<br />
			Business Education
		</td>
		<td>
			Computer Sciences<br />
			Government/Civics<br />
			Bookkeeping<br />
			World Languages
		</td>
		<td>
			History<br />
			Sociology<br />
			Accounting<br />
			Economics
		</td>
		<td>
			Business Law<br />
			Photography<br />
			Psychology
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. Any club or activity that involves helping others or
working for a cause can provide valuable experience.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Community Volunteer<br />
			Audio/Visual Services<br />
			Library Assistant<br />
			Class Officer
		</td>
		<td>
			Teaching Assistant<br />
			Exchange Programs<br />
			Junior Achievement<br />
			Newspaper/Yearbook
		</td>
		<td>
			Future Business Leaders<br />
			Safety Patrol<br />
			Youth Organizations<br />
			Office Assistant
		</td>
		<td>
			Church Activities<br />
			Hospital Volunteer<br />
			Peer Counselor<br />
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Recreation Departments<br />
			Special Olympics<br />
			Accounting Firms<br />
			Temporary Agencies
		</td>
		<td>
			Business Offices<br />
			Legal Offices<br />
			Restaurants<br />
			Television Sales
		</td>
		<td>
			Accounting Firms<br />
			Libraries<br />
			Business Offices<br />
			Legal Offices
		</td>
		<td>
			Camp Counseling<br />
			Courthouses<br />
			Newspaper Offices<br />
			Radio/TV Studios
		</td>
		<td>
			Church Activities<br />
			Life Guarding<br />
			Political Offices<br />
			Youth Coaching
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">DG Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Community Services</span><br />
						<em>Social Worker
							<ul>

	<li>Occupational</li>

	<li>School</li>

	<li>Human Services</li>
							</ul>
						Vocational
Rehabilitation Counselor<br />
						Postal
Inspector<br />
						Teacher
Aide<br />
						Real Estate
Broker<br />
						Flight
Attendant<br />
						Church
Attendant<br />
						Postal
Worker<br />
						Hospital
Outpatient
Coordinator</em>
					</td>
					<td width="33%">
						<span
class="header2">Administrative Services</span><br />
						<em>Government
Office Administrator<br />
						Literary
Agent<br />
						Human Resources
Job
Analyst<br />
						Insurance Claims
Examiner<br />
						Medical Record
Administrator<br />
						Executive
Assistant<br />
						Transportation
Ticket Agent<br />
						Fire Department
Secretary<br />

	Receptionist<br />
						Clerk
							<ul>

	<li>File</li>

	<li>Mail</li>

	<li>Insurance Processing</li>

	</ul></em>
					</td>
					<td width="33%">
						<span
class="header2">Legal/Military Services</span><br />
						<em>Law
Librarian<br />

	Paralegal<br />
						Court
Reporter<br />
						Legal
Secretary<br />
						Flight
Operations
Specialist<br />
						Legal
Technician<br />
						Personnel
Specialist<br />
						Deputy
Sheriff<br />
						Real Estate
Closing
Secretary<br />
						Law Enforcement
Dispatcher<br />
						911
Operator<br />
						Administrative
Support Specialist</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">COMMUNITY SERVICES</span>
<p>The occupations in this field provide help for members in the
community. If you want to help make your community a better place to
live, think about the occupations in this field.</p>

<hr size="1" />

	<span class="header2">Social Worker</span><br />
	<img class="job_pic" src="/images/icons/DG/1212.jpg"
width="100" height="100" border="0" alt="Social Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Social work is all about helping. If you were to
become a social worker, you would help people find solutions to
problems. You might help them deal with being unemployed, being
physically or mentally disabled, or being addicted to drugs. There
is a lot of paperwork involved in being a social worker. There are
many different types of social workers as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is needed for an entry level
job.  Those with more responsible positions must have a master's
degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of social workers was
$50,470 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Teacher Assistant or
Paraprofessional</span><br />
	<img class="job_pic" src="/images/icons/DG/43319.jpg"
width="100" height="100" border="0" alt="Teacher's Aide or
Paraprofessional" />
	<span class="header3">Job Description</span>
	<blockquote>Not everyone who works at a school is a
teacher.  The job of a teacher's assistant is similar to that of a
teacher.  As a teacher's assistant, you would help a teacher care for
his/her students, grade papers, perform clerical duties, and prepare
instructional materials.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A number of colleges offer associate degrees or
certificate programs that either prepare graduates to work as
teacher assistants or provide additional training for current
teacher assistants.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of teacher assistants was
$27,920 in May 2019. </blockquote>

<hr size="1" />

	<span
class="header2">Interpreter/Translator</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Interpreters and translators enable the cross-
cultural communication necessary in today's society by converting
one language into another. However, these language specialists do
more than simply translate words - they relay concepts and ideas
between languages. They must thoroughly understand the subject
matter in which they work. In addition, they must be sensitive to
the cultures associated with their languages of
expertise.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The educational backgrounds of interpreters and
translators vary. Knowing at least two languages is essential.
Although it is not necessary to have been raised bilingual to
succeed, many interpreters and translators grew up speaking two
languages. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of
interpreters/translators was $51,830 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">ADMINISTRATIVE SERVICES</span>
<p>The occupations in this field allow you to help employees or
customers of a company.  You must be able to work well with others
to do these jobs.</p>

<hr size="1" />

	<span class="header2">Compensation and Benefits
Manager</span><br />
	<img class="job_pic" src="/images/icons/DG/1364.jpg"
width="100" height="100" border="0" alt="Job Analyst" />
	<span class="header3">Job Description</span>
	<blockquote>Compensation managers plan, direct, and
coordinate how and how much an organization pays its employees.
Benefits managers do the same for retirement plans, health
insurance, and other benefits an organization offers its
employees.</blockquote>
	<span class="header3">Education</span>
	<blockquote>In filling entry-level jobs, many employers seek
college graduates who have majored in  business administration,
business management, finance, or a related field. Many employers
prefer to hire managers who have a master's degree, particularly one
with a concentration in human resources management, finance, or
business administration (MBA). </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of Compensations and
Benefits Managers was $122,270 in May 2019. </blockquote>

<hr size="1" />

		<span class="header2">Executive
Assistant</span><br />
	<img class="job_pic" src="/images/icons/DE/1206.jpg"
width="100" height="100" border="0" alt="Executive Secretary" />
	<span class="header3">Job Description</span>
	<blockquote>Executive assistants perform a variety of
administrative and clerical duties necessary to run an organization
efficiently. They serve as information and communication managers
for an office; plan and schedule meetings and appointments; organize
and maintain paper and electronic files; manage projects; conduct
research; and disseminate information by using the telephone, mail
services, Web sites, and e-mail. They also may handle travel and
guest arrangements.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers of executive secretaries increasingly
are seeking candidates with a college degree, as these secretaries
work closely with top executives. A degree related to the business
or industry in which a person is seeking employment may provide the
job seeker with an advantage in the application process.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Themedian annual wage of executive assistants 
was $62,920 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Insurance Processing
Clerk</span><br />
	<img class="job_pic" src="/images/icons/DG/C506006.jpg"
width="100" height="100" border="0" alt="Insurance Processing
Clerk" />
	<span class="header3">Job Description</span>
	<blockquote>People who do the clerical work to help the
customers of an insurance company are insurance processing clerks.
In this job, you would process insurance policy applications. You
would also check the terms of the policy when a customer makes a
claim against the policy.  You would need to make sure that you
prepared the papers correctly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma for this
job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of insurance processing
clerks was $42,150 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">LEGAL/MILITARY SERVICES</span>
<p>The occupations found in this field require people who are
efficient and productive.  They also need people who are
dependable.  If you understand the importance of "doing your duty",
you may want to look at occupations in this field.</p>

<hr size="1" />

	<span class="header2">Court Reporter</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Courts are required to have somebody "record"
what is said in the courtroom during a trial or hearing. The person
who does this is a court reporter. As a court reporter, you would
use a stenotype machine which is a type of computer that allows you
to key in every word that the judge, lawyers, and witnesses say.
Some reporters work within the courtroom. Other reporters are 
self-employed and they work in different locations.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are special schools where you can earn a
degree in court reporting. These schools offer two or four year
programs. You might also have to pass a written test to become
certified by the state in which you work.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of court reporters was
$60,130 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Military Legal
Technician</span><br />
	<img class="job_pic" src="/images/icons/DG/43286.jpg"
width="100" height="100" border="0" alt="Military Legal
Technician" />
	<span class="header3">Job Description</span>
	<blockquote>To become a military legal technician, you would
have to join the military. In this job you would conduct research
and prepare for a trial in a military court. You would interview
witnesses. You would also keep the law books and trial information
needed for the case and you would make sure that legal paperwork
was done correctly. The duties of this job are much like those of a
paralegal in the civilian courts.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma to join
the military.  On-the-job training is provided.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is
based on your rank, years of service and occupational
specialty.</blockquote>

<hr size="1" />
<span class="header2">Administrative Support
Specialist</span><br />
<span class="header3">Job Description</span>
<blockquote>An administrative support specialist helps an
administrator do his/her job. In this job you would help with the
clerical duties of a military office.  You would type and
proofread.  You would also order supplies and organize and maintain
files.  You would use a computer to do your job.</blockquote>
<span class="header3">Education</span>
<blockquote>You need a high school diploma to join the
military.  On-the-job training is provided.</blockquote>
<span class="header3">Salary</span>
<blockquote>The median annual wage of civilian administrative support
specialists was $34,040 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 18, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 18, 2020). </blockquote>

</div>
