<span class="header1">Clerical/Administrative paired with
Science/Mathematics (DH)</span>

<p>If you scored high in categories "D" and "H," you naturally
understand that there are always ways to improve a situation.  You
can probably handle several tasks at one time. People like you have
made important contributions in business. You are an excellent
thinker.  You are also likely to be a no-nonsense kind of person.
You are creative and like to ask the question, "Why?" Because of
this, you will look for new ways to do tasks.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree. In some of these jobs, it helps to have a master's degree or
a Ph.D.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that emphasize math and
science. Any courses that help you develop efficiency will be of
great interest to you.  They will also help prepare you for possible
career opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Business Education<br />
			Computer Information Systems<br />
			Computer Programming<br />
			Environmental Science
		</td>
		<td>
			Biology<br />
			Calculus<br />
			Accounting<br />
			Physics
		</td>
		<td>
			Sociology<br />
			Economics<br />
			Psychology<br />
			Trigonometry
		</td>
		<td>
			Business Math<br />
			Communications<br />
			World Languages<br />
			Public Relations
		</td>
		<td>
			Geography<br />
			Life Science<br />
			Computer Sciences
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations you
may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. You will most enjoy any club or activity where you can
use your thinking skills.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Environmental Activities<br />
			Future Business Leaders<br />
			Math/Science Club<br />
			Audio/Visual Services
		</td>
		<td>
			Computer Club<br />
			Library Assistant<br />
			Chess Club<br />
			Tutoring
		</td>
		<td>
			Hospital Volunteer<br />
			Office Assistant<br />
			Newspaper/Yearbook
		</td>
		<td>
			Teaching Assistant<br />
			Community Volunteer<br />
			Class Officer<br />
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Printing Companies<br />
			Computer Sales Companies<br />
			Archeological Projects<br />
			Engineering Firms<br />
			TV/Radio Stations<br />
			Photographic Laboratories
		</td>
		<td>
			Veterinary Offices<br />
			Accounting Firms<br />
			Landscaping Firms<br />
			Printing Companies<br />
			Architect Firms<br />
			Newspaper Offices
		</td>
		<td>
			Theaters<br />
			Computer Services<br />
			Libraries<br />
			Medical Offices<br />
			Electronic Stores<br />
			Libraries<br />
		</td>
		<td>
			Restaurants<br />
			Data Entry<br />
			Landscaping Firms<br />
			Restaurants<br />
			Newspaper Offices
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">DH Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Administrative Services</span><br />
						<em>Medical Record
Administrator<br />
						Medical
							<ul>

	<li>Transcriptionist</li>

	<li>Assistant</li>

	<li>Secretary</li>

	<li>Receptionist</li>
							</ul>
						Pharmacist's
Assistant<br />
						Research
Assistant<br />
						Laboratory/Clinic
Manager<br />
						Medical Office
Manager<br />
						Human Service
Worker<br />
						Medical Coding
Specialist</em>
					</td>
					<td width="33%">
						<span
class="header2">Medical Services</span><br />
						<em>Geriatric
Assessment Coordinator<br />
						Physician's
Assistant<br />
						Nurse
Supervisor<br />
						Research
Analyst<br />
						Medical
Librarian<br />
						Dental
Hygienist<br />
						Science
Technician<br />
						Laboratory
Technologist<br />
						Licensed Practical
Nurse<br />
						Outpatient
Coordinator<br />
						Home Health Aide</em>
					</td>
					<td width="33%">
						<span
class="header2">Math Services</span><br />

	<em>Accountant<br />
						Bio-
statistician<br />
						Public Health
Program Specialist<br />

	Researcher<br />

	Bookkeeper<br />
						Purchasing
Agent<br />
						Computer
							<ul>

	<li>Systems Analyst</li>

	<li>Programmer</li>
						 </ul>
						Clerk
							<ul>

	<li>Accounting</li>

	<li>Statement</li>

	<li>Brokerage</li>
							</ul>
						Bank Teller</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">ADMINISTRATIVE SERVICES</span>
<p>If you work in an occupation in this field, you will work in a
medical facility. This may be a hospital, clinic, hospice, or
laboratory.</p>

<hr size="1" />

	<span class="header2">Medical Records and Health Information Technician
</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Technicians assemble patients' health
information making sure that patients' initial medical charts are
complete, that all forms are completed and properly identified and
authenticated, and that all necessary information is in the
computer. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Medical records and health information
technicians entering the field usually have an associate degree from
a community or junior college. Many employers favor technicians who
have become Registered Health Information Technicians (RHIT).
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of medical records and
health information technicians was $42,630 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Pharmacy Technician</span><br />
	<img class="job_pic" src="/images/icons/DH/1374.jpg"
width="100" height="100" border="0" alt="Medical Record
Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Pharmacy technicians help licensed Pharmacists
provide medication and other health care products to patients.
Technicians usually perform routine tasks to help prepare prescribed
medication such as counting tablets and labeling bottles. They also
perform administrative duties such as answering phones, stocking
shelves, and operating cash registers. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Most pharmacy technicians are trained on-the-
job, but employers favor applicants who have formal training,
certification, or previous experience. Strong customer service
skills also are important. Certification is required in some states.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of pharmacy technicians
was $33,950 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Medical Assistant</span><br />
	<img class="job_pic" src="/images/icons/DH/43148.jpg"
width="100" height="100" border="0" alt="Medical Assistant" />
	<span class="header3">Job Description</span>
	<blockquote>As a medical assistant, you would help a nurse
or doctor collect medical information from patients.  You would also
help store these records and make sure they were accurate and easy
to find. If you worked in a doctor's office, you would greet the
patient.  You would also take his/her temperature and blood
pressure and listen to the patient's heart before the doctor or
nurse sees him/her.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some medical assistants are trained on-the-job,
but many complete one-year or two-year programs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of medical assistants was
$34,800 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">MEDICAL SERVICES</span>
<p>The occupations in this field help others who are in need.</p>

<hr size="1" />

	<span class="header2">Medical Doctor</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Physicians and surgeons diagnose illnesses and
prescribe and administer treatment for people suffering from injury
or disease. Physicians examine patients, obtain medical histories,
and order, perform, and interpret diagnostic tests. </blockquote>
	<span class="header3">Education</span>
	<blockquote>The common path to practicing as a physician
requires eight years of education beyond high school and three to
eight additional years of internship and residency.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of medical doctors was
$208,000 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Dental Hygienist</span><br />
	<img class="job_pic" src="/images/icons/DH/C506012.jpg"
width="100" height="100" border="0" alt="Dental Hygienist" />
	<span class="header3">Job Description</span>
	<blockquote>As a dental hygienist, you would teach your
patients how to care for their teeth. You would clean their
teeth and take x-rays. Also, you would be an extra set of hands if
the dentist needed help.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most dental hygiene programs grant an associate
degree, although some also offer a certificate, a bachelor's degree,
or a master's degree. A minimum of an associate degree or
certificate in dental hygiene is generally required for practice in
a private dental office.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of dental hygienists was
$76,220 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Home Health Aide</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Demand for home health aides is growing because
more sick and elderly people prefer to stay home to recover from
illnesses. As a home health aide, you would help patients take care
of their daily activities such as eating and bathing. You would also
be in the home to talk and listen to the patient. This would help to
keep the patient's spirits up.</blockquote>
	<span class="header3">Education</span>
	<blockquote>In some states, the only requirement for
employment is on-the-job training which generally is provided by
employers. Other states may require formal training which is
available from community colleges, vocational schools, elder care
programs, and home health care agencies.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of home health aides was
$25,280 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">MATH SERVICES</span>
<p>For many of the occupations in this field, you must have a
background in computers. Also you would need math and reasoning
abilities.</p>

<hr size="1" />

	<span class="header2">Computer Programmer</span><br />
	<img class="job_pic" src="/images/icons/DF/43290.jpg"
width="100" height="100" border="0" alt="Computer Programme" />
	<span class="header3">Job Description</span>
	<blockquote>Computer programmers write, test, and maintain
the detailed instructions, called programs, that computers follow to
perform their functions. Programmers also conceive, design, and test
logical structures for solving problems by computer.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is commonly required for
computer programming jobs, although a two-year degree or certificate
may be adequate for some positions. Employers favor applicants who
already have relevant programming skills and experience. Skilled
workers who keep up to date with the latest technology usually have
good opportunities for advancement. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of computer programmers
was $86,550 in May 2019. </blockquote>


<hr size="1" />


	<span class="header2">Computer Scientist</span><br />
	<img class="job_pic" src="/images/icons/DF/43219.jpg"
width="100" height="100" border="0" alt="Computer Scientist" />
	<span class="header3">Job Description</span>
	<blockquote>Computer scientists work as theorists,
researchers, or inventors. The areas of computer science research
range from complex theory to hardware design to programming-language
design. Some researchers work on multidisciplinary projects, such as
developing and advancing uses of virtual reality, extending human-
computer interaction, or designing robots. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Most computer scientist positions require a master's 
degree or Ph.D. degree. Computer
scientists having only a bachelor's degree are generally
limited in their ability to advance. Technological advances come so
rapidly in the computer field that continuous study is necessary to
keep one's skills up to date.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of computer scientists
was $122,840 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Bill & Account
Collector</span><br />
	<img class="job_pic" src="/images/icons/DH/43335.jpg"
width="100" height="100" border="0" alt="Bill & Account Collector" />
	<span class="header3">Job Description</span>
	<blockquote>As a bill and account collector, you would make
sure that customers paid their overdue bills.  You might work for a
collection agency, bank, or department store.  Your job would be to
contact customers who had not paid their bills.  You would work with
these customers to encourage them to pay their bill.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most employers require collectors to have at a
least a high school diploma and prefer some customer service
experience. Employers usually provide on-the-job training to new
employees.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of bill and account
collectors was $37,000 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 21, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 21, 2020). </blockquote>

</div>
