<span class="header1">Clerical/Administrative paired with
Social/Helping (DI)</span>

<p>Your high scores in "D" and "I" show that you have
characteristics that are useful to people. You are seen as
dependable, friendly, and helpful. Others know that they can count
on you. No matter what you choose to do, you will want to know you
are helping people.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree.  In some of these jobs, it helps to have a master's degree
or a Ph.D.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that help you to understand
people. Any courses in social studies or social sciences will be of
interest to you.  They will also help prepare you for possible
career opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Logic<br />
			Education<br />
			Religion
		</td>
		<td>
			Computer Sciences<br />
			Health/Nutrition<br />
			Physical Education<br />
		</td>
		<td>
			Business Law<br />
			Life Sciences<br />
			Communications
		</td>
		<td>
			Psychology<br />
			Business Math<br />
			Sociology
		</td>
		<td>
			Bookkeeping<br />
			Home Economics<br />
			Business Education
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. You will most enjoy any club or activity where you can
use your people skills.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Church Activities<br />
			Childcare / Eldercare<br />
			Hospital Volunteer<br />
			Newspaper / Yearbook
		</td>
		<td>
			Library Assistant<br />
			Class Officer<br />
			Tutoring<br />
			Peer Counselor
		</td>
		<td>
			Community Volunteer<br />
			Audio / Visual Services<br />
			Future Business Leaders
		</td>
		<td>
			Office Assistant<br />
			Teaching Assistant<br />
			Camp Counselor
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising Agencies<br />
			Company Offices<br />
			Printing Companies<br />
			Life Guarding<br />
		</td>
		<td>
			Day Care Centers<br />
			Photography Studios<br />
			Preschool Programs<br />
			Special Olympics
		</td>
		<td>
			Church Programs<br />
			Newspaper Offices<br />
			Libraries<br />
		</td>
		<td>
			Restaurants<br />
			Camp Programs<br />
			Recreational programs
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">DI Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Education</span><br />
						<em>Education
Administrator<br />
						Teacher
							<ul>

	<li>Business</li>

	<li>Continuing Education</li>

	<li>Computer</li>

	<li>Math</li>

	<li>Physical Education</li>
							</ul>
						Nursing
Instructor<br />
						Career
Counselor<br />
						Library
Technician<br />
						Pre-school
Coordinator<br />
						Computer
Trainer<br />
						Camp
Counselor</em>
					</td>
					<td width="33%">
						<span
class="header2">Social Helping</span><br />
						<em>Assistant
Hospital Administrator<br />

	Clergy<br />
						Social Care
Worker<br />
						Marriage &
Family
Therapist<br />
						Retirement
Facility
Administrator<br />
						Traffic Safety
Administrator<br />
						Flight
Attendant<br />
						Cruise Ship
Activities Director<br />
						Convention
Coordinator<br />
						Meeting & Events
Planner<br />
						Nursery School
Child-
Care Provider</em>
					</td>
					<td width="33%">
						<span
class="header2">Administrative Helping</span><br />
						<em>Bank Branch
Manager<br />
						Contract
Administrator<br />
						Loan
Officer<br />
						Office
Manager<br />
						Insurance Sales
Agent<br />
						Hotel Desk
Clerk<br />
						Customer Service
Representative<br />
						Claims
Adjuster<br />
						Personnel
Clerk<br />
						Hospital
Receptionist<br />

	Secretary<br />
						Bank Teller</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">EDUCATION</span>
<p>The occupations in this field deal with helping others learn
more.</p>

<hr size="1" />

	<span class="header2">Education
Administrator</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Even in a school or college, somebody must be in
charge. An education administrator oversees the activities that go
on in a school, college, or school system. In this job, you might be
a school principal. You might also be a county superintendent, or a
dean at a college. You would make sure that the teachers,
professors, and other school personnel were doing their jobs. You
would set goals and plan educational or school programs as
well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a master's degree or Ph.D. to advance
in the field of education. Teaching experience is required as
well.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of education
administrators was $92,150 in May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Training and Development
Manager</span><br />
	<img class="job_pic" src="/images/icons/DI/1378.jpg"
width="100" height="100" border="0" alt="Computer Trainer" />
	<span class="header3">Job Description</span>
	<blockquote>Training and development managers and
specialists conduct and supervise training and development programs
for employees. Increasingly, management recognizes that training
offers a way of developing skills, enhancing productivity and
quality of work, building worker loyalty to the firm, and most
importantly, increasing individual and organizational performance to
achieve business results.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Many colleges and universities have programs
leading to a degree in personnel, human resources, or labor
relations. Some offer degree programs in human resources
administration or human resources management, training and
development, or compensation and benefits. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of training and
development managers was $113,350 in May 2019. </blockquote>

<hr size="1" />

<span class="header2">Recreation Worker</span><br />
	<img class="job_pic" src="/images/icons/DI/C557003.jpg"
width="100" height="100" border="0" alt="Camp Counselor" />
	<span class="header3">Job Description</span>
	<blockquote>Recreation workers plan, organize, and direct
activities in local playgrounds and recreation areas, parks,
community centers, religious organizations, camps, theme parks, and
tourist attractions.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The educational and training requirements for
recreation workers vary widely depending on the type of job. Full-
time career positions usually require a college degree. Many jobs,
however, can be learned with only a short period of on-the-job
training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of recreation workers was
$26,350 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">SOCIAL HELPING</span>
<p>These occupations are for people who want to give support and
encouragement to those in need.</p>

<hr size="1" />

	<span class="header2">Clergy</span><br />
	<img class="job_pic" src="/images/icons/DI/43007.jpg"
width="100" height="100" border="0" alt="Clergy" />
	<span class="header3">Job Description</span>
	<blockquote>Conduct religious worship and perform other
spiritual functions associated with beliefs and practices of
religious faith and denomination. They also provide spiritual and moral
guidance and assistance to members.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree to enter
this occupation. A master degree or Ph.D. is often required. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of clergies was $50,400 in
May 2019.</blockquote>

<hr size="1" />

	<span class="header2">Registered Nurse</span><br />
	<img class="job_pic" src="/images/icons/DI/43148.jpg"
width="100" height="100" border="0" alt="Medical Assistant" />
	<span class="header3">Job Description</span>
	<blockquote>Registered nurses (RNs), regardless of specialty
or work setting, treat patients, educate patients and the public
about various medical conditions, and provide advice and emotional
support to patients' family members. RNs record patients' medical
histories and symptoms, help perform diagnostic tests and analyze
results, operate medical machinery, administer treatment and
medications, and help with patient follow-up and
rehabilitation.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The three major educational paths to registered
nursing are a bachelor's degree, an associate degree, and a diploma
from an approved nursing program.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of registered nurses was
$73,300 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Child Care Worker</span><br />
	<span class="header3">Job Description</span>
	<blockquote>A childcare worker has to enjoy being around
small children because they take care of children ages five and
under.
You would help keep them occupied and happy with activities. You
would see that they got enough rest.  You would also help them to
enjoy snacks and meal times. You would probably work with groups of
children in a nursery, preschool, or daycare center.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma for this
job.  Many employers want to hire people who have experience working
with children.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of child care workers was
$24,230 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">ADMINISTRATIVE HELPING</span>
<p>If you chose an occupation in this field, you would provide
support and help in a company.</p>

<hr size="1" />

<span class="header2">Pharmacy
Technician</span><br />
	<img class="job_pic" src="/images/icons/DH/1374.jpg"
width="100" height="100" border="0" alt="Medical Record
Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Pharmacy technicians help licensed pharmacists
provide medication and other health care products to patients.
Technicians usually perform routine tasks to help prepare prescribed
medication such as counting tablets and labeling bottles. They also
perform administrative duties such as answering phones, stocking
shelves, and operating cash registers. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Most pharmacy technicians are trained on-the-
job, but employers favor applicants who have formal training,
certification, or previous experience. Strong customer service
skills also are important. Certification is required in some states.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of pharmacy technicians
was $33,950 in May 2019. </blockquote>
<hr size="1" />

	<span class="header2">Human Resources
Assistant</span><br />
	<img class="job_pic" src="/images/icons/DI/43302.jpg"
width="100" height="100" border="0" alt="Office Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Human resources assistants keep records of a
company's employees. Every day human resources assistants update
information and answer questions about employees. They also may
create reports for managers. They get information from job
applicants about their education and work experience. They give out
tests and explain the company's rules.</blockquote>
	<span class="header3">Education</span>
	<blockquote>These workers must have at least a high school
diploma or a G.E.D. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of human resources
assistants was $41,430 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Computer Support
Specialist</span><br />
	<img class="job_pic" src="/images/icons/DI/43328.jpg"
width="100" height="100" border="0" alt="Personnel Clerk" />
	<span class="header3">Job Description</span>
	<blockquote>Computer support specialists help people use
computers. When something goes wrong, support specialists figure out
why. Then, they try to fix it. Computer support specialists also
install printers, software, and other computer tools. Then, they
teach people how to use them.

</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some people earn an associate degree. Some
employers prefer to hire people who earn a bachelor's degree.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of computer support
specialists was $54,760 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 21, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 21, 2020). </blockquote>

</div>
