<span class="header1">Protective/Military Service paired with
Technology (EF)</span>

<p>With an "EF" interest, you will want to push your physical and
mental strengths to their limits. You will want to be challenged and
have adventures along the way.</p>
<p>Many of the occupations in this pairing require some sort of
specialized training after high school. Some require college degrees
or college level courses.  For others, you will need technical
training.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that allow you to challenge
your mind. You will want to take technical courses too.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Business Law<br />
			Computer Sciences<br />
			Economics<br />
			Graphic Art<br />
		</td>
		<td>
			Computer Technology<br />
			Public Relations<br />
			Business Education<br />
			Computer Technology<br />
			Government/Civics
		</td>
		<td>
			Computer Programming<br />
			Environmental Sciences<br />
			Physical Education<br />
			Industrial Technology
		</td>
		<td>
			Logic<br />
			Sociology<br />
			History<br />
			Physics
		</td>
		<td>
			Drafting<br />
			Business Math<br />
			World Languages<br />
			Political Science
		</td>
	</tr>
</table>

<p><strong>Extracurricular / volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for after-school activities or part-time jobs, make
them count. Any club or activity where you are mentally and
physically challenged will be valuable. You will also want
technology to be a part of the activities.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Audiovisual Services<br />
			Newspaper/Yearbook<br />
			Math/Science Clubs
		</td>
		<td>
			Flight Training<br />
			Camp Activities<br />
			Library Assistant
		</td>
		<td>
			ROTC<br />
			Athletics<br />
			Scouts
		</td>
		<td>
			Band<br />
			Computer Club<br />
			Martial Arts
		</td>
		<td>
			Language Club<br />
			Parks/Recreation
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Appliance Repair<br />
			Environmental Services<br />
			Newspaper Offices<br />
			Photography Studios<br />
			Small Engine Repair
		</td>
		<td>
			Camp Counseling<br />
			Equipment Operations<br />
			Data Processing<br />
			Graphic Design Firms<br />
			Park Services<br />
		</td>
		<td>
			Lumberyards<br />
			Printing Companies<br />
			Construction<br />
			Equipment Repair<br />
			Landscaping Firms
		</td>
		<td>
			Company Offices<br />
			Delivery Services<br />
			Photographic Labs<br />
			Radio/TV Stations
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">EF Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Military</span><br />
						<em>Transportation
Director<br />
						Military
Strategist<br />
						Air Traffic
Controller<br />
						Communications
Manager<br />
						Ship
Captain<br />
						Space Systems
Specialist<br />
						Recruiter<br />
						Flight Crew
Member<br />
						Recreation
Scout<br />
						Flight Operations
Specialist<br />
						Radar
Operator<br />
						Aircraft
Technician</em>
					</td>
					<td width="33%">
						<span
class="header2">Technology Operations</span><br />

	<em>Archeologist<br />
						Geologist<br />

	Cartographer<br />
						Physical Education
Teacher<br />
						Alcohol, Tobacco,
and Firearms Agent<br />
						Sports
Coordinator<br />
						Professional
Athlete<br />
						State
Trooper<br />
						Truck
Driver<br />
						Plumber<br />
						Heavy Equipment
Operator</em>
					</td>
					<td width="33%">
						<span
class="header2">Technology</span><br />
						<em>Engineer
							<ul>

	<li>Structural</li>

	<li>Electronics</li>

	<li>Mechanical</li>

	<li>Robotics</li>

	<li>Waste Management</li>
							</ul>
						Aircraft
Pilot<br />

	Millwright<br />

	Electrician<br />
						Computer Service
Technician<br />
						Mechanical
Engineering Technician<br />
						Aircraft
Technician<br />
						Computer
Operator<br />
						Machinist</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">MILITARY</span>
<p>There are many technical jobs in the military that offer
excitement and challenge. You may find one of these to be to your
liking.</p>

<hr size="1" />

	<span class="header2">Air Traffic
Controller</span><br />
	<img class="job_pic" src="/images/icons/EF/43161.jpg"
width="100" height="100" border="0" alt="Air Traffic Controller" />
	<span class="header3">Job Description</span>
	<blockquote>An air traffic controller uses radar and
computer equipment to track aircraft while they are in the air. As
an air traffic controller, you would talk to the aircraft pilots at
take-off and landing. You would make sure that only one aircraft was
on the runway at a time. You would also make sure that they stayed a
certain distance from each other while they were in the air.  This
is an important job.  Many people's safety depends on the
controller.  You can also do this job as a civilian.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Training to become an air traffic controller is
very rigorous. Applicants must have three years of full-time work
experience and four years of college (or a combination of the two).
Then they must enroll in an FAA-approved education program and pass
a pre-employment test. Upon successful completion of an FAA-approved
program, those who receive school recommendation attend the FAA
Academy in Oklahoma City, OK, for 12 weeks of training. Then
applicants work two to four more years gaining on-the-job training
to become certified as professional air traffic controllers. Those
who have served in the military are exempted from some of the
requirements. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of civilian air traffic
controllers was $122,990 in May 2019. The yearly salary you receive 
in the military is based on your rank, years of service and occupationalspecialty. </blockquote>

<hr size="1" />

	<span class="header2">Pilot </span><br />
	<img class="job_pic" src="/images/icons/EF/M041.jpg"
width="100" height="100" border="0" alt="Air Crew Member" />
	<span class="header3">Job Description</span>
	<blockquote>Pilots are highly trained professionals who
either fly airplanes or helicopters. Except on small aircraft, two
pilots usually make up the cockpit crew. Generally the most
experienced pilot, the captain, is in command and supervises all
other crew members. The pilot and the copilot, often called the
first officer, share flying and other duties such as communicating
with air traffic controllers and monitoring the instruments.
</blockquote>
	<span class="header3">Education</span>
	<blockquote>To qualify for FAA licensure, applicants must be
at least 18 years old and have at least 250 hours of flight
experience. All pilots who are paid to transport passengers or cargo
must have a commercial pilot's license with an instrument rating
issued by the FAA. Initial training for airline pilots typically
includes a week of company indoctrination; three to six weeks of
ground school and simulator training; and 25 hours of initial
operating experience, including a check-ride with an FAA aviation
safety inspector. Once trained, pilots are required to attend
recurrent training and simulator checks once or twice a year
throughout their career. Most pilots have a college degree. Many
pilots have served and been trained in the military. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of pilots was $121,430 in
May 2019. </blockquote>

<hr size="1" />

<span class="header1">OUTDOOR OPERATIONS</span>
<p>The occupations found in this category are for people who like
working with equipment, tools, and technology. If this sounds like
you, you might want to work in this field.</p>

<hr size="1" />

	<span class="header2">Cartographer or
Photogrammetrist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Cartographers and photogrammetrists collect,
analyze, interpret, and map geographic information from surveys and
from data and photographs collected using airplanes and
satellites.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Cartographers and photogrammetrists usually have
a bachelor's degree in cartography, geography, surveying,
engineering, forestry, computer science, or a physical science,
although a few enter these positions after working as technicians.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of cartographers was
$65,470 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Truck Driver</span><br />
	<img class="job_pic" src="/images/icons/EF/1168.jpg"
width="100" height="100" border="0" alt="Truck Driver" />
	<span class="header3">Job Description</span>
	<blockquote>As a truck driver, you would take loads of goods
and produce across the country to be sold. You would be responsible
for whatever you were hauling in your truck until you delivered it
to its drop-off location.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The Department of Transportation requires
truck drivers to be at least 21 years old, have at least 20/40
vision and good hearing, and be able to read and speak English. They
also must have good driving records and a commercial driver's
license, which they obtain by passing a written examination and a
skills test in which they operate the type of vehicle they will be
driving. Some truck drivers enter the occupation by attending
training schools. Many large trucking companies have formal training
programs that prospective drivers attend. Other companies assign
experienced drivers to teach and mentor newer drivers.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of truck drivers was
$45,260 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2"> Cargo and Freight Agent
</span><br />

	<span class="header3">Job Description</span>
	<blockquote>A Cargo and Freight Agent directs
ground crew in the loading, unloading, securing, and staging of
aircraft cargo or baggage. They determine the quantity and
orientation of cargo and compute aircraft center of gravity. The
cargo and freight agent may accompany aircraft as a
member of a flight crew and monitor and handle cargo in flight, and
assist and brief passengers on safety and emergency
procedures.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most Cargo and Freight Agents learn
from work experience rather than from post-secondary training. It
will be important to be a good leader to be successful in this
job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of cargo and freight agents was $46,070 in May 2019.</blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY</span>
<p>If you like a hands-on approach to technology, you might like the
occupations in this field.</p>

<hr size="1" />

	<span class="header2">Environmental Engineering Technician
</span><br />
	<img class="job_pic" src="/images/icons/EF/C0936_02.jpg"
width="100" height="100" border="0" alt="Electronic Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>Environmental engineering technicians work
closely with environmental engineers and scientists in developing
methods and devices used in the prevention, control, or correction
of environmental hazards. They inspect and maintain equipment
related to air pollution and recycling. Some inspect water and
wastewater treatment systems to ensure that pollution control
requirements are met.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most engineering technicians enter the
occupation with an associate degree in engineering technology. Those
preparing to work in environmental engineering technology need
courses in environmental regulations and safe handling of hazardous
materials. Training is available at technical institutes, community
colleges, extension divisions of colleges and universities, public
and private vocational-technical schools, and in the Armed Forces.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of environmental
engineering technicians was $50,620 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Carpenter</span><br />
	<img class="job_pic" src="/images/icons/EF/C1610_07.jpg"
width="100" height="100" border="0" alt="Millwright" />
	<span class="header3">Job Description</span>
	<blockquote>Carpenters are involved in many different kinds
of construction, from the building of highways and bridges to the
installation of kitchen cabinets. Carpenters construct, erect,
install, and repair structures and fixtures made from wood and other
materials. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Learning to be a carpenter can start in high
school with classes in English, algebra, geometry, physics,
mechanical drawing, blueprint reading, and general shop. After high
school some people get a job as a carpenter's helper, assisting
more experienced workers. Some employers offer employees formal
apprenticeships which usually last three to four years, depending on
the apprentice's skill. Trade, vocational schools, and community
colleges offer further trade-related training for those who plan to
become carpenters. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of carpenters was $48,330
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Physical Therapist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Physical therapists provide services that help
restore function, improve mobility, relieve pain, and prevent or
limit permanent physical disabilities of patients suffering from
injuries or disease. They restore, maintain, and promote overall
fitness and health. Treatment often includes exercise, especially
for patients who have been immobilized or who lack flexibility,
strength, or endurance. Physical therapists also use electrical
stimulation, hot packs or cold compresses, and ultrasound to relieve
pain and reduce swelling. They may use traction or deep-tissue
massage to relieve pain and improve circulation and flexibility.
Therapists also teach patients to use assistive and adaptive
devices such as crutches, prostheses, and wheelchairs. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Individuals pursuing a career as a physical
therapist need a Doctor of Physical Therapy (DPT) degree and a state 
license requiring passing scores on
national and state examinations. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of physical therapists
was $89,440 in  May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 21, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 21, 2020). </blockquote>

</div>

