<span class="header1">Protective/Military Service paired with Public
Service (EG)</span>

<p>Your high scores in this pairing show that you can be put into
positions of leadership and responsibility. You are reliable and
honest. You are also supportive and resourceful. You are the kind of
person that employers prefer. You can plan and coordinate events as
well as guide and influence people.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree. It is helpful to have a master's degree or Ph.D. if you hope
to work in some of these occupations.</p>
<p><strong>Courses you may want to consider taking in high school
and beyond (in addition to English & Math):</strong><br />
In high school you should take courses that will help you to
understand people and train you for leadership roles. Social studies
courses such as political science and sociology may interest you.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Drafting<br />
			Civics<br />
			Psychology<br />
			Geography
		</td>
		<td>
			Health/Nutrition<br />
			Physical Education<br />
			Computer Technology<br />
			Political Science
		</td>
		<td>
			Business Law<br />
			Communications<br />
			Business Math<br />
			Public Speaking
		</td>
		<td>
			Government<br />
			History<br />
			Music<br />
			Sociology<br />
		</td>
		<td>
			World Languages<br />
			Industrial Technology<br />
			Advertising/Marketing<br />
			Criminal Justice
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for after-school activities or part-time jobs, make
them count. You will most enjoy any club or activity where you can
use your mental and physical strength.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Band<br />
			Chess Club<br />
			ROTC
		</td>
		<td>
			Flight Training<br />
			Camp Activities<br />
			Hospital Volunteer
		</td>
		<td>
			Language Club<br />
			Martial Arts<br />
			Athletics
		</td>
		<td>
			Church Activities<br />
			Parks & Recreation<br />
			Youth Organizations
		</td>
		<td>
			Peer Counselor<br />
			Safety Patrol<br />
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Business Offices<br />
			Legal Offices<br />
			Newspaper Offices
		</td>
		<td>
			Camp Counseling<br />
			Courthouse Offices<br />
			Libraries
		</td>
		<td>
			Church Programs<br />
			Radio/TV Studios<br />
			Retail Stores
		</td>
		<td>
			Graphic Design Firms<br />
			Recreation Departments<br />
			Political Offices
		</td>
		<td>
			Special Olympics<br />
			Youth Coaching<br />
			Life Guarding
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">EG Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Community</span><br />
						<em>Social Worker
							<ul>

	<li>Drug & Alcohol</li>

	<li>Family</li>

	<li>Public Health</li>
							</ul>
						Public Health
Consultant<br />
						Public Affairs
Officer<br />
						Postal Service
Administrator<br />

	Firefighter<br />
						Postal Service
Personnel<br />
						Religious Program
Specialist<br />
						Public Health Field
Worker</em>
					</td>
					<td width="33%">
						<span
class="header2">Legal</span><br />

	<em>Lawyer<br />
						Labor Relations
Specialist<br />
						Police
Chief<br />
						County
Sheriff<br />
						FBI Agent<br />
						Investigator
Detective<br />
						Police
Officer<br />
						Legal
Technician<br />
						Customs
Agent<br />
						Security Guard</em>
					</td>
					<td width="33%">
						<span
class="header2">Military</span><br />

	<em>Chaplain<br />
						Engineer<br />
						Military
Officer<br />
						Transportation
Manager<br />
						Military
Police<br />
						Recruiting
Specialist<br />
						Interpreter &
Translator<br />
						Military
Trainer<br />
						Emergency Management
Specialist<br />
						Medic</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">COMMUNITY</span>
<p>If you want to help the people of your community, consider these
occupations. They focus on helping the community stay healthier
and/or happier.</p>

<hr size="1" />

	<span class="header2">Public Health Social
Worker</span><br />
	<img class="job_pic" src="/images/icons/EG/1212.jpg"
width="100" height="100" border="0" alt="Public Health Social
Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Social work is a profession for those with a
strong desire to help improve people's lives. Social workers assist
people by helping them cope with issues in their everyday lives,
deal with their relationships, and solve personal and family
problems. Some social workers help clients who face a disability or
a life-threatening disease or a social problem such as inadequate
housing, unemployment, or substance abuse. Social workers also
assist families that have serious domestic conflicts, sometimes
involving child or spousal abuse.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is the minimum requirement
for entry into the occupation, but many positions require an
advanced degree. All states and the District of Columbia have some
licensure, certification, or registration requirement, but the
regulations vary.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of public health social
workers was $59,300 in May 2019. </blockquote>

<hr size="1" />

	<span class="header1">Medical and Health Services
Managers</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Medical and health services managers, also
referred to as health care executives or health care administrators,
plan, direct, coordinate, and supervise the delivery of health care.
These workers are either specialists in charge of a specific
clinical department or generalists who manage an entire facility or
system.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A master's degree is the standard credential,
although a bachelor's degree is adequate for some entry-level
positions.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of medical and health
services managers was $100,980 in May 2019. </blockquote>


<hr size="1" />

<span class="header1">LEGAL</span>
<p>The occupations in this field are for people who are
trustworthy.  They are also for people who do not mind asking a lot
of questions and can keep up with details.</p>

<hr size="1" />

	<img class="job_pic" src="/images/icons/EG/43222.jpg"
width="100" height="100" border="0" alt="Industrial Labor Relations
Specialist" />
	<span class="header2">Industrial Labor Relations
Specialist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Labor relations managers and their staffs
implement industrial labor relations programs. Labor relations
specialists prepare information for management to use during
collective bargaining agreement negotiations, a process that
requires the specialist to be familiar with economic and wage data
and to have extensive knowledge of labor law and collective
bargaining trends.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most labor relations jobs require at least a 
bachelor's degree in industrial or labor relations. A graduate degree and 
strong background in industrial relations and law are highly desirable 
for contract negotiators, mediators, and arbitrators; in fact, many people in these
specialties are lawyers. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of industrial labor
relations specialists was $69,020 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Police Detective</span><br />
	<span class="header3">Job Description</span>
	<blockquote>As a police detective, you would investigate
crimes to find out what happened and who was involved. This is an
exciting occupation.  But it can be a dangerous job too.  To do this
job well you must be able to look at a crime scene and take in as
much information as possible.  You also must be a good listener so
that you can take in information while a witness or suspect is
talking.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Applicants usually must have at least a high
school education and some departments require one or two years of
college coursework or, in some cases, a college degree. To be
considered for appointment as an FBI agent, an applicant must be a
college graduate and have at least three years of professional work
experience or have an advanced degree plus two years of professional
work experience. Continuing training helps police officers,
detectives, and special agents improve their job performance.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of police detectives was
$65,170 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Security Guard</span><br />
	<img class="job_pic" src="/images/icons/EG/43109.jpg"
width="100" height="100" border="0" alt="Security Guard" />
	<span class="header3">Job Description</span>
	<blockquote>As a security guard, you would patrol a building
to protect it. You would make sure that the office property was not
stolen and that no one was trespassing. Many security guards work
at night. Others work during the day while workers are in the
building.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.
You also need a valid driver's license.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of security guards was
$29,680 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">MILITARY</span>
<p>One of the main functions of the military is to help local
communities. The occupations in this field do this.</p>

<hr size="1" />

	<span class="header2">Recruiting
Specialist</span><br />
	<img class="job_pic" src="/images/icons/EG/M37.jpg"
width="100" height="100" border="0" alt="Recruiting Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>A recruiting specialist helps those who are
interested in joining the military to sign up. In this job, you
would interview people who wanted to join the military.  You would
also speak to high school and community groups.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You would need a high school diploma to become a
recruiting specialist. Courses in English, social studies, and
public speaking are valuable.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military isbased on your rank, years of service and occupationalspecialty. </blockquote>

<hr size="1" />

	<span class="header2">Emergency Management
Specialist</span><br />
	<img class="job_pic" src="/images/icons/EG/M002.jpg"
width="100" height="100" border="0" alt="Emergency Management
Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>Emergency management specialists work for the
military.  If you were a specialist, you would develop and oversee
plans for disaster relief if there should be an emergency. You would
supervise others in how to provide this relief. You would also tell
people what to do if there was an emergency.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The military provides training to people who
want to work in this occupation.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military isbased on your rank, years of service and occupationalspecialty. </blockquote>

<hr size="1" />

	<span class="header2">Military Trainer</span><br />
	<img class="job_pic" src="/images/icons/EG/M99.jpg"
width="100" height="100" border="0" alt="Military Trainer" />
	<span class="header3">Job Description</span>
	<blockquote>A military trainer is a teacher. As a military
trainer, you would teach, lecture, and test military personnel. You
might train new recruits on how to drive a tank. Or, you might teach
officers to use a new computer program. You would actually do many
of the same things your classroom teacher does to prepare for
his/her students.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree for this job. Some
training would be provided by the military.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military isbased on your rank, years of service and occupationalspecialty. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 21, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 21, 2020). </blockquote>

</div>
