<span class="header1">Protective/Military Service paired with
Science/Mathematics (EH)</span>

<p>If you scored high in the "E" and "H" categories, you naturally
understand that there are always ways to improve a situation.
People like you have helped to discover much information about the
world. You are an excellent thinker and are probably a hands-on kind
of person. You are creative and like physical challenges.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree. It is helpful to have a master's degree or Ph.D. if you hope
to work in some of these occupations.</p>
<p><strong>Courses you may want to take in high school and beyond
(In addition to English & Math):</strong><br />
In high school you should take courses that emphasize math and
science. You will also enjoy courses that allow you to use your
physical strength.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting<br />
			Biology<br />
			Calculus
		</td>
		<td>
			Economics<br />
			Business Law<br />
			Chemistry
		</td>
		<td>
			Physics<br />
			Sociology<br />
			History
		</td>
		<td>
			Graphic Art<br />
			Political Science<br />
			Telecommunications
		</td>
		<td>
			Environmental Science<br />
			Technology Education<br />
			Computer Information Systems
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count.  You will enjoy any club or activity where you can use
your thinking skills to face mental and physical challenges.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Athletics<br />
			ROTC<br />
			Martial Arts
		</td>
		<td>
			Flight Training<br />
			Parks/Recreation<br />
			Camp Activities
		</td>
		<td>
			Scouts<br />
			Tutoring<br />
			Band
		</td>
		<td>
			Computer Club<br />
			Chess Club<br />
			Language Club
		</td>
		<td>
			Hospital Volunteer<br />
			Environmental Activities<br />
			Math/Science Club
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting Firms<br />
			Athletic Programs<br />
			Data Entry
		</td>
		<td>
			Landscaping Firms<br />
			Newspaper Offices<br />
			Radio/TV Stations
		</td>
		<td>
			Electronic Stores<br />
			Photographic Labs<br />
			Medical Offices
		</td>
		<td>
			Architect Firm<br />
			Computer Services<br />
			Engineering Firms
		</td>
		<td>
			Printing Companies<br />
			Sports Companies<br />
			Veterinary Offices
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">EH Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Medical Sciences</span><br />

<em>Physician<br />
						Military Medical
Officer<br />
						Sports
Psychologist<br />
						Exercise
Physiologist<br />
						Hospital
Administrators<br />
						Health Sciences
Librarian<br />

	Dietitian/Nutritionist<br />
						Recreation
Therapist<br />
						Nurse<br />
						Paramedic<br />
						Technician
							<ul>

	<li>Medical

	<li>Operation Room

	<li>Military Cardiopulmonary</li>
							</ul></em>
					</td>
					<td width="33%">
						<span
class="header2">Environmental</span><br />

	<em>Archeologist<br />
						Urban/Regional
Planner<br />
						Marine
Biologist<br />
						Engineer
							<ul>

	<li>Aerospace</li>

	<li>Environmental</li>

	<li>Nuclear</li>
							</ul>
						Environmental Risk
Manager<br />

	Meteorologist<br />
						Military
							<ul>

	<li>Land Surveyor</li>

	<li>Weather Observer</li>

	<li>Environmental Health Specialist</li>
							</ul>
						Land
Surveyor<br />
						Waste Management
Technician</em>
					</td>
					<td width="33%">
						<span
class="header2">Math/Analyst</span><br />

	<em>Economist<br />

	Mathematician<br />
						Actuary<br />

	Statistician<br />
						Military
							<ul>

	<li>Strategist</li>

	<li>Financial Manager</li>

	<li>Intelligence Officer</li>
							</ul>
						Analyst
							<ul>

	<li>Budget</li>

	<li>Research</li>

	<li>Computer Systems</li>
							</ul>
						Computer Security
Specialist<br />
						Mapping
Technician</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">MEDICAL</span>
<p>The occupations in this field require people who think very
well.  If you enjoy mental challenges, the occupations in this field
may be for you.</p>

<hr size="1" />

	<span class="header2">Podiatrist</span><br />
	<img class="job_pic" src="/images/icons/EH/40210.jpg"
width="100" height="100" border="0" alt="Podiatrist" />
	<span class="header3">Job Description</span>
	<blockquote>A podiatrist is a medical doctor who treats feet
and lower legs. As a podiatrist you would work with patients to help
correct problems in these two important areas of the body. You might
even be a surgeon who operates when necessary. Your goal would be to
help people walk better without pain or discomfort. Sports medicine
is a branch of podiatry.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Podiatrists must be licensed, requiring three to
four years of undergraduate education, the completion of a four-year
podiatric college program, and passing scores on national and state
examinations.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of podiatrists was
$126,240 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Military Cardiopulmonary & EEG
Technician</span><br />
	<span class="header3">Job Description</span>
	<blockquote>As a military cardiopulmonary & EEG technician,
you would do medical tests on a patient's heart and lungs.  You
would also take the patient's blood pressure. You would report your
findings to the doctor. This occupation can be found in civilian
hospitals as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>On-the-job training is provided for those in the
military.  You would need a high school diploma to be admitted to a
training program. For civilians, most receive training in two to
four year programs. The majority of technologists complete a two-
year junior or community college program, but four-year programs are
increasingly available.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is
based on your rank, years of service and occupational specialty.
</blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>The occupations in this field give you a chance to work with and
help protect the environment.</p>

<hr size="1" />

	<span class="header2">Urban Planner</span><br />
	<img class="job_pic" src="/images/icons/EH/43137.jpg"
width="100" height="100" border="0" alt="Urban Planner" />
	<span class="header3">Job Description</span>
	<blockquote>The word "urban" means "city." An urban planner
works with agencies that are concerned with the growth of cities. As
an urban planner, you would help cities grow in ways that are good
for the environment and for people.  You might decide that a new
street is needed or that old buildings should be repaired. You might
work to ensure that water and sewage are available when new
communities are developed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most entry-level jobs in federal, state, and
local governments require a master's degree from an accredited
program in urban or regional planning or a related field, such as
urban design or geography. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of urban planners was
$74,350 in May 2019. </blockquote>

<hr size="1" />


	<span class="header2">
Geotechnical Engineer</span><br />
	<img class="job_pic" src="/images/icons/EH/1151.jpg"
width="100" height="100" border="0" alt="Geotechnical Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>Tunnels through mountains are possible because
geotechnical engineers have been hard at work. Geotechnics is a 
branch of civil engineering. In this job, you would make and 
oversee plans for structures above or below ground.
You might build tunnels through mountains or under bodies of
water.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Bachelor's degree programs in engineering
typically are designed to last four years, but many students find
that it takes between four and five years to complete their studies.
In a typical four year college curriculum, the first two years are
spent studying mathematics, basic sciences, introductory
engineering, humanities, and social sciences. In the last two years,
most courses are in engineering, usually with a concentration in one
specialty. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of civil engineers was $87,060
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Occupational Health and
Safety Specialist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Occupational health and safety specialists
analyze work environments and design programs to control, eliminate,
and prevent disease or injury. They look for chemical, physical,
radiological, and biological hazards, and they work to make more
equipment ergonomic-designed to promote proper body positioning,
increase worker comfort, and decrease fatigue. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Some employers require occupational health and
safety specialists to have a bachelor's degree in occupational
health, safety, or a related field such as engineering, biology, or
chemistry. For some positions, a master's degree in industrial
hygiene or a related subject is required. There also are associate
degree and one-year certificate programs, which primarily are
intended for technicians. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of occupational health and safety specialists
was $74,100 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">MATH/ANALYSIS</span>
<p>Those who work in occupations in this field are good with
numbers. If you have a strong interest and ability in mathematics,
you might find them interesting.</p>

<hr size="1" />

	<span class="header2">Actuary</span><br />
	<img class="job_pic" src="/images/icons/EH/1287.jpg"
width="100" height="100" border="0" alt="Actuary" />
	<span class="header3">Job Description</span>
	<blockquote>Most people have insurance in one form or
another. They make payments called premiums. The person who decides
how much each person pays is an actuary.  As an actuary, you would
study statistics and set the price that the policyholder must
pay.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Actuaries need a strong foundation in
mathematics, statistics, and general business. They generally have a
bachelor's degree and are required to pass a series of exams in
order to become certified.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of actuaries was $108,350
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Financial
Manager</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Financial managers oversee the preparation of
financial reports, direct investment activities, and implement cash
management strategies. Managers also develop strategies and
implement the long-term goals of their organization.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Financial managers need a bachelor's
degree. Many have a master's degree or professional
certification and several years of experience in a related 
occupation such as accounting. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of financial managers was
$129,890 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Cartographer/Photogrammetrist
</span><br />
	<img class="job_pic" src="/images/icons/EH/43169.jpg"
width="100" height="100" border="0" alt="Mapping Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Cartographers and photogrammetrists collect,
analyze, interpret, and map geographic information from surveys and
from data and photographs collected using airplanes and satellites.
They prepare maps that give both physical and social characteristics
of the land. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Cartographers and photogrammetrists usually have
a bachelor's degree in cartography, geography, surveying,
engineering, forestry, computer science, or a physical science,
although a few enter these positions after working as technicians.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of cartographers was
$65,470 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 21, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 21, 2020). </blockquote>

</div>
