<p class="lead">CHARACTERISTICS OF THE <strong>"F"</strong> CATEGORY</p>
<p class="header2">TECHNOLOGY</p>
<p>If you have a high score in category "F," your results show that 
you are interested in new technology.  You are good at solving 
problems because you are inquisitive by nature. You are proficient 
with equipment which means you would enjoy a job where you handle, 
operate, program, design, repair, or engineer technological 
equipment. Many of the occupations in this pairing require that you 
have specialized and/or technical training after high school. Others 
require college degrees or college level courses. You are very 
important because technology jobs are so valuable to our country's 
economic progress. </p>
