<p class="header1">Technology paired with Public Service (FG)</p>

<p>You will be a valued member of the work force. You are very
community minded and prefer a "hands-on" approach. You want to make
the world a better place through technology.  There are many
occupations that require being able to work with people, machines,
and tools.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree. It is helpful to have a master's degree or Ph.D. if you hope
to work in some of these occupations.</p>
<p class="headsm">Courses you may want to take in high school and beyond (in addition to English & Math):</p>
<p>In high school you should take courses that will help you
understand people, machines, and tools. Technology courses such as
computer science and programming will be of interest to you.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Government/Civics<br />
			Public Speaking<br />
			Computer Sciences<br />
			Business Law<br />
			Physical Education
		</td>
		<td>
			Computer Programming<br />
			Marketing/Advertising<br />
			Technology Education<br />
			Environmental Science
		</td>
		<td>
			Geography<br />
			Psychology<br />
			Sociology<br />
			Economics
		</td>
		<td>
			Business Math<br />
			World Languages<br />
			Public Speaking<br />
			Political Science
		</td>
		<td>
			Telecommunications<br />
			Health/Nutrition<br />
			Business Education
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for after-school activities or part-time jobs, make
them count. You will enjoy any club or activity where you can use
technology.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td valign="top">
			Church Activities<br />
			Hospital Volunteer<br />
			Computer Club<br />
			Library Assistant
		</td>
		<td>
			Audio/Visual Services<br />
			Environmental Activities<br />
			Youth Organizations
		</td>
		<td>
			Chess Club<br />
			Safety Patrol<br />
			Tutoring
		</td>
		<td>
			Camp Counselor<br />
			Newspaper/Yearbook<br />
			Math/Science Clubs
		</td>
		<td>
			Peer Counselor<br />
			Martial Arts
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Graphic Design Firms<br />
			Printing Companies<br />
			Road Construction
		</td>
		<td>
			Camp Counseling<br />
			Life Guarding<br />
			Youth Coaching
		</td>
		<td>
			Church Programs<br />
			Newspaper Offices<br />
			Legal Activities
		</td>
		<td>
			Special Olympics<br />
			Libraries<br />
			Recreation Depts.
		</td>
		<td>
			Courthouse Offices<br />
			Radio/TV Stations<br />
			Political Offices
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore.</strong></p>

<table width="100%" cellpadding="10" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">FG Career Possibilities</span><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">
						<span
class="header2">Community Service</span><br />
						<em>Inspector
							<ul>

	<li>Building</li>

	<li>Public Works</li>
							</ul>
						Land
Surveyor<br />
						Environmental Grass
Roots Coordinator<br />
						Police
Officer<br />
						Immigration
Inspector<br />

	Firefighter<br />
						Recreation
Worker<br />
						Bus
Driver<br />
						Subway Operator</em>
					</td>
					<td width="33%">
						<span
class="header2">Technical Service</span><br />
						<em>Industrial Labor
Relations Specialist<br />
						Engineer
							<ul>

	<li>Civil</li>

	<li>Aircraft</li>

	<li>Structural</li>
							</ul>
						Hazardous Waste
Management<br />
						Plant Safety
Specialist<br />
						Equipment
Specialist<br />
						Tour Boat
Captain<br />
						Broadcast
Technician<br />
						Waste Management
Technician</em>
					</td>
					<td width="33%">
						<span
class="header2">Nature/Wildlife Service</span><br />

	<em>Environmentalist<br />
						Environmental
Protection Specialist<br />
						Historic
Preservationist<br />
						Park
Ranger<br />
						Recreation
Administrator<br />
						Nature
Interpreter<br />
						Zoo
Keeper<br />
						Recreations Site
Developer<br />
						Ranger Aide</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">COMMUNITY SERVICE</span>
<p>The occupations in this field are important. They provide
services to the community.  They often use technology to provide
these services. If you want to help your community and you like
technology, these may be good occupations for you.</p>

<hr size="1" />

	<span class="header2">Construction and Building
Inspector</span><br />
	<img class="job_pic" src="/images/icons/FG/43241.jpg"
width="100" height="100" border="0" alt="Building Inspector" />
	<span class="header3">Job Description</span>
	<blockquote>Building inspectors make sure that buildings are
safe.  They work on-site looking to see that builders follow safety
codes set by the government. As a building inspector, you would make
sure the building is built to stay strong. You might check, for
example, that the roof could not collapse under snow. Or, you might
make sure that there is an easy way to leave the building in case of
a fire.  You would check the building for flaws and insist they be
fixed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>More often employers look for persons who have
experience in construction and who have studied engineering or architecture. A degree from a community or junior college with courses in building inspection,
home inspection, construction technology, drafting, and mathematics is also desirable.
Many community colleges offer certification in building inspection 
technology. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of building inspectors
was $60,710 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Land Surveyor</span><br />
	<img class="job_pic" src="/images/icons/FG/43169.jpg"
width="100" height="100" border="0" alt="Land Surveyor" />
	<span class="header3">Job Description</span>
	<blockquote>Surveyors establish official land, airspace, and
water boundaries. They write descriptions of land for deeds, leases,
and other legal documents; define airspace for airports; and take
measurements of construction and mineral sites. Surveyors provide
data about the shape, contour, location, elevation, or dimension of
land or land features.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most surveyors need a bachelor's degree. A
number of universities offer bachelor's degree programs in
surveying and many community colleges, technical institutes, and
vocational schools offer one, two, and three-year programs in
surveying or surveying technology. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of land surveyors was
$63,420 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Firefighter</span><br />
	<img class="job_pic" src="/images/icons/FG/1392.jpg"
width="100" height="100" border="0" alt="Firefighter" />
	<span class="header3">Job Description</span>
	<blockquote>Firefighters control and put out fires that
threaten lives or property.  As a firefighter, you would have to act
quickly and responsibly in the middle of a fire or other emergency.
You would also learn CPR and first aid so that you could help
injured people. Fire fighting is dangerous and
unpredictable.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most fire fighters have a high school diploma;
however, the completion of community college courses, or in some
cases an associate degree in fire science, may improve an
applicant's chances for a job. Firefighters are usually trained at a fire academy and must pass physical and written tests. They must also earn emergency medical technician (EMT) certification. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of firefighters was
$50,850 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY SERVICE</span>
<p>The occupations in this field combine an interest in technology
and industry.</p>

<hr size="1" />

	<span class="header2">Human Resources Manager
</span><br />
	<img class="job_pic" src="/images/icons/FG/43222.jpg"
width="100" height="100" border="0" alt="Industrial Labor Relations
Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>In an effort to enhance morale and productivity,
limit job turnover, and help organizations increase performance and
improve business results, human resources managers help their firms
effectively use employee skills, provide training and development
opportunities to improve those skills, and increase employees'
satisfaction with their jobs and working conditions. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Many colleges and universities have programs
leading to a bachelor's degree in personnel, human resources, or labor
relations. Some offer degree programs in human resources
administration or human resources management, training and
development, or compensation and benefits.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of human resources
managers was $116,720 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Civil Engineer</span><br />
	<img class="job_pic" src="/images/icons/FG/43243.jpg"
width="100" height="100" border="0" alt="Civil Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>The word "civil" describes anything that has to
do with a city. A civil engineer plans and builds structures that
make our lives easier. As a civil engineer, you would plan and
oversee the building of roads, bridges, and airports. You would also
make sure that these structures were safe to use.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree in engineering is needed for
almost all entry-level engineering jobs. A civil engineer must get a
license from the state to offer services directly to the public. A
license requires four years of relevant work experience and passing
an exam. Beginning engineers often work under an experienced
engineer to get their required work experience. A master's degree may 
be needed to be a candidate for promotions. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of civil engineers was
$87,060 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Fitness Worker</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Fitness workers lead, instruct, and motivate
individuals or groups in exercise activities including
cardiovascular exercise, strength training, and stretching. They
work in health clubs, country clubs, hospitals, universities, yoga
and Pilates studios, resorts, and clients' homes.</blockquote>
	<span class="header3">Education</span>
	<blockquote>An increasing number of employers require
fitness workers to have a bachelor's degree in a field related to
health or fitness such as exercise science or physical education.
Becoming certified by one of the top certification organizations is
increasingly important, especially for personal trainers. One way to
ensure that a certifying organization is reputable is to see that it
is accredited by the National Commission for Certifying Agencies.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of fitness workers was
$40,390 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Computer Support
Specialist</span><br />
		<span class="header3">Job Description</span>
	<blockquote>Computer support specialists provide technical
assistance, support, and advice to customers and other users. This
occupational group includes technical support specialists and 
help-desk technicians. These troubleshooters interpret problems and
provide technical support for hardware, software, and systems. They
answer telephone calls, analyze problems by using automated
diagnostic programs, and resolve recurring
difficulties.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Training requirements for computer support
specialist positions vary, but many employers prefer to hire
applicants with some formal college education. A bachelor's degree
in computer science or information systems is a prerequisite for
some jobs; other jobs, however, may require only a computer-related
associate degree. And for some jobs, relevant computer experience
and certifications may substitute for formal education. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of computer support
specialists was $54,760 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">NATURE/WILDLIFE SERVICES</span>
<p>If you want to work outdoors, enjoy working with others, 
and want to serve the public, these
occupations may be for you.</p>

<hr size="1" />

	<span
class="header2">Urban and Regional Planner</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Urban and regional planners develop long- and
short-term plans for the use of land and the growth and
revitalization of urban, suburban, and rural communities and the
region in which they are located. They help local officials
alleviate social, economic, and environmental problems by
recommending locations for roads, schools, and other infrastructure
and suggesting zoning regulations for private property.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Job prospects will be best for those with a
master's degree and strong computer skills; bachelor's degree
holders may find positions, but advancement opportunities are
limited.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of urban planners was
$74,350 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Environmental Scientist
</span><br />
	<img class="job_pic" src="/images/icons/FG/1285.jpg"
width="100" height="100" border="0" alt="Environmental Scientist" />
	<span class="header3">Job Description</span>
	<blockquote>Environmental scientists conduct research to
identify and eliminate hazards that affect people, wildlife, and
their environments. These workers analyze measurements or
observations of air, food, water, and soil to determine the way to
clean and preserve the environment.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree in an earth science is
adequate for a few entry-level positions, but environmental
scientists increasingly need a master's degree in environmental
science, hydrology, or a related natural science. A master's degree
also is the minimum educational requirement for most entry-level
applied research positions in private industry and in state and federal
agencies. A doctoral degree
is generally necessary for college-level teaching and research. 
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of environmental
scientists was $71,360 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 22, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 22, 2020). </blockquote>

</div>