<span class="header1">Technology paired with Science/Mathematics (FH)
</span>

<p>If your scored high in the "F" and "H" categories, you are
important to the future. People like you have discovered many things
about the world. Your curiosity about how machines and tools work
will be important to the work force. You are an excellent thinker.
You are also probably a hands-on kind of person. You are creative
and have technical skills as well. There will be many opportunities
for you.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree.  It is helpful to have a master's degree or Ph.D. to work in
some of these occupations.</p>
<p><strong>Courses you might want to take in high school and beyond
(in addition to English & Math):</strong><br />
In high school you should take courses that emphasize math and
science. Any courses that provide opportunities to use your mental
strength will be of great interest to you.  They will also help
prepare you for career opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting<br />
			Biology<br />
			Calculus
		</td>
		<td>
			Economics<br />
			Marketing<br />
			Public Relations
		</td>
		<td>
			Physics<br />
			Computer Sciences<br />
			Chemistry
		</td>
		<td>
			Advertising<br />
			Computer Programming<br />
			Sociology
		</td>
		<td>
			Business Math<br />
			Communications<br />
			Psychology
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations
you may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. You will enjoy any club or activity where you can use
your thinking skills and technology.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Chess Club<br />
			Tutoring
		</td>
		<td>
			Newspaper/Yearbook<br />
			Computer Club<br />
		</td>
		<td>
			Environmental Activities<br />
			Audio/Visual Services
		</td>
		<td>
			Math/Science Clubs<br />
			Library Assistant
		</td>
		<td>
			Hospital Volunteer<br />
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting Firms<br />
			Architect Firms<br />
			Computer Services<br />
		</td>
		<td>
			Electronic Stores<br />
			Medical Offices<br />
			Printing Companies<br />
		</td>
		<td>
			Appliance Repair<br />
			Engineering Firms<br />
			Newspaper Offices<br />
		</td>
		<td>
			Computer Services<br />
			Data Entry<br />
			Libraries<br />
		</td>
		<td>
			Photographic Labs<br />
			Radio/TV Stations<br />
			Veterinary Offices
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">FH Career
Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">

						<span
class="header2">Medical Sciences</span><br />


						<em>Physicist
							<ul>

	<li>Biophysicist</li>

	<li>Health</li>

	<li>Medical</li>

	<li>Solid-state</li>

	<li>Nuclear</li>
							</ul>
						Physical
Therapist<br />
						Prosthetic
Engineer<br />
						Prosthetic
Designer<br />
						Physical Therapist
Assistant<br />
						Technician
							<ul>

	<li>Nuclear Medicine</li>

	<li>Surgical</li>

	<li>Radiological</li>

	<li>Clinical Laboratory</li>

	<li>Cardiovascular</li>
							</ul></em>
					</td>
					<td width="33%">
						<span
class="header2">Environmental Sciences</span><br />
						<em>City
Planner<br />
						Marine
Biologist<br />

	Geographer<br />
						Industrial
Hygienist<br />
						Engineer
							<ul>

	<li>Electrical</li>

	<li>Industrial</li>

	<li>Mechanical</li>
							</ul>

	Environmentalist<br />

	Meteorologist<br />

	Climatologist<br />
						Air Pollution
Control Technician<br />
						Land
Surveyor<br />
						Energy Management
Technician</em>
					</td>
					<td width="33%">
						<span
class="header2">Engineering Sciences</span><br />
						<em>Engineer
							<ul>

	<li>Aeronautical</li>

	<li>Electrical</li>

	<li>Mechanical</li>
							</ul>

	Cartographer<br />
						Aircraft
Pilot<br />
						Aviation Safety
Inspector<br />
						Inventor<br />

	Researcher<br />
						Boat
Captain<br />
						Technician
							<ul>

	<li>Mechanical Engineering</li>

	<li>Electrical Repair</li>

	<li>Cable Equipment</li>
							</ul>
						Craftsman
							<ul>

	<li>Stone Cutter</li>

	<li>Brick Mason</li>
							</ul></em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">ENVIRONMENTAL SCIENCES</span>
<p>The occupations in this field are very important to the earth's
future. If you chose one of these occupations, you would research
and explore the earth's limited resources.</p>

<hr size="1" />

	<span class="header2">Marine Biologist</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/43210.jpg"
width="100" height="100" border="0" alt="Marine Biologist" />
	<span class="header3">Job Description</span>
	<blockquote>Marine biologists study salt water organisms
while limnologists study fresh water organisms. Much of the work of
marine biology centers on molecular biology, the study of the
biochemical processes that take place inside living
cells.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most biological scientists need a Ph.D. degree
in biology or one of its subfields to work in research or
development positions. A period of postdoctoral work in the
laboratory of a senior researcher has become common for biological
scientists who intend to conduct research or teach at the university
level.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of marine biologists was
$79,580 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Environmental
Scientist</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/43153.jpg"
width="100" height="100" border="0" alt="Industrial Hygienist" />
	<span class="header3">Job Description</span>
	<blockquote>Environmental scientists find and fix pollution
and other environmental problems. They figure out what is in the
air, water, and soil to make sure that the environment is safe. They
also give advice on how to clean the environment. For example, they
might design a safe way to get rid of trash. </blockquote>
	<span class="header3">Education</span>
	<blockquote>To be an environmental scientist, you would need
at least a bachelor's degree. Most need an advanced degree; either a
master's degree, which takes one or two more years after finishing
college, or a doctoral degree, which takes longer.

 </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of environmental
scientists was $71,360 in May 2019. </blockquote>

</blockquote>

<hr size="1" />

	<span class="header2">Occupational Health and Safety
Specialist/Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/43163.jpg"
width="100" height="100" border="0" alt="Energy Management
Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Occupational health and safety specialists
analyze work environments and design programs to control, eliminate,
and prevent disease or injury. They look for chemical, physical,
radiological, and biological hazards and they work to make more
equipment ergonomic-designed to promote proper body positioning,
increase worker comfort, and decrease fatigue.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some employers require occupational health and
safety specialists to have a bachelor's degree in occupational
health, safety, or a related field such as engineering, biology, or
chemistry. For some positions, a master's degree in industrial
hygiene or a related subject is required. There are also associate
degrees and one-year certificate programs which are primarily
intended for technicians. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of occupational health and
safety specialists was $74,100 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">ENGINEERING TECHNOLOGIES</span>
<p>To work in this field, you need to be a logical thinker. You also
need to have technical skills.</p>

<hr size="1" />

	<span class="header2">Airline Pilot</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/43047.jpg"
width="100" height="100" border="0" alt="Aircraft Pilot">
	<span class="header3">Job Description</span>
	<blockquote>An airline pilot flies an airplane or
helicopter.  In this job, you would  be responsible for the safety
of the aircraft as well as any passengers on board.  You must have
perfect vision, hearing, and coordination to be a pilot.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Commercial pilots need a high school diploma and a 
pilot's license. Most have a bachelor's degree. Airline pilots usually start off as commercial pilots, and many start their career in the military.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of airline pilots was
$147,220 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Engineer</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/C0777_50.jpg"
width="100" height="100" border="0" alt="Mechanical Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>Engineers apply the principles of science and
mathematics to develop economical solutions to technical problems.
Their work is the link between scientific discoveries and the
commercial applications that meet societal and consumer needs.
</blockquote>
	<span class="header3">Education</span>
	<blockquote>Engineers typically enter the occupation with a
bachelor's degree in an engineering specialty, but some basic
research positions may require a graduate degree. Engineers offering
their services directly to the public must be licensed. Continuing
education to keep current with rapidly changing technology is
important for engineers.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of engineers was $81,440 in 
May 2019.</blockquote>

<hr size="1" />

<span class="header1">MEDICAL SCIENCE</span>
<p>These jobs are concerned with the practice of medicine.  They
also involve the technology that doctors and scientists use.</p>

<hr size="1" />

	<span class="header2">Physical Therapist</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Physical therapists provide services that help
restore function, improve mobility, relieve pain, and prevent or
limit permanent physical disabilities of patients suffering from
injuries or disease. They restore, maintain, and promote overall
fitness and health. Their patients include accident victims and
individuals with disabling conditions such as low-back pain,
arthritis, heart disease, fractures, head injuries, and cerebral
palsy.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Individuals pursuing a career as a physical
therapist need a Doctor of Physical Therapy (DPT) degree and a state license. To earn the license, you need passing scores on
national and state examinations.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of physical therapists
was $89,440 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Nuclear Medicine
Technologist</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/C0571_07.jpg"
width="100" height="100" border="0" alt="Nuclear Medicine
Technologist" />
	<span class="header3">Job Description</span>
	<blockquote>Nuclear medicine technologists operate cameras
that detect and map the radioactive drug in a patient's body to
create diagnostic images.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Nuclear medicine technology programs range in
length from one to four years and lead to a certificate, an
associate degree, or a bachelor's degree. Many employers and an
increasing number of states require certification or licensure.
Aspiring nuclear medicine technologists should check the
requirements of the state in which they plan to work. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of nuclear medicine
technnologists was $77,950 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Clinical Laboratory Technologist or
Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/43149.jpg"
width="100" height="100" border="0" alt="Clinical Laboratory
Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Clinical laboratory testing plays a crucial role
in the detection, diagnosis, and treatment of disease. Clinical
laboratory technologists and technicians perform most of these
tests.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The usual requirement for an entry-level
position as a clinical laboratory technologist is a bachelor's
degree with a major in medical technology or one of the life
sciences; however, it is possible to qualify for some jobs with a
combination of education and on-the-job and specialized training.
Medical and clinical laboratory technicians generally have either an
associate degree from a community or junior college or a certificate
from a hospital, a vocational or technical school, or the Armed
Forces. A few technicians learn their skills on the job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of clinical laboratory
technologists and technicians was $53,120 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 22, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 22, 2020). </blockquote>

</div>