<p class="header1">Technology paired with Social/Helping (FI)
</p>

<p>Your high scores in "F" and "I" show that you have
characteristics that are useful to people.  You will be highly
valued in the work force.  In addition, you  have the potential to
make a real difference in the world.  You have an interest in
technology and in other people.  Your strengths will be
useful in many different occupations.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree.  It is helpful to have a master's degree or Ph.D. if you
hope to work in some of these occupations.</p>
<p><strong>Courses you might want to take in high school and beyond
(in addition to English & Math):</strong><br />
In high school you should take courses that will help you
understand people. Any courses in social studies and technology will
be of interest to you.  They will also help prepare you for possible
career opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Health/Nutrition<br />
			Psychology<br />
			Sociology
		</td>
		<td>
			Home Economics<br />
			Public Relations<br />
			Communications
		</td>
		<td>
			Graphic Arts<br />
			Business Education<br />
			Religion
		</td>
		<td>
			Business Law<br />
			Education Technology<br />
			Environmental Science
		</td>
		<td>
			History<br />
			Life Science<br />
			Education
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations you
may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. You will enjoy any club or activity where you can share
your love for nature and use your people skills.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Church Activities<br />
			Camp Counselor<br />
			Hospital Volunteer
		</td>
		<td>
			Peer Counselor<br />
			Tutoring<br />
			Chess Club<br />
		</td>
		<td>
			Childcare/Eldercare<br />
			Yearbook/Newspaper<br />
			Audio/Visual Services
		</td>
		<td>
			Computer Club<br />
			Music Lessons<br />
			Martial Arts
		</td>
		<td>
			Teaching Assistant<br />
			Library Assistant<br />
			Math/Science Clubs
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Company Offices<br />
			Equipment Repair<br />
			Road Building
		</td>
		<td>
			Life Guarding<br />
			Restaurant<br />
			Repair Services
		</td>
		<td>
			Construction Companies<br />
			Graphic Design Firms<br />
			Recreation Department<br />
		</td>
		<td>
			Church Programs<br />
			Day Care Centers<br />
			Libraries
		</td>
		<td>
			Photography Studios<br />
			Printing Companies<br />
			Newspaper Offices
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="10" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">FI Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="33%">

						<span
class="header2">Education & Instruction</span><br />
						<em>College
Professor<br />
						Teacher
							<ul>

	<li>Continuing Education</li>

	<li>Environmental Science</li>

	<li>Computer Science</li>

	<li>Shop</li>

	<li>Physical Education</li>
							</ul>
						Sports & Fitness
Trainer<br />
						Coach<br />
						Instructor
							<ul>

	<li>Aerobics Exercise</li>

	<li>Martial Arts</li>

	<li>Police Academy</li>

	<li>Survival Training</li>

	<li>Trade School</li>
							</ul></em>
					</td>
					<td width="33%">
						<span
class="header2">Social Helping</span><br />
						<em>Public Health
Administrator<br />
						Environmental
Lawyer<br />
						Social
Worker<br />
						Nurse<br />
						Recreational
Therapist<br />
						Dental
Hygienist<br />
						Paramedic<br />
						Police
Officer<br />
						Military
Police<br />
						Flight
Attendant<br />
						Barber</em>
					</td>
					<td width="33%">
						<span
class="header2">Technology Helping</span><br />

	<em>Veterinarian<br />
						Medical Equipment
Designer<br />
						Park
Ranger<br />

	Firefighter<br />
						Military Teletype
Operator<br />
						Computer
Trainer<br />
						Craftsperson
							<ul>

	<li>Plumber</li>

	<li>Carpenter</li>

	<li>Heating</li>

	<li>Air Conditioning</li>
							</ul>
						Appliance Repair
Technician<br />
						Electronics
Technician</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">EDUCATION & INSTRUCTION</span>
<p>Teaching is an excellent way to share the advances made in
technology and to help other people.</p>

<hr size="1" />

	<span class="header2">Health Educator
</span><br />
	<img class="job_pic" src="/images/icons/FI/1076.jpg"
width="100" height="100" border="0" alt="Physical Education
Teacher" />
	<span class="header3">Job Description</span>
	<blockquote>Health educators work to encourage healthy
lifestyles and wellness through educating individuals and
communities about behaviors that promote healthy living and prevent
diseases and other health problems. Health educators can work in
schools, colleges, medical care facilities, state and local
departments of health, non-profits, and private
industry.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is generally required for
entry level health educator positions, but some employers prefer a
bachelor's degree and some related experience gained through an
internship or volunteer work. A master's degree may be required for
some positions and is usually required for advancement. In addition,
some employers may require candidates to be Certified Health
Education Specialists.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of health educators was
$46,910 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Fitness Worker</span><br />
	<img class="job_pic" src="/images/icons/FI/C1207_25.jpg"
width="100" height="100" border="0" alt="Aerobic Exercise
Instructor" />
	<span class="header3">Job Description</span>
	<blockquote>Fitness workers lead, instruct, and motivate
individuals or groups in exercise activities including
cardiovascular exercise, strength training, and stretching. They
work in health clubs, country clubs, hospitals, universities, yoga
and Pilates studios, resorts, and clients' homes. </blockquote>
	<span class="header3">Education</span>
	<blockquote>For most fitness workers, certification is
critical. Personal trainers usually must have certification to begin
working with clients or with members of a fitness facility. Group
fitness instructors may begin without a certification, but they are
often encouraged or required by their employers to become certified.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of fitness workers was
$40,390 in May 2019. </blockquote>

<hr size="1" />


<span class="header2">Dietitian/Nutritionist</span><br />
	<img class="job_pic" src="/images/icons/FI/18272.jpg"
width="100" height="100" border="0" alt="Recreation Therapist" />
		<span class="header3">Job Description</span>
	<blockquote>Dietitians and nutritionists plan food and
nutrition programs, supervise meal preparation, and oversee the
serving of meals. They prevent and treat illnesses by promoting
healthy eating habits and recommending dietary modifications. Most
jobs are in hospitals, nursing care facilities, outpatient care
centers, and offices of physicians or other health practitioners.
</blockquote>
	<span class="header3">Education</span>
	<blockquote>Dietitians and nutritionists need at least a
bachelor's degree. Licensure, certification, or registration
requirements vary by state.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of
dietitian/nutritionists was $61,270 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">SOCIAL HELPING</span>
<p>The occupations in this field require people who are active,
helpful, and outgoing.</p>

<hr size="1" />

	<span class="header2">Medical and Health Services
Manager</span><br />
	<img class="job_pic" src="/images/icons/FI/C506006.jpg"
width="100" height="100" border="0" alt="Public Health
Administrator" />
	<span class="header3">Job Description</span>
	<blockquote>Medical and health services managers, also
referred to as health care executives or health care administrators,
plan, direct, coordinate, and supervise the delivery of health care.
They work to improve efficiency in health care facilities and the
quality of the care provided. </blockquote>
	<span class="header3">Education</span>
	<blockquote>A master's degree in health services
administration, long-term care administration, health sciences,
public health, public administration, or business administration is
the standard credential for most generalist positions in this field.
However, a bachelor's degree is adequate for some entry-level
positions in smaller facilities, at the departmental level within
health care organizations, and in health information management.
Physicians' offices and some other facilities hire those with on-the-
job experience instead of formal education.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of medical and health
services managers was $100,980 in May 2019. </blockquote>

<hr size="1" />

<span class="header2">Teacher</span><br />
		<span class="header3">Job Description</span>
	<blockquote>Teachers play an important role in fostering the
intellectual and social development of children during their
formative years. The education that teachers impart plays a key role
in determining the future prospects of their students. Whether in
preschools, high schools, or in private or public schools, teachers
provide the tools and the environment for their students to develop
into responsible adults.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The traditional route to becoming a public
school teacher involves completing a bachelor's degree from a
teacher education program and then obtaining a license. However,
most states now offer alternative routes to licensure for those who
have a college degree in other fields. Private school teachers may
not have to be licensed but still need a bachelor's degree. A
bachelor's degree may not be needed by preschool teachers and
vocational education teachers; they need experience in their field
rather than a specific degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of teachers (kindergarten 
through high school) was $60,247 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Barber or
Cosmetologist</span><br />
	<img class="job_pic" src="/images/icons/FI/43008.jpg"
width="100" height="100" border="0" alt="Barber or Cosmetologist" />
	<span class="header3">Job Description</span>
	<blockquote>If you were a barber or cosmetologist, you would
cut, shampoo, and color hair.  You would also provide other grooming
services.  This is a social job which means that you would be
working with people. To enjoy this job, you must have good people
skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Barbers and cosmetologists must have a state
license.  They must pass a written test. They must also demonstrate
that they can cut hair.  Vocational tech schools and cosmetology
colleges offer programs for those who want to enter this
occupation.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of barbers or
cosmetologists was $26,270 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY HELPING</span>
<p>The occupations in this field allow you to use technology to help
animals and people.</p>

<hr size="1" />

	<span class="header2">Veterinarian</span><br />
	<img class="job_pic" src="/images/icons/FI/43132.jpg"
width="100" height="100" border="0" alt="Veterinarian" />
	<span class="header3">Job Description</span>
	<blockquote>Veterinarians care for sick and injured
animals.  If you love animals and are good at science, you might
become a veterinarian. In this job, you would diagnose what was
wrong with animals.  You would vaccinate them against disease.  You
would tell people how to care for their animals.  If you like
looking for new ways to treat animals and control diseases, you
could do research in this area.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most veterinary colleges require students to
first obtain a bachelor's degree. A Doctor of Veterinary Medicine
degree takes about four years to complete. Veterinarians must be
licensed by their state. There is keen competition for admission to
veterinary school. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of veterinarians was
$95,460 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Dental Assistant</span><br />
		<span class="header3">Job Description</span>
	<blockquote>Dental assistants sterilize and disinfect
instruments and equipment, prepare and lay out the instruments and
materials required to treat each patient, and obtain patients'
dental records. Assistants make patients as comfortable as possible
in the dental chair and prepare them for treatment. During dental
procedures, assistants work alongside the dentist to provide
assistance. They hand instruments and materials to dentists and keep
patients' mouths dry and clear by using suction or other devices.
They also instruct patients on postoperative and general oral health
care.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Many assistants learn their skills on-the-job,
although an increasing number are trained in dental-assisting
programs offered by community and junior colleges, trade schools,
technical institutes, or the Armed Forces.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of dental assistants was
$40,080 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Registered Nurse</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Registered nurses (RNs), regardless of specialty
or work setting, treat patients, educate patients and the public
about various medical conditions, and provide advice and emotional
support to patients' family members. RNs record patients' medical
histories and symptoms, help perform diagnostic tests and analyze
results, operate medical machinery, administer treatment and
medications, and help with patient follow-up and
rehabilitation.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The three major educational paths to registered
nursing are a bachelor's degree, an associate degree, and a diploma
from an approved nursing program. Nurses most commonly enter the
occupation by completing an associate degree or bachelor's degree
program. Individuals then must complete a national licensing
examination in order to obtain a nursing license.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of registered nurses was
$73,300 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 22, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 22, 2020). </blockquote>

</div>