<p class="header1">Public Service paired with Science/Mathematics
(GH)</p>

<p>If your scored high in the "G" and "H" categories, you understand
that there are always ways to improve a situation. You have the
ability to investigate, explore, and apply information. This will
make you a valuable employee.  People like you have discovered
important information that has made the world a better place.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree.  It is helpful to have a master's degree or Ph.D. if you
hope to work in some of these occupations.</p>
<p><strong>Courses you may want to take in high school and beyond
(in addition to English & Math):</strong><br />
In high school you should take courses that emphasize math and
science. Any courses that will help you understand people and
society will be of interest to you.  They will also prepare you for
possible career opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Communications<br />
			Government/Civics<br />
			Physical Education<br />
			Public Relations
		</td>
		<td>
			Sociology<br />
			Psychology<br />
			Trigonometry<br />
			Accounting
		</td>
		<td>
			Health/Nutrition<br />
			Physics/Chemistry<br />
			Computer Info. Systems<br />
			Technology Education
		</td>
		<td>
			Calculus<br />
			Biology<br />
			Geometry<br />
			Economics
		</td>
		<td>
			Business Education<br />
			World Languages<br />
			Criminal Justice<br />
			Political Science
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations you
may find interesting:</strong><br />
If you have time for afterschool activities or part-time jobs, make
them count. You will enjoy any club or activity where you can share
your love for helping your community and use your thinking skills.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Math/Science Clubs<br />
			Computer Club
		</td>
		<td>
			Chess Club<br />
			Tutoring
		</td>
		<td>
			Environmental Activities<br />
			Hospital Volunteer
		</td>
		<td>
			Peer Counselor<br />
			Church Activities
		</td>
		<td>
			Safety Patrol
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Accounting Firms<br />
			Appliance Repair<br />
			Medical Offices<br />
			Political Offices
		</td>
		<td>
			Data Entry<br />
			Construction<br />
			News Media<br />
			Legal Offices
		</td>
		<td>
			Athletic Programs<br />
			Sports Companies<br />
			Electronic Stores<br />
			Veterinary Offices
		</td>
		<td>
			Printing Companies<br />
			Computer Services<br />
			Libraries<br />
			Computer Sales
		</td>
		<td>
			Archeological Projects<br />
			Courthouse Activities<br />
			Landscaping Services
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="10" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">GH Career Possibilities</span>
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="25%">
						<span
class="header2">Public Service</span><br />
						<em>Military Medical
Officer<br />
						Political
Scientist<br />
						Fire
Chief<br />
						Health
Inspector<br />
						Lobbyist<br />
						Peace Corp
Worker<br />
						Foreign Service
Officer<br />
						Police
Officer<br />

	Investigator<br />
						Security Guard</em>
					</td>
					<td width="25%">
						<span
class="header2">Social/Mental</span><br />
						<em>Public Health
							<ul>

	<li>Physician</li>

	<li>Dental</li>
							</ul>

	Epidemiologist<br />

	Psychologist<br />
						Health Services
Administrator<br />
						Social
Worker<br />
						Public Health Field
Worker</em>
					</td>
					<td width="25%">
						<span
class="header2">Environmental</span><br />
						<em>Environmental
Lawyer<br />
						Chemical
Engineer<br />
						Ecologist<br />
						Environmental Health
Inspector<br />

	Meteorologist<br />
						Meteorologist
Technician<br />
						Energy Management
Technician<br />
						Waste Management
Technician</em>
					</td>
					<td width="25%">
						<span
class="header2">Science/Medical</span><br />
						<em>Biological
Scientist<br />

	Optometrist<br />
						Public Health
Nurse<br />

	Chiropractor<br />
						Dietitian<br />
						Dental
Hygienist<br />
						Paramedic<br />
						Nurse's
Aide<br />
						Ophthalmic Lab
Technician</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">PUBLIC SERVICE</span>
<p>The occupations in this field need people who are active and
enthusiastic and who do not mind hard work.</p>

<hr size="1" />

<span class="header2">Occupational Health and Safety
Specialist or Technician</span><br />
	<img class="job_pic" src="/images/icons/GI/md000590.jpg"
width="100" height="100" border="0" alt="Public Health Care
Investigator" />
	<span class="header3">Job Description</span>
	<blockquote>Occupational health and safety specialists
analyze work environments and design programs to control, eliminate,
and prevent disease or injury. They look for chemical, physical,
radiological, and biological hazards and work to make more equipment
ergonomic-designed to promote proper body positioning, increase
worker comfort, and decrease fatigue. Most occupational health and
safety specialists and technicians work in large private firms or
for federal, state, and local governments.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some employers require occupational health and
safety specialists to have a bachelor's degree in occupational
health, safety, or a related field such as engineering, biology, or
chemistry. For some positions, a master's degree in industrial
hygiene or a related subject is required. There also are associate
degree and one-year certificate programs which primarily are
intended for technicians. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of occupational health and safety specialists
was $70,480 in May 2019. </blockquote>


<hr size="1" />

<span class="header2">Police Officer</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Uniformed police officers have general law
enforcement duties, including maintaining regular patrols and
responding to calls for service. They may direct traffic at the
scene of an accident, investigate a burglary, or give first aid to
an accident victim.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Law enforcement agencies encourage applicants to
take courses or training related to law enforcement subjects after
high school. Many entry-level applicants for police jobs have
completed some formal postsecondary education and a significant
number are college graduates. Police officers are also typically trained
at a police academy. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of police officers was
$65,170 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Security Guard</span><br />
	<img class="job_pic" src="/images/icons/EG/43109.jpg"
width="100" height="100" border="0" alt="Security Guard" />
	<span class="header3">Job Description</span>
	<blockquote>As a security guard, you would patrol a building
to protect it. You would make sure that the office property was not
stolen and that no one was trespassing. Many security guards work
at night. Others work during the day while workers are in the
building.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.
You also need a valid driver's license.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of security guards was
$29,710 in May 2019. </blockquote>


<hr size="1" />

<span class="header1">SOCIAL/MENTAL</span>
<p>The occupations in this field deal with public health.  Those who
work in these occupations work to prevent disease and to encourage
community well-being.</p>

<hr size="1" />

	<span class="header2">Dentist</span><br />
	<img class="job_pic" src="/images/icons/GH/C506031.jpg"
width="100" height="100" border="0" alt="Dentist" />
	<span class="header3">Job Description</span>
	<blockquote>Dentists diagnose and treat problems with teeth
and tissues in the mouth, along with giving advice and administering
care to help prevent future problems. They remove tooth decay, fill
cavities, examine x-rays, place protective plastic sealants on
children's teeth, straighten teeth, and repair fractured teeth. They
also perform corrective surgery on gums and supporting bones to
treat gum diseases.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most dental
students have at least a bachelor's degree before entering dental
school, although a few applicants are accepted to dental school
after two or three years of college and complete their bachelor's
degree while attending dental school. Dental school usually lasts
four academic years, ending with a doctoral degree. All 50 states and the District of Columbia require dentists to be licensed.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of dentists was $159,200
in May 2019. </blockquote>

<hr size="1" />

<span class="header2">Medical Doctor</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Physicians and surgeons diagnose illnesses and
prescribe and administer treatment for people suffering from injury
or disease. Physicians examine patients, obtain medical histories,
and order, perform, and interpret diagnostic tests. </blockquote>
	<span class="header3">Education</span>
	<blockquote>The common path to practicing as a physician
requires eight years of education beyond high school and three to
eight additional years of internship and residency.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of medical doctors was
$208,000 in May 2019. </blockquote>


<hr size="1" />

	<span class="header2">Public Health Social
Worker</span><br />
	<img class="job_pic" src="/images/icons/EG/1212.jpg"
width="100" height="100" border="0" alt="Public Health Social
Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Social work is a profession for those with a
strong desire to help improve people's lives. Social workers assist
people by helping them cope with issues in their everyday lives,
deal with their relationships, and solve personal and family
problems. Some social workers help clients who face a disability or
a life-threatening disease or a social problem such as inadequate
housing, unemployment, or substance abuse. Social workers also
assist families that have serious domestic conflicts, sometimes
involving child or spousal abuse.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is the minimum requirement
for entry into the occupation, but many positions require an
advanced degree. All states and the District of Columbia have some
licensure, certification, or registration requirement, but the
regulations vary.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of public health social
workers was $59,300 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>The occupations in this field need those who are willing to
research and explore nature.</p>

<hr size="1" />

	<span class="header2">Lawyer</span><br />
	<img class="job_pic" src="/images/icons/BH/43286.jpg"
width="100" height="100" border="0" alt="Lawyer" />
	<span class="header3">Job Description</span>
	<blockquote>Lawyers, such as those that work in environmental 
law, give legal advice and assistance to people. They represent their 
clients in court and in other legal
matters.  There are many kinds of lawyers. Some work with people
who have been arrested and represent them in court.  There are also
corporate lawyers who take care of any legal issues that are related
to running a business.  There are real estate lawyers, family
lawyers, and environmental lawyers as well. What these jobs have in
common is that the lawyer is responsible for helping his/her clients
in matters that relate to the law.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree plus three years of
law school to become a lawyer. Also a lawyer must pass an exam known
as the bar. A lawyer must be very sharp and continue to learn about
the law, because laws often change.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of lawyers was $122,960
in May 2019. </blockquote>

<hr size="1" />

		<span class="header2">Ecologist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>An ecologist is a scientist who studies the
effect that people and animals have on the earth's environment.  If
you are concerned about harm to the environment and have good
computer skills, this may be a good job for you.  As an
environmentalist, you would conduct field studies.  You would also
work in laboratories.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree to become an
ecologist.  Most employers look for a master's or doctoral degree and
experience.  To get experience, volunteer with groups who work to
protect the environment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of ecologists was $71,360
in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Meteorologist</span><br />
	<img class="job_pic" src="/images/icons/AF/1265.jpg"
width="100" height="100" border="0" alt="Meteorologist" />
	<span class="header3">Job Description</span>
	<blockquote>Meteorologists use computers, radar, and
satellites to study the atmosphere.  As a meteorologist, you would
use the data you collect to create weather reports.  These reports
tell people about current conditions.  They also forecast future
weather conditions.  This is an important job.  Weather forecasts
are used to warn  people of severe or dangerous weather.  This
information is important to everybody.  It can help to save lives.
It can also help to save property.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a degree in meteorology, or in a
related field such as physics or earth science.  If you want to
teach meteorology or conduct research, you would need a master's
degree or Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of meteorologists was
$95,380 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">SCIENCE/MEDICAL</span>
<p>There are many occupations that combine medicine and science.</p>

<hr size="1" />

	<span class="header2">Registered Nurse</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Registered nurses (RNs), regardless of specialty
or work setting, treat patients, educate patients and the public
about various medical conditions, and provide advice and emotional
support to patients' family members. RNs record patients' medical
histories and symptoms, help perform diagnostic tests and analyze
results, operate medical machinery, administer treatment and
medications, and help with patient follow-up and
rehabilitation.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The three major educational paths to registered
nursing are a bachelor's degree, an associate degree, and a diploma
from an approved nursing program. Nurses most commonly enter the
occupation by completing an associate degree or bachelor's degree
program. Individuals then must complete a national licensing
examination in order to obtain a nursing license.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of registered nurses was
$73,300 in May 2019. </blockquote>


<hr size="1" />

<span class="header2">Dietitian/Nutritionist</span><br />
	<img class="job_pic" src="/images/icons/FI/18272.jpg"
width="100" height="100" border="0" alt="Recreation Therapist" />
		<span class="header3">Job Description</span>
	<blockquote>Dietitians and nutritionists plan food and
nutrition programs, supervise meal preparation, and oversee the
serving of meals. They prevent and treat illnesses by promoting
healthy eating habits and recommending dietary modifications. Most
jobs are in hospitals, nursing care facilities, outpatient care
centers, and offices of physicians or other health practitioners.
</blockquote>
	<span class="header3">Education</span>
	<blockquote>Dietitians and nutritionists need at least a
bachelor's degree. Licensure, certification, or registration
requirements vary by state.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of
dietitians/nutritionists was $61,270 in May 2019. </blockquote>


<hr size="1" />

	<span class="header2">Paramedic / Emergency Medical
Technician</span><br />
	<span class="header3">Job Description</span>
	<blockquote>People's lives often depend on the quick
reaction and competent care of emergency medical technicians (EMTs)
and paramedics. Incidents as varied as automobile accidents, heart
attacks, slips and falls, childbirth, and gunshot wounds all require
immediate medical attention. EMTs and paramedics provide this vital
service as they care for and transport the sick or injured to a
medical facility.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A high school diploma is usually required to
enter a formal emergency medical technician training program.
Training is offered at progressive levels: EMT-Basic, EMT-
Intermediate, and EMT-Paramedic. Most commonly, the EMT-Paramedic
training is conducted in community colleges and technical schools
over one to two years and may result in an associate's degree. Such
education prepares the graduate to take the NREMT examination and
become certified as a Paramedic. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of paramedics/EMTs was
$35,400 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 23, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 23, 2020). </blockquote>

</div>