<p class="header1">Public Service paired with Social/Helping (GI)
</p>

<p>Your high scores in "G" and "I" show that you are headed for a
rewarding career.  You will be highly valued in the work force.  You
also have the potential to make a real difference in the world.  You
are a responsible, independent worker and you know how to make
things happen.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree.  It is helpful to have a master's degree or Ph.D. if you
hope to work in some of these occupations.</p>
<p><strong>Courses you might want to take in high
school.</strong><br />
In high school you should take courses that will help you
understand people. Any courses in social studies and political
science will be of interest to you.  They will also help prepare you
for possible career opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Government/Civics<br />
			World Languages<br />
			Home Economics<br />
			Nutrition/Health
		</td>
		<td>
			Religion<br />
			Psychology<br />
			Sociology<br />
			Education
		</td>
		<td>
			Computer Technology<br />
			Physical Education<br />
			Public Relations<br />
			Marketing/Advertising
		</td>
		<td>
			Communications<br />
			Business Education<br />
			Political Science<br />
			Criminal Justice
		</td>
		<td>
			Graphic Arts<br />
			Law<br />
			Life Science
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations you
may find interesting:</strong><br />
If you have time for after-school activities or part-time jobs, make
them count.  You will enjoy any club or activity where you can share
your love for helping others and use your people skills.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Youth Organizations<br />
			Peer Counselor
		</td>
		<td>
			Safety Patrol<br />
			Tutoring
		</td>
		<td>
			Chess Club<br />
			Camp Counselor
		</td>
		<td>
			Childcare/Eldercare<br />
			Church Activities
		</td>
		<td>
			Hospital Volunteer<br />
			Teaching Assistant
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may wish to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Company Offices<br />
			Church Programs<br />
			Libraries
		</td>
		<td>
			Hospice Activities<br />
			Day Care Centers<br />
			Photographic Studios
		</td>
		<td>
			Life Guarding<br />
			Printing Companies<br />
			Special Olympics
		</td>
		<td>
			Construction Companies<br />
			Hospital Volunteer<br />
			Recreation Departments
		</td>
		<td>
			Camp Programs<br />
			Preschool Programs
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="10" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">GI Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="25%">
						<span
class="header2">Education</span><br />

	<em>Teacher<br />
						Public Health
Education<br />
						Police
Academy<br />

	Instructor<br />
						School
Counselor<br />
						Training
Specialist<br />
						Library
Technician</em>
					</td>
					<td width="25%">
						<span
class="header2">Social Service</span><br />
						<em>Social Worker
							<ul>

	<li>Child Welfare</li>

	<li>Family Services</li>

	<li>Drug & Alcohol</li>

	<li>Mental Health</li>

	<li>Occupational</li>
							</ul>
						Human Services Worker
							<ul>

	<li>Social Service Assistant</li>

	<li>Case Management</li>

	<li>Community Outreach Worker</li>

	<li>Child Care Worker</li>
							</ul>
						Health Care
Worker</em>
					</td>
					<td width="25%">
						<span
class="header2">Public Service</span><br />
						<em>Lawyer
							<ul>

	<li>Public Defender</li>

	<li>Judge</li>
							</ul>
						Paralegal<br />
						Police
Officer<br />

	Firefighter<br />
						Political Campaign
Worker<br />
						Flight Attendant</em>
					</td>
					<td width="25%">
						<span
class="header2">Health Care</span><br />
						<em>Public Health
Investigator<br />
						Rehabilitation
Counselor<br />
						Paramedic<br />
						Community Health
Nurse<br />
						Medical
Assistant<br />
						Patient
Representative<br />
						Nursing
Aide<br />
						Home Health Aide</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">EDUCATION</span>
<p>Occupations in this field involve educational institutions, such
as schools or colleges.</p>

<hr size="1" />

<span class="header2">Social Studies Teacher</span><br />
		<span class="header3">Job Description</span>
	<blockquote>A teacher shares information with
others.  As a social studies teacher, you would use your knowledge
of government, history, and geography to help students better
understand the issues that affect them in the world today. You would
make lesson plans, find materials, and present lectures.</blockquote>

	<span class="header3">Education</span>
	<blockquote>The traditional route to becoming a public
school teacher involves completing a bachelor's degree from a
teacher education program and then obtaining a license. However,
most states now offer alternative routes to licensure for those who
have a college degree in other fields. Private school teachers may
not have to be licensed but still need a bachelor's degree. A
bachelor's degree may not be needed by preschool teachers and
vocational education teachers; they need experience in their field
rather than a specific degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of social studies
teachers was $60,247 in May 2019. </blockquote>

<hr size="1" />


<span class="header2">School Counselor</span><br />
		<span class="header3">Job Descriptions</span>
	<blockquote>School counselors assist students of all levels,
from elementary school to postsecondary education. They advocate for
students and work with other individuals and organizations to
promote the academic, career, personal, and social development of
children and youth. School counselors help students evaluate their
abilities, interests, talents, and personalities to develop
realistic academic and career goals.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Many states require school counselors to hold a
state school counseling certification and to have completed at least
some graduate course work; most require the completion of a master's
degree. Some states require school counselors to be licensed, which
generally requires continuing education credits.  </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of school counselors was
$57,040 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Library Technician</span><br />
	<img class="job_pic" src="/images/icons/GI/43282.jpg"
width="100" height="100" border="0" alt="Library Technician" />
	<span class="header3">Job Description</span>
	<blockquote>As a library technician, you would help a
librarian.  You would gather, organize, and maintain materials used
by library visitors. You would help visitors find information and
materials.  You would need good computer skills to do well in this
job.  You also need to enjoy helping people.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most libraries prefer to hire technicians who
have earned a certificate or associate degree, but some smaller
libraries may hire individuals with only a high school diploma.
</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of library technicians
was $30,560 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">SOCIAL SERVICE</span>
<p>The field of social service can be challenging.  It taps into a
person's resourcefulness. It also demands that he/she be very
involved with people.</p>

<hr size="1" />

<span class="header2">Public Health Social
Worker</span><br />
	<img class="job_pic" src="/images/icons/EG/1212.jpg"
width="100" height="100" border="0" alt="Public Health Social
Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Social work is a profession for those with a
strong desire to help improve people's lives. Social workers assist
people by helping them cope with issues in their everyday lives,
deal with their relationships, and solve personal and family
problems. Some social workers help clients who face a disability or
a life-threatening disease or a social problem such as inadequate
housing, unemployment, or substance abuse. Social workers also
assist families that have serious domestic conflicts, sometimes
involving child or spousal abuse.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is the minimum requirement
for entry into the occupation, but many positions require an
advanced degree. All states and the District of Columbia have some
licensure, certification, or registration requirement, but the
regulations vary.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of public health social
workers was $59,300 in May 2019. </blockquote>

<hr size="1" />

<span class="header2">Clergy (Pastor, Priest, Rabbi)
</span><br />
	<img class="job_pic" src="/images/icons/EI/43007.jpg"
width="100" height="100" border="0" alt="Chaplain" />
	<span class="header3">Job Description</span>
	<blockquote>Clergies lead religious worship and perform other
spiritual functions associated with beliefs and practices of
religious faith or denomination. They also provide spiritual and moral
guidance and assistance to members.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a master's degree in theology to become
a clergy. In addition, you would be "ordained" by a religious
denomination.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of clergies was $55,190 
in May 2019.</blockquote>


<hr size="1" />

<span class="header2">Human Resources Manager
</span><br />
	<img class="job_pic" src="/images/icons/FG/43222.jpg"
width="100" height="100" border="0" alt="Industrial Labor Relations
Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>In an effort to enhance morale and productivity,
limit job turnover, and help organizations increase performance and
improve business results, human resources managers help their firms
effectively use employee skills, provide training and development
opportunities to improve those skills, and increase employees'
satisfaction with their jobs and working conditions. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Many colleges and universities have programs
leading to a degree in personnel, human resources, or labor
relations. Some offer degree programs in human resources
administration or human resources management, training and
development, or compensation and benefits.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of human resources
managers was $116,720 in May 2019. </blockquote>

<hr size="1" />


<span class="header1">PUBLIC SERVICE</span>
<p>The occupations in this field combine public service with law.</p>

<hr size="1" />

<span class="header2">Paralegal</span><br />
	<img class="job_pic" src="/images/icons/BD/43286.jpg"
width="100" height="100" border="0" alt="Paralegal" />
	<span class="header3">Job Description</span>
	<blockquote>You may be interested in law or the court
system, but not want to be a lawyer. If so, you might become a
paralegal.  A paralegal works closely with a lawyer.  As a
paralegal, you would do a lot of research to find background
information for the lawyer. You would also help the lawyer prepare
for court.</blockquote>
	<span class="header3">Education</span>
	<blockquote>In the past, paralegals usually received
training in a paralegal program.  More and more, lawyers want to
hire paralegals who have a bachelor's degree in humanities or the
social sciences.  You will find a job more easily if you learn as
much about the law as you can. It is also helpful to work in a law
office, if possible.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of paralegals was $51,740
in May 2019. </blockquote>

<hr size="1" />


<span class="header2">Police Officer</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Uniformed police officers have general law
enforcement duties, including maintaining regular patrols and
responding to calls for service. They may direct traffic at the
scene of an accident, investigate a burglary, or give first aid to
an accident victim.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Many entry-level applicants for police jobs have
completed some formal postsecondary education in law enforcement, and a significant
number are college graduates. Many junior colleges, colleges, and
universities offer programs in law enforcement or administration of
justice. Police officers also receive training from a police training 
academy. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of police officers was
$65,170 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Flight Attendant</span><br />
	<img class="job_pic" src="/images/icons/BG/1216.jpg"
width="100" height="100" border="0" alt="Flight Attendant" />
	<span class="header3">Job Description</span>
	<blockquote>Major airlines are required by law to provide
flight attendants for the safety and security of the traveling
public. Although the primary job of the flight attendants is to
ensure that security and safety regulations are followed, attendants
also try to make flights comfortable and enjoyable for
passengers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Flight attendants must be certified by the
Federal Aviation Administration (FAA). A high school diploma is the
minimum educational requirement, but airlines increasingly prefer
applicants who have a college degree. Experience in dealing with the
public is important because flight attendants must be able to
interact comfortably with strangers and remain calm under
duress.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of flight attendants was
$56,640 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">HEALTH CARE</span>
<p>The occupations in this field help to keep the community healthy
by providing health care.</p>

<hr size="1" />

	<span class="header2">Occupational Health and Safety
Specialist or Technician</span><br />
	<img class="job_pic" src="/images/icons/GI/md000590.jpg"
width="100" height="100" border="0" alt="Public Health Care
Investigator" />
	<span class="header3">Job Description</span>
	<blockquote>Occupational health and safety specialists
analyze work environments and design programs to control, eliminate,
and prevent disease or injury. They look for chemical, physical,
radiological, and biological hazards and they work to make more
equipment ergonomic-designed to promote proper body positioning,
increase worker comfort, and decrease fatigue. Most occupational
health and safety specialists and technicians work in large private
firms or for federal, state, and local governments.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some employers require occupational health and
safety specialists to have a bachelor's degree in occupational
health, safety, or a related field such as engineering, biology, or
chemistry. For some positions, a master's degree in industrial
hygiene or a related subject is required. There also are associate
degree and one-year certificate programs which primarily are
intended for technicians. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of occupational health 
and safety specialists was $74,100 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Rehabilitation
Counselor</span><br />
	<span class="header3">Job Description</span>
	<blockquote>As a rehabilitation counselor, you would help a
patient who has had a severe injury or trauma to deal with his/her
emotions.  You would also help people who have an illness that
leaves them disabled.  You would listen to your clients.  You would
give them emotional support. You would also plan support services.
You would refer your clients to other people who could help as
well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A master's degree is usually required to be
licensed as a counselor.  The Commission on Rehabilitation Counselor
Certification offers voluntary national certification for
rehabilitation counselors. Many state and local governments and
other employers require rehabilitation counselors to have this
certification. To become certified, rehabilitation counselors
usually must graduate from an accredited educational program,
complete an internship, and pass a written examination. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of rehabilitation
counselors was $35,950 in May 2019. </blockquote>

<hr size="1" />


	<span class="header2">Licensed Practical / Licensed
Vocational Nurse</span><br />
	<span class="header3">Job Description</span>
	<blockquote>LPNs care for patients in many ways. Often, they
provide basic bedside care. Many LPNs measure and record patients'
vital signs such as height, weight, temperature, blood pressure,
pulse, and respiration. They also prepare and give injections,
monitor catheters, dress wounds, and give alcohol rubs and massages.
To help keep patients comfortable, they assist with bathing,
dressing, personal hygiene, moving in bed, standing, and
walking. They might also feed patients who need help eating.
Experienced LPNs may supervise nursing assistants and
aides.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most training programs, lasting about one year,
are offered by vocational or technical schools or community or
junior colleges. LPNs must be licensed to practice. Successful
completion of a practical nurse program and passing an examination
are required to become licensed.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of licensed practical/
licensed vocational nurses was $47,480 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 23, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 23, 2020). </blockquote>

</div>