<span class="header1">Science/Mathematics paired with Social/Helping
(HI)</span>

<p>Your high scores in "H" and "I" show that you are headed for a
rewarding career. You will be highly valued in the work force. You
have the potential to make a real difference in the world. You will
help others by gathering information and doing research. You are a
naturally caring person and you have a scientific mind which will
serve you well.</p>
<p>Most occupations in this pairing require at least a bachelor's
degree. It is helpful to have a master's degree or Ph.D. if you hope
to work in some of these occupations.</p>
<p><strong>Courses you may want to take in high school and beyond
(in addition to English & Math):</strong><br />
In high school you should take courses that help you to understand
people. Any courses in math and science will be of great interest to
you. They will also help prepare you for possible career
opportunities in this area.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Business Law<br />
			Drafting<br />
			Environmental&nbsp;Sciences<br />
			Health<br />
			Math
		</td>

		<td>
			Political Science<br />
			Religion<br />
			Computer&nbsp;Sciences<br />
			Education
		</td>

		<td>
			Government<br />
			Home Economics<br />
			Nutrition<br />
			Psychology
		</td>

		<td>
			Sociology<br />
			Computer&nbsp;Technology<br />
			English<br />
			Graphic Arts
		</td>

		<td>
			Law<br />
			Physical Education<br />
			Public Relations<br />
			Speech&nbsp;&&nbsp;Communications
		</td>
	</tr>
</table>

<p><strong>Extracurricular/volunteer activities or organizations
that you may find interesting:</strong><br />
If you have time for after-school activities or part-time jobs, make
them count. You will enjoy any club or activity where you can share
your love for math and science and use your people skills.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Band<br />
			Church Activities<br />
			Debate Teams<br />
			Hospice Volunteer<br />
			Junior&nbsp;Achievement<br />
			Pen Pals
		</td>

		<td>
			School&nbsp;Newspaper<br />
			School TV<br />
			Tutoring<br />
			Cheerleading<br />
			Class Officer
		</td>

		<td>
			Eldercare<br />
			Hospital Volunteer<br />
			Parks&nbsp;&&nbsp;Recreation<br />
			Photography Clubs<br />
			School Radio
		</td>

		<td>
			Scouts<br />
			Youth Groups<br />
			Childcare<br />
			Community&nbsp;Volunteer<br />
			Exchange Programs
		</td>

		<td>
			Language Clubs<br />
			Peer&nbsp;Counselor<br />
			School Monitor<br />
			School Sales<br />
			Social Clubs
		</td>
	</tr>
</table>

<p><strong>Workplaces that you may want to consider for a part-time
job:</strong><br />
These places may offer valuable opportunities to help you decide
what you want to do when you are an adult.</p>

<table cellpadding="10" cellspacing="10">
	<tr valign="top">
		<td>
			Advertising Agencies<br />
			Construction&nbsp;Companies<br />
			Graphic Design Firms<br />
			Libraries
		</td>

		<td>
			Photography Studios<br />
			Recreation&nbsp;Departments<br />
			Camp Programs<br />
			Church Programs
		</td>

		<td>
			Hospice Activities<br />
			Life Guarding<br />
			Preschool&nbsp;Programs<br />
			Restaurants
		</td>

		<td>
			Company Offices<br />
			Day Care Centers<br />
			Hospital&nbsp;Volunteer
		</td>

		<td>
			Newspaper Offices<br />
			Printing&nbsp;Companies<br />
			Special Olympics
		</td>
	</tr>
</table>

<p><strong>Here are some career possibilities for you to
explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" height="50" style="text-align: center;">
			<span class="header1">HI Career
Possibilities</span><br />
			<table bgcolor="0" cellpadding="0"
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&nbsp;</strong></td>
					<td width="33%" style="text-align: right;"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="" class="side">
				<tr align="center" height="33%"><td><strong>More<br /><br /><br /><br /><br /></strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br/>Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong><br /><br /><br /><br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3"
cellpadding="0" width="100%">
				<tr valign="top" class="main">
					<td width="20%">
						<span
class="header2">Education</span><br />
						<em>College
Professor<br />
						Education
Administrator<br />
						Teacher
							<ul>

	<li>Adult Education</li>

	<li>Science</li>

	<li>Math</li>

	<li>Biology</li>

	<li>Computer</li>

	<li>Physics</li>

	<li>English</li>
							</ul>
						Clergy
							<ul>

	<li>Priest</li>

	<li>Rabbi</li>

	<li>Minister</li>
							</ul>
						Librarian<br />
						Teacher's Aide</em>
					</td>
					<td width="20%">
						<span
class="header2">Social Service</span><br />

	<em>Psychologist<br />
						Health Services
Administrator<br />
						Economist<br />
						Social Worker
							<ul>

	<li>Mental Health</li>

	<li>School</li>

	<li>Geriatric</li>
							</ul>

	Psychotherapist<br />
						Counselor
							<ul>

	<li>School</li>

	<li>Career</li>

	<li>Drugs & Alcohol</li>
							</ul>

	Researcher<br />
						Psychiatric
Technician</em>
					</td>
					<td width="20%">
						<span
class="header2">Medicine</span><br />

	<em>Physician<br />
						Dentist<br />

	Veterinarian<br />

	Pharmacist<br />
						Physical
Therapist<br />
						Nurse<br />
						Dietitian<br />
						Dental
Hygienist<br />
						Lab/Medical
Technologist<br />
						Dental/Veterinary
Assistant<br />
						Dental/Veterinary
Technician<br />
						Home Health Aide</em>
					</td>
					<td width="20%">
						<span
class="header2">Environment</span><br />
						<em>Earth Scientist
							<ul>

	<li>Geologist</li>

	<li>Oceanographer</li>

	<li>Ecologist</li>

	<li>Meteorologist</li>
							</ul>
						Zoologist<br />
						Engineer
							<ul>

	<li>Environmental</li>

	<li>Chemical</li>
							</ul>

	Astronomer<br />
						Forester<br />
						Parks & Recreation
Manager<br />
						Zoo
Keeper<br />
						Meteorological
Technician<br />
						Research
Assistant</em>
					</td>
					<td width="20%">
						<span
class="header2">Mathematics</span><br />
						<em>Social Scientist
							<ul>

	<li>Anthropologist</li>

	<li>Sociologist</li>
							</ul>

	Accountant<br />

	Statistician<br />
						Computer Systems
Analyst<br />
						Computer
Trainer<br />
						Puzzle
Inventor<br />
						Research
Assistant<br />
						Clerk
							<ul>

	<li>Statistics</li>

	<li>Accounting</li>
							</ul></em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<div class="inner">

<hr size="1" />

<span class="header1">EDUCATION</span>
<p>The occupations in this field combine the best of learning and
sharing knowledge.</p>

<hr size="1" />

	<span class="header2">Education
Administrator</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Successful operation of an educational
institution requires competent administrators. Education
administrators provide instructional leadership and manage the day-
to-day activities in schools, preschools, day care centers, and
colleges and universities. </blockquote>
	<span class="header3">Education</span>
	<blockquote>Most education administrators begin their
careers as teachers and prepare for advancement into education
administration by completing a master's or doctoral
degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of education
administrators was $95,410 in May 2019. </blockquote>

<hr size="1" />

<span class="header2">Clergy</span><br />
	<img class="job_pic" src="/images/icons/DI/43007.jpg"
width="100" height="100" border="0" alt="Clergy" />
	<span class="header3">Job Description</span>
	<blockquote>Clergies lead religious worship and perform other
spiritual functions associated with beliefs and practices of
religious faith or denomination. They also provide spiritual and moral
guidance and assistance to members.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree to enter
this occupation.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of clergies was $55,190 in May 2019.</blockquote>

<hr size="1" />

		<span class="header2">Teacher Assistant or
Paraprofessional</span><br />
	<img class="job_pic" src="/images/icons/DG/43319.jpg"
width="100" height="100" border="0" alt="Teacher's Aide or
Paraprofessional" />
	<span class="header3">Job Description</span>
	<blockquote>Not everyone who works at a school is a
teacher.  The job of a teacher assistant is similar to that of a
teacher.  As a teacher assistant, you would help a teacher care for
his/her students, grade papers, perform clerical duties, and prepare
instructional materials.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A number of colleges offer associate degrees or
certificate programs that either prepare graduates to work as
teacher assistants or provide additional training for current
teacher assistants.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of teacher assistants
was $27,920 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">SOCIAL/MENTAL</span>
<p>The occupations in this field require the employee to gather and
use information to help others.</p>

<hr size="1" />

	<span class="header2">Social Worker</span><br />
	<img class="job_pic" src="/images/icons/DG/1212.jpg"
width="100" height="100" border="0" alt="Social Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Social work is all about helping. If you were to
become a social worker, you would help people find solutions to
problems. You might help them deal with being unemployed, being
physically or mentally disabled, or being addicted to drugs. There
is a lot of paperwork involved in being a social worker. There are
many different types of social workers as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is needed for an entry level
job. Those with positions with the most responsibilities must have a master's
degree and certification of a licensed social worker.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of social workers was
$50,470 in May 2019. </blockquote>

<hr size="1" />

<span class="header2">Occupational Health and Safety
Specialist or Technician</span><br />
	<img class="job_pic" src="/images/icons/HI/7240.jpg"
width="100" height="100" border="0" alt="Occupational Social
Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Occupational health and safety specialists
analyze work environments and design programs to control, eliminate,
and prevent disease or injury. They look for chemical, physical,
radiological, and biological hazards and they work to make more
equipment ergonomic-designed to promote proper body positioning,
increase worker comfort, and decrease fatigue. Most occupational
health and safety specialists and technicians work in large private
firms or for federal, state, and local governments.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some employers require occupational health and
safety specialists to have a bachelor's degree in occupational
health, safety, or a related field such as engineering, biology, or
chemistry. For some positions, a master's degree in industrial
hygiene or a related subject is required. There also are associate
degree and one-year certificate programs which primarily are
intended for technicians. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of occupational health and
safety specialists was $70,480 in May 2019. </blockquote>

<hr size="1" />
	<span class="header2">Psychologist</span><br />
	<img class="job_pic" src="/images/icons/BI/43119.jpg"
width="100" height="100" border="0" alt="Psychologist" />
	<span class="header3">Job Description</span>
	<blockquote>There are different kinds of psychologists.
Some focus on testing students. These are educational psychologists
who might measure a student's abilities to see if a student has a learning
disability. Some psychologists focus on helping people who are
having psychological problems. These are clinical psychologists who
help their clients to talk about and work through any problems they
may be having. Then they work with the person to develop a plan that
will help solve the problems. If you were either kind of
psychologist, you could work in private practice, either on your
own, or in a small group. You could also work in a school, hospital,
or treatment center.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A doctoral degree usually is required for
independent practice as a psychologist. A specialist degree or its
equivalent is required in most states for an individual to work as a
school psychologist, although a few states still credential school
psychologists with master's degrees. People with a master's degree
in psychology may work as industrial-organizational psychologists.
A bachelor's degree in psychology qualifies a person to assist
psychologists and other professionals in community mental health
centers, vocational rehabilitation offices, and correctional
programs. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of psychologists was
$80,370 in May 2019. </blockquote>

<hr size="1" />

<span class="header2">Funeral Director</span><br />
	<span class="header3">Job Description</span>
	<blockquote>A funeral director helps a family make funeral plans when a family member has died. If you were a funeral
director, you would handle the details of the funeral service and
burial. You would put a notice in the newspaper. You would also
order flowers and contact people to speak at the
funeral.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Funeral directors are licensed in all states.
State licensing laws vary but most require applicants to be 21
years old, have two years of formal education, serve a one-year
apprenticeship, and pass an examination. College programs in
mortuary science usually last from two to four years. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of funeral directors was
$76,350 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">MEDICINE</span>
<p>The occupations in the field of medicine allow people to study
science and to help others.</p>

<hr size="1" />

	<span class="header2">Medical Doctor</span><br />
	<span class="header3">Job Description</span>
	<blockquote>Physicians and surgeons diagnose illnesses and
prescribe and administer treatment for people suffering from injury
or disease. Physicians examine patients, obtain medical histories,
and order, perform, and interpret diagnostic tests. </blockquote>
	<span class="header3">Education</span>
	<blockquote>The common path to practicing as a physician
requires eight years of education beyond high school and three to
eight additional years of internship and residency.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of  medical doctors was
$208,000 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Pharmacist</span><br />
	<img class="job_pic" src="/images/icons/HI/C506087.jpg"
width="100" height="100" border="0" alt="Pharmacist" />
	<span class="header3">Job Description</span>
	<blockquote>Pharmacists distribute prescription drugs to
individuals. They also advise their patients, as well as physicians
and other health practitioners, on the selection, dosages,
interactions, and side effects of medications. Pharmacists monitor
the health and progress of patients to ensure the safe and effective
use of medication. Compounding - the actual mixing of ingredients to
form medications - is a small part of a pharmacist's practice,
because most medicines are produced by pharmaceutical companies in a
standard dosage and drug delivery form.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Pharmacists must earn a Pharm.D. degree from an
accredited college or school of pharmacy. To be admitted to a
Pharm.D. program, an applicant must have completed at least two
years of postsecondary study, although most applicants have
completed three or more years. A pharmacist must be licensed by the
state.  A state exam must be passed and an internship served in
order to become licensed.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of pharmacists was
$128,090 in May 2019. </blockquote>

<hr size="1" />

<span class="header2">Dietitian/Nutritionist</span><br />
	<img class="job_pic" src="/images/icons/FI/18272.jpg"
width="100" height="100" border="0" alt="Recreation Therapist" />
		<span class="header3">Job Description</span>
	<blockquote>Dietitians and nutritionists plan food and
nutrition programs, supervise meal preparation, and oversee the
serving of meals. They prevent and treat illnesses by promoting
healthy eating habits and recommending dietary modifications. Most
jobs are in hospitals, nursing care facilities, outpatient care
centers, and offices of physicians or other health practitioners.
</blockquote>
	<span class="header3">Education</span>
	<blockquote>Dietitians and nutritionists need at least a
bachelor's degree. Licensure, certification, or registration
requirements vary by state.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of
dietitians/nutritionists was $61,270 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>The occupations in this field need scientists who want to
preserve the earth's resources.</p>

<hr size="1" />

	<span class="header2">Ecologist</span><br />
	<span class="header3">Job Description</span>
	<blockquote>An ecologist is a scientist who studies the
effect that people and animals have on the earth's environment.  If
you are concerned about harm to the environment and have good
computer skills, this may be a good job for you.  As an
environmentalist, you would conduct field studies.  You would also
work in laboratories.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree to become an
ecologist.  Most employers look for a master's degree and
experience.  To get experience, volunteer with groups who work to
protect the environment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of ecologists was $71,360
in May 2019. </blockquote>


<hr size="1" />

	<span class="header2">Oceanographer</span><br />
	<img class="job_pic" src="/images/icons/AH/C511037.jpg"
width="100" height="100" border="0" alt="Oceanographer" />
	<span class="header3">Job Description</span>
	<blockquote>Oceanographers (geoscientists) are scientists
who study the ocean. As an oceanographer, you might study the
ocean's movements.  You might study the plants and animals that live
under the ocean's surface.  You might focus on what lies on the
ocean floor.  The oceans still hold many mysteries.  As an
oceanographer, you would search for what is unknown.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A bachelor's degree is the primary educational
requirement for most entry-level positions, but many begin with 
a master's degree. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of oceanographers was
$92,040 in May 2019. </blockquote>

<hr size="1" />

<span class="header1">MATHEMATICS</span>
<p>The occupations in this field need those who like working with
numbers.</p>

<hr size="1" />
	<span class="header2">Statistician</span><br />
	<img class="job_pic" src="/images/icons/CH/C1618_03.jpg"
width="100" height="100" border="0" alt="Statistician" />
	<span class="header3">Job Description</span>
	<blockquote>As a statistician, you would gather information
in numbers. For example, Major League baseball players have their
batting averages determined by statisticians. If you worked in a
business, you would look at certain numbers to see how well the
company was doing.  Is it in good shape? Numbers give the
statistician the answer.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a bachelor's degree in
statistics or mathematics for this job.  To get a promotion, you
must have a master's degree or a Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of statisticians was
$92,030 in May 2019. </blockquote>

<hr size="1" />

	<span class="header2">Accountant</span><br />
	<img class="job_pic" src="/images/icons/CH/1287.jpg"
width="100" height="100" border="0" alt="Accountant" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy working with numbers, you might
become an accountant. An accountant is responsible for helping a
company make money. You might advise the company to buy or sell
stock, or you might prepare its taxes.  You would also keep careful
records so that it was possible to tell how much money the company
made and where this money was spent.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a bachelor's degree for an entry level
job. Most accountants are CPA's (Certified Public Accountants). To
become a CPA, you must have a bachelor's degree. You must also pass
a written exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of accountants was
$71,550 in May 2019. </blockquote>


<hr size="1" />

	<span class="header2">Computer Systems
Analyst</span><br />
	<img class="job_pic" src="/images/icons/CH/43166.jpg"
width="100" height="100" border="0" alt="Computer Systems Analyst" />
	<span class="header3">Job Description</span>
	<blockquote>Computer systems analysts solve computer
problems and use computer technology to meet the needs of an
organization. They may design and develop new computer systems by
choosing and configuring hardware and software. They may also devise
ways to apply existing systems' resources to additional
tasks.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers generally prefer applicants who have
at least a bachelor's degree in computer science, information
science, or management information systems. </blockquote>
	<span class="header3">Salary</span>
	<blockquote>The median annual wage of computer systems
analysts was $90,920 in May 2019. </blockquote>

<hr size="1" />

<p><strong>To learn more about specific careers, please visit the websites below. These sources of information were used to create this report.</strong></p> <blockquote>Bureau of Labor Statistics, U.S. Department of Labor, <i> Occupational Outlook Handbook </i>, on the Internet at <a href="http://www.bls.gov/ooh">http://www.bls.gov/ooh</a> (visited September 24, 2020). </blockquote> <blockquote>National Center for O*NET Development, <i> O*NET Online </i>, on the Internet at <a href="http://www.onetonline.org">http://www.onetonline.org</a> (visited September 24, 2020). </blockquote>

</div>
