<p>Welcome to your<b><i> Careers and Occupations Guide (COG)</b></i> Report! This report combines career categories you find most interesting to help you:
<ul>
<li> understand your unique personality,</li>
<li> identify what occupations you might enjoy the most, and </li>
<li> determine the education and training required to meet your career goals.</li></ul></p>

<p>Your <b><i>COG</b></i> Report is based on your interests and provides suggestions and information in the following areas: 
<ul> 
<li> high school courses</li>
<li> extra-curricular and volunteer activities</li>
<li> part-time jobs</li>
<li> occupations detailed by people versus technical orientation and 
amount of education and training required </li>
<li> occupations detailed by job description and income 
range</li></ul></p>

<p>Remember, you are just exploring right now. You can create other <B><I>COG</i></b> reports using different career category combinations too.</P>

<p>You might want to share the information with your family, your teacher, or a school counselor. This information will help you make good decisions as you plan for life in high school and beyond.</p>

<p>Before you begin, here are some terms you need to know:

<OL><li><b>Technical, Trade, Vocational and Business Colleges</b> - in two years or less, these schools prepare you for job entry into specific trades, professions, or career fields.</li>

<li><b>Two-year Junior or Community Colleges</b> - these colleges award an associate's Degree. You can take freshman and sophomore level classes at a junior college and then transfer to a four-year institution. </li>

<li><B>Four-year College or University</b> - a school where you can earn a bachelor's degree and high level degrees such as a master's or Ph.D.</li>

<li><B>Master's Degree</b> - awarded for completing a one or two year program of study beyond a Bachelor's degree.</li>

<li><B>Doctorate Degree (e.g. Ph.D., M.D., or Ed.D)</b> - awarded for completing a program of study that is often lengthy and that requires some type of original research, as well as written and oral examinations.</li></ol> </p>

<p>Are you ready to explore your future career possibilities? Let's get started!</p>




