<span class="header1">Outdoor paired with Arts/Communications (AB)</span>

<p>An "AB" person loves to work in the open environment in settings such as nature (nature photographer), entertainment (marching band), recreation (tennis coach), animals (wildlife guide), and land improvements (landscaper) and is able to communicate well. The word "communicate" means that you can get your ideas, thoughts, or feelings understood by others easily and clearly through speaking or writing. With this pattern, you will probably want to share your interest in nature, the environment, or animals with others through your communications skills.</p>
<p>Often, an "AB" person communicates well through "visual media" using pictures, charts, graphs, or diagrams to help others understand. No matter which method you decide to use to communicate, others will probably be able to understand you.</p>
<p>Most occupations in this pairing require a Bachelor's Degree or specialized training. Higher levels of education such as a Master's Degree or a Ph.D. are valuable to certain occupations in this pattern.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">AB Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Arts/Communications</span><br /><br />
						<em>Environmental Lawyer<br /><br />
						Public Administrator<br /><br />
						Foreign Correspondent<br /><br />
						Parks & Recreation<br /><br />
						Public Relations Specialist<br /><br />
						Recreation\Coach<br /><br />
						Cartoonist<br /><br />
						Nature Writer<br /><br />
						Documentary Writer<br /><br />
						Nature Photographer<br /><br />
						Fund Raiser<br /><br /></em>
					</td>
					<td width="33%">
						<span class="header2">Out of Doors</span><br /><br />
						<em>Nature Scientist
							<ul>
								<li>Botanist</li>
								<li>Zoologist</li>
							</ul>
						Agricultural Scientist<br /><br />
						Geologist<br /><br />
						Petologist<br /><br />
						Hydrologist<br /><br />
						Athletic Coach<br /><br />
						Professional Athlete<br /><br />
						Soil Technition<br /><br />
						Parks and Recreation Manager<br /><br />
						Dog Trainer<br /><br /></em>
					</td>
					<td width="33%">
						<span class="header2">Designing/Engineering</span><br /><br />
						<em>Designing/Engineering<br /><br />
						Architect<br /><br />
						Urban Planner<br /><br />
						Engineer/Designer<br /><br />
						Pilot<br /><br />
						Meteorologist<br /><br />
						Stevedore<br /><br />
						Plumber<br /><br />
						Sculptor (concrete, lawn)<br /><br />
						Pest Control Worker<br /><br />
						Developer
							<ul>
								<li>Residential</li>
								<li>Commercial</li>
								<li>Recreational</li>
							</ul></em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">ARTS AND COMMUNICATIONS</span>
<p>Do you want to share your interest in nature and the environment with others?  Do you have strong communication skills?  If so, a career as an environmental lawyer, writer, or photographer may be of interest to you.</p>

<hr size="1" />

	<span class="header2">Environmental Lawyer</span><br /><br />
	<img class="job_pic" src="/images/icons/AB/1360.jpg" width="100" height="100" border="0" alt="Environmental Lawyer" />
	<span class="header3">Job Description</span>
	<blockquote>If you want to influence how people and organizations use the earth's environment, this occupation may be for you. To practice environmental law, you must understand the law and communicate well. You must also be organized and able to negotiate with others. If you become an environmental lawyer, you might develop a legal case or appear in court to prevent the building of a road through a wilderness area.  You might also defend a logging company's right to build that road.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You will need a Bachelor's Degree and three years of law school to be an environmental lawyer. You must also pass the state "bar exam."  To learn about nature sciences and city and rural development, volunteer with political action groups concerned about the environment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Environmental lawyer salaries range from $44,000 to $145,000.</blockquote>

<hr size="1" />

	<span class="header2">Writer</span><br /><br />
	<img class="job_pic" src="/images/icons/AB/1040.jpg" width="100" height="100" border="0" alt="Writer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like to write and are good at it, you may want to become a professional writer. Writers express their thoughts and ideas through words written on a page or computer screen. As a writer, you could help inform others about issues that affect the environment. You may work on nature documentaries, or on articles for newspapers, nature magazines, or scientific journals.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers look for writers with at least a Bachelor's Degree. Education is very valuable, but you must have talent and skill too. You will want to write as much as possible. Getting involved in writing groups, school newspapers, and yearbooks can give you valuable experience and improve your skills. Practice is important, so take every opportunity to write.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A writer's salary can range from $29,000 to $60,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Nature Photographer</span><br /><br />
	<img class="job_pic" src="/images/icons/AB/43060.jpg" width="100" height="100" border="0" ALT="Nature Photographer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like taking pictures of natural settings and have a good "eye,"  you may become a nature photographer. To do so, you must be creative and understand how cameras work. Your work might appear in magazines, books and journals, or in travel and advertising displays. Many photographers work for themselves. So, it is helpful to understand how a small business works.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A Bachelor's Degree in photography or the visual arts can develop your basic skills. But, you also need to be creative to succeed in this	field. Spend as much time as possible looking at great pictures and taking your own. Getting involved in photography clubs and working in photo shops and labs will help you learn more about using your camera to capture nature.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A nature photographer's salary ranges from $15,000 to  $50,000 per year.</blockquote>

<hr size="1" />

<span class="header1">ANIMAL AND NATURE SCIENCES</span>
<p>Occupations in this field are concerned with studying and working with plants and animals. They are more "hands on" than occupations in the arts and communication fields. People in this field work to benefit the plants and animals in our environment. They should be active and enjoy being in nature and working outdoors.</p>

<hr size="1" />
	
	<span class="header2">Botanist</span><br /><br />
	<img class="job_pic" src="/images/icons/AB/1020.jpg" width="100" height="100" border="0" alt="Botanist" />
	<span class="header3">Job Description</span>
	<blockquote>Botanists study and work with plant life. If you would like to grow and harvest food plants, or work with trees, shrubs and flowers, you might become a botanist. As a botanist, you might work to improve plant yields.  You might find ways to regulate plant growth or develop stronger or disease-free plants. You might also teach botany in a high school or university, or work to protect plant life.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A botanist must have at least a Bachelor's Degree for an entry-level job. Employers prefer a Master's or Ph.D. To learn more about plants, you can work in a plant nursery. You can also volunteer with groups concerned with the environment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Salaries run between $19,000 and $25,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Zoologist</span><br /><br />
	<img class="job_pic" src="/images/icons/AB/1079.jpg" width="100" height="100" border="0" alt="Zoologist" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy learning about and working with animals, you may become a zoologist.  Zoologists work in zoos and wildlife parks.  They also work in research centers and agricultural settings.  If you become a zoologist, you could help save animals or protect endangered species. You might also help develop better ways to raise animals for food, or work to produce better breeds of animals.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A zoologist must have at least a Bachelor's Degree for an entry-level job.  Employers prefer a Master's Degree or Ph.D.  To find out if you enjoy close contact with animals, you might work on a farm, or in a zoo or pet store.  You might also volunteer as a veterinarian's assistant.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary range is $29,000 to $71,000 per year.</blockquote>

<hr size="1" />

	<span class="header2">Wildlife Guide</span>
	<br /><br />
	<span class="header3">Job Description</span>
	<blockquote>If you like teaching others about our environment, you may become a wildlife guide. People often tour parks, wildlife refuges and other natural areas. As a wildlife guide, you would point out the interesting features of such areas to these people.  You would need excellent public speaking skills to do this.</blockquote>
	<span class="header3">Education</span> 
	<blockquote>You don't need a college degree for this occupation.  But you do need experience in the outdoors and a desire to share information with other people.  You can gain outdoor experience and skill in talking with others by working with groups concerned about the environment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary range is $13,000 to $18,000 per year.</blockquote>

<hr size="1" />

<span class="header1">DESIGNING AND ENGINEERING</span>
<p>Another good way to combine your interests in nature, the arts, and communications is to put your skills to use in design and engineering. These occupations are very technical. To do them, you must be good at logical thinking and know how to plan. You must also be able to demonstrate your plan or create a sample of the new product you have developed. Those who enjoy careers in these fields are very precise people. They like detailed work and are willing to spend time ensuring that things are done right.</p>
<p>Let's look at three occupations that may interest you.</p>

<hr size="1" />

	<span class="header2">Urban Planner</span><br /><br />
	<img class="job_pic" src="/images/icons/AB/43137.jpg" width="100" height="100" border="0" alt="Urban Planner" />
	<span class="header3">Job Description</span>
	<blockquote>The word "urban" means "city." An urban planner works with agencies that are concerned with the growth of cities. As an urban planner, you would help to see that cities grew in ways that were good for the environment and for people.  You might decide that a new street is needed or that old buildings should be repaired. You might work to ensure that water and sewage are available when new communities are developed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers require at least a Bachelor's Degree.  You will need a Master's degree to advance in this field.  You also need to be creative and able to see the "big picture" when faced with a complex problem.  To see if urban issues interest you, volunteer with groups that work to make their city a better place to live.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary range is $33,000 to $81,000 per year.</blockquote>

<hr size="1" />

	<span class="header2">Industrial Designer</span><br /><br />
	<img class="job_pic" src="/images/icons/AB/C0777_50.jpg" width="100" height="100" border="0" alt="Industrial Designer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like to create things that others want, you may become an industrial designer.  An industrial designer plans and makes manufactured products such as toys, cars, or exercise equipment for others to buy. To succeed at this occupation, you need to be artistic. You also need to understand what consumers want to buy.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers require at least a Bachelor's Degree.  They look for experience as well. You will also need a flair for seeing where a product can be improved or a new product is needed.  Spend time with people who "tinker," - play with products to see if they can be improved.  Obtain part-time work in a manufacturing setting, if possible.  Find a way to be around people who can teach you informally how to think about products.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average salary for this occupation is about $52,000 yearly.</blockquote>

<hr  size="1" />

	<span class="header2">Land Surveyor</span><br /><br />
	<img class="job_pic" src="/images/icons/AB/43169.jpg" width="100" height="100" border="0" alt="Land Surveyor" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy working outdoors with others, you may become a land surveyor.  A land surveyor works with a team of two to four people to measure land and map out property boundaries.  Construction crews cannot start building until the land has been surveyed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You don't need to a college degree to get a job as a surveyor. But those who have a degree earn more money and get promotions.  Some vocational/technical schools offer programs for land surveying.  A part-time job with a surveying company could help you to see if you would like to become a land surveyor.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary range is $25,000 to $68,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
