<span class="header1">Arts/Communications paired with 
Protective/Military Service (BE)</span>

<p>If you show high scores in categories "B" and "E" you are a 
person who knows how to make things happen. You are very independent 
and have your own way of doing things. You like to use your 
creativity and explore new possibilities.  Teamwork and people are 
important to you. You are especially good at working on teams that 
are solving problems.</p>
<p>The occupations in this pairing often require some sort of 
specialized training after high school. Some require college level 
courses. Others require training programs provided by the company 
that hires you.</p>

<p><strong>Here are some career possibilities for you to 
explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">BE Career 
Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" 
cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" 
align="left"><strong>More People Oriented</strong></td>
					<td width="33%" 
align="center"><strong>??</strong></td>
					<td width="33%" 
align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" 
cellspacing="0" height="400">
				<tr align="center" 
height="33%"><td><strong>More<br />?</strong></td></tr>
				<tr align="center" 
height="33%"><td><strong>Education<br />or<br />Training<br />Require
d</strong></td></tr>
				<tr align="center" 
height="33%"><td><strong>?<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" 
cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span 
class="header2">Written & Oral Communication</span><br /><br />
					
	<em>Attaché<br /><br />
						Public Relations 
Manager<br /><br />
						Foreign 
Correspondent<br /><br />
						Scientific & 
Technical Publications Editor<br /><br />
						International News 
Correspondent<br /><br />
						Historian<br /><br />
						Radio 
Announcer<br /><br />
						Editorial 
Assistant<br /><br />
						Reporter<br /><br />
						Interpreter</em>
					</td>
					<td width="33%">
						<span 
class="header2">Communication Technologies</span><br /><br />
						<em>Communications 
Manager<br /><br />
						Traffic 
Engineer<br /><br />
						Film 
Editor<br /><br />
						Sonar & Radar 
Technician<br /><br />
						Radio 
Operator<br /><br />
						Sound & Recording 
Engineer<br /><br />
						Engineering 
Technician<br /><br />
						Broadcast 
Technician<br /><br />
						Instrument 
Mechanic<br /><br />
						Teletype 
Operator</em>
					</td>
					<td width="33%">
						<span 
class="header2">Visual Product</span><br /><br />
						<em>Television 
Program Director<br /><br />
						Broadcast 
Journalist<br /><br />
						Industrial 
Designer<br /><br />
					
	Photojournalist<br /><br />
						Movie 
Director<br /><br />
						Graphic 
Designer<br /><br />
					
	Photographer<br /><br />
						Motion Picture 
Camera Operator<br /><br />
						Drafting 
Technician<br /><br />
						Photographic Process 
Worker</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">WRITTEN & ORAL COMMUNICATIONS</span>
<p>These occupations need people who can write well and enjoy public 
speaking. If speaking in front of large groups does not bother you, 
the occupations in this field may be appropriate.</p>

<hr size="1" />

	<span class="header2">Scientific or Technical Publications 
Editor</span><br /><br />
	<img class="job_pic" src="/images/icons/BE/43289.jpg" 
width="100" height="100" border="0" alt="Scientific or Technical 
Publications Editor" />
	<span class="header3">Job Description</span>
	<blockquote>To be a scientific or technical publications 
editor, you must be a good writer.  You must also be interested in 
science or technology.  As an editor, you would read scientific or 
technical materials as they are being written.  You would make 
suggestions for changes that would make them easier to understand.  
Editors often use computers to make their editing 
changes.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree in 
communications, journalism, or English for this job.  Many editors 
have been promoted from the writing staff.  Also, your work 
experience will be very important to finding a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>An editor can make anywhere from $24,000 to 
$76,000.</blockquote>

<hr size="1" />

	<span class="header2">Editorial Assistant</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As an editorial assistant you would work closely 
with an editor.  You would check to be sure that the grammar, 
spelling, and sentence structure were correct. You would also be 
sure that any facts, dates and other information were 
correct.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree in 
communications, journalism, or English for this job.  Volunteer work 
on yearbooks and school newspapers can give you 
experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>An editorial assistant may earn form $16,000 to 
$60,000.</blockquote>

<hr size="1" />

	<span class="header2">Reporter</span><br /><br />
	<img class="job_pic" src="/images/icons/BE/43293.jpg" 
width="100" height="100" border="0" alt="Reporter" />
	<span class="header3">Job Description</span>
	<blockquote>If you like to look for clues and piece stories 
together, you might become a reporter. As a reporter, you would 
research "a lead" or information about a possible newsworthy story. 
You would then write the story using the facts you found through 
your research.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree in 
communications, journalism, or English for this job.  Experience at 
a newspaper or broadcast studio is helpful too.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $18,000 to 
$69,000+.</blockquote>

<hr size="1" />

<span class="header1">COMMUNICATIONS TECHNOLOGIES</span>
<p>The occupations in this field are very important to our everyday 
routines. They allow you to come in contact with large numbers of 
people.</p>

<hr size="1" />

	<span class="header3">Traffic Engineer</span><br /><br />
	<img class="job_pic" src="/images/icons/BE/1099.jpg" 
width="100" height="100" border="0" alt="Traffic Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>A traffic engineer decides where the traffic 
lights go and how long the lights stay red or green.  As a traffic 
engineer, you would design traffic lights, road signs, and pavement 
markings. You would use your computer to make sure that traffic 
lights are set to allow traffic to flow smoothly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A traffic engineer must have at least a 
Bachelor's Degree and be registered in the state where he/she 
works.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly income ranges from $25,000 to 
$85,000+.</blockquote>

<hr size="1" />

	<span class="header2">Radio Operator</span><br /><br />
	<img class="job_pic" src="/images/icons/BE/M100.jpg" 
width="100" height="100" border="0" alt="Radio Operator" />
	<span class="header3">Job Description</span>
	<blockquote>A radio operator often works for the military. 
In this job, you would send, receive, and log radio messages. 
Sometimes you would figure out secret codes.  This is an important 
job. Without radio operators, it would be hard to communicate within 
the military.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You do not need a college degree for this job.  
But courses in typing, speech, and English will be valuable. The 
military will train you in radio operation.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in any branch of 
the military is based on your rank, the number of years of service, 
and the job you have.</blockquote>

<hr size="1" />

	<span class="header2">Broadcast Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/BE/1102.jpg" 
width="100" height="100" border="0" alt="Broadcast Technician" />
	<span class="header3">Job Description</span>
	<blockquote>A broadcast technician helps set up, repair, and 
operate the equipment used to send radio and television signals. 
Technicians operate the cameras.  They also create lighting effects 
and develop sound tracks. You might enjoy this job if you like 
working with equipment and do not mind getting your hands 
dirty.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need some post high school courses for this 
job.  Many technicians attend 2 or 3-year programs at vocational 
technical institutions.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A technician can start a job at $20,000. You 
salary will depend on the amount of education and experience you 
have.</blockquote>

<hr size="1" />

<span class="header1">VISUAL PRODUCTION</span>
<p>Jobs in this field are concerned with producing visual 
materials.  These materials can play an important role in helping 
people to understand information. They make written materials more 
interesting as well.  Here are three examples.</p>

<hr size="1" />

	<span class="header2">Broadcast Journalist</span><br /><br />
	<img class="job_pic" src="/images/icons/BE/43067.jpg" 
width="100" height="100" border="0" alt="Audiovisual Production 
Director" />
	<span class="header3">Job Description</span>
	<blockquote>If you are interested in radio and movies and 
you think you would like to join the military, consider becoming a 
broadcast journalist. A broadcast journalist participates in the 
production of radio or television programs.  For example, if you 
were in the military, you might work for Armed Forces Radio as a 
script writer or announcer.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Usually, you need a college degree for this 
job.  The military also provides training.  Experience is 
important.  Part-time jobs and extracurricular activities could play 
a role in getting a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Your salary is based on your experience and 
skill.</blockquote>

<hr size="1" />

	<span class="header2">Graphic Designer</span><br /><br />
	<img class="job_pic" src="/images/icons/BE/43312.jpg" 
width="100" height="100" border="0" alt="Graphic Designer" />
	<span class="header3">Job Description</span>
	<blockquote>A graphic designer helps to create visual 
displays that appear in many kinds of publications.  As a graphic 
designer, you would make signs, charts, tables, and other visual 
displays.  Your work could appear in magazines, training manuals, 
newspapers, and other publications.  You need to be creative to do 
well in this job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A college degree is not required. Because 
graphic design is highly computer-oriented today, computer skills 
would be beneficial to aquiring a job in this field.  You may also 
want to consider attending an art school that offers courses in 
graphic design.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive depends on your 
experience and skill.  It also depends on where you work.  
Experience will help in getting a job.  Part-time jobs and volunteer 
work can be important.</blockquote>

<hr size="1" />

	<span class="header2">Photojournalist</span><br /><br />
	<img class="job_pic" src="/images/icons/BE/43060.jpg" 
width="100" height="100" border="0" alt="Photojournalist" />
	<span class="header3">Job Description</span>
	<blockquote>If you like to take photographs, you might 
become a photojournalist. In this job, you would photograph 
important events for newspapers, magazines, and television.  A 
photojournalist's job is much like that of a reporter.  The 
difference is that you would use photos to tell the story.  To be 
successful, you need to be brave enough to follow a hunch.  You also 
have to be able to make quick decisions.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A Bachelor's Degree is needed to become a 
photojournalist. Experience is important also.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary is from $17,000 to $45, 
000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit 
the <em>Occupational Outlook Handbook</em>:</strong> <a 
href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information 
Network</em> Web site:</strong> <a 
href="http://online.onetcenter.org/gen_search_page">online.onetcenter
.org/gen_search_page</a></p>

