<span class="header1">Business/Management paired with Public Service (CG)</span>

<p>If you scored high in the "C" and "G" categories, you are people-oriented. You have leadership ability and can persuade others. You feel a responsibility to others. You probably want to work in ways that can help your friends, your family and your community.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree. In some of these jobs, it helps to have a Master's Degree or a Ph.D.</p>

<p><strong>Here are some career possibilities for you to explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">CG Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Public Service</span><br /><br />
						<em>College President/Administrator<br /><br />
						Publisher<br /><br />
						City Manager<br /><br />
						Social Work Agency Director<br /><br />
						Hospital Marketing Director<br /><br />
						Police Chief<br /><br />
						Elected Public Official<br /><br />
						Director of Security<br /><br />
						Continuing Education Coordinator<br /><br />
						Detective<br /><br />
						Bank Teller<br /><br />
						Security Guard</em>
					</td>
					<td width="33%">
						<span class="header2">Management</span><br /><br />
						<em>Airport Manager<br /><br />
						Hospital Administrator<br /><br />
						Public School Administrator<br /><br />
						Hotel Manager<br /><br />
						Shopping Mall Manager<br /><br />
						Trade Show Coordinator<br /><br />
						Military Officer<br /><br />
						Press Secretary<br /><br />
						Plant (Manufacturing) Manager<br /><br />
						Postal Supervisor<br /><br />
						Retail Sales Manager<br /><br />
						Assistant Restaurant Manager</em>
					</td>
					<td width="33%">
						<span class="header2">Business & Industry</span><br /><br />
						<em>Corporate Lawyer<br /><br />
						Patent Lawyer<br /><br />
						Industrial Psychologist<br /><br />
						City Housing Director<br /><br />
						Personnel Director<br /><br />
						Marketing Director<br /><br />
						Mortgage Loan Officer<br /><br />
						Financial Manager<br /><br />
						Corporate Trainer<br /><br />
						Land Developer<br /><br />
						Personnel Consultant<br /><br />
						Auctioneer<br /><br />
						Retail Salesperson</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">PUBLIC SERVICE</span>
<p>People who do well in this field are good leaders. They also want to provide some sort of service to the community.</p>

<hr size="1" />

	<span class="header2">School Principal</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/1387.jpg" width="100" height="100" border="0" alt="School Principal" />
	<span class="header3">Job Description</span>
	<blockquote>A school principal is responsible for the day-to-day management of the school. As a principal, you would work very closely with teachers to make sure that students were being taught well. You would also work to keep students' parents and the members of the community satisfied.  The school board would hire the teachers and other employees, but you would interview them and make an assessment of them before they were hired.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most states require a principal to have at least a Master's Degree. Some prefer principals to have a Ph.D. and coursework in school administration. State teaching certificates are needed for any occupation in education. Principals and teachers are expected to be students themselves. They must take courses to improve their skills and knowledge.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A principal can make between $75,000 to $85,000.</blockquote>

<hr size="1" />

	<span class="header2">Government Legislator</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/1403.jpg" width="100" height="100" border="0" alt="Government Legislator" />
	<span class="header3">Job Description</span>
	<blockquote>A government legislator works with other elected officials to pass laws. The purpose of these laws is to make improvements or solve problems. It is possible to serve as a state or federal legislator.  In either case, those who lived in your community would vote you into office.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Legislators do not have to have a degree, but most people who are elected do have a degree. The most common degrees are law, public administration, and political science. In addition, people vote for candidates who have experience in planning. They also prefer legislators who can negotiate and motivate other people.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary can range from $20,000 to $71,000.</blockquote>

<hr size="1" />

	<span class="header2">Police Detective</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a police detective, you would investigate crimes. You would try to find out what happened and who was involved. This is an exciting occupation. But it can be a dangerous job too.  To do this job well, you must be able to look at a crime scene and take in as much information as possible. You also must be a good listener so that you can take in information while a witness or suspect is talking.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Local police departments prefer to hire those with a Bachelor's Degree. To get a job with a state bureau of investigation or the FBI, you must have a degree. Detectives must pass a written exam.  They must also meet certain physical requirements.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary ranges from $31,000 to $80,000.</blockquote>

<hr size="1" /> 

<span class="header1">MANAGEMENT</span>
<p>The occupations in this field are for people who like to oversee the work of others.</p>

<hr size="1" />

	<span class="header2">Hospital Administrator</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a hospital administrator, you would be responsible for the day-to-day running of a health care facility such as a hospital, clinic or hospice. You would be in charge of hiring employees and budgeting money. You might also help to raise money to keep the facility going. To do well in this job, you need business skills.  You also need leadership and people skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Master's Degree for this job. This degree might be in hospital or health administration. It might also be in public health.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $40,000 to $175,000+.</blockquote>

<hr size="1" />

	<span class="header2">Hotel Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/43096.jpg" width="100" height="100" border="0" alt="Hotel Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Hotels are an important part of the community. The person who runs a hotel is called a hotel manager. As a hotel manager, you would be responsible for making sure the guests are comfortable during their stay. One of the most important duties you would have is to make sure that the employees are doing their jobs properly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in hotel and restaurant management for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary ranges from $35,000 to $80,000+ a year.</blockquote>

<hr size="1" />

	<span class="header2">Assistant Restaurant Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/43129.jpg" width="100" height="100" border="0" alt="Assistant Restaurant Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Restaurants are very busy places. They have many different activities going on at the same time. The restaurant manager is responsible for making sure that the restaurant runs smoothly. But sometimes he/she needs an assistant to help. As an assistant manager, you might choose and price menu items and help in hiring the staff. You would do what the manager asked you to do. Many managers start as assistant managers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers look for those who work well with others and have experience in the restaurant business. A Bachelor's Degree is preferred, but is not required.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $30,000.</blockquote>

<hr size="1" />

<span class="header1">BUSINESS & INDUSTRY</span>
<p>If you like to be challenged mentally, you may want to consider this occupational field. The occupations in this field need people who are good at solving problems.</p>

<hr size="1" />

	<span class="header2">Corporate Lawyer</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/1366.jpg" width="100" height="100" border="0" alt="Corporate Lawyer" />
	<span class="header3">Job Description</span>
	<blockquote>As a corporate lawyer, you would work for a large company.  You would use your knowledge of the law to advise executives.  You would tell them how to best protect the company and stay within the laws that govern business.  You would also gather and communicate information to other legal professionals or clients.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To become a lawyer, you need a Bachelor's Degree plus three years of law school.  Lawyers must pass a written test known as the "bar exam" also.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $35,000 to $300,000+.  Salary depends on the size and wealth of the company.</blockquote>

<hr size="1" />

	<span class="header2">Personnel Consultant</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/1370.jpg" width="100" height="100" border="0" alt="Personnel Consultant" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy helping people in practical ways, you might become a personnel consultant. As a personnel consultant, you would find job opportunities in the community.  You would then find people within the community to fill these jobs. You would interview the person to be hired.  You might also test the person, using an instrument like the Interest Inventory that you took.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A personnel consultant can make as much as $80,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Retail Salesperson</span><br /><br />
	<img class="job_pic" src="/images/icons/CG/1302.jpg" width="100" height="100" border="0" alt="Retail Salesperson" />
	<span class="header3">Job Description</span>
	<blockquote>When you go into a department store, you may have someone who comes to you and asks, "May I help you?"  This person is a retail salesperson. A retail salesperson answers questions that customers ask and helps the customer decide on what to buy. He/she also "rings up" the sale on a cash register or computer. Sometimes he/she is asked to restock shelves or racks.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Companies provide on-the-job training for this job. They may require special knowledge for people who want to work in technical sales positions.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average salary may range from $16,000 to $36,000 per year.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
