<span class="header1">Clerical/Administrative paired with Protective/Military Service (DE)</span>

<p>If you show high scores in categories "D" and "E," you are a person who knows how to make things happen. You are respectful to others. You also probably enjoy working on a team. You are able to complete tasks quickly. An exciting environment is important to you. You especially like to try new things.</p>
<p>Some of the occupations in this pairing require a Bachelor's Degree and many others require specialized training.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">DE Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Staff Support Services</span><br /><br />
						<em>Assistant Sports Coach<br /><br />
						Paralegal<br /><br />
						Airline Ticket Agent<br /><br />
						Executive Assistant<br /><br />
						Drafting Technician<br /><br />
						Court Reporter<br /><br />
						Data Reporter<br /><br />
						Receptionist<br /><br />
						City Maintenance Worker<br /><br />
						Clerk
							<ul>
								<li>Accounting</li>
								<li>Mail</li>
								<li>Shipping & Receiving</li>
							</ul></em>
					</td>
					<td width="33%">
						<span class="header2">Office Administration</span><br /><br />
						<em>Operations Manager<br /><br />
						Computer Systems Analyst<br /><br />
						Human Resources Representative<br /><br />
						Office Manager<br /><br />
						Purchasing Agent<br /><br />
						Clerical Supervisor<br /><br />
						Software Technician<br /><br />
						Office Machine Repair Technician<br /><br />
						Accountant
							<ul>
								<li>Payroll</li>
								<li>Accounts Payable</li>
								<li>Accounts Receivable</li>
							</ul></em>
					</td>
					<td width="33%">
						<span class="header2">Military</span><br /><br />
						<em>Religious Program Specialist<br /><br />
						Recruiting Specialist<br /><br />
						Administrative Support Services<br /><br />
						Lodging Specialist<br /><br />
						Legal Technician<br /><br />
						Transportation Specialist<br /><br />
						Computer Operator<br /><br />
						Optometric Technician<br /><br />
						Stenographer<br /><br />
						Stock & Inventory Specialist</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">STAFF SUPPORT SERVICES</span>
<p>The occupations in this field give support to other staff members and provide services to the public. If you chose an occupation in this field, you would play an important role in an organization or business because you would make sure that things were done coreectly.</p>

<hr size="1" />

	<span class="header2">Executive Assistant</span><br /><br />
	<img class="job_pic" src="/images/icons/DE/1206.jpg" width="100" height="100" border="0" alt="Executive Secretary" />
	<span class="header3">Job Description</span>
	<blockquote>An executive is a person who makes very important decisions for an organization or business. As an executive assistant, you would help the executive set up meetings and conferences. You would also answer letters, prepare reports, and do any other tasks that needed attention. You would need to have good people skills to do this job well. You would also need to be able to use a computer.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $22,000 to $50,000+.</blockquote>

<hr size="1" />

	<span class="header2">Drafting Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/DE/43138.jpg" width="100" height="100" border="0" alt="Drafting Technician" />
	<span class="header3">Job Description</span>
	<blockquote>A drafting technician helps architects, engineers, or designers to prepare the technical drawings that are used to present ideas. In this job, you would deal with the details.  For example, you would make sure that the drawings were drawn to scale, and you would maintain a list of the materials needed. You would also be sure that government regulations were followed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need some type of post high school training for this job.  Many technical institutes or community colleges have programs for those who want to become drafting technicians.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $24,000 to $56,000.</blockquote>

<hr size="1" />

	<span class="header2">Accounting Clerk</span><br /><br />
	<img class="job_pic" src="/images/icons/DE/1203.jpg" width="100" height="100" border="0" alt="Accounting Clerk" />
	<span class="header3">Job Description</span>
	<blockquote>As an accounting clerk, you would help a company keep track of its money. You would use the computer to develop spreadsheets that track how and where company money was being spent.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some companies require their accounting clerks to have taken some post high school courses.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary is $27,000.</blockquote>

<hr size="1" />

<span class="header1">OFFICE ADMINISTRATION</span>
<p>All of the occupations in this field need people who will follow very strict rules. If you chose an occupation in this field, you would make sure that procedures were followed and that all tasks were completed.</p>

<hr size="1" />

	<span class="header2">Purchasing Agent</span><br /><br />
	<img class="job_pic" src="/images/icons/DE/1387.jpg" width="100" height="100" border="0" alt="Purchasing Agent" />
	<span class="header3">Job Description</span>
	<blockquote>Businesses need supplies for work just like you need supplies for school. The person who is responsible for getting supplies for a business is a purchasing agent. In this job, you would buy the products or services that a business needs every day. You would compare prices to get the best deal. You would also make sure that detailed records were kept.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most purchasing agents start as a trainee and learn by experience. Some accounting skills are needed. It is also necessary to be able to properly read suppliers' detailed proposals.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $23,000 to $76,000.</blockquote>

<hr size="1" />

	<span class="header2">Clerical Supervisor</span><br /><br />
	<img class="job_pic" src="/images/icons/DE/43302.jpg" width="100" height="100" border="0" alt="Clerical Supervisor" />
	<span class="header3">Job Description</span>
	<blockquote>A clerical supervisor plans and schedules what those in an office do. As a clerical supervisor, you would assign work, maintain personnel files, and train new staff members. If the office equipment were to break down, it would be your responsibility to make sure it was repaired. You must be able to communicate well and handle many things going on at the same time.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least an Associate's Degree for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $23,000 to $65,000.</blockquote>

<hr size="1" />

	<span class="header2">Office Machine Repair Technician</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Office machines must be kept in good running order.  As an office machine repair technician, you would be responsible for installing office equipment. You would also repair and maintain this equipment.  You would work on copiers, computers, and other machines.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need some training in electronics for this job. It is helpful to attend a one-to-two year program in this field.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary is $33,000.</blockquote>

<hr size="1" />

<span class="header1">MILITARY</span>
<p>The military has many jobs for people who are good at handling details and who are efficient.</p>

<hr size="1" />

	<span class="header2">Optometric Technician</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Optometry is the study of the eyes and vision. As an optometric technician, you would help an optometrist with his/her patients. You would perform vision screening tests and order glasses and contact lenses. You would have to be very precise in giving prescriptions for glasses and contacts.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You do not need any special education to become an optometric technician. It would be helpful to take courses such as geometry and algebra in high school.  Biology courses will also be helpful.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in any branch of the military is based on your rank, the number of years of service, and job.</blockquote>

<hr size="1" />

	<span class="header2">Transportation Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/DE/400067.jpg" width="100" height="100" border="0" alt="Transportation Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>A transportation specialist in the military has many duties.  As a transportation specialist, you might make travel reservations.  You might also check cargo or check in passengers. You might also act as a flight attendant. Most of your passengers would be military personnel and their families.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are no formal requirements for this position.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in any branch of the military is based on your rank, the number of years of service, and job.</blockquote>

<hr size="1" />

	<span class="header2">Lodging Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/DE/43099.jpg" width="100" height="100" border="0" alt="Lodging Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>A lodging specialist is much like a hotel manager and clerk.  In this job, you would check in military personnel and their families at a hotel-like facility. You would answer telephone calls. You would keep records of expenses as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are no formal requirements for this position.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in any branch of the military is based on your rank, the number of years of service, and job.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
