<span class="header1">Clerical/Administrative paired with Technology (DF)</span>

<p>With a "DF" interest, you will be a valuable employee. Those who have strong scores in "D" and "F" have very high goals and want things to be done right. You like to use tools and information to reach your goals. You are an active person and will want a job that keeps you on the go.</p>
<p>Many of the occupations in this pairing require some specialized or technical training after high school. Some require college level courses and others require college degrees.</p>

<p><strong>Here are some career possibilities for you to explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">DF Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Technical Administration</span><br /><br />
						<em>Publisher<br /><br />
						Graphic Artist<br /><br />
						Technical Proofreader<br /><br />
						Graphics Specialist<br /><br />
						Medical Record Administrator<br /><br />
						Computer Programmer<br /><br />
						Airline Ticket Agent<br /><br />
						Dispensing Optician<br /><br />
						Stenographer<br /><br />
						Work Processor<br /><br />
						Switchboard Operator</em>
					</td>
					<td width="33%">
						<span class="header2">Clerical Services</span><br /><br />
						<em>Court Reporter<br /><br />
						Recreation Administrator<br /><br />
						Library Technical Assistant<br /><br />
						Insurance Claims Examiner<br /><br />
						Directory Assistance Operator<br /><br />
						Mail Carrier<br /><br />
						Construction Secretary<br /><br />
						Clerk
							<ul>
								<li>General Office</li>
								<li>Personnel</li>
								<li>Mail</li>
								<li>Shipping</li>
							</ul></em>
					</td>
					<td width="33%">
						<span class="header2">Technical Operation</span><br /><br />
						<em>Surveyor<br /><br />
						Parks & Recreation<br /><br />
						Public Relations Assistant<br /><br />
						Database Administrator<br /><br />
						Computer Programmer<br /><br />
						Flight Operations Specialist<br /><br />
						Computer Service Technician<br /><br />
						Shoe Repairer<br /><br />
						Corrections Officer<br /><br />
						Security Guard<br /><br />
						Parts Clerk
							<ul>
								<li>Auto
								<li>Hardware</li>
							</ul></em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header2">TECHNICAL ADMINISTRATION</span>
<p>If you have the ability to keep details straight and like to work with technology, this field may be for you. The occupations in this field must have detail oriented people who have technical skills.</p>

<hr size="1" />

	<span class="header2">Graphic Artist</span><br /><br />
	<img class="job_pic" src="/images/icons/DF/43285.jpg" width="100" height="100" border="0" alt="Graphic Artist" />
	<span class="header3">Job Description</span>
	<blockquote>A graphic artist helps create many of today's commercials and advertisements. A graphic artist uses media such as print and film to create new images. These images are used in advertisements and commercials. They are also used in product packaging, books, and magazines. To be a graphic artist, you must be creative and have good computer skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in fine arts, graphic design, or visual communications for this job. In addition, employers will want to see your portfolio.  This is a book that has examples of your work.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $22,000 to $65,000.</blockquote>

<hr size="1" />

	<span class="header2">Dispensing Optician</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>In this job, you would work with the two types of eye doctors, ophthalmologists and optometrists. Your duties would be to fill the prescriptions for eyeglasses and contact lenses. You would help patients pick out frames as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You do not need any special education for this job. You do need to understand some physics. Knowledge of anatomy and mechanical drawing is helpful as well. Most employers provide on-the-job training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary ranges from $20,000 to $46,000.</blockquote>

<hr size="1" />

	<span class="header2">Word Processor</span><br /><br />
	<img class="job_pic" src="/images/icons/DF/43219.jpg" width="100" height="100" border="0" alt="Word Processor" />
	<span class="header3">Job Description</span>
	<blockquote>Computers are important in every kind of work. If you like working with computers, you might become a word processor. In this job, you would enter documents on the computer.  You would also revise and edit documents.  You might also make copies of documents and answer the office telephones.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A high school diploma and typing skills are needed.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $17,000 to $40,000.</blockquote>

<hr size="1" />

<span class="header1">CLERICAL SERVICES</span>
<p>The occupations in this field need people who can recall and record details. If you have a mind that easily remembers details, they may interest you.</p>

<hr size="1" />

	<span class="header2">Court Reporter</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Courts are required to have somebody "record" what is said in the courtroom during a trial or hearing. The person who does this is a court reporter. As a court reporter, you would use a special type of machine called a stenotype, which is a type of computer that allows you to key in every word that the lawyers, judge, and witnesses say. Some reporters work within the courtroom.  Other reporters are self-employed and they work in different locations.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are special schools where you can earn a degree in court reporting. These schools offer two or four year programs. You might also have to pass a written test to become certified by the state in which you work.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges between $23,000 to $73,000.</blockquote>

<hr size="1" />

	<span class="header2">Insurance Claims Adjuster</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Sometimes accidents occur and property is damaged or destroyed. If the property has been insured, it is replaced, repaired, or reimbursed by an insurance company. The person who decides whether a "claim" is covered under an insurance policy is an insurance claims adjuster. In this job, you would do a lot of paperwork.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma and some insurance office experience for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $27,000 to $72,000.</blockquote>

<hr size="1" />

	<span class="header2">Shipping Clerk</span><br /><br />
	<img class="job_pic" src="/images/icons/DF/C1737_20.jpg" width="100" height="100" border="0" alt="Shipping Clerk" />
	<span class="header3">Job Description</span>
	<blockquote>Companies often send packages or items to other companies or places.  The person who sees that this is handled correctly is a shipping clerk.  As a shipping clerk, you would get packages ready to be shipped to other places. You would be responsible for knowing which packages went where and seeing that they arrived on time.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A high school diploma is required to become a shipping clerk.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $16,000 to $37,000.</blockquote>

<hr size="1" />

<span class="header1">TECHNICAL OPERATIONS</span>
<p>Many of the occupations in this field require computer skills. If you enjoy working with computers, these occupations may be for you.</p>

<hr size="1" />

	<span class="header2">Computer Programmer</span><br /><br />
	<img class="job_pic" src="/images/icons/DF/43290.jpg" width="100" height="100" border="0" alt="Computer Programme" />
	<span class="header3">Job Description</span>
	<blockquote>Computers must be able to perform the right programs to be of use to a company. Computers do not program themselves. Instead, a person creates and installs computer programs. As a computer programmer, you would give the computer certain instructions to follow. You would have to give the computer every instruction in detail.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $35,000 to $97,000.</blockquote>

<hr size="1" />

	<span class="header2">Database Administrator</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A database is information stored on a computer, such as a list of names and addresses. A database administrator enters and organizes this information to makes sure it is easy to get to. This is an important job because most companies have information that has to be managed a certain way.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $32,000 to $95,000.</blockquote>

<hr size="1" />

	<span class="header2">Computer Service Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/DF/1234.jpg" width="100" height="100" border="0" alt="Computer Service Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Computers are very important to our society and will continue to be in the future. If you like knowing what makes computers work and want to keep them running, you might become a computer service technician. In this job, you figure out why a computer isn't working and fix it.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma and courses in electronics for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $23,000 to $68,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
