<span class="header1">Protective/Military Service paired with Public Service (EG)</span>

<p>Your high scores in this pairing show that you can be put into positions of leadership and responsibility. You are reliable and honest. You are also supportive and resourceful. You are the kind of person that employers prefer. You can plan and coordinate events as well as guide and influence people.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree. It is helpful to have a Master's Degree or Ph.D. if you hope to work in some of these occupations.</p>

<p><strong>Here are some career possibilities for you to explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">EG Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Community</span><br /><br />
						<em>Social Worker
							<ul>
								<li>Drug & Alcohol</li>
								<li>Family</li>
								<li>Public Health</li>
							</ul>
						Public Health Consultant<br /><br />
						Public Affairs Officer<br /><br />
						Postal Service Administrator<br /><br />
						Firefighter<br /><br />
						Postal Service Personnel<br /><br />
						Religious Program Specialist<br /><br />
						Public Health Field Worker</em>
					</td>
					<td width="33%">
						<span class="header2">Legal</span><br /><br />
						<em>Lawyer<br /><br />
						Labor Relations Specialist<br /><br />
						Police Chief<br /><br />
						County Sheriff<br /><br />
						FBI Agent<br /><br />
						Investigator Detective<br /><br />
						Police Officer<br /><br />
						Legal Technician<br /><br />
						Customs Agent<br /><br />
						Security Guard</em>
					</td>
					<td width="33%">
						<span class="header2">Military</span><br /><br />
						<em>Chaplain<br /><br />
						Engineer<br /><br />
						Military Officer<br /><br />
						Transportation Manager<br /><br />
						Military Police<br /><br />
						Recruiting Specialist<br /><br />
						Interpreter & Translator<br /><br />
						Military Trainer<br /><br />
						Emergency Management Specialist<br /><br />
						Medic</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">COMMUNITY</span>
<p>If you want to help the people of your community, consider these occupations. They focus on helping the community stay healthier and/or happier.</p>

<hr size="1" />

	<span class="header2">Public Health Social Worker</span><br /><br />
	<img class="job_pic" src="/images/icons/EG/1212.jpg" width="100" height="100" border="0" alt="Public Health Social Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Social work is about helping. As a public health social worker, you would interview a family and others who know them.  You would be looking for information that would allow you to improve the family's health and well-being.  You would complete paperwork documenting what you found and did.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become a social worker at an entry-level. Those with more responsible positions must have a Master's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $23,000 to $56,000.</blockquote>

<hr size="1" />

	<span class="header1">Public Health Consultant</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A public health consultant works for the state or federal public health agency. His/her job is to make sure that the community stayed well as a whole. In this job, you would decide whether public health plans are working, or if new plans are needed. You would work with schools and doctors to educate the public in better health practices.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Health departments prefer a Bachelor's Degree. Many who enter public health have their master's degrees. A high school diploma, some college level courses, and work experience may get you an entry-level position.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $11,000 to $31,000.</blockquote>

<hr size="1" />

<span class="header1">LEGAL</span>
<p>The occupations in this field are for people who are trustworthy.  They are also for people who do not mind asking a lot of questions and can keep up with details.</p>

<hr size="1" />

	<img class="job_pic" src="/images/icons/EG/43222.jpg" width="100" height="100" border="0" alt="Industrial Labor Relations Specialist" />
	<span class="header2">Industrial Labor Relations Specialist</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As an industrial labor relations specialist, you would help senior managers and employees to agree on salaries and benefits. You would need to know the labor laws.  You would also need to have wage information.  You would need to understand economic principles as well. This would help you to know what was fair for both the company and the workers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You would need a Master's Degree for this job.  Often these specialists are lawyers who have added courses in industrial relations.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary is $52,000. Someone with a legal degree may earn more.</blockquote>

<hr size="1" />

	<span class="header2">Police Detective</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a police detective, you would investigate crimes to find out what happened and who was involved. This is an exciting occupation.  But it can be a dangerous job too.  To do this job well, you must be able to look at a crime scene and take in as much information as possible.  You also must be a good listener so that you can take in information while a witness or suspect is talking.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Local police departments prefer to hire those with a Bachelor's Degree.  To get a job with a state bureau of investigation or the FBI, you must have a college degree.  Detectives must pass a written exam. They must also meet certain physical requirements.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary ranges from $30,000 to $80,000.</blockquote>

<hr size="1" />

	<span class="header2">Security Guard</span><br /><br />
	<img class="job_pic" src="/images/icons/EG/43109.jpg" width="100" height="100" border="0" alt="Security Guard" />
	<span class="header3">Job Description</span>
	<blockquote>As a security guard, you would patrol a building to protect it. You would make sure that the office property was not stolen, and that no one was trespassing. Many security guards work at night. Others work during the day while workers are in the building.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.  You also need a valid driver's license.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Security guards are paid by the hour. The hourly wage ranges from $6.00 to $15.00.</blockquote>

<hr size="1" />

<span class="header1">MILITARY</span>
<p>One of the main functions of the military is to help local communities. The occupations in this field do this.</p>

<hr size="1" />

	<span class="header2">Recruiting Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/EG/M37.jpg" width="100" height="100" border="0" alt="Recruiting Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>A recruiting specialist helps those who are interested in joining the military to sign up. In this job, you would interview people who wanted to join the military.  You would also speak to high school and community groups.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You would need a high school diploma to become a recruiting specialist. Courses in English, Social Studies, and Public Speaking are valuable.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

	<span class="header2">Emergency Management Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/EG/M002.jpg" width="100" height="100" border="0" alt="Emergency Management Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>Emergency management specialists work for the military.  If you were a specialist, you would develop and oversee plans for disaster relief if there should be an emergency. You would supervise others in how to provide this relief. You would also tell people what to do if there was an emergency.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The military provides training to people who want to work in this occupation.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

	<span class="header2">Military Trainer</span><br /><br />
	<img class="job_pic" src="/images/icons/EG/M99.jpg" width="100" height="100" border="0" alt="Military Trainer" />
	<span class="header3">Job Description</span>
	<blockquote>A military trainer is a teacher. As a military trainer, you would teach, lecture, and test military personnel. You might train new recruits on how to drive a tank. Or, you might teach officers to use a new computer program. You would actually do many of the same things your classroom teacher does to prepare for his/her students.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree for this job. Some training would be provided by the military.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
