<span class="header1">Protective/Military Service paired with Social/Helping (EI)</span>

<p>Your high scores in "E" and "I" show that you have characteristics that are useful to people. You will be highly valued in the work force. Your strengths will be useful in many different occupations. You have a desire to share information with others and will be able to do this in a systematic way. You can be a leader if necessary.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree. In some of these jobs, it helps to have a Master's Degree or a Ph.D.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">EI Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Teaching/Guidance</span><br /><br />
						<em>Chaplain<br /><br />
						College Professor<br /><br />
						Librarian<br /><br />
						Industrial Arts Teacher<br /><br />
						Nurse<br /><br />
						Recruiting Specialist<br /><br />
						Religious Program Specialist<br /><br />
						Nursing Technician<br /><br />
						Trainer<br /><br />
						Instructor
							<ul>
								<li>Karate</li>
								<li>Sky Diving</li>
								<li>Skiing</li>
								<li>Scuba Diving</li>
							</ul></em>
					</td>
					<td width="33%">
						<span class="header2">Helping/Supportive</span><br /><br />
						<em>Therapist<br /><br />
						Social Worker<br /><br />
						Chiropractor<br /><br />
						Food Service Director<br /><br />
						Housing Relocation Administration<br /><br />
						Physical Therapist Assistant<br /><br />
						Special Service Coordinator<br /><br />
						Interpreter/Translator<br /><br />
						Occupation Therapy Specialist<br /><br />
						Recreation Specialist<br /><br />
						Medical Service Technician<br /><br />
						Cleaning Service Owner</em>
					</td>
					<td width="33%">
						<span class="header2">Supportive Operations</span><br /><br />
						<em>U.S. Marshal<br /><br />
						Customs Inspector<br /><br />
						Private Investigator<br /><br />
						Police Officer/Military Police<br /><br />
						City/State Employee<br /><br />
						Correctional Officer<br /><br />
						Compliance Officer<br /><br />
						Volunteer Coordinator<br /><br />
						City Transportation Operator<br /><br />
						Security Guard<br /><br />
						Life Guard</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">TEACHING/GUIDANCE</span>
<p>The occupations in this field allow you to help others while working in a place that has set procedures and guidelines. If you like to know what is expected of you, these are good job possibilities.</p>

<hr size="1" />

	<span class="header2">Chaplain</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/43007.jpg" width="100" height="100" border="0" alt="Chaplain" />
	<span class="header3">Job Description</span>
	<blockquote>A chaplain helps military personnel with their spiritual and personal concerns. As a chaplain, you would lead religious worship services. You would marry couples and preside at funerals. If a soldier or officer needed help, you would be there for him/her. You also would be responsible for the religious educational programs.  You would oversee volunteer programs as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Master's Degree in theology to become a chaplain. In addition, you would be "ordained" by a religious denomination.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

	<span class="header3">Military Trainer</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/M99.jpg" width="100" height="100" border="0" alt="Military Trainer" />
	<span class="header3">Job Description</span>
	<blockquote>A military trainer is a teacher. As a military trainer, you would teach, lecture, and test military personnel. You might train new recruits on how to drive a tank. Or, you might teach officers to use a new computer program. You would actually do many of the same things your classroom teacher does to prepare for his/her students.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree for this job.  Some training would be provided by the military.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

	<span class="header2">Recruiting Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/M37.jpg" width="100" height="100" border="0" alt="Recruiting Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>A recruiting specialist helps those who are interested in joining the military to sign up. In this job, you would interview people who wanted to join the military.  You would also speak to high school and community groups.</blockquote>
	<span class="header3">Educations</span>
	<blockquote>You would need a high school diploma to become a recruiting specialist. Courses in English, social studies, and public speaking are valuable.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

<span class="header1">HELPING SUPPORTIVE</span>
<p>The occupations in this field provide services to others that help them to improve their well-being. If you want to help people stay healthy, these occupations might be for you.</p>

<hr size="1" />

	<span class="header2">Chiropractor</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/43039.jpg" width="100" height="100" border="0" alt="Chiropractor" />
	<span class="header3">Job Description</span>
	<blockquote>A chiropractor believes that disease, pain, and poor health are caused by problems with the spinal column, muscles, and nerves.  As a chiropractor, you would help your patients feel better by "adjusting" their spinal column.  Most chiropractors work for themselves, so knowledge of a small business would be helpful.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A chiropractor must have at least two years of undergraduate courses or more, as requirements vary by state.  He/she must also have four years of courses in chiropractic from an accredited school.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $30,000 to $150,000. Experience and reputation will determine yearly salary.</blockquote>

<hr size="1" />

	<span class="header2">Physical Therapy Assistant</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A physical therapy assistant is a health care worker. This person works under the supervision of another health care practitioner.  This might be a physical therapist, or it might be a doctor or psychologist. In this job, you would use equipment such as a stationary bike to help patients recover from an illness or injury. You would also help with paperwork.  You would report the patient's progress to your supervisor as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need an Associate's Degree from an accredited program for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $24,000 to $49,000.</blockquote>

<hr size="1" />

	<span class="header2">Cleaning Service/Janitorial Service</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/43024.jpg" width="100" height="100" border="0" alt="Cleaning Service/Janitorial Service" />
	<span class="header3">Job Descriptions</span>
	<blockquote>A cleaning service or janitorial service cleans public places and private homes. As a janitor or cleaning serviceperson, you would find out what the client needed to be cleaned. You would either do the work yourself or hire someone to do the work for you. The client might want you to vacuum, dust, and mop. This occupation allows for a flexible schedule and is an excellent business to own.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are no educational requirements for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Cleaning service employees earn by the hour. The hourly wage ranges from $9.00 to $15.00.</blockquote>

<hr size="1" />

<span class="header1">SUPPORTIVE OPERATIONS</span>
<p>The occupations in this field mainly deal with law enforcement. If you want to make sure others are safe, consider these jobs.</p>

<hr size="1" />

	<span class="header2">U.S. Marshal</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>The main job of a U.S. marshal is to protect federal employees in the court system. As a marshal, you might be responsible for making sure that a federal courtroom is safe. You would protect the judge, clerk, and jurors. You could be assigned to protect a prisoner.  You could also be expected to track down an escaped prisoner. Being a U.S. marshal is a demanding job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree with a 2.95 grade point average for this job. You also need to have worked in another law enforcement agency.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $23,000 to $60,000.</blockquote>

<hr size="1" />

	<span class="header2">Customs Inspector</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/25032.jpg" width="100" height="100" border="0" alt="Customs Inspector" />
	<span class="header3">Job Description</span>
	<blockquote>Many people come into the United States from other countries to visit or live. Goods or products also arrive every day. To enter the country, people and goods must go through customs. As a customs inspector, you would work at an airport, seaport, or border.  Your job would be to enforce our country's laws. You might be assigned to inspect goods coming into the country. You would make sure taxes were paid and that nothing illegal was being brough in.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You  need  a Bachelor's Degree or three years of work experience for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $31,000 to $84,000+.</blockquote>

<hr size="1" />

	<span class="header2">Military Police</span><br /><br />
	<img class="job_pic" src="/images/icons/EI/M26.jpg" width="100" height="100" border="0" alt="Military Police" />
	<span class="header3">Job Description</span>
	<blockquote>Each branch of the military has its own police department. As a  member of the military police, you would make sure that people and properties were safe. You might patrol the base or facility. You would provide traffic control when needed. You might also make arrests.</blockquote>
	<span class="header3">Education</span>
	<blockquote>On-the-job training is provided for M.P.'s.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
