<span class="header1">Public Service paired with Science/Mathematics (GH)</span>

<p>If your scored high in the "G" and "H" categories, you understand that there are always ways to improve a situation. You have the ability to investigate, explore, and apply information. This will make you a valuable employee.  People like you have discovered important information that has made the world a better place.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree.  It is helpful to have a Master's Degree or Ph.D. if you hope to work in some of these occupations.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">GH Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="25%">
						<span class="header2">Public Service</span><br /><br />
						<em>Military Medical Officer<br /><br />
						Political Scientist<br /><br />
						Fire Chief<br /><br />
						Health Inspector<br /><br />
						Lobbyist<br /><br />
						Peace Corp Worker<br /><br />
						Foreign Service Officer<br /><br />
						Police Officer<br /><br />
						Investigator<br /><br />
						Security Guard</em>
					</td>
					<td width="25%">
						<span class="header2">Social/Mental</span><br /><br />
						<em>Public Health
							<ul>
								<li>Physician</li>
								<li>Dental</li>
							</ul>
						Epidemiologist<br /><br />
						Psychologist<br /><br />
						Health Services Administrator<br /><br />
						Social Worker<br /><br />
						Public Health Field Worker</em>
					</td>
					<td width="25%">
						<span class="header2">Environmental</span><br /><br />
						<em>Environmental Lawyer<br /><br />
						Chemical Engineer<br /><br />
						Ecologist<br /><br />
						Environmental Health Inspector<br /><br />
						Meteorologist<br /><br />
						Meteorologist Technician<br /><br />
						Energy Management Technician<br /><br />
						Waste Management Technician</em>
					</td>
					<td width="25%">
						<span class="header2">Science/Medical</span><br /><br />
						<em>Biological Scientist<br /><br />
						Optometrist<br /><br />
						Public Health Nurse<br /><br />
						Chiropractor<br /><br />
						Dietitian<br /><br />
						Dental Hygienist<br /><br />
						Paramedic<br /><br />
						Nurse's Aide<br /><br />
						Ophthalmic Lab Technician</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">PUBLIC SERVICE</span>
<p>The occupations in this field need people who are active and enthusiastic and who do not mind hard work.</p>

<hr size="1" />

	<span class="header2">Public Health Care Investigator</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>If you like to find solutions to problems and solve mysteries, you might become a public health care investigator.  In this job, you would find, prevent, and control diseases.  You would interview patients and gather statistics.  You would report what you found to local and state health departments and physicians.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranged from $15,000 to $36,000.</blockquote>

<hr size="1" />

	<span class="header2">Police Officer</span><br /><br />
	<img class="job_pic" src="/images/icons/GH/43135.jpg" width="100" height="100" border="0" alt="Police Officer" />
	<span class="header3">Job Description</span>
	<blockquote>If you want to help keep your community safe, you might become a police officer.  In this job, you would patrol the community to make sure that those who live and work there are safe.  You would investigate crimes, settle arguments, and even write tickets.  You would need to have good writing skills so that you could write reports on the cases you handle.</blockquote>
	<span class="header3">Education</span>
	<blockquote>It is better to have a Bachelor's Degree in this occupation.  However, some communities will hire police officers who do not have a degree.  All officers must attend a police academy where they learn police procedure and regulations.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $24,000 to $50,000 and depends on the community's ability to pay.</blockquote>

<hr size="1" />

	<span class="header2">Security Guard</span><br /><br />
	<img class="job_pic" src="/images/icons/GH/43109.jpg" width="100" height="100" border="0" alt="Security Guard" />
	<span class="header3">Job Description</span>
	<blockquote>As a security guard, you would patrol a building to make property was not stolen, and that no one was trespassing.  Many security guards work at night. Others work during the day while workers are in the building.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.  You also need a valid driver's license.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Security guards are paid by the hour. The hourly wage ranges from $6.00 to $12.00.</blockquote>

<hr size="1" />

<span class="header1">SOCIAL/MENTAL</span>
<p>The occupations in this field deal with public health.  Those who work in these occupations work to prevent disease and to encourage community well-being.</p>

<hr size="1" />

	<span class="header2">Dentist</span><br /><br />
	<img class="job_pic" src="/images/icons/GH/C506031.jpg" width="100" height="100" border="0" alt="Dentist" />
	<span class="header3">Job Description</span>
	<blockquote>A dentist helps people keep their teeth healthy and clean.  A dentist who works for the public health department not only works with individual patients, he/she also works with community health dental programs.  If you were a dentist for the health department, you might talk to students or to community groups about dental care.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need to have a Bachelor's Degree.  You also need to complete a doctorate degree from a dental school to be a dentist. You must also be licensed by the state.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $39,000 to $70,000+.</blockquote>

<hr size="1" />

	<span class="header2">Physician</span><br /><br />
	<img class="job_pic" src="/images/icons/GH/1152.jpg" width="100" height="100" border="0" alt="Physician" />
	<span class="header3">Job Description</span>
	<blockquote>A physician is a medical doctor.  If you were a doctor for the health department, you would promote wellness through community programs.  You would be responsible for making sure the programs were available to those who needed it.  For example, vaccinations are required for children.  You would make sure that announcements were made so that parents would bring their children to be vaccinated.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree.  In addition, you must graduate from medical school.  An internship and residency in a hospital are also required.  You must be licensed by the state.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $120,000 to $200,000.</blockquote>

<hr size="1" />

	<span class="header2">Public Health Social Worker</span><br /><br />
	<img class="job_pic" src="/images/icons/GH/1212.jpg" width="100" height="100" border="0" alt="Public Health Social Worker">
	<span class="header3">Job Description</span>
	<blockquote>Social work is about helping. As a public health social worker, you would interview a family and others who know them.  You would be looking for information that would allow you to improve the family's health and well-being.  You would complete paperwork documenting what you found and did.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become a social worker at an entry-level. Those with more responsible positions must have a master's degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $44,000.</blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>The occupations in this field need those who are willing to research and explore nature.</p>

<hr size="1" />

	<span class="header2">Environmental Lawyer</span><br /><br />
	<img class="job_pic" src="/images/icons/GH/1360.jpg" width="100" height="100" border="0" alt="Environmental Lawyer" />
	<span class="header3">Job Description</span>
	<blockquote>If you want to influence how people and organizations use the earth's environment, this occupation may be for you.  To practice environmental law, you must understand the law and communicate well.  You must also be organized and able to negotiate with others.  If you become an environmental lawyer, you might develop a legal case or appear in court to prevent the building of a road through a wilderness area.  Or, you might defend a logging company's right to build that road.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You will need a Bachelor's Degree and three years of law school to be an environmental lawyer. You must also pass the state "bar exam." To learn about nature sciences and city and rural development, volunteer with political action groups concerned about the environment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Environmental lawyer salaries range from $35,000 to $80,000.</blockquote>

<hr size="1" />

	<span class="header2">Ecologist</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>An ecologist is a scientist who studies the effect that people and animals have on the earth's environment.  If you are concerned about harm to the environment and have good computer skills, this may be a good job for you.  As an environmentalist, you would conduct field studies.  You would also work in laboratories. Computer skills are very important in this job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become an ecologist.  Most employers look for a Master's Degree and experience.  To get experience, volunteer with groups who work to protect the environment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $22,000 to $28,000. Those with a master's degree and experience can earn $60,000.</blockquote>

<hr size="1" />

	<span class="header2">Meteorologist Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/GH/1285.jpg" width="100" height="100" border="0" alt="Environmental Lawyer" />
	<span class="header3">Job Description</span>
	<blockquote>Meteorology is the science that studies the weather.  You may be very interested in the weather, but you may not want to become a meteorologist.  If so, you might become a meteorologist technician. In this job, you would work with a meteorologist to study and predict the weather.  You would use special tools and instruments to gather the information needed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree or military training for this job.  Many employers  prefer those with military training.  They bring practical experience to the job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $25,000.</blockquote>

<hr size="1" />

<span class="header1">SCIENCE/MEDICAL</span>
<p>There are many occupations that combine medicine and science.</p>

<hr size="1" />

	<span class="header2">Nurse</span><br /><br />
	<img class="job_pic" src="/images/icons/GH/1329.jpg" width="100" height="100" border="0" alt="Nurse" />
	<span class="header3">Job Description</span>
	<blockquote>As a nurse, you might help a doctor care for his or her patients.  You might care for patients in a hospital.  You would give shots, record a patient's progress, and assist the doctor in any medical procedures.  You must enjoy working with people to be good at this occupation.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are different levels of nursing and each has its own educational requirements.  Nursing school is required for all.  In addition, a licensing exam must be passed.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $60,000.</blockquote>

<hr size="1" />

	<span class="header2">Dietitian</span><br /><br />
	<img class="job_pic" src="/images/icons/GH/C577054.jpg" width="100" height="100" border="0" alt="Dietitian" />
	<span class="header3">Job Description</span>
	<blockquote>As a dietitian, you would make suggestions for good nutrition at hospitals, schools, and other institutions.  You might create menus.  You might make sure that food is prepared in a healthy way.  You might even go into a patient's home to plan appropriate meals. You would also try to educate people on how to eat properly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in nutrition or a health related subject for this job.  You must also complete an internship under an experienced dietitian.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $36,000.</blockquote>

<hr size="1" />

	<span class="header2">Paramedic</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>In many emergencies, an ambulance is called.  A person who works in an ambulance is called a paramedic.  As a paramedic, you would be a part of a team that helps injured or sick people in emergency situations. You would provide first aid or emergency care.  You might also take the patient to the hospital.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma.  You also need training as an emergency medical technician for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $28,000 to $40,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
