<span class="header1">Public Service paired with Social/Helping (GI)</span>

<p>Your high scores in "G" and "I" show that you are headed for a rewarding career.  You will be highly valued in the work force.  You also have the potential to make a real difference in the world.  You are a responsible, independent worker and you know how to make things happen.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree.  It is helpful to have a Master's Degree or Ph.D. if you hope to work in some of these occupations.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">GI Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="25%">
						<span class="header2">Education</span><br /><br />
						<em>Teacher<br /><br />
						Public Health Education<br /><br />
						Police Academy<br /><br />
						Instructor<br /><br />
						school Counselor<br /><br />
						Training Specialist<br /><br />
						Library Technician</em>
					</td>
					<td width="25%">
						<span class="header2">Social Service</span><br /><br />
						<em>Social Worker
							<ul>
								<li>Child Welfare</li>
								<li>Family Services</li>
								<li>Drug & Alcohol</li>
								<li>Mental Health</li>
								<li>Occupational</li>
							</ul>
						Human Services Worker
							<ul>
								<li>Social Service Assistant</li>
								<li>Case Management</li>
								<li>Community Outreach Worker</li>
								<li>Child Care Worker</li>
							</ul>
						Health Care Worker</em>
					</td>
					<td width="25%">
						<span class="header2">Public Service</span><br /><br />
						<em>Lawyer
							<ul>
								<li>Public Defender</li>
								<li>Judge</li>
							</ul>
						Paralegal<br /><br />
						Police Officer<br /><br />
						Firefighter<br /><br />
						Political Campaign Worker<br /><br />
						Flight Attendant</em>
					</td>
					<td width="25%">
						<span class="header2">Health Care</span><br /><br />
						<em>Public Health Investigator<br /><br />
						Rehabilitation Counselor<br /><br />
						Paramedic<br /><br />
						Community Health Nurse<br /><br />
						Medical Assistant<br /><br />
						Patient Representative<br /><br />
						Nursing Aide<br /><br />
						Home Health Aide</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">EDUCATION</span>
<p>Occupations in this field involve educational institutions, such as schools or colleges.</p>

<hr size="1" />

	<span class="header2">Social Studies Teacher</span><br /><br />
	<img class="job_pic" src="/images/icons/GI/ed000887.jpg" width="100" height="100" border="0" alt="Social Studies Teacher" />
	<span class="header3">Job Description</span>
	<blockquote>A teacher shares information with others.  As a social studies teacher, you would use your knowledge of government, history, and geography to help students better understand the issues that affect them in the world today. You would make lesson plans, find materials, and present lectures.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to become a teacher.  Many states prefer to hire teachers who have Master's Degrees.  Certification is also needed.  Often this means you must pass a test.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $40,000.</blockquote>

<hr size="1" />

	<span class="header2">school Counselor</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A school Counselor has many responsibilities in a school. In this job, you would  listen to your student's problems. You would help students discover their strengths and interests. You would help them reach their educational goals. You might also educate students about important topics such as drug or alcohol use. You might work with elementary, middle school, or high school students.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to be a school Counselor.  Many states require their counselors to do master's level coursework before they can be certified.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $40,000.</blockquote>

<hr size="1" />

	<span class="header2">Library Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/GI/43282.jpg" width="100" height="100" border="0" alt="Library Technician" />
	<span class="header3">Job Description</span>
	<blockquote>As a library technician, you would help a librarian.  You would gather, organize, and maintain materials used by library visitors. You would help visitors find information and materials.  You would need good computer skills to do well in this job.  You also need to enjoy helping people.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some libraries will hire high school graduates and give them on-the-job training.  Other libraries only hire those with Bachelor's Degrees.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary is $25,000.</blockquote>

<hr size="1" />

<span class="header1">SOCIAL SERVICE</span>
<p>The field of social service can be challenging.  It taps into a person's resourcefulness. It also demands that he/she be involved.</p>

<hr size="1" />

	<span class="header2">Child Welfare Social Worker</span><br /><br />
	<img class="job_pic" src="/images/icons/GI/1212.jpg" width="100" height="100" border="0" alt="Child Welfare Social Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Social work is all about helping others. As a social worker in child welfare, you would help children who are struggling with problems.  These problems may be dealing with a new school, a sick parent, drug problems, or a disability.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to find an entry-level position. To be promoted, you must have a Master's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $44,000.</blockquote>

<hr size="1" />

	<span class="header2">Occupational Social Worker</span><br /><br />
	<img class="job_pic" src="/images/icons/GI/7240.jpg" width="100" height="100" border="0" alt="Occupational Social Worker" />
	<span class="header3">Job Description</span>
	<blockquote>An occupational social worker usually works for a large company in their personnel department. Your job would be to help employees cope with the stress of working.  To do this, you would listen closely to the employee. Then you would work with him/her to get help or solve a problem.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become an entry-level social worker. Those with more responsible positions must have a Master's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $44,000.</blockquote>

<hr size="1" />

	<span class="header2">Human Services Social Worker</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a human services social worker, you would work under a doctor, nurse, or psychiatrist. You would help these health care professionals find ways to help the patient. For example, you might find a way for the patient to get to his/her doctor's appointment. Your duties would depend on what the patient needed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become an entry-level social worker. Those with more responsible positions must have a Master's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $44,000.</blockquote>

<hr size="1" />

<span class="header1">PUBLIC SERVICE</span>
<p>The occupations in this field combine public service with law.</p>

<hr size="1" />

	<span class="header2">Paralegal</span><br /><br />
	<img class="job_pic" src="/images/icons/GI/43286.jpg" width="100" height="100" border="0" alt="Paralegal" />
	<span class="header3">Job Description</span>
	<blockquote>You may be interested in law or the court system, but not want to be a lawyer. If so, you might become a paralegal.  A paralegal works closely with a lawyer.  As a paralegal, you would do a lot of research to find background information for the lawyer. You would also help the lawyer prepare for court.</blockquote>
	<span class="header3">Education</span>
	<blockquote>In the past, paralegals usually received training in a paralegal program.  More and more, lawyers want to hire paralegals who have a Bachelor's Degree in the humanities or the social sciences.  You will find a job more easily if you learn as much about the law as you can. It is also helpful to work in a law office, if possible.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average salary range is between $16,000 to $40,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Police Officer</span><br /><br />
	<img class="job_pic" src="/images/icons/GI/43135.jpg" width="100" height="100" border="0" alt="Police Office" />
	<span class="header3">Job Description</span>
	<blockquote>If you want to help keep your community safe, you might become a police officer.  In this job, you would patrol the community to make sure that those who live and work there are safe.  You would investigate crimes, settle arguments, and even write tickets.  You would need to have good writing skills so that you could write reports on the cases you handle.</blockquote>
	<span class="header3">Education</span>
	<blockquote>It is better to have a Bachelor's Degree.  However, some communities will hire police officers who do not have a degree.  All officers must attend a police academy where they learn police procedure and regulations.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $24,000 to $50,000 and depends on the community's ability to pay.</blockquote>

<hr size="1" />

	<span class="header2">Flight Attendant</span><br /><br />
	<img class="job_pic" src="/images/icons/GI/43271.jpg" width="100" height="100" border="0" alt="Flight Attendant" />
	<span class="header3">Job Description</span>
	<blockquote>As a flight attendant you would always be on the go. You would work for a commercial airline and provide services to passengers.  You would make sure passengers know safety procedures before take-off.  You would also serve them meals or refreshments.  Your most important job would be to make sure that they were safe.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma to become a flight attendant.  Many airlines prefer to hire people who have taken some college courses.  A training program is provided for flight attendants once they are hired.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $50,000.</blockquote>

<hr size="1" />

<span class="header1">HEALTH CARE</span>
<p>The occupations in this field help to keep the community healthy by providing health care.</p>

<hr size="1" />

	<span class="header2">Public Health Care Investigator</span><br /><br />
	<img class="job_pic" src="/images/icons/GI/md000590.jpg" width="100" height="100" border="0" alt="Public Health Care Investigator" />
	<span class="header3">Job Description</span>
	<blockquote>If you like to find solutions to problems and solve mysteries, you might become a public health care investigator.  In this job, you would find, prevent, and control diseases.  You would interview patients and gather statistics.  You would report what you found to local and state health departments and physicians.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $36,000.</blockquote>

<hr size="1" />

	<span class="header2">Rehabilitation Counselor</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a rehabilitation counselor, you would help a patient who has had a severe injury or trauma to deal with his/her emotions.  You would also help people who have an illness that leaves them disabled.  You would listen to your clients.  You would give them emotional support. You would also plan support services.  You would refer your clients to other people who could help as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You  need at least a Bachelor's Degree for this job.  Many counselors enter this occupation with a Master's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $18,000 to $40,000.</blockquote>

<hr size="1" />

	<span class="header2">Home Health Aide</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Demand for home health aides is growing because more sick and elderly people prefer to stay in their homes. As a home health aide, you would help the patient take care of his/her daily activities such as eating and bathing. You would also be in the home to talk and listen to the patient.  This would help to keep the patient's spirits up.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A high school diploma is needed to be a home health aide.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges runs from $10,000 to $16,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
