<span class="header1">Outdoor paired with Business / Management (AC)</span>

<p>Your high score in category "A" shows that you are a person who might like an outdoor job that allows you to work with your hands.  Your high score in "C" shows that you may have an interest in working with others.  You probably would like jobs in business, sales, and management.  You may like jobs that require that you negotiate.  It is likely that you work well with people.  You may be happiest in an occupation that includes plenty of interactions with different people.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree. It is helpful to have a Master's Degree or Ph.D. if you hope to work in some of these occupations.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">AC Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Business</span><br /><br />
						<em>Agricultural Economist<br /><br />
						Museum Director<br /><br />
						Agribusiness Consultant<br /><br />
						Range Manager<br /><br />
						Union Leader<br /><br />
						Farm Broker<br /><br />
						Factory Manager<br /><br />
						Warehouse Supervisor<br /><br />
						Auctioneer<br /><br />
						Pet Shop Owner/Worker</em>
					</td>
					<td width="33%">
						<span class="header2">Outdoor Management</span><br /><br />
						<em>Nature Scientist
							<ul>
								<li>Horticulturist</li>
							</ul>
						Wildlife Manager<br /><br />
						Recreation Administrator<br /><br />
						Resort Manager<br /><br />
						Farm Manager<br /><br />
						Rancher<br /><br />
						Orchard Manager<br /><br />
						County Fair Organizer<br /><br />
						Nursery Manager/Worker</em>
					</td>
					<td width="33%">
						<span class="header2">Environment</span><br /><br />
						<em>Regional Planner<br /><br />
						Environmentalist<br /><br />
						Environmental Health Inspector<br /><br />
						Environmental Risk Manager<br /><br />
						Wetlands Manager<br /><br />
						Safety/Traffic Engineer<br /><br />
						Logging Supervisor<br /><br />
						Water Quality Technologist<br /><br />
						Agricultural Technician<br /><br />
						Waste Management Technician<br /><br />
						Forestry Technician</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<p>Keep reading to learn more about some of the occupations shown above.</p>

<hr size="1" />

<span class="header1">BUSINESS</span>
<p>The occupations in this field help others use our earth's natural resources in a productive and efficient way. Without those in this field, the earth's resources would not last long against the demands of our growing population.</p>

<hr size="1" />

	<span class="header2">Agricultural Economist</span><br /><br />
	<img class="job_pic" src="/images/icons/AC/1142.jpg" width="100" height="100" border="0" alt="Agricultural Economist" />
	<span class="header3">Job Description</span>
	<blockquote>If you become an agricultural economist, you would help in growing, pricing, and selling of farm products. You would find out what customers want, and tell farmers what to plant, and how much they should charge for it.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To work as an assistant to an agricultural economist, you need a Bachelor's Degree in agriculture.  You need at least a Master's Degree to become an agricultural economist.  Many in this field have a Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The starting salary is based on how much education you have and may be in the range of $20,000 to $35,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Range Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/AC/1023.jpg" width="100" height="100" border="0" alt="Range Manager" />
	<span class="header3">Job Description</span>
	<blockquote>A range manager works to protect the plant and animal life of rangelands that are used for business or recreation.  For example, a business may be drilling for oil on the rangeland.  As a range manager, you would monitor the drilling activities to make sure no oil was spilled. This is a difficult occupation.  To do it well, you would need knowledge of both nature and business management.  You must also be able to balance the business's needs with those of the environment.</blockquote>
	<span class="header3">Education</span> 
	<blockquote>A range manager must have at least a Bachelor's Degree in range management or range science.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary runs from $30,000 to $80,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Farm Broker</span><br /><br />
	<img class="job_pic" src="/images/icons/AC/43204.jpg" width="100" height="100" border="0" alt="Farm Broker" />
	<span class="header3">Job Description</span>
	<blockquote>Farm brokers use their agricultural training and knowledge of farmland soils.  They are expected to know everything from when to plant to what new agricultural technology is available.  As a farm broker, you would use this knowledge to determine what crops grow best in different soils.  Then you would help farmers decide which crops they should buy and cultivate.  Sometimes you would help with running the farm.  The more you know about farmland soils, the more useful you could be.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You may learn a lot about farming through experience. You may, however, also want to get a Bachelor's Degree in agriculture or farm science. A Bachelor's Degree offers the advantage of knowing about the technology used in farming today and in the future.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Farm brokers are usually paid on commission, which means their income is based on how much is sold.  Brokers usually get a certain percentage of their income from the farmers they help.  They get another percentage of what is bought.</blockquote>

<hr size="1" />

<span class="header1">OUTDOOR MANAGEMENT</span>
<p>In this field, you would work more with people than with nature and the environment. To succeed as a manager, you must be a good team leader, be able to plan ahead, and want to work outdoors. Here are three occupations which may interest you.</p>

<hr size="1" />

	<span class="header2">Wildlife Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/AC/1270.jpg" width="100" height="100" border="0" alt="Wildlife Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Wildlife managers look for ways to protect wild animals and their habitats.  As a wildlife manager, you would do more than look after the wellbeing of individual animals.  You would care for their  homes as well.  You would monitor the plants, water, and soil of the area to be sure they  could sustain the animals.  If you found a problem, you would work to solve it.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Competition for these jobs is intense. You need at least a Master's Degree. The more education and experience you have in caring for wild animals and their habitats, the more likely you are to get a job.  Your leisure activities and part-time jobs can help you to gain experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Wildlife managers earn between $21,000 to $80,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Recreation Administrator</span><br /><br />
	<img class="job_pic" src="/images/icons/AC/C553057.jpg" width="100" height="100" border="0" alt="Recreation Administrator" />
	<span class="header3">Job Description</span>
	<blockquote>Recreation administrators plan recreational activities.  They also see that these activities go smoothly and that people who participate have a good time.  As a recreation administrator, you might plan a craft class for a group of eight-year-olds. You may also plan physical exercise programs or travel groups for people of all ages.  You may even work at a beach resort or on a cruise ship.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to become a recreation administrator.  You also need to be creative and enthusiastic.  To get experience and see if you would like this job, get a part-time job as a camp counselor or a youth organizer.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A recreation administrator can make from $26,000 to $40,000.</blockquote>

<hr  size="1" />

	<span class="header2">Farm Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/AC/1028.jpg" width="100" height="100" border="0" alt="Farm Manager" />
	<span class="header3">Job Description</span>
	<blockquote>If you like both farming and business, you may become a farm manager.  As a farm manager, you would run another person's farm. You would plan the planting and harvesting of crops, and get the crop to market for selling.  You would also decide how many farm workers were needed and what chores they needed to do.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree with courses in agriculture and business to become a farm manager.  You would need practical experience as well.  Consider summer work on a farm to get that experience.  Many people want to become farm managers, so you must be well prepared.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Because farm managers do very different things for different employers, their salaries vary.  Salaries range from $19,000 to $50,000+.</blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>The occupations in this field call for strong, free thinking people who do not mind getting their hands dirty or being on their own. All the occupations in this field have one thing in common. They require that you work directly with our environment.  If you want to do this and have the qualities that were listed, there are three occupations that you might find interesting.</p>

<hr size="1" />

	<span class="header2">Environmentalist</span><br /><br />
	<img class="job_pic" src="/images/icons/AC/1285.jpg" width="100" height="100" border="0" alt="Environmentalist" />
	<span class="header3">Job Description</span>
	<blockquote>If you care about our environment and look for ways to protect it, you might become an environmentalist. An environmentalist looks for ways to stop pollution and to clean up the air, land, and water. Most environmentalists are specialists.  They focus on one area of the environment.  This may be wildlife preservation, land conservation, or hazardous waste removal.  As an environmentalist, you would work with others as part of a large team.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree in environmental science or some area of agriculture. It will be important to understand the environment as much as possible.  Others will count on you for advice on ways to work with the environment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $60,000.</blockquote>

<hr  size="1" />

	<span class="header2">Waste Management Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/AC/43020.jpg" width="100" height="100" border="0" alt="Waste Management Technician" />
	<span class="header3">Job Description</span>
	<blockquote>Manufacturing processes can create dangerous waste materials.  If you become a waste management technician, you might help to remove chemical or nuclear wastes created by these processes.  You would wear protective clothing. You would work with equipment designed to remove toxic waste from the water and soil.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma to become a waste management technician. You would also participate in a training program offered by your company.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $44,000.</blockquote>

<hr size="1" />

<span class="header2">Forestry Technician</span><br /><br />
<img class="job_pic" src="/images/icons/AC/1042.jpg" width="100" height="100" border="0" alt="Forestry Technician" />
<span class="header3">Job Description</span>
<blockquote>A forestry technician works to allow people to visit and use our forests, and to protect the environment.  If you become a forestry technician, you might plan and oversee forest operations. These include logging, tree planting,water regulation, and wildlife management.  You might also collect information for research and oversee work crews. This is not an easy job.  You must be willing to work hard and be outside in all kinds of weather.</blockquote>
<span class="header3">Education</span>
<blockquote>To become a forestry technician, you need a Bachelor's Degree from one of the 47 schools that specialize in forestry.</blockquote>
<span class="header3">Salary</span>
<blockquote>The annual salary ranges from $18,000 to $75,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
