<span class="header1">Outdoor paired with Clerical/Administrative (AD)</span>

<p>If you had a high score in the "A" and "D" categories, you are probably a hard worker who likes to do things in a structured way. You also prefer to know what is expected of you and have a set procedure for tasks.  You do well with order, paperwork, directions and time-oriented work details. You learn best by experience and like to know the facts. You want to know exactly what will happen. You may want to look for careers that will allow you to combine your interest in the outdoors with your ability to get things done.</p>
<p>Most occupations in "AD" combination require at least a Bachelor's Degree. Many require training through a vocational or technical program.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">AD Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Outdoor Technical Environments</span><br /><br />
						<em>Air Traffic Controller<br /><br />
						Army Officer<br /><br />
						Community Relations Manager<br /><br />
						Military Enlisted Personnel<br /><br />
						Aerial Photographer<br /><br />
						Safety Engineer<br /><br />
						Travel Agent<br /><br />
						Air Quality Control Technician<br /><br />
						Telephone Cable Installer<br /><br />
						Highway Maintenance</em>
					</td>
					<td width="33%">
						<span class="header2">Nature/Office Environments</span><br /><br />
						<em>Administrative Assistant<br /><br />
						Land & Water Conservationist<br /><br />
						Title Searcher<br /><br />
						Tour Guide<br /><br />
						Receptionist<br /><br />
						Ticket Agent-Wildlife Tours Agent</em>
					</td>
					<td width="33%">
						<span class="header2">Nature/Animal Environments</span><br /><br />
						<em>Livestock Auction Coordinator<br /><br />
						Veterinary Clinic/Hospital
							<ul>
								<li>Technician</li>
								<li>Office Manager</li>
								<li>Administrative Assistant</li>
								<li>Records/Billing Clerk</li>
							</ul>
						Secretary- Zoo, Farm, Ranch<br /><br />
						Pet Store Clerk/Caretaker<br /><br />
						Pet Sitter</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">OUTDOOR TECHNICAL FIELD</span>
<p>Environmental pollution makes us more likely to get sick.  We need more facts and new technologies to prevent damage to the environment and our health.  Each occupation in this field helps preserve our future.</p>

<hr size="1" />

	<span class="header2">Community Relations Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/AD/1369.jpg" width="100" height="100" border="0" alt="Community Relations Manager" />
	<span class="header3">Job Description</span>
	<blockquote>If you understand technical information, and you communicate well, you might become a community relations manager.  In this job, you would work for a manufacturer.  You would tell people who live near the factory about any risks the factory might pose to them.  You would also report any emergencies in the plant that could cause harm to its neighbors.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in communications, public relations, or journalism to become a community relations manager.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A community relations manager earns from $22,000 to $60,000+ each year.</blockquote>

<hr  size="1" />

	<span class="header2">Safety Engineer</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A safety engineer works to make products safer and easier to use.  If you become a safety engineer, you would work for manufacturers, government agencies, or consulting firms. You might set safety standards for products. You might also inspect products to see that they meet these standards.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to become a safety engineer. Many employers prefer a Master's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>If you have a Bachelor's Degree, you can earn about $30,000 a year.  If you have a Master's Degree and are certified, you may earn up to $75,000.</blockquote>

<hr size="1" />

	<span class="header2">Air Quality Control Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/AD/C1259_02.jpg" width="100" height="100" border="0" alt="Air Quality Control Technician" />
	<span class="header3">Job Description</span>
	<blockquote>If you are concerned about the air we breathe, you might become an air quality control technician.  In this job, you would use special equipment to be sure that factories do not emit too much pollution into the air. You would also conduct laboratory experiments and pollution inspections.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma to become an air quality control technician. Companies usually provide on-the-job training once you are hired.  Some companies will want you to have some college education.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The amount you will earn depends on your educational level.  The salary range is $18,000 to $31,000.</blockquote>

<hr size="1" />

<span class="header1">NATURE/OFFICE FIELD</span>
<p>If you're interested in nature and the environment, and are good at problem solving, then you may want to consider the following occupations.</p>

<hr size="1" />

	<span class="header2">Land and Water Conservationist</span><br /><br />
	<img class="job_pic" src="/images/icons/AD/1231.jpg" width="100" height="100" border="0" alt="Land and Water Conservationist" />
	<span class="header3">Job Description</span>
	<blockquote>As a land and water conservationist, you would protect the natural habitats of wildlife. You would likely work for a federal or state government agency. The purpose of your office would be to make the rules and regulations that keep land and water from being polluted or contaminated.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most occupations at the clerical/administrative level do not require a college education. Technical training or college may be required for some occupations. Often programs are offered to increase skill level through on-the-job training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A person who works in this occupation may work for hourly wages or may make as much as $30,000.</blockquote>

<hr size="1" />

	<span class="header2">Water and Land Conservation Technician</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a water and land conservation technician, you would work with conservationists.  You will help them to protect natural wildlife habitats.  You might perform chemical tests on water and soil samples to check for pollutants.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma to become a water and land conservation technician.  High school courses in chemistry and geology will be very helpful.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $18,000 to $25,000.</blockquote>

<hr size="1" />

	<span class="header2">Tour Guide</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>If you like to teach others about our environment, you might become a wildlife guide. People often tour parks, wildlife refuges and other natural areas.  As a wildlife guide, you would point out the interesting features of such areas to these people.  You would need excellent public speaking skills to do this.</blockquote>
	<span class="header3">Education</span>
	<blockquote>The education you need varies with the employer and job. For some positions, you need a college education.  For other positions, you need only a high school diploma.  You must be interested in the park or museum where you want to work and have a pleasant disposition.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Many tour guides are paid hourly or by the trip. This work is often part-time or seasonal.</blockquote>

<hr size="1" />

<span class="header1">NATURE/ANIMAL FIELD</span>
<p>If you enjoy working with or around animals, consider the following occupations.</p>

<hr size="1" />

	<span class="header2">Veterinary Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/AD/Ph43131.jpg" width="100" height="100" border="0" alt="Veterinary Technician" />
	<span class="header3">Job Description</span>
	<blockquote>A veterinary technician works with animals in animal hospitals and clinics.  In this job, you would work closely with veterinarians.  You would help conduct laboratory tests.  You would also help dress wounds and prepare animals for surgery.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You don't need a college degree for this occupation.  However, many states require that you be licensed or certified.  To become licensed or certified, you must take a specific course(s) and pass a written test.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>You can expect to make a salary of $16,000 to $34,000.</blockquote>

<hr size="1" />

	<span class="header2">Animal Caretaker</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>An animal caretaker does for animals many of the things that a practical nurse does for people.  As an animal caretaker, you would work in an animal hospital or clinic.  You would look after sick animals and report any changes to the veterinarian. You would also feed, walk, and care for the animals. You might even bathe them.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most employers have on-the-job training programs for employees.  No college degree is required.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>An animal caretaker may earn anywhere from $11,000 to $25,000.</blockquote>

<hr size="1" />

	<span class="header2">Pet Sitter</span><br /><br />
	<img class="job_pic" src="/images/icons/AD/43130.jpg" width="100" height="100" border="0" alt="Pet Sitter" />
	<span class="header3">Job Description</span>
	<blockquote>A pet sitter cares for pets while their owners are away.  If you become a pet sitter, you will visit the animal's home or stay there until its owners return.  You will feed, walk, groom, and play with the pet(s).</blockquote>
	<span class="header3">Education</span>
	<blockquote>No college degree or high school diploma is required for this position.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A pet sitter charges by the hour, day, or week.  The hourly wage may be $10-15+.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
