<span class="header1">Outdoor paired with Protective/Military Service (AE)</span>

<p>If you scored high in categories "A" and "E" you have a strong interest in nature and you are an adventurous spirit. You like to explore new possibilities.  You also know how to  get things done.  You are willing to be a leader, and to get your hands dirty.</p>
<p>You need specialized training after high school for many of the occupations in this pairing.  For some you will need college level courses.  For others on-the-job training will be sufficient.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">AE Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Military</span><br /><br />
						<em>Pilot<br /><br />
						Intelligence Specialist<br /><br />
						Graphic Information Specialist<br /><br />
						Aircraft Launch & Recovery Specialist<br /><br />
						Artillery Crew Member<br /><br />
						Military Police<br /><br />
						Platoon/Squad Leader<br /><br />
						Mapping Technician<br /><br />
						Explosive Blasting Specialist</em>
					</td>
					<td width="33%">
						<span class="header2">Environmental</span><br /><br />
						<em>Nature Scientist
							<ul>
								<li>Geologist</li>
								<li>Marine Biologist</li>
							</ul>
						Agricultural Scientist<br /><br />
						Marine Surveyor<br /><br />
						Wildlife Manager<br /><br />
						Park Ranger<br /><br />
						Waste Management Technician<br /><br />
						Cartographer Technician</em>
					</td>
					<td width="33%">
						<span class="header2">Outdoor Service</span><br /><br />
						<em>Homeland Security Officer<br /><br />
						Immigration Specialist<br /><br />
						Public Safety Officer<br /><br />
						Contruction Equipment Operator<br /><br />
						Firefighter<br /><br />
						Heavy Equipment Mechanic<br /><br />
						Security Guard<br /><br />
						Construction Worker<br /><br />
						Groundskeeper</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">MILITARY</span>
<p>If you are looking for a challenge that will test your brain and body, consider the occupations in this field.</p>

<hr size="1" />

	<span class="header2">Military Pilot</span><br /><br />
	<img class="job_pic" src="/images/icons/AE/43025.jpg" width="100" height="100" border="0" alt="Military Pilot" />
	<span class="header3">Job Description</span>
	<blockquote>Military pilots fly many kinds of aircraft in all branches of the Armed Forces.  As a military pilot, you might fly a reconnaissance plane, or supersonic jet fighter.  You might also fly a helicopter or cargo transport.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree from a military college to become a military pilot.  Both the college and follow up training programs are very difficult.  Many people want to be a military pilot.  Only a few can meet the requirements.  To get this job, you must work very hard, and must have great mental and physical health.  You should expect to attend graduate school and other military education programs as you advance in your career.  It takes about 16 years to become a high-ranking command pilot.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

	<span class="header2">Intelligence Specialist</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>You have probably seen movies about government spies who provide information on an opposing government. These are intelligence specialists. These individuals gather and study information that is needed to protect our national safety.  In this job, you would use tools such as computers and satellites.  You would also take and study photographs, and create and study maps.  For example, they might find out about another nation's troop movements.  They might discover their military codes or find their missile sites.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree and special training from the military for this job. Courses in algebra, geometry, and geography will be helpful to you.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

	<span class="header2">Blasting Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/AE/M15-0974.jpg" width="100" height="100" border="0" alt="Blasting Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>A blasting specialist works with explosives used by the military. If you become a blasting specialist, you would move explosives from one location to another.  You would also blow up buildings or other sites.  You would keep detailed records of what you had done. To work as a blasting specialist, you must be able to stay calm under pressure.  You must also be able to follow procedures carefully and exactly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>It's best to have a college degree.  You will also need to attend a special training program.  It is important to understand chemistry so that you can handle explosives safely.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENTAL</span>
<p>You may have a strong interest in working outdoors or in saving our environment. The occupations in this field deal with the "Great Outdoors."</p>

<hr size="1" />

	<span class="header2">Marine Surveyor</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Marine surveyors explore the land under the world's oceans and seas.  As a marine surveyor, you would use different equipment to find out how deep the water is and what kind of land lies under it.  You would not work alone.  Instead, you would be part of a team. You must be very precise and detail oriented when working as a marine surveyor.  You must also work well with other people.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a surveyor's license to do this work.  You can get this license by earning a college degree and taking special surveying training.  You can also get the license by taking special surveying training and working two-to-four years in the field.  Participate in leisure activities or work in part-time jobs that help you to learn more about this work.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A surveyor will make from $15,000 to $40,000+ a year.</blockquote>

<hr size="1" />

	<span class="header2">Park Ranger</span><br /><br />
	<img class="job_pic" src="/images/icons/AE/C585042.jpg" width="100" height="100" border="0" alt="Park Ranger" />
	<span class="header3">Job Description</span>
	<blockquote>A park ranger makes sure that visitors and wildlife are safe in state and national parks. As a park ranger, you would patrol the park.  You would also collect fees, provide information about the park, and enforce park rules and regulations.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least 2 years of college courses in science and law enforcement to become a park ranger.  Many of the jobs with the U.S. Forest Service require a ranger to have a Bachelor's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive as a park ranger is based on your education and experience.  It can range from $30,000 to $70,000+.</blockquote>

<hr size="1" />

	<span class="header2">Wildlife Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/AE/1270.jpg" width="100" height="100" border="0" alt="Wildlife Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Wildlife managers look for ways to protect wild animals and their habitats.  As a wildlife manager, you would do more than look after the well-being of individual animals.  You would care for their  homes as well.  You would monitor the plants, water, and soil of the area to be sure they  could sustain the animals.  If you found a problem, you would work to solve it.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Competition for these jobs is intense.  You need at least a Master's Degree.  The more education and experience you have in caring for wild animals and their habitats, the more likely you are to get a job.  Your leisure activities and part-time jobs can help you to gain experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Wildlife managers earn between $21,000 to $80,000 a year.</blockquote>

<hr size="1" />

<span class="header1">OUTDOOR ACTIVE</span>
<p>Many people with your interests like to work in occupations that allow them to stay "on the go."  These next occupations do this.</p>

<hr size="1" />

	<span class="header2">Building Inspector</span><br /><br />
	<img class="job_pic" src="/images/icons/AE/43241.jpg" width="100" height="100" border="0" alt="Building Inspector" />
	<span class="header3">Job Description</span>
	<blockquote>Building inspectors make sure that buildings are safe.  They work on-site, looking to see that builders follow the safety codes and other rules set by the government. As a building inspector, you would check to see that the building is built to stay strong.  You would make sure, for example, that the roof would not collapse under snow.  You would make sure that there is an easy way to leave the building  in case of a fire.  You would check the building for flaws and insist that all flaws be fixed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>It's good to have some college courses.  You will also receive on-the-job training.  Many inspectors begin as construction workers, electricians, plumbers, or pipe fitters. They go on to become managers and then inspectors.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A building inspector can make from $20,000 to $60,000 each year.</blockquote>

<hr size="1" />

	<span class="header2">Meter Reader</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a meter reader, you would drive through neighborhoods, stopping at utility meters.  You would check these meters to see how much water, electricity or natural gas each household has used.  You would record these figures and report them to the utility company.  The company would send a bill to each customer, based on these figures.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma, and good writing and math skills for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A meter reader makes from $15,000 to $34,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Construction Worker</span><br /><br />
	<img class="job_pic" src="/images/icons/AE/43191.jpg" width="100" height="100" border="0" alt="Construction Worker" />
	<span class="header3">Job Description</span>
	<blockquote>A construction worker builds things like houses, office buildings, and skyscrapers.  If you were a construction worker, you could be a roofer.  You could frame buildings.  Or, you might dig foundations.  Construction is hard work, and a construction site can be dangerous.  To do construction work, you must be in top physical condition. You must also follow safety procedures and regulations carefully.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You do not need college courses for this work. But you must understand basic math and be able to read mechanical drawings.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary of a construction worker is roughly $16,000 to $50,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
