<span class="header1">Outdoor paired with Technology (AF)</span>

<p>With an "AF" interest, you will want to combine your interest in open-air occupations with your interest in technologies. You like to conduct research, employ change and apply what you know,  to work settings of the technologies and outdoors.</p>
<p>Many of the occupations in this pairing require that you have specialized and/or technical training after high school. Many require college degrees or college level courses.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">AF Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Biotechnology Environmental</span><br /><br />
						<em>Veterinarian<br /><br />
						Aquatic Biologist<br /><br />
						Ecologist<br /><br />
						Geneticist<br /><br />
						Microbiologist<br /><br />
						Physiologist<br /><br />
						Geological Oceanographer<br /><br />
						Seiasmologist<br /><br />
						Stratigrapher</em>
					</td>
					<td width="33%">
						<span class="header2">Information</span><br /><br />
						<em>Urban Planner<br /><br />
						Systems Analyst<br /><br />
						Computer
							<ul>
								<li>Sortware Engineer</li>
								<li>Programmer</li>
								<li>Technician</li>
								<li>Systems Programmer</li>
							</ul>
						Information Systems Mgr.<br /><br />
						Applications Programmer<br /><br />
						User Support Analyst<br /><br />
						Recording Engineer</em>
					</td>
					<td width="33%">
						<span class="header2">Engineering</span><br /><br />
						<em>Engineer<br /><br />
						Electrical Engineer<br /><br />
						Mechanical Engineer<br /><br />
						Civil Engineer<br /><br />
						Chemical Engineer<br /><br />
						Industrial Engineer<br /><br />
						Metallurgical Engineer<br /><br />
						Materials Engineer<br /><br />
						Medical Scientist<br /><br />
						Waste Management<br /><br />
						Water Quality Technologist</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">NATURE/ANIMALS</span>
<p>If you choose an occupation in this field, you will work  directly with nature and animals. People in these occupations often work as practical scientists. They discover new information about nature because they work closely in it.</p>

<hr size="1" />

	<span class="header2">Agricultural Scientist</span><br /><br />
	<img class="job_pic" src="/images/icons/AF/43207.jpg" width="100" height="100" border="0" alt="Agricultural Scientist" />
	<span class="header3">Job Description</span>
	<blockquote>An agricultural scientist finds ways to make farming easier and more productive.  As an agricultural scientist, you could work to increase plant production and keep farm animals healthier. You could also work to develop safer pesticides and find better ways to protect water and soil.  For this work, you need a strong background in biology and other sciences.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to assist an agricultural scientist.  You need a Master's Degree or a Ph.D. to be an agricultural scientist.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A yearly salary from $35,000 to $65,000 can be expected.</blockquote>

<hr size="1" />

	<span class="header2">Wildlife Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/AF/1270.jpg" width="100" height="100" border="0" alt="Wildlife Manager" />
	<span class="header3">Job Description</span>
	<blockquote>As a wildlife manager, you would look for ways to protect animals and their habitats.  This means you would not only look after the animals, but also care for their homes. You would make sure the plants, water, and soil of the area were in good shape for the animals. If a problem arises with the habitat, you would be responsible for solving it.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Competition for these jobs is intense.  You need at least a Master's Degree.  The more education and experience you have in caring for wild animals and their habitats, the more likely you are to get a job.  Your leisure activities and part-time jobs can help you to gain experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary runs from $21,000 to $80,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Animal Caretaker</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>An animal caretaker works with non-farm animals.  If you were an animal caretaker, you would work in a zoo, veterinary hospital, pet store or animal shelter.  You would feed and water the animals.  You would bathe, groom and exercise the animals too.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most employers have on-the-job training programs for employees. No college degree is required. There is a need for more animal caretakers.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $10,000 to $25,000.</blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>There are occupations that mix a love for the outdoors and an interest in technology.  Here are three examples.</p>

<hr size="1" />

	<span class="header2">Meteorologist</span><br /><br />
	<img class="job_pic" src="/images/icons/AF/1265.jpg" width="100" height="100" border="0" alt="Meteorologist" />
	<span class="header3">Job Description</span>
	<blockquote>Meteorologists use computers, radar and satellites to study the atmosphere.  As a meteorologist, you would use the data you collect to create weather reports.  These reports tell people about current conditions.  They also forecast future weather conditions.  This is an important job.  Weather forecasts are used to warn  people of severe or dangerous weather.  This information is important to everybody.  It can help to save lives.  It can also help to save property.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a degree in meteorology, or in a related field such as physics or earth science.  If you want to teach meteorology or conduct research, you would need a Master's Degree or Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary is between $30,000 to $92,000.</blockquote>

<hr size="1" />

	<span class="header2">Agricultural Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/AF/1194.jpg" width="100" height="100" border="0" alt="Agricultural Technician" />
	<span class="header3">Job Description</span>
	<blockquote>An agricultural technician works closely with agricultural scientists.  If you were an agricultural technician, you would help these scientists to increase plant production.  You would also help to see that farm animals were well fed.  You would spend time in the laboratory and at local farms.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a two-year degree in agriculture from a technical or community college.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $40,000.</blockquote>

<hr size="1" />

	<span class="header2">Landscaper</span><br /><br />
	<img class="job_pic" src="/images/icons/AF/43190.jpg" width="100" height="100" border="0" alt="Landscaper" />
	<span class="header3">Job Description</span>
	<blockquote>Landscapers spend nearly all of their time outdoors.  If you were a landscaper, you might work as a gardener or groundskeeper.  You would seed, weed, mow, fertilize grass, and fertilize and prune shrubs using the many tools of the landscaping trade. This is a good occupation if you want a business of your own.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma.  If you want to supervise other landscapers, you need some college courses in horticulture and landscaping experience. Many landscapers work for themselves.  So, it is helpful to understand how a small business works.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A landscaper can make anywhere from $11,000 to $24,000 a year.</blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY</span>
<p>Your active, hands-on way of working and interest in how things work will make you valuable to employers in this occupational field.</p>

<hr size="1" />

	<span class="header2">Petroleum Engineer</span><br /><br />
	<img class="job_pic" src="/images/icons/AF/1323.jpg" width="100" height="100" border="0" alt="Petroleum Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>Petroleum and natural gas are found under the ground.  If you were a petroleum engineer, you would find and retrieve this petroleum and natural gas. You would need to know about rocks and minerals and retrieval methods.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to become a petroleum engineer. Most engineers get their first jobs with a master's degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $49,000 to $127,000.</blockquote>

<hr size="1" />

	<span class="header2">Equipment Operator</span><br /><br />
	<img class="job_pic" src="/images/icons/AF/1396.jpg" width="100" height="100" border="0" alt="Equipment Operator" />
	<span class="header3">Job Description</span>
	<blockquote>Equipment operators use heavy machinery such as cranes, bulldozers, and winches to move dirt, wood, or other materials used in construction.  If you were an equipment operator, you might work at road paving sites.  You might also work at industrial and construction sites.  This equipment can be dangerous.  Safety practices are a big concern.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.  You are more likely to get a job running expensive equipment if you have taken courses at a vocational school.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A general salary range for this job is $18,000 to $26,000 per year.</blockquote>

<hr size="1" />

	<span class="header2">Survival Equipment Specialist of the Armed Forces (Military)</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A survival equipment specialist makes sure that equipment such as parachutes, rafts, fire extinguishers, and oxygen tanks are working well.  In this job, you would inspect safety equipment before training sessions or military missions. Others' lives would depend on your work.  You would need to be very thorough and detailed in performing your duties.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You do not need college courses to be a survival equipment specialist.  Shop mechanics and the sciences are high school courses that will help you to get this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
