<span class="header1">Outdoor paired with Science/Mathematics (AH)</span>

<p>If you scored high in the "A" and "H" categories, you can play an important role in understanding, protecting and exploring the laws of nature. People with your interests have contributed much to our development, discovery and application of knowledge in this area. "AH" people are usually excellent thinkers and appliers of their knowledge. They are also creative scientists who have a great respect for nature. They often find new ways to solve old problems in in all fields.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree and many will require a Master's Degree or Ph.D.</p>

<p><strong>Here are some career possibilities for you to explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">AH Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="25%">
						<span class="header2">Medical</span><br /><br />
						<em>Professor<br /><br />
						Coroner<br /><br />
						Sports Psychologist<br /><br />
						Veterinarian<br /><br />
						Horticultural Therapist<br /><br />
						Scientist
							<ul>
								<li>Animal</li>
								<li>Botanist</li>
								<li>Ecologist</li>
								<li>Food</li>
							</ul>
						Recreational Therapist<br /><br />
						Researcher<br /><br />
						Meat Inspector</em>
					</td>
					<td width="25%">
						<span class="header2">Nature Sciences</span><br /><br />
						<em>Microbiologist<br /><br />
						Archaeologist<br /><br />
						Geoscientist
							<ul>
								<li>Petroleum Geologist</li>
								<li>Mineralogist</li>
								<li>Paleontologist</li>
								<li>Oceanographer</li>
							</ul>
						Ecologist<br /><br />
						Conservationist
							<ul>
								<li>Soil</li>
								<li>Wildlife</li>
							</ul>
						Political Scientist Climatologist<br /><br />
						Firefighter<br /><br />
						Tree Farmer<br /><br />
						Planetarium Technician</em>
					</td>
					<td width="25%">
						<span class="header2">Environment</span><br /><br />
						<em>Engineer
							<ul>
								<li>Environmental</li>
								<li>Geotechnical</li>
								<li>Mining</li>
								<li>Petroleum</li>
								<li>Waste Management</li>
							</ul>
						Hazardous Materials Specialist<br /><br />
						Landscape Architect<br /><br />
						Environmental Health Inspector<br /><br />
						Coast Guard<br /><br />
						Surveyor<br /><br />
						Water Treatment Plant Operator<br /><br />
						Engineering Technician<br /><br />
						Mining</em>
					</td>
					<td width="25%">
						<span class="header2">Math</span><br /><br />
						<em>Astronomer<br /><br />
							<ul>
								<li>Astrophysicist</li>
								<li>Solar</li>
							</ul>
						Engineer
							<ul>
								<li>Aeronautical</li>
								<li>Industrial</li>
							</ul>
						Financial Officer<br /><br />
						Military Budget Officer<br /><br />
						Bio-statistician<br /><br />
						Statistician<br /><br />
						Surveyor<br /><br />
						Mapping Scientist<br /><br />
						Researcher<br /><br />
						Technician
							<ul>
								<li>Airport Computer
								<li>Mapping</li>
							</ul></em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">MEDICAL</span>
<p>Your ability to reason and your no-nonsense approach to science can help you to become an expert in this field.  Observation is very important in this field. Problem solving is important too. Here are three occupations found in this field.</p>

<hr size="1" />

	<span class="header2">Horticultural Therapist</span><br /><br />
	<img class="job_pic" src="/images/icons/AH/43033.jpg" width="100" height="100" border="0" alt="Horticultural Therapist" />
	<span class="header3">Job Description</span>
	<blockquote>Horticultural therapists combine skill in growing plants with a concern for people.  In this job, you would teach people with disabilities to grow and care for flowers, plants, vegetables, fruits, and shrubs.  This would help them to relax and allow them to create something of use and beauty.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in horticulture and some psychology courses to do this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>An average salary for this occupation is $35,000.</blockquote>

<hr size="1" />

	<span class="header2">Animal Scientist</span><br /><br />
	<img class="job_pic" src="/images/icons/AH/1009.jpg" width="100" height="100" border="0" alt="Animal Scientist" />
	<span class="header3">Job Description</span>
	<blockquote>Animal scientists conduct research to improve the breeding and health of livestock and other farm animals.  As an animal scientist, you would look for ways farmers and cattle ranchers could keep their animals healthy through better nutrition and disease control. For example, you might find a vaccine that helps prevent a disease found in cattle. You might work to solve problems in breeding.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to become an animal scientist. If you plan to do research or teach, you will need a graduate degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A yearly salary of $15,000 to $25,0000 can be expected.</blockquote>

<hr size="1" />

	<span class="header2">Veterinary Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/AH/43131.jpg" width="100" height="100" border="0" alt="Veterinary Technician" />
	<span class="header3">Job Description</span>
	<blockquote>A veterinary technician works in animal hospitals and clinics.  In this job, you would work closely with veterinarians.  You would help conduct laboratory tests.  You would also help dress wounds and prepare animals for surgery.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You don't need a college degree for this occupation.  However, many states require that you be licensed or certified.  To become licensed or certified, you must take a specific course(s) and pass a written test.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>You can expect to make a salary of $16,000 to $34,000.</blockquote>

<hr size="1" />

<span class="header1">NATURE</span>
<p>Science thrives on curiosity. We know about the world and its history because there were people who were curious. The following occupations need people who aren't afraid to ask questions and who like finding answers.</p>

<hr size="1" />

	<span class="header2">Oceanographer</span><br /><br />
	<img class="job_pic" src="/images/icons/AH/C511037.jpg" width="100" height="100" border="0" alt="Oceanographer" />
	<span class="header3">Job Description</span>
	<blockquote>Oceanographers are scientists who study the ocean. As an oceanographer, you might study the ocean's movements.  You might study the plants and animals that live under the ocean's surface.  You might focus on what lies on the ocean floor.  The oceans still hold many mysteries.  As an oceanographer, you would search for what is unknown.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become a technician or laboratory assistant.  You must have a Master's or Ph.D. to be an oceanographer.  In this area, the more education you have, the more respect you are given.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary range is $29,000 to $78,000. The salary depends on the position you have and how much education you have.</blockquote>

<hr size="1" />

	<span class="header2">Soil Conservationist</span><br /><br />
	<img class="job_pic" src="/images/icons/AH/43173.jpg" width="100" height="100" border="0" alt="Soil Conservationist" />
	<span class="header3">Job Description</span>
	<blockquote>A soil conservationist protects the soil needed for plant and crop growth. As a soil conservationist, you would work with other scientists.  Your goal would be to find ways to get the most crops from the land without hurting the environment. You would find solutions to problems such as erosion and share your solutions with farmers, ranchers, and government agencies.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You will need at least a Bachelor's Degree to get a job. In this area, the more you know and the more experience you have, the better your chances for employment. Your part-time jobs and extracurricular activities may play an important role in your job prospects.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Beginning conservationists earn between $19,000 and $40,000.  The more education you have and the higher your position, the more money you will make.</blockquote>

<hr size="1" />

	<span class="header2">Climatologist</span><br /><br />
	<img class="job_pic" src="/images/icons/AH/1053.jpg" width="100" height="100" border="0" alt="Climatologist" />
	<span class="header3">Job Description</span>
	<blockquote>Climatologists study the earth's climates.  As a climatologist, you would look at past weather records and research weather pattern changes to determine and predict area climates. You might study the effect of people's activities on the atmosphere and the effect of pollution on our air.  Your work could contribute to maps that show the world's climates.  It could contribute to other reports as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to work as a climatologist.  In this occupation, the more education you have, the better off you will be.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>An entry-level job pays from $19,000 to $23,000 per year.</blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>A desire to help improve our environment plays an important role in these occupations.</p>

<hr size="1" />

	<span class="header2">Landscape Architect</span><br /><br />
	<img class="job_pic" src="/images/icons/AH/43236.jpg" width="100" height="100" border="0" alt="Landscape Architect" />
	<span class="header3">Job Description</span>
	<blockquote>Around office buildings and malls are beautiful areas of flowers and trees. During construction, these areas are nothing more than mud or dirt. The person who plans the landscaping around a new building is a landscape architect. As a landscape architect, you would look over the area surrounding a project or building site.  You would think of a way to change the ugliness into a beautiful natural looking environment. To succeed in this job, you must appreciate nature and have an "eye" for beauty.  You must also have the technical skills to draw up plans that can be followed easily.  Finally, you must be able to "see" how the area will look after your plans are followed before the project begins.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in landscape architect for this profession.  Some programs require 5 years of study for this degree.  Also, you must get an architect's license.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average salary range is $36,000 to $62,000.</blockquote>

<hr size="1" />

	<span class="header2">Environmental Health Inspector</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Environmental health inspectors usually work for a state government.  In this job, you would work to keep our food, water and air clean and safe.  You would monitor factories, businesses, and hospitals to be sure that they obeyed government safety regulations that help to keep our environment safe.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most states agencies prefer hiring people who have Bachelor's Degrees. Many states require a license as well. To apply for a license, you must pass a written exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary for this occupation is about $49,000.</blockquote>

<hr size="1" />

<span class="header1">MATH</span>
<p>It takes a person who is good at reasoning and is very curious to fill positions in this field.  Here are three occupations that you might find interesting.</p>

<hr size="1" />

	<span class="header2">Astrophysicist/Solar Astronomer</span><br /><br />
	<img class="job_pic" src="/images/icons/AH/1277.jpg" width="100" height="100" border="0" alt="Astrophysicist/Solar Astronomer" />
	<span class="header3">Job Description</span>
	<blockquote>If you are fascinated by the stars in the sky and the solar system, you might become an astrophysicist or a solar astronomer.  People in these professions track, study and review data related to the stars and planets.  You need an imagination to work in this area.  You need good math skills too.</blockquote>
	<span class="header3">Education</span>
	<blockquote>For most occupations in the field of astronomy, a Ph.D. is required.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Yearly salaries could be anywhere from $50,000 to $129,000.  The amount depends on your degree, your position, and your employer.</blockquote>

<hr size="1" />

	<span class="header2">Surveyor</span><br /><br />
	<img class="job_pic" src="/images/icons/AH/43169.jpg" width="100" height="100" border="0" alt="Surveyor" />
	<span class="header3">Job Description</span>
	<blockquote>If you are a down to earth person and enjoy working outdoors, you might become a surveyor.  As a surveyor, you would chart, study, measure, and map the earth's surface. This occupation requires someone who is detailed and precise.</blockquote>
	<span class="header3">Education</span>
	<blockquote>In most states, a surveyor needs a four-year degree in surveying or civil engineering.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary runs from $25,000 to $67,000.</blockquote>

<hr size="1" />

	<span class="header2">Mapping Technician</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A mapping technician helps a surveyor. As a mapping technician, you would work with a team headed by a surveyor.  You would handle and use the surveying instruments used to measure distance and altitude.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You can get on-the-job training.  But it is easier to get a job if you complete a vocational tech program.  There are one-year, two-year, and three-year programs for those who want to study mapping technology.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary runs from $18,000 to $49,000 a year.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
