<span class="header1">Arts/Communications paired with Science/Mathematics (BH)</span>

<p>If your scored high in the "B" and "H" categories you are important to the future. You understand that there are always possibilities for improvement in any situation.  People like you have discovered many things about the world. You are an excellent thinker and are probably a no-nonsense kind of person. You are scientifically creative and like to ask the question, "Why?" Because of this, you will look for new ways of communicating and new ideas to communicate.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree or some post high school courses. It is helpful to have a Master's Degree or Ph.D. if you want to work in many of these occupations.</p>

<p><strong>Here are some career possibilities for you to explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">BH Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="25%">
						<span class="header2">Design</span><br /><br />
						<em>Museum Curator<br /><br />
						Architect<br /><br />
						Archeologist<br /><br />
						Gemologist<br /><br />
						Advertising Layout Artist<br /><br />
						Designer
							<ul>
								<li>Industrial</li>
								<li>Graphic</li>
								<li>Product Development</li>
								<li>Interior</li>
								<li>Hair</li>
								<li>Jewelry</li>
								<li>Lighting</li>
							</ul>
						Watch Maker<br /><br />
						Inventor</em>
					</td>
					<td width="25%">
						<span class="header2">Communications</span><br /><br />
						<em>Lawyer<br /><br />
						Technical & Scientific Publications Editor<br /><br />
						Teacher
							<ul>
								<li>Drama</li>
								<li>Speech</li>
								<li>Communications</li>
							</ul>
						Broadcast News Analyst<br /><br />
						Writer
							<ul>
								<li>Technical</li>
								<li>Journalist</li>
								<li>Biographer</li>
								<li>Nature</li>
								<li>Textbook</li>
							</ul>
						Video Producer</em>
					</td>
					<td width="25%">
						<span class="header2">Analysis</span><br /><br />
						<em>Dentist<br /><br />
						Psychologist<br /><br />
						Speech Pathologist<br /><br />
						Audiologist<br /><br />
						Physical Therapist<br /><br />
						Marketing Director<br /><br />
						Military Officer<br /><br />
						Art Therapist<br /><br />
						Librarian
							<ul>
								<li>Medical</li>
								<li>Research</li>
							</ul>
						Statistician
							<ul>
								<li>Marketing</li>
								<li>Research</li>
								<li>Television</li>
							</ul></em>
					</td>
					<td width="25%">
						<span class="header2">Technology</span><br /><br />
						<em>Engineer
							<ul>
								<li>Civil</li>
								<li>Structural</li>
								<li>Industrial</li>
							</ul>
						Photographer
							<ul>
								<li>Biological</li>
								<li>Nature</li>
							</ul>
						Medical Illustrator<br /><br />
						Landscape Designer<br /><br />
						Computer Artist<br /><br />
						Cartographer<br /><br />
						Dental Technician<br /><br />
						Optician<br /><br />
						Game Inventor</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">DESIGN</span>
<p>In this field, employees must be creative, like to study, and be good communicators. If this describes you, then you might want to consider the following occupations.</p>

<hr size="1" />

	<span class="header2">Museum Curator</span><br /><br />
	<img class="job_pic" src="/images/icons/BH/43054.jpg" width="100" height="100" border="0" alt="Museum Curator" />
	<span class="header3">Job Description</span>
	<blockquote>Museums are wonderful places. They allow you to see how people in the past lived. A museum curator finds and purchases the "artifacts," or items used long ago, for display in the museum. As a curator, you would decide how the items would be shown to the public. For example, you might plan a museum display on the French Revolution or possibly the Cherokee Indians.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Usually a curator has a Master's Degree or Ph.D. There are not many museums and competition for these jobs is intense.  It is important for a future curator to know as much about history and/or art as possible.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A yearly salary of $20,000 to $100,000+ can be expected.</blockquote>

<hr size="1" />

	<span class="header2">Archeologist</span><br /><br />
	<img class="job_pic" src="/images/icons/BH/1325.jpg" width="100" height="100" border="0" alt="Archeologist" />
	<span class="header3">Job Description</span>
	<blockquote>Archeologists often participate in archeological digs, looking for clues of past communities. As an archeologist, you would work with others to find artifacts from people who lived in the past. This is a difficult job.  You would not only look for clues that lead to artifacts, you would also oversee assistants at the dig as well. This can be a very exciting occupation.  The digs often occur in distant and unusual places. Sometimes the artifacts found are very valuable.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Master's Degree for this job.  Most archeologists have a Ph.D.  This is an occupation that needs very educated people.  Those who have a Bachelor's Degree work as assistants to archeologists.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $24,000 to $70,000.</blockquote>

<hr size="1" />

	<span class="header2">Industrial Designer</span><br /><br />
	<img class="job_pic" src="/images/icons/BH/C0777_50.jpg" width="100" height="100" border="0" alt="Industrial Designer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like to create things that others want, you might become an industrial designer.  An industrial designer plans and makes manufactured products such as toys, cars, or exercise equipment for others to buy. To succeed at this occupation, you need to be artistic. You also need to understand what consumers want to buy.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers require at least a Bachelor's Degree.  They look for experience as well. You will also need a flair for seeing where a product can be improved or a new product is needed.  Spend time with people who "tinker" with products to see if they can be improved.  Obtain part-time work in a manufacturing setting, if possible.  Find a way to be around people who can teach you informally how to think about products.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary for this occupation is about $26,000.</blockquote>

<hr size="1" />

<span class="header1">COMMUNICATION</span>
<p>Occupations in this field are for people who enjoy investigating clues and are able to speak and write well.  People who do well in these occupations like to tell others what they have discovered.</p>

<hr size="1" />

	<span class="header2">Lawyer</span><br /><br />
	<img class="job_pic" src="/images/icons/BH/43286.jpg" width="100" height="100" border="0" alt="Lawyer" />
	<span class="header3">Job Description</span>
	<blockquote>Lawyers give legal advice and assistance to people.  They represent their clients in court and in other legal matters.  There are many kinds of lawyers.  Some work with people who have been arrested and represent them in court.  There are also corporate lawyers who take care of any legal issues that are related to running a business.  There are real estate lawyers, family lawyers, and environmental lawyers as well.  What these jobs have in common is that the lawyer is responsible for helping his/her clients in matters that relate to the law.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree plus three years of law school to become a lawyer. Also a lawyer must pass an exam known as the bar. A lawyer must be very sharp and continue to learn about the law, because laws often change.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A lawyer may earn anywhere from $35,000 to $500,000+ a year.</blockquote>

<hr size="1" />

	<span class="header2">Broadcast News Analyst</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>If you like to share your opinions and want to persuade others to think as you do, you might become a broadcast news analyst.  As a news analyst, you would present the news story on the television or radio. You would then explain how you think this will affect your viewers or listeners.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree in journalism for this job.  Experience and knowledge are also very important.  As a rule, a news analyst is promoted to this position after years of experience as a broadcaster.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary runs from $17,000 to $80,000. The amount depends on the experience and skill of the analyst.  It also depends on how the television station can pay.</blockquote>

<hr size="1" />

	<span class="header2">Biographer</span><br /><br />
	<img class="job_pic" src="/images/icons/BH/43219.jpg" width="100" height="100" border="0" alt="Biographer" />
	<span class="header3">Job Description</span>
	<blockquote>If you have ever read a book about the life of someone important, you have read a biography. The person who wrote the biography is a biographer. As a biographer, you would research a person's life and then write a book about him or her. To get your information, you would interview people who know or knew the person.  You would also use documents from a library or family album to learn about the person's life.  It would be important to know where to look for information. Good writing skills are essential as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A biographer usually has a degree in journalism or English.  You need to combine writing courses and as much experience as possible to prepare for this work.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>There is no typical salary for a writer. The salary depends on the publishing company's ability to pay and whether or not others buy the book.</blockquote>

<hr size="1" />

<span class="header1">ANALYSIS</span>
<p>The occupations in this field need someone who is naturally curious and can use the scientific method to solve problems.</p>

<hr size="1" />

	<span class="header2">Speech Pathologist</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A speech pathologist helps people who have trouble speaking.  As a speech pathologist, you would teach your clients to shape their mouth and use their tongue correctly when speaking. You would also help them to make distinctions between words so that others can understand them.  Some speech pathologists work with children who are having trouble learning to speak clearly.  Others work with adults who have had a stroke or other medical problem.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A speech pathologist needs a Master's Degree in speech and language pathology. One of the best ways to learn about speech pathology is to ask a speech pathologist. There is usually one in every school.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary range is $32,000 to $74,000.</blockquote>

<hr size="1" />

	<span class="header2">Health Science Librarian</span><br /><br />
	<img class="job_pic" src="/images/icons/BH/43282.jpg" width="100" height="100" border="0" alt="Health Science Librarian" />
	<span class="header3">Job Description</span>
	<blockquote>You probably know that a librarian works in a library and keeps books and other library materials in order. What you may not know is that there are specific types of librarians. One type is a health science librarian.  As a health science librarian, you would keep the large amount of information found in the medical field available and organized.  You would also help doctors, nurses, and other health care workers find information about health issues or diseases. This is an important job.  To do it well, you must be able to handle and organize large amounts of information.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Master's Degree in library science to apply for this job.  Volunteer or work in a library to get experience with the way information is organized.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary is about $35,000.</blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY</span>
<p>Occupations in this field require good communication skills.  They also require an interest in technology.  People who work in his field must have an eye for beauty and must also be able to work with details.</p>

<hr size="1" />

	<span class="header2">Civil Engineer</span><br /><br />
	<img class="job_pic" src="/images/icons/BH/43243.jpg" width="100" height="100" border="0" alt="Civil Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>The word "civil" describes anything that has to do with a city or with civilization. A civil engineer plans and builds structures that make our lives easier. As a civil engineer, you would plan and oversee the building of roads, bridges, and airports. You would also make sure that the structures were safe for people to use.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become a civil engineer. Many people enter into this field with a Master's Degree. Civil engineers can work in several specialty fields.  Each has its own education requirements.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Salaries range between $26,000 to $75,000.</blockquote>

<hr size="1" />

	<span class="header2">Photographer</span><br /><br />
	<img class="job_pic" src="/images/icons/BH/43060.jpg" width="100" height="100" border="0" alt="Photographer" />
	<span class="header3">Job Description</span>
	<blockquote>If you like taking pictures and have a good "eye", you might become a professional photographer. A photographer combines communications skills and technology.  In this job, you would take pictures of people, things, or events. You must be creative.  Your goal is to show people something they might not have seen otherwise.  You must understand the technical aspects of the camera. You must alsoknow how to process film. Many photographers work for themselves, so it is helpful to understand how a small business works.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A Bachelor's Degree in photography or the visual arts can develop your basic skills.  But, you also need to be creative to succeed in this field.  Spend as much time as possible looking at pictures and taking your own. Getting involved in photography clubs and working in photo shops and labs will help you learn more about using your camera to capture successful photographs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A photographer's salary can be anywhere from $15,000 to $48,000+ per year.</blockquote>

<hr size="1" />

	<span class="header2">Dental Technician</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A dental technician makes equipment used by the dentist in treating patients.  As a dental technician you would make crowns, bridges, and dentures for people's mouths.</blockquote>
	<span class="header3">Education</span>
	<blockquote>It takes about four years to be a qualified dental technician. You can get the training you need through a community college.  The military also offers dental technician training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary for a dental technician is about $27,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
