<span class="header1">Arts/Communications paired with Social Helping (BI)</span>

<p>Your high scores in "B" and "I" show that you bring together many characteristics that can be useful to people. You are a creative and outgoing person, and you enjoy helping others with tehir problems. You also have the ability to communicate your ideas and thoughts clearly.  You may be a person who likes to teach or to plan fund raising programs for charity.  For you, what is important is that you are helping others.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree or some post high school courses.  It is helpful to have a Master's Degree or Ph.D. if you want to work in many of these occupations.</p>

<p><strong>Here are some career possibilities for you to explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">BI Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Creative Education</span><br /><br />
						<em>Clergy
							<ul>
								<li>Brother</li>
								<li>Minister</li>
								<li>Nun</li>
								<li>Priest</li>
								<li>Rabbi</li>
							</ul>
						Teacher/Professor
							<ul>
								<li>Art</li>
								<li>Drama</li>
								<li>Dance</li>
								<li>Communications</li>
								<li>Music</li>
								<li>Pre-school</li>
								<li>Religion</li>
								<li>Special Education</li>
								<li>Writing</li>
							</ul>
						Teacher's Aide<br /><br />
						Library Assistant</em>
					</td>
					<td width="33%">
						<span class="header2">Creative Helping</span><br /><br />
						<em>Psychologist<br /><br />
						Public Relations Counselor<br /><br />
						Marriage Counselor<br /><br />
						Art/Music Therapy<br /><br />
						Interior Designer<br /><br />
						Cosmetologist
							<ul>
								<li>Manicurist</li>
								<li>Barber</li>
							</ul>
						Massage Therapist<br /><br />
						Audiovisual Librarian<br /><br />
						Advertising Production Specialist<br /><br />
						Adventure Travel Coordinator<br /><br />
						Caterer<br /><br />
						Retail Salesperson</em>
					</td>
					<td width="33%">
						<span class="header2">Creative Performance</span><br /><br />
						<em>Writer
							<ul>
								<li>Author</li>
								<li>Playwright</li>
								<li>Poet</li>
								<li>Song</li>
								<li>Screen</li>
								<li>Travel</li>
							</ul>
						Chef<br /><br />
						Photographer<br /><br />
						Radio/TV Talk Show Host<br /><br />
						Police Artist<br /><br />
						Actress/Actors<br /><br />
						Musician<br /><br />
						Singer<br /><br />
						Model<br /><br />
						Comedian</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">CREATIVE EDUCATION</span>
<p>The occupations in this field need people who communicate well and want to help people solve problems. Let's look at three occupations that may interest you.</p>

<hr size="1" />

	<span class="header2">Art Teacher</span><br /><br />
	<img class="job_pic" src="/images/icons/BI/C2126_01.jpg" width="100" height="100" border="0" alt="Art Teacher" />
	<span class="header3">Job Description</span>
	<blockquote>An art teacher helps students in his/her class to enjoy the beauty in art and to develop any skills in art that they might have.  As an art teacher, you would write lesson plans, teach classes, and possibly sponsor the school's art club. You would need to have skill in at least one area of art. But what is most important is that you are able to help students get in touch with their own interests and skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To teach in the public schools, you need at least a Bachelor's Degree. You also need a teaching license or certificate.  Most public school teachers earn a Master's Degree as they continue to teach.  Teachers love to learn and spend a great deal of time as students themselves.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary is $39,000.</blockquote>

<hr size="1" />

	<span class="header2">Special Education Teacher</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A special education teacher works with students who have physical, mental or emotional disabilities.  As a special education teacher, you would write individual lesson plans and teach your students.  You would need to be able to encourage students to work hard even when they found the work difficult. You must also be able to help them get in touch with their interests and skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To teach in public schools, you need at least a Bachelor's Degree. You also need a teaching license or certificate.  Most public school teachers earn a Master's Degree as they continue to teach. Teachers love to learn and spend a great deal of time as students themselves.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary is $42,000.</blockquote>

<hr size="1" />

	<span class="header2">Teacher's Aide/Paraprofessional</span><br /><br />
	<img class="job_pic" src="/images/icons/BI/Ph43319.jpg" width="100" height="100" border="0" alt="Teacher's Aide/Paraprofessional" />
	<span class="header3">Job Description</span>
	<blockquote>Not everyone who works at a school is a teacher. The job of a teacher's aide is similar to that of a teacher. As a teacher's aide, you would help a teacher care for his/her students, grade papers, perform clerical duties, and prepare instructional materials.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree or at least some higher-level education courses for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average wage is about $8.29 to $8.77 an hour.</blockquote>

<hr size="1" />

<span class="header1">CREATIVE HELPING</span>
<p>If you want to help others and are creative, the occupations in this field may be appropriate for you. The goal of these occupations is to help others reach a goal. Let's look at three occupations that may interest you.</p>

<hr size="1" />

	<span class="header2">Psychologist</span><br /><br />
	<img class="job_pic" src="/images/icons/BI/43119.jpg" width="100" height="100" border="0" alt="Psychologist" />
	<span class="header3">Job Description</span>
	<blockquote>There are different kinds of psychologists.  Some focus on testing students. These are educational psychologists who might test a student's IQ, or to see if a student has a learning disability. Some psychologists focus on helping people who are having psychological problems. These are clinical psychologists who help their clients to talk about and work through any problems they may be having. Then they work with the person to develop a plan that will help solve the problems. If you were either kind of psychologist, you could work in private practice, either on your own or in a small group. You could also work in a school, hospital, or treatment center.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Ph.D. to earn respect in this occupation.  This is a job where formal education is very important.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary ranges from $30,000 to $150,000+.</blockquote>

<hr size="1" />

	<span class="header2">Interior Designer</span><br /><br />
	<img class="job_pic" src="/images/icons/BI/43032.jpg" width="100" height="100" border="0" alt="Interior Designer" />
	<span class="header3">Job Description</span>
	<blockquote>If you have a skill for making a room look its best, you might become an interior designer. Interior designers help their clients decorate the inside of homes, offices, and businesses.  In this job, you would decorate rooms working within a budget. To do this, you would have to know the best prices on furniture, drapes, and other room accessories.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need to complete a three to four-year program in interior designing.  You must also be a member of a professional association to find a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>An interior designer may make from $21,000 to $70,000 a year. The salary depends on the company and the designer's reputation.</blockquote>

<hr size="1" />

	<span class="header2">Retail Salesperson</span><br /><br />
	<img class="job_pic" src="/images/icons/BI/1302.jpg" width="100" height="100" border="0" alt="Retail Salesperson" />
	<span class="header3">Job Description</span>
	<blockquote>A retail salesperson answers questions that customers ask and helps them decide what to buy.  As a retail salesperson, you would "ring up" the sale on a cash register or computer.  You would search for items that customers asked for.  You would also restock the shelves as needed. Other duties might include closing the cash register at the end of a shift and keeping the store neat.  Sometimes you will need to be pleasant with people even when they seem to be demanding.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You do not need a Bachelor's Degree for this job.  But you may need background knowledge if you take a technical sales position.  For example, an electronics store would hire a person who knew as much as possible about sound systems, telephones, and VCR's.  Retail companies provide on-the-job training to teach sales people how to run a register.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary may range from $16,000 to $36,000 per year.</blockquote>

<hr size="1" />

<span class="header1">CREATIVE PERFORMANCE</span>
<p>To enter  occupations in this field, you need talent and the courage to perform. It takes hard work and determination to succeed in the field of creative performance. Here are three occupations that might interest you.</p>

<hr size="1" />

	<span class="header2">Screenwriter</span><br /><br />
	<img class="job_pic" src="/images/icons/BI/43336.jpg" width="100" height="100" border="0" alt="Screenwriter">
	<span class="header3">Job Description</span>
	<blockquote>A screenwriter does not perform on stage, but his/her work is still important. As a screenwriter, you would write plays that are seen in movies and television programs. You would search for interesting topics and write scripts and screenplays based on these. You would work closely with producers and directors.  You might even work with other writers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Writers usually have at least a Bachelor's Degree.  They must also have writing skills.  Experience is also important. Competition for screenwriting jobs is intense. Only a few screenwriters are able to earn a living writing for movies or television.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Since so few screenplays are performed, salaries range from $0 to $100,000+. Only a few screenwriters earn large sums.</blockquote>

<hr size="1" />

	<span class="header2">Chef</span><br /><br />
	<img class="job_pic" src="/images/icons/BI/43009.jpg" width="100" height="100" border="0" alt="Chef" />
	<span class="header3">Job Description</span>
	<blockquote>If you became a chef, you would use your creativity to prepare new kinds of dishes or meals for others to eat. You would work in a kitchen creating new recipes, preparing the meals, and overseeing the staff. Creativity is important to a chef.</blockquote>
	<span class="header3">Education</span>
	<blockquote>No college degree is needed. Most chefs learn their craft at schools called "culinary institutes." Chefs who do not train at a culinary institute are put through a tough on-the-job training program while working in a kitchen at another job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A yearly salary for a chef ranges from $19,000 to $75,000.</blockquote>

<hr size="1" />

	<span class="header2">Musician</span><br /><br />
	<img class="job_pic" src="/images/icons/BI/C1926_03.jpg" width="100" height="100" border="0" alt="Musician" />
	<span class="header3">Job Description</span>
	<blockquote>A musician is someone who plays an instrument or sings. As a musician, you would perform in front of other people. Most musicians practice and work with other musicians.  To succeed as a musician, you must be creative and have musical talent. You must also be able to work with others, as few musicians play music alone.  In addition, you will want to understand business.  Many musicians are expected to manage their own careers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You will need lessons to learn how to play an instrument.  But the amount of education you need depends on the type of music you play.  If you play traditional or classical music, you will need more formal education. If you play rock, country, or rap music, experience is your best teacher.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary for a musician can vary greatly. Some musicians earn millions a year while others work another job in order to make a living. The music business is tough and very few "make it big."</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
