<span class="header1">Business/Management paired with Clerical/Administrative (CD)</span>

<p>If you had a high score in categories "C" and "D" you have a head for business. You are a good thinker and know how to get what you want. You are probably goal-oriented and prefer to know what you are working toward.  You may be an outgoing person who likes to lead, or you may be a quiet person who likes working with numbers. Either way, you know how get the job done. You will benefit from learning to understand business.</p>
<p>Most occupations in this pairing require a Bachelor's Degree.  Many others require some post-high school courses.  In most of the occupations listed under this pairing, the more education you have the better your chances of employment. The competition for these jobs is tough. You will need to give yourself every advantage possible.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">CD Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Business Sales</span><br /><br />
						<em>Computer Sales Representative<br /><br />
						Business Machine Sales Representative<br /><br />
						Insurance Sales Agent<br /><br />
						Real Estate Agent/Broker<br /><br />
						Personnel Consultant<br /><br />
						Analyst
							<ul>
								<li>Marketing</li>
								<li>Stock</li>
							</ul>
						Sales Account Supervisor<br /><br />
						Travel Agent<br /><br />
						Sales Support<br /><br />
						Cashier</em>
					</td>
					<td width="33%">
						<span class="header2">Business Administrative</span><br /><br />
						<em>Personnel Director<br /><br />
						Human Resources Manager<br /><br />
						Data Processing Manager<br /><br />
						Facilities Manager<br /><br />
						Office Manager<br /><br />
						Retail Buyer<br /><br />
						Employee Benefits Manager<br /><br />
						Executive Secretary<br /><br />
						Underwriter<br /><br />
						Stock Transfer Clerk<br /><br />
						Personnel Clerk</em>
					</td>
					<td width="33%">
						<span class="header2">Business Financial</span><br /><br />
						<em>Chief Financial Officer<br /><br />
						Statistician<br /><br />
						Economic Researcher<br /><br />
						Financial Planner<br /><br />
						Bank Loan Officer<br /><br />
						Auditor<br /><br />
						Bookkeeper<br /><br />
						Tax Preparer<br /><br />
						Clerk
							<ul>
								<li>Accounting</li>
								<li>Statistical</li>
							</ul>
						Bank Teller</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">BUSINESS SALES</span>
<p>People who do well in this occupations are self-starters and can be responsible for their own schedule.  In addition, they like meeting new people.  If this describes you, consider the occupations in this field.</p>

<hr size="1" />

	<span class="header2">Insurance Agent</span><br /><br />
	<img class="job_pic" src="/images/icons/CD/C506005.jpg" width="100" height="100" border="0" alt="Insurance Agent" />
	<span class="header3">Job Description</span>
	<blockquote>An insurance agent sells and services insurance policies.  People buy insurance for their homes, cars, and even health.  It protects them from losing a lot of money if something happens to their possessions or themselves.  But choosing the right insurance can be difficult.  As an insurance agent, you would help people decide what type of insurance policy they need. You would also help them to file a claim to collect money on their policy when necessary.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Some companies insist on a Bachelor's Degree in economics or business. But many companies don't. Instead, they provide on-the-job training. A state license is required.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>An insurance agent is paid on commission. This means that he/she is paid based on the number and price of the insurance policies sold.</blockquote>

<hr size="1" />

	<span class="header2">Travel Agent</span><br /><br />
	<img class="job_pic" src="/images/icons/CD/1216.jpg" width="100" height="100" border="0" alt="Travel Agent">
	<span class="header3">Job Description</span>
	<blockquote>When people go on trips, they often make transportation and hotel reservations. A travel agent is important to a traveler. If you were a travel agent, you would work very closely with the public making arrangements for vacations or business trips. You might work for a hotel or an airline. A good agent must be able to work well with people and understand the needs of a traveler.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.  You also need to know how to use a computer.  Geography and history will be important.  Many of the places that people visit are studied in these courses.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly average income of a reservation agent is $26,000.</blockquote>

<hr size="1" />

	<span class="header2">Cashier</span><br /><br />
	<img class="job_pic" src="/images/icons/CD/1142.jpg" width="100" height="100" border="0" alt="Cashier">
	<span class="header3">Job Description</span>
	<blockquote>A cashier takes the money of customers who want to buy something from a store.  As a cashier, you would ring up the items the customer wanted to buy. You would handle cash, checks and credit and debit card purchases. It would be important that the amount of money in the cash drawer matched the amount on the receipts in the machine.</blockquote>
	<span class="header3">Education</span>
	<blockquote>If you were a cashier, you would be given on-the-job training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Many cashier jobs pay minimum wage. Some pay as much as $20,000 a year.</blockquote>

<hr size="1" />

<span class="header1">BUSINESS ADMINISTRATION</span>
<p>In the occupations in this field, you would make sure that others did their jobs correctly, and that the business actions ran smoothly. If you enjoy overseeing the work of others, consider the occupations in this field.  Here are three examples.</p>

<hr size="1" />

	<span class="header2">Human Resources Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CD/1372.jpg" width="100" height="100" border="0" alt="Human Resource Manager">
	<span class="header3">Job Description</span>
	<blockquote>A human resources manager helps to develop and carry out a company's "people" policies.  He/she serves as a link between employees and upper management. As a human resources manager, you might hire or fire employees.  You might also write job descriptions and train new employees.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree for this job.  This degree should be in human resources management.  It could also be in personnel administration.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $36,000 to $114,000+.  Salary depends on experience and education.</blockquote>

<hr size="1" />

	<span class="header2">Employee Benefits Manager</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Companies often provide their employees with benefits such as paid vacation time and health insurance. These are called employee benefits.  An employee benefits manager helps employees to understand their benefits. She/he also helps them to use these benefits to their advantage. As an employee benefits manager, you would need to be well organized. You would also need to enjoy working with people.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You would need at least a Bachelor's Degree for this job.  It is important to take courses in insurance, business management, and finance.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $36,000 to $114,000+.</blockquote>

<hr size="1" />

	<span class="header2">Personnel Clerk</span><br /><br />
	<img class="job_pic" src="/images/icons/CD/43328.jpg" width="100" height="100" border="0" alt="Personnel Clerk">
	<span class="header3">Job Description</span>
	<blockquote>Companies keep information about each of their employees on file.  This information includes each employee's job application. It includes information about any job evaluations as well. As a personnel clerk, you would keep employee files up to date and secure. You would use a computer to do this.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.  You need a Bachelor's Degree if you plan to stay with the company and be promoted.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average salary is $30,000 a year.</blockquote>

<hr size="1" />

<span class="header1">BUSINESS FINANCIAL</span>
<p>People who do well in the occupations in this field enjoy working with money. They also are good organizers and can keep track of details.</p>

<hr size="1" />

	<span class="header2">Loan Officer</span><br /><br />
	<img class="job_pic" src="/images/icons/CD/C506008.jpg" width="100" height="100" border="0" alt="Loan Officer">
	<span class="header3">Job Description</span>
	<blockquote>A loan officer works for a bank or lending company. As a loan officer, you help customers fill out loan applications and make sure that the information on the application is correct. You would then see if the people wanting the loan met your company's guidelines for a loan. If so, you would help to process the loan.  If not, you would help them to understand why they did not get the loan.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree for this job.  Some banks and lending companies only hire those with a Master's Degree in business administration.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary range for a loan officer is $26,000 to $89,000 per year.</blockquote>

<hr size="1" />

	<span class="header2">Bookkeeper</span><br /><br />
	<img class="job_pic" src="/images/icons/CD/1287.jpg" width="100" height="100" border="0" alt="Bookkeeper">
	<span class="header3">Job Description</span>
	<blockquote>All companies must keep detailed records of their cash flow and how much money they earn. As a bookkeeper, you would be responsible for keeping this information. You would have to enjoy working with numbers and be good at keeping track of details to do this job well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job. Most companies offer on-the-job training. Courses in business math and computer science from a vocational school can help you to get a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $19,000 to $30,000.</blockquote>

<hr size="1" />

	<span class="header2">Bank Teller</span><br /><br />
	<img class="job_pic" src="/images/icons/CD/1371.jpg" width="100" height="100" border="0" alt="Bank Teller">
	<span class="header3">Job Description</span>
	<blockquote>A bank teller handles large sums of money. As a bank teller, you would help customers with their deposits and withdrawals. Banks look for people who work well with customers, have good math skills, and know the importance of keeping detailed records.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A high school diploma is needed to be a bank teller. A teller is given on-the-job training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A bank teller earns $9,000 to $24,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
