<span class="header1">Business/Management paired with Technology (CF)</span>

<p>With an "CF" interest, you will be a valuable employee. You like working with people on projects or assignments that have to do with biotechnology, information systems, engineering and environmental in the technology industries. The field of business is becoming more technical and fast-paced. This means that you will have many opportunities to find the occupation that suits you. You will be happiest in an occupation that allows you to use your ability to understand how things work and gives you a chance to make important transactions.</p>
<p>Many of the occupations in this pairing require some sort of specialized and/or technical training after high school. Some require college degrees or college level courses.</p>

<p><strong>Here are some career possibilities for you to explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">CF Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Business & Community Service</span><br /><br />
						<em>Athletic Director<br /><br />
						Safety Engineer<br /><br />
						Police Chief<br /><br />
						Sheriff<br /><br />
						Deputy Sheriff<br /><br />
						Youth services Director<br /><br />
						Fitness Club Manager<br /><br />
						Aircraft Sales Representative<br /><br />
						Professional Athlete<br /><br />
						Real Estate Agent<br /><br />
						Machinist<br /><br />
						Corrections Officer<br /><br />
						Cleaning Service Owner</em>
					</td>
					<td width="33%">
						<span class="header2">Business & Environment</span><br /><br />
						<em>Environmental Risk Manager<br /><br />
						Land Acquisition Professional<br /><br />
						Solid Waste Management<br /><br />
						Environmental Protection Specialist<br /><br />
						Environmental Project Manager<br /><br />
						Fire Chief<br /><br />
						Park Ranger<br /><br />
						Park & Recreation Manager<br /><br />
						Forestry Technician<br /><br />
						Firefighter<br /><br />
						Rancher<br /><br />
						Logging Supervisor</em>
					</td>
					<td width="33%">
						<span class="header2">Business & Technology</span><br /><br />
						<em>Information Manager<br /><br />
						Computer Specialist<br /><br />
						Database Manager<br /><br />
						Air Traffic Controller<br /><br />
						Construction Manager<br /><br />
						Building Contractor<br /><br />
						Computer Sales Representative<br /><br />
						Software Sales Representative<br /><br />
						Computer Engineer<br /><br />
						Industrial Production Manager<br /><br />
						Computer Store Manager<br /><br />
						Public Service Technician<br /><br />
						Truck Driver</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">BUSINESS & COMMUNITY SERVICE</span>
<p>If you worked within this occupational field, a community or business would hire you. These occupations are physically demanding. To enjoy them, you must like adventure.</p>

<hr size="1" />

	<span class="header2">Sheriff</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A sheriff is very much like a police officer. Usually a sheriff works for a small town, community, or county that cannot afford a police force. If you were a sheriff, you would keep the community safe. You might direct traffic, settle arguments, and investigate crimes. Also, you would schedule and oversee any deputy sheriffs who worked for the same community.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma for this job.  Many communities or towns want someone with a college education or years of experience in law enforcement. Most sheriffs must pass a written exam. They must also meet some physical requirements.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary of a sheriff depends on how much money the community can afford to pay. Some communities pay as little as $25,000.  Others may pay as much as $65,000.</blockquote>

<hr size="1" />

	<span class="header2">Deputy Sheriff</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a deputy sheriff, you would help the sheriff enforce the laws of a small town that has no police department. Your duties might include directing traffic, writing tickets, settling arguments, and investigating crimes. You would perform many of the same duties as the sheriff, but you would not manage other employees.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma for this job.  Many communities or towns want someone with a college education or years of experience in law enforcement. Most deputy sheriffs must pass a written exam. They must also meet some physical requirements.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary of a deputy sheriff depends on how much money the community can afford to pay. Some communities pay as little as $25,000. Others may pay as much as $65,000.</blockquote>

<hr size="1" />

	<span class="header2">Corrections Officer</span><br /><br />
	<img class="job_pic" src="/images/icons/CF/so000174.jpg" width="100" height="100" border="0" alt="Corrections Officer" />
	<span class="header3">Job Description</span>
	<blockquote>A corrections officer works in a jail or prison. As a corrections officer, you would make sure that prisoners were safe. You would also see that they followed the rules of the prison and did not escape. You would search cells for items that the prisoners should not have and report any arguments or fights.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most law enforcement officers need a high school diploma or pass an equivalency test. Some counties or states prefer those who have taken college courses. Corrections officers cannot have a criminal record. They must have a driver's license, and must be at least 18 years old.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary range is $22,000 to $55,000.</blockquote>

<hr size="1" />

<span class="header1">BUSINESS & ENVIRONMENT</span>
<p>The occupations in this field protect, manage, or research the environment. If the environment is one of your interests, you might want to consider the occupations in this field. Here are three examples.</p>

<hr size="1" />

	<span class="header2">Solid Waste Manager</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>If you want to protect the environment, you might become a solid waste manager. In this job, you would look for the best ways to collect, move, store, and dispose of solid waste. For example, you might make sure that styrofoam cups and other household trash were discarded in a place that would cause as little harm as possible to the environment.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in a technical field for this job.  Your degree might be in engineering, geology, chemistry, or a related area.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary is from $21,000 to $45,000+.</blockquote>

<hr size="1" />

	<span class="header2">Park Ranger</span><br /><br />
	<img class="job_pic" src="/images/icons/CF/C585042.jpg" width="100" height="100" border="0" alt="Park Ranger" />
	<span class="header3">Job Description</span>
	<blockquote>A park ranger makes sure that visitors and wildlife are safe in state and national parks. As a park ranger, you would patrol the park.  You would also collect fees, provide information about the park, and enforce park rules and regulations.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least 2 years of college courses in science and law enforcement to become a park ranger.  Many of the jobs with the U.S. Forest Service require a ranger to have a Bachelor's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive as a park ranger is based on your education and experience.  It can range from $30,000 to $73,000+.</blockquote>

<hr size="1" />

	<span class="header2">Forestry Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/CF/43168.jpg" width="100" height="100" border="0" alt="Forestry Technician" />
	<span class="header3">Job Description</span>
	<blockquote>If you want to work outdoors, you might become a forestry technician. In this job, you would help a forester oversee logging and tree planting.  You would also help him or her with water regulation and wildlife management. In addition, you might collect information for people who want to know how to protect the forest.  You might also oversee work crews and survey the forest for road construction.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least an Associate's Degree for this job.  Some states require that you take a test and become registered.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary runs from $15,000 to $30,000.</blockquote>

<hr size="1" />

<span class="header1">BUSINESS & TECHNOLOGY</span>
<p>Technology is becoming more and more important in running an office.  The occupations in this field need people who know how business machines and equipment work. If you enjoy working with equipment or machines, this field may be for you.</p>

<hr size="1" />

	<span class="header2">Information Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CF/43334.jpg" width="100" height="100" border="0" alt="Information Manager" />
	<span class="header3">Job Description</span>
	<blockquote>You may have heard the saying that we live in an "Information Age." This means that getting information from one place to another is very important. An information manager makes sure that people within a company can do this. People who work in the same location must be able to communicate with each other.  They must also be able to communicate with people in company offices in different cities.  To do this job well, you must know as much as possible about telephones and computers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You would need at least a Bachelor's Degree for this job.  Many employers require a Master's Degree.  To teach others in information management, you must have a Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $40,000.</blockquote>

<hr size="1" />

	<span class="header2">Computer Engineer</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Businesses are always looking for a new way to make their offices run smoother. A computer engineer helps businesses do this. As a computer engineer, you would look for ways to make a business' day-to-day tasks easier. You would make suggestions on which computer systems would be best for the company. You would also help the company come up with new ways to route information. To be a good computer engineer, you must a lot about computers and be able to work with different types of people.  People who do this job are also called computer systems analysts.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job. It is also helpful to have taken courses in computer science, technology and programming.  Experience with computers will help you to get a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $40,000 to $95,000+.</blockquote>

<hr size="1" />

	<span class="header2">Computer Service Technician</span><br /><br />
	<!-- <img class="job_pic" src="/images/icons/CF/1234.jpg" width="100" height="100" border="0" alt="Computer Service Technician" /> -->
	<span class="header3">Job Description</span>
	<blockquote>Computers are very important to our society and will continue to be in the future. If you like knowing what makes computers work and want to keep them running, you might become a computer service technician. In this job, you figure out why a computer isn't working and fix it.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma and courses in electronics for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $40,000 to $68,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
