<span class="header1">Business/Management paired with Science/Mathematics (CH)</span>

<p>If your scores on this pairing were high, you naturally understand that there are always ways to improve a situation. You can probably handle several tasks at one time. People like you have made important contributions in business. You are an excellent thinker.  You are also likely to be a no-nonsense kind of person. You are mentally creative and like to ask the question, "Why?" Because of this, you will look for new business ventures.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree or some post high school courses. For some jobs, it may be valuable to have a Master's Degree or a Ph.D.</p>

<p><strong>Here are some career possibilities for you to explore:</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">CH Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="25%">
						<span class="header2">Finance</span><br /><br />
						<em>Chief Financial Officer<br /><br />
						Financial Advisor<br /><br />
						Accountant<br /><br />
						Auditor
							<ul>
								<li>Bank</li>
								<li>Federal Reserve</li>
							</ul>
						Stockbroker<br /><br />
						Statistician<br /><br />
						Loan Officer<br /><br />
						Accounting Clerk<br /><br />
						Cashier</em>
					</td>
					<td width="25%">
						<span class="header2">Medical</span><br /><br />
						<em>Public Health Administrator<br /><br />
						Physician<br /><br />
						Hospital Administrator<br /><br />
						Epidemiologist<br /><br />
						Medical Officer<br /><br />
						Nursing Home Director<br /><br />
						Pharmacist<br /><br />
						Optician<br /><br />
						Patient Representative</em>
					</td>
					<td width="25%">
						<span class="header2">Analysis/Research</span><br /><br />
						<em>Economist<br /><br />
						Marketing Director<br /><br />
						Entrepreneur<br /><br />
						Financial Analyst<br /><br />
						Market Researcher<br /><br />
						Insurance Planner & Analyst<br /><br />
						Medical Economist<br /><br />
						Computer Systems Analyst</em>
					</td>
					<td width="25%">
						<span class="header2">Nature</span><br /><br />
						<em>Zoo Administrator<br /><br />
						Science Museum Director<br /><br />
						Historic Preservationist<br /><br />
						Fishery Manager/Technician<br /><br />
						Wildlife Manager/Technician<br /><br />
						Refuge Manager<br /><br />
						Lobbyist<br /><br />
						Grass Roots Coordinator<br /><br />
						Fund Raiser<br /><br />
						Real Estate Developer<br /><br />
						Nursery Manager</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">FINANCE</span>
<p>The occupations in this field are for people who are able to investigate and are good at numbers. If you would like to work with finances, these occupations might be for you.</p>

<hr size="1" />

	<span class="header2">Accountant</span><br /><br />
	<img class="job_pic" src="/images/icons/CH/1287.jpg" width="100" height="100" border="0" alt="Accountant" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy working with numbers, you might become an accountant. An accountant is responsible for helping a company make money. You might advise the company to buy or sell stock, or you might prepare its taxes.  You would also keep careful records so that it was possible to tell how much money the company made and where this money was spent.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree for an entry level job. Most accountants are CPA's (Certified Public Accountants). To become a CPA, you must have a Bachelor's Degree. You must also pass a written exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A CPA makes $30,000 to $82,000+ per year.</blockquote>

<hr size="1" />

	<span class="header2">Statistician</span><br /><br />
	<img class="job_pic" src="/images/icons/CH/C1618_03.jpg" width="100" height="100" border="0" alt="Statistician" />
	<span class="header3">Job Description</span>
	<blockquote>As a statistician, you would gather information in numbers. For example, Major League Baseball players have their batting averages determined by statisticians. If you worked in a business, you would look at certain numbers to see how well the company was doing.  Is it in good shape? Numbers give the statistician the answer.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree in statistics or mathematics for this job.  To get a promotion, you must have a Master's Degree or a Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average salary for a statistician is $57,000.</blockquote>

<hr size="1" />

	<span class="header2">Loan Officer</span><br /><br />
	<img class="job_pic" src="/images/icons/CH/C506008.jpg" width="100" height="100" border="0" alt="Loan Officer" />
	<span class="header3">Job Description</span>
	<blockquote>A loan officer works for a bank or lending company. As a loan officer, you would help customers fill out loan applications and make sure that the information on the application is correct. You would then see if the people wanting the loan met your company's guidelines for a loan. If so, you would help to process the loan.  If not, you would help them to understand why they did not get the loan.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree for this job.  Some banks and lending companies only hire those with a Master's Degree in business administration.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary range for a loan officer is $25,000 to $88,000 per year.</blockquote>

<hr size="1" />

<span class="header1">MEDICAL</span>
<p>Health care is one area where business and science blend well. The occupations in this field need people who are interested in the physical well-being of others.</p>

<hr size="1" />

	<span class="header2">Public Health Administrator</span><br /><br />
	<img class="job_pic" src="/images/icons/CH/C506006.jpg" width="100" height="100" border="0" alt="Public Health Administrator" />
	<span class="header3">Job Description</span>
	<blockquote>Because many illnesses can be passed to others, it is important to have people who help to guard against widespread illnesses. This person is a public health administrator. In this job, you would oversee the health care programs of a county or city.  You would make sure that the hospitals, clinics, and health departments follow the rules set by the state or local government.</blockquote>
	<span class="header3">Education</span>
	<blockquote>All people who work as health care administrators must have a Master's Degree. Some health care administrators have degrees in public health. Others have a degree in public administration.  Still others have a degree in business administration.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $37,000 to $100,000+.</blockquote>

<hr size="1" />

	<span class="header2">Nursing Home Director</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a nursing home director, you would make sure that the building and equipment are kept in good condition.  You would also make sure that the elderly people who live in the home are well cared for. An important part of your duties would be to oversee the employees who care for the elderly. Another important duty is to run the home so that it earns a profit.</blockquote>
	<span class="header3">Education</span>
	<blockquote>All people who work as health care administrators must have a Master's Degree. Some health care administrators have degrees in public health.  Others have a degree in public administration.  Still others have a degree in business administration.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary ranges from $55,000 to $100,000+.</blockquote>

<hr size="1" />

	<span class="header2">Patient Representative</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>If you like to make sure others are treated well, you might become a patient representative. In this job, you would act as a go-between for the hospital and its employees and patients. For example, if a patient felt he/she was being treated poorly or unfairly, you would step in to help. You would talk with employees and the patient.  Then you would work out the best plan for getting appropriate care for the patient.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma for this job. More and more people with Bachelor's Degrees are going into this occupation.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary ranges from $15,000 to $51,000.</blockquote>

<hr size="1" />

<span class="header1">ANALYSIS/RESEARCH</span>
<p>In this field, employees need to understand how to make money and how to do business. If you chose to work in this field, you would study how business is practiced and what companies must do to make money.</p>

<hr size="1" />

	<span class="header2">Economist</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy finding clues and drawing conclusions, you might become an economist. An economist looks at trends in business and predicts what will happen. For example, you might study the oil business and decide whether the price of gasoline will be going up or down. You would probably like this job if you are naturally curious and enjoy a challenge.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Master's Degree for this job. Many employers will want you to have a Ph.D. Education is very important.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary ranges from $40,000 to $128,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Market Researcher</span><br /><br />
	<img class="job_pic" src="/images/icons/CH/43326.jpg" width="100" height="100" border="0" alt="Market Researcher" />
	<span class="header3">Job Description</span>
	<blockquote>A market researcher works for a company that makes a product sold to the public. As a researcher, you might work for a toy manufacturer or a retail store. You would collect information about what customers want to buy and give your results to the company.  If you are curious and understand business, this might be a good job for you.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree for this job.  Market researchers start out in entry-level jobs, then they are promoted to this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $29,000 to $100,000.</blockquote>

<hr size="1" />

	<span class="header2">Computer Systems Analyst</span><br /><br />
	<img class="job_pic" src="/images/icons/CH/43166.jpg" width="100" height="100" border="0" alt="Computer Systems Analyst" />
	<span class="header3">Job Description</span>
	<blockquote>Businesses are always looking for a new way to make their offices run smoothly. A computer systems analyst looks for ways to make the day-to-day tasks of a business easier. You would make suggestions on which computer systems would be best for the company. You would also help the company come up with new ways to route information.  To be a good computer systems analyst, you must know a lot about computers and be able to work with different types of people.  People who do this job are also called computer engineers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job. It is also helpful to have taken courses in computer science, technology and programming.  Experience with computers will help you to get a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $39,000 to $93,000.</blockquote>

<hr size="1" />

<span class="header1">NATURE</span>
<p>If you enjoy nature or are concerned about the environment, this occupational field may be for you.  People who work in this field enjoy life sciences and understand business.</p>

<hr size="1" />

	<span class="header2">Life Science Museum Director</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy helping others know about the environment and nature, you might become a life science museum director.  In this job, you would plan and oversee the daily routine of a museum. You would manage employees and keep the building in good repair. Most directors start out as a museum curator.  Later, they are promoted the director's job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You must have a Master's Degree to become a museum director. Many directors have their Ph.D.  Employers look for directors who have plenty of experience in the museum business.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $100,000+.</blockquote>

<hr size="1" />

	<span class="header2">Wildlife Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CH/1270.jpg" width="100" height="100" border="0" alt="Wildlife Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Wildlife managers look for ways to protect wild animals and their habitats.  As a wildlife manager, you would do more than look after the well-being of individual animals.  You would care for their homes as well.  You would monitor the plants, water, and soil of the area to be sure they could sustain the animals.  If you found a problem, you would work to solve it.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Competition for these jobs is intense.  You need at least a Master's Degree. The more education and experience you have in caring for wild animals and their habitats, the more likely you are to get a job. Your leisure activities and part-time jobs can help you to gain experience.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Wildlife managers earn between $21,000 to $80,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Grass Roots Coordinator</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A grass roots coordinator oversees the activities of a group of people who are working to protect or restore the environment.  As a grass roots coordinator, you might work for a national organization,  but you would live and work in a county or town. You would help protect the environment or animals in the wild. To do this job well, you must feel strongly about protecting the environment.  You must also be able to motivate people to work toward your cause.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are no formal requirements to become a grass roots coordinator, but there are some college-level courses that are valuable, inluding business,communications, biological sciences, and political science. What is most important is that you have a strong commitment to the environmental cause that you coordinate.  You must also have the knowledge needed to do the job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Many coordinators have another job. The yearly salary is very low.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
