<span class="header1">Business/Management paired with Social Helping (CI)</span>

<p>Your high scores in "C" and "I" show that that you have several characteristics that can help you to be useful to people. You are a creative, outgoing, and talented person. You like to offer support to people who are having difficulties. You also know that working hard is important. No matter what you choose to do, you will want to know you are helping people.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree.  It is helpful to have a Master's Degree or a Ph.D. in some of the occupations.</p>

<p><strong>Here are some career possibilities for you to explore.</strong><p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">CI Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Social Helping</span><br /><br />
						<em>Religious Activities Director<br /><br />
						Health Services Administrator<br /><br />
						Clergy<br /><br />
						Occupational Social Worker<br /><br />
						Public Health Social Worker<br /><br />
						Adult Education Teacher (Business Courses)<br /><br />
						Human Services Worker<br /><br />
						Homeless Shelter Director<br /><br />
						Parole Officer<br /><br />
						Home Health Aide</em>
					</td>
					<td width="33%">
						<span class="header2">Business Helping</span><br /><br />
						<em>Personnel Consultant<br /><br />
						Corporate Trainer<br /><br />
						Employment Interviewer<br /><br />
						Property Manager<br /><br />
						Real Estate Agent<br /><br />
						Insurance Agent<br /><br />
						Sales Occupation<br /><br />
						Service Occupation<br /><br />
						Bank Teller<br /><br />
						Receptionist<br /><br />
						Computer Salesperson<br /><br />
						Retail Salesperson</em>
					</td>
					<td width="33%">
						<span class="header2">Business Management</span><br /><br />
						<em>Hospital Administrator<br /><br />
						Financial Planner<br /><br />
						Geriatric Care Manager<br /><br />
						Human Resources Manager<br /><br />
						Funeral Director<br /><br />
						Hotel Manager<br /><br />
						Benefits Administrator<br /><br />
						Retirement Manager<br /><br />
						Restaurant Manager<br /><br />
						Travel Agency Manager</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">SOCIAL HELPING</span>
<p>Occupations in this field allow you to help others. They also allow you to use your business and management skills.  Most of the occupations are associated with social work.</p>

<hr size="1" />

	<span class="header2">Public Health Social Worker</span><br /><br />
	<img class="job_pic" src="/images/icons/CI/1212.jpg" width="100" height="100" border="0" alt="Public Health Social Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Social work is about helping. As a public health social worker, you would interview a family and others who know them. You would be looking for information that would allow you to improve the family's health and well being. You would complete paperwork documenting what you found and did.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become an entry-level social worker. Those with more responsible positions must have a Master's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $23,000 to $56,000.</blockquote>

<hr size="1" />

	<span class="header2">Occupational Social Worker</span><br /><br />
	<img class="job_pic" src="/images/icons/CI/7240.jpg" width="100" height="100" border="0" alt="Occupational Social Worker" />
	<span class="header3">Job Description</span>
	<blockquote>An occupational social worker usually works for a large company. In this job, you would work in the personnel department. Your job would be to help employees to cope with the stresses of working. To do this, you would listen closely to the employee. Then you would work with him/her to get help or solve a problem.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become an entry-level social worker. Those with more responsible positions must have a master's degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $23,000 to $56,000.</blockquote>

<hr size="1" />

	<span class="header2">Human Services Social Worker</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a human services social worker, you would work under a doctor, nurse, or psychiatrist. You would help these health care professionals find ways to help the patient. For example, you might find a way for the patient to get to his/her doctor's appointment. Your duties would depend on what the patient needed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become an entry-level social worker. Those with more responsible positions must have a master's degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $23,000 to $56,000.</blockquote>

<hr size="1" />

<span class="header1">BUSINESS HELPING</span>
<p>In this field you would need to have an outgoing personality.  You would also need to enjoy meeting new people. The occupations in this field allow you to provide a service to customers.</p>

<hr size="1" />

	<span class="header2">Property Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CI/1319.jpg" width="100" height="100" border="0" alt="Property Manager" />
	<span class="header3">Job Description</span>
	<blockquote>Property is land that has value. The property may have  building or buildings on it. If you were a property manager, you would be responsible for the day-to-day running of a property. You might run an office or apartment complex, or a retail building. Your duties might include making rental agreements, collecting rent, and hiring employees to maintain the grounds.</blockquote>
	<span class="header3">Education</span>
	<blockquote>This job requires that you have a Bachelor's Degree in finance or business administration.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $17,000 to $86,000+.</blockquote>

<hr size="1" />

	<span class="header2">Real Estate Agent</span><br /><br />
	<img class="job_pic" src="/images/icons/CI/C526017.jpg" width="100" height="100" border="0" alt="Real Estate Agent" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy working with people and want to help them buy a house or land, you might become a real estate agent. As a real estate agent, you would work with people who want to sell their homes, and you would show these homes to others. You would help people who want to buy a home to get a loan. You would need to be independent and a good problem solver.  You also need to be able to communicate well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma to be a real estate agent. More and more employers want you to have a Bachelor's Degree.  Real estate agents must be licensed in the state in which they work.  To get this license, you must take courses in real estate law and pass an exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A real estate agent is paid on "commission." This means that the agent is paid a percentage of the selling price of the property.</blockquote>

<hr size="1" />

	<span class="header2">Bank Teller</span><br /><br />
	<img class="job_pic" src="/images/icons/CI/1371.jpg" width="100" height="100" border="0" alt="Bank Teller" />
	<span class="header3">Job Description</span>
	<blockquote>A bank teller handles large sums of money. As a bank teller, you would help customers with their deposits and withdrawals. Banks look for people who work well with customers, have good math skills, and know the importance of keeping detailed records.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A high school diploma is needed to be a bank teller. A teller is given on-the-job training.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A bank teller earns $9,000 to $24,000.</blockquote>

<hr size="1" />

<span class="header1">BUSINESS MANAGEMENT</span>
<p>The occupations in this field require you to oversee others as they are doing their jobs. You need to be good with people and know how to handle business.</p>

<hr size="1" />

	<span class="header2">Funeral Director</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A funeral director helps a family make funeral plans when a family member who has died. If you were a funeral director, you would handle the details of the funeral service and burial. You would put a notice in the newspaper. You would also order flowers and contact people to speak at the funeral.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A funeral director must have a high school diploma and post high school courses in mortuary sciences. He/she must also be 21 years of age. It is necessary to be licensed by the state as well.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $40,000 to $62,000+.</blockquote>

<hr size="1" />

	<span class="header2">Hotel General Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CI/43096.jpg" width="100" height="100" border="0" alt="Hotel General Manager" />
	<span class="header3">Job Description</span>
	<blockquote>The person who runs a hotel is called a hotel manager. As a hotel manager, you would be responsible for making sure the guests are comfortable during their stay. One of the most important duties you would have is to make sure that the employees are doing their jobs.  You would need to make sure that the hotel makes a profit.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in hotel and restaurant management for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The salary ranges from $35,000 to $80,000+ a year.</blockquote>

<hr size="1" />

	<span class="header2">Restaurant Manager</span><br /><br />
	<img class="job_pic" src="/images/icons/CI/43111.jpg" width="100" height="100" border="0" alt="Restaurant Manager" />
	<span class="header3">Job Description</span>
	<blockquote>A restaurant is a very busy place. There are many different activities going on at the same time. The person who is responsible for making sure that the restaurant runs smoothly is the manager. As a restaurant manager, you would oversee the daily operations of a restaurant. You would hire employees, and oversee the inventory of food and supplies. You would make sure that the food served was prepared well and that the customers enjoyed themselves.</blockquote>
	<span class="header3">Education</span>
	<blockquote>To become a restaurant manager, you must first work in a restaurant.  You might also need some college level courses.  Courses in business management, for example, could be very helpful.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $16,000 to $50,000+.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
