<span class="header1">Clerical/Administrative paired with Science/Mathematics (DH)</span>

<p>If your scored high in categories "D" and "E," you naturally understand that there are always ways to improve a situation.  You can probably handle several tasks at one time. People like you have made important contributions in business. You are an excellent thinker.  You are also likely to be a no-nonsense kind of person. You are creative and like to ask the question, "Why?" Because of this, you will look for new ways to do tasks.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree. In some of these jobs, it helps to have a Master's Degree or a Ph.D.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">DH Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Administrative Services</span><br /><br />
						<em>Medical Record Administrator<br /><br />
						Medical
							<ul>
								<li>Transcriptionist</li>
								<li>Assistant</li>
								<li>Secretary</li>
								<li>Receptionist</li>
							</ul>
						Pharmacist's Assistant<br /><br />
						Research Assistant<br /><br />
						Laboratory/Clinic Manager<br /><br />
						Medical Office Manager<br /><br />
						Human Service Worker<br /><br />
						Medical Coding Specialist</em>
					</td>
					<td width="33%">
						<span class="header2">Medical Services</span><br /><br />
						<em>Geriatric Assessment Coordinator<br /><br />
						Physician's Assistant<br /><br />
						Nurse Supervisor<br /><br />
						Research Analyst<br /><br />
						Medical Librarian<br /><br />
						Dental Hygienist<br /><br />
						Science Technician<br /><br />
						Laboratory Technologist<br /><br />
						Licensed Practical Nurse<br /><br />
						Outpatient Coordinator<br /><br />
						Home Health Aide</em>
					</td>
					<td width="33%">
						<span class="header2">Math Services</span><br /><br />
						<em>Accountant<br /><br />
						Bio-statistician<br /><br />
						Public Health Program Specialist<br /><br />
						Researcher<br /><br />
						Bookkeeper<br /><br />
						Purchasing Agent<br /><br />
						Computer
							<ul>
								<li>Systems Analyst</li>
								<li>Programmer</li>
						 </ul>
						Clerk
							<ul>
								<li>Accounting</li>
								<li>Statement</li>
								<li>Brokerage</li>
							</ul>
						Bank Teller</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">ADMINISTRATIVE SERVICES</span>
<p>If you work in an occupation in this field, you will work in a medical facility. This may be a hospital, clinic, or hospice, or it may be in a laboratory.</p>

<hr size="1" />

	<span class="header2">Medical Record Administrator</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a medical record administrator, you would be in charge of technicians and clerks. These individuals would collect, record, process, and preserve medical information. Doctors, nurses, and other health care providers would come to you to find information on their patients.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to do this job.  Your degree should be in medical record administration or health information management.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $40,000 to $118,000.</blockquote>

<hr size="1" />

	<span class="header2">Medical Record Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/DH/1374.jpg" width="100" height="100" border="0" alt="Medical Record Technician" />
	<span class="header3">Job Description</span>
	<blockquote>If you do not want to be a boss but you do want to work with patient information, you might become a medical record technician. In this job, you would collect, record, and process information on patients.  You would also preserve this information.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers want medical record technicians to have at least an Associate's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $80,000.</blockquote>

<hr size="1" />

	<span class="header2">Medical Assistant</span><br /><br />
	<img class="job_pic" src="/images/icons/DH/43148.jpg" width="100" height="100" border="0" alt="Medical Assistant" />
	<span class="header3">Job Description</span>
	<blockquote>As a medical assistant, you would help a nurse or doctor collect medical information from patients.  You would also help store these records and make sure they were accurate and easy to find. If you worked in a doctor's office, you would greet the patient.  You would also take his/her temperature and blood pressure, and listen to the patient's heart before the doctor or nurse sees him/her.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need to take special courses at a vocation school to become a medical assistant.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $17,000 to $35,000.</blockquote>

<hr size="1" />

<span class="header1">MEDICAL SERVICES</span>
<p>The occupations in this field help others who are in need.</p>

<hr size="1" />

	<span class="header2">Geriatric Assessment Coordinator</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>The word "geriatric" refers to the elderly.  As a geriatric assessment coordinator, you would work with a team of professionals. This group would look at the physical, emotional, and mental condition of an elderly patient.  Then they would develop a plan to help him/her. Part of your job would be to see that those providing the day-to-day care for the patient follow the plan.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree in social work.  You also need courses in gerontology (the study of human aging). Many people in this occupation have a Master's Degree or Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $30,000 to $60,000.</blockquote>

<hr size="1" />

	<span class="header2">Dental Hygienist</span><br /><br />
	<img class="job_pic" src="/images/icons/DH/C506012.jpg" width="100" height="100" border="0" alt="Dental Hygienist" />
	<span class="header3">Job Description</span>
	<blockquote>As a dental hygienist, you would teach your patients how to care for their teeth. You would clean your patient's teeth and take x-rays. Also, you would be an extra set of hands if the dentist needed help.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need an Associate's Degree in dental hygiene for this job.  Most vocational schools have dental hygiene programs.  So do most community colleges.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $35,000 to $80,000.</blockquote>

<hr size="1" />

	<span class="header2">Home Health Aide</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Demand for home health aides is growing because more sick and elderly people prefer to stay home to recover from illnesses. As a home health aide, you would help patients take care of their daily activities such as eating and bathing. You would also be in the home to talk and listen to the patient. This would help to keep the patient's spirits up.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A high school diploma is needed to be a home health aide.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges runs from $13,000 to $25,000.</blockquote>

<hr size="1" />

<span class="header1">MATH SERVICES</span>
<p>For many of the occupations in this field, you must have a background in computers. Also you would need math and reasoning abilities.</p>

<hr size="1" />

	<span class="header2">Computer Systems Analyst</span><br /><br />
	<img class="job_pic" src="/images/icons/DH/43166.jpg" width="100" height="100" border="0" alt="Computer Systems Analysis" />
	<span class="header3">Job Description</span>
	<blockquote>A computer systems analyst looks for ways to make the day-to-day tasks of a business easier. You would make suggestions on which computer systems would be best for the company. You would also help the company come up with new ways to route information.  To be a good computer systems analyst, you must know a lot about computers and be able to work with different types of people.  People who do this job are also called computer engineers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job. It is also helpful to have taken courses in computer science, technology, and programming.  Experience with computers will help you to get a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $39,000 to $93,000.</blockquote>

<hr size="1" />

	<span class="header2">Computer Programmer</span><br /><br />
	<img class="job_pic" src="/images/icons/DH/43290.jpg" width="100" height="100" border="0" alt="Computer Programmer" />
	<span class="header3">Job Description</span>
	<blockquote>Computers must be able to perform the right programs to be of use to a company.  Computers do not program themselves.  Instead, a person creates and installs computer programs.  As a computer programmer, you would give the computer certain instructions to follow. You would have to give the computer every instruction in detail.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $35,000 to $97,000.</blockquote>

<hr size="1" />

	<span class="header2">Bill & Account Collector</span><br /><br />
	<img class="job_pic" src="/images/icons/DH/43335.jpg" width="100" height="100" border="0" alt="Bill & Account Collector" />
	<span class="header3">Job Description</span>
	<blockquote>As a bill and account collector you would make sure that customers paid their overdue bills.  You might work for a collection agency, bank, or department store.  Your job would be to contact customers who had not paid their bills.  You would work with these customers to encourage them to pay their bill.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job.  Employers look for those who have experience in telemarketing.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $19,000 to $41,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
