<span class="header1">Protective/Military Service paired with Science/Mathematics (EH)</span>

<p>If your scored high in the "E" and "H" categories, you naturally understand that there are always ways to improve a situation.  People like you have helped to discover much information about the world. You are an excellent thinker and are probably a hands-on kind of person. You are creative and like physical challenges.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree. It is helpful to have a Master's Degree or Ph.D. if you hope to work in some of these occupations.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">EH Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Medical</span><br /><br />
						<em>Physician<br /><br />
						Military Medical Officer<br /><br />
						Sports Psychologist<br /><br />
						Exercise Physiologist<br /><br />
						Hospital Administrators<br /><br />
						Health Sciences Librarian<br /><br />
						Dietitian/Nutritionist<br /><br />
						Recreation Therapist<br /><br />
						Nurse<br /><br />
						Paramedic<br /><br />
						Technician
							<ul>
								<li>Medical
								<li>Operation Room
								<li>Military Cardiopulmonary</li>
							</ul></em>
					</td>
					<td width="33%">
						<span class="header2">Environmental</span><br /><br />
						<em>Archeologist<br /><br />
						Urban/Regional Planner<br /><br />
						Marine Biologist<br /><br />
						Engineer
							<ul>
								<li>Aerospace</li>
								<li>Environmental</li>
								<li>Nuclear</li>
							</ul>
						Environmental Risk Mgr<br /><br />
						Meteorologist<br /><br />
						Military
							<ul>
								<li>Land Surveyor</li>
								<li>Weather Observer</li>
								<li>Environmental Health Specialist</li>
							</ul>
						Land Surveyor<br /><br />
						Waste Management Technician</em>
					</td>
					<td width="33%">
						<span class="header2">Math/Analyst</span><br /><br />
						<em>Economist<br /><br />
						Mathematician<br /><br />
						Actuary<br /><br />
						Statistician<br /><br />
						Military
							<ul>
								<li>Strategist</li>
								<li>Financial Manager</li>
								<li>Intelligence Officer</li>
							</ul>
						Analyst
							<ul>
								<li>Budget</li>
								<li>Research</li>
								<li>Computer Systems</li>
							</ul>
						Computer Security Specialist<br /><br />
						Mapping Technician</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">MEDICAL</span>
<p>The occupations in this field require people who think very well.  If you enjoy mental challenges, the occupations in this field may be for you.</p>

<hr size="1" />

	<span class="header2">Podiatrist</span><br /><br />
	<img class="job_pic" src="/images/icons/EH/40210.jpg" width="100" height="100" border="0" alt="Podiatrist" />
	<span class="header3">Job Description</span>
	<blockquote>A podiatrist is a medical doctor who treats feet and lower legs. As a podiatrist you would work with patients to help correct problems in these two important areas of the body. You might even be a surgeon who operates when necessary. Your goal would be to help people walk better without pain or discomfort. Sports medicine is a branch of podiatry.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A doctor goes to school for a very long time. After receiving a Bachelor's Degree, you would enter medical school for several years. Internship and residency at a hospital is then required.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $62,000 to $150,000.</blockquote>

<hr size="1" />

	<span class="header2">Military Cardiopulmonary & EEG Technician</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a military cardiopulmonary & EEG technician, you would do medical tests on a patient's heart and lungs.  You would also take the patient's blood pressure. You would report your findings to the doctor. This occupation can be found in civilian hospitals as well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>On-the-job training is provided for those in the military.  You would need a high school diploma to be admitted to a training program.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>The occupations in this field give you a chance to work with and help protect the environment.</p>

<hr size="1" />

	<span class="header2">Urban Planner</span><br /><br />
	<img class="job_pic" src="/images/icons/EH/43137.jpg" width="100" height="100" border="0" alt="Urban Planner" />
	<span class="header3">Job Description</span>
	<blockquote>The word "urban" means "city." An urban planner works with agencies that are concerned with the growth of cities. As an urban planner, you would help cities grow in ways that are good for the environment and for people.  You might decide that a new street is needed or that old buildings should be repaired. You might work to ensure that water and sewage are available when new communities are developed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers require at least a Bachelor's Degree.  You will need a master's degree to advance in this field.  You also need to be creative and able to see the "big picture" when faced with a complex problem.  To see if urban issues interest you, volunteer with groups that work to make their city a better place to live.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Those with a Master's Degree can earn as much as $81,000 a year.</blockquote>

<hr size="1" />

	<span class="header2">Geotechnical Engineer</span><br /><br />
	<img class="job_pic" src="/images/icons/EH/1151.jpg" width="100" height="100" border="0" alt="Geotechnical Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>Tunnels through mountains are possible because geotechnical engineers have been hard at work. In this job, you would make and oversee plans for structures above or below ground. You might build tunnels through mountains or under bodies of water.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Master's Degree for this job.  A Ph.D. is valuable in the occupation if you want to be considered an expert. Interest in geology, the study of the earth's crust, and math ability is a must.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $40,000 to $90,000.</blockquote>

<hr size="1" />

	<span class="header2">Military Environmental Health Inspector</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a military environmental health specialist, you would make sure that the air, food, and water of a particular area are not dangerous. You might have one of several duties.  You might inspect food storage areas or military kitchens and dining halls. You might help to plan how to dispose of hazardous waste.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

<span class="header1">MATH/ANALYSIS</span>
<p>Those who work in occupations in this field are good with numbers. If you have a strong interest and ability in mathematics, you might find them interesting.</p>

<hr size="1" />

	<span class="header2">Actuary</span><br /><br />
	<img class="job_pic" src="/images/icons/EH/1287.jpg" width="100" height="100" border="0" alt="Actuary" />
	<span class="header3">Job Description</span>
	<blockquote>Most people have insurance in one form or another. They make payments called premiums. The person who decides how much each person pays is an actuary.  As an actuary, you would study statistics and set the price that the policyholder must pay.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in mathematics or statistics for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $39,000 to $137,000.</blockquote>

<hr size="1" />

	<span class="header2">Military Financial Manager</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>The military buys a large amount of equipment. The person who is responsible for the purchases is the military financial manager. In this job, you would decide the best use of the military's money. You would look for ways to buy large amounts of supplies and equipment. You might even plan, report, and budget the financial accounts.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in accounting or finance for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary you receive in the military is based on your rank, years of service, and job.</blockquote>

<hr size="1" />

	<span class="header2">Mapping Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/EH/43169.jpg" width="100" height="100" border="0" alt="Mapping Technician" />
	<span class="header3">Job Description</span>
	<blockquote>If you like the idea of working with maps, you might become a mapping technician. In this job, you would work as a team helping a surveyor to measure land. You would handle surveying equipment and instruments. These measure distance and altitude.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are 1, 2, and 3-year programs for those who want to study mapping technology.  Most employers want those who have graduated from a vocational program.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $18,000 to $49,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
