<span class="header1">Technology paired with Public Service (FG)</span>

<p>You will be a valued member of the work force. You are very community minded and prefer a "hands-on" approach. You want to make the world a better place through technology.  There are many occupations that require being able to work with people, machines, and tools.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree. It is helpful to have a Master's Degree or Ph.D. if you hope to work in some of these occupations.</p>

<p><strong>Here are some career possibilities for you to explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">FG Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Community Service</span><br /><br />
						<em>Inspector
							<ul>
								<li>Building</li>
								<li>Public Works</li>
							</ul>
						Land Surveyor<br /><br />
						Environmental Grass Roots Coordinator<br /><br />
						Police Officer<br /><br />
						Immigration Inspector<br /><br />
						Firefighter<br /><br />
						Recreation Worker<br /><br />
						Bus Driver<br /><br />
						Subway Operator</em>
					</td>
					<td width="33%">
						<span class="header2">Technical Service</span><br /><br />
						<em>Industrial Labor Relations Specialist<br /><br />
						Engineer
							<ul>
								<li>Civil</li>
								<li>Aircraft</li>
								<li>Structural</li>
							</ul>
						Hazardous Waste Management<br /><br />
						Plant Safety Specialist<br /><br />
						Equipment Specialist<br /><br />
						Tour Boat Captain<br /><br />
						Broadcast Technician<br /><br />
						Waste Management Technician</em>
					</td>
					<td width="33%">
						<span class="header2">Nature/Wildlife Service</span><br /><br />
						<em>Environmentalist<br /><br />
						Environmental Protection Specialist<br /><br />
						Historic Preservationist<br /><br />
						Park Ranger<br /><br />
						Recreation Administrator<br /><br />
						Nature Interpreter<br /><br />
						Zoo Keeper<br /><br />
						Recreations Site Developer<br /><br />
						Ranger Aide</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">COMMUNITY SERVICE</span>
<p>The occupations in this field are important. They provide services to the community.  They often use technology to provide these services. If you want to help your community and you like technology, these may be good occupations for you.</p>

<hr size="1" />

	<span class="header2">Building Inspector</span><br /><br />
	<img class="job_pic" src="/images/icons/FG/43241.jpg" width="100" height="100" border="0" alt="Building Inspector" />
	<span class="header3">Job Description</span>
	<blockquote>Building inspectors make sure that buildings are safe.  They work on-site, looking to see that builders follow safety codes set by the government. As a building inspector, you would make sure the building is built to stay strong. You might check, for example, that the roof could not collapse under snow. Or, you might make sure that there is an easy way to leave the building in case of a fire.  You would check the building for flaws and insist they be fixed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>It's good to have some college courses.  You will also receive on-the-job training.  Many inspectors begin as construction workers, electricians, plumbers, or pipe fitters. They go on to become managers and then inspectors.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A building inspector can make from $27,000 to $66,000 each year.</blockquote>

<hr size="1" />

	<span class="header2">Land Surveyor</span><br /><br />
	<img class="job_pic" src="/images/icons/FG/43169.jpg" width="100" height="100" border="0" alt="Land Surveyor" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy working outdoors with others, you might become a land surveyor. A land surveyor works with a team of two to four people to measure land and map out property boundaries.  Construction crews cannot start building until the land has been surveyed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You don't need a college degree to get a job as a surveyor, but those who have a degree earn more money and get promotions. Some vocational/technical schools offer programs for land surveying.  A part-time job with a surveying company could help you to see if you would like to become a land surveyor.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary range is $25,000 to $67,000.</blockquote>

<hr size="1" />

	<span class="header2">Firefighter</span><br /><br />
	<img class="job_pic" src="/images/icons/FG/1392.jpg" width="100" height="100" border="0" alt="Firefighter" />
	<span class="header3">Job Description</span>
	<blockquote>Firefighters control and put out fires that threaten lives or property.  As a firefighter, you would have to act quickly and responsibly in the middle of a fire or other emergency.  You would also learn CPR and first aid, so that you could help injured people. Fire fighting is dangerous and unpredictable.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You usually do not need a college degree to become a firefighter, but you must pass a written test and a test of physical strength.  Firefighters need to understand chemistry, as  certain chemical mixtures can cause a fire or explosion.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>An experienced firefighter can earn between $36,000 to $68,000.</blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY SERVICE</span>
<p>The occupations in this field combine an interest in the technical and in industry.</p>

<hr size="1" />

	<span class="header2">Industrial Labor Relations Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/FG/43222.jpg" width="100" height="100" border="0" alt="Industrial Labor Relations Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>As an industrial labor relations specialist, you would help senior managers and employees to agree on salaries and benefits. You would need to know the labor laws.  You would also need to have wage information.  You would need to understand economic principles as well. This would help you to know what was fair for both the company and its workers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You would need a Master's Degree for this job.  Often these specialists are lawyers who have added courses in industrial relations.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary is $52,000. Someone with a legal degree may earn more.</blockquote>

<hr size="1" />

	<span class="header2">Civil Engineer</span><br /><br />
	<img class="job_pic" src="/images/icons/FG/43243.jpg" width="100" height="100" border="0" alt="Civil Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>The word "civil" describes anything that has to do with a city. A civil engineer plans and builds structures that make our lives easier. As a civil engineer, you would plan and oversee the building of roads, bridges, and airports. You would also make sure that these structures were safe to use.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become a civil engineer. Many people enter into this field with a Master's Degree. Civil engineers can work in several specialty fields.  Each has its own education requirements.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Salaries range between $40,000 to $90,000.</blockquote>

<hr size="1" />

	<span class="header2">Recreation Worker</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>If you are outgoing and athletic, you might become a recreation worker. In this job, you would plan, organize, and direct recreational activities. You might work at playgrounds, parks, or community centers.  You might also work at theme parks, camps, and other recreational areas.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a high school diploma for this job.  Some employers look for workers who have post-high school courses in recreation.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $16,000 to $40,000. The salary will depend on the employee's education and experience.</blockquote>

<hr size="1" />

	<span class="header2">Broadcast Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/FG/1102.jpg" width="100" height="100" border="0" alt="Broadcast Technician" />
	<span class="header3">Job Description</span>
	<blockquote>A broadcast technician helps set up, repair, and operate the equipment used to send radio and television signals. Technicians operate cameras. They also create lighting effects and develop sound tracks. You might enjoy this job if you like working with equipment and do not mind getting your hands dirty.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need some post high school courses for this job.  Many technicians attend 2 or 3-year programs at technical institutions.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A technician can start a job at $20,000. You salary will depend on the amount of education and experience you have.</blockquote>

<hr size="1" />

<span class="header1">NATURE/WILDLIFE SERVICES</span>
<p>If you want to work outdoors and enjoy working with others, these occupations may be for you.</p>

<hr size="1" />

	<span class="header2">City Planner</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>City planners help cities develop areas that have become run down. Those who live within these areas have few ways of making money. As a city planner, you would work with the neighborhoods and businesses to improve these areas. You would also work to preserve parks and natural areas.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to work in the city-planning department. A Master's Degree is required if you want to be a city planner.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $33,000 to $81,000.</blockquote>

<hr size="1" />

	<span class="header2">Environmental Protection Specialist</span><br /><br />
	<img class="job_pic" src="/images/icons/FG/1285.jpg" width="100" height="100" border="0" alt="Environmental Protection Specialist" />
	<span class="header3">Job Description</span>
	<blockquote>An environmental protection specialist works for the government.  In this job, you would monitor companies and manufacturers.  Your job would be to see that they obeyed the regulations which keep the air and water clean.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in a technical field for this job.  You also need to have skills in accounting and statistics.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The starting salary of an environmental protection specialist is between $25,000 to $30,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
