<span class="header1">Technology paired with Science/Mathematics (FH)</span>

<p>If your scored high in the "F" and "H" categories, you are important to the future. People like you have discovered many things about the world. Your curiosity about how machines and tools work will be important to the work force. You are an excellent thinker.  You are also probably a hands-on kind of person. You are creative and have technical skills as well. There will be many opportunities for you.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree.  It is helpful to have a Master's Degree or Ph.D. to work in some of these occupations.</p>

<p><strong>Here are some career possibilities for you to explore.</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">FH Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Medical Sciences</span><br /><br />
						<em>Physicist
							<ul>
								<li>Biophysicist</li>
								<li>Health</li>
								<li>Medical</li>
								<li>Solid-state</li>
								<li>Nuclear</li>
							</ul>
						Physical Therapist<br /><br />
						Prosthetic Engineer<br /><br />
						Prosthetic Designer<br /><br />
						Physical Therapist Assistant<br /><br />
						Technician
							<ul>
								<li>Nuclear Medicine</li>
								<li>Surgical</li>
								<li>Radiological</li>
								<li>Clinical Laboratory</li>
								<li>Cardiovascular</li>
							</ul></em>
					</td>
					<td width="33%">
						<span class="header2">Environmental Sciences</span><br /><br />
						<em>City Planner<br /><br />
						Marine Biologist<br /><br />
						Geographer<br /><br />
						Industrial Hygienist<br /><br />
						Engineer
							<ul>
								<li>Electrical</li>
								<li>Industrial</li>
								<li>Mechanical</li>
							</ul>
						Environmentalist<br /><br />
						Meteorologist<br /><br />
						Climatologist<br /><br />
						Air Pollution Control Technician<br /><br />
						Land Surveyor<br /><br />
						Energy Management Technician</em>
					</td>
					<td width="33%">
						<span class="header2">Engineering Sciences</span><br /><br />
						<em>Engineer
							<ul>
								<li>Aeronautical</li>
								<li>Electrical</li>
								<li>Mechanical</li>
							</ul>
						Cartographer<br /><br />
						Aircraft Pilot<br /><br />
						Aviation Safety Inspector<br /><br />
						Inventor<br /><br />
						Researcher<br /><br />
						Boat Captain<br /><br />
						Technician
							<ul>
								<li>Mechanical Engineering</li>
								<li>Electrical Repair</li>
								<li>Cable Equipment</li>
							</ul>
						Craftsman
							<ul>
								<li>Stone Cutter</li>
								<li>Brick Mason</li>
							</ul></em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">ENVIRONMENTAL SCIENCES</span>
<p>The occupations in this field are very important to the earth's future. If you chose one of these occupations, you would research and explore the earth's limited resources.</p>

<hr size="1" />

	<span class="header2">Marine Biologist</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/43210.jpg" width="100" height="100" border="0" alt="Marine Biologist" />
	<span class="header3">Job Description</span>
	<blockquote>If you are curious about the ocean, you might become a marine biologist. In this job, you would study the plants and animals found in the ocean and on its floor. An important part of your job would be to protect marine animals and plants.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree for this job.  It is better to have a Master's Degree or Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $22,000 to $44,000.</blockquote>

<hr size="1" />

	<span class="header2">Industrial Hygienist</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/43153.jpg" width="100" height="100" border="0" alt="Industrial Hygienist" />
	<span class="header3">Job Description</span>
	<blockquote>As an industrial hygienist, you would research how humans react to paints, cleaners, and other products. You would use the results to decide the amounts of these products that are safe in a work environment. You would develop regulations based on these amounts.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree.  This degree can be in chemistry, biology, or engineering. You also need to have master's level courses in industrial hygiene for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary depends on the company's ability to pay and the industrial hygienist's education and experience.</blockquote>

<hr size="1" />

	<span class="header2">Energy Management Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/43163.jpg" width="100" height="100" border="0" alt="Energy Management Technician" />
	<span class="header3">Job Description</span>
	<blockquote>The cost of fuel is very high.  Big industries must make sure that the fuel their machinery uses is used efficiently.  An energy management technician makes sure that fuel is not wasted. In this job, you  would work to improve the energy efficiency of machinery.  You would use your knowledge of machines and electronics to reduce the amount of fuel wasted by a machine.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Employers prefer those who have taken some college level courses.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $30,000+.</blockquote>

<hr size="1" />

<span class="header1">ENGINEERING TECHNOLOGIES</span>
<p>To work in this field, you need to be a logical thinker. You also need to have technical skills.</p>

<hr size="1" />

	<span class="header2">Aircraft Pilot</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/43047.jpg" width="100" height="100" border="0" alt="Aircraft Pilot">
	<span class="header3">Job Description</span>
	<blockquote>An aircraft pilot flies an airplane or helicopter.  In this job, you would  be responsible for the safety of the aircraft as well as any passengers on board.  You must have perfect vision, hearing, and coordination to be a pilot.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Most commercial pilots have a college degree and have a pilot's license.  Many pilots start out as military pilots.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $41,000 to $200,000.</blockquote>

<hr size="1" />

	<span class="header2">Mechanical Engineer</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/C0777_50.jpg" width="100" height="100" border="0" alt="Mechanical Engineer" />
	<span class="header3">Job Description</span>
	<blockquote>Have you ever wondered who came up with or improved the machines that we use? Mechanical engineers have improved many of the machines that we use.  In this job, you would create, research, and test mechanical systems. Air conditioners and cars are among the machines you might find ways to improve.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in engineering to become a mechanical engineer. You also need very good math and science skills.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $43,000 to $96,000.</blockquote>

<hr size="1" />

<span class="header1">MEDICAL SCIENCE</span>
<p>These jobs are concerned with the practice of medicine.  They also involve the technology that doctors and scientists use.</p>

<hr size="1" />

	<span class="header2">Physical Therapist</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>A physical therapist helps a patient recover from a disability, injury, or illness.  As a physical therapist, you would help the patient with exercises.  You would teach him/her to do daily tasks such as getting in and out of bed or the bathtub.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's or Master's Degree from a physical therapist program for this job.  There is a lot of competition for physical therapist jobs.  It will be valuable to have experience helping people and as much education as possible.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $40,000 to $86,000+.</blockquote>

<hr size="1" />

	<span class="header2">Nuclear Medicine Technologist</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/C0571_07.jpg" width="100" height="100" border="0" alt="Nuclear Medicine Technologist" />
	<span class="header3">Job Description</span>
	<blockquote>As a nuclear medicine technologist, you would give patients a form of drug called radiopharmaceuticals.  This drug causes organs and tissues to show up on photographic film.  It is used to help make diagnoses.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A nuclear medicine technologist must complete a nuclear medicine program.  These programs run from one to four years.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average yearly salary range is $36,000 to $68,000.</blockquote>

<hr size="1" />

	<span class="header2">Clinical Laboratory Technician</span><br /><br />
	<img class="job_pic" src="/images/icons/FH/43149.jpg" width="100" height="100" border="0" alt="Clinical Laboratory Technician" />
	<span class="header3">Job Description</span>
	<blockquote>If you would like to work in a laboratory, you might become a clinical laboratory technician.  In this job, you would use microscopes to look for bacteria and other microorganisms in cells.  You would report your findings to doctors so they can treat their patients properly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>There are different levels of clinical laboratory technicians.  Some jobs require more education and some require less.  For most positions, you must have at least an Associate's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $19,000 to $44,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
