<span class="header1">Technology paired with Social/Helping (FI)</span>

<p>Your high scores in "F" and "I" show that you have characteristics that are useful to people.  You will be highly valued in the work force.  In addition, you  have the potential to make a real difference in the world.  You have an interest in technology, the outdoors, and other people.  Your strengths will be useful in many different occupations.</p>
<p>Most occupations in this pairing require at least a Bachelor's Degree.  It is helpful to have a Master's Degree or Ph.D. if you hope to work in some of these occupations.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">FI Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="33%">
						<span class="header2">Education & Instruction</span><br /><br />
						<em>College Professor<br /><br />
						Teacher
							<ul>
								<li>Continuing Education</li>
								<li>Environmental Science</li>
								<li>Computer Science</li>
								<li>Shop</li>
								<li>Physical Education</li>
							</ul>
						Sports & Fitness Trainer<br /><br />
						Coach<br /><br />
						Instructor
							<ul>
								<li>Aerobics Exercise</li>
								<li>Martial Arts</li>
								<li>Police Academy</li>
								<li>Survival Training</li>
								<li>Trade School</li>
							</ul></em>
					</td>
					<td width="33%">
						<span class="header2">Social Helping</span><br /><br />
						<em>Public Health Administrator<br /><br />
						Environmental Lawyer<br /><br />
						Social Worker<br /><br />
						Nurse<br /><br />
						Recreational Therapist<br /><br />
						Dental Hygienist<br /><br />
						Paramedic<br /><br />
						Police Officer<br /><br />
						Military Police<br /><br />
						Flight Attendant<br /><br />
						Barber</em>
					</td>
					<td width="33%">
						<span class="header2">Technology Helping</span><br /><br />
						<em>Veterinarian<br /><br />
						Medical Equipment Designer<br /><br />
						Park Ranger<br /><br />
						Firefighter<br /><br />
						Military Teletype Operator<br /><br />
						Computer Trainer<br /><br />
						Craftsperson
							<ul>
								<li>Plumber</li>
								<li>Carpenter</li>
								<li>Heating</li>
								<li>Air Conditioning</li>
							</ul>
						Appliance Repair Technician<br /><br />
						Electronics Technician</em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">EDUCATION & INSTRUCTION</span>
<p>Teaching is an excellent way to share the advances made in technology and to help other people.</p>

<hr size="1" />

	<span class="header2">Physical Education Teacher</span><br /><br />
	<img class="job_pic" src="/images/icons/FI/1076.jpg" width="100" height="100" border="0" alt="Physical Education Teacher" />
	<span class="header3">Job Description</span>
	<blockquote>If your favorite subject is PE, you might want to consider becoming a physical education teacher.  In this job, you would use your knowledge of health and physical fitness to help students be healthier.  You would make lesson plans to teach games, sports, and exercises.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A Bachelor's Degree is needed to become a teacher.  Many states prefer teachers who have Master's Degrees.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $40,000.</blockquote>

<hr size="1" />

	<span class="header2">Aerobic Exercise Instructor</span><br /><br />
	<img class="job_pic" src="/images/icons/FI/C1207_25.jpg" width="100" height="100" border="0" alt="Aerobic Exercise Instructor" />
	<span class="header3">Job Description</span>
	<blockquote>If physical fitness is very important to you, you might become an aerobic exercise instructor.  In this job, you would help people exercise properly.  You would teach the correct way to do exercises.  You might also lead exercise classes.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You must meet certification requirements to become an aerobic exercise instructor.  You must also participate in a training program where you would learn correct exercise techniques.  You will also learn the basics of first aid.  In many states, you must pass a written exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $12,000 to $25,000.</blockquote>

<hr size="1" />

	<span class="header2">Personal Trainer</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>Sometimes people want someone to help them become physically fit, but do not want to be in a class or visit a gym. These people hire a personal trainer.  As a personal trainer, you would work with one to two people at a time. You would plan an exercise and diet program for each client. You would recommend healthy eating habits and teach appropriate exercise techniques.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in a health-related field for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>Personal trainers usually work for hourly wages.  The average hourly wage ranges from $30 to $35.</blockquote>

<hr size="1" />

<span class="header1">SOCIAL HELPING</span>
<p>The occupations in this field require people who are active, helpful, and outgoing.</p>

<hr size="1" />

	<span class="header2">Public Health Administrator</span><br /><br />
	<img class="job_pic" src="/images/icons/FI/C506006.jpg" width="100" height="100" border="0" alt="Public Health Administrator" />
	<span class="header3">Job Description</span>
	<blockquote>Because many illnesses can be passed on to others, it is important to have people who help to guard against widespread illnesses in towns and counties. This person is a public health administrator. In this job, you would oversee the health care programs of a county or city.  You would make sure that the hospitals, clinics, and health departments follow the rules set by the state or local government.</blockquote>
	<span class="header3">Education</span>
	<blockquote>All people who work as health care administrators must have a master's degree. Some health care administrators have degrees in public health.  Others have a degree in public administration.  Still others have a degree in business administration.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $51,000.</blockquote>

<hr size="1" />

	<span class="header2">Recreation Therapist</span><br /><br />
	<img class="job_pic" src="/images/icons/FI/18272.jpg" width="100" height="100" border="0" alt="Recreation Therapist" />
	<span class="header3">Job Description</span>
	<blockquote>If you want to make a difference in people's lives, you might become a recreation therapist. Recreation therapists work as members of a medical team. They use nature, dance, art, games, and music to help patients as they go through a serious illness or trauma.  They help them to regain self-confidence as they are getting well.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to work in a medical facility. Some employers want certified therapists only. To be certified you need to pass the required state or board exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>An average yearly salary for a recreation therapist is about $30,000.</blockquote>

<hr size="1" />

	<span class="header2">Barber or Cosmetologist</span><br /><br />
	<img class="job_pic" src="/images/icons/FI/43008.jpg" width="100" height="100" border="0" alt="Barber or Cosmetologist" />
	<span class="header3">Job Description</span>
	<blockquote>If you were a barber or cosmetologist, you would cut, shampoo, and color hair.  You would also provide other grooming services.  This is a social job which means that you would be working with people. To enjoy this job, you must have good people skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>Barbers and cosmetologists must have a state license.  They must pass a written test. They must also demonstrate that they can cut hair.  Vocational tech schools and cosmetology colleges offer programs for those who want to enter this occupation.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary depends on the reputation of the barber or cosmetologist. It also depends on how much time is spent working.  Barbers and cosmetologist may earn hourly minimum wage.  They may also make a very comfortable living.</blockquote>

<hr size="1" />

<span class="header1">TECHNOLOGY HELPING</span>
<p>The occupations in this field allow you to use technology to help animals and people.</p>

<hr size="1" />

	<span class="header2">Veterinarian</span><br /><br />
	<img class="job_pic" src="/images/icons/FI/43132.jpg" width="100" height="100" border="0" alt="Veterinarian" />
	<span class="header3">Job Description</span>
	<blockquote>Veterinarians care for sick and injured animals.  If you love animals and are good at science, you might become a veterinarian. In this job, you would diagnose what was wrong with animals.  You would vaccinate them against disease.  And you would tell people how to care for their animals.  If you like looking for new ways to treat animals and control diseases, you could do research in this area.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A veterinarian must have a license.  He/she must also have a Doctor of Veterinary Medicine degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary range is from $24,0000 to $60,000+. The number of animals you treat and your experience as a veterinarian will determine what you earn.</blockquote>

<hr size="1" />

	<span class="header2">Computer Trainer</span><br /><br />
	<img class="job_pic" src="/images/icons/FI/1378.jpg" width="100" height="100" border="0" alt="Computer Trainer" />
	<span class="header3">Job Description</span>
	<blockquote>A computer trainer teaches others to use a computer.  As a computer trainer, you would need technical knowledge of the computer and know how to teach.  Some computer trainers work for one company.  Others have their own computer training business.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need to have some college courses for this job.  Also, you need to know about many different kinds of computers and software packages.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $40,000.</blockquote>

<hr size="1" />

	<span class="header2">Appliance Repair Technician</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>When the machines we use in our homes break down, we call an appliance repair technician. In this job, you would fix appliances found in the home.  You might work on washing machines, clothes dryers, and refrigerators.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma.  You also need training in appliance repair for this job.  Vocational technology schools offer training programs.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $25,000.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
