<span class="header1">Science/Mathematics paired with Social/Helping (HI)</span>

<p>Your high scores in "H" and "I" show that you are headed for a rewarding career. You will be highly valued in the work force. You have the potential to make a real difference in the world. You will help others by gathering information and doing research. You are a naturally caring person, and you have a scientific mind which will serve you well.</p>
<p>Most occupations in this pairing require at least a Bachelor's degree. It is helpful to have a Master's Degree or Ph.D. if you hope to work in some of these occupations.</p>

<p><strong>Here are some career possibilities for you to explore:</strong></p>

<table width="100%" cellpadding="20" cellspacing="0" border="0">
	<tr>
		<td></td>
		<td bgcolor="#FFF9D8" align="center" height="50">
			<span class="header1">HI Career Possibilities</span><br /><br />
			<table bgcolor="0" cellpadding="0" cellspacing="0" width="100%">
				<tr bgcolor="#FFF9D8">
					<td width="33%" align="left"><strong>More People Oriented</strong></td>
					<td width="33%" align="center"><strong>&larr;&rarr;</strong></td>
					<td width="33%" align="right"><strong>More Technical Oriented</strong></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#D3EEF5" align="center" width="50">
			<table border="0" cellpadding="0" cellspacing="0" height="400">
				<tr align="center" height="33%"><td><strong>More<br />&uarr;</strong></td></tr>
				<tr align="center" height="33%"><td><strong>Education<br />or<br />Training<br />Required</strong></td></tr>
				<tr align="center" height="33%"><td><strong>&darr;<br />Less</strong></td></tr>
			</table>
		</td>
		<td valign="top">
			<table border="0" cellspacing="3" cellpadding="0" width="100%">
				<tr valign="top">
					<td width="20%">
						<span class="header2">Education</span><br /><br />
						<em>College Professor<br /><br />
						Education Administrator<br /><br />
						Teacher
							<ul>
								<li>Adult Education</li>
								<li>Science</li>
								<li>Math</li>
								<li>Biology</li>
								<li>Computer</li>
								<li>Physics</li>
								<li>English</li>
							</ul>
						Clergy
							<ul>
								<li>Priest</li>
								<li>Rabbi</li>
								<li>Minister</li>
							</ul>
						Librarian<br /><br />
						Teacher's Aide</em>
					</td>
					<td width="20%">
						<span class="header2">Social Service</span><br /><br />
						<em>Psychologist<br /><br />
						Health Services Administrator<br /><br />
						Economist<br /><br />
						Social Worker
							<ul>
								<li>Mental Health</li>
								<li>School</li>
								<li>Geriatric</li>
							</ul>
						Psychotherapist<br /><br />
						Counselor
							<ul>
								<li>School</li>
								<li>Career</li>
								<li>Drugs & Alcohol</li>
							</ul>
						Researcher<br /><br />
						Psychiatric Technician</em>
					</td>
					<td width="20%">
						<span class="header2">Medicine</span><br /><br />
						<em>Physician<br /><br />
						Dentist<br /><br />
						Veterinarian<br /><br />
						Pharmacist<br /><br />
						Physical Therapist<br /><br />
						Nurse<br /><br />
						Dietitian<br /><br />
						Dental Hygienist<br /><br />
						Lab/Medical Technologist<br /><br />
						Dental/Veterinary Assistant<br /><br />
						Dental/Veterinary Technician<br /><br />
						Home Health Aide</em>
					</td>
					<td width="20%">
						<span class="header2">Environment</span><br /><br />
						<em>Earth Scientist
							<ul>
								<li>Geologist</li>
								<li>Oceanographer</li>
								<li>Ecologist</li>
								<li>Meteorologist</li>
							</ul>
						Zoologist<br /><br />
						Engineer
							<ul>
								<li>Environmental</li>
								<li>Chemical</li>
							</ul>
						Astronomer<br /><br />
						Forester<br /><br />
						Parks & Recreation Manager<br /><br />
						Zoo Keeper<br /><br />
						Meteorological Technician<br /><br />
						Research Assistant</em>
					</td>
					<td width="20%">
						<span class="header2">Mathematics</span><br /><br />
						<em>Social Scientist
							<ul>
								<li>Anthropologist</li>
								<li>Sociologist</li>
							</ul>
						Accountant<br /><br />
						Statistician<br /><br />
						Computer Systems Analyst<br /><br />
						Computer Trainer<br /><br />
						Puzzle Inventor<br /><br />
						Research Assistant<br /><br />
						Clerk
							<ul>
								<li>Statistics</li>
								<li>Accounting</li>
							</ul></em>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<hr size="1" />

<span class="header1">EDUCATION</span>
<p>The occupations in this field combine the best of learning and sharing knowledge.</p>

<hr size="1" />

	<span class="header2">Educator</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>An educator can be a teacher or principal.  He/she can be a librarian or coach.  He/she can also be another professional who works within the educational system. As an educator, you would help others by increasing their knowledge and skills.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to become an educator.  Many states prefer to have educators who have Master's Degrees.  For administrative positions a Master's Degree is required. Many administrators have their Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $200,000.</blockquote>

<hr size="1" />

	<span class="header2">Clergy</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/43007.jpg" width="100" height="100" border="0" alt="Clergy" />
	<span class="header3">Job Description</span>
	<blockquote>The word "clergy" refers to someone who works as a minister, rabbi, or priest. If you were a member of the clergy, you would run religious activities. You would perform weddings, preside at funerals, and be of help to those who needed it.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to enter this occupation.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary varies. It depends on the religious affiliation.  It also depends on the what the religious community can afford to pay.</blockquote>

<hr size="1" />

	<span class="header2">Teacher's Aide</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/43319.jpg" width="100" height="100" border="0" alt="Teacher's Aide" />
	<span class="header3">Job Description</span>
	<blockquote>Not everyone who works at a school is a teacher.  The job of a teacher's aide is similar to that of a teacher.  As a teacher's aide, you would help a teacher care for his/her students, grade papers, perform clerical duties, and prepare instructional materials.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a college degree or at least some higher-level education courses for this job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average wage is about $8.29 to $8.77 an hour.</blockquote>

<hr size="1" />

<span class="header1">SOCIAL/MENTAL</span>
<p>The occupations in this field require the employee to gather and use information to help others.</p>

<hr size="1" />

	<span class="header2">Child Welfare Social Worker</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/1212.jpg" width="100" height="100" border="0" alt="Child Welfare Social Worker" />
	<span class="header3">Job Description</span>
	<blockquote>Social work is all about helping others. As a social worker in child welfare, you would help children who are struggling with problems.  These problems may be dealing with a new school, a sick parent, drug problems, or a disability.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree to find an entry-level position. To be promoted, you must have a Master's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $44,000.</blockquote>

<hr size="1" />

	<span class="header2">Occupational Social Worker</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/7240.jpg" width="100" height="100" border="0" alt="Occupational Social Worker" />
	<span class="header3">Job Description</span>
	<blockquote>An occupational social worker usually works in the personnel department of a large company.  Your job would be to help employees to cope with the stress of working. To do this, you would listen closely to the employee.  Then you would work with him/her to get help or solve a problem.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become an entry-level social worker. Those with more responsible positions must have a Master's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $44,000.</blockquote>

<hr size="1" />

	<span class="header2">Human Services Social Worker</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>As a human services social worker, you would work under a doctor, nurse, or psychiatrist. You would help these health care professionals find ways to help the patient. For example, you might find a way for the patient to get to his/her doctor's appointment. Your duties would depend on what the patient needed.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become an entry-level social worker. Those with more responsible positions must have a Master's Degree.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $15,000 to $44,000.</blockquote>

<hr size="1" />

<span class="header1">MEDICINE</span>
<p>The occupations in the field of medicine allow people to study science and to help others.</p>

<hr size="1" />

	<span class="header2">Physician</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/1152.jpg" width="100" height="100" border="0" alt="Physician" />
	<span class="header3">Job Description</span>
	<blockquote>A physician is a medical doctor.  As a physician you would care for patients who were ill.  You would examine patients and perform diagnostic tests to diagnose and treat illnesses and injuries.</blockquote>
	<span class="header3">Education</span>
	<blockquote>It takes 10 years to become a doctor.  You need a Bachelor's Degree.  In addition, you must graduate from medical school.  An internship and residency in a hospital are also required.  You must be licensed by the state.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $110,000 and $240,000.</blockquote>

<hr size="1" />

	<span class="header2">Pharmacist</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/C506087.jpg" width="100" height="100" border="0" alt="Pharmacist" />
	<span class="header3">Job Description</span>
	<blockquote>If you were a pharmacist, you would fill prescriptions given to patients by doctors. Patients and doctors would depend on you to give them information on side effects and correct dosage.</blockquote>
	<span class="header3">Education</span>
	<blockquote>A pharmacist must do graduate work in pharmaceuticals. A pharmacist must be licensed by the state.  A state exam must be passed and an internship served in order to become licensed.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges between $25,000 to $55,000+.</blockquote>

<hr size="1" />

	<span class="header2">Dietitian</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/C577054.jpg" width="100" height="100" border="0" alt="Dietitian" />
	<span class="header3">Job Description</span>
	<blockquote>As a dietitian, you would make suggestions for good nutrition at hospitals, schools, and other institutions.  You might create menus,  make sure that food was prepared in a healthy way.  You might even go into a patient's home to plan appropriate meals. You would also try to educate people on how to eat properly.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree in nutrition or a health related subject for this job.  You must also complete an internship under an experienced dietitian.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $20,000 to $36,000.</blockquote>

<hr size="1" />

<span class="header1">ENVIRONMENT</span>
<p>The occupations in this field need scientists who want to preserve the earth's resources.</p>

<hr size="1" />

	<span class="header2">Marine Biologist</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/43210.jpg" width="100" height="100" border="0" alt="Marine Biologist" />
	<span class="header3">Job Description</span>
	<blockquote>If you are curious about the ocean, you might become a marine biologist. In this job, you would study the plants and animals found in the ocean and on its floor. An important part of your job would be to protect marine animals and plants.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bchelor's Degree for this job.  It is better to have a Master's Degree or Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $22,000 to $44,000.</blockquote>

<hr size="1" />

	<span class="header2">Ecologist</span><br /><br />
	<span class="header3">Job Description</span>
	<blockquote>An ecologist is a scientist who studies the effect that people and animals have on the earth's environment.  If you are concerned about harm to the environment and have good computer skills, this may be a good job for you.  As an environmentalist, you would conduct field studies.  You would also work in laboratories. Computer skills are very important in this job.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become an ecologist.  Most employers look for a Master's Degree and experience.  To get experience, volunteer with groups who work to protect the environment.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $22,000 to $28,000. Those with a master's degree and experience can earn $60,000.</blockquote>

<hr size="1" />

	<span class="header2">Oceanographer</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/C511037.jpg" width="100" height="100" border="0" alt="Oceanographer" />
	<span class="header3">Job Description</span>
	<blockquote>Oceanographers are scientists who study the ocean. As an oceanographer, you might study the ocean's movements.  Or, you might study the plants and animals that live in the ocean. The oceans still hold many mysteries.  As an oceanographer, you would search for what is unknown.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree to become a technician or laboratory assistant.  You must have a Master's or Ph.D. to be an oceanographer. In this area, the more education you have, the better.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary range is $22,000 to $40,000. The salary depends on the position you have and how much education you have.</blockquote>

<hr size="1" />

<span class="header1">MATHEMATICS</span>
<p>The occupations in this field need those who like working with numbers.</p>

<hr size="1" />

	<span class="header2">Statistician</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/C1618_03.jpg" width="100" height="100" border="0" alt="Statistician" />
	<span class="header3">Job Description</span>
	<blockquote>As a statistician, you would gather information in numbers. For example, Major League baseball players have their batting averages determined by statisticians.  If you worked for a business, you would look at certain numbers to see how well the company was doing.  Is it in good shape? Numbers give the statistician the answer.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need at least a Bachelor's Degree in statistics or mathematics for this job.  To get a promotion, you must have a Master's Degree or a Ph.D.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The average salary for a statistician is $50,000.</blockquote>

<hr size="1" />

	<span class="header2">Accountant</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/1287.jpg" width="100" height="100" border="0" alt="Accountant" />
	<span class="header3">Job Description</span>
	<blockquote>If you enjoy working with numbers, you might become an accountant. An accountant is responsible for helping a company make money. You might advise the company to buy or sell stock.  You might prepare its taxes.  You would also keep careful records so that it was possible to tell how much money the company made and where this money was spent.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a Bachelor's Degree for an entry level job.  Most accountants are CPA's (Certified Public Accountants). To become a CPA, you must have a Bachelor's Degree. You must also pass a written exam.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>A CPA makes $27,000 to $60,000+ per year.</blockquote>

<hr size="1" />

	<span class="header2">Computer Systems Analyst</span><br /><br />
	<img class="job_pic" src="/images/icons/HI/43166.jpg" width="100" height="100" border="0" alt="Computer Systems Analyst" />
	<span class="header3">Job Description</span>
	<blockquote>A computer systems analyst looks for ways to make theday-to-day tasks of a business easier. You would make suggestions on which computer systems would be best for the company. You would also show the company new ways to route information.  To be a good computer systems analyst, you must know a lot about computers and be able to work with different types of people.  People who do this job are also called computer engineers.</blockquote>
	<span class="header3">Education</span>
	<blockquote>You need a high school diploma for this job. It is also helpful to have taken courses in computer science, technology and programming.  Experience with computers will help you to get a job.</blockquote>
	<span class="header3">Salary</span>
	<blockquote>The yearly salary ranges from $22,000 to $65,000+.</blockquote>

<hr size="1" />

<p><strong>Looking for more information on specific careers? Visit the <em>Occupational Outlook Handbook</em>:</strong> <a href="http://www.bls.gov/oco">www.bls.gov/oco</a></p>

<p><strong>You may also want to try the <em>Occupational Information Network</em> Web site:</strong> <a href="http://online.onetcenter.org/gen_search_page">online.onetcenter.org/gen_search_page</a></p>
