Your answers to the <i><B>Interest Inventory</i></B> 
indicate what you like and dislike and the kind of places in which 
you work best. This report will help you better understand what your 
results mean. The report includes information that you should find 
valuable as you plan your future, including descriptions of several 
sample occupations that may be appropriate for you based on your 
career interests. You should consider this information as you make 
future course selections and career decisions. 
<BR>
<P>The <i><B>Careers and Occupations Guide</i></B> should not be the 
only resource you use, however. There are many additional resources, 
including the <i><B>Occupational Outlook Handbook </i></B><A 
HREF="http://www.bls.gov/oco"> www.bls.gov/oco</A> published by the 
U.S.Department of Labor. 
You may also want to try the <I><B>Occupational Information 
Network</I></B> Web site: 
<A HREF="http://online.onetcenter.org/gen_search_page"> 
online.onetcenter.org/gen_search_page</A>.
<c> For more information, see your school Guidance 
Counselor.
<BR>
<P>The chart in the <i><B>Career Direction</i></B> and 
<i><B>FUTURE</B>FOCUS</i> booklets will give you a brief idea of what 
your scores mean. Look at your answer sheet 
for the three highest scores and the letter of the alphabet that goes 
with each of the scores. The information on the chart next to each 
letter will help you understand your scores. 
<P>
This Internet report pairs your highest scores to help you better 
understand your unique personality and to give you an idea of what 
occupations might suit you best. If you entered three high scores, 
the computer pairs all three to create three reports. 
Remember, you are just exploring right now and you can look at as 
many of the possibilities as you want.
<P>
Several occupations are described in this report, along with their 
education requirements and average salaries. If possible, you should 
print this report for future reference. You also might want to share 
the information with your parents, your teacher, or a friend. This 
information will help you make good decisions as you plan for life 
in school and beyond.
<P>
Before you begin, it will help to understand some words that will be 
used many times in this report. 
<OL id="glossary">
<LI> <B>Career</B> - describes the type of work a 
person has done or will do in the future. For example, 
your teacher has a career in Education. This means that your teacher 
works where people learn and his/her duties deal with making sure 
others learn.<P>

<LI> <B>Occupation</B> - describes the exact work that 
someone does. For example, many people work in your school in 
different occupations. There are <B>teachers,</B> <B>counselors,</B> 
<B>cafeteria workers,</B> <B>custodians,</B> and 
the <B>principal</B>.<P>
  
<LI> <B>Job</B> - "job" is another word for occupation and it also 
describes where a person goes to work everyday. For example, a 
person may have a <B>career</B> in education, with 
the <B>occupation</B> of a teacher as his/her <B>job</B> at your 
school.<P>

<LI> <B>Technical and Trade Schools</B> - these schools teach 
specific 
skills such as auto mechanics, secretarial skills, 
dental hygiene, etc. Upon completion (usually two years or less), the 
school awards a Certificate of Completion or Diploma that is specific 
to the trade/skill studied.<P>

<LI> <B>Two-Year Junior or Community Colleges</B> - these colleges 
offer general education opportunities and award completion with an 
Associate's Degree. You can take freshman and sophomore 
level classes at a Junior College and then transfer to a four-year 
institution. <P>
  
<LI> <B>Four-Year College or University</B> - these are schools where 
students can earn a Bachelor's degree and higher level degrees such 
as a Master's or Ph.D.<P>

<LI> <B>Associate's Degree</B> - awarded for completing an initial 
two 
year program of college work. <P>

<LI> <B>Bachelor's Degree</B> - awarded for completing a college 
program of at least four years. <P>
  
<LI> <B>Master's Degree</B> - awarded for completing a one or two 
year 
program of study beyond a Bachelor's degree.<P>
  
<LI> <B>Doctorate Degree (Ph.D.)</B> - awarded for completing a 
program of 
study that is often lengthy and that requires some type of original 
research, as well as written and oral examinations.<P>
</OL>
<P>
Are you ready to explore your future career possibilities? Let's get 
started!









